### ISSUE TITLE
nativescript project fails to build if nativescript-plugin-firebase added

### ISSUE THREAD

**Issue by mcorbridge** [EddyVerbruggen/nativescript-plugin-firebase#10]
I have shown that a project cloned from git (samples-Groceries) builds and runs correctly on a connected device.
If I now add  **nativescript-plugin-firebase**, the project fails to build.

* What went wrong:
Execution failed for task ':processNativescriptfloatingactionbuttonNativescript-geolocationNativescript-plugin-firebaseNativescript-telerik-uiDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'c:\Users\Mike\AppData\Local\Android\android-sdk\build-tools\23.0.1\aapt.exe'' finished with non-zero exit value 1   

I have noticed a similar error occurring when I attempt to combine nativescript-geolocation and nativescript-google-sdk.

Removal of **nativescript-plugin-firebase** permits a successful build of the project.

***************************************************************************************************************
System information:
{ procInfo: 'nativescript/1.5.2',
  platform: 'win32',
  os: 'Windows 10 Pro 6.3.10586',
  shell: 'C:\\WINDOWS\\system32\\cmd.exe',
  dotNetVer: '4.6.01038',
  procArch: 'x64',
  nodeVer: 'v4.2.6',
  npmVer: '2.14.12',
  javaVer: '1.8.0',
  nodeGypVer: null,
  xcodeVer: null,
  itunesInstalled: true,
  cocoapodVer: null,
  adbVer: 'Android Debug Bridge version 1.0.32',
  androidInstalled: true,
  monoVer: null,
  gitVer: '2.7.0.windows.1',
  gradleVer: null,
  javacVersion: '1.8.0_72' }

**Comment by tstpierre** [comment]
Same issue:

:processNativescript-phoneNativescript-plugin-firebaseNativescript-telerik-uiDebugResources FAILED

**Comment by tstpierre** [comment]
Updated to latest 23.x build tools....  this dependency builds fine now.

Got another issue, but not sure its related to this plugin.

```
platforms/android/build/intermediates/exploded-aar/com.android.support/appcompat-v7/23.1.1/jars/classes.jar
	at com.telerik.metadata.ClassRepo.cacheJarFile(ClassRepo.java:21)
	at com.telerik.metadata.Builder.build(Builder.java:38)
	at com.telerik.metadata.Generator.main(Generator.java:44)
:buildMetadata FAILED

**Comment by tstpierre** [comment]
May have spoke to soon...  doing:

```
tns platform remove android
tns build android
```

Produces the same error again:
```Execution failed for task ':processNativescript-phoneNativescript-plugin-firebaseNativescript-telerik-uiDebugResources'.```

**Comment by tstpierre** [comment]
This wasn't a plugin issue after all.

`rm -rf node_modules/`
`tns platform remove ios`
`tns platform remove android`
`tns build ios`
`tns build android`

That essentially cleans the workspace and builds from scratch.  I also updated JDK to 8u73 and verified I had extras and API 17 and up platform SDK.

**Comment by kpmrafeeq** [comment]
Any update, I am still getting error Log info:

:generateNativescriptfloatingactionbuttonNativescript-telerik-uiDebugAssets UP-TO-DATE
:mergeNativescriptfloatingactionbuttonNativescript-telerik-uiDebugAssets UP-TO-DATE
:generateNativescriptfloatingactionbuttonNativescript-telerik-uiDebugResValues UP-TO-DATE
:generateNativescriptfloatingactionbuttonNativescript-telerik-uiDebugResources UP-TO-DATE
:mergeNativescriptfloatingactionbuttonNativescript-telerik-uiDebugResources UP-TO-DATE
:processNativescriptfloatingactionbuttonNativescript-telerik-uiDebugManifest UP-TO-DATE
**:processNativescriptfloatingactionbuttonNativescript-telerik-uiDebugResources FAILED**

**Comment by vzhen** [comment]
Any update?   this is so annoying as i have to tns platform remove android and readd back everytime this error comes out

**Comment by EddyVerbruggen** [comment]
@vzhen What I'm reading here is folks are not having plugin related issues but rather an issue with lingering build artifacts in NativeScript - it also seems to happen with other plugins.

That being siad: what's the error you're seeing and the exact reproduction path? I won't offer help if you're simply asking for an update or pinging me on Slack.

**Comment by vzhen** [comment]
ok, i'm trying @tstpierre solution to see if it fix or not.

> rm -rf node_modules/
tns platform remove ios
tns platform remove android
tns build ios
tns build android

**Comment by hvadotnarola** [comment]
`Execution failed for task ':buildMetadata'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1`
Got this error after 
`rm -rf node_modules/
tns platform remove ios
tns platform remove android
tns build ios
tns build android
`
