### ISSUE TITLE
cloud messaging not showing notification with angular

### ISSUE THREAD

**Issue by tahir-jamil** [EddyVerbruggen/nativescript-plugin-firebase#1001]
I am following the documentation for cloud message and we have firebase notifications to show notification in ios but its not working 
https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/MESSAGING.md#interactive-notifications-ios-only-for-now

this is the home component in which i am using firebase 
`import { Component, OnInit } from '@angular/core';
import { RouterExtensions } from 'nativescript-angular/router';
import * as platformModule from 'tns-core-modules/platform';
import { UserDataService } from '../userData.service';
import { Router, NavigationExtras } from '@angular/router';
import { Message } from "nativescript-plugin-firebase/firebase";
const firebase = require("nativescript-plugin-firebase");
import { messaging } from "nativescript-plugin-firebase/messaging";

@Component({
  selector: 'ns-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
  moduleId: module.id
})
export class HomeComponent implements OnInit {

  imgWidth
  imgHeight
  model;
  constructor(private routerExtensions: RouterExtensions, private userService: UserDataService, private router: Router) {
    this.model = new messaging.PushNotificationModel();
    this.model.iosSettings = new messaging.IosPushSettings();
  }

  ngOnInit() {
    let deviceHeight: number = platformModule.screen.mainScreen.heightDIPs;
    let deviceWidth: number = platformModule.screen.mainScreen.widthDIPs;

    this.imgWidth = deviceWidth * 0.35;
    this.imgHeight = deviceHeight * 0.6;

    firebase.init({
      // showNotificationsWhenInForeground: true,
      onMessageReceivedCallback: (message: Message) => {
        console.log(`Title: ${message.title}`);
        console.log(`Body: ${message.body}`);
        
        // if (message.title) {
        //   this.userService.localNotification(message);
        // }

        this.model.iosSettings.badge = false;
        this.model.iosSettings.alert = true;

        this.model.iosSettings.interactiveSettings = new messaging.IosInteractivePushSettings();
        this.model.iosSettings.interactiveSettings.actions = [
          {
            identifier: "OPEN_ACTION",
            title: "Open the app (if closed)",
            options: messaging.IosInteractiveNotificationActionOptions.foreground
          }
          // {
          //   identifier: "AUTH",
          //   title: "Open the app, but only if device is not locked with a passcode",
          //   options: messaging.IosInteractiveNotificationActionOptions.foreground | messaging.IosInteractiveNotificationActionOptions.authenticationRequired
          // },
          // {
          //   identifier: "INPUT_ACTION",
          //   title: "Tap to reply without opening the app",
          //   type: "input",
          //   submitLabel: "Fire!",
          //   placeholder: "Load the gun..."
          // },
          // {
          //   identifier: "INPUT_ACTION",
          //   title: "Tap to reply and open the app",
          //   options: messaging.IosInteractiveNotificationActionOptions.foreground,
          //   type: "input",
          //   submitLabel: "OK, send it",
          //   placeholder: "Type here, baby!"
          // },
          // {
          //   identifier: "DELETE_ACTION",
          //   title: "Delete without opening the app",
          //   options: messaging.IosInteractiveNotificationActionOptions.destructive
          // }
        ];

        // this.model.iosSettings.interactiveSettings.categories = [{
        //   identifier: "GENERAL"
        // }];

        // this.model.onNotificationActionTakenCallback = (actionIdentifier: string, message: any) => {
        //   console.log(`onNotificationActionTakenCallback fired! Message: ${JSON.stringify(message)}, Action taken: ${actionIdentifier}`);
        // };

        firebase.registerForInteractivePush(this.model);
      }
    }).then(
      () => {
        console.log("firebase.init done");
      },
      error => {
        console.log(`firebase.init eßrror: ${error}`);
      }
    );

    firebase.getCurrentPushToken().then((token: string) => {
      // may be null if not known yet
      console.log(`Current push token: ${token}`);
    });

    firebase.subscribeToTopic("news").then(() => console.log("Subscribed to topic"));
  }

  privacy() {
    this.routerExtensions.navigate(['/privacy'], {
      transition: {
        name: 'slideLeft',
        curve: 'linear'
      }
    });
  }

  gotoContact() {

    let navigationExtras: NavigationExtras = {
      queryParams: {
        "title": "Web",
        "url": "https://seefarma.it/chat/"
      }
    };
    this.router.navigate(["webview"], navigationExtras);

    // utils.openUrl("https://seefarma.it/chat/");
  }

  gotoWebsite() {
    // utils.openUrl("https://seefarma.it/promozioni");
    let navigationExtras: NavigationExtras = {
      queryParams: {
        "title": "Web",
        "url": "https://seefarma.it/promozioni"
      }
    };
    this.router.navigate(["webview"], navigationExtras);
  }

  gotoPromo() {
    // utils.openUrl("https://seefarma.it/promo-app/");
    let navigationExtras: NavigationExtras = {
      queryParams: {
        "title": "Web",
        "url": "https://seefarma.it/promo-app/"
      }
    };
    this.router.navigate(["webview"], navigationExtras);
  }

  gotoTab(args, id) {
    this.userService.onchangeIndex(id);
    this.routerExtensions.navigate([args], {
      transition: {
        name: 'fade',
        curve: 'linear'
      }
    });
  }

}

`

their is no error in execution what i am doing wrong please help

**Comment by EddyVerbruggen** [comment]
Please share a repo instead of snippets.

**Comment by tahir-jamil** [comment]
https://github.com/tahir-jamil/seefarma

**Comment by tahir-jamil** [comment]
this is my repo i am working on

**Comment by EddyVerbruggen** [comment]
Let's discuss there.

**Comment by tahir-jamil** [comment]
ok
