### ISSUE TITLE
No Firestore snapshots received after app has been offline for some time

### ISSUE THREAD

**Issue by jnorkus** [EddyVerbruggen/nativescript-plugin-firebase#1002]
To reproduce:
1. Subscribe to a Firestore document snapshot
2. Go to airplane mode for 5min
3. Disable airplane mode
4. Make changes in Firestore
Result: changes are not picked up by the snapshot callback any more

Haven't tested on iOS, but it is easy to reproduce on Android.

Not sure if this is how Firestore SDKs work or this is a bug in the plugin? Haven't found anything about tracking connection state in the official docs.

**Comment by EddyVerbruggen** [comment]
You may want to check plugin version 7.4.0 because I saw some mentions in the SDK changelog about Firestore and coming out of offline mode that have now been integrated into the plugin. Closing for now.
