### ISSUE TITLE
Error: Tried to serialize an unsupported type: java.util.HashMap

### ISSUE THREAD

**Issue by larssn** [EddyVerbruggen/nativescript-plugin-firebase#1004]
Hey

Ran into this yesterday (on Android). It happened a few times after a project rebuild.
I did some Googling, and it appears to be related to `markingmode: none` in NS (maybe releated: https://github.com/NativeScript/android-runtime/issues/887).

I'll leave it here for now.

```
JS: PLEASE REPORT THIS AT https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues: Tried to serialize an unsupported type: java.util.HashMap, error: Error: com.tns.NativeScriptException: Attempt to use cleared object reference id=1500
JS:     com.tns.Runtime.getJavaObjectByID(Runtime.java:923)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:983)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:967)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:959)
JS:     com.tns.gen.com.google.firebase.firestore.EventListener.onEvent(EventListener.java:17)
JS:     com.google.firebase.firestore.Query.zza(com.google.firebase:firebase-firestore@@17.1.1:882)
JS:     com.google.firebase.firestore.zzl.onEvent(com.google.firebase:firebase-firestore@@17.1.1)
JS:     com.google.firebase.firestore.obfuscated.zzgp.zza(com.google.firebase:firebase-firestore@@17.1.1:42)
JS:     com.g...
```

**Comment by EddyVerbruggen** [comment]
Hmm, don't think this plugin can help that. I've changed the log message a bit.

**Comment by edusperoni** [comment]
If this error came from this plugin (and not from user code passed to it), we should probably make sure this never happens: https://github.com/NativeScript/android-runtime/issues/887#issuecomment-348164990

`makingMode: none` is basically mandatory in angular applications otherwise we get very poor performance

**Comment by EddyVerbruggen** [comment]
@edusperoni I know, I use it as well in my Angular apps. But it's not clear to me if in this case anything actually breaks in the app or that it is a mere glitch. Still, the plugin can't help it either way.
