### ISSUE TITLE
Exit Code 65 on iOS

### ISSUE THREAD

**Issue by packytagliaferro** [EddyVerbruggen/nativescript-plugin-firebase#1005]
I am getting a failed error on iOS simulator after installing your plugin. Before I could build fine. After I deleted the plugin and all the hooks it built fine again. Here are the steps to reproduce:

**Error:**

```
/Users/patricktagliaferro/Library/Developer/Xcode/DerivedData/aGLocker-glfyhrxpmknejwbgsjczoboxbdqa/Build/Intermediates.noindex/aGLocker.build/Debug-iphonesimulator/aGLocker.build/Script-FF7D0F60A10A410FBDC7C1C6.sh: line 2: /Users/patricktagliaferro/Apps/aG: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code
note: Using new build systemnote: Planning buildnote: Constructing build description
** BUILD FAILED **

Unable to apply changes on device: 6D3BBE18-C71B-4D85-BBFF-25D9FA9CBD5B. Error is: Command xcodebuild failed with exit code 65.
Executing after-watch hook from /Users/patricktagliaferro/Apps/aG Locker/hooks/after-watch/nativescript-dev-webpack.js
Stopping webpack watch
```

**Versions:**

- TNS: 5.0.0-2018-10-10-12456
- Plugin: just installed so 7.3.0

**What I did:**

- Installed Plugin
- Added google files to respective folders
- added entitlements file
- updated Pods
- ran `tns build ios --bundle`

**What I tried:**

- removed and added iOS platform

**Comment by EddyVerbruggen** [comment]
What's your `firebase.nativescript.json`? Or even better: can I look at a repo? And does it matter if you use tns 4 or 5?

**Comment by EddyVerbruggen** [comment]
Please bump the plugin to 7.4.0 (just released). I've tested most features on iOS and Android, with NativeScript 4 and 5 and have not run into this issue.

If you still have the issue after upgrading (clean your platform folder as well!) then please share a repo I can look at.
