### ISSUE TITLE
pluginfirebaseinfo not found

### ISSUE THREAD

**Issue by shinde-sagar** [EddyVerbruggen/nativescript-plugin-firebase#1006]
Hello All,

When I run my application using **tns run android** always getting error 
> nativescript-plugin-firebase: E:\project\mobile application\ngasceapp\platforms\android\.pluginfirebaseinfo not found, forcing prepare!

How we can overcome from these issue.

Thanks,
Sagar Shinde

**Comment by EddyVerbruggen** [comment]
No idea. That's new.. Share a repo and perhaps someone can help.

**Comment by Ahineya** [comment]
Hi.

I've just faced the same issue.

It wasn't like this before. I've used to correctly work with my project, but this issue suddenly happened, and now my project is always rebuilding itself.

I'm using the Firebase Plugin v5.1.8 with NativeScript v4.2 on a latest MacOS.

I have removed node_modules and platforms/android, and ran "tns debug android".

Here is the part of log after successful install of the app on the emulator:

> NativeScript Debugger started #
> To start debugging, open the following URL in Chrome:
> chrome-devtools://devtools/bundled/inspector.html?experiments=true&ws=localhost:40000
> 
> Successfully synced application com.[REMOVED] on device 192.168.56.101:5555.
> Executing before-checkForChanges hook from /Users/pyevsehnieiev/projects/[REMOVED]/hooks/before-checkForChanges/firebase-copy-google-services.js
> nativescript-plugin-firebase: /Users/pyevsehnieiev/projects/[REMOVED]/platforms/android/.pluginfirebaseinfo not found, forcing prepare!
> nativescript-plugin-firebase: running release build or change in environment detected, forcing prepare!
> 

Do you have any ideas of what might happened?
