### ISSUE TITLE
Access Custom Claims On The Client - getIdTokenResult method non excistent

### ISSUE THREAD

**Issue by Ianc22** [EddyVerbruggen/nativescript-plugin-firebase#1008]
Hi, first o fall thanks a lot for this useful plugin.

I've been hitting my head agains the wall trying to implement accesing the custom claims from the 
client. Not sure if I've overlooked something?

Here is a link to the implementation required. 
https://firebase.google.com/docs/auth/admin/custom-claims#access_custom_claims_on_the_client

Any assistance would be greatly appreciated.

**Comment by Ianc22** [comment]
Thanks for your quick reply.

In case you are not aware of Custom Claims here's a rundown.

If you scroll to the top of the page that I linked you'll see instructions on how to create custom claims for the user.

admin.auth().setCustomUserClaims(uid, {admin: true}).then(() => {
// The new custom claims will propagate to the user's ID token the
// next time a new one is issued.
});

These claims then get included with the user ID token, either when logging back in or when the token is refreshed.

You can then access these claims off of the JWT that gets returned from Firebase (your User object basically needs to accommodate for that also as currently, the cast doesn't include it.

Other than that, on the client you can call firebase.auth().currentUser.getIdTokenResult() (as shown below) to get access to those claims...

firebase.auth().currentUser.getIdTokenResult()
  .then((idTokenResult) => {
     // Confirm the user is an Admin.
     if (!!idTokenResult.claims.admin) {
       // Show admin UI.
       showAdminUI();
     } else {
       // Show regular user UI.
       showRegularUI();
     }
  })
  .catch((error) => {
    console.log(error);
  });
  
So two things here, as mentioned on login, you need to handle the additional claims and then also I need the getIdTokenResult() function so that I can then access those custom claims on the client.
  
  Hope that all makes sense?
  
  Thanks in advance,
  
  Ian

**Comment by Ianc22** [comment]
Here's what the token looks like when checking it on the server:

context.auth.token ==>  { 
  admin: true,
  coach: true,
  aud: 'inspire-219716',
  auth_time: 1541236732,
  user_id: 'qWmXEePRkAeKvS6NSJF8j2Wz1',
  sub: 'qWmXEePRkAeKn96NSJF8j2Wz1',
  iat: 1541236732,
  exp: 1541240332,
  email: 'user@nativescript.org',
  email_verified: false,
  firebase: 
   { identities: { email: [Object] },
     sign_in_provider: 'password' },
  uid: 'qWmXERkAeKn9mvSJF8j2Wz1' }

As you can see here the Admin and Coach added to the object. They get lost in the cast to User

**Comment by Ianc22** [comment]
Here's what the token looks like when checking it on the server:

context.auth.token ==>  { 
  admin: true,
  coach: true,
  aud: 'blob-2749239',
  auth_time: 1541236732,
  user_id: 'qWmXEePRkAeKvS6NSJF8j2Wz1',
  sub: 'qWmXEePRkAeKn96NSJF8j2Wz1',
  iat: 1541236732,
  exp: 1541240332,
  email: 'user@nativescript.org',
  email_verified: false,
  firebase: 
   { identities: { email: [Object] },
     sign_in_provider: 'password' },
  uid: 'qWmXERkAeKn9mvSJF8j2Wz1' }

As you can see here the Admin and Coach added to the object. They get lost in the cast to User

**Comment by Ianc22** [comment]
Hey Eddy,

So I've been thinking. I don't think there's a need to amend the User object. We just need to implement the following two features, as mentioned, and we should be all set!

**to access the custom claims** - getIdTokenResult returns the current ID token result object
https://firebase.google.com/docs/reference/js/firebase.User#getIdTokenResult
`firebase.auth().currentUser.getIdTokenResult()`

And then:

**to force refresh to pick up the latest custom claims changes.** - getIdToken returns the current token
https://firebase.google.com/docs/reference/js/firebase.User#getIdToken
`currentUser.getIdToken(true)`

As you'll see you can use either method to force a token refresh by passing true as the value for the forceRefresh parameter. 

An example here (anchor on the initial linked page above)
https://firebase.google.com/docs/auth/admin/custom-claims#defining_roles_via_firebase_functions_on_user_creation

Thanks again!

**Comment by Ianc22** [comment]
I think I may have found it!

**firebase.android.ts:668** `firebase.getAuthToken = arg => { ... };`

**firebase.android.ts:676** `resolve(getTokenResult.getToken());`

need to add `getTokenResult.getClaims()' here somewhere, maybe with the resolve? WIP... lol

**Comment by Ianc22** [comment]
Hey Eddy, so I have come across your implementation of the first requirement of **getIdToken(forceRefresh):string**.

It's implemented in your `firebase.getAuthToken()` method:

https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/AUTHENTICATION.md#getauthtoken

So I've gone ahead and added `firebase.getAuthTokenClaims()` method. Calling `user.getIdTokenResult(arg.forceRefresh)` instead of `user.getIdToken(arg.forceRefresh)`.

Alas, I'm getting an error: `getIdTokenResult is not a function`...

```
firebase.getAuthTokenClaims = (arg): Promise<object> => {
  return new Promise((resolve, reject) => {
    try {
      const firebaseAuth = com.google.firebase.auth.FirebaseAuth.getInstance();
      const user = firebaseAuth.getCurrentUser();
      if (user !== null) {
        const onSuccessListener = new com.google.android.gms.tasks.OnSuccessListener({
          onSuccess: getTokenResult => {
            resolve({
              token: getTokenResult.getToken(),
              claims: getTokenResult.getClaims()
            });
          }
        });

        const onFailureListener = new com.google.android.gms.tasks.OnFailureListener({
          onFailure: exception => {
            reject({ exception });
          }
        });

        user.getIdTokenResult(arg.forceRefresh)
          .addOnSuccessListener(onSuccessListener)
          .addOnFailureListener(onFailureListener);


      } else {
        reject({ error: "Log in first" });
      }
    } catch (ex) {
      console.log("Error in firebase.getIdTokenResult: " + ex);
      reject(ex);
    }
  });
};
```

**Comment by EddyVerbruggen** [comment]
@Ianc22 There's no `getIdTokenResult` on that class. Check the source here: https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseUser

**Comment by Ianc22** [comment]
I'm back! After some digging I found that the Java SDK doesn't expose the `getIdTokenResult()` function. The `getIdToken()` actually returns the claims. You can access them via the getTokenResult.getClaims() method.

This, however, needs to be cast like you are doing with the User loginResult.

I just updated firebase.getAuthToken() to return an object instead of a string as you can see below:

```
firebase.getAuthToken = (arg): Promise<object> => {
  return new Promise((resolve, reject) => {
    try {
      const firebaseAuth = com.google.firebase.auth.FirebaseAuth.getInstance();
      const user = firebaseAuth.getCurrentUser();
      if (user !== null) {
        const onSuccessListener = new com.google.android.gms.tasks.OnSuccessListener({
          onSuccess: getTokenResult => {
            resolve({
              token: getTokenResult.getToken(),
              **claims: getTokenResult.getClaims()**
          });
          }
        });

        const onFailureListener = new com.google.android.gms.tasks.OnFailureListener({
          onFailure: exception => {
            reject(exception);
          }
        });

        user.getIdToken(arg.forceRefresh)
            .addOnSuccessListener(onSuccessListener)
            .addOnFailureListener(onFailureListener);

      } else {
        reject("Log in first");
      }
    } catch (ex) {
      console.log("Error in firebase.getAuthToken: " + ex);
      reject(ex);
    }
  });
};
```

I can then access the claims in this manner : `idTokenResult.claims.get('coach')`. Example below

```
        firebasePlugin.getAuthToken({
            forceRefresh: true
        })
            .then((idTokenResult: any) => {
                const { claims } = idTokenResult;
                debugger;
                if (claims.get('coach')) {
                    console.log('User is a coach');
                    // showCoachUI();
                } else {
                    console.log('User is an athlete');
                    // showAthleteUI();
                }
            })
            .catch((errorMessage: string) => {
                alert({
                    title: 'An Error Occurred',
                    message: errorMessage,
                    okButtonText: 'OK, thanks'
                });
            });
```

Not as clean as `idTokenResult.claims.coach` but it works! Maybe you can refactor it when you get time :)

**Comment by Ianc22** [comment]
I'm back! After some digging I found that the Java SDK doesn't expose the `getIdTokenResult()` function. The `getIdToken()` actually returns the claims. You can access them via the getTokenResult.getClaims() method.

This, however, needs to be cast like you are doing with the User loginResult.

I just updated firebase.getAuthToken() to return an object instead of a string as you can see below:

```
firebase.getAuthToken = (arg): Promise<object> => {
  return new Promise((resolve, reject) => {
    try {
      const firebaseAuth = com.google.firebase.auth.FirebaseAuth.getInstance();
      const user = firebaseAuth.getCurrentUser();
      if (user !== null) {
        const onSuccessListener = new com.google.android.gms.tasks.OnSuccessListener({
          onSuccess: getTokenResult => {
            resolve({
              token: getTokenResult.getToken(),
              **claims: getTokenResult.getClaims()**
          });
          }
        });

        const onFailureListener = new com.google.android.gms.tasks.OnFailureListener({
          onFailure: exception => {
            reject(exception);
          }
        });

        user.getIdToken(arg.forceRefresh)
            .addOnSuccessListener(onSuccessListener)
            .addOnFailureListener(onFailureListener);

      } else {
        reject("Log in first");
      }
    } catch (ex) {
      console.log("Error in firebase.getAuthToken: " + ex);
      reject(ex);
    }
  });
};
```

I can then access the claims in this manner : `idTokenResult.claims.get('coach')`. Example below

```
firebasePlugin.getAuthToken({
            forceRefresh: true
        })
            .then((idTokenResult: any) => {
                const { claims } = idTokenResult;
                debugger;
                if (claims.get('coach')) {
                    console.log('User is a coach');
                    // showCoachUI();
                } else {
                    console.log('User is an athlete');
                    // showAthleteUI();
                }
            })
            .catch((errorMessage: string) => {
                alert({
                    title: 'An Error Occurred',
                    message: errorMessage,
                    okButtonText: 'OK, thanks'
                });
            });
```

Not as clean as `idTokenResult.claims.coach` but it works! Maybe you can refactor it when you get time :)

**Comment by Ianc22** [comment]
> Here's what the token looks like when checking it on the server:
> 
> context.auth.token ==> {
> admin: true,
> coach: true,
> aud: 'blob-2749239',
> auth_time: 1541236732,
> user_id: 'qWmXEePRkAeKvS6NSJF8j2Wz1',
> sub: 'qWmXEePRkAeKn96NSJF8j2Wz1',
> iat: 1541236732,
> exp: 1541240332,
> email: '[user@nativescript.org](mailto:user@nativescript.org)',
> email_verified: false,
> firebase:
> { identities: { email: [Object] },
> sign_in_provider: 'password' },
> uid: 'qWmXERkAeKn9mvSJF8j2Wz1' }
> 
> As you can see here the Admin and Coach added to the object. They get lost in the cast to User

btw, `getTokenResult.getClaims()` returns the above... So looks like all the user claims instead of just the custom claims (admin and coach respectively)

**Comment by Ianc22** [comment]
> @Ianc22 There's no `getIdTokenResult` on that class. Check the source here: https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseUser

Yeah thanks for that, I'd discovered it already by the time you hinted! lol

**Comment by Ianc22** [comment]
Hey Eddy,

I was a little hasty in closing this issue as IOS still needs sorting.

Also, will you be updating the package? Maybe instead of refactoring the getAuthToken method create an additional one to handle returning the custom claims?

**Comment by EddyVerbruggen** [comment]
Yeah, leave this open as a feature request.

We don't need a new method in case we can add the claims while maintaining backward.

**Comment by Ianc22** [comment]
Yeah it's required this end. Gonna have to see if I can get the IOS sorted, can't test it this end though... Guess I can use NativeScript Sidekick ;)

The reason I suggested a new method was for backward compatibility as the interface `export function getAuthToken(option: GetAuthTokenOptions): Promise<string>` needs to be `export function getAuthToken(option: GetAuthTokenOptions): Promise<object>`

I suppose you could refactor `getAuthToken(args)` and pass back either the token **string** or the **object** returning the token string and claims but then you'd still need to change the signature as pointed out.

In the meantime, I guess we manually need to maintain the package in node_modules?

**Comment by Ianc22** [comment]
Hi Eddy,

I just had a quick look at the IOS implementation. I found this method `getIDTokenResultForcingRefreshCompletion`. 
I can't find any reference to it but I assume this is the one we're after as it's the Result.

I'm gonna give it a go and let you know.

**Comment by fernandezmjm** [comment]
hi @Ianc22  @EddyVerbruggen ,

I'm also trying to use this function and it's for both iOS and android. 

Sorry to ask but are there any updates with this?

**Comment by Ianc22** [comment]
Hi @fernandezmjm. So sorry about the late reply. I glimpsed the email last week and then forgot to get back to it. Been a little manic. You got it sorted?

We have resolved to update Android:

firebase.android.js
firebase_common_1.firebase.getAuthToken.
     var onSuccessListener = new com.google.android.gms.tasks.OnSuccessListener({
                    onSuccess: function (getTokenResult) {
                        resolve({
                            token: getTokenResult.getToken(),
                            claims: getTokenResult.getClaims()
                        });
                    }
                });

And iOS...

firebase.ios.js
firebase_common_1.firebase.getAuthToken and replace function call
user.getIDTokenForcingRefreshCompletion(arg.forceRefresh, onCompletion); with
user.getIDTokenResultForcingRefreshCompletion(arg.forceRefresh, onCompletion)

We have to replace that every time we do an `npm i` of course so not ideal but no way around it unless you've come up with something?

**Comment by fernandezmjm** [comment]
hi @Ianc22 
I just used what was stock by the plugin since everyone in the team needs to do it every time the plugin is installed. However, we sorted to using a decoder for the token just to get the claims. 

@EddyVerbruggen 
Thank you for the response also, maybe plugin update would be a great help as well as for the future users.

**Comment by Ianc22** [comment]
> @Ianc22 you mean there's no way to integrate with the plugin's code in this repo?

Hey Eddy,

Not from what I can see, no. You have the 
     getAuthToken()

method (which I've pasted above, with an ammended 
    resolve({
        token: getTokenResult.getToken(),
        claims: getTokenResult.getClaims()
     });
There plugin only returns the token. We're also after the claims... Have a look here https://firebase.google.com/docs/reference/android/com/google/firebase/auth/GetTokenResult

**Comment by Ianc22** [comment]
> hi @Ianc22
> I just used what was stock by the plugin since everyone in the team needs to do it every time the plugin is installed. However, we sorted to using a decoder for the token just to get the claims.
> 
> @EddyVerbruggen
> Thank you for the response also, maybe plugin update would be a great help as well as for the future users.

hmm yeah we're not actually using the claims now as it stands....

**Comment by EddyVerbruggen** [comment]
I meant: instead of amending the local copy of the plugin, I'd be happy to merge a PR that adds this feature so you no longer have to 😉

**Comment by Ianc22** [comment]
> I meant: instead of amending the local copy of the plugin, I'd be happy to merge a PR that adds this feature so you no longer have to 😉

That would be awesome!! Thanks @EddyVerbruggen :) 👍

**Comment by Ianc22** [comment]
Currently, we're amending the following:
For Android:
firebase.android.js: firebase_common_1.firebase.getAuthToken resolve with the following:

     resolve({
               token: getTokenResult.getToken(),
               claims: getTokenResult.getClaims()
      });

and for iOS
firebase.ios.js: firebase.ios.js replace
    user.getIDTokenForcingRefreshCompletion(arg.forceRefresh, onCompletion
with
    user.getIDTokenForcingRefreshCompletion(arg.forceRefresh, onCompletion

You may want to add a new method, either way you get the idea ;)

**Comment by CaptainDingle** [comment]
@Ianc22  - For me, changing to:

`user.getIDTokenResultForcingRefreshCompletion`

is still returning just the token as a string on iOS. It is not returning the Result object that we normally get in the web API that has the custom claims. It seems to be working for you - did I miss something?

**Comment by EddyVerbruggen** [comment]
Thanks for the PR! @CaptainDingle I've streamlined the API a little, so there's no difference on iOS and Android anymore when 'getting' the claims. See https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/9751c7fa1218ab8a76115b04d834192ff08c9ba1/docs/AUTHENTICATION.md#getauthtoken

Note that the signature of this method has slightly changed consequently, but as I'm about to cut the 8.0.0 release I don't think it's too bad.

**Comment by CaptainDingle** [comment]
Thanks so much @EddyVerbruggen, your way is much more streamlined. Thanks to @Ianc22 for pointing me in the right direction originally. Thank you for this firebase plugin and your fingerprint and secure storage plugins. I appreciate your work very much and we will try to contribute whenever we can in any way. Thanks again.

**Comment by Ianc22** [comment]
Thanks @EddyVerbruggen for sorting this out. Funnily, the timing couldn't have been better. This morning got to a point where we need the claims for rules on the storage so the commented out code requesting the claims are now re-included. Will be doing some testing ;) And I concur with @CaptainDingle, all much appreciated!

**Comment by DscCalabar** [comment]
Hello,  I'm new to firebase. I'm working on a web app and I need to manage user state from one page to another,  when I sign-up or login from a form, I get the user state on that page but if I navigate to another page I loss the user*the user will no longer be logged in*, please can I get help,  thanks

**Comment by SashankDash** [comment]
@Ianc22 i am trying to implement the same thing using react but the issue is the custom claims does not update itself till 1 hr so. what I want is once the user logs in and sends the token to my node back end server it should get the custom claims. but I am not able to find the solution.
this is how I am storing and keeping the token in the cookies.
----------------------------------------
export function setCookies(){
    const cookies = new Cookies();

    return firebase.auth().onIdTokenChanged(async user => {
        if (user) {
            const token = await user.getIdToken(true);
            cookies.set('access_token', token, { path: '/', maxAge: 60 * 60});
        }
    });
also tried with  
 return firebase.auth().currentUser.getIdTokenResult(true)
  .then(async (idTokenResult) => { console.log(idTokenResult)}
but not able to get the token to save in cookies I know its a object but I have no idea how to retrieve this.
