### ISSUE TITLE
Version 7.3 conflict with nativescript-globalevents

### ISSUE THREAD

**Issue by mspusta78** [EddyVerbruggen/nativescript-plugin-firebase#1009]
After I upgraded to version 7.3 I get the following

CONSOLE LOG file:///app/tns_modules/nativescript-platform-css/node_modules/nativescript-globalevents/globalevents.js:28:16: NativeScript-globalevents auto disabled; functionality appears to be already present!

I am using 

"nativescript-globalevents": "^1.2.2"
"nativescript-platform-css": "^1.6.6"

and in my app.js I have

require("nativescript-platform-css");

Is there a fix for this?

Martin

**Comment by EddyVerbruggen** [comment]
That message (..already present) is not logged by this plugin. I think this is not related to this plugin, or at least I have never seen this.

**Comment by mspusta78** [comment]
Thanks for your reply.

I verified that setting the

"invites" : true

in the firebase.nativescript.json

is what will trigger this error. When I set this flag to "false" all is
working well.

**Comment by EddyVerbruggen** [comment]
It's [this line](https://github.com/NathanaelA/nativescript-globalevents/blob/6e3010bd51ce9d56c2640a02247ebcc6dd30e82b/src/globalevents.js#L27) that logs the message - I think you'll need to dig deeper yourself because I don't use the 'nativescript-globalevents' plugin myself.
