### ISSUE TITLE
The Android Gradle plugin supports only Crashlytics (Nativescript 5.0)

### ISSUE THREAD

**Issue by NeriCodec** [EddyVerbruggen/nativescript-plugin-firebase#1010]
The Android Gradle plugin supports only Crashlytics Gradle plugin version 1.25.4 and higher.

**Comment by janossuta** [comment]
I had the same issue but after I updated the plugin to the latest version the error message disappeared.
"nativescript-plugin-firebase": "^7.3.0"

**Comment by NeriCodec** [comment]
@janossuta got test now !!

**Comment by NeriCodec** [comment]
Nice !!!

**Comment by alangiovannipc** [comment]
Thanks so much , I resolved the problem, Updating the version .
