### ISSUE TITLE
Non-firebase messaging and google-services.json

### ISSUE THREAD

**Issue by raulvc** [EddyVerbruggen/nativescript-plugin-firebase#1014]
The gradle build is struck due to needing a google-services.json, however as stated by the docs page I could use this plugin for a third party push service (I'm using amazon's SNS)

So I'm confused, is it mandatory for me to register a firebase app despite not using it so that this plugin will work?

**Comment by EddyVerbruggen** [comment]
Doesn't Amazon SNS build upon FCM for message delivery, in which case you'll need a Firebase configuration anyway (and consequently that `google-services.json` file)?

**Comment by raulvc** [comment]
I believe you're right Eddy :) sorry!
