### ISSUE TITLE
 'firebase.init error: TypeError: Cannot read property \'firebase\' of undefined' Updated in Nativescript-vue

### ISSUE THREAD

**Issue by thiamugb** [EddyVerbruggen/nativescript-plugin-firebase#1015]

**Comment by thiamugb** [comment]
I have a problem like this if i use nativescript vue with firebase.
I use this template vue init nativescript-vue/vue-cli-template sample.
I dont know where i put the file firebase.nativescript.json

**Comment by EddyVerbruggen** [comment]
Share a repo please and @ me in an issue on your repo, then I might take a look.
