### ISSUE TITLE
Add google-services to the include.gradle file 

### ISSUE THREAD

**Issue by vchimev** [EddyVerbruggen/nativescript-plugin-firebase#102]
Hi @EddyVerbruggen,

In order to avoid [these](https://github.com/EddyVerbruggen/nativescript-plugin-firebase#open-platformsandroidbuildgradle) manual steps, is it possible to add all needed dependencies to the [include.gradle](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/platforms/android/include.gradle) file of the plugin?

This would facilitate a lot the usage of the plugin.

Thank you,
@vchimev

**Comment by EddyVerbruggen** [comment]
Hey @vchimev I hope it can be done but my gradle-foo is not sufficient to pull that off (I've tried).. do you have any idea?

**Comment by vchimev** [comment]
Perhaps @Plamen5kov could help?

**Comment by EddyVerbruggen** [comment]
Landed in 3.8.0!
