### ISSUE TITLE
Can't run application on Android device after installation of Firebase plugin

### ISSUE THREAD

**Issue by Chehow** [EddyVerbruggen/nativescript-plugin-firebase#1026]
Hi

After installation of "nativescript-plugin-firebase": "^7.4.1" I can't build my application any more.
I see such error:
Project successfully built.
Installing on device b40c398b...
Successfully installed on device with identifier 'b40c398b'.
Unable to apply changes on device: b40c398b. Error is: Socket connection timed out..
Executing after-watch hook from D:\nodejs\ChatStories\hooks\after-watch\nativescript-dev-typescript.js
Stopping tsc watch
Executing after-watch hook from D:\nodejs\ChatStories\hooks\after-watch\nativescript-dev-webpack.js
Stopping webpack watch
Executing after-watch hook from D:\nodejs\ChatStories\hooks\after-watch\nativescript-dev-typescript.js
Executing after-watch hook from D:\nodejs\ChatStories\hooks\after-watch\nativescript-dev-webpack.js
Stopping webpack watch

My package.json 
**{
  "nativescript": {
    "id": "org.nativescript.ChatStories",
    "tns-ios": {
      "version": "5.0.0"
    },
    "tns-android": {
      "version": "5.0.0"
    }
  },
  "scripts": {
    "start": "tns run android"
  },
  "description": "ChatStories Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "@angular/animations": "~7.0.3",
    "@angular/cli": "^7.0.5",
    "@angular/common": "~7.0.3",
    "@angular/compiler": "~7.0.3",
    "@angular/core": "~7.0.3",
    "@angular/forms": "~7.0.3",
    "@angular/http": "~7.0.3",
    "@angular/platform-browser": "~7.0.3",
    "@angular/platform-browser-dynamic": "~7.0.3",
    "@angular/router": "~7.0.3",
    "nativescript-angular": "^6.2.0",
    "nativescript-audio": "^5.0.1",
    "nativescript-bottom-navigation": "^1.4.3",
    "nativescript-bottombar": "^3.0.8",
    "nativescript-cardview": "^3.1.1",
    "nativescript-image-filters": "^2.2.0",
    "nativescript-ngx-shadow": "^6.3.0",
    "nativescript-photoviewer": "^1.4.0",
    "nativescript-plugin-firebase": "^7.4.1",
    "nativescript-ripple": "^2.1.0",
    "nativescript-svg": "^1.3.7",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-gauge": "^3.7.1",
    "nativescript-ui-listview": "^3.7.2",
    "nativescript-ui-sidedrawer": "^5.0.0",
    "nativescript-web-image-cache": "^4.2.6",
    "reflect-metadata": "~0.1.10",
    "rxjs": "^6.0.0",
    "tns-core-modules": "^5.0.1",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~7.0.3",
    "@nativescript/schematics": "~0.3.4",
    "@ngtools/webpack": "~7.0.5",
    "nativescript-dev-typescript": "^0.7.4",
    "nativescript-dev-webpack": "^0.17.0",
    "typescript": "^3.1.6"
  },
  "readme": "ChatStories Application",
  "author": "Artem Chehowsy"
}`**

Firebase configuration (firebase.nativescript.json):
**`{
    "external_push_client_only": false,
    "using_ios": false,
    "using_android": true,
    "firestore": true,
    "realtimedb": false,
    "authentication": false,
    "remote_config": false,
    "performance_monitoring": false,
    "messaging": true,
    "crashlytics": false,
    "crash_reporting": false,
    "storage": true,
    "functions": true,
    "facebook_auth": false,
    "google_auth": false,
    "admob": true,
    "invites": false,
    "dynamic_links": false,
    "ml_kit": false
}**

app.gradle:
**android {  
  defaultConfig {  
    generatedDensities = []
    applicationId = "org.nativescript.ChatStories"
    multiDexEnabled true
    renderscriptTargetApi 25
    renderscriptSupportModeEnabled true
  }  
  aaptOptions {  
    additionalParameters "--no-version-vectors"  
  }
  dexOptions {
    javaMaxHeapSize "4g"
  }
  project.ext {
    googlePlayServicesVersion = "16.0.0"
  }
}**

I tried to remove node_modules, hooks and platforms and rebuild but it still does not work.
I tried rollback to version without firebase plugin and it works fine.
Do you have any idea how can I fix this problem?

Thanks a lot.

**Comment by EddyVerbruggen** [comment]
Do the demo apps in this repo work for you?

**Comment by Chehow** [comment]
Looks like after some magic (wihtout code changes) it started to work.
