### ISSUE TITLE
TypeError: com.google.android.gms.ads.AdView is not a constructor

### ISSUE THREAD

**Issue by Gcuencam** [EddyVerbruggen/nativescript-plugin-firebase#1027]
Hi Eddy,

I'm using native-plugin-firebase (v7.4.1) to admob and I receive the next error: 

JS: 'Error in firebase.admob.showBanner: TypeError: com.google.android.gms.ads.AdView is not a constructor'

Previously, I'm using nativescript-admob plugin and all was fine, but in the build I had gradle conflicts (because I'm using firebase auth, messages and realtimedb) and I had to change to this plugin.

Thanks.

**Comment by EddyVerbruggen** [comment]
What have you tried to resolve it? Removed the platforms folder? Feel free to share a repo and I’ll take a look if you’re really stuck. Plz don’t share snippets, only the real deal :)

**Comment by Gcuencam** [comment]
Solved!

It was silly. Going from the plugin nativescript-admob to the nativescript-plugin-firebase, I forgot to reconfigure the plugin and put `admob: true` in the configuration file, firebase.nativescript.json.

Once this was done I deleted the platforms folder and it worked.

What would life be without these little details? :')

Thanks !
