### ISSUE TITLE
Question: can we get an image's thumbnail from Storage?

### ISSUE THREAD

**Issue by jlooper** [EddyVerbruggen/nativescript-plugin-firebase#103]
Question - with the Storage module, can we get access to thumbnails? It would make loading my card interface quicker. I see thumbnails in the firebase console when I look up my images, but I don't see how we can get ahold of them. Do you have an idea how to? I can't find info in the docs. thanks!

**Comment by EddyVerbruggen** [comment]
Nope, there's nothing in de docs nor API and I've also inspected the runtime objects quickly. It probably makes sense as Firebase supports any filetype, not just image.

It would be a great enhancement to their SDK's though: providing a thumbnail URL for files of content-type `image/*`.

In the meanwhile, one approach could be to upload thumbnails yourself to the Storage bucket, and online load the bigger one when it makes sense.
