### ISSUE TITLE
IOS - failed to call firestore

### ISSUE THREAD

**Issue by edyrkaj** [EddyVerbruggen/nativescript-plugin-firebase#1030]
CONSOLE ERROR file:///app/tns_modules/@angular/core/bundles/core.umd.js:1743:28: ERROR TypeError: null is not an object (evaluating 'firebase.firestore.collection(_COLLECTION_NAME).where')

**Comment by EddyVerbruggen** [comment]
Did you enable firestore? Have you triwd removing the platforms folder? If all else fails, please share a repo and I’ll see if I can help.

**Comment by edyrkaj** [comment]
You are right. I have runned npm config from node_modules to choose services for firebase and it fixed the problem.
Also it was after I have removed platform and added again.
Thnx
