### ISSUE TITLE
How can I use notification click to open app with specific routes.

### ISSUE THREAD

**Issue by nakorndev** [EddyVerbruggen/nativescript-plugin-firebase#1032]
Sorry if I ask what docs has been written, but I no see a way to interact with click notification to open some specific route. Like I receive a new notify from firebase without open application. When I click it will only open a app homepage.

Please give me some example or docs to make this happens. Thanks.

**Comment by EddyVerbruggen** [comment]
You'll have to route the user to the correct page in `onMessageReceivedCallback`. Probably in an 'app loaded' event. But that's up to your app, not something this plugin can do.

**Comment by mshanak** [comment]
To make the notification works in foreground and background, you need to format the push message ( not this plugin ) correctly.

as explained in the FCM [documentation](https://firebase.google.com/docs/cloud-messaging/concept-options), you need to have two attributes in the message ``notification`` key and the ``data`` key
The ``notification`` key is used when the app is in the background, and the ``data`` key is used when the app is opened or when the user taps the notification.

Here is a JSON-formatted message containing both the notification key and the data key:

```{
  "message":{
    "token":"bk3RNwTe3H0:CI2k_HHwgIpoDKCIZvvDMExUdFQ3P1...",
    "notification":{
      "title":"you have new comment",
      "body":"user Ahmed added a new comment on you post!"
    },
    "data" : {
      "contentId" : "123",
      "contentType" : "post"
    }
  }
} 
```
 



This is my `addOnMessageReceivedCallback` function (typescript):

```
     
        
        firebase.addOnMessageReceivedCallback(
          (message) => {
            const self=this;
            let contentId:string=null;
            let contentType:string=null;
            let route:string="";

            /** if the app is already open, show a dialog message**/
            if (message.foreground){
              
              dialogs.confirm({
                title: message.title,
                message: message.body,
                okButtonText: "open ",
                
                neutralButtonText: "cancel"
              }).then(function (result) {
                // result argument is boolean
                if(result){
                  if (message.data.contentId && message.data.contentType) {
                    contentId = message.data.contentId;
                    contentType = message.data.contentType;
                    if (contentType === 'post') {
                      route = 'post/details/' + contentId;
                    }
                    
                    
                    self.router.navigate([route]);
                    
                    
                  }
                }
                console.log("Dialog result: " + result);
              });
              
              
              
            }else{
              
              /**if the message arrived when the app is in the background, this code is executed when the user taps on the notification **/
              console.log("message", message);
              
              if (message.contentId && message.contentType){
                contentId = message.contentId ;
                contentType = message.contentType;
                if(contentType==='post'){
                  route ='post/details/'+contentId;
                }
                
                
                this.router.navigate([route]);
                
                
              }
              
            }
            
            
          }
          
          );
          


```

**Comment by bjesus** [comment]
@mshanak, I tried your code but it doesn't seem to launch the app if it's in the background while the notification is received. Does it work it for you? Seems to me like I'm maybe navigating to page corresponding to the notification, but my app remains in the background. Kinda struggling with how to make the app go to foreground upon tapping on the notification on Android.

**Comment by mshanak** [comment]
@bjesus if the app don’t open when tapping the notification, the problem is with you message.
You should format your message as described in my previous comment .

**Comment by bjesus** [comment]
Thank, you are right of course. I've used the same message as the 
official tutorial did but your message structure worked.
