### ISSUE TITLE
Messaging: onPushTokenReceivedCallback called immediately after unregisterForPushNotifications

### ISSUE THREAD

**Issue by gregersen79** [EddyVerbruggen/nativescript-plugin-firebase#1045]
On Android, right after I successfully have called messaging.unregisterForPushNotifications(), the callback onPushTokenReceivedCallback gets called returning a new token. So the phone gets unregistered successfully but then receives a new token.

I have tested this on a Google Pixel 2, Samsung Galaxy S8 and S4 (real devices).

I have tried creating a new project and added this:

`require("nativescript-plugin-firebase");`

in app.js

and this in main-view-model.js:

`viewModel.register = function () {
        messaging.registerForPushNotifications({
            onPushTokenReceivedCallback: (token) => {
              console.log("Firebase plugin received a push token: " + token);
            },
          
            onMessageReceivedCallback: (message) => {
              console.log("Push message received: " + message.title);
            },
          
            // Whether you want this plugin to automatically display the notifications or just notify the callback. Currently used on iOS only. Default true.
            showNotifications: false,
          
            // Whether you want this plugin to always handle the notifications when the app is in foreground. Currently used on iOS only. Default false.
            showNotificationsWhenInForeground: false
          }).then(() => console.log("Registered for push"));
    }

    viewModel.unRegister = function () {
        messaging.unregisterForPushNotifications().then(() => {
              console.log("Unregistered!!!");
        });
    }`

How to avoid this? Or what am I doing wrong?

I'm using {N} 5 and 7.4.2 of the firebase-plugin.

**Comment by PeterStaev** [comment]
Having the same problem. Seems that when you call `unregisterForPushNotifications` it also triggers `onPushTokenReceivedCallback`. Interesting that when the callback is triggered the token is different than the current one. 

My current workaround is remove the callback from the register and then use the `getCurrentPushToken` instead. 

Using {N} 5.2 & 8.2 of the firebase plugin

**Comment by PeterStaev** [comment]
Seems this is caused by this code:
https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/acdbaa1f8604dc81748925fe4e8689eb7b702d41/src/platforms/android/libraryproject/firebase/src/main/java/org/nativescript/plugins/firebase/FirebasePlugin.java#L46-L51

@EddyVerbruggen , not sure why you are deleting the whole FCM instance instead of using the commented code and just delete the current token? I replaced locally my AAR with one using the commented code instead and the callback is not triggered when unregister is called.

**Comment by IAMtheIAM** [comment]
I have the same issue, is it pushed yet?

**Comment by EddyVerbruggen** [comment]
I think you know the answer. Otherwise let me know where you look for the current package version vs the milestone of this issue.
