### ISSUE TITLE
Android: Remote Config not fetched if called before foregroundActivity is set

### ISSUE THREAD

**Issue by jnorkus** [EddyVerbruggen/nativescript-plugin-firebase#1048]
I am upgrading my apps to latest Angular and NS. I've run into this issue where my remote config is not fetched if called before `foregroundActivity` is set. I found this code:
```
// if this is called before application.start() wait for the event to fire
appModule.on(appModule.launchEvent, runGetRemoteConfig);
```
The problem is that launch has already happened at this point and is not fired at all. Looks like `launchEvent` does not guarantee the `foregroundActivity` to be present.

**Comment by jnorkus** [comment]
I created a PR with a fix.

**Comment by EddyVerbruggen** [comment]
TY!
