### ISSUE TITLE
Error when trying to get messaging push token

### ISSUE THREAD

**Issue by yonatann** [EddyVerbruggen/nativescript-plugin-firebase#1053]
Hello,

I am trying to handle push notifications in my app.

I have initialized firebase and once it has been initialized I try to call firebase.addOnPushTokenReceivedCallback and get an error.

My initialization code:
let instance = await firebase.init({});
console.log("firebase.init success!");

firebase.addOnPushTokenReceivedCallback(
    function(token) {
        console.log("Firebase push token: " + token);
    }   
);

JS: TypeError: Cannot read property 'firebase' of undefined
JS:     at file:///data/data/com.moodapplication/files/app/tns_modules/nativescript-plugin-firebase/messaging/messaging.js:124:38
JS:     at new ZoneAwarePromise (file:///data/data/com.moodapplication/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:902:29)
JS:     at Object.addOnPushTokenReceivedCallback (file:///data/data/com.moodapplication/files/app/tns_modules/nativescript-plugin-firebase/messaging/messaging.js:122:12)
JS:     at AppComponent.<anonymous> (file:///data/data/com.moodapplication/files/app/app.component.js:34:34)
JS:     at step (file:///data/data/com.moodapplication/files/app/tns_modules/tslib/tslib.js:133:27)
JS:     at Object.next (file:///data/data/com.moodapplication/files/app/tns_modules/tslib/tslib.js:114:57)
JS:     at fulfilled (file:///data/data/com.moodapplication/files/app/tns_modules/tslib/tslib.js:104:62)
JS:     at ZoneDelegate.invoke (file:///data...
JS: Unhandled Promise rejection: Uncaught (in promise): TypeError: Cannot read property 'firebase' of undefined
JS: TypeError: Cannot read property 'firebase' of undefined
JS:     at file:///data/data/com.moodapplication/files/app/tns_modules/nativescript-plugin-firebase/messaging/messaging.js:124:38
JS:     at new ZoneAwarePromise (file:///data/data/com.moodapplication/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:902:29)
JS:     at Object.addOnPushTokenReceivedCallback (file:///data/data/com.moodapplication/files/app/tns_modules/nativescript-plugin-firebase/messaging/messaging.js:122:12)
JS:     at AppComponent.<anonymous> (file:///data/data/com.moodapplication/files/app/app.component.js:34:34)
JS:     at step (file:///data/data/com.moodapplication/files/app/tns_modules/tslib/tslib.js:133:27)
JS:     at Object.next (file:///data/data/com.moodapplication/files/app/tns_modules/tslib/tslib.js:114:57)
JS:     at fulfilled (file:///data/data/com.moodapplication/files/app/tns_modules/tslib/tslib.js:104:62)
JS:     at Zone...
12-01 15:22:06.984 21818 21818 E AndroidRuntime:        at com.tns.Runtime.callJSMethodNative(Native Method)
12-01 15:22:06.984 21818 21818 E AndroidRuntime:        at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
12-01 15:22:06.984 21818 21818 E AndroidRuntime:        at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
12-01 15:22:06.984 21818 21818 E AndroidRuntime:        at com.tns.Runtime.callJSMethod(Runtime.java:983)
12-01 15:22:06.984 21818 21818 E AndroidRuntime:        at com.tns.Runtime.callJSMethod(Runtime.java:967)
12-01 15:22:06.984 21818 21818 E AndroidRuntime:        at com.tns.Runtime.callJSMethod(Runtime.java:959)

**Comment by EddyVerbruggen** [comment]
Share a repo plz, I don't even see your `firebase` import here..
