### ISSUE TITLE
Authorization library should not be required for Dynamic Links

### ISSUE THREAD

**Issue by jfturcot** [EddyVerbruggen/nativescript-plugin-firebase#1058]
I am trying to use Dynamic Links, but it tries to call FIRAuth which my project does not use.

Could you please change the following:
https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/f18262b6e56c6ac93358bde928841340b2d6489d/src/firebase.ios.ts#L162-L163

To:
```
var fAuth;
if (typeof (FIRAuth) !== "undefined") {
    fAuth = FIRAuth.auth();
}
if (fAuth && fAuth.isSignInWithEmailLink(userActivity.webpageURL.absoluteString)) {
```

Thanks!

**Comment by EddyVerbruggen** [comment]
FIxed in #1070
