### ISSUE TITLE
App won't launch due to version mismatch between Google Analytics and Google App Measurement

### ISSUE THREAD

**Issue by danbockapps** [EddyVerbruggen/nativescript-plugin-firebase#1061]
I installed the plugin for my app. When I run tns run ios, I get an error, and the app wont' start.

*** JavaScript call stack:
(
0   configure@[native code]
1   applicationDidFinishLaunchingWithOptions@file:///app/tns_modules/nativescript-plugin-firebase/firebase.js:39:33
2   UIApplicationMain@[native code]
3   start@file:///app/tns_modules/tns-core-modules/application/application.js:273:26
4   run@file:///app/tns_modules/tns-core-modules/application/application.js:301:10
5   bootstrapNativeScriptApp@file:///app/tns_modules/nativescript-angular/platform-common.js:187:26
6   bootstrapApp@file:///app/tns_modules/nativescript-angular/platform-common.js:105:38
7   bootstrapModule@file:///app/tns_modules/nativescript-angular/platform-common.js:89:26
8   anonymous@file:///app/main.js:6:57
9   evaluate@[native code]
10  moduleEvaluation@:1:11
11  promiseReactionJob@:1:11
)
*** Terminating app due to uncaught exception 'FIRAnalyticsVersionMismatch', reason: 'Google Analytics for Firebase version (50300000) does not match with Google App Measurement (50400000) version. Please update.'

**Comment by danbockapps** [comment]
The error happened with the latest version, 7.4.3. I downgraded to 7.3.0, and did not get the error.

**Comment by danbockapps** [comment]
This looks related: https://github.com/firebase/firebase-ios-sdk/issues/2151

**Comment by danbockapps** [comment]
I created a new app from scratch and reproduced the issue:

1. tns create firebase-test-app --template tns-template-blank-ng
2. Create app in Firebase console and follow the steps
3. Change package.json to my package name
4. Download GoogleService-Info.plist and put it in App_Resources/iOS
5. tns plugin add nativescript-plugin-firebase
6. Answer n to all questions except iOS, Crashlytics and save config
7. pod repo update
8. Add Angular startup wiring
9. tns run ios

**Comment by EddyVerbruggen** [comment]
Thanks!

**Comment by EddyVerbruggen** [comment]
Added a locked dependency to `pod 'GoogleAppMeasurement', '5.3'` as suggested in the upstream issue. Thank you for bringing this to my attention!

Just published to npm with version 7.4.4.

**Comment by iLyxa3D** [comment]
How to fix it without using pods?
`reason: 'Google Analytics for Firebase version (50801000) does not match with Google App Measurement (60001000) version. Please update.'`
