### ISSUE TITLE
Installing plugin makes device console very verbose on iOS device

### ISSUE THREAD

**Issue by danbockapps** [EddyVerbruggen/nativescript-plugin-firebase#1066]
After installing the plugin, and running `tns run ios` or `tns debug ios`, I get much more console output than before:

![ezgif-5-c0d27682fd9e](https://user-images.githubusercontent.com/4488712/49687786-24ac0a00-fad6-11e8-8856-fd1571131683.gif)

These messages don't look like they're related to the plugin, but more likely a more verbose logging level got turned on. This gets in the way of seeing the console output that I do want to see.

I'm experiencing this on an iPhone 7 Plus with iOS 12, and an iPhone 5S with iOS 11.

Removing the plugin makes the console go back to normal.

I'm using Nativescript 5.0.3 and nativescript-plugin-firebase 7.3.0.

**Comment by EddyVerbruggen** [comment]
I have no idea what to do about that.. feel free to reopen with more insight (anyone).

**Comment by danbockapps** [comment]
This duplicates https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/978 - I should have found that before.
