### ISSUE TITLE
Unable to copy google-services.json

### ISSUE THREAD

**Issue by JonasJW** [EddyVerbruggen/nativescript-plugin-firebase#1067]
My NativeScript App crashes as soon as I install the nativescript-plugin-firebase.

I create a new app with `tns create test1`. I run `tns run android` everything works to this point. Then I generate my goolge-services.json and run `tns plugin add nativescript-plugin-firebase`. As soon as the plugin is installed, the app crashes after the splash screen with the error:

`
    Unable to copy google-services.json.
    Unable to apply changes on device: LGH8705317fe7. Error is: Failed to execute hook: /Users/jonas/Projects/NativeScript/test1/hooks/after-prepare/firebase-copy-google-services.js..`

The problem is still there when I initialize the plugin in as described like this:

const firebase = require("nativescript-plugin-firebase");

    const firebase = require("nativescript-plugin-firebase");

    @Component({
        // ...
    })
    export class AppComponent implements OnInit {
    ngOnInit() {
        firebase.init({
        }).then(
        instance => {
            console.log("firebase.init done");
        },
        error => {
            console.log(`firebase.init error: ${error}`);
        }
        );
    }
    }

**Comment by EddyVerbruggen** [comment]
Please share a repo and reopen. Thanks!
