### ISSUE TITLE
Unable to copy google-services.json

### ISSUE THREAD

**Issue by JonasJW** [EddyVerbruggen/nativescript-plugin-firebase#1068]
My NativeScript App crashes as soon as I install the nativescript-plugin-firebase.

I create a new app with tns create test1. I run tns run android everything works to this point. Then I generate my goolge-services.json and run tns plugin add nativescript-plugin-firebase. As soon as the plugin is installed, I cannot run the app anymore. I get this error:

`Unable to copy google-services.json.` 
`Unable to apply changes on device: LGH8705317fe7. Error is: Failed to execute hook: /Users/jonas/Projects/NativeScript/test1/hooks/after-prepare/firebase-copy-google-services.js..`

The problem is still there when I initialize the plugin in as described like this:

    export class AppComponent implements OnInit {

        ngOnInit(): void {
            firebase.init({
            }).then(
                (instance) => {
                console.log("firebase.init done");
                },
                (error) => {
                console.log(`firebase.init error: ${error}`);
                }
            );
        }
    }

Here is the Repo: https://github.com/JonasJW/test1

**Comment by Skintillion** [comment]
Did you copy your google-services.json file over to your App_Resources/Android folder?

**Comment by JonasJW** [comment]
No I actually had it placed in platform/android by accident. However I changed it to App_Resources/Android and I still get the same error.

**Comment by Skintillion** [comment]
platform remove and add?

**Comment by abhayastudios** [comment]
@JonasJW seems the `google-services.json` is missing from your `App_Resources`?

**Comment by vosonha89** [comment]
> Did you copy your google-services.json file over to your App_Resources/Android folder?

It worked for me 👍. Many thanks.
