### ISSUE TITLE
Facebook Login does not return any result in iOS

### ISSUE THREAD

**Issue by asaph26** [EddyVerbruggen/nativescript-plugin-firebase#107]
While authenticating through Facebook in iOS, the facebook SDK does not return any result, and the safari instance opened remains as it is.

Everything works smoothly in Android.

This is a recurring issue in the latest Facebook SDK.

One suggested solution is to change the Login Method to a popup http://stackoverflow.com/a/34737097 

Another thread is here. I believe the top voted solution is what is implemented in the plugin.
http://stackoverflow.com/questions/32299271/facebook-sdk-login-never-calls-back-my-application-on-ios-9

Any other ideas/thoughts in resolving this?

**Comment by EddyVerbruggen** [comment]
Which iOS version, and is there anything in the log? See Xcode > Window > Devices.

**Comment by asaph26** [comment]
iOS Version 9.3.
I haven't been able to run the app due to other issues. Will post the log once I get things up and running again.

**Comment by asaph26** [comment]
This seems to be working after re-installing the Facebook SDK pod. So closing the issue for now.
Thank you for the immediate reply.

**Comment by EddyVerbruggen** [comment]
If it pops up again, .. I think there was a regression introduces for iOS when Google SignIn was added. Should be fine in version 3.5.4.

**Comment by asaph26** [comment]
That could be it. Thank you for the fix.
