### ISSUE TITLE
Android build fails because it suddenly can't find com.google.gms:google-services:4.2.0

### ISSUE THREAD

**Issue by EddyVerbruggen** [EddyVerbruggen/nativescript-plugin-firebase#1072]
See https://stackoverflow.com/questions/53704155/could-not-find-com-google-gmsgoogle-services4-0-1 for details.

TL;DR: Google unpublished the dependency from their maven repo, so we need to have the plugin add another maven repo during the build. 😡

**Comment by mediadeo** [comment]
Desperately watching for a fix! any ideas as to why they unpublished the dependency ? is this related to the deprecation of the GCM platform you think?

**Comment by EddyVerbruggen** [comment]
Give me 15 minutes and it's done.

I have no idea, would love to know!

**Comment by EddyVerbruggen** [comment]
OK, thanks for bearing with me - 7.4.5 is now on npm. Remove your `platforms` folder to be sure the native dependencies get updated.

**Comment by mediadeo** [comment]
works like a charm! thanks eddy!
