### ISSUE TITLE
Facebook login not working on iOS

### ISSUE THREAD

**Issue by daniel-rfe** [EddyVerbruggen/nativescript-plugin-firebase#1073]
Hello,

I'm not being able to login by Facebook in iOS 12.1. I Don't know about other version since I test on a real device, as I'm on Windows using sidekick. I receive the following message:

```
CONSOLE LOG file:///app/tns_modules/nativescript-plugin-firebase/firebase.js:701:36: Facebook login error Error Domain=com.facebook.sdk.core Code=3 "(null)" UserInfo={com.facebook.sdk:FBSDKErrorDeveloperMessageKey=Unknown error building URL.}
CONSOLE LOG file:///app/shared/user-view-model.js:355:16: error The operation couldn\M-b\M^@\M^Yt be completed. (com.facebook.sdk.core error 3.)
```
I tried looking for this "error code 3" on facebook docs, however could not find any light.

- I already reviewed my info.plist;
- I already verified the facebook configuration on my sdk account;
- It works correctly on Android;
- Previous versions of the plugin were working properly, it started getting errors after 7.4.x releases;

**Comment by vidrepar** [comment]
Same here. I also tried nativescript-facebook plugin and got the same error.

**Comment by vidrepar** [comment]
Maybe this is a way forward to find a solution: https://stackoverflow.com/questions/35248412/ios-facebook-login-error-unknown-error-building-url-com-facebook-sdk-core-e

**Comment by abhayastudios** [comment]
Indeed pinning the Facebook pods in `platforms/ios/Podfile` as below fixes the issue:

```
# Facebook Authentication
pod 'FBSDKCoreKit', '~> 4.38.0'
pod 'FBSDKLoginKit', '~> 4.38.0'
```

**Comment by vidrepar** [comment]
@abhayastudios awesome, it works! In the meantime, for anyone still struggling with this:

1. Remove platform
```
rm -rf node_modules && tns platform remove ios
```

2.  Add platform and generate Podfile
```
tns run ios
```

3. Change Facebook Authentication in Podfile (platforms/ios/Podfile)
```
# Facebook Authentication
pod 'FBSDKCoreKit', '~> 4.38.0'
pod 'FBSDKLoginKit', '~> 4.38.0'
```

4. In **platforms/ios** run:
```
pod update
```

5. Run ios again
```
tns run ios
```

**Comment by daniel-rfe** [comment]
Thanks! I'm happy to see that we have a solution, however it didn't work for me, but since I'm on windows and using cloud builds, I'm 95% sure that sidekick does not take into consideration any modification I do on node_modules folder and it goes directly to the npm repository to build... Hence I must wait for a new version release :/

**Comment by EddyVerbruggen** [comment]
Thanks for your help, everyone!
