### ISSUE TITLE
Couldn't find Manage User functions

### ISSUE THREAD

**Issue by kunjee17** [EddyVerbruggen/nativescript-plugin-firebase#1080]
There are bunch of [manager user](https://firebase.google.com/docs/auth/web/manage-users) functions. Like, you verify user using phone verification and then add further details to same user. I can't find all functions in that other than email verification functions and update profile function. Can you please point me if functions are already implemented or if any plans to implement them?

**Comment by EddyVerbruggen** [comment]
Well, quite a few of those are implemented and documented here: https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/AUTHENTICATION.md, so please be more specific about what you need.

**Comment by kunjee17** [comment]
@EddyVerbruggen hey, thanks for replying and nice library. 

Requirement for me is, I need to allow user to authenticate him/her self using email/phone and password. And I also need to verify phone no. 

So, I was thinking of creating user using phone no verification method. Which is as per documentation working. But then I wanted to add other details to user like, name, email etc. I couldn't find any method to do that. 

Below are the methods I couldn't find. 

```
user.updateEmail("user@example.com").then(function() {
  // Update successful.
}).catch(function(error) {
  // An error happened.
});
```

and to update password

```

user.updatePassword(newPassword).then(function() {
  // Update successful.
}).catch(function(error) {
  // An error happened.
});
```

Also, one more dumb question. There is provider array we are having for user. So, is it possible to have multiple verification method for same user?

**Comment by rafaelcmrj** [comment]
Any idea when the `updateEmail` method will be implemented?

**Comment by EddyVerbruggen** [comment]
@kunjee17 Changing a password is supported: https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/b833b1bee77b0f30217af14c1902ad76d6b543ad/docs/AUTHENTICATION.md#changing-a-password

**Comment by kunjee17** [comment]
Thanks @EddyVerbruggen

**Comment by rafaelcmrj** [comment]
@EddyVerbruggen any idea for the `updateEmail` method?

**Comment by EddyVerbruggen** [comment]
@rafaelcmrj I've just added `updateEmail`, [check out the doc](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/a749960738998964fa8ce3c8cb4134921dbf6bd1/docs/AUTHENTICATION.md#updating-an-email-address).

I've also aligned this a bit better with the Web API:
- `changePassword` is now `updatePassword`
- added `updateEmail`
- `resetPassword` is now `sendPasswordResetEmail`

Will be part of 8.0.0 and that will be out in about a week.
