### ISSUE TITLE
Firestore on Android may crash during livesync

### ISSUE THREAD

**Issue by EddyVerbruggen** [EddyVerbruggen/nativescript-plugin-firebase#1089]
I had this happen during development in my Vue app: `java.lang.IllegalStateException: FirebaseFirestore has already been started and its settings can no longer be changed. You can only call setFirestoreSettings() before calling any other methods on a FirebaseFirestore object.`

**Comment by canhkieu** [comment]
I things it's the same error with #1036 because we cann't settings follow this guide:
https://firebase.google.com/docs/firestore/quickstart#initialize

```
firebase.initializeApp({
  apiKey: '### FIREBASE API KEY ###',
  authDomain: '### FIREBASE AUTH DOMAIN ###',
  projectId: '### CLOUD FIRESTORE PROJECT ID ###'
});

// Initialize Cloud Firestore through Firebase
var db = firebase.firestore();

// Disable deprecated features
db.settings({
  timestampsInSnapshots: true
});
```
