### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by zhengiko** [EddyVerbruggen/nativescript-plugin-firebase#109]
Hello guys. Have strange problem. 
I create empty app and try to add firebase plugin. 

`tns plugin add nativescript-plugin-firebase`

After question in console "Are you using iOS (y/n): " and any answer from me, process doesn't finish. I use android only, so I answer "n" => I see new folder "nativescript-plugin-firebase" in "node_modules" but in console I see nothing and process doesn't finish.

**Comment by kaurag007ph** [comment]
Hi @zhengiko are you using windows? I encountered the same issue a while ago using git bash, but when I tried it on default commandline, it works.

**Comment by zhengiko** [comment]
Windows 8.1 + command Prompt (admin) with Ruby. Tryed default command prompt - nothing changes - the same problem.

**Comment by Leeaandrob** [comment]
I am with same problem using mac os x. I am using ITerm2...

**Comment by EddyVerbruggen** [comment]
@Leeaandrob do you have the exact same problem? So you're not using iOS, answer `n` and get stuck as @zhengiko does?

I just tried these steps on my Mac, console output:

```
localhost:_remove eddyverbruggen$ tns create fbtestt
Project fbtestt was successfully created.

localhost:_remove eddyverbruggen$ cd fbtestt
localhost:fbtestt eddyverbruggen$ tns platform add android
[..]
Project successfully created.
localhost:fbtestt eddyverbruggen$ tns plugin add nativescript-plugin-firebase
|
> nativescript-plugin-firebase@3.5.3 postinstall /Users/eddyverbruggen/sandboxes/_remove/fbtestt/node_modules/nativescript-plugin-firebase
> node scripts/postinstall.js

NativeScript Firebase Plugin Installation
prompt: Are you using iOS (y/n):  (y) n
prompt: Are you using Android (y/n):  (y)
```

So after answering `n` the installscript happily moves to the next question. Is this different than what you are seeing?
