### ISSUE TITLE
No .entitlements file in CLI 5+

### ISSUE THREAD

**Issue by delanick** [EddyVerbruggen/nativescript-plugin-firebase#1090]
Hey @EddyVerbruggen 

In your instructions you make mention of the .entitlements file. I'm using NS CLI 5+ and don't have an entitlements file, at all. Do you know why? Or how I can create it? 

Using:
Xcode 10.1
NS CLI 5.0.3, then 5.1 and now 5.2 -> none of them create an entitlements file. PLEASE advise :)

**Comment by EddyVerbruggen** [comment]
You can grab this one: https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/demo/app_resources/iOS/app.entitlements

**Comment by delanick** [comment]
@EddyVerbruggen Thanks bud!

**Comment by delanick** [comment]
@EddyVerbruggen  Sorry to bug again, I just need to try understand this. The entitlements file you linked above, as aps-environment set to development. Do I need to create a dev push cert with Apple?

And once ready for production, do I change the entitlements file to "Production", "production", or "prod" or what?

Sorry, this is breaking my brain a bit!
