### ISSUE TITLE
Question/Feature: Group namespace and function

### ISSUE THREAD

**Issue by KkevinLi** [EddyVerbruggen/nativescript-plugin-firebase#1091]
With the firebase webApi I am able to access DataSnapshot just by importing firebase 
`function foo(a: firebase.database.DataSnapshot): any {}`
but with the Nativescript WebApi, `import * as firebaseWeb from "nativescript-plugin-firebase/app";
` is not enough as I do not have access to DataSnapshot unless I import from `"nativescript-plugin-firebase/app/database"`; 

Is there a reason for this difference? It would be great if they were the same so it makes sharing code much easier.

**Comment by EddyVerbruggen** [comment]
Why was this closed / what did you find out?
