### ISSUE TITLE
Datasnapshot exists()

### ISSUE THREAD

**Issue by KkevinLi** [EddyVerbruggen/nativescript-plugin-firebase#1094]
How can we call exists() on firebase.database.datasnapshot?

**Comment by EddyVerbruggen** [comment]
Can you give a full example?

**Comment by KkevinLi** [comment]
[https://firebase.google.com/docs/reference/android/com/google/firebase/database/DataSnapshot#exists()](url)

`  const example: firebase.database.DataSnapshot = ____;
    example.exists();`

I noticed that I could just check if `DataSnapshot.val() !== null` so it is not as important that I cannot call exists().

**Comment by EddyVerbruggen** [comment]
Example added to the Web API example @ https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/DATABASE.md#addvalueeventlistener
