### ISSUE TITLE
firebase.js:1275:24: Error in firebase.query: ReferenceError: Can't find variable: FIRDatabase

### ISSUE THREAD

**Issue by yblok13** [EddyVerbruggen/nativescript-plugin-firebase#1096]
> CONSOLE LOG file:///app/tns_modules/nativescript-plugin-firebase/firebase.js:1275:24: Error in firebase.query: ReferenceError: Can't find variable: FIRDatabase

Issue is happening on device(iPhone 7 plus) and emulator.

        firebase.query((q) => {
            console.log(q)
            }, "/parties",{
            singleEvent: true,
            orderBy: {
                type: firebase.QueryOrderByType.CHILD,
                value: 'isPublic'
            },
            range: {
                type: firebase.QueryRangeType.EQUAL_TO,
                value: true
            }
        })

**Comment by EddyVerbruggen** [comment]
You probably haven't enabled this line:

https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/e295d5b54c18f16bb97321143e4b500d68fc41d2/demo/firebase.nativescript.json#L6

Or if you have, please remove the `platforms` and `node_modules` folders and rebuild.

**Comment by yblok13** [comment]
Thanks for the speedy reply! That did fix the error - and I realize now you did mention it in the docs.
However, nothing is being logged from my code? 
I have a collection with path "/parties", each document has a field "isPublic" with boolean true.
Any idea?

Thanks in advance!

**Comment by EddyVerbruggen** [comment]
Perhaps there's a missing index, or the permissions are incorrect.
