### ISSUE TITLE
Firebase PushNotifications are not received in iOS

### ISSUE THREAD

**Issue by nuno-morais** [EddyVerbruggen/nativescript-plugin-firebase#1097]
Hello,
I'm not able to receive pushnotifications in iOS.

You can check this issue on this repository:
 - https://github.com/nuno-morais/TestPushNotifications

This is never called: 
```
        onPushTokenReceivedCallback: token => {
```
neither 

```
        onMessageReceivedCallback: message => {
```

**Comment by EddyVerbruggen** [comment]
I didn't check other things, but [this filename](https://github.com/nuno-morais/TestPushNotifications/blob/master/app/App_Resources/iOS/demong.entitlements) doesn't look right. Rename to `app.entitlements`.

**Comment by nuno-morais** [comment]
why `app.entitlements`?

**Comment by EddyVerbruggen** [comment]
Did you try it?

**Comment by nuno-morais** [comment]
Yes I made the change and it is not working...

However this project is a fork of your repository.... I don't understand why I have to change anything. 

You can confirm on `build.xconfig` the entitlements `CODE_SIGN_ENTITLEMENTS = demong/demong.entitlements`

Can you explain? 🙏

**Comment by EddyVerbruggen** [comment]
Check https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/MESSAGING.md#copy-the-entitlements-file

**Comment by nuno-morais** [comment]
the app name is the name of root folder?

**Comment by EddyVerbruggen** [comment]
Yeah just like in the demo, but you can also use `app.entitlements` so you don't need to worry about that.

**Comment by nuno-morais** [comment]
ah, thanks.
I have some concerns about it.... I don't know what is happening, because when I'm using the simulator I'm receiving the `onMessageReceivedCallback` (i'm using logs), but when I use the real mobile the notification does not appear.

**Comment by nuno-morais** [comment]
I found this log: 
`5.15.0 - [Firebase/Messaging][I-FCM002010] The subscription operation is suspended because you don't have a token. The operation will resume once you get an FCM token.`

I'm not receiving any push token 🤔

**Comment by nuno-morais** [comment]
Do you have any suspect why I'm not able to get the push token on iOS? (just for sanity check: it is working on Android)

**Comment by EddyVerbruggen** [comment]
No idea, but I can spend an hour looking at your project. If you'd like that, please mail me at eddyverbruggen at gmail dot com so we can arrange something.
