### ISSUE TITLE
Enable push support for iOS without Xcode (on Windows)

### ISSUE THREAD

**Issue by saibbyweb** [EddyVerbruggen/nativescript-plugin-firebase#1100]
This is more of a question than an issue which I couldn't find in the docs.

[Enabling push support in Xcode](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/MESSAGING.md#enable-push-support-in-xcode) in the docs points to opening the project in **Xcode** and switch on the **Push Capabilities**. But what If I'm developing on Windows. I don't have Xcode.

**Comment by EddyVerbruggen** [comment]
The doc at that link also says that step will create a file you need to copy. Here's an example: https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/demo/app_resources/iOS/app.entitlements
