### ISSUE TITLE
"this account already exists on your device"

### ISSUE THREAD

**Issue by mosesweb** [EddyVerbruggen/nativescript-plugin-firebase#1106]
How do I battle this error I get when I try to login through Google on my phone?
This appears when I logout from firebase (with logout) and when I try log in again I get the google login but I can't login because of this error: "this account already exists on your device". How do I login if I logged out and I have a Google account on the phone already?

**Comment by jalberto-ghub** [comment]
I am facing the same issue, can you let me know how did you solve it?

**Comment by Slanfan** [comment]
Same here @mosesweb
