### ISSUE TITLE
"${PODS_ROOT}/Fabric/run" double quote is missing

### ISSUE THREAD

**Issue by praveshkhatana** [EddyVerbruggen/nativescript-plugin-firebase#1107]
`"${PODS_ROOT}/Fabric/run"` double quote is missing which causing the following issue 

```
Command PhaseScriptExecution failed with a nonzero exit code
note: Using new build systemnote: Planning buildnote: Constructing build description
** ARCHIVE FAILED **
```

it works fine when i add `"` in build phases via  xcode.

**Comment by EddyVerbruggen** [comment]
Where's that missing from exactly? The relevant LoC is this one, but it looks right:

https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/13fca449d815003dcc629fbad2928e632b3fbfd2/publish/scripts/installer.js#L495

**Comment by praveshkhatana** [comment]
it should be like `'\"${PODS_ROOT}/Fabric/run\"'` 

working fine for me after this change

**Comment by EddyVerbruggen** [comment]
Hi, did you close this because it's not an issue anymore?

**Comment by praveshkhatana** [comment]
I found a reason which was causing this issue.
if project/folder name contain any spacing like `project a` then it start giving such error and fix for that is `'\"${PODS_ROOT}/Fabric/run\"'`

**Comment by EddyVerbruggen** [comment]
Oh that makes sense! I’ll add the quotes then, thx!
