### ISSUE TITLE
No need to use fs as npm dependency

### ISSUE THREAD

**Issue by YurySolovyov** [EddyVerbruggen/nativescript-plugin-firebase#111]
Hi!
`fs` is a node core module, there is no need to include it as npm dependency
See https://github.com/npm/npm/issues/13743

**Comment by EddyVerbruggen** [comment]
Hi Yuri, to your knowledge - is there a specific version of node that it has been added to as core module? I'm wondering if ppl using older versions would run into issues..

**Comment by YurySolovyov** [comment]
It was there from the beginning

**Comment by EddyVerbruggen** [comment]
Awesome, thanks Yuri!
