### ISSUE TITLE
App crashes after adding firebase.init() 

### ISSUE THREAD

**Issue by Omi231** [EddyVerbruggen/nativescript-plugin-firebase#1115]
Everything was working fine untill i yesterday decided to upgrade to Nativescript 5. Now only in new projects as soon as i add initialize firebase in app.component using `firebase.init({})` app crashes (Nativescript 4 projects run without any issue).

The error doesn't provide me any clue what is wrong.
![screenshot-1547882164069](https://user-images.githubusercontent.com/44071105/51423634-ef223280-1be4-11e9-937e-6435d00fd890.jpg)

**Comment by EddyVerbruggen** [comment]
To see the actual error, run ‘adb logcat’ on the command line and make it crash again.

**Comment by Omi231** [comment]
reinstalling plugin and mapping with existing firebase project solved the issue.
