### ISSUE TITLE
AdMob: Cannot read property of addView

### ISSUE THREAD

**Issue by vtjon** [EddyVerbruggen/nativescript-plugin-firebase#1120]
Despite adding a timeout, I often get TypeError: Cannot read property 'addView' of null  when I create the banner. The main admob repo seems to have some extra null checks. See:
https://github.com/EddyVerbruggen/nativescript-admob/blob/master/src/admob.android.js#L140

I think these are missing in this repo. Is it possible to add those checks?

**Comment by EddyVerbruggen** [comment]
Good point. Added here as well. Thanks!
