### ISSUE TITLE
Current push token: undefined

### ISSUE THREAD

**Issue by GalushkoVasiliy** [EddyVerbruggen/nativescript-plugin-firebase#1122]
Hello, I have issue with Current push token: undefined on IOS platform, I add files app.entitlements to app_resources/ios and to platform but token is undefined
on Android this task is done
Can you help me?

**Comment by EddyVerbruggen** [comment]
Not unless you share a repo.

**Comment by GalushkoVasiliy** [comment]
Thanks for feedback, Eddy, can you check https://github.com/GalushkoVasiliy/test.git repo?

**Comment by GalushkoVasiliy** [comment]
> Not unless you share a repo.

I add a repo

**Comment by GalushkoVasiliy** [comment]
Hi, Eddy, can you help me?

**Comment by EddyVerbruggen** [comment]
@GalushkoVasiliy 2 things:
- Make sure you test on a real device
- Change [this line](https://github.com/GalushkoVasiliy/test/blob/7e021e8aa24c9e101901eff7250dd80414e3fb7d/App_Resources/iOS/build.xcconfig#L10) to `CODE_SIGN_ENTITLEMENTS = ownapp/ownapp.entitlements`

Then remove the platforms/ios folder and it should work.
