### ISSUE TITLE
Migration from push-plugin to plugin-firebase

### ISSUE THREAD

**Issue by jannomeister** [EddyVerbruggen/nativescript-plugin-firebase#1125]
Previously I used `nativescript-push-plugin` to handle push notifications in iOS. On my server I used `https://github.com/node-apn/node-apn` to send notification to iOS devices. `nativescript-push-plugin` works very well. But since the NS team deprecated it and they have a migration guide for  push-plugin to plugin-firebase, so I tried to implement it. I did some testing but I didn't receive any push notifications. :( Does node-apn and ns-plugin-firebase is compatible?

**Comment by EddyVerbruggen** [comment]
Sure. It's library-agnostic. Did you check out demo-push to see if you have all bits in place?

**Comment by EddyVerbruggen** [comment]
So I guess you want me to look at your code?

**Comment by jannomeister** [comment]
Also, im not receiving a token using `registerForPushNotifications` or `getCurrentPushToken`.

**Comment by jannomeister** [comment]
I already allowed xcode push notification and added 
```
<key>UIBackgroundModes</key>
<array>
  <string>remote-notification</string>
</array>
<key>UseExternalPushProvider</key>
<true/>
```
in my info.plist

**Comment by jannomeister** [comment]
@EddyVerbruggen does `GoogleService-Info.plist` still needed for non-firebase push notification? because when I checked the demo-push for non-firebase push notif, I didn't see any GoogleService-Info.plist.

**Comment by EddyVerbruggen** [comment]
Can you share a repo instead of snippets?

**Comment by jannomeister** [comment]
the repo is hosted in gitlab and its a private repo :(

**Comment by EddyVerbruggen** [comment]
Two things:
- Make sure that entitlements file has the correct name and the reference in `build.xcconfig` is correct. This may be the case, I did not run your app nor did I check the config in Xcode
- More importantly, this https://github.com/jannomeister/test-push-notif/blob/71a7143cca82252d54a7de5cee56573c2cc4ff12/app/main.ts#L24-L55 overrides the appdelegate changes of the plugin! I don't see why you'd need to do it in the appdelegate anyway - just move your code to the 'app launched' event NativeScript fires fi.

**Comment by jannomeister** [comment]
@EddyVerbruggen its because of the damn delegate! thank you so much!! you're a lifesaver :)
