### ISSUE TITLE
Add support for "inverse" barcodes

### ISSUE THREAD

**Issue by zalesak** [EddyVerbruggen/nativescript-plugin-firebase#1128]
Please add scanning of inverse barcode - white code on black background.
It will be super to turn on or off this feature through configuration, or switch scanner to "inverse" mode.

**Comment by EddyVerbruggen** [comment]
What would that implementation look like? I mean, interpreting camera images is offloaded to ML Kit.

**Comment by EddyVerbruggen** [comment]
If you can preprocess the image and turn it into a 'regular' QR code then yeah.

**Comment by zalesak** [comment]
Can you add preprocess hook to getImage method? And add option to configuration i.a. - imagePreprocesesMethod. 
Then it will be possible to create preprocessor for image source, there is plugin which can invert image https://github.com/bradmartin/nativescript-image-filters

**Comment by EddyVerbruggen** [comment]
Sounds nice, would you like to give it a try?

**Comment by zalesak** [comment]
so actually i`ve made it for Android. 
I added simple paramater for tag MLKitBarcodeScanner and bind custom service to preprocess byteArray from camera frame. 
Preprocess has to be implemented in custom java class because of speed, but it is just simple "bitwise NOT" on byteArray,

I see here two ways how this could be made in plugin:
1. custom preprocessor service, but it will be harder to implement for user, but open more options (crop image, black&white, tune contrast..), 
2. add "reverseEveryNthFrame" parameter and plugin itself will reverse frame data before call detectInImage

What do you think?

**Comment by EddyVerbruggen** [comment]
Hey @zalesak, that sounds good!

I guess adding an optional `boolean` property `supportInverseBarcodes` would be more clear. Internally we can check every nth frame. Would that work, you think?

**Comment by zalesak** [comment]
OK I have it done for both IOS and Android platgorm. I tried to email you patch but mail in your profile not work.

**Comment by EddyVerbruggen** [comment]
Please use the PR workflow instead. GitHub has great tutorials on Pull Requests and other Git workflow stuff. Thx!

**Comment by MurilloBrand** [comment]
@zalesak Could you share your solution, please?

**Comment by zalesak** [comment]
Hi @MurilloBrand, sorry, I completely forgot.
Today I created pull request, you can find solution here
https://github.com/zalesak/nativescript-plugin-firebase/tree/zalesak-inverse-code-pr

**Comment by MurilloBrand** [comment]
Hi @zalesak, thank you so much! :)
