### ISSUE TITLE
"Error: Unsupported browser"

### ISSUE THREAD

**Issue by jmarlow4** [EddyVerbruggen/nativescript-plugin-firebase#1131]
I've set up a shared angular nativescript app with this firebase plugin and it builds and runs well, but when I make calls to AngularFireAuth, specifically with the signInAnonymously method, it never makes the call, and instead errors out "Error: Unsupported Browser."

I've tried retracing my steps during setup and I think I've done everything correctly. I've also tried searching if others have had the same problem, but it looks like it only relates to the messaging service. I haven't even tried setting that up.. I'm only testing this out with auth.

This same piece of code works in the web app... it only happens when I try android or iOS. So I know it has to do with the way I'm setting up this plugin. I just don't know what it could be.

I've placed the nativescript firebase plugin init in app.module.tns.ts:
```
@NgModule({
  declarations: [
    AppComponent,
    HomeComponent,
  ],
  imports: [
    NativeScriptModule,
    AppRoutingModule,
    AngularFireModule.initializeApp(environment.firebase),
    AngularFireAuthModule
  ],
  providers: [],
  bootstrap: [AppComponent],
  schemas: [NO_ERRORS_SCHEMA]
})
export class AppModule {
  constructor() {
    nsFirebasePlugin.init({
      iOSEmulatorFlush: true
    }).then(
      () => {
        console.log('firebase.init done');
      },
      error => {
        console.log(`firebase.init error: ${error}`);
      }
    )
  }
}
```

I did this instead of putting it in `app.component.ts` because I wanted to avoid creating a separate tns.ts component. I've tested them both and the results are the same so that can't be it. The plugin initializes correctly.

The component in which I call the AngularFireAuth service is in the home.component.ts:
```
@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
})
export class HomeComponent implements OnInit {

  title = 'angular-nativescript-firebase-akita-starter'
  isAuthed = false

  constructor( public afAuth: AngularFireAuth ) { }

  ngOnInit() {
  }

  login() {
    console.log('logging in...')
    this.afAuth.auth.signInAnonymously().then( (res) => {
      console.log('res', res)
      this.isAuthed = true
    }, err => console.log('this is the error', err))
  }
}
```

In the template I have a click handler, and like I said, it all works in the browser in chrome, but if I click the button that sets off `login()` in iOS or Android, I get `Error: Unsupported Browser`

If you want to take a look at the code itself here's a link: https://github.com/jmarlow4/angular-nativescript-firebase-akita-starter/tree/adding-angular-firebase

**Comment by jmarlow4** [comment]
No one knows what's causing this?

**Comment by EddyVerbruggen** [comment]
Is it because you’re using the plugin through angularfire?

**Comment by jmarlow4** [comment]
I am using @angular/fire, yes... is that a no-no?

**Comment by EddyVerbruggen** [comment]
At the moment you can’t use that. Just stick to the native api or web api documented in the readme.
