### ISSUE TITLE
Custom logs for crashlytics

### ISSUE THREAD

**Issue by kanclalg** [EddyVerbruggen/nativescript-plugin-firebase#1134]
Hi, I wonder if custom logs for crashlytics (https://firebase.google.com/docs/crashlytics/customize-crash-reports#ios) supposed to work in the latest plugin version?
I get it to work for android and seems like Crashlytics.log (https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/src/crashlytics/crashlytics.d.ts#L7) works as expected for android but on iOS I don't get any log information on Crashlytics exception "Logs" tab. Looks like the wrong function is called in the code. In the documentation they write that you should call CLS_LOG though I'm not sure how to access this one. Thank you for any help.

**Comment by kanclalg** [comment]
It's documentated in this link under "Add custom logs" https://firebase.google.com/docs/crashlytics/customize-crash-reports#ios

**Comment by EddyVerbruggen** [comment]
Thanks. I doubt that macro is available on NativeScript. Can you try `console.log("CLS_LOG: " + CLS_LOG)`? In case you get a TypeScript error, add `declare const CLS_LOG: any`.

**Comment by kanclalg** [comment]
Yeah, I've already tried it before, it throws:
`ERROR ReferenceError: Can't find variable: CLS_LOG`.
Do you have any ideas how to wrap that macro so it would be accessible to nativescript?

**Comment by EddyVerbruggen** [comment]
I don't think you can, but I haven't extensively googled it. Perhaps we can use these alternatives: https://github.com/irccloud/ios/blob/master/Crashlytics.framework/Headers/CLSLogging.h

**Comment by kanclalg** [comment]
What do you have in mind exactly? None of these seems to be accessible.

**Comment by EddyVerbruggen** [comment]
OK, then it's not possible I guess. But the generated typings seem to suggest `logEvent` is a thing, so I'm not sure why your events aren't logged ☹️

https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/14d83d8cb881f197ec5a4009f0126286fed69041/src/platforms/ios/typings/objc!Crashlytics.d.ts#L154

**Comment by kanclalg** [comment]
`logEvent` is also missing from their official documentation here: https://firebase.google.com/docs/reference/ios/crashlytics/api/reference/Classes/Crashlytics#-recorderror
and looks like it's deprecated: https://github.com/irccloud/ios/blob/master/Crashlytics.framework/Headers/Crashlytics.h#L202
I'll try to use Answers. logCustomEventWithName they are referring.

**Comment by EddyVerbruggen** [comment]
Oh interesting, that would be `Answers.logCustomEventWithNameCustomAttributes("myEvent", null)` in NativeScript. Curious if that works!

**Comment by kanclalg** [comment]
Unfortunately, that doesn't work too :( In case you wonder how I test it, I'm logging multiple (3) events (using these functions, e.g  logCustomEventWithNameCustomAttributes, logEvent..) seperated by 2 seconds and after that I'm invoking `Crashlytics.sharedInstance().crash()` to force crash. Also tried to crash with non fatal like that `Crashlytics.sharedInstance().recordError(NSError.errorWithDomainCodeUserInfo("test", 0, null));`. But I get nothing in Logs tab near Crash on iOS :(
As I said this works on Android and here's how it looks in firebase:
![screenshot 2019-02-05 at 15 18 49](https://user-images.githubusercontent.com/11705645/52275920-89120b00-2959-11e9-924b-fa961fe14728.png)
