### ISSUE TITLE
didReceiveMessage: not implemented

### ISSUE THREAD

**Issue by galer88** [EddyVerbruggen/nativescript-plugin-firebase#1135]
Hi and thanks for an amazing plugin! I've implemented push notifications https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/MESSAGING.md on android and everything works fine. Now I try to do the same on iOS but unfortunately I have some problems.

I tired your culr example requests https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/MESSAGING.md#ios-background-notification-example

and I got success message in console

`{"multicast_id":5755092260544836688,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1549384955562803%fbf3b3ddfbf3b3dd"}]}`

unfortunately there is no notification on phone and there is an error 

`5.15.0 - [Firebase/Messaging][I-FCM002019] FIRMessaging received data-message, but FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented`

I test on real Iphone 7 device and use your plugin in version 7.4.1

I did also this provisioning hell https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/MESSAGING.md#provisioning-hell but app doesn't ask me about permission.

**Comment by EddyVerbruggen** [comment]
Perhaps there's something wrong initializing the plugin, because that method is actually wired by the plugin:

https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/794467a9d72b66247c1343eee3a7665c6b00306c/src/messaging/messaging.ios.ts#L616

Can you share a repo and an example of the exact CURL command?

**Comment by brndusic** [comment]
Hi @EddyVerbruggen, I have similar problem like @galer88. I found same message in logs and tried different things to implement but without success. 
Interesting thing is that app is not asking for permissions for notifications and I think we should start there with investigation.

I'm creating ng-app, added ```require("nativescript-plugin-firebase");``` on first line in ```main.ts```. ```initFirebase``` is called on service initialization and it regularly returns token.

main.ts:
```
// this import should be first in order to load some required settings (like globals and reflect-metadata)

require("nativescript-plugin-firebase");
import { platformNativeScriptDynamic } from "nativescript-angular/platform";
import { android as tnsAndroid, AndroidApplication, AndroidActivityBundleEventData } from "tns-core-modules/application";
import { isAndroid } from "tns-core-modules/ui/page/page";
import { StoreUpdate, AlertTypesConstants } from "nativescript-store-update";

import { AppModule } from "./app/app.module";
```

service.ts:
```
import { Injectable } from '@angular/core';
import {init as initFirebase, getCurrentPushToken} from 'nativescript-plugin-firebase';

@Injectable()
export class FirebaseNotificationService {
    constructor() {
        initFirebase().then(() => console.log('Initialized successfuly'), error => console.error(error));
    }

    public getAuthToken(): Promise<string> {
        return getCurrentPushToken();
    }
}

```

I lost a lot of hours trying to find out what is a problem and I don't really know what to try anymore.

Can you help please?

**Comment by EddyVerbruggen** [comment]
If you share a repo I can clone I might take a look.

**Comment by brndusic** [comment]
@EddyVerbruggen I would like to share a repo but I can't. If I have time I will try to create a demo repo.

Can you suggest what else I can try? 

Could it be because of webpack?

**Comment by EddyVerbruggen** [comment]
It could be many things. And it usually is something that’s covered in the readme or demo apps, but it’s impossible to tell without the actual project.

**Comment by brndusic** [comment]
Hi @EddyVerbruggen,
found solution for my problem:

```
import { Injectable } from '@angular/core';
import {init as initFirebase, getCurrentPushToken, registerForPushNotifications} from 'nativescript-plugin-firebase';

@Injectable()
export class FirebaseNotificationService {
    constructor() {
        initFirebase().then(() => {
            registerForPushNotifications({
                showNotificationsWhenInForeground: true,
                showNotifications: false
            }).then(
                () => console.log('registerForPushNotifications success'),
                () => console.log('registerForPushNotifications failed')
            )
        });
    }

    public getAuthToken(): Promise<string> {
        return getCurrentPushToken();
    }
}
```

In order to make app asks for permissions I needed to call ```registerForPushNotifications```

**Comment by ashokIosDev** [comment]
Hi 
@EddyVerbruggen in ios onPushTokenReceivedCallback is not calling, i put this in app.component.ts
> messaging.registerForPushNotifications({
        onPushTokenReceivedCallback: (token: string): void => {
          console.log("Firebase plugin received a push token: " + token);
        },

        onMessageReceivedCallback: (message: Message) => {
          console.log("Push message received: " + message.title);
        },

        // Whether you want this plugin to automatically display the notifications or just notify the callback. Currently used on iOS only. Default true.
        showNotifications: true,

        // Whether you want this plugin to always handle the notifications when the app is in foreground. Currently used on iOS only. Default false.
        showNotificationsWhenInForeground: true
      }).then(() => console.log("Registered for push"));

      messaging.getCurrentPushToken()
      .then(token => console.log(`Current push token: ${token}`));

      this.pushSettings()
   }
