### ISSUE TITLE
how to get a single FieldValue

### ISSUE THREAD

**Issue by job111** [EddyVerbruggen/nativescript-plugin-firebase#1137]
am trying to check a FieldValue and see if it exists or not

**Comment by EddyVerbruggen** [comment]
So what have you tried already?

**Comment by job111** [comment]
i tried everything but nothing seems to be working

**Comment by job111** [comment]
I'm going to close this issue since i managed to solve the problem

**Comment by VladsGG** [comment]
how did you solve it? please provide code. thanks!
