### ISSUE TITLE
Facebook authentication return object missing object members

### ISSUE THREAD

**Issue by Sulman633** [EddyVerbruggen/nativescript-plugin-firebase#114]
Hi, I have Facebook authentication working with the firebase plugin but it doesn't seem to be returning an object with all the object members that the Facebook SDK says it will return when using public_profile. Link to Facebook public profile: https://developers.facebook.com/docs/facebook-login/permissions#reference-public_profile 

![fblogincode](https://cloud.githubusercontent.com/assets/11000928/18028725/ca792756-6c53-11e6-8e41-6715ffc427a8.PNG)

As you can see not all the object members are present? Is this intended behavior?
![objectmembers](https://cloud.githubusercontent.com/assets/11000928/18028715/9cb2273c-6c53-11e6-8f11-c50cc063c1bb.png)
Note: I also had to suppress object type error for intended scope since it was throwing an error(look below)
![error](https://cloud.githubusercontent.com/assets/11000928/18028733/ed8e1184-6c53-11e6-9c2c-2fb061ef7778.png)

I used the following compiler option in tsconfig file for typescript to suppress that warning: 

![suppresserror](https://cloud.githubusercontent.com/assets/11000928/18028744/30d8b250-6c54-11e6-8f6c-c2e681db5bf6.PNG)

**Comment by Sulman633** [comment]
Also what is the token property on the returned object supposed to be? Since mine is empty. I would have thought it would be a token from from Facebook?

**Comment by Sulman633** [comment]
@EddyVerbruggen Could you please elaborate further?

**Comment by EddyVerbruggen** [comment]
@Sulman633 I fixed the TS error you mentioned. That's all at this point.
