### ISSUE TITLE
Feature Request -  Passing State in Email Actions

### ISSUE THREAD

**Issue by reedkellen** [EddyVerbruggen/nativescript-plugin-firebase#1146]
Would it be possible to update the *sendEmailVerification* method (https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/AUTHENTICATION.md) to accept an argument similar to what is documented here (https://firebase.google.com/docs/reference/js/firebase.User#sendEmailVerification)?

I would like to be able to direct users back to the native app with a dynamic link after they verify their email address as described in this article (https://firebase.google.com/docs/auth/web/passing-state-in-email-actions#handling_email_actions_in_a_mobile_application)

**Comment by EddyVerbruggen** [comment]
Thanks for requesting this! I've added the required code to 8.0.0 (trying to release that to npm tomorrow). Docs updated already: https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/AUTHENTICATION.md#sendemailverification
