### ISSUE TITLE
Realtime Database transaction error

### ISSUE THREAD

**Issue by Socha17** [EddyVerbruggen/nativescript-plugin-firebase#1148]
Been trying to get transactions working with real time database, but Ive been getting this error 
`JS ERROR TypeError: undefined is not a function (near '...firebase.transaction...')` 

This is my code
```  
firebase.transaction('users', (currentValue => {
        if (currentValue === null) {
          return 0;
        } else {
          // console.log('User ada already exists.');
          return ++currentValue; // Abort the transaction.
        }
      })) // firebase.Datasnapshot follows the web datasnapshot interface
      .then((result: { committed: boolean, snapshot}) => {
         console.log(result.committed + " snapshotValue: " + result.snapshot.val());
       }).catch(err => console.log("Encountered an error " + err));
```
Ive tried both native API and web API
I also tried on both ios and android emulators, both crash with this error.

if anyone has any ideas, any help would be greatly appreciated thanks!

**Comment by EddyVerbruggen** [comment]
Please share a repo that shows the error and reopen. I can't run snippets on my phone. Thanks!
