### ISSUE TITLE
Facebook Authentication Redirect

### ISSUE THREAD

**Issue by davidaustinarcher** [EddyVerbruggen/nativescript-plugin-firebase#115]
Hi, I have had partial success with the facebook authentication in that the facebook login page is shown then I log in ok but it doesn't redirect back to my app. It shows a blank page? I am using the ios simulator.

![image](https://cloud.githubusercontent.com/assets/16766645/18030370/5185c310-6cab-11e6-8f67-4da7ce73ab56.png)

I have set up the appid and secret in firebase and the "Valid OAuth redirect URIs" in Facebook. I have also configured the info.plist file.

Has anyone seen this before?

**Comment by davidaustinarcher** [comment]
I read issue #107 which sounds identical. I'm running ios 9.3. I tried pod update which updated the FB pods to: 

Using FBSDKCoreKit (4.15.0)
Using FBSDKLoginKit (4.15.0)

However it doesn't appear to have resolved my issue.

**Comment by EddyVerbruggen** [comment]
Let me take a look..

**Comment by EddyVerbruggen** [comment]
Thanks for reporting this issue. I think this regression was introduced for iOS when Google SignIn was added. Should be fine in version 3.5.4.
