### ISSUE TITLE
No valid 'aps-environment' entitlement string found for application on iOS10+

### ISSUE THREAD

**Issue by TweroDev** [EddyVerbruggen/nativescript-plugin-firebase#1151]
I'm developing an in-house (enterprise) app with Nativescript-Vue and using this plugin to deliver the push notifications. Everything works as expected on Android and iOS 9, but on iOS 10 and above I get the following error:

`Error in application: didFailToRegisterForRemoteNotificationsWithError: no valid 'aps-environment' entitlement string found for application`

The funny thing is that the entitlements file is present and has the 'aps-environment' key. I've tried with both development and production values.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>aps-environment</key>
    <string>development</string>
</dict>
</plist>
```
Of course the app capabilities for push notifications and push notifications in background mode are switched on.
![push-notifications](https://user-images.githubusercontent.com/47771325/52996578-50c10100-341e-11e9-9bf9-553c0a60e7f1.png)
![background-modes](https://user-images.githubusercontent.com/47771325/52996585-56b6e200-341e-11e9-91ac-0f2b2e8c8b46.png)

The provisioning profile was generated after switching the app's push notifications on, and has capabilities and entitlements correctly set.
![provisioning-profile](https://user-images.githubusercontent.com/47771325/52996599-5e768680-341e-11e9-8a60-c26a9e4f9bd9.png)

I'm requiring the plugin on top of my main.js file, right after the imports
```js

import * as application  from 'tns-core-modules/application';
import * as appSettings  from 'tns-core-modules/application-settings';
import * as platform     from 'tns-core-modules/platform';
import * as dialogs      from 'tns-core-modules/ui/dialogs';
import * as utils        from 'utils/utils';
import Vue               from 'nativescript-vue';
import { ImageCacheIt }  from 'nativescript-image-cache-it';
import { Gif }           from 'nativescript-gif';
import { RadSideDrawer } from 'nativescript-ui-sidedrawer';
import RadListView       from 'nativescript-ui-listview/vue';
import { DropDown }      from 'nativescript-drop-down/drop-down';
import { handleOpenURL } from 'nativescript-urlhandler';
import Router            from './router/index';
import Login             from './components/Login';
import socket            from './services/socket';
import updateApp         from './services/updateApp';
import API               from './services/api';
import config            from './config/config';
import faIcons           from './fonts/json/fa.json';

import './filters/filters';

require('nativescript-plugin-firebase');
```
And I init the firebase plugin on the first loaded component mounted hook
```js
mounted () {
  firebase.init({
    showNotificationsWhenInForeground : true,
    onPushTokenReceivedCallback       : (token) => {
      console.log(`Firebase plugin received a push token: ${token}`);
    },
    onMessageReceivedCallback (message) {
      console.log(`Title: ${message.title}`);
      console.log(`Body: ${message.body}`);
    },
  });
}
```

I've spent more than thirty hours googling, researching and trying different configurations, but I can't find a way to make it work.

Is there something I'm missing/overlooking?

**Comment by EddyVerbruggen** [comment]
Share a repo reproducing this please.

**Comment by pabloislive** [comment]
Sorry, forgot to say that it's a commercial app and I'm not allowed to share the full code, can I provide you with some specific part?

**Comment by TweroDev** [comment]
Sorry, forgot to say that it's a commercial app and I'm not allowed to share the full code, can I provide you with some specific part?

**Comment by EddyVerbruggen** [comment]
Yes, a repo that isolates the issue.

**Comment by TweroDev** [comment]
@EddyVerbruggen I've created a private repo with the bare minimum to reproduce the issue and made you collaborator https://github.com/TweroDev/nativescript-firebase/invitations

I've deliberately deleted the app/App_Resources/Android/google-services.json and app/App_Resources/iOS/GoogleService-Info.plist files.

Thanks for your help, man!

**Comment by EddyVerbruggen** [comment]
Thanks, I'll open an issue there and report back here if there's something relevant to report. Thx!

**Comment by TweroDev** [comment]
@EddyVerbruggen I've tried with two more devices and it works perfectly. Apparently there's some problem with the test device I was using.
Thank you for your time and for your good work, mate!
