### ISSUE TITLE
https callable function - uncatchable error

### ISSUE THREAD

**Issue by acrollet** [EddyVerbruggen/nativescript-plugin-firebase#1159]
Hi there,

when using an https callable function, if there is a network error, the entire app will crash with this error:

`*** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: ReferenceError: Metadata for "FirebaseFunctions.FIRFunctionsErrorDomain" found but symbol not available at runtime.
`

It is not catchable in the application code. It's easy enough to reproduce this error, simply call a function with a misspelled function name, e.g.:

```javascript
const myCloudFunction = firebase.functions.httpsCallable('thisFunctionNameDoesNotExist');

myCloudFunction({ args }).then((return) => {
  // won't get here.
}).catch((e) => {
  // won't get here either.
});
```

thanks for all your hard work!

**Comment by EddyVerbruggen** [comment]
Thanks for the clear error report! I've removed the unnecessary `FIRFunctionsErrorDomain` check and verified the app no longer crashes.
