### ISSUE TITLE
Cannot read property 'vision' of undefined

### ISSUE THREAD

**Issue by alexiej** [EddyVerbruggen/nativescript-plugin-firebase#1160]
Hi

When I try run ,
`npm run setupandinstall (just skip through the plugin y/n prompts you'll get as those are ignored in this case)` I've got error on Windows machine `.' is not recognized as an internal or external command,`, so I decided to use Vue.js firebase example. 

I tried to use nativescript with the mlkit image recognition but it doesn't work :(.
When I try run the code:

```js
var firebase = require("nativescript-plugin-firebase");
import { MLKitImageLabelingOnDeviceResult  } from "nativescript-plugin-firebase/mlkit/landmarkrecognition";

  firebase.mlkit.imagelabeling.labelImageOnDevice({
                          image: image,
                          confidenceThreshold: 0.6 // this will only return labels with at least 0.6 (60%) confidence. Default 0.5.
                        }).then((result) => console.log(JSON.stringify(result.labels)))
                        .catch(errorMessage => console.log("ML Kit error: " + errorMessage));

```
I've got error ""Cannot read property 'vision' of undefined"". When I Run debugger the reason for this is function `getDetector`. I think that I miss something to install or configure, but I don't know what it is.
Is it possible to add `ml` library to the `Vue.js` template example?

![image](https://user-images.githubusercontent.com/12593751/53681748-4d672880-3cee-11e9-8758-5dbec020c897.png)

I run on the `Android configuration`, vue.js firebase example that has included nativescript-plugin-firebase. 

`AndroidManifest.xml`

```html
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
	package="__PACKAGE__"
	android:versionCode="10000"
	android:versionName="1.0">

	<supports-screens
		android:smallScreens="true"
		android:normalScreens="true"
		android:largeScreens="true"
		android:xlargeScreens="true"/>

	<uses-sdk
		android:minSdkVersion="17"
		android:targetSdkVersion="__APILEVEL__"/>

	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
	<uses-permission android:name="android.permission.INTERNET"/>
  <meta-data android:name="com.google.firebase.ml.vision.DEPENDENCIES"
        android:value="image, face,barcode" 
    />

	<application
		android:name="com.tns.NativeScriptApplication"
		android:allowBackup="true"
		android:icon="@drawable/icon"
		android:label="@string/app_name"
		android:theme="@style/AppTheme">

		<activity
			android:name="com.tns.NativeScriptActivity"
			android:label="@string/title_activity_kimera"
			android:configChanges="keyboard|keyboardHidden|orientation|screenSize|smallestScreenSize|screenLayout|locale|uiMode"
			android:theme="@style/LaunchScreenTheme">

			<meta-data android:name="SET_THEME_ON_LAUNCH" android:resource="@style/AppTheme" />

			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
		</activity>
		<activity android:name="com.tns.ErrorReportActivity"/>
	</application>
</manifest>

```

This is my `package.json` file.

```js
{
    "nativescript": {
        "id": "org.nativescript.thisisexampleoffirebase",
        "tns-android": {
            "version": "5.2.0"
        },
        "tns-ios": {
            "version": "5.2.0"
        }
    },
    "description": "NativeScript Application",
    "license": "SEE LICENSE IN <your-license-filename>",
    "repository": "<fill-your-repository-here>",
    "dependencies": {
        "nativescript-camera": "4.2.0",
        "nativescript-imagepicker": "~6.0.0",
        "nativescript-plugin-firebase": "~7.7.0",
        "nativescript-theme-core": "~1.0.4",
        "nativescript-ui-listview": "~5.1.0",
        "nativescript-vue": "~2.0.0",
        "tns-core-modules": "~5.2.0"
    },
    "devDependencies": {
        "@babel/core": "~7.1.0",
        "@babel/preset-env": "~7.1.0",
        "babel-loader": "~8.0.0",
        "nativescript-dev-webpack": "~0.20.0",
        "nativescript-vue-template-compiler": "~2.0.0",
        "node-sass": "~4.9.0",
        "vue-loader": "~15.4.0"
    },
    "gitHead": "59b6da006346fedb5bb201fcc9cd7d204a69a82f",
    "readme": "NativeScript Application"
}

```

**Comment by EddyVerbruggen** [comment]
Can you share a repo and instructions showing the issue?

**Comment by alexiej** [comment]
Hi,

I've created the repository: https://github.com/alexiej/nativescript_example

The whole code is in the `Home.vue` file, in the `app\components\` directory. After taking a screenshot I've got this error.

![android](https://user-images.githubusercontent.com/12593751/53833630-4a3b9900-3f89-11e9-93a3-d6d88334646f.png)

**Comment by VimalKumarS** [comment]
hi 
Any pointer ?  facing the same issue, but using barcode scanner functionality

Error in firebase.mlkit.scanBarcodesOnDevice: TypeError: Cannot read property 'vision' of undefined
JS:  LOG  ML Kit error: TypeError: Cannot read property 'vision' of undefined

registered the app in firebase, enabled the vision api .

thanks
Vimal

**Comment by fabioaraujo121** [comment]
My error appeared when the camera opened (using the live feed).
I don't know if it's going to work with you guys. But I just ran `tns plugin remove nativescript-plugin-firebase` **remove** de `platforms/` folder and reinstall, running `tns plugin add nativescript-plugin-firebase`.

Hope it helps!

**Comment by cherimo** [comment]
Unfortunately I have the same problem for the BarCodeScanner.
I still even have the error  when I re-installed the plugin and platforms.

This is what I constant get:
LOG from device Galaxy S6 edge+: sizePair.previewSize: 1440x1080
LOG from device Galaxy S6 edge+: sizePair.pictureSize: 3984x2988
LOG from device Galaxy S6 edge+: Error in Firebase MLKit's runCamera function: TypeError: Cannot read property 'vision' of undefined

Is there any solution to this?

**Comment by EddyVerbruggen** [comment]
@cherimo Depends on how you build the app and what your Firebase config is. Care to share a repo?

**Comment by dotun** [comment]
Hi @alexiej. Did you get this resolved? Facing the same issue.

**Comment by cherimo** [comment]
@EddyVerbruggen sorry for the late reply, when I moved my files from my Windows machine to my Mac and removed the platforms so that I can rebuild them again.. After that it seems everything works fine now! 
If it helps I can make 2 repos, 1 from a Windows machine and 1 from the Mac with the same steps?

**Comment by EddyVerbruggen** [comment]
@cherimo Are you running the app on an emulator on Windows? And if so, does it have Google Play Services installed (it's required)?

**Comment by cherimo** [comment]
@EddyVerbruggen I dont use the emulator, I have a couple android and ios devices where I test my app. But I can use the emulator if needed.

**Comment by EddyVerbruggen** [comment]
No that’s ok. So I don’t see that I need to look at anything because you’ve got it working on a machine. Not sure how I can assist because I don’t have a Windows machine.

**Comment by dotun** [comment]
Hi @EddyVerbruggen just to add to the discussion: it appears that the dependencies that brings in such Android classes as **FirebaseVisionBarcodeDetectorOptions** are not being pulled through. I say this because when I debug, I get a similar **undefined** error that @alexiej posted.

Is there a way I can check locally that the android dependencies are fully added? Thanks in advance.

**Comment by dotun** [comment]
Just solved the problem on my side. What did it for me was switching the **ml_kit** property of my **firebase.nativescript.json** file to **true**. I also did `tns plugin remove nativescript-plugin-firebase` and deleted my `platforms` folder and re-installed with `tns plugin add nativescript-plugin-firebase`, as suggested by @fabioaraujo121.

Apparently, switching **ml_kit** to true is a requirement for such features as barcode scanning.

BTW, this is some good stuff, @EddyVerbruggen.

**Comment by EddyVerbruggen** [comment]
Yes it is required. It should be enabled when this bit of the docs is executed: https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/ML_KIT.md#enabling-ml-kit
