### ISSUE TITLE
Push notifications not working on IOS

### ISSUE THREAD

**Issue by sebestindragos** [EddyVerbruggen/nativescript-plugin-firebase#1162]
Hi, I've been struggling for the past few weeks to get this plugin to work on IOS, but it just seems that is doesn't want to. I have been able to retrieve the push token after many tries, but the onMessageReceivedCallback just won't get called. 

I'm using a node.js server and sending push notifications via a node-apn module. This worked flawlessly with the old push-plugin, but I just haven't got it working with this one. Any ideas why it might not work? Thanks.

**Comment by EddyVerbruggen** [comment]
It’s impossible for me to comment without being able to look at your repo.

**Comment by sebestindragos** [comment]
It's a quite large Angular app running on NS 4.2. 
I'm using this plugin only for push notifications because the nativescript push plugin was deprecated in favor of this one. So I followed the setup instructions from here
https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/NON_FIREBASE_MESSAGING.md

I also followed the migration guide from the old plugin. 

I do a require() in my app.module.ts file, and for the actual code I have a PushNotifications service that I inject in my top level app component. This component does nothing with this service, it just requires it to actually instantiate the service. I'm also using ngrx store in the project, so in my push notifications service I subscribe to a user profile observer. This is because when the user is logged in that subscription will run the code to init the push plugin. The code looks like this:

`
this._store.select(s => s.profile).subscribe(profile => {
    if (profile) {
      this._initChannel();
    }
});
`
Inside the _initChannel() private method I'm using this plugin's API with 

`
pushPlugin.registerForPushNotifications({})
`

The thing is that this works well on Android, but I haven't been able to get it to do anything on IOS. Not even the pushTokenReceived callback doesn't get called. I did manage at some point to get the push token, but after that I made some changes and it isn't working anymore.

I'm all out of ideas right now. 
Is it a server side problem? I haven't really figured out how does this plugin work on IOS. The old plugin made use of the native code to manage notifications via Apple Push Service. Does this work over Firebase also on IOS? And then Firebase somehow relays the data through APN? Should I send the message to firebase only on the server side?

Thanks for your help Eddy, I'm really stuck right now.

**Comment by EddyVerbruggen** [comment]
Add me to the repo and I might take a look..

**Comment by sebestindragos** [comment]
It's hosted on BitBucket :)

**Comment by EddyVerbruggen** [comment]
I have a BB account (eddyverbruggen at gmail)

**Comment by EddyVerbruggen** [comment]
I'll add a ticket with my findings in your BB account. First thing I noticed is you don't require the plugin in `main.ts`. Follow-up there.

**Comment by sebestindragos** [comment]
Hi Eddy,

I've managed to get the plugin working on IOS. Moving the require to
main.ts seems to have solved it.
I am now facing another issue though. The onPushTokenReceivedCallback is
getting called twice SOMETIMES. I've capitalized the word because I haven't
been able to figure out how to reproduce it.
On Android work as expected.

Any ideas on this one? :)

Regards,
Dragos
