### ISSUE TITLE
JWT validation failed: BAD_FORMAT

### ISSUE THREAD

**Issue by jnorkus** [EddyVerbruggen/nativescript-plugin-firebase#1163]
After upgrading to 8.0.0, I started getting the error in title on all requests to my backend. We use the Firebase Auth. Same for iOS and Android, emulator and device.

**Comment by EddyVerbruggen** [comment]
What have you tried to solve it, and is there a way for me to reproduce it?

**Comment by jnorkus** [comment]
Sorry about being lazy. I have found the issue. In version 7.x `getAuthToken` would return a `string`. Now it's `GetAuthTokenResult` where the string token is a `token` property. You can close this one but such breaking changes are probably worth mentioning somehwere.

**Comment by EddyVerbruggen** [comment]
Yeah, sorry about that. What would be an appropriate place on your opinion?  Would you have checked the changelog file in this case? If so, I can add it there.

**Comment by jnorkus** [comment]
I think changelog makes sense, that's the first place to check after a major version bump.

**Comment by EddyVerbruggen** [comment]
👍 I'll take care of that. Thx.
