### ISSUE TITLE
Error when using Array_union to push a GeoPoint

### ISSUE THREAD

**Issue by MichaelFBA** [EddyVerbruggen/nativescript-plugin-firebase#1164]
Hello,

I am using Version 8.0.0 of the library.
I noticed some recent changes were made when using array_union when pushing new objects into an array. It seems like all subsequent updates map the values to objects which causes an issue with GeoPoints.
https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/src/firebase.android.ts#L146

Example (See Below)
1. I am pushing a single Geopoint into an array
2. I am then updating with array_union and pushing another GeoPoint.
```
{
location:
   [ GeoPoint { _latitude: 47.297257, _longitude: 8.5604391 },
     { latitude: 47.2972584, longitude: 8.5604395 },
     { longitude: 8.5604466, latitude: 47.2972555 },
     { latitude: 47.2972588, longitude: 8.5604429 }
   ]
}
```

**Comment by EddyVerbruggen** [comment]
Is there a fix you can propose? And does it behave the same on iOS?

**Comment by MichaelFBA** [comment]
Ill have to confirm it's the same on iOS, the code looks the same so I guess so.

I'm not entirely sure of the history of changes that have been made prior.
I will take a look and see.

**Comment by MichaelFBA** [comment]
I think i might just pass a map initally
