### ISSUE TITLE
Error assigning FIRDatabaseReference to FIRDatabaseQuery

### ISSUE THREAD

**Issue by KkevinLi** [EddyVerbruggen/nativescript-plugin-firebase#1166]
```
Type 'FIRDatabaseReference' is not assignable to type 'FIRDatabaseQuery'.
  Types of property 'description' are incompatible.
    Type '() => string' is not assignable to type 'string'.

this.query = this.dbRef;
```
Not sure why I am seeing this error when FIRDatabaseReference extends FIRDatabaseQuery. this.query is of type FIRDatabaseQuery and this.dbRef is FIRDatabaseReference.

**Comment by EddyVerbruggen** [comment]
What code triggers this?

**Comment by KkevinLi** [comment]
I am implementing a feature (firebase.ios.ts) and when I tried to do ^ I get that error.

**Comment by KkevinLi** [comment]
Seems that FIRDatabaseReference's description method is conflicting with NSObject's description method. Had to make the type of query = FIRDatabaseQuery | FIRDatabaseReference (a bit awkward) but it resolved my problem so closing for now.
