### ISSUE TITLE
Feature Request: displayName property for createUserObject

### ISSUE THREAD

**Issue by deytola** [EddyVerbruggen/nativescript-plugin-firebase#1169]
I can't seem to save the displayname for a user during user registration. when I call firebase.createUser(), I get a warning that the displayName property does not exist when I pass displayName together with email and password. Kindly provide a way to save a user's displayName in your plugin. Thanks.

<img width="494" alt="capture" src="https://user-images.githubusercontent.com/36213634/54026346-c8708900-419d-11e9-9de5-60453653c764.PNG">

**Comment by EddyVerbruggen** [comment]
What makes you think `displayName` is a valid property? I don't see it in their docs: https://firebase.google.com/docs/auth/web/manage-users#create_a_user

**Comment by deytola** [comment]
I'm a bit unclear as to how I can save the username for a user on firebase after providing email and password. Could you clarify?

![image](https://user-images.githubusercontent.com/36213634/54029196-e17e3780-41a7-11e9-8e8c-6c41d6cc34ec.png)

**Comment by EddyVerbruggen** [comment]
`displayName` is a field from a provider (like Google or Facebook). When creating a user in Firebase itself, there is no `displayName` field. You could of course store this yourself in a record in Realtime DB or Firestore, but that's up to you.

**Comment by deytola** [comment]
Alright. Thanks a lot.
