### ISSUE TITLE
Module not found: Error: Can't resolve 'nativescript-plugin-firebase' in ng serve

### ISSUE THREAD

**Issue by yayagabay** [EddyVerbruggen/nativescript-plugin-firebase#1170]
Module not found: Error: Can't resolve 'nativescript-plugin-firebase' in ng serve command 
pls help me eddy? :) i want to build my app to android and ios and web ..

**Comment by EddyVerbruggen** [comment]
This is not really a comprehensive bugreport, is it? :)

**Comment by yayagabay** [comment]
what do u want me to mention more?

**Comment by yayagabay** [comment]
the import // const firebase = require("nativescript-plugin-firebase");
doesnt work in ng serve...

**Comment by EddyVerbruggen** [comment]
What’s ng serve doing? Running in a browser? Perhaps share a repo to make things more clear.

**Comment by yayagabay** [comment]
not sure how to share a repo.
yeah its running in a browser.
but it doesnt compile because it doesnt found module
nativescript-plugin-firebase... :(

‫בתאריך יום ו׳, 8 במרץ 2019 ב-19:31 מאת ‪Eddy Verbruggen‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by EddyVerbruggen** [comment]
Yeah but that plugin is meant for iOS and Android, not for a browser. So just don't include it for web..

**Comment by yayagabay** [comment]
how do i not include it in my web? its inside the home.component.ts..


‫בתאריך יום ו׳, 8 במרץ 2019 ב-21:31 מאת ‪Eddy Verbruggen‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by EddyVerbruggen** [comment]
That's really up to your code sharing setup, not an issue with this plugin.

**Comment by yayagabay** [comment]
but its happening only when i import your firebase.. where should i put it
to not enable it while compiling web..
i dont understand really.

‫בתאריך יום ו׳, 8 במרץ 2019 ב-21:58 מאת ‪Eddy Verbruggen‬‏ <‪
notifications@github.com‬‏>:‬
