### ISSUE TITLE
Error in firebase.login: TypeError: Cannot read property 'getInstance' of undefined JS: TypeError: Cannot read property 'getInstance' of undefined

### ISSUE THREAD

**Issue by daddach** [EddyVerbruggen/nativescript-plugin-firebase#1171]
i try to use firebase plugin in my nativescript (with Angular) project

firebase.init works fine with
```
firebase.init({
            showNotificationsWhenInForeground: true
        }).then(
            () => {
                console.log('firebase.init done');
            },
            (error) => {
                console.log(`firebase.init error: ${error}`);
            }
        );
```
but if i try to call:
```
firebase.login({
            type: firebase.LoginType.PASSWORD,
            passwordOptions: {
                email: this.user.email,
                password: this.user.password
            }
        })
        .then((result) => JSON.stringify(result))
        .catch((error) => console.log(error));
```

then i got this error: ` Error in firebase.login: TypeError: Cannot read property 'getInstance' of undefined`.

i have already enabled email-password login in my firebase instance. and this is my firebase.nativescript.json:

```
{
    "external_push_client_only": false,
    "using_ios": true,
    "using_android": true,
    "firestore": true,
    "realtimedb": false,
    "authentication": true,
    "remote_config": false,
    "performance_monitoring": false,
    "messaging": true,
    "crashlytics": false,
    "crash_reporting": false,
    "storage": false,
    "functions": false,
    "facebook_auth": false,
    "google_auth": false,
    "admob": false,
    "invites": false,
    "dynamic_links": false,
    "ml_kit": false
}
```

any suggestions please

**Comment by EddyVerbruggen** [comment]
Please share a repo and reopen.

**Comment by daddach** [comment]
thanks for your reply. what do you mean with repo sharing?

**Comment by EddyVerbruggen** [comment]
Pushing the code to github so I can reproduce the issue.

**Comment by Omi231** [comment]
i am having the same issue. Everything is working fine except authentication. I have also tried reinstalling plugin and removing platform.

Giving me error when trying to login anonymously or with email password it gives this error:
`Login error: {"code":"auth/exception","message":"TypeError: Cannot read property 'getInstance' of undefined"}`

**Comment by b02505048** [comment]
I solved this issue with simply rerun `npm run config` in `node_modules/nativescript-plugin-firebase`
Give it a try guys ;-)

**Comment by Omi231** [comment]
@b02505048 I already did that but it didn't work for me.

**Comment by daddach** [comment]
I solved this issue with
```
rm -rf platforms && rm -rf node_modules
```
then

```
tns run <plattform>
```
