### ISSUE TITLE
Background notifications not working

### ISSUE THREAD

**Issue by codingsett** [EddyVerbruggen/nativescript-plugin-firebase#1173]
Hello i have tried every fix that has been suggested in previous issues but i cant get notifications to show when the app is killed completely. 

I have added this to my gradle file
```
dependencies {
  compile "com.google.firebase:firebase-messaging:17.4.0"
}
```

and also this to my manifest

```
 <service android:name="org.nativescript.plugins.firebase.MyFirebaseInstanceIDService">
            <intent-filter>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
            </intent-filter>
        </service>
        <service android:name="org.nativescript.plugins.firebase.MyFirebaseMessagingService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT"/>
            </intent-filter>
        </service>
```

I have also usednMessageReceivedCallback but to no avail. Any help would be appreciated thanks!

**Comment by EddyVerbruggen** [comment]
Those changes should not be needed. Please share your repo.

**Comment by codingsett** [comment]
I created a new app to recreate the issue here is the link to the repo

https://github.com/codingsett/NativescriptTestNotification

**Comment by EddyVerbruggen** [comment]
Let's move discussions [there](https://github.com/codingsett/NativescriptTestNotification/issues/1).
