### ISSUE TITLE
[iOS Performance Monitoring]: traces are not started automatically

### ISSUE THREAD

**Issue by Frederiks96** [EddyVerbruggen/nativescript-plugin-firebase#1175]
The current implementation of performance monitoring does not start traces on iOS - it only creates them. However, it does not expose an API to start the traces with. In `performance.ios.js` on line 5 the current implementation is:
```
return new FirebaseTrace(FIRPerformance.sharedInstance().startTraceWithName(name));
```
However, as the [documentation from Google](https://firebase.google.com/docs/reference/ios/firebaseperformance/api/reference/Classes/FIRPerformance#/c:objc(cs)FIRPerformance(im)traceWithName:) says, this does _not_ start the trace. Instead, we should use the class function `startTraceWithName` ([docs](https://firebase.google.com/docs/reference/ios/firebaseperformance/api/reference/Classes/FIRPerformance#/c:objc(cs)FIRPerformance(cm)startTraceWithName:)):
```
return new FirebaseTrace(FIRPerformance.startTraceWithName(name));
```

**Comment by EddyVerbruggen** [comment]
Good point! I'll change that.
