### ISSUE TITLE
Not working for ios on device

### ISSUE THREAD

**Issue by vforv** [EddyVerbruggen/nativescript-plugin-firebase#1177]
There is some problem with plugin I am trying to make it work whole day for ios, but no luck.

I did all steps:

- Created app id
- Created dev certs and send box push notification cert
- Then created provisioning profile
- Added certs to firebase console

All installed and started app on device like this:

`tns run ios --bundle --provision 7672d288-d708-4dfb-xh02-99c84r127588`

When I try to send notification with curl it returns:

> {"multicast_id":8514483219876853447,"success":0,"failure":1,"canonical_ids":0,"results":[{"error":"NotRegistered"}]

**Comment by EddyVerbruggen** [comment]
Share a repo and I may take a look.

**Comment by vforv** [comment]
It was problem with App ID, my app ID was look like this: io.imenu.imenu, when I changed bundle id it works but now problem is I need to remove app, change bundle id and, create app again and wait for review... 
Do you know why this bundle id create problem with registration  io.imenu.imenu ?
