### ISSUE TITLE
Can't add the nativescript firebase plugin to my app

### ISSUE THREAD

**Issue by indiggojorge** [EddyVerbruggen/nativescript-plugin-firebase#1179]
Hi. I am unable to add the nativescript firebase plugin to my app. It appears to be an issue with certain versions of dependent plugins. I try updating or adding the plugins but never seem to get anywhere. Am I missing something?

I execute the following command in my project folder ...
"tns plugin add nativescript-plugin-firebase"

... and I get the following ...

Error while loading nativescript-angular-cli is: Default commands should be required before child commands

> nativescript-plugin-firebase@8.0.0 postinstall /Users/Jorge/dev/ns/indiggo-mobile/node_modules/nativescript-plugin-firebase
> node postinstall-hooks.js && node scripts/postinstall.js

Hook already installed: nativescript-plugin-firebase at location: /Users/Jorge/dev/ns/indiggo-mobile/hooks/before-prepare
Hook already installed: nativescript-plugin-firebase at location: /Users/Jorge/dev/ns/indiggo-mobile/hooks/after-prepare
/Users/Jorge/dev/ns/indiggo-mobile/node_modules/nativescript-plugin-firebase/scripts/postinstall.js:1215
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version: Error while loading nativescript-angular-cli is: Default commands should be required before child commands
5.2.3

    at new SemVer (/Users/Jorge/dev/ns/indiggo-mobile/node_modules/nativescript-plugin-firebase/scripts/postinstall.js:1215:11)
    at compare (/Users/Jorge/dev/ns/indiggo-mobile/node_modules/nativescript-plugin-firebase/scripts/postinstall.js:1488:10)
    at Function.gte (/Users/Jorge/dev/ns/indiggo-mobile/node_modules/nativescript-plugin-firebase/scripts/postinstall.js:1537:10)
    at Object.<anonymous> (/Users/Jorge/dev/ns/indiggo-mobile/node_modules/nativescript-plugin-firebase/scripts/postinstall.js:4182:86)
    at __webpack_require__ (/Users/Jorge/dev/ns/indiggo-mobile/node_modules/nativescript-plugin-firebase/scripts/postinstall.js:20:30)
    at /Users/Jorge/dev/ns/indiggo-mobile/node_modules/nativescript-plugin-firebase/scripts/postinstall.js:66:18
    at Object.<anonymous> (/Users/Jorge/dev/ns/indiggo-mobile/node_modules/nativescript-plugin-firebase/scripts/postinstall.js:69:10)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
npm WARN @angular/compiler-cli@7.2.9 requires a peer of @angular/compiler@7.2.9 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/platform-browser-dynamic@7.2.0 requires a peer of @angular/compiler@7.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@4.5.0 requires a peer of @angular/compiler@>=2.3.1 <8.0.0 || >7.0.0-beta <8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN nativescript-angular@7.2.1 requires a peer of @angular/compiler@~7.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN nativescript-mixpanel@2.0.1 requires a peer of tns-core-modules@^3.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nativescript-plugin-firebase@8.0.0 postinstall: `node postinstall-hooks.js && node scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nativescript-plugin-firebase@8.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Jorge/.npm/_logs/2019-03-15T18_33_09_199Z-debug.log
Command npm failed with exit code 1

**Comment by indiggojorge** [comment]
I think the main issue is that mixpanel wants tns-core-modules@^3.0.0 but  nativescript-angular@7.2.1 want tns-core-modules@^5.1.0 || >5.1.0- || >5.2.0-. How do I resolve that?

**Comment by indiggojorge** [comment]
This issue is an environment issue and not a plugin issue.

**Comment by dhairya0704** [comment]
I am facing the same issue. Can you please guide me through this?

**Comment by dhairya0704** [comment]
> This issue is an environment issue and not a plugin issue.
Can you please guide me the steps to resolve it?
