### ISSUE TITLE
Messaging cannot receive data on ios device

### ISSUE THREAD

**Issue by khhily** [EddyVerbruggen/nativescript-plugin-firebase#1183]
I use `nativescript-plugin-firebase` in by project, and I receive push data well on android devices, but when I test it on ios real device, there's an error.  the app had been terminated.

The error log is here:

***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x105707370 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x105737dec NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
3   0x10619c494 ffi_closure_SYSV_inner
4   0x1061a01b4 .Ldo_closure
5   0x104c2b850
6   0x104c48e44
7   0x104c486c4
8   0x104c3dba4
9   0x104c32708
10  0x104c383f4
11  0x104c366a8
12  0x104c57ff4
13  0x104c577a4
14  0x104c55b80
15  0x22eb0cf44 <redacted>
16  0x22eb0a048 <redacted>
17  0x22eb09e28 <redacted>
18  0x22f21b670 <redacted>
19  0x22f220f40 <redacted>
20  0x22f21cc78 <redacted>
21  0x22eb014bc <redacted>
22  0x22eafa0e0 <redacted>
23  0x22eafa060 <redacted>
24  0x22eaf9944 <redacted>
25  0x22eaf4810 <redacted>
26  0x22eaf40e0 CFRunLoopRunSpecific
27  0x230d6d584 GSEventRunModal
28  0x25be88c00 UIApplicationMain
29  0x1061a0044 ffi_call_SYSV
30  0x10619bbb4 ffi_call_int
31  0x10619b6b0 ffi_call
JavaScript stack trace:
1   @file:///app/tns_modules/nativescript-plugin-firebase/messaging/messaging.js:307:30
2   forEach@[native code]
3   updateUserInfo@file:///app/tns_modules/nativescript-plugin-firebase/messaging/messaging.js:305:38
4   @file:///app/tns_modules/nativescript-plugin-firebase/messaging/messaging.js:365:31
5   messagingDidReceiveMessage@file:///app/tns_modules/nativescript-plugin-firebase/messaging/messaging.js:515:22
6   UIApplicationMain@[native code]
7   start@file:///app/tns_modules/tns-core-modules/application/application.js:275:26
8   run@file:///app/tns_modules/tns-core-modules/application/application.js:303:10
9   bootstrapNativeScriptApp@file:///app/tns_modules/nativescript-angular/platform-common.js:188:26
10  bootstrapApp@file:///app/tns_modules/nativescript-angular/platform-common.js:106:38
11  bootstrapModule@file:///app/tns_modules/nativescript-angular/platform-common.js:90:26
12  anonymous@file:///app/main.js:7:57
13  evaluate@[native code]
14  moduleEvaluation@[native code]
15  promiseRea<\M-b\M^@\M-&>
JavaScript error:
file:///app/tns_modules/nativescript-plugin-firebase/messaging/messaging.js:307:30: JS ERROR TypeError: Attempted to assign to readonly property.
*** JavaScript call stack:
(
0   UIApplicationMain@[native code]
1   start@file:///app/tns_modules/tns-core-modules/application/application.js:275:26
2   run@file:///app/tns_modules/tns-core-modules/application/application.js:303:10
3   bootstrapNativeScriptApp@file:///app/tns_modules/nativescript-angular/platform-common.js:188:26
4   bootstrapApp@file:///app/tns_modules/nativescript-angular/platform-common.js:106:38
5   bootstrapModule@file:///app/tns_modules/nativescript-angular/platform-common.js:90:26
6   anonymous@file:///app/main.js:7:57
7   evaluate@[native code]
8   moduleEvaluation@:1:11
9   promiseReactionJob@:1:11
)
*** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: TypeError: Attempted to assign to readonly property.
at
1   @file:///app/tns_modules/nativescript-plugin-firebase/messaging/messaging.js:307:30
2   forEach@[native code]
3   updateUserInfo@file:///app/tns_modules/nativescript-plugin-firebase/messaging/messaging.js:305:38
4   @file:///app/tns_modules/nativescript-plugin-firebase/messaging/messaging.js:365:31
5   messagingDidReceiveMessage@file:///app/tns_modules/nativescript-plugin-firebase/messaging/messaging.js:515:22
6   UIApplicationMain@[native code]
7   start@file:///app/tns_modules/tns-core-modules/application/application.js:275:26
8   run@file:///app/tns_modules/tns-core-modules/application/application.js:303:10
9   bootstrapNativeScriptApp@file:///app/tns_modules/nativescript-angular/platform-common.js:188:26
10  bootstrapApp@file:///app/tns_modules/nativescript-angular/platform-common.js:106:38
11  bootstrapModule@file:///app/tns_modules/nativescript-ang<\M-b\M^@\M-&>
Retrieving resting unlock: 0

This is my test-project on github.
[https://github.com/khhily/test_ns_firebase.git](https://github.com/khhily/test_ns_firebase.git),

could anyone help me to see how to fix it?

**Comment by EddyVerbruggen** [comment]
What's the exact payload you're sending? Looks like there's something in the `data` object of the notification that's not expected.

**Comment by khhily** [comment]
my payload like this:
![image](https://user-images.githubusercontent.com/13519063/54739826-60399280-4bf4-11e9-8752-3c349b042467.png)

**Comment by EddyVerbruggen** [comment]
The problem *I think* is the name of the nested `data` object. Can you change that to literally anything else?

**Comment by khhily** [comment]
I try to change the `data` key to `content`, and it works. thank you very much.

**Comment by EddyVerbruggen** [comment]
Cool! I'll see if I can make the plugin more compatible with `data`. Cheers!
