### ISSUE TITLE
Terminating app due to uncaught exception 'NativeScript encountered a fatal error: ReferenceError: Can't find variable: FIRVision at

### ISSUE THREAD

**Issue by AquilesOliveira** [EddyVerbruggen/nativescript-plugin-firebase#1186]
This problem only happens in iOS, do we have any solution?

**Comment by leevigraham** [comment]
@AquilesOliveira Did you solve this issue?

**Comment by leevigraham** [comment]
For anyone else looking at this ticket… I think the issue was I was building the app on a case-sensitive drive. As a result the Podfile was not being created and the deps were not loaded. 

Link to issue: https://github.com/NativeScript/nativescript-cli/issues/5159

**Comment by AquilesOliveira** [comment]
@leevigraham Yes, after update a plugin version.

**Comment by leevigraham** [comment]
@AquilesOliveira probably worth closing this ticket then :)

**Comment by HulioEglesias** [comment]
I got same error. But I just now install plugin and create project `tns project` from blank template.
![image](https://user-images.githubusercontent.com/15662060/80777694-7c418e80-8b7f-11ea-9a97-1a7b64be8d14.png)
