### ISSUE TITLE
There is no "getIdToken" method on firebase.auth().currentUser?

### ISSUE THREAD

**Issue by danu165** [EddyVerbruggen/nativescript-plugin-firebase#1189]
I am currently trying to check an id token in cloud functions that are sent from my native script app. I am following the documentation here:
https://firebase.google.com/docs/auth/admin/verify-id-tokens

However, when I try to retrieve the token from the client with this line, I get the error listed below
`firebase.auth().currentUser.getIdToken(/* forceRefresh */ true).then(function(idToken) {
  // Send token to your backend via HTTPS
  // ...
}).catch(function(error) {
  // Handle error
});`

Error:
`Property 'getIdToken' does not exist on type 'User'.ts(2339)`

Is there another way to accomplish this or am I doing something wrong here?

**Comment by EddyVerbruggen** [comment]
Correct, it's not implemented on the User in the plugin, so I'll leave this open as a feature request to make it compatible with the Web API.

In the meanwhile, check this: https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/AUTHENTICATION.md#getauthtoken

**Comment by EddyVerbruggen** [comment]
Here you go: https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/AUTHENTICATION.md#getauthtoken--getidtoken, I'll release 8.1.1 later today.
