### ISSUE TITLE
Feature Request: Upload Progress

### ISSUE THREAD

**Issue by colinskow** [EddyVerbruggen/nativescript-plugin-firebase#119]
I would like to be able to setup an `onProgress` listener to display a progress bar as the user uploads files. This is definitely present in the Android and IOS native APIs so it is just a matter of translating it to Javascript on both platforms.

**Comment by EddyVerbruggen** [comment]
Correct, that wouldn't be too hard to add. Would you like giving it a shot perhaps?

**Comment by colinskow** [comment]
I could give it a shot. I'm from the Javascript world and have zero experience with iOS and native code. The Firebase docs are fairly clear, I'd just need to figure out how to translate to Javascript. Your source code has some good examples of how to do it. I'll take a look and let you know if I run into trouble.

**Comment by EddyVerbruggen** [comment]
Then you already know the most important language 😄 

Of course, let me know if you run into something, godspeed!

**Comment by EddyVerbruggen** [comment]
I'll take a look as I'm about to release a new version.

**Comment by EddyVerbruggen** [comment]
Just adde support for an `onProgress` callback function to 3.6.0. See [the doc](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/STORAGE.md#uploadfile) for details.

**Comment by colinskow** [comment]
Woo hoo!
