### ISSUE TITLE
Using Non-Firebase Push Messaging with other Firebase Services

### ISSUE THREAD

**Issue by alfonsocj** [EddyVerbruggen/nativescript-plugin-firebase#1198]
Hello, I've been trying to use Crashlytics and Analytics along with Non-Firebase Push Messaging for iOS.

It works for iOS if I use these settings
```
{
  "external_push_client_only": false,
  "using_ios": true,
  "using_android": true,
  "firestore": false,
  "realtimedb": false,
  "authentication": false,
  "remote_config": false,
  "performance_monitoring": true,
  "messaging": false,
  "in_app_messaging": false,
  "crashlytics": true,
  "crash_reporting": false,
  "storage": false,
  "functions": false,
  "facebook_auth": false,
  "google_auth": false,
  "admob": false,
  "invites": false,
  "dynamic_links": false,
  "ml_kit": false
}
```

but that makes Android crash because `org.nativescript.plugins.firebase` is not setup since in the settings I have `messaging: false`.

Is there a way to use Non-Firebase Push Messaging along with other Firebase services?

**Comment by btulsi-ygrene** [comment]
+1 Also facing this issue

**Comment by alfonsocj** [comment]
@btulsi-ygrene This issue was solved on https://github.com/EddyVerbruggen/nativescript-plugin-firebase/pull/1201
