### ISSUE TITLE
Cannot read property 'PASSWORD' of undefined

### ISSUE THREAD

**Issue by mikeres0** [EddyVerbruggen/nativescript-plugin-firebase#12]
I am attempting to use this plugin, however I receive an error message when trying to log in. I have enabled Email & Password Authentication within the Firebase App Dashboard, so I don't think the issue is with that. Below is the code that I am using to log in. My idea is that ```loginType``` is undefined, as I know firebase is defined as the ```init()``` function works correctly. 

```
firebase.login({
	type: firebase.loginType.PASSWORD,
	email: email.text,
	password: password.text
}).then(
	function(response){
		for (i in response){
			console.log(i + " || " + response[i])
		}
	}
)
```

**Comment by mikeres0** [comment]
In the examples in the readme.md file the code reads:

**Comment by mikeres0** [comment]
```firebase.loginType.PASSWORD``` should actually be ```firebase.LoginType.PASSWORD```.

**Comment by sflament** [comment]
Thank's a lot Mike, I was facing the same issue.
With uppercase Login, it's ok now.

**Comment by EddyVerbruggen** [comment]
Thanks! A small tip if I may: please use TypeScript, the definition in there should be correct.

**Comment by JayBit33** [comment]
Having the same issue. What was the resolution. 
firebase.login({
        type: firebase.loginType.PASSWORD,
        passwordOptions: {
          email: this.email,
          password: this.password
        }
      })

**Comment by JayBit33** [comment]
Here is the solution I found for anyone else needing it. use this import in your component
const firebase = require('@nativescript/firebase/app');
and call
firebase.auth().signInWithEmailAndPassword(this.email, this.password)
