### ISSUE TITLE
Chaining range types

### ISSUE THREAD

**Issue by austinlarue** [EddyVerbruggen/nativescript-plugin-firebase#120]
Is it possible to chain range type queries with this plugin like in the official API? This is from the official firebase documentation:
[https://firebase.google.com/docs/database/server/retrieve-data#range-queries](https://firebase.google.com/docs/database/server/retrieve-data#range-queries)

`dinosaursRef.orderByKey().startAt("b").endAt("b\uf8ff").addChildEventListener...`

**Comment by EddyVerbruggen** [comment]
That's from the server API, [this is Android](https://firebase.google.com/docs/database/android/retrieve-data), but it's the same principle.

At the moment you can't combine those, but it would be a great addition!

**Comment by EddyVerbruggen** [comment]
Just added support in version 3.6.0, please see [the doc](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/DATABASE.md#query) for details; you can now use `ranges` in addition to `range`.

**Comment by austinlarue** [comment]
Thanks for the quick response Eddy!
