### ISSUE TITLE
In App Messaging throws this error

### ISSUE THREAD

**Issue by tanekim77** [EddyVerbruggen/nativescript-plugin-firebase#1203]
When building with Firebase In App Messaging enabled, it throws this now. It was working before.

/Users/apple/Desktop/CSP/CAKE-Mobile/platforms/ios/Pods/FirebaseInAppMessagingDisplay/Firebase/InAppMessagingDisplay/ImageOnly/FIDImageOnlyViewController.m:154:29: error: property 'renderAsTestMessage' not found on object of
      type 'FIRInAppMessagingImageOnlyDisplay *'
  if (self.imageOnlyMessage.renderAsTestMessage)

**Comment by aeliusdev** [comment]
Same issue here

**Comment by EddyVerbruggen** [comment]
Hi, I don't see that specific issue, but indeed there seems to be some sort of build issue with InAppMessaging enabled.

Note that I don't officially support it yet (there's no mention in [the docs](https://github.com/EddyVerbruggen/nativescript-plugin-firebase#features) yet), but this is obviously not what I intended either.

Which cocoapods version are you using? `pod --version`, and which NativeScript version? `tns --version`.

**Comment by EddyVerbruggen** [comment]
Btw, the implementation of InAppMessaging on iOS was blocked by issues with the appdelegate, but it looks like that can be fixed by implementing this: https://github.com/firebase/firebase-ios-sdk/pull/2354

Also, bumping the iOS Firebase SDK to the latest version seems to get rid of the build error I'm seeing, so this issue should be fixed soon.

**Comment by tanekim77** [comment]
I remember updating pod and tns to the latest version last week, and it still didn't work.

**Comment by HugoAntares** [comment]
@EddyVerbruggen you closed this issue. But I still have the problem. Should I update something ?

**Comment by EddyVerbruggen** [comment]
I added the 8.2.0 milestone didn’t I? I’m on mobile so hard to check that quickly.

**Comment by HugoAntares** [comment]
@EddyVerbruggen indeed, the milestone 8.2.0 exists. Do you know when it'll be published ?

**Comment by EddyVerbruggen** [comment]
Working my ass of to get it out of the door. Hoping tomorrow.
