### ISSUE TITLE
[Android] Firebase.init fails on Android

### ISSUE THREAD

**Issue by MustafaCa** [EddyVerbruggen/nativescript-plugin-firebase#1204]
Hi Eddy,

The app works fine on iOS. It used to work fine on Android as well - last tested on Android back in January or February. 

Now, I get "_Error in firebase.init: Error: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.XXX. Make sure to call FirebaseApp.initializeApp(Context) first_" when I called **firebase.init**.

Any suggestions? Thank you!
-Mustafa.

**Comment by EddyVerbruggen** [comment]
Without a repo to look at it's quite impossible to comment.

**Comment by MustafaCa** [comment]
Thanks for the quick reply. Looks like it was about the missing link between the firebase project and the admob app. In the mean time, I also updated all the npm modules. Everything looks works fine again.

BTW, thank you for building and sharing such a useful plug-in.

**Comment by EddyVerbruggen** [comment]
Ah nice, and thank you!
