### ISSUE TITLE
Error in firebase.login: Error: android.content.res.Resources$NotFoundException: String resource ID #0x0

### ISSUE THREAD

**Issue by mosesweb** [EddyVerbruggen/nativescript-plugin-firebase#1208]
Hi I am getting this error below. Not sure what to do as I've been trying a lot. This happens when I am calling the login method.

> Error in firebase.login: Error: android.content.res.Resources$NotFoundException: String resource ID #0x0

I started getting this on my app I've been working on so I tested to create a completetly new project with angular. Downloaded this plugin and added my app to firebase, downloaded the google service file and added it. But I keep getting the above error when calling firebase.login with google as a type. My code can be viewed at: https://github.com/mosesweb/testapp
```

firebase.login({
            type: firebase.LoginType.GOOGLE,
          }).then(
              function (result) {
                JSON.stringify(result);
              },
              function (errorMessage) {
                console.log(errorMessage);
              }
          );
```

> 
> Error in firebase.login: Error: android.content.res.Resources$NotFoundException: String resource ID #0x0
> JS:     android.content.res.Resources.getText(Resources.java:335)
> JS:     android.content.res.Resources.getString(Resources.java:381)
> JS:     com.tns.Runtime.callJSMethodNative(Native Method)
> JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1203)
> JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1083)
> JS:     com.tns.Runtime.callJSMethod(Runtime.java:1070)
> JS:     com.tns.Runtime.callJSMethod(Runtime.java:1050)
> JS:     com.tns.Runtime.callJSMethod(Runtime.java:1042)
> JS:     com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:20)
> JS:     android.app.Activity.performCreate(Activity.java:6679)
> JS:     android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
> JS:     android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
> JS:     android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
> JS:     android.app.ActivityThread.-wrap12(ActivityThread.java)
> JS:     android.app.ActivityThread$H....
> JS: Error: android.content.res.Resources$NotFoundException: String resource ID #0x0
> JS:     android.content.res.Resources.getText(Resources.java:335)
> JS:     android.content.res.Resources.getString(Resources.java:381)
> JS:     com.tns.Runtime.callJSMethodNative(Native Method)
> JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1203)
> JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1083)
> JS:     com.tns.Runtime.callJSMethod(Runtime.java:1070)
> JS:     com.tns.Runtime.callJSMethod(Runtime.java:1050)
> JS:     com.tns.Runtime.callJSMethod(Runtime.java:1042)
> JS:     com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:20)
> JS:     android.app.Activity.performCreate(Activity.java:6679)
> JS:     android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
> JS:     android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
> JS:     android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
> JS:     android.app.ActivityThread.-wrap12(ActivityThread.java)
> JS:     android.app.ActivityThread$H.handleMessage(ActivityThr...

**Comment by mosesweb** [comment]
Changed to try with anonymous login instead: type: firebase.LoginType.ANONYMOUS
Got this strange error instead. Any advice?

> 
> JS: Logging in the user failed. com.google.firebase.FirebaseException: An internal error has occurred. [ ADMIN_ONLY_OPERATION ]
> JS: Trouble in paradise: Logging in the user failed. com.google.firebase.FirebaseException: An internal error has occurred. [ ADMIN_ONLY_OPERATION ]

**Comment by weps84** [comment]
I've have the same trouble :(

**Comment by EddyVerbruggen** [comment]
This *may* be fixed in 8.3.0, but without a full stacktrace and a reproduction path it's hard to say for sure.

**Comment by weps84** [comment]
Hi all,

I've solved this case adding the "default_web_client_id" to string.xml file in App > App_Resources > Android > .... > values > string.xml

<string name="default_web_client_id">web_client_id</string>

This value you can found in Firebase > Android > Authentication > Google > Web Sdk Configuration.

Best regards

**Comment by mosesweb** [comment]
> Hi all,
> 
> I've solved this case adding the "default_web_client_id" to string.xml file in App > App_Resources > Android > .... > values > string.xml
> 
> web_client_id
> 
> This value you can found in Firebase > Android > Authentication > Google > Web Sdk Configuration.
> 
> Best regards

Hey it is great news to hear you found this! I shall try it myself.
