### ISSUE TITLE
Using database persist feature makes data less secure?

### ISSUE THREAD

**Issue by Omi231** [EddyVerbruggen/nativescript-plugin-firebase#1210]
Recently i came to know that anyone having rooted Android device/emulator can easily access app data stored locally. Does this apply on firebase cached data also? If yes, then how can I make it more secure?

or at least how can i stop firebase from storing some parts of database locally?

**Comment by EddyVerbruggen** [comment]
That's a question you should ask on the Firebase repo or StackOverflow.
