### ISSUE TITLE
Push Notification not appearing [Android]

### ISSUE THREAD

**Issue by Manbearpixel** [EddyVerbruggen/nativescript-plugin-firebase#1211]
I've been following these two guides:
- https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/MESSAGING.md
- https://github.com/eddyverbruggen/nativescript-plugin-firebase/blob/HEAD/docs/NON_FIREBASE_MESSAGING.md

I tested out a push notification via POSTMAN and saw the response successfully in the logs:
```
JS: 2Push message received in push-view-model: {"foreground":true,"from":"138392321396","data":{}}
JS: 2Push message received in push-view-model: {"foreground":false,"from":"138392321396","data":{}}
```

But no notification popped up on the screen. I have configured it initially with:
```
firebase.init({
      // Optionally pass in properties for database, authentication and cloud messaging,
      // see their respective docs.
      showNotifications: true,
      showNotificationsWhenInForeground: true
}) ...
```

i'm running this application on a real Android device. I've tested receiving a notification through the Firebase UI and it pops up. Not sure what else I need to do here.

The handler function looks like this:
```
messaging.addOnMessageReceivedCallback(
      message => {
        console.log("2Push message received in push-view-model: " + JSON.stringify(message, getCircularReplacer()));
      }
    ).then(() => {
      console.log("Added addOnMessageReceivedCallback");
    }, err => {
      console.log("Failed to add addOnMessageReceivedCallback: " + err);
    });
```

**Comment by Manbearpixel** [comment]
I've seemed to figure out the problem. I was setting up the message according to these docs on the Firebase website:

https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages

I realize that in the guides listed above you had a different configuration when testing a message. Not sure why the resource above was incorrect. Closing for now!

**Comment by Whip** [comment]
Can you specify what exactly did you change to make it work? I'm facing the same issue.
