### ISSUE TITLE
Crash running demo on iOS

### ISSUE THREAD

**Issue by KkevinLi** [EddyVerbruggen/nativescript-plugin-firebase#1216]
On master when I run `npm run demo.ios` I get the following error:

```Uncaught NativeScript Error: Error: The Google Mobile Ads SDK was initialized incorrectly. Google AdMob publishers should follow instructions here: https://googlemobileadssdk.page.link/admob-ios-update-plist to include the AppMeasurement framework, set the -ObjC linker flag, and set GADApplicationIdentifier with a valid App ID. Google Ad Manager publishers should follow instructions here: https://googlemobileadssdk.page.link/ad-manager-ios-update-plist```

**Comment by EddyVerbruggen** [comment]
Yep, thanks for the heads-up. I'm working on upgrading the native SDKs on both platforms to their latest versions and this seems to be a breaking change I have to iron out.

**Comment by EddyVerbruggen** [comment]
For others reading this: there's no published version on npm with this issue, so don't worry about it.

**Comment by EddyVerbruggen** [comment]
This will be required from 8.2.0 (a similar change had to be added to the Android manifest since 7.4.0): https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/ADMOB.md#ios
