### ISSUE TITLE
Increment Feature in Firestore. 

### ISSUE THREAD

**Issue by ShyshkovOleg** [EddyVerbruggen/nativescript-plugin-firebase#1225]
Is it possible to add INCREMENT() func to Firestore  when updatind document? Would be nice.
```
washingtonRef.update({
    population: firebase.firestore.FieldValue.increment(50)
});
```

**Comment by EddyVerbruggen** [comment]
Hi! Thanks for the feature request. The [Android SDK changelog](https://firebase.google.com/support/release-notes/android) tells me it has been added in the latest version of the Android Firebase SDK (8.2.0), so this would be possible.

Same for iOS, on [march 19th](https://firebase.google.com/support/release-notes/ios).

**Comment by EddyVerbruggen** [comment]
Code, demo, and docs updated. Will be part of the next release.
