### ISSUE TITLE
iOS - Application Delegate Overwritten

### ISSUE THREAD

**Issue by KkevinLi** [EddyVerbruggen/nativescript-plugin-firebase#1232]
```
import { CustomAppDelegate } from "./custom-app-delegate";

application.ios.delegate = CustomAppDelegate;
```
Having ^ in `main.ts` and initializing Firebase in the `AppComponent.ngOnInit` will result in the customAppDelegate's `applicationDidFinishLaunchingWithOptions()` not being called.

**Comment by EddyVerbruggen** [comment]
Correct, but (depending on which Firebase features you need) this has been fixed in 8.3.0 (unreleased).

**Comment by KkevinLi** [comment]
I looked at the commit and noticed that Firebase Messaging would override the app delegate. How would we get around this if we do not want messaging for iOS, but want it for android?

**Comment by EddyVerbruggen** [comment]
Good question. Any suggestions?

**Comment by KkevinLi** [comment]
Ideally we wouldn't pull in Firebase/Messaging if it isn't needed (Is this possible? I see https://github.com/EddyVerbruggen/nativescript-plugin-firebase/pull/1201 but I am not sure if this will cause potential issues) . If this isn't possible perhaps we can have a flag in the info.plist which we use to check if we should override the delegate (Kind of hacky and we not have an unused Firebase/Messaging pod pulled in).

**Comment by EddyVerbruggen** [comment]
Looks like that PR you referred to should indeed do the trick. [Doc](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/NON_FIREBASE_MESSAGING.md) updated as well. Will release 8.3.0 soon.
