### ISSUE TITLE
Google auth without firebase

### ISSUE THREAD

**Issue by vahidvdn** [EddyVerbruggen/nativescript-plugin-firebase#1233]
Is it possible to use this plugin's native google auth without firebase?? I want to open the native google popup and then verify the user by my own server, based on his `id_token` (received from google), not the firebase. (I mean something similar to [this ](https://github.com/EddyVerbruggen/cordova-plugin-googleplus)but for nativescript)

Is it possible?

**Comment by EddyVerbruggen** [comment]
No. Isn't there a Google Sign-In plugin for {N} at all?

**Comment by vahidvdn** [comment]
@EddyVerbruggen Yes, there is. [nativescript-social-login](https://github.com/mkloubert/nativescript-social-login) is the way I go. But it would be really nice to support it because I must install nativescript-plugin-firebase for my non-firebase push messaging.

**Comment by EddyVerbruggen** [comment]
I understand, but I don't want to create any more maintenance burden for myself by adding even more features. I don't mind anyone adding (and maintaining) it through a PR though.
