### ISSUE TITLE
Using Firebase Firestore in a Nativescript Worker thread

### ISSUE THREAD

**Issue by nmandyam** [EddyVerbruggen/nativescript-plugin-firebase#1238]
Firestore works very well for me, but with even a midisize dataset (300 to 400 records), the snapshotting hangs the UI for 5 to 10 seconds, MUCH worse on 2-year-old phones. So I tried to move the snapshot into a Worker thread, but that crashes with the error below, as the point of firebase.login (the firebase.init works OK).
I understand this is not standard usage, but it may be of value to others like me, who  have larger datasets to deal with. Any ideas on how I could solve this problem?
Here's the error. Thanks!

```
JS: Error in firebase.login: Error: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
JS:     com.google.android.gms.common.GooglePlayServicesUtilLight.isGooglePlayServicesAvailable(Unknown Source:12)
JS:     com.google.android.gms.common.GoogleApiAvailabilityLight.isGooglePlayServicesAvailable(Unknown Source:5)
JS:     com.google.android.gms.common.GoogleApiAvailability.isGooglePlayServicesAvailable(Unknown Source:94)
JS:     com.google.android.gms.common.GoogleApiAvailabilityLight.isGooglePlayServicesAvailable(Unknown Source:3)
JS:     com.google.android.gms.common.GoogleApiAvailability.isGooglePlayServicesAvailable(Unknown Source:93)
JS:     com.tns.Runtime.WorkerGlobalOnMessageCallback(Native Method)
JS:     com.tns.Runtime.access$400(Runtime.java:34)
JS:     com.tns.Runtime$WorkerThreadHandler.handleMessage(Runtime.java:338)
JS:     android.os.Handler.dispatchMessage(Handler.java:106)
JS:     android.os.Looper.loop(Looper.java:164)
JS:     android.os...
```

**Comment by EddyVerbruggen** [comment]
Can you share that worker code as well?

**Comment by EddyVerbruggen** [comment]
Perhaps the worker doesn't have access to the current activity (because it's off the main thread), so can you try and change this line

https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/5cd2a650885a40931f1223d58e2ebbbe45e3569b/src/firebase.android.ts#L514

in `node_modules/nativescript-plugin-firebase/firebase.android.js` to `var activity = appModule.android.context;`?

Then remove the `<approot>/platforms/android` folder and build again.

**Comment by nmandyam** [comment]
Unnfortunattely, that did not work - same error. Anything else I coould try?
May be unrelated: the code you've quoted is on line 458, not 514, in `node_modules/nativescript-plugin-firebase/firebase.android.js` in my install. I updated the plugin, too, no change - I assume that's because of ts compilation.
Thanks for checking this out!

**Comment by EddyVerbruggen** [comment]
Yes, that’s expected because of transpilation. 

Can you share a minimal repo with a worker I can clone?

**Comment by nmandyam** [comment]
Sorry this took so long. [Here's](https://bitbucket.org/nmandyam/evb_repo) a minimal set of code that behaves in the manner I've described above.

**Comment by EddyVerbruggen** [comment]
Thanks for sharing that demo, @nmandyam! Really helpful.

So that initial exception is easy to work around with by a little change in the plugin (pushed), but the next error is more problematic:

```
System.err: com.tns.NativeScriptException: Cannot find object id for instance=com.tns.gen.com.google.android.gms.tasks.OnCompleteListener@7f7cb4a
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1076)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1070)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1050)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1042)
System.err:     at com.tns.gen.com.google.android.gms.tasks.OnCompleteListener.onComplete(OnCompleteListener.java:16)
System.err:     at com.google.android.gms.tasks.zzj.run(Unknown Source)
System.err:     at android.os.Handler.handleCallback(Handler.java:751)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     at android.os.Looper.loop(Looper.java:154)
```

The problem here is that Android (by design) will invoke those callbacks on the main thread, while you created that callback in the worker thread (through the plugin).

I don't think there's a fix here as the Firestore functions also rely on this kind of callbacks.

Do you have any idea which part of the snapshotting is responsible for the freezes? Maybe if you can add that to the (ui thread) demo we can think of a better approach..

**Comment by nmandyam** [comment]
@EddyVerbruggen thank you for all the effort. Pity I can't use that method, but I figured out what was locking things up: the UI refresh. I use an ObservableArray and, since that does not refresh itself on update, I was refreshing the whole ListView that it was bound to. Further, I depended on the snapshot to build the ObservableArray, instead of doing a .get() and loading it up. Both fixed, plus a few other issues and performance has improved tremendously. Thanks again for putting me on the right track here. Although I would have liked it if I could have offloaded all Firestore triggers to a separate thread.
I wish ObservableArrays behaved like real arrays of Observables! :)

**Comment by EddyVerbruggen** [comment]
Appreciate the feedback and happy to read you've solved most of the perf issues. Kudos!

**Comment by johnwanjohi** [comment]
> @EddyVerbruggen thank you for all the effort. Pity I can't use that method, but I figured out what was locking things up: the UI refresh. I use an ObservableArray and, since that does not refresh itself on update, I was refreshing the whole ListView that it was bound to. Further, I depended on the snapshot to build the ObservableArray, instead of doing a .get() and loading it up. Both fixed, plus a few other issues and performance has improved tremendously. Thanks again for putting me on the right track here. Although I would have liked it if I could have offloaded all Firestore triggers to a separate thread.
> I wish ObservableArrays behaved like real arrays of Observables! :)

@nmandyam am still going through this; what should I do; please help; thanks in advance

**Comment by nmandyam** [comment]
@johnwanjohi I've completely gone away from relying on Observable Arrays to update the UI. I still use them to keep the data in sync, but in the events that update the ObservableArray, I also pull the array of items from the UI (using a getViewById on the ListView/RadListView that the ObservableArray is used in), loop through them and set the relevant element to the new value. In the XML of the view, I set a unique value to the id for each element, so I can use it later to identify which item to update. This mechanism is both fast and reliable, unlike setting the ObservableArray itself or setting the bindingContext of the current element on an event. Make sense?
