### ISSUE TITLE
Query return result

### ISSUE THREAD

**Issue by waleeddbnet** [EddyVerbruggen/nativescript-plugin-firebase#124]
I want to display the result.value on View List from Query function, i couldn't cause its only return result as char by char through JSON.stringfy, i would like to return  result.value as object so i can push it on array and view it on List, Please Help.
The Query Function defined as below:
` var onQueryEvent = function(result) 
  {
        // note that the query returns 1 match at a time
        // in the order specified in the query
        if (!result.error) {

            console.log("Event type: " + result.type);
            console.log("Key: " + result.key);
            console.log("Value: " +JSON.stringify(result.value));          
                    
    }
  }

    firebase.query(
        onQueryEvent,
        "/users",
        {
            // set this to true if you want to check if the value exists or just want the event to fire once
            // default false, so it listens continuously
            singleEvent: true,
            // order by company.country
            orderBy: {
                type: firebase.QueryOrderByType.CHILD,
                value: 'Key' // mandatory when type is 'child'
            },
            // but only companies named 'Telerik'
            // (this range relates to the orderBy clause)
            //range: {
              //  type: firebase.QueryRangeType.EQUAL_TO,
                //value: 'Bulgaria'
            //},
            // only the first 2 matches
            // (note that there's only 1 in this case anyway)
          
        }
  
    );`
Thanks.

**Comment by EddyVerbruggen** [comment]
Hmm, that's what I'm [doing in the demo app as well](https://github.com/EddyVerbruggen/nativescript-plugin-firebase-demo/blob/master/Firebase/app/main-view-model.js#L516) without a problem. What's the value supposed to be, and on which platforms?
