### ISSUE TITLE
Error to login with Facebook on Android

### ISSUE THREAD

**Issue by rafaelcmrj** [EddyVerbruggen/nativescript-plugin-firebase#1241]
When I try to log in using Facebook, the app seems to try to open a modal and then close in less than a second. The terminal shows the following error:

`chromium: [INFO:library_loader_hooks.cc(140)] Chromium logging enabled: level = 0, default verbosity = 0
chromium: [ERROR:gl_surface_egl.cc(264)] eglChooseConfig failed with error EGL_SUCCESS
chromium: [ERROR:gl_surface_egl.cc(264)] eglChooseConfig failed with error EGL_BAD_ATTRIBUTE
chromium: [ERROR:gl_surface_egl.cc(417)] No suitable EGL configs found.
ch`

Nothing happens after that

**Comment by EddyVerbruggen** [comment]
That doesn't ring a bell. Have you tried the demo app in this repo? If not, [try this](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/tree/afc594bfcdb4d6e964a12921a20ed4710cffeec3#demo-app).

**Comment by rafaelcmrj** [comment]
It's working now. It was a misconfiguration thing
