### ISSUE TITLE
"getCurrentUser" is not a function with 8.2.0 on android

### ISSUE THREAD

**Issue by danu165** [EddyVerbruggen/nativescript-plugin-firebase#1245]
I updated the plugin to 8.2.0 and I am now getting this error when I try to find the current user on android. I have not tried this on iOS.

Code:
`import firebase = require("nativescript-plugin-firebase/app");`
`let user = firebase.auth().currentUser;`

Error:
`JS: ERROR Error: Uncaught (in promise): Object: {"code":"auth/exception","message":"TypeError: com.google.firebase.auth.FirebaseAuth.getInstance(...).getCurrentUser is not a function"}
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.ExampleApp/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
System.err: Calling js method onCreate failed
System.err: TypeError: firebaseAuth.addAuthStateListener is not a function
System.err: File: "file:///data/data/org.nativescript.ExampleApp/files/app/tns_modules/nativescript-plugin-firebase/firebase.js, line: 331, column: 33
System.err: StackTrace: 
System.err:     Frame: function:'runInit', file:'file:///data/data/org.nativescript.ExampleApp/files/app/tns_modules/nativescript-plugin-firebase/firebase.js', line: 331, column: 34
System.err:     Frame: function:'Observable.notify', file:'file:///data/data/org.nativescript.ExampleApp/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 110, column: 23
System.err:     Frame: function:'notifyLaunch', file:'file:///data/data/org.nativescript.ExampleApp/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 979, column: 17
System.err:     Frame: function:'ActivityCallbacksImplementation.setActivityContent', file:'file:///data/data/org.nativescript.ExampleApp/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 909, column: 28
System.err:     Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.ExampleApp/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 768, column: 14
System.err:     Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.ExampleApp/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
System.err:     at android.app.ActivityThread.access$800(ActivityThread.java:151)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
System.err:     at android.os.Looper.loop(Looper.java:135)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:5254)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
System.err: Caused by: com.tns.NativeScriptException: 
System.err: Calling js method onCreate failed
System.err: TypeError: firebaseAuth.addAuthStateListener is not a function
System.err: File: "file:///data/data/org.nativescript.ExampleApp/files/app/tns_modules/nativescript-plugin-firebase/firebase.js, line: 331, column: 33
System.err: StackTrace: 
System.err:     Frame: function:'runInit', file:'file:///data/data/org.nativescript.ExampleApp/files/app/tns_modules/nativescript-plugin-firebase/firebase.js', line: 331, column: 34
System.err:     Frame: function:'Observable.notify', file:'file:///data/data/org.nativescript.ExampleApp/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 110, column: 23
System.err:     Frame: function:'notifyLaunch', file:'file:///data/data/org.nativescript.ExampleApp/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 979, column: 17
System.err:     Frame: function:'ActivityCallbacksImplementation.setActivityContent', file:'file:///data/data/org.nativescript.ExampleApp/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 909, column: 28
System.err:     Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.ExampleApp/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 768, column: 14
System.err:     Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.ExampleApp/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1203)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1083)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1070)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1050)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1042)
System.err:     at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:18)
System.err:     at android.app.Activity.performCreate(Activity.java:5990)
System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
System.err:     ... 10 more`

**Comment by francklinmarroq** [comment]
Try something like this:

`    createUser(){
      firebase.createUser({
        email: this.Email,
         password: this.Password
}).then(
  function (result) {
    const userId = result.uid
    firebase.firestore
    },
    function (errorMessage) {
        alert('No user created. Got error message insted:'+errorMessage);             
    }
)
      console.log(this.Email);
      
    }`

**Comment by danu165** [comment]
It appears some plugin version eventually fixed this. I no longer have this issue.
