### ISSUE TITLE
Admob Error in preload interstitial (IOS)

### ISSUE THREAD

**Issue by Beckmi2** [EddyVerbruggen/nativescript-plugin-firebase#1246]
I use admob in my app to show an interstitial.
Before I updated all my plugins Android and IOS build were ok. 
IOS showed the interstitial, but Android didn't (there was an error in preload interstitial.

**Then I updated all my plugins. I didn't change anything in my code.**
And suddenly Android worked, but IOS didn't any more. Now IOS throws an error in preload interstitial (**_"Request Error: No ad to show"_**).

I tried to reconstruct the situation in a test app.
Android build for this test app failed (I don't know why), but this isn't relevant for the IOS issue. On IOS it shows the same error as in my other app. 

Here is the test app:
[TestBeckmi.zip](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/files/3124724/TestBeckmi.zip)

I tried everything:
Remove nativescript-plugin-firebase.
Delete firebase.nativescript.json.
Reinstall plugin (several versions).
Nothing helps.

Any ideas? Thanks to everyone for help!

@EddyVerbruggen can you have a look on it? Please! I have already spent so much time on it ...

**Comment by Beckmi2** [comment]
Here is the last sidekick log file:
[main_19-04-28_09-58-16.979.log](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/files/3124736/main_19-04-28_09-58-16.979.log)

**Comment by Beckmi2** [comment]
And this is the output from the device console:

_CONSOLE LOG file:///app/bundle.js:406:16: preload interstitial tapped
{"msg":"CLInternalGetAuthorizationStatus", "event":"activity"}
{"msg":"CLLocationManager", "event":"activity", "_cmd":"stopUpdatingLocation", "self":"0x282f67dd0"}
{"msg":"state transition", "event":"state_transition", "state":"LocationManager", "id":"0x282f67dd0", "property":"updatingLocation", "old":0, "new":0}
0x10bb9dc00 - DocumentLoader::startLoadingMainResource: Returning empty document (frame = 0x10ab82400, main = 0)
0x10250b770 - FrameLoader::loadURLIntoChildFrame: frame load started (frame = 0x109134240, main = 1)
0x10248e010 - FrameLoader::loadURL: frame load started (frame = 0x10ab82400, main = 0)
0x10248e010 - FrameLoader::loadWithNavigationAction: frame load started (frame = 0x10ab82400, main = 0)
0x10248e010 - FrameLoader::loadWithDocumentLoader: frame load started (frame = 0x10ab82400, main = 0)
0x10248e010 - FrameLoader::continueLoadAfterNavigationPolicy: can't continue loading frame due to the following reasons (frame = 0x10ab82400, main = 0, allowNavigationToInvalidURL = 1, requestURLIsValid = 0, navigationPolicyDecision = 1)
Task <DB6FACD6-B130-4EA6-B120-0DEF317D2B43>.<4> resuming, QOS(0x19)
Task <DB6FACD6-B130-4EA6-B120-0DEF317D2B43>.<4> {strength 1, tls 8, ct 0, sub 0, sig 0, ciphers 1, bundle 0, builtin 0}
Task <DB6FACD6-B130-4EA6-B120-0DEF317D2B43>.<4> now using Connection 10
Task <DB6FACD6-B130-4EA6-B120-0DEF317D2B43>.<4> sent request, body N
Task <DB6FACD6-B130-4EA6-B120-0DEF317D2B43>.<4> received response, status 200 content K
Task <DB6FACD6-B130-4EA6-B120-0DEF317D2B43>.<4> done using Connection 10
Task <DB6FACD6-B130-4EA6-B120-0DEF317D2B43>.<4> response ended
0x10bb44e00 - DocumentLoader::startLoadingMainResource: Returning empty document (frame = 0x10bb86d00, main = 0)
0x10250b770 - FrameLoader::loadURLIntoChildFrame: frame load started (frame = 0x109134240, main = 1)
0x102556660 - FrameLoader::loadURL: frame load started (frame = 0x10bb86d00, main = 0)
0x102556660 - FrameLoader::loadWithNavigationAction: frame load started (frame = 0x10bb86d00, main = 0)
0x102556660 - FrameLoader::loadWithDocumentLoader: frame load started (frame = 0x10bb86d00, main = 0)
0x102556660 - FrameLoader::continueLoadAfterNavigationPolicy: can't continue loading frame due to the following reasons (frame = 0x10bb86d00, main = 0, allowNavigationToInvalidURL = 1, requestURLIsValid = 0, navigationPolicyDecision = 1)
_

**Comment by Beckmi2** [comment]
I found out, that on IOS simulator the interstitial is shown correctly ... But on IOS real device there is still the error "No ad to show".

**Comment by EddyVerbruggen** [comment]
Hi, @Beckmi2, I just tested with `npm run demo.ios` in this repo on my physical iPad and that showed the interstitial just fine after preloading them.

Can you confirm that `ca-app-pub-4808109210558941~1166505885` is what you have at:

<img width="711" alt="Screenshot 2019-04-30 at 19 00 46" src="https://user-images.githubusercontent.com/1426370/56979562-5d7a7780-6b7a-11e9-9728-822702bc2977.png">

And `ca-app-pub-4808109210558941/6577656800` is what you have at:

<img width="634" alt="Screenshot 2019-04-30 at 19 03 10" src="https://user-images.githubusercontent.com/1426370/56979672-a0d4e600-6b7a-11e9-843d-ca9b68da3acd.png">

Double check that please, as I don't see anything wrong with your setup otherwise.

**Comment by Beckmi2** [comment]
Yes, I can confirm:
![Screenshot 2019-05-02 09 18 21](https://user-images.githubusercontent.com/25406329/57060912-60c94c80-6cbb-11e9-854d-6a71df8d0fa1.png)
![Screenshot 2019-05-02 09 21 58](https://user-images.githubusercontent.com/25406329/57061015-c4537a00-6cbb-11e9-9208-151b1ba5f871.png)

**Comment by EddyVerbruggen** [comment]
Can you try a different device, or at least rebooting this one? There must be something wrong with the device because all your setup seems OK).

**Comment by Beckmi2** [comment]
I rebooted both my iPhone and my iPad. But it still doesn't work.
At the moment, I have no other device available ...
The deviceID for test-devices is the identifier, which is shown here, isn't it?
![Screenshot 2019-05-02 09 44 28](https://user-images.githubusercontent.com/25406329/57061955-134ede80-6cbf-11e9-812f-5f536eb2fb87.png)

And, as I mentioned before: before I updated my plugins, ads on IOS device were shown correctly (same devices) ...

**Comment by EddyVerbruggen** [comment]
Yep, that ID looks fine. So I guess the only logical option left is to pinpoint which plugin update screwed things up for you..

**Comment by Beckmi2** [comment]
Oh no ... I know that ... that's hard work ;-)

Do you think, that the problem also exists on release version? Because on simulator all works fine.

**Comment by EddyVerbruggen** [comment]
There's only one way to find out.

**Comment by Beckmi2** [comment]
@EddyVerbruggen 
After rebooting my device there was a real mess. Nothing worked. And I got a shock. 
Today, aber some days, I tried again. And everything worked like before. Everything but showing ads.
So I will spend some time to find out which plugin causes the problem as you suggested. 
And I will report.
Thanks for your help so far! I hope I will be able to solve this problem soon.

**Comment by Beckmi2** [comment]
Now it's two weeks later. I ignored the problem and released my app (not the test app, but my 'real' app 'Protest' both on IOS and Android on the stores.
And on both platforms there are no ads shown ...

**Comment by Beckmi2** [comment]
I summarise the issue:
Before Plugin-Update: Testing on IOS on real device worked, but not on Android ('no ads available'-message)

After Plugin-Update: Testing on IOS real device didn't work any more ('no ads available'-message), 
Testing on IOS simulator worked fine and on Android real device worked also fine.

Release: Ads don't work neither on IOS nor on Android.






After

**Comment by Beckmi2** [comment]
![firebase nativescript json](https://user-images.githubusercontent.com/25406329/58015487-b004df00-7afb-11e9-8596-f0b4927f2f17.png)

**Comment by Beckmi2** [comment]
![info plist](https://user-images.githubusercontent.com/25406329/58015508-beeb9180-7afb-11e9-98c3-451367a8090e.png)

**Comment by Beckmi2** [comment]
![AndroidManifest xml](https://user-images.githubusercontent.com/25406329/58015534-cdd24400-7afb-11e9-8414-e7ea4a1f5d3a.png)

**Comment by Beckmi2** [comment]
![admob-view-model](https://user-images.githubusercontent.com/25406329/58015568-e3476e00-7afb-11e9-9d8a-f2239e4a2024.png)

**Comment by Beckmi2** [comment]
![current_situation-view-model js](https://user-images.githubusercontent.com/25406329/58015628-08d47780-7afc-11e9-9e47-85a244567256.png)

**Comment by Beckmi2** [comment]
![current_situation-page js](https://user-images.githubusercontent.com/25406329/58015691-2dc8ea80-7afc-11e9-83eb-7c9a98454320.png)

**Comment by Beckmi2** [comment]
![package json](https://user-images.githubusercontent.com/25406329/58015885-a760d880-7afc-11e9-99eb-924175229f98.png)

**Comment by Beckmi2** [comment]
Android Release Build.
Thats's what device control in sidekick is showing:
![Ohne Titel](https://user-images.githubusercontent.com/25406329/58161459-93de7a80-7c80-11e9-943f-592d67530dbb.png)

**Comment by Beckmi2** [comment]
In the meantime I changed some versions (Nativescript cli, tns-ios, tns-android, and - without changing anything in the code, IOS works fine. Android still doesn't work ...
My current versions are: 
<img width="845" alt="Screenshot 2019-06-06 10 53 49" src="https://user-images.githubusercontent.com/25406329/59020034-72b58680-8849-11e9-94d1-63ec32ec5c2e.png">

@EddyVerbruggen Which version-mix do you use or recommend?

**Comment by Beckmi2** [comment]
Some further weeks passed and - without changing anything in the code the interstitial work fine now both on iOS and Android ...
So I close this issue now ...
