### ISSUE TITLE
FacebookSDK sdkinitialize logout problem without use of facebook login

### ISSUE THREAD

**Issue by andreabbondanza** [EddyVerbruggen/nativescript-plugin-firebase#1256]
Hi, great work with this plugin! Love it, but I'm having a problem with the firebase.Logout() function.
After the __PHONE__ Login, I've created a button to do the logout but, when I press it, I got this:

Error output
-------------

Error in firebase.logout: Error: The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.
JS:     com.facebook.internal.Validate.sdkInitialized(Validate.java:143)
JS:     com.facebook.login.LoginManager.<init>(LoginManager.java:80)
JS:     com.facebook.login.LoginManager.getInstance(LoginManager.java:93)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1203)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1083)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1070)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1050)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1042)
JS:     com.tns.gen.android.view.GestureDetector_SimpleOnGestureListener_gestures_16_32_TapAndDoubleTapGestureListenerImpl.onSingleTapUp(GestureDetector_SimpleOnGestureListener_gestures_16_32_TapAndDoubleTapGestureListenerImpl.java:21)
JS:     android.view.GestureDetector.onTouchEvent(GestureDetector.java:641)
JS:     android.support.v4.view.GestureDetectorCompat$GestureDetecto...

This problem is present __ONLY__ on __Android__, on IOS it works well.
The strange thing is that I do not use the Facebook Login and in the plugin source code seems that SDK is initialized only in Facebook Login Type login.

Code
------------

What I'm Using:
Nativescript core with Typescript;
My firebase init in the main page constructor:
### init
```typescript
try 
{
       await firebase.init()
      _.Log("Init");
}
catch (error)
{
      _.Log("FIREBASE ERROR");
}
```
### my login event
```typescript
try
{
    const task = await firebase.login({
        type: firebase.LoginType.PHONE,
        phoneOptions: {
            phoneNumber: '+39' + this.Phone,
            verificationPrompt: "Test"
        }
    });
    _.Log(JSON.stringify(task));
}
catch (err)
{
    console.log(err);
}
```
### logout event
```typescript
try 
{
    _.Log("exit");
    await firebase.logout();
}
catch (err)
{
    _.Log(err);
}
```

For some reason seems that the flow goes into this code from _firebase.android.js_ file even if I do not use the Facebook login (that contains the init).
```javascript
 if (typeof (com.facebook) !== "undefined" && typeof (com.facebook.login) !== "undefined") {
     com.facebook.login.LoginManager.getInstance().logOut();
}

```

Thank you for your help 👍

**Comment by EddyVerbruggen** [comment]
That's very strange indeed. So in your `firebase.nativescript.json` there's no `"facebook_auth"` property, or it is `false`?

Could there be any other plugin that drags in this Facebook lib?

**Comment by andreabbondanza** [comment]
Hi @EddyVerbruggen , thank you for your answer. 
You're right, and I'm sorry I didn't catch the problem. In the _firebase.nativescript.json_ the _"facebook_auth"_ property was __true__ (in first place the app was using the FB login, removed after). 
I'm really sorry for this useless issue  😞
