### ISSUE TITLE
Android - registerForPushNotifications not resolved.

### ISSUE THREAD

**Issue by marianedu** [EddyVerbruggen/nativescript-plugin-firebase#1259]
Hi, looks like the promise on registerForPushNotifications is never resolved on Android - looks just like a missing call to resolve() right after calling getSenderId on line 166 in  
https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/src/messaging/messaging.android.ts.

Better yet, the promise should be resolved when getSenderId is revolved and rejected if that fails (same for unregisterForPushNotifications).

**Comment by EddyVerbruggen** [comment]
Looks like you're right - I guess that was removed by accident during refactoring.

**Comment by marianedu** [comment]
Thanks, is probably way too small for a pull request though :)

**Comment by EddyVerbruggen** [comment]
Nothing is! But I've changed it myself because I wanted to release a new version tonight anyway.. so the timing was perfect.
