### ISSUE TITLE
Add ability to add scopes for GoogleAuthProvider

### ISSUE THREAD

**Issue by romandragan** [EddyVerbruggen/nativescript-plugin-firebase#1266]
Could we add an ability of adding scopes to the `GoogleAuthProvider`?

https://firebase.google.com/docs/auth/web/google-signin#handle_the_sign-in_flow_with_the_firebase_sdk

**Comment by EddyVerbruggen** [comment]
Thanks for asking - would you be able to link to the iOS and Android docs as well?

**Comment by romandragan** [comment]
@EddyVerbruggen, sure.

For Android we can use [`GoogleSignInOptions.Builder.requestScopes(..)`](https://developers.google.com/android/reference/com/google/android/gms/auth/api/signin/GoogleSignInOptions.Builder#requestScopes(com.google.android.gms.common.api.Scope,%20com.google.android.gms.common.api.Scope...)) function.

For iOS I believe we can use [`GIDSignIn.scopes `](https://developers.google.com/identity/sign-in/ios/api/interface_g_i_d_sign_in.html#a43386d1f0af8fedf6263e673631a56ca) property.

**Comment by EddyVerbruggen** [comment]
Thanks! Added the required code an docs.
