### ISSUE TITLE
Build failed iOS crashlytics

### ISSUE THREAD

**Issue by giorgiopiatti** [EddyVerbruggen/nativescript-plugin-firebase#1269]
I'm using the latest version of this plugin (8.3.2) with Crashlytics enabled, and I've encountered this issues when building on xcode 10 (with legacy building mode).

This error is showed when trying to run the script for configuring Crashlytics, during the build phase:

`Could not get GMP_APP_ID in Google Services file form build environment.`

I think that some how some configuration is missing, but I searched here on the doc and I've include  everything. 
I'm not so sure that this issue is directly connected to this project or instead one of his dependencies.

Note: setting Crashlytics to false in the config file and building the project result with no issues.

**Comment by hiteshborse12** [comment]
@giorgiopiatti facing same issue. Got solution?

**Comment by 18clans** [comment]
I'm getting this same error after Android builds successfully and I try to run iOS, it errors out:

```
error: Could not get GMP_APP_ID in Google Services file from build environment
note: Using new build systemnote: Planning buildnote: Constructing build description
```

The temporary fix is to go to the iPhone emulator and click on the top menu `Hardware > Erase All Content and Settings`. Go and delete the `platforms` folder.  Once that is done, run `tns run ios --bundle` command.

This will occur again if you run Android than iOS.  Very annoying especially if you're trying to test both emulators.

**Comment by 18clans** [comment]
Do you have two Google Services `plist`?  I noticed that the multiple environment `plist` swapping during build time doesn't work.  I was getting this erroring until I used only one `plist`.  This goes the same with `google-services.json` for Android.

**Comment by MichaelM97** [comment]
I had this issue too, and as @18clans said it is related to having more than one Google Services `plist`.
However, you can still make it work.

To do this, move the logic which selects which Google Services `plist` to use out of `AppDelegate`, and into a run script (see [here](https://stackoverflow.com/a/48789232)).

Position the script just before 'Copy Bundle Resources' as below

<img width="831" alt="Screenshot 2019-07-18 at 19 54 38" src="https://user-images.githubusercontent.com/22373058/61484075-02486c00-a996-11e9-9eb7-5d182685445c.png">
