### ISSUE TITLE
firebase.firestore.FieldValue.serverTimestamp() creates a "modified" snapshot entry while I am trying to insert it.

### ISSUE THREAD

**Issue by abhishek0196** [EddyVerbruggen/nativescript-plugin-firebase#1271]
Sorry , I  am not aware that ,is this a  issue, or I am not able to use it  in the correct manner,

The problem I am facing is ..

I am trying to create a new document , with certain fields , with one field being **created** ,the issue comes when I'm trying to retrieve the newly entered document with a onSnapshot() listener.
The onSnapshot() listener gets triggered twice once with the type **added** and just after that with the type **modified** , just because the value of **firebase.firestore.FieldValue.serverTimestamp()**  is not inserted at the same time.

Here is the code snippet for adding the document

```  this.db.collection(this.collectionName.friendsCollection).doc(this.buddy.docid).collection(this.collectionName.chatsCollection).add({
            senderid : this.buddy.senderId,
            receiverid: this.buddy.receiverId,
            message : msg,
            created: firebase.firestore.FieldValue.serverTimestamp()
       
```

And here is the code for reading the documents:

```
   this.db.collection(this.collectionName.friendsCollection).doc(this.buddy.docid)
     .collection(this.collectionName.chatsCollection).orderBy('created')
     .onSnapshot(snapshot=> {
       skip.buddymessages = [];
       if(snapshot.empty)
       {
         console.log("First Chat");
       }
       else{
         console.log("size",snapshot.size)
         snapshot.docChanges.forEach(change => {
           if (change.type === 'added') {
             console.log('New : ', change.doc.data());
           }
           if (change.type === 'modified') {
             console.log('Modified : ', change.doc.data());
           }
           if (change.type === 'removed') {
             console.log('Removed : ', change.doc.data());
           }
         });
```

Here is the console screenshot:-
![Error](https://user-images.githubusercontent.com/13505029/58324961-09e00e80-7e46-11e9-8074-9275b33a600d.PNG)

> Note: I do have a workaround for this , just curious about this issue.The workaround will be to use new Date() js method to get the current timestamp

**Comment by EddyVerbruggen** [comment]
Would you mind Googling this is a broader (non-plugin) context? My suspicion is this is simply how Firebase works.

**Comment by abhishek0196** [comment]
Oh sorry I just forget to close this issue , when I found that firebase works this way.
