### ISSUE TITLE
Add support for ML Kit Object Detection and Tracking

### ISSUE THREAD

**Issue by adfdev** [EddyVerbruggen/nativescript-plugin-firebase#1274]
Where is module Object Detection and Tracking? Is not yet integrated?

**Comment by EddyVerbruggen** [comment]
What’s that?

**Comment by adfdev** [comment]
[https://firebase.google.com/docs/ml-kit/object-detection](https://firebase.google.com/docs/ml-kit/object-detection)

**Comment by EddyVerbruggen** [comment]
Aha

**Comment by adfdev** [comment]
Than?

**Comment by EddyVerbruggen** [comment]
Not implemented atm..

**Comment by adfdev** [comment]
You think can implement that in the next weeks?
