### ISSUE TITLE
Source Option Server or cache

### ISSUE THREAD

**Issue by Robernator** [EddyVerbruggen/nativescript-plugin-firebase#1275]
Hello Eddy,
Thank you for this excellent plugin.

I want to be in control whether I want to query from cache or server. 
A lot of data in my app are lookup tables which will not change very often.
For Firestore you have to pay for every read.

In the Firestore document there is a Source Option which I really want to use.

Request:
Can you add this functionality in this plug-in?

https://cloud.google.com/firestore/docs/query-data/get-data
// Valid options for source are 'server', 'cache', or
// 'default'. See https://firebase.google.com/docs/reference/js/firebase.firestore.GetOptions
// for more information.
var getOptions = {
    source: 'cache'
};

// Get a document, forcing the SDK to fetch from the offline cache.
docRef.get(getOptions).then(function(doc) {
    // Document was found in the cache. If no cached document exists,
    // an error will be returned to the 'catch' block below.
    console.log("Cached document data:", doc.data());
}).catch(function(error) {
    console.log("Error getting cached document:", error);
});

Kind Regards,
Rob Berghout

**Comment by EddyVerbruggen** [comment]
Thanks for the feature request Rob!

Sounds like a very useful feature to have. I'll add it soon.

**Comment by Robernator** [comment]
Hello Eddy,
That would be very nice. 
I would like to be the first who will test this feature :-)

**Comment by soscler** [comment]
Hi,

I've tried this feature on android but it doesn't work. I have a query that looks like this
```javascript
firestore.collection('countries')
.where('population', '>=', '1_000_000')
.orderBy('name', 'asc')
.get({
source: 'cache'
})
```
This query always returns the data from the server.
I have persits set to true on the initialization of firebase.

I need your help.
I need to reduce the number of reads my app makes on firestore, and using the cache is a good choice for me.
