### ISSUE TITLE
registerForPushNotifications() resolving instantly

### ISSUE THREAD

**Issue by rynop** [EddyVerbruggen/nativescript-plugin-firebase#1277]
plugin ver `8.3.2`

I'm using FB messaging, and want to make sure end user has push enabled (its a requirement for my app).

On iOS when I call `messaging.registerForPushNotifications()` the promise resolves before the end user presses `allow` or `Don't Allow` in the popup.

I need to know when the async operation is complete so I can check if the user has allowed or denied.

Simple snippet to reproduce:

```typescript
        await messaging.registerForPushNotifications({
            onPushTokenReceivedCallback: (token: string) => {
                this.setToken(token);
            },

            onMessageReceivedCallback: (message: Message) => {
                this.onMessageRecieved(message);
            },

            showNotifications: true,
            showNotificationsWhenInForeground: true
        });
        console.log('** registerForPushNotifications resolved');
```

**Comment by EddyVerbruggen** [comment]
Yep, makes sense. It's a bit harder on iOS because everything is async and registering for remote notifications is something different than accepting the consent (prompt). So I'm now only resolving if both those check succeed, and reject the promise otherwise.

**Comment by rynop** [comment]
Thank you my friend, for addressing AND implementing this so quickly.  

I have confirmed it works on physical iOS device.  On the emulator it is working as Apple designed, however, I feel this change may break other folks using this commit (https://github.com/EddyVerbruggen/nativescript-plugin-firebase/commit/a882277e9aa485a4e71a445e8b010b13f1d704e5).

When calling `messaging.registerForPushNotifications()` on iOS simulator, you will now get this error:

> enabling push remote notifications are not supported in the simulator 

Calling `messaging.registerForPushNotifications()` before this commit did NOT throw an error.

While this is technically [working correctly](https://stackoverflow.com/questions/21741259/push-notifications-in-mavericks-ios-simulator), I think you may want to catch and supress this specific error inside your plugin, so it does not cause regression problems with others using this lib.  You also [mention](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/MESSAGING.md#provisioning-hell):

> Once you've done it run tns run ios and upon starting the app it should prompt you for notification support. **That also works on the simulator**, but actually receiving (background) notifications is only possible on a real device.

Alternatively, you could update the readme (and I can help do this) to let folks know that `v8.4.0` will probably break their app in development, unless they explicitly `catch` and suppress this error.

IMO I think its more reasonable for your lib to swallow this error...

**Comment by EddyVerbruggen** [comment]
Agreed, thanks for the suggestion!

**Comment by rynop** [comment]
I'm having trouble verifying, I think its due to how I'm trying to test against my local checked out version of nativescript-plugin-firebase#c03fb18.

Do you have any docs for best practice to dev/test non released versions of your plugin? My workflow is below - I'm guessing I'm missing a much easier way to do this:

```
yarn add -s https://github.com/EddyVerbruggen/nativescript-plugin-firebase#c03fb18
cd node_modules/nativescript-plugin-firebase/publish/
./pack.js

//update my package.json to look like:
"nativescript-plugin-firebase": "file:./node_modules/nativescript-plugin-firebase/publish/package/nativescript-plugin-firebase-8.3.2.tgz",

// From my proj root:
yarn install 
```

**Comment by EddyVerbruggen** [comment]
That should work actually. I don't think the release of 8.4.0 will take much longer, so you might as well wait for that.
