### ISSUE TITLE
Get latest version?

### ISSUE THREAD

**Issue by Robernator** [EddyVerbruggen/nativescript-plugin-firebase#1279]
Hello Eddy,

I have seen that you have implemented the option (server, cache or default). That is great!
How can I get the latest plugin with this feature?
tns plugin add nativescript-plugin-firebase gives the version 8.3.2

Kind regards,
Rob

**Comment by EddyVerbruggen** [comment]
When it's published to npm, and that will be done when 8.4.0 is ready, and that will be probably sometime next week.
