### ISSUE TITLE
Android analytics: Error in firebase.logEvent: Error: java.lang.NullPointerException: null reference

### ISSUE THREAD

**Issue by NathanWalker** [EddyVerbruggen/nativescript-plugin-firebase#128]
> JS: Error in firebase.logEvent: Error: java.lang.NullPointerException: null reference
JS:     com.google.android.gms.common.internal.zzab.zzy(Unknown Source)
JS:     com.google.android.gms.measurement.internal.zzx.zzdo(Unknown Source)
JS:     com.google.firebase.analytics.FirebaseAnalytics.getInstance(Unknown Source)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:862)

There are no `null`'s being passed in so I'm assuming this is coming from the plugin... will look.

**Comment by EddyVerbruggen** [comment]
Curious to learn what it is. I can imagine this could happen with 3.6.0, less with 3.6.1. Can you post the snippet that logs the event?

**Comment by NathanWalker** [comment]
@EddyVerbruggen occurs after I do this:
```
firebase.analytics.logEvent({
        key: 'MY_ACTION',
        properties:[
          {
            key: 'category',
            value: 'my_category'
          },
          {
            key: 'label',
            value: 'my_label'
          },
          {
            key: 'value',
            value: 'my_value'
          },
        ]
      }).then(() => {
       
      });
```
^ causes this immediate crash:
```
JS: Error in firebase.logEvent: Error: java.lang.NullPointerException: null reference
JS:     com.google.android.gms.common.internal.zzab.zzy(Unknown Source)
JS:     com.google.android.gms.measurement.internal.zzx.zzdo(Unknown Source)
JS:     com.google.firebase.analytics.FirebaseAnalytics.getInstance(Unknown Source)
```

**Comment by NathanWalker** [comment]
oh crap, just realized mistake...LOL

**Comment by NathanWalker** [comment]
Hmm, yeah puzzled by this one. Am I missing something obvious?

**Comment by NathanWalker** [comment]
Nvm!! Ah... it's `parameters` ... not `properties` ...

**Comment by EddyVerbruggen** [comment]
Just wanted [to show you](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/firebase.d.ts#L391) 😉

In your defence it took me a while to choose between those two param names..

**Comment by NathanWalker** [comment]
Well shoot, it's stiiiilll crashing. :(

**Comment by EddyVerbruggen** [comment]
Noooooooooo!

You áre on 3.6.1, right?

**Comment by NathanWalker** [comment]
I am yeah... just Android only. Works fine in iOS... pretty puzzling.

**Comment by NathanWalker** [comment]
https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/firebase.android.js#L303

`currentContext` must be where the issue is coming from since stack says:
```
com.google.firebase.analytics.FirebaseAnalytics.getInstance(Unknown Source)
```
? Unknown Source?

**Comment by EddyVerbruggen** [comment]
That has bitten me before in other plugins.. that context.. it seems to get nulled sometimes. Time to investigate!

**Comment by EddyVerbruggen** [comment]
It must be the single quotes!

**Comment by NathanWalker** [comment]
LOL! right.

**Comment by NathanWalker** [comment]
maybe try this: `app.android.currentContext || app.android.context` ...

**Comment by EddyVerbruggen** [comment]
Does `appModule.android.context` work for your case?

**Comment by NathanWalker** [comment]
building now... lemme see

**Comment by NathanWalker** [comment]
Worked like a charm 👍

**Comment by NathanWalker** [comment]
`com.google.firebase.analytics.FirebaseAnalytics.getInstance(app.android.currentContext || app.android.context).logEvent(action, bundle);`

**Comment by EddyVerbruggen** [comment]
Thanks for looking into it. You may run into a similar issue with other methods as well so I will investigate this further shortly!

**Comment by NathanWalker** [comment]
Thanks @EddyVerbruggen yep been bit by similar kind of thing with {N} android projects...Hope similar conditional will help resolve throughout!

**Comment by EddyVerbruggen** [comment]
I'm settling on your proposed patch. [This {N} issue](https://github.com/NativeScript/NativeScript/issues/2447) seems to also advice to use `context` if `currentContext` is causing trouble. Let's just ignore this oddity and move on :)

**Comment by priyangamani** [comment]
app.android.currentContext || app.android.context||app.android.foregroundActivity||utils.ad.getApplicationContext()  nothing worked..
how to pass the current Activity context...
