### ISSUE TITLE
Upgrade Facebook SDK to v5.0

### ISSUE THREAD

**Issue by romandragan** [EddyVerbruggen/nativescript-plugin-firebase#1280]
Could we upgrade to the latest Facebook SDK, which is recently became 5.0?

https://take.ms/daNJi
https://developers.facebook.com/docs/app-events/upgrade-guide/

As far as I understand we're [using](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/c3f9e9b9fe7e734aca9cf1cf32800404cebfe45f/src/scripts/postinstall.js#L4617) 4.38.0 version now.

**Comment by romandragan** [comment]
Could it be in just bumping up the version in the `postinstall.js`?

**Comment by EddyVerbruggen** [comment]
@romandragan Nope, that's not sufficient :)

But the good news is: I've just completed bumping that SDK and many others in #1283 for iOS, so please follow that one. I'll be working on doing the same for Android today and implementing a few new features the days after.
