### ISSUE TITLE
Upgrade native SDKs to iOS 6.2.0 and Android 16.0.9

### ISSUE THREAD

**Issue by EddyVerbruggen** [EddyVerbruggen/nativescript-plugin-firebase#1283]
See https://firebase.google.com/support/release-notes/ios#version_620_-_june_4_2019 and https://firebase.google.com/support/release-notes/android

**Comment by EddyVerbruggen** [comment]
iOS is done. Next up: Android!

**Comment by EddyVerbruggen** [comment]
Android is done as well. Now let's see if we can sneak in a few bugfixes while we're at it. Closing this one, but not yet releasing it. Will do later this week!

**Comment by nickykln** [comment]
Thanks a lot Sir @EddyVerbruggen :)
Do you think you will have the time to release the 8.4.0. 
I am really impatient, to finish the app with the push working again :)

Thanks again for everything you do in this community.

N

**Comment by alfonsocj** [comment]
@EddyVerbruggen I'm getting a pod error that version 6.2.0 of FirebaseCore doesn't exist.
I checked https://cocoapods.org/pods/FirebaseCore and it looks like the latest is 6.1.0
