### ISSUE TITLE
Add support for Firestore Collection Group queries

### ISSUE THREAD

**Issue by EddyVerbruggen** [EddyVerbruggen/nativescript-plugin-firebase#1284]
See https://firebase.google.com/docs/firestore/query-data/queries#collection-group-query

**Comment by EddyVerbruggen** [comment]
https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/FIRESTORE.md#collection-group-queries-collectiongroupwhere

**Comment by siavee** [comment]
This is awesome
