### ISSUE TITLE
Bounds property of barcode scan result not the same for iOS and Android

### ISSUE THREAD

**Issue by nickdekkers** [EddyVerbruggen/nativescript-plugin-firebase#1288]
I want to be able to check whether a barcode is within a certain rectangular view on the screen. That way it will only process the barcode within that view and not the ones outside of it.
When I scan the barcode and log the MLKitScanBarcodesResultBarcode I see that the bounds property of the iOS and Android barcode result is different. To clarify, I scanned the barcode in the top left corner of the full scanner area (so the top-left corner of the barcode is close to the top-left corner of the scanner area).

The issue is as follows (EAN-13 barcode scanned):
What I would expect from the result would be something like the code below where the x and y coordinate of the origin are close to 0 (expect the top-left corner to be (0,0)) and the width to be higher than the height (an EAN-13 barcode is wider than it is high):
```
"bounds": {
  "origin": {
    "x": 24,
    "y": 83
   },
   "size: {
      "width": 341,
      "height": 7
  }
}
```
The result I get for Android is also close to that:
```

{
  "value": "5713778111841",
  "format": "EAN_13",
  "android": {},
  "bounds": {
    "origin": {
      "x": 24,
      "y": 83
    },
    "size: {
      "width": 341,
      "height": 7
    }
  }
}
```
The result for iOS on the other hand is way different:
```

{
  "value": "5713778111841",
  "format": "EAN_13",
  "ios": {},
  "bounds": {
    "origin": {
      "x": 396,
      "y": 466
    },
    "size": {
      "width": 19,
      "height": 241
    }
  }
}
```
After some research and scanning from different position I found out the following things:

- The x and y coordinate are reversed

- The width and height are reversed

- The x-coordinate (y in the bounds that are returned as the result) is oriented from right to left instead of left to right

- The y-coordinate (x in the bounds that are returned as the result) have a value of roughly 380 when scanned at the top of the screen instead of starting at 0

Due to these issues it is really difficult to write a system that recognizes whether a barcode is within a certain scannable area.

**Comment by EddyVerbruggen** [comment]
Yeah, I expected someone to log an issue like this :)

The image has to rotated etc before it's fit for ML Kit so that may explain a few of the transformations you're seeing. But of course, the plugin should transparently handle this for you.

**Comment by EddyVerbruggen** [comment]
This fix will be available with version 9.0.0 later today.

**Comment by EddyVerbruggen** [comment]
Note that I've also added an `image` object to the result, which contains a `width` and `height` property. This represents the image used to detect barcodes in, so you should be able to calculate the frame the barcode was detected in.

**Comment by nickdekkers** [comment]
Thanks a lot.
