### ISSUE TITLE
Declaring `addOnMessageReceivedCallback` twice create a priority behavior 

### ISSUE THREAD

**Issue by kefahB** [EddyVerbruggen/nativescript-plugin-firebase#1290]
Hi @EddyVerbruggen 

My code logic need to declaring ` addOnMessageReceivedCallback` twice ! I use it for receiving confirmation from other device...

What I remarque since the last update is the plugin use the `FIRST` declaration and ignore the seconde one ?!

Is that the default behavior ?

Thanks

**Comment by EddyVerbruggen** [comment]
I think it is.. only one callback can currently be registered..
