### ISSUE TITLE
Not working with Nativescript 5.4, Android and iOS

### ISSUE THREAD

**Issue by erkanarslan** [EddyVerbruggen/nativescript-plugin-firebase#1294]
I recently upgraded to Nativescript 5.4. After the update, this plugin does not work with Android because of the "VersionNumber" error mentioned here: #1263 
Upgrading the plugin to version 8 solves this problem however, this time plugin does not work with iOS because when app is refreshed i get this error:

`Error in messaging.getCurrentPushToken: TypeError: null is not an object (evaluating 'FIRMessaging.messaging().FCMToken')`

You don't get this error when you start the application first time with "tns run ios" but after you refresh the application, it doesn't start and you get the error above.

So, version 8 does not work with iOS and version 7 does not work with Android after upgrading to NS 5.4

**Comment by erkanarslan** [comment]
For now, I just added "org.gradle.util." in front of "VersionNumber" in the file mentioned at #1263. This fixes the problem.

**Comment by EddyVerbruggen** [comment]
That `VersionNumber` issue was fixed in 8.3.0 by #1250, so let's focus on the iOS issue you mentioned with version 8+.

What do you mean by 'refresh'? Which steps do I take to reproduce this?

**Comment by erkanarslan** [comment]
Run the application. Then, edit and save a file. Webpack will rebuild and reload the application. When it is reloaded, I get the error I mentioned. If you cannot reproduce it, I can send you my project folder.

**Comment by edrick27** [comment]
I have the same problem, when create a new proyect in version 5.4, that version use webpack by defult. and if try to init() firebase i get folliwing error: Cannot read property 'android' of undefined

**Comment by erkanarslan** [comment]
Version 9.0.1 fixes the problem.

@edrick27 Your problem looks different than what I posted.
