### ISSUE TITLE
Found com.google.android.gms:play-services-base:9.4.0, but version 9.0.0 is needed for the google-services plugin.

### ISSUE THREAD

**Issue by piyushgodara** [EddyVerbruggen/nativescript-plugin-firebase#130]
Need push notification in my app. 
Followed the steps to install "nativescript-plugin-firebase":"^3.6.1" . 
 Did following configuration while installing the plugin

**NativeScript Firebase Plugin Installation
prompt: Are you using iOS (y/n):  (y) y
prompt: Are you using Android (y/n):  (y) y
prompt: Are you using Firebase RemoteConfig (y/n):  (n) n
prompt: Are you using Firebase Messaging (y/n):  (n) y
prompt: Are you using Firebase Storage (y/n):  (n) n
prompt: Are you using Firebase Facebook Authentication (y/n):  (n) n
prompt: Are you using Firebase Google Authentication (y/n):  (n) n**

Attached are gradle.build and google-services.json.

And using Andular2+NS app on android emulator with version 4.4.4.

After build of the app it gives following error "**Found com.google.android.gms:play-services-base:9.4.0, but version 9.0.0 is needed for the google-services plugin**."

Some other exceptions an warnings:

"What went wrong:
**Execution failed for task ':processF0F1DebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 9.0.0."**

**google-services plugin could not detect any version for com.google.android.gms or com.google.firebase, default version: 9.0.0 will be used.**

Adding Android SDK Manager versions as well.

![image](https://cloud.githubusercontent.com/assets/13695305/18479305/1fc052f6-79f2-11e6-9538-c01840e1e1eb.png)

[Plugin issue.zip](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/files/470132/Plugin.issue.zip)

**Comment by EddyVerbruggen** [comment]
You have `apply plugin: "com.google.gms.google-services"` at line 34 of `build.gradle`. Can you move it to the __very bottom of the file__ and try again?

**Comment by piyushgodara** [comment]
@EddyVerbruggen  No same issue after moving to very bottom.

**Comment by EddyVerbruggen** [comment]
Can I get your entire project perhaps? In such a way that I can reproduce the problem.

**Comment by piyushgodara** [comment]
Well Eddy , i am using a sample project, i can share that, its just like hello World, with only "nativescript-plugin-firebase" plugin. I will share that.

**Comment by piyushgodara** [comment]
Hi @EddyVerbruggen  Here my sample app
[Push App Project.zip](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/files/470349/Push.App.Project.zip)

**Comment by piyushgodara** [comment]
@EddyVerbruggen  added the sample app here https://github.com/piyushgodara/Push-app

Can you please check?

**Comment by t-moe** [comment]
Same problem here but with 9.2.0 instead of 9.0.0, haven't been able to fix this yet :(

**Comment by t-moe** [comment]
```Found com.google.android.gms:play-services-base:9.4.0, but version 9.2.0 is needed for the google-services plugin.```

when trying to build with:
- nativescript-plugin-firebase@3.6.2
- tns-core-modules@2.3.0
- and the following sdk packages:
![2016-09-17-144550_1600x900_scrot](https://cloud.githubusercontent.com/assets/11081135/18608297/d853b358-7ce5-11e6-8826-3f202d1c5cea.png)

@EddyVerbruggen what packages have you installed for your working setup?

**Comment by EddyVerbruggen** [comment]
@t-moe I have the exact same config.

@piyushgodara I need the platforms/android folder as well since that's where you need to add the additional configuration.

What I understand is that if you place `apply plugin: "com.google.gms.google-services"` at the very bottom of `platforms/android/build.gradle` it will sort out any version conflicts for you.

**Comment by t-moe** [comment]
oh, I had a `app.gradle` file where I had something like:
`compile "com.google.firebase:firebase-messaging:9.2.0"` (in order to avoid having to modify include.gradle)

Removed that line, and now it works again :sweat_smile:

**Comment by piyushgodara** [comment]
@EddyVerbruggen  Updated  platforms/android folder in the repository. Please help :)

**Comment by piyushgodara** [comment]
@EddyVerbruggen did you got change to figure out this one ??

**Comment by piyushgodara** [comment]
Working with latest version :+1:

**Comment by anuragetech** [comment]
sss
