### ISSUE TITLE
Limited number of active onSnaphot subscription

### ISSUE THREAD

**Issue by Manu-F** [EddyVerbruggen/nativescript-plugin-firebase#1301]
Limited number of 'count of onSnapshota'?

It looks like there is a limited number of the count of active onSnapshots in one app. 

**Expected Behavior:**
The count should be unlimited, the count should be documented or there should be an error message.

My code is below:

The app should listen for changes on data stores in firebase cloud firestore. The data is stored like following:

```
root
+--mycollections
   +---coll01
       +---data
	       +---001:
		      timestamp: ...
		      value: ...
	       +---002:
		      timestamp: ...
		      value: ...
   +---coll02
       +---data
	       +---0034
		      timestamp: ...
		      value: ...
	       +---0038:
		      timestamp: ...
		      value: ...
```
		   
On startup the app reads his own configuration which contains a set of ids of collections like 'coll01', 'coll02'. Then it should register on firebase to show always the newest value.
This works great for a limit number of ids, about 25-35 ids.

**configuration:**
One Nativescript/Angulat app running on android is using the Firebase Nativescript Plugin. (Nativescript 5.3)
Firebase Spark Plan (should be upgraded latef it the app is released)
Firebase-Plugin 8.3.2

**Problem:**
If we increae the number of ids to register we have the problem, that on some querysnapshot, we got no data. But the data is realyy abailable!

**Tried following workaround to solve the prpblem:**
I tried to solve the provlem (just for testing) to break the registration for a second after any registrations.
Tried to to found any exceeded limits in firebase console => but found nothing.
```

 getCollectionData(collectionId: string): () => void {
        try {
            return firebase.firestore
                .collection('mycollections')
                .doc(collectionId)
                .collection('data')
                .orderBy('timestamp', 'desc')
                .limit(1)
                .onSnapshot((querySnapshot) => {
                    this.zone.run(() => {
                        this.handleCollectionSnapshot(collectionId, querySnapshot);
                    });
                });
        } catch (error) {
            console.log('error while getting collection data of firebase: ' + error);
        }
    }

```
 ```
   private handleCollectionSnapshot(collectionId: string, querySnapshot: firebase.firestore.QuerySnapshot): void {
        if (querySnapshot.docs && querySnapshot.docs.length > 0) {
            querySnapshot.docs.forEach((doc) => {

                const timeStampUtc = doc.data().timestamp;
                const timeStamp = new Date(timeStampUtc).getTime();

                // TODO: handle data
            });
        } else {
            console.error(`No Data found for collection ID ${collectionId}`);
        }
    }
```

**Comment by EddyVerbruggen** [comment]
There is nothing in the plugin restricting this. Please ask on the Firebase SDK repo instead.

**Comment by Manu-F** [comment]
Thabks for your fast response. I will ask on firebase.
