### ISSUE TITLE
firebaseRemoteConfig.setDefaultsAsync is not a function

### ISSUE THREAD

**Issue by naranjja** [EddyVerbruggen/nativescript-plugin-firebase#1302]
I am getting this error when trying to execute the following after initializing `firebase` correctly:
```js
const firebase = require("nativescript-plugin-firebase");
firebase.getRemoteConfig({
        developerMode: false,
        cacheExpirationSeconds: 3600,
        properties: [{
            key: "some_key",
            default: "some_value"
        }]
    }).then(result => {
    	console.log(result)
    }).catch(err => {
        console.error(err)
    })
// TypeError: firebaseRemoteConfig.setDefaultsAsync is not a function
```

These are my app's relevant package versions:
- tns-android: `5.3.1`
- nativescript-plugin-firebase: `8.3.2`
- tns-core-modules: `5.1.2`

I couldn't find anyone else with this error, which prompted me to post here. Does anyone have a clue as to what could be happening? I tried placing this code inside `firebase.init().then` and obtained the same results.

**Comment by EddyVerbruggen** [comment]
There is no need to call that function; on Android, the plugin's `getRemoteConfig` function calls it internally.

**Comment by naranjja** [comment]
Hi! Thanks for your answer. Unfortunately, I am not explicitly calling `setDefaultsAsync()` rather `getRemoteConfig()` which, like you said, internally calls the other function.

For some reason, I am getting a `TypeError` when doing this.

**Comment by EddyVerbruggen** [comment]
Oh, sorry, misread that.

So `setDefaultsAsync` has been recently added to the Android Firebase SDK, so perhaps you'll need to clear your platforms/android folder and build again because the 'remote config' jar may not have been updated when you upgraded your plugin version to 9.0.0 (which I assume you did, to trigger this error).
