### ISSUE TITLE
Upgrade 8.3.2 to 9.0.1 Firebase initialisation error

### ISSUE THREAD

**Issue by Robernator** [EddyVerbruggen/nativescript-plugin-firebase#1307]
Hello,

First of all, I want to thank you for the good work you have done.

I want to upgrade my project to the new version but I get an error in the initialisation of the firebase:

Error in firebase.init: TypeError: FIRAnalytics.setAnalyticsCollectionEnabled is not a function. (In 'FIRAnalytics.setAnalyticsCollectionEnabled(arg.analyticsCollectionEnabled !== false)', 'FIRAnalytics.setAnalyticsCollectionEnabled' is undefined).

You also can reproduce this error in the Demo App.
Press button 'init firebase - do this first' and look at the console

I hope you can fix this problem.
Thanks in advanced

Rob

**Comment by EddyVerbruggen** [comment]
Do you mean in the demo app you uncommented this and ran `npm run demo.ios` from the `src` folder?

https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/a67e4ba754f83b07d83e94dadeb44f53dcfa9c20/demo/app/main-view-model.ts#L398

**Comment by Robernator** [comment]
Yes. Indeed.  


Verstuurd vanaf mijn iPhone

**Comment by MopheusDG** [comment]
Same problem for me, only IOS is giving me the same error and under my own project. Any chance to identify the problem ?

Error in firebase.init: TypeError: FIRAnalytics.setAnalyticsCollectionEnabled is not a function. (In 'FIRAnalytics.setAnalyticsCollectionEnabled(arg.analyticsCollectionEnabled !== false)', 'FIRAnalytics.setAnalyticsCollectionEnabled' is undefined).

Thanks.

**Comment by Robernator** [comment]
The problem still exists in 9.0.3 for iOS

You can easily reproduce this error.
git clone the project
cd src.
npm i
npm run demo.ios

In the IOS emulator:
- choose menu Native App
- press button 'Init  firebase do this first'
see the console:
CONSOLE LOG file:///app/main-view-model.js:356:24: firebase.init error: TypeError: FIRAnalytics.setAnalyticsCollectionEnabled is not a function. (In 'FIRAnalytics.setAnalyticsCollectionEnabled(arg.analyticsCollectionEnabled !== false)', 'FIRAnalytics.setAnalyticsCollectionEnabled' is undefined)

I hope this issue will be fixed.

Rob

**Comment by EddyVerbruggen** [comment]
I'm not sure why the `FIRAnalytics` would be missing, but I've now added a guard to prevent that error.
