### ISSUE TITLE
barcode scanner scanResult event keeps firing every second VueJS only.

### ISSUE THREAD

**Issue by mehulcs** [EddyVerbruggen/nativescript-plugin-firebase#1309]
I'm using `mlkit/barcodescanner`, `scanResult` event keeps firing every second and does not scan any QR code. The issue is only on Nativescript Vue. Angular demo app of this repository works completely fine and Vue demo app does not have sample for barcode scanner, Adding barcode scanner results in the same issue `scanResult` keeps firing.

**Comment by EddyVerbruggen** [comment]
Would you mind sharing a minimal sample app reproducing this?

**Comment by mehulcs** [comment]
Apologies for not putting in issue, https://github.com/mehulcs/barcodescanner-test

**Comment by mehulcs** [comment]
Well, that was a blooper, It fires event even with an empty result property.

**Comment by Argus444** [comment]
> Well, that was a blooper, It fires event even with an empty result property.
> Wondering, Are there any downsides of calling `this.notify` method only when `result.barcodes` length is not zero.

Hi, were you able to resolve this issue. I am also facing the same issue

**Comment by mehulcs** [comment]
I resolved by putting a condition to check whether parameter `result` has key `barcodes` and length is greater than 0, Then you get a result in `result.barcodes`.
