### ISSUE TITLE
Multiple Environments Issue (authentication)

### ISSUE THREAD

**Issue by keerl** [EddyVerbruggen/nativescript-plugin-firebase#1310]
I am setting up a project to use multiple environments. I'm currently using the `.dev` and `.prod` feature that is already implemented for this, but the issue I am having is for Google Authentication. 

I am suppose to add `REVERSED_CLIENT_ID` to `app/App_Resources/iOS/Info.plist` but this value will be different for each environment I am working in.

Is there any way to anyway I can configure this to switch automatically depending on if I'm building for development or production?

**Comment by keerl** [comment]
I think I figured it out. In `build.xcconfig` I can add a variable that changes value depending on the build.
```
REVERSED_CLIENT_ID[config=Debug] = com.googleusercontent.apps.1052836194035-l81fsjai1u40ocnqjcpnoebnnsltt03b;
REVERSED_CLIENT_ID[config=Release] = com.googleusercontent.apps.1152836194035-l81fsjai1u40ocnqjcpnoebnnsltt03c;
```
Then in `Info.plist` I reference this variable instead of the actual value. It seems to be working so far.
```
<key>CFBundleURLTypes</key>
<array>
	<dict>
		<key>CFBundleTypeRole</key>
		<string>Editor</string>
		<key>CFBundleURLName</key>
		<string>REVERSED_CLIENT_ID</string>
		<key>CFBundleURLSchemes</key>
		<array>
			<string>${REVERSED_CLIENT_ID}</string>
		</array>
	</dict>
</array>
```

**Comment by anarnoli** [comment]
Hey, I have similar scenario with Dev and Prod and struggling to get correct REVERSED_CLIENT_ID in Info.plist file.

How are you mapping correct value for REVERSED_CLIENT_ID in `build.xconfig`?
