### ISSUE TITLE
It seam that Provider interface need to extend with token property

### ISSUE THREAD

**Issue by ycherniavskyi** [EddyVerbruggen/nativescript-plugin-firebase#1316]
This issue related to operation with plugin by TypeScript.

In [Facebook login](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/AUTHENTICATION.md#facebook-login) and [Google Sign-In](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/AUTHENTICATION.md#google-sign-in) documentation mentioned that as result we get response with next part:
``` json
"providers": [
         {
             "id": "facebook.com | google.com",
             "token": "<FB token> | <Google Access Token>"
         }
     ]
```
and I got it in `result` which is `User` interface, but `Provider` interface does not have `token` property, so I need to cast it to `any` to access to `token`.

So it seam that `Provider` interface need to by updated next way:
``` ts
export interface Provider {
  id: string;
  token?: string;
}
```

**Comment by EddyVerbruggen** [comment]
Hi!

If you’re positive this behaves similar on both platforms, please consider creating a PR.
