### ISSUE TITLE
[Feature request] Get Firebase timestamp

### ISSUE THREAD

**Issue by NordlingArt** [EddyVerbruggen/nativescript-plugin-firebase#132]
**Android:** https://firebase.google.com/docs/reference/android/com/google/firebase/database/ServerValue

**iOS:** https://firebase.google.com/docs/reference/ios/firebasedatabase/interface_f_i_r_server_value.html#a39c5a614879f2040d9355977a4879071

I feel like this should be a simple task to implement :) It's needed to prevent users to manipulate their local timestamp.

**Comment by EddyVerbruggen** [comment]
Thanks for the links to the SDK's, that's really helpful.

Do you also have a suggestion how you'd want to use this feature?

**Comment by NordlingArt** [comment]
@EddyVerbruggen - No worries! I believe the most efficient way to use this is to follow the steps of the JS version of Firebase ([link to documentation](https://www.firebase.com/docs/web/api/servervalue/timestamp.html)):

```js
var timestamp = Firebase.ServerValue.TIMESTAMP;
```

Or we could wrap it in a function so the timestamp is retrieved from the server upon method call:

```js
var timestamp = Firebase.ServerValue.TIMESTAMP();
```

Currently `ServerValue` only has `TIMESTAMP` (As [documented here](https://www.firebase.com/docs/web/api/servervalue/)). But I would still suggest that `ServerValue` stays as an object for other future values.

**Comment by EddyVerbruggen** [comment]
Note to self: [iOS doc](https://firebase.google.com/docs/database/ios/offline-capabilities), [Android doc](https://firebase.google.com/docs/database/android/offline-capabilities). Scroll down to 'Server Timestamps' for both platforms.

**Comment by EddyVerbruggen** [comment]
Hey @NordlingArt, I've now added a way to fill a property serverside based on this placeholder. [Check the doc](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/DATABASE.md#adding-an-update-timestamp).

It's available now in the master (default) branch of this repo so if you want to test it, install the plugin from GitHub.

Is there anything else you need regarding this?

**Comment by NordlingArt** [comment]
@EddyVerbruggen - Sorry for the late response. This is perfect, thanks!
