### ISSUE TITLE
App crash after version update from v5.3.1 to v8.3.2

### ISSUE THREAD

**Issue by it3r4-pineda** [EddyVerbruggen/nativescript-plugin-firebase#1328]
my app crashes after I update my firebase version any version higher than v5.3.1

my app was built by the time v5.3.1 was the latest version and I never updated it ever since. Now I updated it to a newer version, the build process went fine but whenever I try to open my app it crashes without an error log. It just closes itself whenever I try to open it.

**Framework versions:**

**Nodes.js:** v10.16.0
**npm:** v6.9.0
**Nativescript CLI:** v5.4.2

the errors i've found are:

> Error detected during LiveSync on 84RDU17125010328 for F:\NativeScript\simpleapp. Error: Socket connection timed out.

and: 

*note: error found in Nativescript sidekick Device Console during build.

> System.err: android.content.pm.PackageManager$NameNotFoundException: org.nativescript.ustpsystem
> System.err: 	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:363)
> System.err: 	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:345)
> System.err: 	at com.huawei.systemmanager.power.model.BatteryStatisticsHelper.updateBatteryInfos(BatteryStatisticsHelper.java:143)
> System.err: 	at com.huawei.systemmanager.power.receiver.handle.HandlePackageRemoved.handlePackageRemoved(HandlePackageRemoved.java:26)
> System.err: 	at com.huawei.systemmanager.power.receiver.handle.HandlePackageRemoved.handleBroadcast(HandlePackageRemoved.java:18)
> System.err: 	at com.huawei.systemmanager.power.receiver.BootBroadcastReceiver.doInBackground(BootBroadcastReceiver.java:109)
> System.err: 	at java.lang.reflect.Method.invoke(Native Method)
> System.err: 	at com.huawei.systemmanager.util.content.HsmIntentService$Work.reflectTargetReceiver(HsmIntentService.java:231)
> System.err: 	at com.huawei.systemmanager.util.content.HsmIntentService$Work.doBackgroud(HsmIntentService.java:212)
> System.err: 	at com.huawei.systemmanager.util.content.HsmIntentService$Work.run(HsmIntentService.java:192)
> System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
> System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
> System.err: 	at java.lang.Thread.run(Thread.java:776)
> System.err: java.lang.SecurityException: uid 10978 does not have android.permission.UPDATE_DEVICE_STATS.
> System.err: 	at android.app.ContextImpl.enforce(ContextImpl.java:1760)
> System.err: 	at android.app.ContextImpl.enforcePermission(ContextImpl.java:1773)
> System.err: 	at com.android.server.am.BatteryStatsService.enforceCallingPermission(BatteryStatsService.java:1202)
> System.err: 	at com.android.server.am.BatteryStatsService.noteStartVideo(BatteryStatsService.java:756)
> System.err: 	at com.android.internal.app.IBatteryStats$Stub.onTransact(IBatteryStats.java:72)
> System.err: 	at android.os.Binder.execTransact(Binder.java:565)
> System.err: java.lang.SecurityException: uid 10978 does not have android.permission.UPDATE_DEVICE_STATS.
> System.err: 	at android.app.ContextImpl.enforce(ContextImpl.java:1760)
> System.err: 	at android.app.ContextImpl.enforcePermission(ContextImpl.java:1773)
> System.err: 	at com.android.server.am.BatteryStatsService.enforceCallingPermission(BatteryStatsService.java:1202)
> System.err: 	at com.android.server.am.BatteryStatsService.noteStopVideo(BatteryStatsService.java:766)
> System.err: 	at com.android.internal.app.IBatteryStats$Stub.onTransact(IBatteryStats.java:81)
> System.err: 	at android.os.Binder.execTransact(Binder.java:565)
> System.err: java.lang.SecurityException: uid 10978 does not have android.permission.UPDATE_DEVICE_STATS.
> System.err: 	at android.app.ContextImpl.enforce(ContextImpl.java:1760)
> System.err: 	at android.app.ContextImpl.enforcePermission(ContextImpl.java:1773)
> System.err: 	at com.android.server.am.BatteryStatsService.enforceCallingPermission(BatteryStatsService.java:1202)
> System.err: 	at com.android.server.am.BatteryStatsService.noteStartVideo(BatteryStatsService.java:756)
> System.err: 	at com.android.internal.app.IBatteryStats$Stub.onTransact(IBatteryStats.java:72)
> System.err: 	at android.os.Binder.execTransact(Binder.java:565)
> System.err: java.lang.SecurityException: uid 10978 does not have android.permission.UPDATE_DEVICE_STATS.
> System.err: 	at android.app.ContextImpl.enforce(ContextImpl.java:1760)
> System.err: 	at android.app.ContextImpl.enforcePermission(ContextImpl.java:1773)
> System.err: 	at com.android.server.am.BatteryStatsService.enforceCallingPermission(BatteryStatsService.java:1202)
> System.err: 	at com.android.server.am.BatteryStatsService.noteStopVideo(BatteryStatsService.java:766)
> System.err: 	at com.android.internal.app.IBatteryStats$Stub.onTransact(IBatteryStats.java:81)
> System.err: 	at android.os.Binder.execTransact(Binder.java:565)
> System.err: java.lang.SecurityException: uid 10978 does not have android.permission.UPDATE_DEVICE_STATS.
> System.err: 	at android.app.ContextImpl.enforce(ContextImpl.java:1760)
> System.err: 	at android.app.ContextImpl.enforcePermission(ContextImpl.java:1773)
> System.err: 	at com.android.server.am.BatteryStatsService.enforceCallingPermission(BatteryStatsService.java:1202)
> System.err: 	at com.android.server.am.BatteryStatsService.noteStartVideo(BatteryStatsService.java:756)
> System.err: 	at com.android.internal.app.IBatteryStats$Stub.onTransact(IBatteryStats.java:72)
> System.err: 	at android.os.Binder.execTransact(Binder.java:565)
> System.err: java.lang.SecurityException: uid 10978 does not have android.permission.UPDATE_DEVICE_STATS.
> System.err: 	at android.app.ContextImpl.enforce(ContextImpl.java:1760)
> System.err: 	at android.app.ContextImpl.enforcePermission(ContextImpl.java:1773)
> System.err: 	at com.android.server.am.BatteryStatsService.enforceCallingPermission(BatteryStatsService.java:1202)
> System.err: 	at com.android.server.am.BatteryStatsService.noteStopVideo(BatteryStatsService.java:766)
> System.err: 	at com.android.internal.app.IBatteryStats$Stub.onTransact(IBatteryStats.java:81)
> System.err: 	at android.os.Binder.execTransact(Binder.java:565)
> System.err: java.lang.SecurityException: uid 10978 does not have android.permission.UPDATE_DEVICE_STATS.
> System.err: 	at android.app.ContextImpl.enforce(ContextImpl.java:1760)
> System.err: 	at android.app.ContextImpl.enforcePermission(ContextImpl.java:1773)
> System.err: 	at com.android.server.am.BatteryStatsService.enforceCallingPermission(BatteryStatsService.java:1202)
> System.err: 	at com.android.server.am.BatteryStatsService.noteStartVideo(BatteryStatsService.java:756)
> System.err: 	at com.android.internal.app.IBatteryStats$Stub.onTransact(IBatteryStats.java:72)
> System.err: 	at android.os.Binder.execTransact(Binder.java:565)
> System.err: java.lang.SecurityException: uid 10978 does not have android.permission.UPDATE_DEVICE_STATS.
> System.err: 	at android.app.ContextImpl.enforce(ContextImpl.java:1760)
> System.err: 	at android.app.ContextImpl.enforcePermission(ContextImpl.java:1773)
> System.err: 	at com.android.server.am.BatteryStatsService.enforceCallingPermission(BatteryStatsService.java:1202)
> System.err: 	at com.android.server.am.BatteryStatsService.noteStopVideo(BatteryStatsService.java:766)
> System.err: 	at com.android.internal.app.IBatteryStats$Stub.onTransact(IBatteryStats.java:81)
> System.err: 	at android.os.Binder.execTransact(Binder.java:565)
> System.err: java.lang.SecurityException: uid 10978 does not have android.permission.UPDATE_DEVICE_STATS.
> System.err: 	at android.app.ContextImpl.enforce(ContextImpl.java:1760)
> System.err: 	at android.app.ContextImpl.enforcePermission(ContextImpl.java:1773)
> System.err: 	at com.android.server.am.BatteryStatsService.enforceCallingPermission(BatteryStatsService.java:1202)
> System.err: 	at com.android.server.am.BatteryStatsService.noteStartVideo(BatteryStatsService.java:756)
> System.err: 	at com.android.internal.app.IBatteryStats$Stub.onTransact(IBatteryStats.java:72)
> System.err: 	at android.os.Binder.execTransact(Binder.java:565)
> System.err: java.lang.SecurityException: uid 10978 does not have android.permission.UPDATE_DEVICE_STATS.
> System.err: 	at android.app.ContextImpl.enforce(ContextImpl.java:1760)
> System.err: 	at android.app.ContextImpl.enforcePermission(ContextImpl.java:1773)
> System.err: 	at com.android.server.am.BatteryStatsService.enforceCallingPermission(BatteryStatsService.java:1202)
> System.err: 	at com.android.server.am.BatteryStatsService.noteStopVideo(BatteryStatsService.java:766)
> System.err: 	at com.android.internal.app.IBatteryStats$Stub.onTransact(IBatteryStats.java:81)
> System.err: 	at android.os.Binder.execTransact(Binder.java:565)
> System.err: java.lang.SecurityException: uid 10978 does not have android.permission.UPDATE_DEVICE_STATS.
> System.err: 	at android.app.ContextImpl.enforce(ContextImpl.java:1760)
> System.err: 	at android.app.ContextImpl.enforcePermission(ContextImpl.java:1773)
> System.err: 	at com.android.server.am.BatteryStatsService.enforceCallingPermission(BatteryStatsService.java:1202)
> System.err: 	at com.android.server.am.BatteryStatsService.noteStartVideo(BatteryStatsService.java:756)
> System.err: 	at com.android.internal.app.IBatteryStats$Stub.onTransact(IBatteryStats.java:72)
> System.err: 	at android.os.Binder.execTransact(Binder.java:565)
> System.err: java.lang.SecurityException: uid 10978 does not have android.permission.UPDATE_DEVICE_STATS.
> System.err: 	at android.app.ContextImpl.enforce(ContextImpl.java:1760)
> System.err: 	at android.app.ContextImpl.enforcePermission(ContextImpl.java:1773)
> System.err: 	at com.android.server.am.BatteryStatsService.enforceCallingPermission(BatteryStatsService.java:1202)
> System.err: 	at com.android.server.am.BatteryStatsService.noteStopVideo(BatteryStatsService.java:766)
> System.err: 	at com.android.internal.app.IBatteryStats$Stub.onTransact(IBatteryStats.java:81)
> System.err: 	at android.os.Binder.execTransact(Binder.java:565)
> System.err: java.lang.SecurityException: uid 10978 does not have android.permission.UPDATE_DEVICE_STATS.
> System.err: 	at android.app.ContextImpl.enforce(ContextImpl.java:1760)
> System.err: 	at android.app.ContextImpl.enforcePermission(ContextImpl.java:1773)
> System.err: 	at com.android.server.am.BatteryStatsService.enforceCallingPermission(BatteryStatsService.java:1202)
> System.err: 	at com.android.server.am.BatteryStatsService.noteStartVideo(BatteryStatsService.java:756)
> System.err: 	at com.android.internal.app.IBatteryStats$Stub.onTransact(IBatteryStats.java:72)
> System.err: 	at android.os.Binder.execTransact(Binder.java:565)
> System.err: java.lang.SecurityException: uid 10978 does not have android.permission.UPDATE_DEVICE_STATS.
> System.err: 	at android.app.ContextImpl.enforce(ContextImpl.java:1760)
> System.err: 	at android.app.ContextImpl.enforcePermission(ContextImpl.java:1773)
> System.err: 	at com.android.server.am.BatteryStatsService.enforceCallingPermission(BatteryStatsService.java:1202)
> System.err: 	at com.android.server.am.BatteryStatsService.noteStopVideo(BatteryStatsService.java:766)
> System.err: 	at com.android.internal.app.IBatteryStats$Stub.onTransact(IBatteryStats.java:81)
> System.err: 	at android.os.Binder.execTransact(Binder.java:565)
> ActivityManager: Start dump, calling from : pid=0, uid=2000
> System.err: java.lang.SecurityException: uid 10978 does not have android.permission.UPDATE_DEVICE_STATS.
> System.err: 	at android.app.ContextImpl.enforce(ContextImpl.java:1760)
> System.err: 	at android.app.ContextImpl.enforcePermission(ContextImpl.java:1773)
> System.err: 	at com.android.server.am.BatteryStatsService.enforceCallingPermission(BatteryStatsService.java:1202)
> System.err: 	at com.android.server.am.BatteryStatsService.noteStartVideo(BatteryStatsService.java:756)
> System.err: 	at com.android.internal.app.IBatteryStats$Stub.onTransact(IBatteryStats.java:72)
> System.err: 	at android.os.Binder.execTransact(Binder.java:565)
> 

the only way to run the app back is by reverting firebase version to v5.3.1. any version higher than that returns the problem

**Comment by EddyVerbruggen** [comment]
What if I reported a bug like this on one of your projects? 😀
Please elaborate. A lot.

**Comment by it3r4-pineda** [comment]
edited my issue sorry for that :(

**Comment by EddyVerbruggen** [comment]
No worries. Can you share your repo (or something stripped-down that reproduces it)? It's must be quite specific to your setup because all demo apps in this repo work just fine..

**Comment by it3r4-pineda** [comment]
@EddyVerbruggen  here's the repo https://github.com/it3r4-pineda/ustpsystem

**Comment by EddyVerbruggen** [comment]
@it3r4-pineda Looks like this is missing: https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/b389c3242890e6966130e85f68dc7f7ea1e449cb/docs/ADMOB.md#android
