### ISSUE TITLE
Real Device IOS IPad Push Notification Token Always Return Undefined.

### ISSUE THREAD

**Issue by Rjgoolsby** [EddyVerbruggen/nativescript-plugin-firebase#1330]
Same as many have reported. Very simple app. Just trying to get the push notification token to use for an external messenger. Here's the Repo https://github.com/Rjgoolsby/firebase-message-app . I added you as a collaborator. Let me know if it didn't work and if you can't access it. 

I followed the instructions to a Tee. Here's also screen shots of Xcode to show a valid signing.
Any guidance and help I'd be grateful. 

![Screen Shot 2019-07-11 at 10 33 49 PM](https://user-images.githubusercontent.com/10386821/61098170-0a4f5b80-a42c-11e9-982b-01ffb61a597f.png)
![Screen Shot 2019-07-11 at 10 33 33 PM](https://user-images.githubusercontent.com/10386821/61098174-0e7b7900-a42c-11e9-8840-81f8e644efb9.png)

**Comment by Rjgoolsby** [comment]
@EddyVerbruggen, Can you take a look at this repo and me know whether this is a known issue, or did I set this up wrong? It's just a basic repo and I followed the instructions for Message Only Firebase setup.

**Comment by EddyVerbruggen** [comment]
Let's continue in your repo then.

**Comment by ShabanRamadani** [comment]
@EddyVerbruggen Having the same problem only on iOS, have you managed to find a solution regarding this one?

**Comment by EddyVerbruggen** [comment]
Sure, the plugin wasn't `require`d in `app.ts`.
