### ISSUE TITLE
Parameter Reporting Not Working

### ISSUE THREAD

**Issue by Manbearpixel** [EddyVerbruggen/nativescript-plugin-firebase#1331]
After reading the Analytics Doc about logging events to firebase, I tried logging an event with parameters and I am so far not seeing any parameters properly set on Firebase.

Doc Implementation:
```
firebase.analytics.logEvent({
    key: "add_to_cart",
    parameters: [ // optional
      {
        key: "item_id",
        value: "p7654"
      },
      {
        key: "item_name",
        value: "abc"
      }]
  }).then(
      function () {
        console.log("Firebase Analytics event logged");
      }
  );
```

My implementation:
```
firebase.analytics.logEvent({
      key: 'spend_virtual_currency',
      parameters: [
        {
          key: 'virtual_currency_name',
          value: 'xxx'
        },
        {
          key: 'item_name',
          value: 'xxx'
        }
      ]
    })
    .then(() => { console.log('[Analytics] Metric logged'); });
```

Now, I know there are predefined events and predefined event parameters for Firebase logging, and I specifically looked up the event I am using above ([Source](https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.Event.html#SPEND_VIRTUAL_CURRENCY)).

Yet when checking Firebase to see if this was capturing the parameters there have so far been nothing recorded. I am not sure what else I need to do to capture these parameters.

**Comment by EddyVerbruggen** [comment]
You’re doing it right. I tested something similar on iOS yesterday and it worked fine. Perhaps it needs some time to show up?

**Comment by Manbearpixel** [comment]
@EddyVerbruggen I've waited a few days and I unfortunately do not see anything showing up... I'll likely have to try again on a fresh project for nativescript and firebase and see if I can replicate this issue :(

**Comment by EddyVerbruggen** [comment]
Hmm, sorry to hear that. Just fyi, I tried with NativeScript 5.x and the latest version of the plugin, and on iOS only.

To double check I just looked at the streamview while adding items to a cart in my app and after a minute or so this popped up:

<img width="1160" alt="Screenshot 2019-07-12 at 19 58 20" src="https://user-images.githubusercontent.com/1426370/61148633-80f96100-a4df-11e9-9131-9d947a0608ef.png">

So the event `cart_item_added` has a property `name` which represents the product name that was added to the cart. The code to push to Analytics is almost identical to yours.

**Comment by Manbearpixel** [comment]
@EddyVerbruggen I'm not seeing this event `cart_item_added` in the list of predefined [FirebaseAnalytics.Events](https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.Event.html). I see `add_to_cart` however, so I'm not sure where you have a list of events you can use? Maybe I am using the wrong one.

**Comment by Manbearpixel** [comment]
I've created a simple version of the interaction I am using in my application where parameter reporting is not working for Android. I've not tested this on iOS. Can you please have a look and test this using your own Firebase setup and see if you get anything to come through? I'd appreciate the assistance!

**Comment by EddyVerbruggen** [comment]
Hu @Manbearpixel, [this is not an allowed value](https://github.com/Manbearpixel/ns-firebase/blob/725b740e5f61f71ccb0358c69ef768e85f6fe9a0/src/app/item/items.component.ts#L82), and plugin version 9.0.4 will give you meaningful feedback if you try to send invalid key/param values to Firebase, because I've implemented validation based on rules like [these](https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.Param).
