### ISSUE TITLE
Bug Report: iOS _pushToken/device deviceToken.description.replace(/[< >]/g, "") Is Not Valid FCM Token

### ISSUE THREAD

**Issue by Rjgoolsby** [EddyVerbruggen/nativescript-plugin-firebase#1336]
# Problem
When using plugin for external messaging only, FIRMessaging pod isn't installed so it's always undefined. Because of this _pushToken uses the deviceToken description which isn't a valid FCM token. 

# Reproduce 
Create app with External messaging only. In other words adjust your firebase.nativescript.json to 
```
{
    "external_push_client_only": true,
    "using_ios": true,
    "using_android": true
}

```

# Description
Register for push token. The token returned is the device description and it's not a valid FCM token. 

This only occurs if you only use the plugin for external messaging. I'm guessing it's because the FIRMessaging pod isn't installed so it's always undefined. Because of this it uses the deviceToken description as the token.

If you go to  `node_modules/nativescript-plugin-firebase/messaging/messaging.ios.js line:148`. OR Line 165 in the ts file: https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/08e81b1ec96335a3287118a89120b1c915cd8933/src/messaging/messaging.ios.ts#L165
 
You'll see it there. 

Then if you `getCurrentPushToken` it return this `_pushToken` because `FIRMessaging == undefined` https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/08e81b1ec96335a3287118a89120b1c915cd8933/src/messaging/messaging.ios.ts#L66

Also because of this, if you call `registerForPushNotifications` it returns `_pushToken` because of this line https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/08e81b1ec96335a3287118a89120b1c915cd8933/src/messaging/messaging.ios.ts#L136

The only way to avoid this is use the plugin in its entirety.

**Comment by Rjgoolsby** [comment]
This is not a bug. This is desired. Be sure to configure your APN correctly in your apple developers account.

**Comment by Rjgoolsby** [comment]
Reopening this because I just confirmed this to be true. 
 
Firebase is returning the APN and not registering it with Firebase to use FCM. 

In order to use this with FCM you have to get a token registered. 

You can do it via their API via 
```
url -X POST -H "Authorization: key=YOUR_FCM_SERVER_KEY" -H "Content-Type: application/json" -d '{
    "application": "com.nraboy.nativescriptexample",
    "sandbox":false,
    "apns_tokens":[
        "368dde283db539abc4a6419b1795b6131194703b816e4f624ffa12",
        "76b39c2b2ceaadee8400b8868c2f45325ab9831c1998ed70859d86"
    ]
}' "https://iid.googleapis.com/iid/v1:batchImport"
```
then you can use the FCM

I followed the tutorial here https://www.thepolyglotdeveloper.com/2017/06/apns-tokens-fcm-tokens-simple-http

like so 
```
curl -X POST \
  https://fcm.googleapis.com/fcm/send \
  -H 'Authorization: key=YOUR_FCM_SERVER_KEY' \ 
  -H 'Content-Type: application/json' \
  -d '{
	"to" : "FCM TOKEN",
	"notification" : {
		"body" : "test",
		"title" : "test",
		"content_available" : true,
		"priority" : "high"
	}
}'
```

Is this a BUG or is this desired and need to be updated in the Docs that the token on ios is an APN token and an additional step needs to be taken?

**Comment by EddyVerbruggen** [comment]
If you want to use Firebase Messaging (FCM) then your `external_push_client_only` should actually be `false` as you're not using an "external" provider (like Amazon, Pushy, Pushwoosh, *whatever*).

So if your intention is to actually use Firebase Messaging please remove that firebase.nativescript.json file and run `npm i`. This time answer `n` to the first question and answer `y` when it prompts you if you want to use Firebase Messaging.

**Comment by Rjgoolsby** [comment]
@EddyVerbruggen User/Developer Error again!
