### ISSUE TITLE
Sign In with Apple

### ISSUE THREAD

**Issue by rynop** [EddyVerbruggen/nativescript-plugin-firebase#1340]
Just wanted to get the Firebase team's progress and statement about supporting sign in with Apple on your radar.  My hope is you can roll the firebase SDK update containing this FR (once complete) into this plugin and add support for sign in with apple as a first class [authentication provider](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/AUTHENTICATION.md).

> we are committed to releasing Sign in with Apple support before Sign in with Apple is mandatory for new apps, which is expected to happen in fall of this year

^per https://github.com/firebase/firebase-ios-sdk/issues/3145#issuecomment-513310787 

thanks

**Comment by EddyVerbruggen** [comment]
Hey @rynop, thanks for making me aware of this! I've now subscribed to that issue. I'm also [pretty interested](https://github.com/EddyVerbruggen/nativescript-apple-sign-in) in this feature.

**Comment by rynop** [comment]
np my man. I had no idea about your apple sign-in plugin, thanks for linking it here.  Very useful if FBase is unable to hold to their commitment.

**Comment by abhayastudios** [comment]
Looks like Firebase now supports [Apple sign-in](https://firebase.google.com/docs/auth/ios/apple)

**Comment by rynop** [comment]
Hi @EddyVerbruggen just a heads up [FBase Sign In With Apple](This is available in the latest SDK release (6.13.0)) is now supported in SDK release (6.13.0).

Details at https://github.com/firebase/firebase-ios-sdk/issues/3145#issuecomment-554113378

**Comment by EddyVerbruggen** [comment]
Hey guys! I also received the notification from the upstream repo and started working on it on my plane back from jsMobileConf in Boston :)

I hope to have this ready soon, but I have quite the pile of work waiting for me at home. More soon!

**Comment by EddyVerbruggen** [comment]
That wasn't super easy, but I think that's it! Check out the [Sign in with Apple docs](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/AUTHENTICATION.md#sign-in-with-apple) in this repo.
