### ISSUE TITLE
MLKitTextRecognition rotation bug when device orientation changed 

### ISSUE THREAD

**Issue by jacky-tay** [EddyVerbruggen/nativescript-plugin-firebase#1341]
I've been testing the demo app for text recognition, and I have noticed that when the device orientation changed, live camera preview seems to stay at its previous orientation.

![Bug](https://user-images.githubusercontent.com/1891395/61674913-2adfb580-ad4a-11e9-812f-44dbf66d0bf9.gif)

**Comment by alexander-mai** [comment]
This is a bug in the android implementation.
There is no event listener for orientation change, which corrects the camera orientation like on iOS.
The orientation is only set on once here: https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/4c60759c2148fbcbde09f65868de0a828dc8b37c/src/mlkit/mlkit-cameraview.android.ts#L157
Adding an listener like on iOS will fix the problem:
application.on("orientationChanged", () => { this.setRotation(this.camera, parameters, requestedCameraId) });
