### ISSUE TITLE
Google signIn doesn't work after last major update.

### ISSUE THREAD

**Issue by NeevorPL** [EddyVerbruggen/nativescript-plugin-firebase#1343]
As a part of last major Nativescript upgrade (5.4 => 6.0), it was also an firebase plugin upgrade (8.3.2 => 9.0.4).

Before that day everything worked perfectly with configuration:
```
{
    "external_push_client_only": false,
    "using_ios": true,
    "using_android": true,
    "firestore": false,
    "realtimedb": false,
    "authentication": true,
    "remote_config": false,
    "performance_monitoring": false,
    "messaging": false,
    "in_app_messaging": true,
    "crashlytics": false,
    "crash_reporting": false,
    "storage": false,
    "functions": false,
    "facebook_auth": false,
    "google_auth": true,
    "admob": false,
    "invites": false,
    "dynamic_links": false,
    "ml_kit": false
}
```
and some tweaks in build.gradle
![image](https://user-images.githubusercontent.com/53299345/61869596-47135c00-aedc-11e9-8445-73424fb428ad.png)

and the way i'm logging in (JS + Vue):
```
          this.$firebase.login({
            type: this.$firebase.LoginType.GOOGLE,
            googleOptions: {
              hostedDomain: 'somedomain.com',
              scopes: ['https://tools.somedomain.com/holidays/']
            }
          }).then(
            (r) => { console.log("Processing user data here"); },
            (e) => { console.log("Auth result retrieval error: " + e); }
          );
          },
            (e) => { console.log(e); }
          );
```
All above worked for me just fine for previous versions of SDK and mentioned versions of {N} and Firebase plugin.

Now after:
- doublechecked google-services.json
- triplechecked SHAs
- deleted and recreated node_modules and platforms
- deleted and recreated firebase project (aldo with consent screen configuration and stuff)
- crying a lot

the result is:

> JS: 'Error in firebase.login: TypeError: Cannot read property \'getInstance\' of undefined'
> JS: [TypeError: Cannot read property 'getInstance' of undefined]

for configuration like
```
{
    "external_push_client_only": false,
    "using_ios": false,
    "using_android": true,
    "firestore": false,
    "realtimedb": false,
    "authentication": false,
    "remote_config": false,
    "performance_monitoring": false,
    "messaging": false,
    "in_app_messaging": false,
    "crashlytics": false,
    "storage": false,
    "functions": false,
    "facebook_auth": false,
    "google_auth": true,
    "admob": false,
    "dynamic_links": false,
    "ml_kit": false
}
```

and/or...
> JS: 'Make sure you\'ve uploaded your SHA1 fingerprint(s) to the Firebase console. Status: Status{statusCode=unknown status code: 12500, resolution=null}'
> JS: 'Has the SHA1 fingerprint been uploaded? Sign-in status: Status{statusCode=unknown status code: 12500, resolution=null}'

for configuration
```
{
    "external_push_client_only": false,
    "using_ios": false,
    "using_android": true,
    "firestore": false,
    "realtimedb": false,
    "authentication": true,
    "remote_config": false,
    "performance_monitoring": false,
    "messaging": false,
    "in_app_messaging": false,
    "crashlytics": false,
    "storage": false,
    "functions": false,
    "facebook_auth": false,
    "google_auth": true,
    "admob": false,
    "dynamic_links": false,
    "ml_kit": false
}
```
and adb log said....

> 07-25 12:19:29.940 11768 11771 I zygote  : After code cache collection, code=48KB, data=44KB
> 07-25 12:19:29.941 11768 11771 I zygote  : Increasing code cache capacity to 256KB
> 07-25 12:19:29.941  1444  1444 W SurfaceFlinger: couldn't log to binary event log: overflow.
> 07-25 12:19:30.334 18251 18251 W AutoManageHelper: Unresolved error while connecting client. Stopping auto-manage.
> 07-25 12:19:30.463 20621 20621 I JS      : 'Make sure you\'ve uploaded your SHA1 fingerprint(s) to the Firebase console. Status: Status{statusCode=unknown status code: 12500, resolution=null}'

that's all folks
i'm on dead end

**Comment by EddyVerbruggen** [comment]
Hi, I just ran the demo app in this repo for both iOS and Android with NativeScript 6 and was able to log in without problems.

That error code is reported [a lot on Google](https://www.google.com/search?q=android+google+login+status+code+12500&oq=android+google+login+status+code+12500&aqs=chrome..69i57j69i64.4494j0j7&sourceid=chrome&ie=UTF-8).. not sure how I can help here.

**Comment by Skintillion** [comment]
I upgraded, logged in just fine as well.
