### ISSUE TITLE
Crashlytics: upload-symbols killing my machine

### ISSUE THREAD

**Issue by abhayastudios** [EddyVerbruggen/nativescript-plugin-firebase#1347]
Hey @EddyVerbruggen!

Since the last few versions of Xcode, I’m having this annoying issue with building for iOS. Every time when doing a full build, many instances of a process called `upload-symbols` are spawned by the Fabric post build step added by [this plugin](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/publish/scripts/installer.js#L533-L555). These processes run briefly, hog all the system memory (16G) and then my system becomes irresponsive.

As far as I understand, running this process is only helpful if we are running a release build. What do you think of indeed running this process only for release builds? Something like suggested [here](https://stackoverflow.com/a/40953102/918269):

```
if [ "$CONFIGURATION" == "Release" ]; then
  echo "Release build: uploading symbols!"
  "${PODS_ROOT}/Fabric/run"
else
  echo "Non-release build: skip uploading symbols!"
fi
```

**Comment by abhayastudios** [comment]
Seems to have solved itself after upgrading to NS 6 which includes changes in handling of hooks.

**Comment by jacopo69** [comment]
Hello @abhayastudios,
I have same problem although I upgraded NS to 6.1 version.
Are you sure that this issue depends on NS? Did you solve it finally?

**Comment by abhayastudios** [comment]
hi @jacopo69 part of the upgrade to NS6.0 I removed all the hooks and reinstalled the plugin. I've seen it still, but somehow it happens a lot less even on NS 6.1. I just did a `killall -9 upload-symbols` to free it. As far as I know uploading the symbols only makes sense for release builds.

**Comment by jacopo69** [comment]
I agree with you
