### ISSUE TITLE
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

### ISSUE THREAD

**Issue by mpilija** [EddyVerbruggen/nativescript-plugin-firebase#1351]
While building with latest version of CLI and plugin following error occurs:

Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
  The number of method references in a .dex file cannot exceed 64K.
  Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
[00:01:06.958] [WARN]   option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 45s

[00:01:07.538] [WARN]  Command ./gradlew failed with exit code 1

[00:01:07.859] [ERROR] D8: Cannot fit requested classes in a single dex file (# methods: 109499 > 65536)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
  The number of method references in a .dex file cannot exceed 64K.
  Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 45s
Command ./gradlew failed with exit code 1

more info...

registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

**Comment by EddyVerbruggen** [comment]
Smells like https://github.com/EddyVerbruggen/nativescript-plugin-firebase/tree/56ceba2f2a476f0080cbacae8e7bf5bfa5a381c3#dexindexoverflowexception
