### ISSUE TITLE
Android run issue

### ISSUE THREAD

**Issue by Riddhi135** [EddyVerbruggen/nativescript-plugin-firebase#1355]
Hello,
I am using this plugin and my ios app is working fine but I am having issue with running app in android. I have added google-services.json file inside App_Resource/Android path. Every time I run app in android, I get below error in Setting.gradle file  :

Failed to build plugin nativescript-plugin-firebase : 
Error: Command ./gradlew failed with exit code 1

Project directory '/private/var/lib/workspace/MOBILE-BUILDS/<AppName>/platforms/tempPlugin/nativescript_plugin_firebase' is not part of the build defined by settings file '/private/var/lib/workspace/MOBILE-BUILDS/<AppName>/settings.gradle'. If this is an unrelated build, it must have its own settings file

**Comment by EddyVerbruggen** [comment]
Can you share your repo? This is a bit hard to diagnose otherwise.

**Comment by elimin8r** [comment]
same issue here :(

**Comment by elimin8r** [comment]
actually it was caused by a settings.gradle file in a lower directory. works now :)

**Comment by Riddhi135** [comment]
I have added below files 
1. App_Resources/Android/google-service.json
2. Add firebase plugin and generated firebase.nativescript.json file with below details
{
    "external_push_client_only": false,
    "using_ios": false,
    "using_android": true,
    "firestore": false,
    "realtimedb": false,
    "authentication": false,
    "remote_config": false,
    "performance_monitoring": false,
    "messaging": true,
    "in_app_messaging": true,
    "crashlytics": true,
    "storage": false,
    "functions": true,
    "facebook_auth": false,
    "google_auth": false,
    "admob": false,
    "dynamic_links": false,
    "ml_kit": false
}

**Comment by ibnYusrat** [comment]
I am having the same issue after updating to `nativescript-plugin-firebase@10.0.1`

Before the update it was fine.
