### ISSUE TITLE
Uncomment firebase-messaging in the plugin's include.gradle first

### ISSUE THREAD

**Issue by maxorlovsky** [EddyVerbruggen/nativescript-plugin-firebase#1358]
This issue seems to reappear again, here is the previous one https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/928

Using setTimeout to trigger **messaging.registerForPushNotifications** doesn't really help.

And there are no explanation about include.graddle in the docs https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/MESSAGING.md

**Comment by EddyVerbruggen** [comment]
Can you share a repo I can look at? When configured properly there's no need to manually edit gradle files.

**Comment by maxorlovsky** [comment]
Weirdly enough, it worked when I did the upgrade to version 9.0.4. This bug was appearing for me on 9.0.1. So I guess it's irrelevant, I will close the issue. Thank you @EddyVerbruggen

**Comment by thukuwanjiku** [comment]
@maxorlovsky you upgraded to version 9.0.4 of what? I have this issue using NativescriptVue.
@EddyVerbruggen please see snippets [here](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/928#issuecomment-519221135)

**Comment by EddyVerbruggen** [comment]
@thukuwanjiku I can't work with snippets.

**Comment by thukuwanjiku** [comment]
@EddyVerbruggen [here's](https://github.com/thukuwanjiku/test) my repo

**Comment by EddyVerbruggen** [comment]
@thukuwanjiku You don't even have messaging enabled: https://github.com/thukuwanjiku/test/blob/deed37f6fedb23f1ee23cdf144ce3eb908451f1b/firebase.nativescript.json#L10

**Comment by thukuwanjiku** [comment]
@EddyVerbruggen I've enabled messaging, but same error.

**Comment by EddyVerbruggen** [comment]
Did you remove the node_modules and platforms folder, then did a clean build?

**Comment by thukuwanjiku** [comment]
@EddyVerbruggen thank you very much. The error is fixed, I'm now able to receive a token. I'm most thankful.
