### ISSUE TITLE
`Error: Unsupported type: (null) for value (null)` when calling firebase http function

### ISSUE THREAD

**Issue by caddac** [EddyVerbruggen/nativescript-plugin-firebase#1363]
I've followed the instructions in Functions.MD to enable functions and am calling my http function exactly as in the example (I've tried both Native API and WEB API). However I keep getting the error `file:///node_modules/tns-core-modules/application/application.js:277:26 JS ERROR Error: Unsupported type: (null) for value (null)` when I try to invoke my function. The function does not show any invocation from the firebase console. 

I've tried wrapping the function construction and invocation in a try/catch but the catch never catches the error, the application just quits.

I'm using tns cli `6.0.2` and plugin version `9.0.4`.

Any idea how I can troubleshoot this issue?

**Comment by EddyVerbruggen** [comment]
Not without being able to see and run your project myself..

**Comment by caddac** [comment]
Figured this out, whatever object I'm trying to submit via the function is causing the error.
