### ISSUE TITLE
Android - Face detection infos

### ISSUE THREAD

**Issue by kriefsacha** [EddyVerbruggen/nativescript-plugin-firebase#1366]
Hi,

First , thanks for you help on all your plugins , you are really the best !

I just had a question.

I'm on nativescript android and i tried the face detection of MLKit.

What i need , is to recognize a face from another.

Let's say at the beginning every user save his face on a database.

And then we can know which user is it by seeing his face again and comparing with what we have in database.

I'm asking that because when i tried the face detection i have different datas with the same person.

Do you know if it's possible to do something like that ? 

I tried with the live camera on the app for now. Thank you very much !

**Comment by EddyVerbruggen** [comment]
Hi, you might want to check first if that's possible with the native Android Firebase MLKit SDK. If it is, we could add it to the plugin as well. A good place to start looking is https://firebase.google.com/docs

**Comment by kriefsacha** [comment]
Wow that was a quick answer !

I just sent them a support ticket.

I'll keep you in touch here about their answer.

Thanks for all !

**Comment by kriefsacha** [comment]
@EddyVerbruggen on their docs they talk about face countours : 

![image](https://user-images.githubusercontent.com/35034421/63328791-6f567500-c339-11e9-90ba-09b658901859.png)

Can't we get them and then compare it ? I don't see them in the result

**Comment by EddyVerbruggen** [comment]
I know, but would that be of any help for your use case?

**Comment by kriefsacha** [comment]
We may try something yes , try to check if there is a face that have approximetly the same countours points in the database.

**Comment by kriefsacha** [comment]
Sorry i didn't write here news for a long time.

Firebase sended us mails , telling that for now what we want to do is not possible .. maybe in the future.

But thanks for you help !
