### ISSUE TITLE
new iOS error on google auth - presenting view controller must be set

### ISSUE THREAD

**Issue by edmundpf** [EddyVerbruggen/nativescript-plugin-firebase#1370]
Google Auth was previously working on iOS but now I am receiving this error with no changes to codebase: "presenting view controller must be set"

**Comment by EddyVerbruggen** [comment]
Please share your repo.

**Comment by edmundpf** [comment]
> Please share your repo.

I'm using this for a private project that I'm not allowed to share but I will include anything relevant to the plugin, please let me know if I'm missing anything. Thank you for the help!

* google-services.json in app/App_Resources/Android/
* GoogleService-Info.plist in app/App_Resources/iOS/
* firebase.nativescript.json
``` json
{
    "external_push_client_only": false,
    "using_ios": true,
    "using_android": true,
    "firestore": true,
    "realtimedb": false,
    "authentication": true,
    "remote_config": false,
    "performance_monitoring": false,
    "messaging": false,
    "in_app_messaging": false,
    "crashlytics": false,
    "crash_reporting": false,
    "storage": false,
    "functions": false,
    "facebook_auth": true,
    "google_auth": true,
    "admob": false,
    "invites": false,
    "dynamic_links": false,
    "ml_kit": false
}
```
* package.json dependencies (nativescript-plugin-firebase v8.3.2)
``` json
  "dependencies": {
    "lodash": "^4.17.11",
    "nativescript-bluetooth": "^2.0.0-beta.23",
    "nativescript-iqkeyboardmanager": "^1.5.1",
    "nativescript-plugin-firebase": "^8.3.2",
    "nativescript-toasty": "^1.3.0",
    "nativescript-vue": "^2.0.0",
    "nativescript-vuex-persistent": "^1.2.0",
    "tns-core-modules": "^5.0.2",
    "vuex": "^3.0.1"
  },
```
* Google login method
``` javascript
	async loginGoogle() {
		return await firebase
		.login({
			type: firebase.LoginType.GOOGLE
		})
	},
```
* Google login call where error originates (called on button click)
``` javascript
const res = await userFunctions.loginGoogle()
```

**Comment by EddyVerbruggen** [comment]
The relevant bit is the page structure (because it seems like the code can't resolve the page controller) so I really need an app I can run to reproduce it. Of course I don't want your actual project, just a very simple app that shows the issue.

**Comment by edmundpf** [comment]
> The relevant bit is the page structure (because it seems like the code can't resolve the page controller) so I really need an app I can run to reproduce it. Of course I don't want your actual project, just a very simple app that shows the issue.

Gotcha, thanks again for the help!
* Auth Page
``` vue
<template>
	<Page class="page" actionBarHidden="true">
		<FlexboxLayout flexDirection="column">
			<mainLogo/>
			<StackLayout class="form">
				<TextField
					hint="Email..."
					v-model="emailText"
					class="input input-rounded input-font m-t-10"
					v-bind:class="{ danger: emailDanger, success: emailSuccess }"
				/>
				<TextField
					hint="Password..."
					v-model="passText"
					class="input input-rounded input-font m-t-25 m-b-25"
					secure="true"
					v-bind:class="{ danger: passDanger, success: passSuccess }"
				/>
				<Button
					class="btn btn-primary btn-ruby btn-rounded-sm"
					text="Login"
					:isEnabled="loginEnabled"
					@tap="loginEvent"
				/>
				<Button
					class="btn btn-primary btn-purple btn-rounded-sm m-y-25"
					text="Signup"
					@tap="signupPageNav"
				/>
				<Label
					class="text-center m-x-5 m-t-10 t-18"
					v-bind:class="{ 'text-danger': feedbackDanger }"
					:text="feedbackText"
					textWrap="true"
				/>
				<StackLayout orientation="horizontal">
					<Button
						class="btn btn-primary btn-error btn-circle-half btn-left fab"
						:text="googleIcon"
						width="25%"
						@tap="googleLogin"
					/>
					<Button
						class="btn btn-primary btn-blue btn-circle-half btn-right fab"
						:text="facebookIcon"
						width="25%"
						@tap="facebookLogin"
					/>
				</StackLayout>
			</StackLayout>
		</FlexboxLayout>
	</Page>
</template>

<script>

import userMixin from '~/mixins/userMixin'
import iconMixin from '~/mixins/iconMixin'
import fireStore from '~/mixins/fireStore'
import mainLogo from '~/components/mainLogo'
import signupPage from '~/pages/signupPage'
import { slideNav, noTransNav, jsonLog } from '~/utils/miscFunctions'
import { userFunctions } from '~/utils/fire'

export default {
	mixins: [
		userMixin,
		iconMixin,
		fireStore,
	],
	data() {
		return {
			loginEnabled: true,
		}
	},
	components: {
		mainLogo,
	},
	methods: {
		signupPageNav() {
			slideNav(this,
					signupPage,
					{ email: this.emailText,
						password: this.passText,
						signin_method: 'email' })
		},
		async loginEvent() {
			try {
				const res = await userFunctions.login({
					email: this.emailText,
					password: this.passText,
				})
				console.log(res)
				var getRes
				try {
					getRes = await this.getData(res.uid)
				}
				catch (error) {
					console.log(error)
					getRes = {}
				}
				const dataRes = this.$store.dispatch('setData', {
					...getRes,
					uid: res.uid,
					logged_in: true,
					signin_method: 'email',
				})
				this.feedbackText = ''
				this.feedbackDanger = false
			}
			catch (error) {
				console.log(error)
				this.feedbackDanger = true
				this.feedbackText = 'Could not login. Please try again.'
			}
		},
		async googleLogin() {
			try {
				const res = await userFunctions.loginGoogle()
				console.log(res)
				var getRes
				try {
					getRes = await this.getData(res.uid)
				}
				catch (error) {
					console.log(error)
					getRes = {}
				}
				if (getRes.logged_in != null) {
					const dataRes = this.$store.dispatch('setData', {
						...getRes,
						uid: res.uid,
						logged_in: true,
						signin_method: 'google',
					})
					this.feedbackText = ''
					this.feedbackDanger = false
				}
				else {
					this.$store.dispatch('setState', {
						uid: res.uid
					})
					slideNav(this,
							signupPage,
							{
								email: res.email,
							 	signin_method: 'google',
							})
				}
			}
			catch (error) {
				console.log(error)
			}
		},
		async facebookLogin() {
			try {
				const res = await userFunctions.loginFacebook()
				console.log(res)
				var getRes
				try {
					getRes = await this.getData(res.uid)
				}
				catch (error) {
					console.log(error)
					getRes = {}
				}
				console.log(getRes)
				if (getRes.logged_in != null) {
					const dataRes = this.$store.dispatch('setData', {
						...getRes,
						uid: res.uid,
						logged_in: true,
						signin_method: 'facebook',
					})
					this.feedbackText = ''
					this.feedbackDanger = false
				}
				else {
					this.$store.dispatch('setState', {
						uid: res.uid
					})
					slideNav(this,
							signupPage,
							{
								email: res.email,
							 	signin_method: 'facebook',
							})
				}
			}
			catch (error) {
				console.log(error)
			}
		},
	}
}

</script>
```

**Comment by brownkevg** [comment]
I could be barking up the wrong tree but GoogleSignIn just updated their pod file recently from 4.4.0 to 5.0.0... on the 14th this month. One of the things that was changed was replacing uiDelegate with presentingViewController (https://developers.google.com/identity/sign-in/ios/release).

**Comment by edmundpf** [comment]
> I could be barking up the wrong tree but GoogleSignIn just updated their pod file recently from 4.4.0 to 5.0.0... on the 14th this month. One of the things that was changed was replacing uiDelegate with presentingViewController (https://developers.google.com/identity/sign-in/ios/release).

That would make sense

**Comment by edmundpf** [comment]
@EddyVerbruggen @brownkevg after further testing all login/signup functionality only on iOS was recently broken for me at least on 9.0.2 but the update to 9.1.0 fixed all of it, I'll go ahead and close this

**Comment by Root-vb** [comment]
> Google Auth was previously working on iOS but now I am receiving this error with no changes to codebase: "presenting view controller must be set" 
@edmundpf instead of this `GIDSignIn.sharedInstance()?.uidelegate = self` 
try this `GIDSignIn.sharedInstance()?.presentingViewController = self`

**Comment by MajidBashir** [comment]
> > Google Auth was previously working on iOS but now I am receiving this error with no changes to codebase: "presenting view controller must be set"
> 
> @edmundpf instead of this `GIDSignIn.sharedInstance()?.uidelegate = self`
> try this `GIDSignIn.sharedInstance()?.presentingViewController = self`

actually you  should use both, in order to perform this action

**Comment by Vikrant-art** [comment]
Yes use both GIDSignIn.sharedInstance()?.uidelegate = self and  GIDSignIn.sharedInstance()?.presentingViewController = self
in order to resolve this issue.

**Comment by EddyVerbruggen** [comment]
@Vikrant-art is there some code I need to integrate into the plugin? Can you perhaps do a PR even? Cheers!

**Comment by Vikrant-art** [comment]
> Can you perhaps do a PR even? Cheers!

First you need to update your pods for GoogleSignIn (5.0.0) and then just add below attached code 


import Foundation
import GoogleSignIn

// Gmail Constants
struct GoogleConstant {
    static let clientID = “Your_Client_ID”
    static let UrlScheme : String! = “Your_URL_Scheme”
}
extension LoginController {
    // This Method will select Social Login Type
    func googleLogin() {
        Application.Method.showLoader(loadingText: "")
       // GIDSignIn.sharedInstance().uiDelegate = self// Deprecated
        
        var configureError  : NSError?
        ///initialize google signin context
        ///Passed address of error over here
        
        if(configureError != nil) {
            return
        }
        assert(configureError == nil, "\(String(describing: configureError))")
        GIDSignIn.sharedInstance().delegate = self
        //GIDSignIn.sharedInstance().uiDelegate = self // Depricated
        GIDSignIn.sharedInstance()?.presentingViewController = self
        GIDSignIn.sharedInstance().signIn()
    }
    
    func googleLogout() {
        //Google logout functionality
        GIDSignIn.sharedInstance().signOut()
    }
}

**Comment by vinod1988** [comment]
> > > Google Auth was previously working on iOS but now I am receiving this error with no changes to codebase: "presenting view controller must be set"
> > 
> > 
> > @edmundpf instead of this `GIDSignIn.sharedInstance()?.uidelegate = self`
> > try this `GIDSignIn.sharedInstance()?.presentingViewController = self`
> 
> actually you should use both, in order to perform this action

Thank you so much. Its worked

**Comment by rajni1721** [comment]
That's work for me... Hurrayyyyyy

**Comment by EddyVerbruggen** [comment]
@rajni1721 Can you please share what you’ve changed exactly, because I’m not entirely clear if there’s something I can change in the plugin.

**Comment by aamirarslann** [comment]
> > > Google Auth was previously working on iOS but now I am receiving this error with no changes to codebase: "presenting view controller must be set"
> > 
> > 
> > @edmundpf instead of this `GIDSignIn.sharedInstance()?.uidelegate = self`
> > try this `GIDSignIn.sharedInstance()?.presentingViewController = self`
> 
> actually you should use both, in order to perform this action

thanks. its worked
