### ISSUE TITLE
[ios][messaging] onMessaggeReceived callback not triggered when showNotificationsWhenInForeground is true

### ISSUE THREAD

**Issue by PeterStaev** [EddyVerbruggen/nativescript-plugin-firebase#1371]
On iOS if I set `showNotificationsWhenInForeground` to `true` the `onMessagReceivedCallback` is not triggered when my app is in the foreground. Is it supposed to work like this? Can we make it so that the callback is also trigerred?

**Comment by PeterStaev** [comment]
I think this is related to this code:
https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/e2da843dd4031af0ee145b1c199ed520f9d650e3/src/messaging/messaging.ios.ts#L536-L548
I think this is a wrong logic as there can be cases (like in my app right now) where you need to also process the callback AND show a notification when app is foreground. Considering under android the callback is always called. 
@EddyVerbruggen  can we at least have a config option that allows processing the callback in this case?

**Comment by EddyVerbruggen** [comment]
I guess that makes sense, and you can always still use the `foreground` property to decide what to do when a notification is received.. so I'v now moved that callback invocation out of the condition:

https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/56ceba2f2a476f0080cbacae8e7bf5bfa5a381c3/src/messaging/messaging.ios.ts#L532-L547

**Comment by ditoglez** [comment]
@ycherniavskyi did you came up with a solution for this? I am experiencing the same issue in my app.

**Comment by ycherniavskyi** [comment]
@ditoglez yes I came up, but with the really dirty solution, so don't tell anyone who shown it to you 🤣:
```ts
onMessageReceivedCallback: (message: firebase.Message) => {
    // ...
    if (message.foreground) {
        if (isIOS) { // HACK: to skip processing the notification which received in foreground check stack trace 
                     // (this processing appear after resolving the issue https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/1371),
                     // the notification will remain in notification center because of `showNotificationsWhenInForeground` flag
                     // and will be processed on click on it
            const stack = new Error().stack;
            if (stack.includes("userNotificationCenterWillPresentNotificationWithCompletionHandler")) {
                console.log("onMessageReceivedCallback skipped")
                return;
            }
        }
        // ...
    }
    // ...
    processPushMessageHelper(message);
}
```

**Comment by EddyVerbruggen** [comment]
I've now (v 10.1.0) added the `notificationTapped` boolean to the notification payload on iOS. That may @ycherniavskyi to clean up that hacky (but cool!) logic.

**Comment by ycherniavskyi** [comment]
@EddyVerbruggen thank you for the added flag, I replaced my hack with it and everything works as expected!
