### ISSUE TITLE
Can't find variable: FIRVisionObjectDetectorOptions

### ISSUE THREAD

**Issue by adfdev** [EddyVerbruggen/nativescript-plugin-firebase#1372]
When start live camera feed for MLKitObjectDetection have this error and crash:

Platform is IOS

`Can't find variable: FIRVisionObjectDetectorOptions
getDetector@file:///node_modules/nativescript-plugin-firebase/mlkit/objectdetection/index.js:44:
`

**Comment by EddyVerbruggen** [comment]
Assuming you ran “pod repo update” and added “object recognition” to the config (see docs on mlkit) you should get around this by cleaning the platforms and node_modules folders.

**Comment by adfdev** [comment]
solved thanks
