### ISSUE TITLE
Wrong orientation on object detection

### ISSUE THREAD

**Issue by adfdev** [EddyVerbruggen/nativescript-plugin-firebase#1376]
In object detection when get results bounds are wrong in both case: live camera feed and in process image manually. Seem bounds data for example width and height are reversed. I have notice this because when i tried to crop, the cropped image is not respect than detected.

I'm working on IOS platform i don't know if this issue there is on also Android

**Comment by EddyVerbruggen** [comment]
@adfdev Interestingly those properties are reversed on purpose on iOS, because I had to do that for barcodescanning in the past. Can you please check if barcodescanning reports the correct bounds for you?

Also, what device are you testing with?

**Comment by adfdev** [comment]
Yes have a same problem on barcode scan. Have noticed on barcode scan the last vision image is rotated on 90 degrees.
On object detection have commented this part of code:

```javascript
function getMLKitObjectDetectionResultItem(obj, image) {
    console.log(">> getMLKitObjectDetectionResultItem, image: " + image);
    var imageWidth;
    var imageHeight;
    var _a = obj.frame.origin, x = _a.x, y = _a.y;
    var _b = obj.frame.size, width = _b.width, height = _b.height;
    // if (image) {
    //     imageWidth = image.size.width;
    //     imageHeight = image.size.height;
    //     var origX = x;
    //     var origWidth = width;
    //     var origImageWidth = imageWidth;
    //     if (utils_1.ios.isLandscape()) {
    //         if (UIDevice.currentDevice.orientation === 4) {
    //             x = image.size.width - (width + x);
    //             y = image.size.height - (height + y);
    //         }
    //     }
    //     else {
    //         x = image.size.height - (height + y);
    //         y = origX;
    //         width = height;
    //         height = origWidth;
    //         imageWidth = imageHeight;
    //         imageHeight = origImageWidth;
    //     }
    // }
    return {
        id: obj.trackingID,
        category: objectdetection_common_1.ObjectDetectionCategory[obj.classificationCategory],
        confidence: obj.confidence,
        ios: obj,
        bounds: {
            origin: {
                x: x,
                y: y
            },
            size: {
                width: width,
                height: height
            }
        },
        image: {
            width: imageWidth,
            height: imageHeight
        }
    };
}
```

and now seem work done!

**Comment by EddyVerbruggen** [comment]
Hmm, perhaps this orientation thing has been fixed in a recent release of the Firebase iOS MLKit SDK. Thanks for sharing your findings!

**Comment by EddyVerbruggen** [comment]
@adfdev I need to have one thing cleared up: do you see the same problem on both still images and the feed, and on both barcode scanning and object detection?

I ask, because I'm testing with an iPhone X as well and I only see the problem with object detection on still images.

**Comment by adfdev** [comment]
Have on both! Sincerely the big problem for is when i want crop last vision image from object detection live feed, bounds results wrong.

**Comment by EddyVerbruggen** [comment]
OK so is the reported bounds correct for the live view, but incorrect for the cropped image? I'm not sure what to do here because different people report different things so this needs to be crystal clear before I can change anything..

**Comment by adfdev** [comment]
The problem is (in live feed):
If you show in Image layout lastVisionImage, this is have correct orientation;
If you try to crop width detected bounds the result image will have orientation to 90 anti-clockwise 
. But otherwise the bound it's wrong.
