### ISSUE TITLE
Internal error using sendPasswordResetEmail

### ISSUE THREAD

**Issue by mantonelli** [EddyVerbruggen/nativescript-plugin-firebase#1377]
I've updated an app to {N} 6.0.3 and version 9.0.4 of this plugin.

When I request a reset password e-mail, the app is throwing the error "An internal error has occurred, print and inspect the error details for more information.".

I've changed the file firebase-io.js, at line 926, to see more info about this error:

``` javascript
firebase_common_1.firebase.sendPasswordResetEmail = function (email) {
    return new Promise(function (resolve, reject) {
        try {
            var onCompletion = function (error) {
                if (error) {
                    //line 926 >> console.dir(error);
                    reject(error.localizedDescription);
                }
                else {
                    resolve();
                }
            };
            FIRAuth.auth().sendPasswordResetWithEmailCompletion(email, onCompletion);
        }
        catch (ex) {
            console.log("Error in firebase.sendPasswordResetEmail: " + ex);
            reject(ex);
        }
    });
};
```

The result was:

NSLocalizedDescription = "An internal error has occurred, print and inspect the error details for more information.";
NSUnderlyingError = "Error Domain=FIRAuthInternalErrorDomain Code=3 \"(null)\" UserInfo={FIRAuthErrorUserInfoDeserializedResponseKey={\n    code = 400;\n    errors =     (\n                {\n            domain = global;\n            message = \"Request contains an invalid argument.\";\n            reason = badRequest;\n        }\n    );\n    message = \"Request contains an invalid argument.\";\n    status = \"INVALID_ARGUMEN<…>

At Firebase Console I didn't find any configuration to change. I only use email/password authentication method, which is working normally.

I've tried to update the plugin to version 9.1.0, but I had the same problem reported on issue #1375.

**Comment by EddyVerbruggen** [comment]
Interesting. I just reset my password on iOS and it all worked fine.

The errormessage "Request contains an invalid argument" indicates to me there's an issue with the emailaddress you're passing in, but you may want to Google that.
