### ISSUE TITLE
Validation for analytics event key seems incorrect

### ISSUE THREAD

**Issue by s-ovation** [EddyVerbruggen/nativescript-plugin-firebase#1378]
According to the comment in analytics-common.ts and also official document: https://firebase.google.com/docs/reference/cpp/group/parameter-names, alphanumeric characters are allowed in param names. 

However, the regexp used in the following line does not accept 'numeric' character.

https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/6a2e0a9f1aeb26f6e568c3e68bd960069f4fe150/src/analytics/analytics-common.ts#L12

So, a param name like 'group1' is rejected by the logic.

**Comment by EddyVerbruggen** [comment]
Damn, you're right. Let me fix that. Thanks for reporting it!
