### ISSUE TITLE
UIWebView usage and ITMS-90809: Deprecated API Usage

### ISSUE THREAD

**Issue by nickykln** [EddyVerbruggen/nativescript-plugin-firebase#1380]
Hello Sir @EddyVerbruggen 

As you may know there is a deprecation warning sent from today related to the usage of UIWebView

I have read that firebase still contains references to this deprecated library. 

https://github.com/firebase/firebase-ios-sdk/issues/3722

This issue concerns Dynamics Links but I am not using this component, that is why I am not sure that is the root cause of this warning that will be a blocking issue for AppStore submissions soon :( 
 
` "dynamic_links": false, in ny firebase.nativescript.json`

If you have time to have a look ? If anyone has the same issue ?

Thanks a lot,

N

**Comment by EddyVerbruggen** [comment]
We'll have to wait for Google to publish a new version of their SDK first. Thx for the heads-up!

**Comment by EddyVerbruggen** [comment]
Almost there, see https://github.com/firebase/firebase-ios-sdk/pull/3723#issuecomment-527183143

**Comment by NathanWalker** [comment]
Looks like they published `6.8.0` now. Curious if any code changes needed you think @EddyVerbruggen or can we just bump cocoapod versions?

**Comment by EddyVerbruggen** [comment]
@NathanWalker Usually they break things which you may or may not notice based on the features you (don't) use.

I always wait for them to be happy with the release and post the release notes here: https://firebase.google.com/support/release-notes/ios

**Comment by EddyVerbruggen** [comment]
The build issues I mentioned are related to MLKit and tns-ios, but the team has solved it in 6.1.0, so if you're running tns-ios 6.1.0+ and Firebase plugin 9.2.0 you will be good.

**Comment by NathanWalker** [comment]
@EddyVerbruggen not you intended to close this? after `pod repo update` the following firebase cocoapods are used with latest published 9.1.1 (published 20 days ago https://www.npmjs.com/package/nativescript-plugin-firebase):
```
Installing Firebase (6.6.0)
Installing FirebaseAnalytics (6.1.0)
Installing FirebaseAnalyticsInterop (1.4.0)
Installing FirebaseAuth (6.2.3)
Installing FirebaseAuthInterop (1.0.0)
Installing FirebaseCore (6.2.0)
Installing FirebaseCoreDiagnostics (1.0.1)
Installing FirebaseCoreDiagnosticsInterop (1.0.0)
Installing FirebaseInstanceID (4.2.5)
Installing FirebaseMessaging (4.1.4)
```
The deprecation fix I believe comes from `6.8.0` of cocoapods which are not pulled even after `pod repo update` and 9.1.1 of this plugin. I noticed a `10.0.0` prepped but in this changeset https://github.com/EddyVerbruggen/nativescript-plugin-firebase/commit/a13e6520e6ca2ec051b85fca92b59d60916bce82 I don't see anything that would pull the 6.8.0 latest. Am I missing something?

**Comment by EddyVerbruggen** [comment]
10.0.0 is out. Hope that helps.

**Comment by narusevic** [comment]
@EddyVerbruggen Just released with latest version 10.0.0 'Firebase/Core', '~> 6.6.0'. Got same warning

**Comment by nitrotm** [comment]
I still get that message from Apple even after upgrading to 10.0.0. I have cross-checked by removing all other dependencies. Everything pass except if I add nativescript-pluging-firebase to the project.

Here's my `firebase.nativescript.json`:

```
{
    "external_push_client_only": false,
    "using_ios": true,
    "using_android": true,
    "firestore": false,
    "realtimedb": false,
    "authentication": false,
    "remote_config": false,
    "performance_monitoring": false,
    "messaging": true,
    "in_app_messaging": false,
    "crashlytics": false,
    "crash_reporting": false,
    "storage": false,
    "functions": false,
    "facebook_auth": false,
    "google_auth": false,
    "admob": false,
    "invites": false,
    "dynamic_links": false,
    "ml_kit": true,
    "ml_kit_text_recognition": false,
    "ml_kit_barcode_scanning": true,
    "ml_kit_face_detection": false,
    "ml_kit_image_labeling": false,
    "ml_kit_custom_model": false,
    "ml_kit_natural_language_identification": false,
    "ml_kit_natural_language_smartreply": false
}
```

**Comment by cuijinfeng68** [comment]
> https://firebase.google.com/support/release-notes/ios#dynamic-links
> 
> It was already updated...

how to update it? pod repo update? After I update ,but it does not work.
