### ISSUE TITLE
Programmatically set camera off or on

### ISSUE THREAD

**Issue by cherimo** [EddyVerbruggen/nativescript-plugin-firebase#1383]
Hey there,

Thank you for your awesome plugin, it works great.
I use the MLKitBarcodeScanner to scan barcodes etc.. on Angular.
What i am looking for is how to programmatically set camera off or on. 
At this moment I use visibility collapsed or visible. 
But when I put it to visible again the Camera doesn't show, which is obvious. 

Can I set the camera programmatically on again as soon as its visible?

Thank you in advance.

**Comment by EddyVerbruggen** [comment]
Perhaps the `pause` feature is what you're after?

https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/6fe086271d8d421da43504f9587a0cf09e7faeb1/demo-ng/app/tabs/mlkit/barcodescanning/barcodescanning.component.html#L15

**Comment by cherimo** [comment]
@EddyVerbruggen thx for your fast reply, its almost the same.
To give you an example, I have the following HTML(Angular):

 ```
       <AbsoluteLayout id="scan" visibility="collapsed" row="1">
                    <MLKitBarcodeScanner
                    width="100%"
                    height="300"
                    formats="QR_CODE"
                    beepOnScan="false"
                    [torchOn]="torchOn"
                    [pause]="pause"
                    supportInverseBarcodes="false"
                    android:processEveryNthFrame="5"
                    ios:processEveryNthFrame="10"
                    (scanResult)="onBarcodeScanResult($event)">
                </MLKitBarcodeScanner>
        </AbsoluteLayout>
```
When I tap a button to make id 'scan' visibility visible again, it shows the <AbsoluteLayout> as it should be but no Camera Screen(<MLKitBarcodeScanner>) visible. 
How can i make Camera Screen programmatically visible again after I tap the visibility button?

I hope that i am not confusing :)

**Comment by EddyVerbruggen** [comment]
Dunno from the top of my head. You'll have to try a few things yourself I guess.

**Comment by cherimo** [comment]
Thx, I found a workaround. Closing the issue.

**Comment by EinatGit** [comment]
@cherimo  what is the workaround you found ? I need it please
