### ISSUE TITLE
How to query by bach Keys?

### ISSUE THREAD

**Issue by IvRRimum** [EddyVerbruggen/nativescript-plugin-firebase#139]
I have a dictionary of Keys i wish to receive from firebase.

How would one do that?

**Comment by IvRRimum** [comment]
Documentation, doesn't specify how to use range's, for KEY's

**Comment by EddyVerbruggen** [comment]
Do you have an example of your data structure? Screenshot perhaps.

**Comment by IvRRimum** [comment]
It justs regular ids:

firebase:
  photoId : {...},
  photoId: {...},
  photoId: {...}

photoId - The firebase generated ID's.

How can one acheave that?

**Comment by IvRRimum** [comment]
Still relevant guys? Can creator respond?

**Comment by EddyVerbruggen** [comment]
Hi, creator here.

I previously asked for a screenshot of the data in your Firebase instance you want to retrieve. I asked because I need a way to replicate your data structure, otherwise I can't find a way to help you.

Also, if this is more of a Firebase question in general you may have more success on StackOverflow..

**Comment by IvRRimum** [comment]
This is more of the plugin, becouse, as i have read, you can do it with firebase.js

Here's the pic: http://prnt.sc/cnhhzl

**Comment by IvRRimum** [comment]
I got a array of Phot Keys.

For example: ["-KPn4p7spS8NO7IVSLdF", "-KSDRx5BN54JHitoq7Wb"];

**Comment by EddyVerbruggen** [comment]
Thanks. So as a result you want those keys? What would the firebase.js syntax be in this case? That may help me figuring this out as well..

**Comment by IvRRimum** [comment]
http://stackoverflow.com/questions/38192711/how-to-retrieve-multiple-keys-in-firebase

I am using this appraoch. But it retreaves the last data, 4 times( i have 4 photos and 4 keys ).

Here's the code:

```
144   private fetchFirebaseRef(esContent, photoService) {
145     Object.keys(esContent).forEach(function(data, index, array) {
146       photoService.getPhoto(esContent[data]["photo_id"]);
147     });
148   }
```

```
203   public getPhoto(photoId) {
204     console.log(photoId);
205     firebase.query(
206         this.onQueryEvent.bind(this),
207         "/photos",
208         {
209             singleEvent: false,
210 
211             orderBy: {
212                 type: firebase.QueryOrderByType.KEY,
213                 value: ''+photoId+''
214             },
215 
216             limit: {
217                 type: firebase.QueryLimitType.LAST,
218                 value: 1
219             }
220         }
221     );
222   }
``` 

Hope, this clears things up.

**Comment by IvRRimum** [comment]
By last photo 4 times i meant.

When i click search. It shows The last photo from firebase, 4 times in my UI.

**Comment by EddyVerbruggen** [comment]
So with that query you want to retrieve the object at (for instance) `-KPn4p7spS8NO7IVSLdF`? If so, then change `singleEvent` to true and the promise should contain your data:

```js
203   public getPhoto(photoId) {
204     console.log(photoId);
205     firebase.query(
207         "/photos",
208         {
209             singleEvent: true,
210 
211             orderBy: {
212                 type: firebase.QueryOrderByType.KEY,
213                 value: ''+photoId+''
214             },
215 
216             limit: {
217                 type: firebase.QueryLimitType.LAST,
218                 value: 1
219             }
220         }
221     ).then(function(data) {console.log(data)});
222   }
```

Not sure if it's possible, but instead of this can't you do it like this:?

```js
203   public getPhoto(photoId) {
204     console.log(photoId);
205     firebase.query(
206         "/photos/"+photoId,
207         {
208             singleEvent: true,
209         }
210     ).then(function(data) {console.log(data)});
211   }
```

**Comment by IvRRimum** [comment]
Will try that first thing tomorrow.

Thanks a lot!

**Comment by IvRRimum** [comment]
```
this.onQueryEvent.bind(this)
```
When i remove this, then i get 
```
error TS2346: Supplied parameters do not match any signature of call target.
```

That's the firebase line.

I call it like that:
```
205     firebase.query(
206         "/photos"+photoId,
207         {
208             singleEvent: true,
209         }   
210     ).then((data) => { console.log(data); });
```

**Comment by IvRRimum** [comment]
This functionality is not possible with this plugin i think...

**Comment by IvRRimum** [comment]
It is possible trough heavy monkey paches.

Using callbacks to call next firebase event.

**Comment by IvRRimum** [comment]
Even that doesn't work.

**Comment by IvRRimum** [comment]
```
210   public getPhotoFromBack(coordinate) {
211     console.log(this.bachKeys[coordinate]);
212     firebase.query(
213         function() {},
214         "/photos",
215         {   
216             singleEvent: true,
217             
218             orderBy: {
219                 type: firebase.QueryOrderByType.KEY,
220                 value: ''+this.bachKeys[coordinate]+""
221             },
222             
223             limit: {
224                 type: firebase.QueryLimitType.LAST,
225                 value: 1
226             }
227         }
228     ).then((data) => {
229       console.dir(data);
230       if(this.bachKeys.length-1 >= coordinate) {
231         console.log("HELLO");
232         this.getPhotoFromBack(coordinate+1);
233       } 
234     });
235   }
```

This doesnt work.

**Comment by IvRRimum** [comment]
Progress:
```
  limit: {
224                 type: firebase.QueryLimitType.LAST,
225                 value: 1
226             }
```

To .FIRST now only shows first of the firebase(3 times).

**Comment by IvRRimum** [comment]
Got it working:
```
205     firebase.query(
206         this.onQueryEvent.bind(this),
207         "/photos/"+photoId,
208         {
209             singleEvent: true,
210 
211             orderBy: {
212                 type: firebase.QueryOrderByType.KEY,
213             }
214         }   
215     );  
```

This also solves the key problem.

Closing.

**Comment by EddyVerbruggen** [comment]
WOW! Would that be something for the readme do you reckon?

**Comment by IvRRimum** [comment]
I think the Limit, with combination with the path, was the problem.

I will try to make a PR in a minute( for the documentation ).

**Comment by IvRRimum** [comment]
But i need access for that right? Can you give?
