### ISSUE TITLE
firebase mlkit object detection in nativescript vue

### ISSUE THREAD

**Issue by Rabi8961** [EddyVerbruggen/nativescript-plugin-firebase#1393]
firebase.mlkit.objectdetection.detectObjects({
  image: imageSource,
  classify: true, 
  multiple: true 
}).then((result) => console.log(JSON.stringify(result.objects)))
.catch(errorMessage => console.log("ML Kit error: " + errorMessage));

i am using above code in my nativescript vue project.
I can access other features like text recognition, image labelling, face detection very well. but, i am not able to use the object detection features. it's giving error "Cannot load object detector module.".

is there any solution about this????

**Comment by EddyVerbruggen** [comment]
Can you share that project? Or even better: did you try demo-ng on your device?

**Comment by EddyVerbruggen** [comment]
Can you share that project? Or even better: did you try demo-ng on your device?

**Comment by Rabi8961** [comment]
Actually i am using it in nativescript vue. and i had used your demo-vue project. but, there you haven't mentioned any object detection .
so, i followed your tutorial and i am able to access all other services of mlkit like text recognition, face detection, image labelling but in object detection it throwing error. 
"Cannot load object detector module."   this is the error message.
which kind of module it looking for..??
Do you have any idea??

**Comment by EddyVerbruggen** [comment]
That's why I asked you to try demo-ng as it has a demo for object detection. Please test that first.
