### ISSUE TITLE
firebase-messaging in the plugin's include.gradle first

### ISSUE THREAD

**Issue by cherimo** [EddyVerbruggen/nativescript-plugin-firebase#1395]
Hey guys,

I came across many of this same issue but didnt find a way to reslove this issue.
I am using the External push notification with a combination of ML Kit Barcode scanner.
The version of Nativescript and Firebase plugin are the most recent with Angular.

On the iOs everything works fine but the android on the other hand not so much.

I am getting this error every time:
```
Unhandled Promise rejection: Uncomment firebase-messaging in the plugin's include.gradle first ; Zone: <root> ; Task: Promise.then ; Value: Uncomment firebase-messaging in the plugin's include.gradle first undefined
```

From the previous issues this should have been resolved and a clean platform & node_modules should do the fix. Unfortunately not my case. I dont know if this has to do with the fact that i am also using the MLkit barcodescanner.

This is my main.ts

```
import { platformNativeScriptDynamic } from "nativescript-angular/platform";
import { AppModule } from "./app/app.module";
import { enableProdMode } from '@angular/core';

require("nativescript-plugin-firebase");

enableProdMode();
platformNativeScriptDynamic().bootstrapModule(AppModule);
```

This is my dashboard.component.ts
```
...
import { Observable } from "tns-core-modules/data/observable";
import { messaging, Message } from "nativescript-plugin-firebase/messaging";
import { alert, confirm } from "tns-core-modules/ui/dialogs";
import * as platform from "tns-core-modules/platform";
import * as applicationSettings from "tns-core-modules/application-settings";

messaging.registerForPushNotifications({
    onPushTokenReceivedCallback: (token: string): void => {
      console.log("Firebase plugin received a push token: " + token);
    },
  
    onMessageReceivedCallback: () => {
      console.log("Push message received");
    },
  
    showNotifications: true,
    showNotificationsWhenInForeground: true
}).then(() => console.log("Registered for push"));

...
```

If I am correctly this should do the trick?
(I have followed also these steps: https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/NON_FIREBASE_MESSAGING.md )
is there something that i am missing?

Thank you guys in advance.

**Comment by cherimo** [comment]
I created another Angular project and this time I used only External Push notification without the MLkit Barcode scanner and everything works fine. Android and iOs both works.

As soon as I created another new project with Angular + External Push notification + Mlkit barcode scanner I get the following error:
`JS: Unhandled Promise rejection: Uncomment firebase-messaging in the plugin's include.gradle first ; Zone: <root> ; Task: Promise.then ; Value: Uncomment firebase-messaging in the plugin's include.gradle first undefined`

Is there a workaround for this?

**Comment by EddyVerbruggen** [comment]
@cherimo It may depend a little on how you use it - can you share that problematic repo with me?

**Comment by cherimo** [comment]
@EddyVerbruggen but of course:
https://github.com/cherimo/pushApp

**Comment by EddyVerbruggen** [comment]
Thx, closing here.. continuing @ https://github.com/cherimo/pushApp/issues/1

**Comment by cobreen** [comment]
firebase.nativescript.json

messaging set to true

Hope it will help someone
