### ISSUE TITLE
Run app tempPlugin folder issue

### ISSUE THREAD

**Issue by Riddhi135** [EddyVerbruggen/nativescript-plugin-firebase#1396]
I am using this plugin and my ios app is working fine but I am having issue with running app in android. I have added google-services.json file inside App_Resource/Android path. Every time I run app in android, I get below error in Setting.gradle file :

Failed to build plugin nativescript-plugin-firebase :
Error: Command ./gradlew failed with exit code 1

Project directory '/private/var/lib/workspace/MOBILE-BUILDS//platforms/tempPlugin/nativescript_plugin_firebase' is not part of the build defined by settings file '/private/var/lib/workspace/MOBILE-BUILDS//settings.gradle'. If this is an unrelated build, it must have its own settings file

I have added below files

1. App_Resources/Android/google-service.json
2. Add firebase plugin and generated firebase.nativescript.json file with below details
{
    "external_push_client_only": false,
    "using_ios": true,
    "using_android": true,
    "firestore": false,
    "realtimedb": false,
    "authentication": true,
    "remote_config": false,
    "performance_monitoring": false,
    "messaging": false,
    "in_app_messaging": false,
    "crashlytics": true,
    "storage": false,
    "functions": false,
    "facebook_auth": false,
    "google_auth": false,
    "admob": false,
    "dynamic_links": false,
    "ml_kit": false
}

Please help me with this issue as I am having serious problem with my app.

**Comment by marotes** [comment]
> I am using this plugin and my ios app is working fine but I am having issue with running app in android. I have added google-services.json file inside App_Resource/Android path. Every time I run app in android, I get below error in Setting.gradle file :
> 
> Failed to build plugin nativescript-plugin-firebase :
> Error: Command ./gradlew failed with exit code 1
> 
> Project directory '/private/var/lib/workspace/MOBILE-BUILDS//platforms/tempPlugin/nativescript_plugin_firebase' is not part of the build defined by settings file '/private/var/lib/workspace/MOBILE-BUILDS//settings.gradle'. If this is an unrelated build, it must have its own settings file
> 
> I have added below files
> 
> 1. App_Resources/Android/google-service.json
> 2. Add firebase plugin and generated firebase.nativescript.json file with below details
>    {
>    "external_push_client_only": false,
>    "using_ios": true,
>    "using_android": true,
>    "firestore": false,
>    "realtimedb": false,
>    "authentication": true,
>    "remote_config": false,
>    "performance_monitoring": false,
>    "messaging": false,
>    "in_app_messaging": false,
>    "crashlytics": true,
>    "storage": false,
>    "functions": false,
>    "facebook_auth": false,
>    "google_auth": false,
>    "admob": false,
>    "dynamic_links": false,
>    "ml_kit": false
>    }
> 
> Please help me with this issue as I am having serious problem with my app.

Hi Riddhi135,
I have exactly the same issue. How did you solve it ? Thanks

**Comment by ibnYusrat** [comment]
Hi I am also having exactly the same issue.

**Comment by marotes** [comment]
> Hi I am also having exactly the same issue.

Not sure it will solve your issue, but on my side I have solved it (after many hours….) just by removing the settings.gradle file in the root project directory…..
