### ISSUE TITLE
Android Scanner freezes up while scanning QR code for the second time.

### ISSUE THREAD

**Issue by gauchanneelam** [EddyVerbruggen/nativescript-plugin-firebase#1397]
On android ,whenever I scan the code for the second time(after successful  scan for the first time), the scanner freezes up. Its working fine on iOS.

**Comment by EddyVerbruggen** [comment]
Can you share a repo that shows this behavior?

**Comment by gauchanneelam** [comment]
Hi @EddyVerbruggen Here's the video that shows the behaviour

**Comment by EddyVerbruggen** [comment]
Hi @gauchanneelam, appreciate the video, but I meant a repo I can clone and run myself.

**Comment by EddyVerbruggen** [comment]
@gauchanneelam Thanks, I'll take a look!

**Comment by EddyVerbruggen** [comment]
AFAIK it's a simple Angular routing issue which you can fix by merging https://github.com/gauchanneelam/MLKIT-barcode-scanner/pull/1
