### ISSUE TITLE
does an empty query fire the onvalue function ?

### ISSUE THREAD

**Issue by sflament** [EddyVerbruggen/nativescript-plugin-firebase#14]
Good job with this firebase plugin.
thank's for that.

But I'am facing an issue :  I do a query to search for an item in the firebase path.
Here is my code
```js
console.log('query start');
fbresp = firebase.query( function(snap) { console.log('query fired');  },
            myPath,
            {
              orderBy: {type: firebase.QueryOrderByType.CHILD, value : 'title'},
              range: {type: firebase.QueryRangeType.EQUAL_TO, value: 'foo' },
              limit: {type: firebase.QueryLimitType.FIRST, value: 1 }
            }
          ).then(
        function () { console.log("firebase.query added"); },
        function (error) { console.log("firebase.query error: " + error); 
});
console.log('query end');
```

If "foo" exist in the firebase path, I see "query fired"
But if "foo" doesn't, I see nothing else that query start/query end

How can i know that an item is not in my database ?
In javascript, i use if (snap.exist()) {...
But here, the function where i could place this piece of code is not triggered.

regards
Stephane

**Comment by EddyVerbruggen** [comment]
Hey, great question! There's no `.exists` in the native SDK's, but I think there's something else: you can add a query as a listener which listens forever, but there's also a way to make it stop after the first value has been retrieved. It's not in the docs, but I'm speculating that one will just get the current state and also return in case the value is currently null. Let me try this..

**Comment by EddyVerbruggen** [comment]
Yep, that worked - please update to 2.0.1 and see the readme at `singleEvent`.

**Comment by sflament** [comment]
Great ! and very quick response.

Using the singleEvent, I get a snapshot with only the key as value.

for exemple :
  .../branch0/-KEFGGRS56TGER 
                          - title : "foo"
                          - detail : "bla bla"    

with singleEvent , I get
   type = Valuechanged
   key = branch0
   value = -KEFGGRS56TGER

With no singleEvent (when the key exist), I get
  type = ChildAdded
  key = -KEFGGRS56TGER
  value = object
       with  value.title = "foo"
                value.detail = "bla bla"


So, Is it normal to get only the key with the singleEvent ?
if it's normal, then, I need 2 query , one to check, and if exist, an aother query to get the full snapshot.

It would be better if I can obtain the full snapshot with singleEvent if the object exist, and null as value if not.

what you think ?

**Comment by EddyVerbruggen** [comment]
That's not what I'd expect. Can you post the exact code you're using for both calls? Please use 3 backticks around your code to make it look pretty.

**Comment by sflament** [comment]
Hello Eddy,
Sorry for bad formatting, I'm a newbie with new tools.

I don't know how to use correctly the bacticks.
I will look at this.
I mus leave now.


For now , here is my code, splitted in 2 calls,  because, one was not ok.



    function checkNode(PTitle, FTitle, mForceTxt, member) {
       // le noeud fils existe t-il dans la table des noeuds ?
       fbresp = firebase.query(
            function(snap) {
               if (snap.value != null){
                  doAddNode(PTitle, FTitle, mForceTxt, member, true)
               } else {
                  doAddNode(PTitle, FTitle, mForceTxt, member, false)
               };
            },
            FBserv.nodesPath,
            {
              singleEvent : true, // pour vérifier s'il existe ou pas une
valeur
              orderBy: {type: firebase.QueryOrderByType.CHILD, value :
'title'}, //value mandatory if CHILD
              range: {type: firebase.QueryRangeType.EQUAL_TO, value:
FTitle},
              limit: {type: firebase.QueryLimitType.FIRST, value: 1 }
            }
          ).then(
        function () { console.log("firebase.query check node"); },
        function (error) { console.log("firebase.query check node error: "
+ error); });
    }


function doAddNode(PTitle, FTitle, mForceTxt, member, found) {
       var mForce = parseInt(mForceTxt);
       // le noeud fils existe t-il dans la table des noeuds ?
       if (found) { // le noeud existe, je dois le récupérer
         fbresp = firebase.query(
             function(snap) {
                  var oldfNkey = snap.key;
                  var oldpAFGpkey = snap.value.pAFGpkey;
                  var oldfNowner = snap.value.owner;
                  doMore(PTitle, FTitle, mForce, member, oldfNkey,
oldpAFGpkey, oldfNowner);
              },
              FBserv.nodesPath,
              {
                //orderBy: {type: firebase.QueryOrderByType.KEY } //value
not mandatory if KEY
                orderBy: {type: firebase.QueryOrderByType.CHILD, value :
'title'}, //value mandatory if CHILD
                range: {type: firebase.QueryRangeType.EQUAL_TO, value:
FTitle},
                limit: {type: firebase.QueryLimitType.FIRST, value: 1 }
              }
            ).then(function () {console.log("firebase.query doAdd node");},
                   function (error) {console.log("firebase.query doAdd node
error: " + error); });
       } else { // le noeud n'exite pas, je l'ajoute direct
           var newfNkeypath = CreateNode (FBserv.nodesPath, FTitle, member);
           //addNodeInTrees(PTitle, FTitle, mForce, member,
newfNkeypath.key(), newfNkeypath );
       };
    }

Stephane


2016-02-28 15:51 GMT+01:00 Eddy Verbruggen <notifications@github.com>:

**Comment by sflament** [comment]
I have an other question.

Can i get easely, the generated key with a push ?
It seems, the the push return only somethin when error.

Stéphane

2016-02-28 15:51 GMT+01:00 Eddy Verbruggen <notifications@github.com>:

**Comment by sflament** [comment]
Here is my code, splitted in 2 calls,  with correct formatting.

```js
 function checkNode(PTitle, FTitle, mForceTxt, member) {
       // le noeud fils existe t-il dans la table des noeuds ?
       fbresp = firebase.query(
            function(snap) {
               if (snap.value != null){
                  doAddNode(PTitle, FTitle, mForceTxt, member, true)
               } else {
                  doAddNode(PTitle, FTitle, mForceTxt, member, false)
               };
            },
            FBserv.nodesPath,
            {
              singleEvent : true, // pour vérifier s'il existe ou pas une valeur
              orderBy: {type: firebase.QueryOrderByType.CHILD, value : 'title'}, //value mandatory if CHILD
              range: {type: firebase.QueryRangeType.EQUAL_TO, value: FTitle},
              limit: {type: firebase.QueryLimitType.FIRST, value: 1 }
            }
          ).then(
        function () { console.log("firebase.query check node"); },
        function (error) { console.log("firebase.query check node error: " + error); });
    }

function doAddNode(PTitle, FTitle, mForceTxt, member, found) {
       var mForce = parseInt(mForceTxt);
       // le noeud fils existe t-il dans la table des noeuds ?
       if (found) { // le noeud existe, je dois le récupérer
         fbresp = firebase.query(
             function(snap) {
                  var oldfNkey = snap.key;
                  var oldpAFGpkey = snap.value.pAFGpkey;
                  var oldfNowner = snap.value.owner;
                  doMore(PTitle, FTitle, mForce, member, oldfNkey,oldpAFGpkey, oldfNowner);
              },
              FBserv.nodesPath,
              {
                orderBy: {type: firebase.QueryOrderByType.CHILD, value :'title'},
                range: {type: firebase.QueryRangeType.EQUAL_TO, value: FTitle},
                limit: {type: firebase.QueryLimitType.FIRST, value: 1 }
              }
            ).then(function () {console.log("firebase.query doAdd node");},
                   function (error) {console.log("firebase.query doAdd node error: " + error); });
       } else { // le noeud n'existe pas, je l'ajoute direct
           var newfNkeypath = CreateNode (FBserv.nodesPath, FTitle, member);
       };
    }
```

**Comment by EddyVerbruggen** [comment]
Hi, I've tested this and with `singleEvent` the value is not only the key but the key's value as well. Compare this:

`singleEvent:false` (returns the last event that resulted in the current state):
<img width="451" alt="screen shot 2016-02-28 at 22 00 01" src="https://cloud.githubusercontent.com/assets/1426370/13381888/59d344b6-de67-11e5-8cbb-401a5995b5c0.png">

`singleEvent:true` (returns the current state):
<img width="458" alt="screen shot 2016-02-28 at 22 01 13" src="https://cloud.githubusercontent.com/assets/1426370/13381889/5dd04e92-de67-11e5-9160-5f2535e69118.png">

This is according to the Firebase docs AFAIK.

**Comment by sflament** [comment]
Thank you VERY much.
I was wrong (not enough at ease with JSON)

Here is my code now, with only one call
with 2 small functions to get first object and first key inside the snap result

```js
function firstObject(JSONobj) {
	for(var key in JSONobj) { return JSONobj[key] }
}

function firstKey(JSONobj) {
	for(var key in JSONobj) { return key }
}

function doAddNode(PTitle, FTitle, Force, member) {
       fbresp = firebase.query(
            function(snap) {
               if (snap.value != null){
                  var item = firstObject(snap.value);
                  var oldfNkey = firstKey(snap.value);
                  var oldpAFGpkey = item.pAFGpkey;
                  var oldfNowner = item.owner;
                  doMore(PTitle, FTitle, Force, member, oldfNkey, oldpAFGpkey, oldfNowner);
               } else {
                  var newfNkeypath = CreateNode (FBserv.nodesPath, FTitle, member);
               };
            },
            FBserv.nodesPath,
            {
              singleEvent : true, // pour vérifier s'il existe ou pas une valeur
              orderBy: {type: firebase.QueryOrderByType.CHILD, value : 'title'}, //value mandatory if CHILD
              range: {type: firebase.QueryRangeType.EQUAL_TO, value: FTitle},
              limit: {type: firebase.QueryLimitType.FIRST, value: 1 }
            }
          ).then(
        function () { console.log("firebase.query check node"); },
        function (error) { console.log("firebase.query check node error: " + error); });
    }
```
