### ISSUE TITLE
How do I get UserID after the login process?

### ISSUE THREAD

**Issue by 9thwall** [EddyVerbruggen/nativescript-plugin-firebase#140]
Hi!
Sorry to bother you with such a simple question...
I was wondering how I can get the userid of the current logged in user in another component after logging in. I understand I can do this.... 

```
firebase.login({
            type: firebase.LoginType.FACEBOOK
            }).then(
            function (result) {
                //JSON.stringify(result);
                console.log("USERID: " + result.uid);
            },
            function (errorMessage) {
                console.log("Login Error: " + errorMessage);
            }
        )
```

But I'm trying to get the uid after.. in another component.

**Comment by asaph26** [comment]
@9thwall: You can add a listener to and get the uid from the listener as documented here https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/AUTHENTICATION.md#listening-to-auth-state-changes. 

You can persist the uid in a singleton service, given that you are using angular.

**Comment by 9thwall** [comment]
Perfect! Thank you!
