### ISSUE TITLE
Firebase functions httpsCallable region support

### ISSUE THREAD

**Issue by siavee** [EddyVerbruggen/nativescript-plugin-firebase#1403]
Hi,

I've created some httpsCallable backend code in Firebase Cloud Functions using the default `us-central1` region and I've tried calling them without a problem.

However since my database lives in `asia-east2` region, I need to move the functions to the same region to reduce costs. This is described [here](https://firebase.google.com/docs/functions/locations) in the documents.

How do I set the region of a httpsCallable function?

Thanks in advance!

**Comment by EddyVerbruggen** [comment]
Hi, good question, but you currently can't. It's a simple change though so a nice one to have in an upcoming version. No idea when exactly.

**Comment by siavee** [comment]
Can I help? I am interested if you can point me the direction 😄

**Comment by EddyVerbruggen** [comment]
Thanks for offering. The actual change is very quickly implemented, but I need to do a few other tasks before I can release a new version of this plugin.

The code required is actually on the page you linked to and it needs to be incorporated in [these files](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/tree/master/src/functions).

**Comment by siavee** [comment]
Ah I see.. Thanks alot for the pointers. Of course I understand, this is a huge plugin. Not to mention other plugins that you maintain..

Thanks a lot again for the super quick reply, the plug-in is awesome!

**Comment by siavee** [comment]
Hi @EddyVerbruggen, I've created a fix [here](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/compare/master...siavee:feature/functions-region?expand=1). Is that code satisfactory?

I haven't been able to test it on iOS, somehow even with vanilla v9.1.1 I can't call any httpsCallable in my iOS emulator, but I think the problem is on the configuration on my side. Works well in Android though.

Let me know if the code is ok, and I will create a pull request.

**Comment by EddyVerbruggen** [comment]
Very cool, nice work! Please send a PR :)

**Comment by siavee** [comment]
Will do 👌🏻😁

**Comment by EddyVerbruggen** [comment]
Awesomenesss

**Comment by ibnYusrat** [comment]
Is it done? I am having the same issue..
