### ISSUE TITLE
Forground notications not came in android

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [EddyVerbruggen/nativescript-plugin-firebase#1408]
Hai iam developing android and ios application using nativescript angular.iam using fcm push notifications. i have an issue in android that is notifications not came when app in foreground but in ios the notification come foreground and background. how to solve the issue in foreground?

**Comment by aranmohyeddin** [comment]
You need to specify it in the init call that you want foreground notifications. Please search for it in the issues. This question has been asked and answered so many times already.

**Comment by ArigarasuthanRepo** [comment]
i was specified foregroundnotifications:true but it was not worked.

**Comment by aranmohyeddin** [comment]
Then you should describe exactly what you did and how you initialized the plugin etc plus your android version.

**Comment by aranmohyeddin** [comment]
I'm quite sure you haven't took the time too look at [these](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues?q=foreground+is%3Aclosed)

**Comment by ArigarasuthanRepo** [comment]
Thanks for the response. I have fixed the issue by using onMessageRecived callback
