### ISSUE TITLE
firebase.createUser() returns wrong return type on resolve in android version of code

### ISSUE THREAD

**Issue by jamesehly** [EddyVerbruggen/nativescript-plugin-firebase#141]
The typescript definition declares that createUser should return a type of Promise<CreateUserResult>

`export function createUser(options: CreateUserOptions): Promise<CreateUserResult>;`

The android version of the code is returning a `Promise<User>` result via the toLoginResult function.  The iOS version of the code returns the correct type of result.

I've already fixed this in a local version and will make a pull request for you.  

James

**Comment by EddyVerbruggen** [comment]
Awesome, James! Thanks in advance 👍

**Comment by EddyVerbruggen** [comment]
Available in 3.7.0.
