### ISSUE TITLE
Help Wanted: Authentication Persistence

### ISSUE THREAD

**Issue by kdiehl** [EddyVerbruggen/nativescript-plugin-firebase#1410]
Usually then web api has a way to persist the authentication state as follows 
```ts
firebase.auth().setPersistence(firebase.auth.Auth.Persistence.SESSION)
  .then(function() {
    return firebase.auth().signInWithEmailAndPassword(email, password);
  })
  .catch(function(error) {
    // Handle Errors here.
  });
```
Source: https://firebase.google.com/docs/auth/web/auth-state-persistence

I have not found a way yet to solve this issue using the plugin.
Any Ideas?

**Comment by EddyVerbruggen** [comment]
Did you look at the Firebase iOS and Android docs to see if there's something similar to the Web API? If so, we can add it to the plugin as well.

**Comment by kdiehl** [comment]
I did not find anything that is similar.
At the moment I realized "keep me logged in" functionality by saving the 
user object in the application-settings as serialilzed json.
That does not feel very good :laughing:

**Comment by EddyVerbruggen** [comment]
Well I have to work with what the Firebase SDK has to offer.. if you need a best practice or want to do a feature request then I think it's best to post that in the Firebase Github repo instead.

**Comment by pandabuilt** [comment]
@kdiehl  you shoudn't have to store anything in application settings. Just inside your initializeApp set the user if data.loggedIn is true.... 

There is no need to reloadUser as well. using `@nativescript/firebase` `firebase.firebase.reloadUser`
`
firebaseWebApi.initializeApp({
        onAuthStateChanged: (data: any) => {
          if (data.loggedIn) {
            firebaseWebApi.auth().currentUser = data.user;
          } else {
            this.authService.setAuthToken('');
          }
        }
      })`

**Comment by paul-muckypuddle** [comment]
Hey @pandabuilt - trying to do the same thing here but using the Native API - if you have a moment would you be able to provide a little more detail?

**Comment by pandabuilt** [comment]
@paul-muckypuddle I would need more to understand what you are trying to do with Native API

Basically on the initialization of my wrapper component i initialize the firebase app.  In it's options I initialize firebase with an event of onAuthStateChanged - firebase will send back the user if they are logged in, and data.loggedIn will be false.  Based on that I will log them in or  I'll push the viewcontroller of a sign in page if they are not logged in.

**Comment by paul-muckypuddle** [comment]
@pandabuilt I think my issue was more Nativescript Vue specific, requiring access to navigate on the Vue object within the onAuthStateChanged callback wasn't working.
