### ISSUE TITLE
Error with firebase.logout related to FacebookSdk.sdkInitialize()

### ISSUE THREAD

**Issue by Arystosedes** [EddyVerbruggen/nativescript-plugin-firebase#1413]
Hi, I have an error with firebase.logout related to FacebookSdk.sdkInitialize(). If I'm logged in (using signInWithEmailAndPassword, I'm not using Facebook login method) and then try to log out using this code below:

const firebaseWebApi = require('nativescript-plugin-firebase/app');
    return firebaseWebApi
      .auth()
      .signOut()
      .then(() => console.log('Logout OK'));

I get this:

Error in firebase.logout: Error: The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.
JS:     com.facebook.internal.Validate.sdkInitialized(Validate.java:144)
JS:     com.facebook.login.LoginManager.<init>(LoginManager.java:80)
JS:     com.facebook.login.LoginManager.getInstance(LoginManager.java:93)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1209)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1096)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1083)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1063)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1055)
JS:     com.tns.gen.java.lang.Runnable.run(Runnable.java:17)
JS:     android.os.Handler.handleCallback(Handler.java:873)
JS:     android.os.Handler.dispatchMessage(Handler.java:99)
JS:     android.os.Looper.loop(Looper.java:193)
JS:     android.app.ActivityThread.main(ActivityThread.java:6669)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     com.android.internal.os.RuntimeInit$Me...
JS: Unhandled Promise rejection: {
JS:   "message": {
JS:     "nativeException": {}
JS:   }
JS: } ; Zone: <root> ; Task: Promise.then ; Value: {
JS:   "message": {
JS:     "nativeException": {}
JS:   }
JS: } undefined

my package.json

"dependencies": {
    "@angular/animations": "~8.0.1",
    "@angular/cdk": "^8.2.0",
    "@angular/common": "~8.0.1",
    "@angular/compiler": "~8.0.1",
    "@angular/core": "~8.0.1",
    "@angular/forms": "~8.0.1",
    "@angular/http": "~8.0.0-beta.10",
    "@angular/platform-browser": "~8.0.1",
    "@angular/platform-browser-dynamic": "~8.0.1",
    "@angular/router": "~8.0.1",
    "@angular/fire": "^5.2.1",
    "@angular/material": "^8.2.0",
    "@ngrx/store": "^8.3.0",
    "core-js": "^2.5.4",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "firebase": "^6.6.1",
    "nativescript-angular": "~8.2.1",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-sidedrawer": "7.0.1",
    "nativescript-plugin-firebase": "^10.0.0",
    "reflect-metadata": "~0.1.12",
    "rxjs": "~6.5.0",
    "tns-core-modules": "^5.1.0 || >5.1.0- || >5.2.0-",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular/cli": "~8.0.3",
    "@angular/compiler-cli": "~8.0.1",
    "@angular-devkit/build-angular": "~0.803.4",
    "@nativescript/schematics": "~0.7.0",
    "@nativescript/tslint-rules": "~0.0.2",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "nativescript-dev-webpack": "~1.2.0",
    "tns-core-modules": "next",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3",
    "node-sass": "^4.7.1"
  }

**Comment by EddyVerbruggen** [comment]
Do you have any idea why this line evaluates to `true` in your app?

https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/f80b1dba425c941c478bdcf4c8350a38bede0716/src/firebase.android.ts#L691

**Comment by Arystosedes** [comment]
I have no idea :/ I'm not using facebook to log in (I have "facebook_auth" set to false in my firebase.nativescript.json also).

How I log in:
      public login(authData: AuthData): Promise<firebase.auth.UserCredential> {
    return this.getAuth()
      .signInWithEmailAndPassword(authData.email, authData.password)
      .then((userCredential: firebase.auth.UserCredential) => {
        if (userCredential && userCredential.user.emailVerified) {
          userCredential.user.getIdTokenResult().then((idTokenResult: firebase.auth.IdTokenResult) => {
            do something
          });
        } else {
          alert(error);
        }
        return;
      })
      .catch((error: any) => {
        console.log(error);
      });
  }

and my log out method
 public signOut(): Promise<void> {
    return firebaseWebApi
      .auth()
      .signOut()
      .then(x => {
        debugger;
      })
      .catch(x => {
        here is the bug "Error: The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first. com.facebook.internal.Validate.sdkInitialized(Validate.java:144) com.facebook.login.LoginManager"
      });
  }

**Comment by EddyVerbruggen** [comment]
Can you share that repo? Or even better: a minimal repo that demonstrates this issue?

**Comment by Arystosedes** [comment]
Ok, I know what was wrong. When I created new project, during the initialization of firebase config I set facebook_auth on true (I need this in the future, but now I'm not using this). When I remove node_modues, firebase.config file, and hooks folder (not sure if it was needed to remove all of them) and set firebase config with facebook_auth on false, then the app wored correctly.
