### ISSUE TITLE
Firebase Analytics is listed as missing dependency

### ISSUE THREAD

**Issue by Lehren** [EddyVerbruggen/nativescript-plugin-firebase#1416]
I have only installed Firebase In App messaging and Firebase Cloud Messaging and upon running the app, I get the following error

```
java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: com.google.firebase.components.MissingDependencyException: Unsatisfied dependency for component Component<[class com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay]>{2, type=0, deps=[Dependency{anInterface=class com.google.firebase.FirebaseApp, type=required, direct=true}, Dependency{anInterface=interface com.google.firebase.analytics.connector.AnalyticsConnector, type=required, direct=true}, Dependency{anInterface=class com.google.firebase.inappmessaging.FirebaseInAppMessaging, type=required, direct=true}]}: interface com.google.firebase.analytics.connector.AnalyticsConnector
```

I am running version 10.0.0 and you have stated Analytics can be an optional dependency. Doesn't seem to quite work yet.

**Comment by EddyVerbruggen** [comment]
Interesting, so I guess `FirebaseInAppMessagingDisplay` still internally depends on Analytics in the Firebase Android SDK.

I guess for the time being adding [this](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/f80b1dba425c941c478bdcf4c8350a38bede0716/demo-ng/firebase.nativescript.json#L5) (but `true`) and running `rm -rf platforms node_modules` should get you going again.

**Comment by n0mer** [comment]
@EddyVerbruggen , does this plugin support yarn? I've got package-lock.json file created after running `rm -rf platforms node_modules` and then `tns run android`

**Comment by EddyVerbruggen** [comment]
@n0mer I'm not sure what that has to do with this issue, but AFAIK no.

**Comment by kdiehl** [comment]
I solved a lot of problems by running npm install and then deleting package.lock etc. 
and running yarn again. (Does not feel very good but seems to work somehow)

**Comment by n0mer** [comment]
@EddyVerbruggen you are right, this is sort of side-effect to this issue. Discovered it after applying fix with "analytics: true" in config file, removing node_modules & platforms.
