### ISSUE TITLE
Android background notification does not retrieve data

### ISSUE THREAD

**Issue by danielangelo** [EddyVerbruggen/nativescript-plugin-firebase#1417]
Is there a way I can receive the notification data when an ANDROID user clicks on the notification ? On iOS it works. It should be like this: User receives notification, clicks on it, and previews it's data, but the problem is that on android there is no data received from background state.

This is the JSON content of the notification received on FOREGROUND:

```
"message": {
     "foreground": true,
     "from": "452159219143",
     "title": "My title",
     "body": "My text",
     "data": {}
}
```

This is the JSON content of the notification received on BACKGROUND:

```
"message": {
     "foreground": false,
     "data": {
       "google.delivered_priority": "high",
       "google.sent_time": {},
       "google.ttl": {},
       "google.original_priority": "high",
       "google.message_id": "0:1558126089047652%05..."
     },
     "google.delivered_priority": "high",
     "google.sent_time": "[Circular]",
     "google.ttl": "[Circular]",
     "google.original_priority": "high",
     "google.message_id": "0:1558126089047652%05..."
}
```
As you can see, data is only received when app is in foreground.

**Comment by opHASnoNAME** [comment]
Same issue here (;

**Comment by danielangelo** [comment]
I figured it out by sending data as payload. Payload is received no mather what

**Comment by opHASnoNAME** [comment]
Yep same here, thanks ;)
