### ISSUE TITLE
xcodebuild failed iosfwd

### ISSUE THREAD

**Issue by sudiptosen** [EddyVerbruggen/nativescript-plugin-firebase#1418]
Hi,

I keep getting the following error

"/platforms/ios/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/model/document.h:20:10: fatal error: 'iosfwd' file not found
#include <iosfwd>"

I have the updated   "nativescript-plugin-firebase": "^10.0.0"

Some more log here.
[log.txt](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/files/3668841/log.txt)

Really appreciate any suggestions

**Comment by EddyVerbruggen** [comment]
Do you really really really need nativescript-svg? Because removing that will resolve the issue. Looks like the Pods in these plugins bite each other.

**Comment by sudiptosen** [comment]
Thanks a ton Eddy - worked like a charm. Took out "nativescript-svg" and everything compiled fine. 
Does this mean that the one Pod was removing the "iosfwd" file or something? Just curious.

**Comment by EddyVerbruggen** [comment]
I didn't look into the details, but the last few lines of your log pointed at that plugin so I immediately tried without it.
