### ISSUE TITLE
Is it possible to understand which notification message is tapped to open the app

### ISSUE THREAD

**Issue by osmanertem** [EddyVerbruggen/nativescript-plugin-firebase#1419]
Consider following scenario;

* Initially the apps is killed
* A push notification is received by the phone
* user tappes on the new notification

After that the application is launched. Then I want to navigate to a special page with some information from the notification which triggered app launch. 

Is this possible with the plugin?

**Comment by EddyVerbruggen** [comment]
I guess it is, but did you try it?

**Comment by osmanertem** [comment]
Firstly, I thought that naticescript-plugin-firebase may provide a callback for this purpose but apparently it is not :). 

But now I think that this functionality may be provided by nativescript itself. 

I will try registering for following event and share the result here.
```
const application = require("tns-core-modules/application");

application.on(application.launchEvent, (args) => {
    if (args.android) {
        // For Android applications, args.android is an android.content.Intent class.
        console.log("Launched Android application with the following intent: " + args.android + ".");
    } else if (args.ios !== undefined) {
        // For iOS applications, args.ios is NSDictionary (launchOptions).
        console.log("Launched iOS application with options: " + args.ios);
    }
});
```

**Comment by osmanertem** [comment]
I could not manage to get the tapped notification data from `application.launchEvent` but `OnMessageReceivedCallback` is triggered with tapped notification's data after app launched. 

It may make application launch flow a little complicated but at least it is a solution.  Thanks @EddyVerbruggen
