### ISSUE TITLE
Documentation incorrect on retrieving collection

### ISSUE THREAD

**Issue by joshpied** [EddyVerbruggen/nativescript-plugin-firebase#1422]
The documentation found here https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/FIRESTORE.md says to retrieve a collection like so:

`const citiesCollection = firebase.firestore().collection("cities");`

This was not working for me and I noticed the error `JS: ERROR TypeError: firebase.firestore is not a function` when console logging `citiesCollection`. After changing `firestore()` to `firestore` it is working as expected.

Why is `firestore` used as a function throughout the documentation if it is incorrect?

**Comment by EddyVerbruggen** [comment]
Depends on how you import `firebase`. This example uses the web API. Check the demo-ng folder for some examples.
