### ISSUE TITLE
How to call useFunctionsEmulator

### ISSUE THREAD

**Issue by caddac** [EddyVerbruggen/nativescript-plugin-firebase#1424]
I'm trying to run my firebase functions locally (which I've got working) but want to point my mobile app to my locally running functions. 

How do I call `useFunctionsEmulator`  using this library? I've tried several ways but nothing seems to work.

Here is the original documentation: https://firebase.google.com/docs/reference/android/com/google/firebase/functions/FirebaseFunctions.html#useFunctionsEmulator(java.lang.String)

Thanks!

**Comment by EddyVerbruggen** [comment]
Hi!

You couldn't find it, because it wasn't implemented. But I've tried to do it now and will release it with 10.0.2. Not sure when that's out though.
