### ISSUE TITLE
Is there a way to check notification permissions on IOS?

### ISSUE THREAD

**Issue by Mixelated** [EddyVerbruggen/nativescript-plugin-firebase#1429]
Implemented cloud messaging and cannot find anything online regarding permission. Is there a way to see if the user rejected the notification permission?

**Comment by EddyVerbruggen** [comment]
Can you give [this](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/8fffc8f9d88780327abbb7b177f7c6d7d3234c58/docs/NON_FIREBASE_MESSAGING.md#arenotificationsenabled) a go?

**Comment by Mixelated** [comment]
works great, thanks!
