### ISSUE TITLE
NullPointerException inside Facebook auth code

### ISSUE THREAD

**Issue by raffaeler** [EddyVerbruggen/nativescript-plugin-firebase#143]
Hi, I carefully followed the auth documentation to test Facebook and Google auth.
The Google Auth worked successfully while I have a persisten error with the Facebook authentication.

I triple checked the Facebook codesm the string files, the manifest.xml and compared the app with the sample that uses this plugin, but I didn't find anything wrong yet.

Does anybody have any idea of what could be the root cause of this exception?

TIA

~~~~
09-28 18:48:58.834  5379  5379 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
09-28 18:48:58.834  5379  5379 W System.err:    at com.facebook.login.LoginClient.getLogger(LoginClient.java:381)
09-28 18:48:58.834  5379  5379 W System.err:    at com.facebook.login.LoginClient.logAuthorizationMethodComplete(LoginClient.java:431)
09-28 18:48:58.834  5379  5379 W System.err:    at com.facebook.login.LoginClient.tryNextHandler(LoginClient.java:212)                                                        
09-28 18:48:58.834  5379  5379 W System.err:    at com.facebook.login.GetTokenLoginMethodHandler.getTokenCompleted(GetTokenLoginMethodHandler.java:119)
09-28 18:48:58.835  5379  5379 W System.err:    at com.facebook.login.GetTokenLoginMethodHandler$1.completed(GetTokenLoginMethodHandler.java:74)
09-28 18:48:58.835  5379  5379 W System.err:    at com.facebook.internal.PlatformServiceClient.callback(PlatformServiceClient.java:161)
09-28 18:48:58.835  5379  5379 W System.err:    at com.facebook.internal.PlatformServiceClient.handleMessage(PlatformServiceClient.java:141)                                  
09-28 18:48:58.835  5379  5379 W System.err:    at com.facebook.internal.PlatformServiceClient$1.handleMessage(PlatformServiceClient.java:62)
09-28 18:48:58.835  5379  5379 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:102)                                                                       
09-28 18:48:58.835  5379  5379 W System.err:    at android.os.Looper.loop(Looper.java:148)
09-28 18:48:58.835  5379  5379 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:5461)                                                                  
09-28 18:48:58.835  5379  5379 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
09-28 18:48:58.835  5379  5379 W System.err:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)                                            
09-28 18:48:58.835  5379  5379 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-28 18:48:58.843   572   590 I ActivityManager: START u0 {flg=0x14008000 cmp=org.zzz.iot01/com.tns.ErrorReportActivity (has extras)} from uid 10028 on display 0           
09-28 18:48:58.912  5379  5379 I Process : Sending signal. PID: 5379 SIG: 9
09-28 18:48:58.962   572  1187 I WindowState: WIN DEATH: Window{3d8e447 u0 org.zzz.iot01/com.facebook.FacebookActivity}                                                      
09-28 18:48:58.962   572  1692 D GraphicsStats: Buffer count: 8
09-28 18:48:58.966   572  1388 I WindowState: WIN DEATH: Window{e4f2776 u0 org.zzz.iot01/com.tns.NativeScriptActivity}                                                       
09-28 18:48:58.988   572  1201 I ActivityManager: Process org.zzz.iot01 (pid 5379) has died
09-28 18:48:59.006   572  1201 I ActivityManager: Start proc 5611:org.zzz.iot01/u0a28 for activity org.zzz.iot01/com.tns.ErrorReportActivity
09-28 18:48:59.019 31815 31815 I Finsky  : [1] com.google.android.finsky.utils.dz.onTrimMemory(25): Memory trim requested to level 5                                          
09-28 18:48:59.019  5611  5611 I art     : Late-enabling -Xcheck:jni
~~~~

**Comment by EddyVerbruggen** [comment]
Interesting issue. Just tried the latest version on my shiny new Android 7 powered Nexus 6P and all is fine. Same on my old 4.4.4 Samsung tablet as well as a few simulators. So clearly we're running different code.

Have you tried the [demo app](https://github.com/EddyVerbruggen/nativescript-plugin-firebase-demo) on a real device? That may help narrowing this down.

**Comment by raffaeler** [comment]
I will for sure, but what I am scared of, is that the error is totally not-understandable.
The stack trace is so long that I don't even see my code.
Is there any way to read from the firebase object the FB configuration (such as the app id in the resource string)?
Thank you

**Comment by EddyVerbruggen** [comment]
If init() worked then google-services.json was picked up correctly, so that's the config that's being used.

And that stacktrace is useless indeed.

**Comment by raffaeler** [comment]
Yes, but the facebook configuration uses the @string/xxx resource notation and I don't have a proof that it is read correctly by the library... (just guessing of course)

**Comment by raffaeler** [comment]
The demo app works well, so there is nothing with the device.
Could you please tell me if this other stack trace (from my test app) give some hints?

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at com.facebook.login.LoginClient.getLogger(LoginClient.java:381)
	at com.facebook.login.LoginClient.logAuthorizationMethodComplete(LoginClient.java:431)
	at com.facebook.login.LoginClient.tryNextHandler(LoginClient.java:212)
	at com.facebook.login.GetTokenLoginMethodHandler.getTokenCompleted(GetTokenLoginMethodHandler.java:119)
	at com.facebook.login.GetTokenLoginMethodHandler$1.completed(GetTokenLoginMethodHandler.java:74)
	at com.facebook.internal.PlatformServiceClient.callback(PlatformServiceClient.java:161)
	at com.facebook.internal.PlatformServiceClient.handleMessage(PlatformServiceClient.java:141)
	at com.facebook.internal.PlatformServiceClient$1.handleMessage(PlatformServiceClient.java:62)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5461)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by EddyVerbruggen** [comment]
Perhaps you were trying to use init before the app started / the first view was shows? That's fixed since 3.6.4.

**Comment by raffaeler** [comment]
I call the init inside the ngOnInit() {} of the first view in the app.
Good to know there is the 3.7.0 now, I will test it on Wed (I am OOF now).
Crossing fingers ... (thank you)

**Comment by raffaeler** [comment]
I managed to make some network magic, connected remotely and made adb work on the network.
While the 3.70 had problems with typescript, the 3.71 now work with Facebook and Google providers.
I will soon test the other services.
To sum up:
1. thank you for your support
2. Please enhance the exception messages

Thank you.
