### ISSUE TITLE
How is the messagin token created? do I ever need to refresh it?

### ISSUE THREAD

**Issue by aranmohyeddin** [EddyVerbruggen/nativescript-plugin-firebase#1433]
I'm using this plugin only for firebase cloud messaging.
I'm a little confused as to how the registration token is created? once for each user? each installation? each device? 
Do I have to update it on my server after every release of the app?
right now I'm only sending the token to server when the user registers. but I don't feel so good about this. Can you walk me through the lifecycle of the token please?

**Comment by EddyVerbruggen** [comment]
Please post this on SO because it's not related to the plugin, but rather how the Firebase SDK handles this. I could answer, but I'm not 100% sure it would be correct.

**Comment by aranmohyeddin** [comment]
Thank you for your response. I asked it [here](https://stackoverflow.com/q/58426964/5120089) Any answer that comes from you would be helpful to me even if you are not sure about it:D it would be great if you could indulge me with your thoughts on this :D
