### ISSUE TITLE
FIROptions not found

### ISSUE THREAD

**Issue by AvigarD611** [EddyVerbruggen/nativescript-plugin-firebase#1434]
Hello! 

I am trying to implement this plugin and still no success ... My project is nativescript vue (dont think it matters, everything up to date) and after tns preview --bundle I get "firebase.init error: Reference error Can't find variable FIROptions".

It is ios build with NS Preview. 

Found only one issue for this problem and the guy is getting error on pod install, because of windows max path length. I got the same error. Now i did it in virtual linux and it runs fine, BUT:

I am doing all the steps with 1-2 more steps (installing ruby, then cocoapods, then i am trying to use "pod install", "pod setup" and etc ... I am getting "could not automatically select an Xcode workspace 'path/to/workspace.xcworkspace".

**Comment by EddyVerbruggen** [comment]
The Preview app does not ship with this plugin installed, so I don't think you can use the `preview` command. Try `tns run ios` instead.

**Comment by AvigarD611** [comment]
So the Preview app, doesn't support this plugin even if I install it (with tns plugin add nativescript-plugin-firebase)? 

And how it won't be possible to try it without MacOS (because tns run ios requires MacOS only)? Is there any chance to do it without MacOS?

**Comment by EddyVerbruggen** [comment]
I think you could try NativeScript Sidekick to deploy apps to an iOS device when not using a Mac.
