### ISSUE TITLE
Retrieving Notification Message but not triggering actual notification. 

### ISSUE THREAD

**Issue by Mixelated** [EddyVerbruggen/nativescript-plugin-firebase#1439]
Testing with iPhone 10s/iOS 11 on VueJS

When sending the notification message using CURL I retrieve a success message and while running the app I see the message in the onMessageRetrievedCallback. The problem is that it is not triggering an actual notification. 

```
firebase.init({
  showNotificationsWhenInForeground: true,
  showNotifications: true,
  onMessageReceivedCallback: function(message) {
    console.log("Title: " + message.title);
    console.log("Body: " + message.body);
  },
  onPushTokenReceivedCallback: function(token) {
    appSettings.setString('firebasetoken', token)
  }
})
```
Tried so far:
- I checked all the logs for firebase warnings but everything seems fine
- double checked the permission on the device to ensure notifications are allowed and showing
- tried using debug console instead of CURL. same result
- firebase is initialised in app.js
- reuploaded p8 and double checked bundle ids/date of device/not using vpn
- removed nativescript-local-notifications 

curl command I use:
```
curl -X POST --header "Authorization: key=MY_SERVER_KEY" --Header "Content-Type: application/json" https://fcm.googleapis.com/fcm/send -d "{\"notification\":{\"title\": \"My title\", \"text\": \"My text\", \"badge\": \"1\", \"sound\": \"default\"}, \"data\":{\"foo\":\"bar\"}, \"priority\": \"High\", \"to\": \"DEVICE_REGISTRATION_ID\"}"
```

config: 

```
{
    "external_push_client_only": false,
    "using_ios": true,
    "using_android": true,
    "analytics": false,
    "firestore": false,
    "realtimedb": false,
    "authentication": false,
    "remote_config": false,
    "performance_monitoring": true,
    "messaging": true,
    "in_app_messaging": false,
    "crashlytics": true,
    "storage": true,
    "functions": true,
    "facebook_auth": false,
    "google_auth": false,
    "admob": false,
    "dynamic_links": false,
    "ml_kit": false
}
```

notification response:
```
CONSOLE LOG file:///app/app.js:82:11: 'Title: test'
CONSOLE LOG file:///app/bundle.js:14041:16: 'Body: test'
[com.bundlerorg.mobile] Setting badge number to 0
[com.bundlerorg.mobile] Set badge number [ hasCompletionHandler: 0 hasError: 0 ]
```

**Comment by Mixelated** [comment]
*found someone with a similar issue suggesting that it might conflict with nativescript-local-notifications so will try that tonight

**Comment by Mixelated** [comment]
*update 2 days later still no clue why it is not working, someone suggested in another issue that nativescript-local might interfere but this didn't solve the problem for me

**Comment by EddyVerbruggen** [comment]
I may be able to assist you if you share that app. There could be a configuration issue or some other plugin interfering with the appdelegate.

**Comment by Mixelated** [comment]
Thanks! @EddyVerbruggen  I sent you an invite to the repository

**Comment by Mixelated** [comment]
let me know if there is anything else you need

**Comment by EddyVerbruggen** [comment]
Thx, let's use the issue-tracker in your repo to continue the discussion.

**Comment by vytautas-pranskunas-** [comment]
Hi, do you have this sorted out?
I also get notifications only in console in onMessageReceivedCallback but notifications are not showing
