### ISSUE TITLE
app not receiving push notifications from firebase

### ISSUE THREAD

**Issue by aquinn637** [EddyVerbruggen/nativescript-plugin-firebase#1440]
I’m working on trying to get push notifications working on my project. I’m working on a new project with NativeScript and Angular 8. 

I have created a free account with Firebase: https://console.firebase.google.com/
I linked my app id to the Firebase project and added Android. I downloaded the file ‘google-services.json ’ and put it in app/App_Resources/Android/google-services.json

I found a plugin for NativeScript for using Firebase:
https://github.com/EddyVerbruggen/nativescript-plugin-firebase

I followed the steps on both the firebase console and on the plugin github page but I’m not getting any notifications through on my phone.

How can I get my app to receive the push notifications?

Here is my app.components.ts file:

```
import { Component, OnInit } from "@angular/core";
const firebase = require("nativescript-plugin-firebase");
//import * as firebase from "firebase";

@Component({
    selector: "ns-app",
    templateUrl: "./app.component.html"
})
export class AppComponent implements OnInit {

    ngOnInit() {
      firebase.init({

        showNotifications: true,
        showNotificationsWhenInForeground: true,

        // Optionally pass in properties for database, authentication and cloud messaging,
        // see their respective docs.

        onPushTokenReceivedCallback: (token) => {
          console.log('[Firebase] onPushTokenReceivedCallback:', { token });
        },

        onMessageReceivedCallback: (message) => {
          console.log('[Firebase] onMessageReceivedCallback:', { message });
        }

      }).then(
        () => { console.log("firebase.init done"); },
        error => {
          console.log(`firebase.init error: ${error}`);
        }
      );
    }

}
```
package.json:

```
{
  "nativescript": {
    "id": "org.nativescript.FireBaseTest2",
    "tns-android": {
      "version": "6.1.2"
    },
    "tns-ios": {
      "version": "6.1.0"
    }
  },
  ....
```
Here are my push notification attempts:

![Screenshot (77)](https://user-images.githubusercontent.com/52042381/67303079-d0d9c200-f4e9-11e9-8ae1-7ff00f11ed4a.png)

**Comment by EddyVerbruggen** [comment]
Can you share that project with me? And are you running on a real device?

**Comment by aquinn637** [comment]
@EddyVerbruggen Yes, I'm running on a real Android device. How can I share my project with you?

**Comment by EddyVerbruggen** [comment]
Push a version of your that shows the problem to Github. Please strip it of any unrelated things..

**Comment by aquinn637** [comment]
@EddyVerbruggen Here it is: https://github.com/aquinn637/FireBaseTest2

**Comment by aquinn637** [comment]
@EddyVerbruggen I got one notification but it was only when the app was in the background. Not when the app was in the foreground.

**Comment by EddyVerbruggen** [comment]
Let's continue in your repo.

**Comment by vytautas-pranskunas-** [comment]
Hi, do you have this sorted out?
I also get notifications only in console in onMessageReceivedCallback but notifications are not showing

**Comment by manojdcoder** [comment]
@vytautas-pranskunas- 
- Are you testing on real device? 
- Notification never appear Or only when app is on foreground?

**Comment by vytautas-pranskunas-** [comment]
- Not sure what does that mean "testing on real device" because i have run "tns run adnroid" so emulator started but by using "preview" i also have it running on my phone. So is it real or not?

- Notifications appear only in console never on device or emulator

**Comment by vytautas-pranskunas-** [comment]
I wonder maybe this is because i never got notification about push notification permissions?

**Comment by felicks** [comment]
I have the same issue

**Comment by NazimMertBilgi** [comment]
Will the emulator not work in any way?
