### ISSUE TITLE
showNotifications: false is not working

### ISSUE THREAD

**Issue by KEYHAN-A** [EddyVerbruggen/nativescript-plugin-firebase#1444]
Hi,

I set `showNotifications: false` but I still get firebase notification directly on Android,
I'm trying to push notification with Nativescript-local-notification plugin when I get notification from Firebase, but when I close the app, I get firebase notification and if I tap on it, app opens and my own notification pops up after that

**Comment by KEYHAN-A** [comment]
I should have pass data payload instead of message.

**Comment by bliulin** [comment]
Hi @KEYHAN-A , do you mean to pass a message with "data" field in it? I.e., something like this?

`{"foreground":true,"from":"1054843449","body":"data message","data":{"key1":"1","key2":"2"}}`

Does this make any difference in whether or not the plugin shows the notification on Android? I'm having the same issue, that a notification is shown even though I set `showNotifications: false` in the init method.

**Comment by KEYHAN-A** [comment]
Hi @bliulin ,
below is the data format for Firebase payloads,
```
var payload = {
  notification: {
    title: "Account Deposit",
    body: "A deposit to your savings account has just cleared."
  },
  data: {
    account: "Savings",
    balance: "$3020.25"
  }
}
```
you can pass data/notification,
if you have a notification property, it's going to push direct notification,
but if you just push data like this:
```
var payload = {
  data: {
    account: "Savings",
    balance: "$3020.25"
  }
}
```
it's not going to push notification, you can trigger/fire some functionality on your own,
but the thing was I couldn't exactly figure out the functions in the background,
I think when it gets the data, triggers the function, but runs it when you open the app to the foreground.

hope this helps you! ;)

**Comment by bliulin** [comment]
Hi @KEYHAN-A ,

This is a great insight. Indeed, I confirm that if you don't put the notification section in the message, Android does not show a notification.

What I notice is that:
a. If the app is running in the background and a data message is received, then the `addOnMessageReceivedCallback ` gets called.
b. If the app is not running and a message is sent, the addOnMessageReceivedCallback will get called once the app is running again (provided that the message is not expired).

Thank you!

**Comment by krthush** [comment]
Yeah following up on this, I found the same issue as @bliulin ...

Do you guys know of any way of being able to use the Nativescript-local-notification plugin even when the app is closed?

I need to be able to use buttons/inputs on my notifications and the basic google FCM notification doesn't allow for this on Android. I thought I found my solution when trying to use the local-notification plugin, but I can't have it not working when the app is closed - i.e. I need to be able to notify my user with iteractive notifications even if the app is closed.

**Comment by Ot92** [comment]
Same use case as @krthush. So +1
