### ISSUE TITLE
How to exclude unused firebase components

### ISSUE THREAD

**Issue by dlcole** [EddyVerbruggen/nativescript-plugin-firebase#1446]
I've added firebase auth, messaging, and realtime db to my app.  Everything works fine, but I've noticed ALL the firebase components are included in the build, conspicuously so on iOS.  I've uninstalled and reinstalled the iOS platform and the firebase plugin.  firebase.nativescript.json looks accurate: 

```
{
    "using_ios": true,
    "using_android": true,
    "analytics": false,
    "firestore": false,
    "realtimedb": true,
    "authentication": true,
    "remote_config": false,
    "performance_monitoring": false,
    "external_push_client_only": false,
    "messaging": true,
    "in_app_messaging": false,
    "crashlytics": false,
    "storage": false,
    "functions": false,
    "facebook_auth": false,
    "google_auth": false,
    "admob": false,
    "dynamic_links": false,
    "ml_kit": false
}
```
When I build the project I see this: 

```
nativescript-plugin-firebase: running release build or change in environment detected, forcing prepare!
Installing pods...
Analyzing dependencies
Downloading dependencies
Installing Firebase (6.10.0)
Installing FirebaseAnalyticsInterop (1.4.0)
Installing FirebaseAuth (6.3.0)
Installing FirebaseAuthInterop (1.0.0)
Installing FirebaseCore (6.3.1)
Installing FirebaseCoreDiagnostics (1.1.1)
Installing FirebaseCoreDiagnosticsInterop (1.0.0)
Installing FirebaseDatabase (6.1.1)
Installing FirebaseInstanceID (4.2.5)
Installing FirebaseMessaging (4.1.6)
Installing GTMSessionFetcher (1.2.2)
Installing GoogleDataTransport (3.0.1)
Installing GoogleDataTransportCCTSupport (1.2.1)
Installing GoogleMaps (3.5.0)
Installing GoogleUtilities (6.3.1)
Installing MDFInternationalization (2.0.0)
Installing MaterialComponents (84.6.0)
Installing Protobuf (3.10.0)
Installing leveldb-library (1.22)
Installing nanopb (0.3.901)
Generating Pods project
```
And then, when I do Xcode build, I see the various frameworks included: 

![image](https://user-images.githubusercontent.com/11671244/67488514-f37cef80-f63d-11e9-9a9d-f08fefbd057a.png)

(I'm not using crashlytics or mlkitcamera). 

So, how do I exclude the unused components from my app?

**Comment by EddyVerbruggen** [comment]
I understand the issue but it’s not as bad as you might think. I’ll explain when I’m behind a computer again.

**Comment by EddyVerbruggen** [comment]
So any library prefixed `TNS` here is not a Firebase library, but a tiny helper library added by either this plugin (`TNSMLKitCamera`) or NativeScript (`TNSCrashlyticsLogger`). Those are part of your app regardless your Firebase config.

That being said, I should make that `TNSMLKitCamera` lib optional, depending on whether or not you selected the MLKit feature. But like I said, it's a very tiny lib.

**Comment by dlcole** [comment]
@EddyVerbruggen - thanks for the clarification!  That helps to know that what's being included isn't to big.

**Comment by EddyVerbruggen** [comment]
I'm going to release 10.1.1 shortly, which will no longer link those frameworks if not used.
