### ISSUE TITLE
Adaptation of Firebase MlKit dosen't works with iOS 9

### ISSUE THREAD

**Issue by bartoszekj** [EddyVerbruggen/nativescript-plugin-firebase#1452]
Hello.
I tried to use the library but your code doesn't work with iOS 9.
The problem is in the function canUseCamera. I receive info 

> here's no Camera on this device :(

I found the information that the "AVCaptureDeviceDiscoverySession" is supported from iOS 10. 
Is any hope to implementation support for the oldest ios?

**Comment by EddyVerbruggen** [comment]
Yeah that class seems to be required so I added a note to the ML Kit docs. Perhaps there would be a way to support the camera stream on iOS 9 but I have no device to test any changes I'd make.

Btw, I think if you would not use the camera, but still images instead, you could perhaps use ML Kit features.
