### ISSUE TITLE
Sending Data Messages without notification key.

### ISSUE THREAD

**Issue by Edujugon** [EddyVerbruggen/nativescript-plugin-firebase#146]
When I send a push notification without notification key the app crashes. If I add the notification key, it works like a charm.

below is the error log I get:
`
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.firebase.messaging.RemoteMessage$Notification.getTitle()' on a null object reference
org.nativescript.plugins.firebase.MyFirebaseMessagingService.onMessageReceived (MyFirebaseMessagingService.java:21)
com.google.firebase.messaging.FirebaseMessagingService.zzo ()
com.google.firebase.messaging.FirebaseMessagingService.zzn ()
com.google.firebase.messaging.FirebaseMessagingService.zzm ()
com.google.firebase.iid.zzb$2.run ()
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1113)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:588)
java.lang.Thread.run (Thread.java:818)
`

(In data keys there are title and body)

Should I always send Notification Messages instead of Data Message?

Thanks in advance.

**Comment by EddyVerbruggen** [comment]
Thanks for that clear bugreport and the stacktrace!

I've just updated the master branch of this repo with a changed Android implementation where we can deal with `null` notifications - so after an update your workaround would no longer be needed.

Will be part of the next npm release of course.

Can you test it to make sure?

**Comment by Edujugon** [comment]
Now, it seems the app doesn't crash but I don't get any notification..
Are you checking for title and body from the data payload? or  doesn't it have any of those values?

I'm sending those values (title and body) as Data Message keys...
What about if I don't send those keys at all? do you set something by default?

**Comment by EddyVerbruggen** [comment]
Hmm, it's [this piece of code](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/platforms/android/libraryproject/firebase/src/main/java/org/nativescript/plugins/firebase/MyFirebaseMessagingService.java#L19-L34). What you describe should work.

**Comment by Edujugon** [comment]
What I understand from your code is that try to take the title and the body from the notification.
But if there isn't a notification, it doesn't try to take the title and body from the data..

Maybe after confirm that notification is null you could check if data has those values and if so, then take them like

json.put("title", data.getTitle())
          .put("body", data.getBody());

What do you think?

**Comment by EddyVerbruggen** [comment]
That's what [this piece of code](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/platforms/android/libraryproject/firebase/src/main/java/org/nativescript/plugins/firebase/MyFirebaseMessagingService.java#L29-L32) is supposed to do. It's a map so there's not `getTitle` etc.

What would be an easy way for me to reproduce your notification?

**Comment by Edujugon** [comment]
Oh, that's correct. I didn't see those lines..
Let me do some more tests from my side and I'll update you. May be there is something wrong at my end..

**Comment by Edujugon** [comment]
I'm doing some tests and when sending the notification without notification key, I don't receive anything on my device.

That is what I send:
```
array (
  'priority' => 'normal',
  'dry_run' => false,
  'data' => 
  array (
    'title' => 'title',
    'body' => 'subtitle',
    'sound' => 'default'
  )
```
I get a successful response from FCM server:
```
{"multicast_id":8646166671199375786,"success":4,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1475588262916178%76d52ec2f9fd7ecd"},{"message_id":"0:1475588262916945%76d52ec2f9fd7ecd"},{"message_id":"0:1475588262915324%76d52ec2f9fd7ecd"},{"message_id":"0:1475588262923838%76d52ec2f9fd7ecd"}]}
```

Now, when sending the following:
```
array (
  'priority' => 'normal',
  'dry_run' => false,
  'data' => 
  array (
    'text' => 'Lorem ipsum',
    'extraPayload' => 'whatever'
  ),
  'notification' => 
  array (
    'title' => 'title',
    'body' => 'subtitle',
    'sound' => 'default',
  )
```

This time I got the notification on my device. and again a successful response form FCM server
```
{"multicast_id":5271419661157049325,"success":4,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1475588379148808%76d52ec276d52ec2"},{"message_id":"0:1475588379148585%76d52ec276d52ec2"},{"message_id":"0:1475588379170929%76d52ec276d52ec2"},{"message_id":"0:1475588379149438%76d52ec276d52ec2"}]}
```
Any idea why can it be happening?

**Comment by dbenninger** [comment]
I have the same issue on iOS. A push notification without notification structure crashes the app:

***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x1012f37b4 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
2   0x101b7f2dc ffi_closure_SYSV_inner
3   0x101b801b4 .Ldo_closure
4   0x10021995c -[FIRMessagingReceiver scheduleIos10NotificationForMessage:withIdentifier:]
5   0x1002194ec -[FIRMessagingReceiver didReceiveMessage:withIdentifier:]
6   0x100211a60 -[FIRMessagingDataMessageManager didReceiveParsedMessage:]
7   0x10020c148 -[FIRMessagingClient connectionDidRecieveMessage:]
8   0x10020ec84 -[FIRMessagingConnection didReceiveDataMessageStanza:]
9   0x10020df14 -[FIRMessagingConnection secureSocket:didReceiveData:withTag:]
10  0x10021e98c -[FIRMessagingSecureSocket processCurrentInputBuffer:outOffset:]
11  0x10021e720 -[FIRMessagingSecureSocket performRead]
12  0x10021e0cc -[FIRMessagingSecureSocket stream:handleEvent:]
13  0x1858fea94 <redacted>
14  0x1859098fc <redacted>
15  0x1858fe5b8 <redacted>
16  0x1860c9bc8 <redacted>
17  0x1860cf724 <redacted>
18  0x1860cb2f8 <redacted>
19  0x185967a70 <redacted>
20  0x185962b5c <redacted>
21  0x1859624a4 <redacted>
22  0x1859600a4 <redacted>
23  0x18588e2b8 CFRunLoopRunSpecific
24  0x187342198 GSEventRunModal
25  0x18b8d57fc <redacted>
26  0x18b8d0534 UIApplicationMain
27  0x101b80044 ffi_call_SYSV
28  0x101b7ee1c ffi_call_int
29  0x101b7e934 ffi_call
30  0x1012b54fc NativeScript::FFICall::call(JSC::ExecState*)
31  0x1018e9890 JSC::LLInt::setUpCall(JSC::ExecState*, JSC::Instruction*, JSC::CodeSpecializationKind, JSC::JSValue, JSC::LLIntCallLinkInfo*)


To reproduce:
1. Setup test app with messaging
2. This works: curl -X POST --header "Authorization: key=SERVER_KEY" --Header "Content-Type: application/json" https://fcm.googleapis.com/fcm/send -d "{\"notification\":{\"title\": \"My title\", \"text\": \"My text\", \"sound\": \"default\"}, \"data\":{\"foo\":\"bar\"}, \"priority\": \"High\", \"to\": \"DEVICE_TOKEN\"}"
3. This crashes the app: curl -X POST --header "Authorization: key=SERVER_KEY" --Header "Content-Type: application/json" https://fcm.googleapis.com/fcm/send -d "{\"data\":{\"foo\":\"bar\"}, \"priority\": \"High\", \"to\": \"DEVICE_TOKEN\"}"
