### ISSUE TITLE
Firestore - Paginate data with query cursors

### ISSUE THREAD

**Issue by milansar** [EddyVerbruggen/nativescript-plugin-firebase#1469]
As Per Firestore [readme](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/FIRESTORE.md) Paginate data with query cursors is supported and it should work same as document on [Web](https://firebase.google.com/docs/firestore/query-data/query-cursors)

It appears Plugin only works with document snapshot to define query cursor , even example given in readme is for document Snapshot. A simple cursor to a query is not working
Example citiesRef.orderBy("population").startAt(1000000)

When as argument anything other than snapshot is given application throw error **"Provided snapshot must not be null."**. This happen because plugin assume that snapshot is provided and try to convert that to native snapshot on this [line ](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/fdb58634d3f65bef3c5129f51276a13e5df7d955/src/firebase.android.ts#L2583)

```
firebase.firestore.startAt = (collectionPath: string, snapshot: DocumentSnapshot, query: com.google.firebase.firestore.Query): firestore.Query => {
  return firebase.firestore._getQuery(collectionPath, query.startAt(snapshot.android));
};
```
as JavaScript does not have overloaded methods , tried to change directly generated javascript file with following code 
```
firebase_common_1.firebase.firestore.startAt = function (collectionPath, snapshot, query) {
    return firebase_common_1.firebase.firestore._getQuery(collectionPath, query.startAt(snapshot.android ? snapshot.android :  snapshot);
};
```
This gives Following error

> java.lang.Exception: Failed resolving method startAt on class com.google.firebase.firestore.Query
> System.err:     at com.tns.Runtime.resolveMethodOverload(Runtime.java:1245)       
> System.err:     ... 20 more

Looking into Firebase Android-SDK code and official documentation, it is clear startAt has two overloaded [methods with different signature](https://github.com/firebase/firebase-android-sdk/blob/405d287a34c488cd53b7c9ea21a0a00406cc0529/firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java#L601)

**Not sure why it is not able to resolve to second signature when value of snapshot is just string** 
**What is correct way to implement it in plugin so everyone can get benefit out of this?** 

Any help on this Highly appreciated

**Comment by EddyVerbruggen** [comment]
The plugin was created to use a snapshot as you found out. I've never tested your kind of usage, and perhaps those overloaded methods were even added after I implemented this. So this is feature request. Are you willing to attempt doing a PR?

**Comment by milansar** [comment]
I am for than happy to to attempt doing a PR, at this point I am just stuck on why overloaded method is not being called when I am not passing snapshot 

Just to give you some background on why I feel second overloaded method of startAt is more important then snapshot.

Second overloaded method is required for **Geo query** (near by, radius search etc...) using **GeoHash** implementation.  I guess doing near by search should be very common use case.

I cam across this issue as I tried to use [GeoFirestore-JS ](https://github.com/geofirestore/geofirestore-js), This library is intended for web use but with only one tweak I could make it compatible with the plugin which is great :-).  Only problem is its near function depend on startAt second overloaded method.

Could this be native firebase SDK needs to be updated to support second overloaded method? I am investing on that

**Comment by milansar** [comment]
@EddyVerbruggen 
Update:
I figured Marshaling issue and changed code for Android. Now it works for Android.
here is snippet of hacked generated javascript code 

```
firebase_common_1.firebase.firestore.startAt = function (collectionPath, snapshot, query) {
    if(snapshot.android) {
        return firebase_common_1.firebase.firestore._getQuery(collectionPath, query.startAt(snapshot.android));
    } else {
        const list = Array.create('java.lang.Object',1);
        list[0] = new java.lang.String(snapshot);
        return firebase_common_1.firebase.firestore._getQuery(collectionPath, query.startAt(list));
    }    
};
```

Now I understand what needs to be done to make it compatible with Geforce-JS library.  I will make changes and create pull request after testing for ios as well

let me know if you have any thoughts on how it should be implemented

**Comment by EddyVerbruggen** [comment]
Hi @milansar I don't mind too much about a hacky solution as long as it works reliably.

For iOS the situation is much easier; there's `queryStartingAtDocument` (which I currently use) and `queryStartingAtValues` (which you'll need).

Btw, similar implementations are possible for startingAfter, endingAt, etc.

Happy to merge a PR!

Happy to merge a PR!

**Comment by milansar** [comment]
Thanks @EddyVerbruggen 

I figured that.  in end ios was much easier to support compare to Adnroid ;-). I was scared with ios

created [PR](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/pull/1476)

Thanks for awesome plugin

**Comment by EddyVerbruggen** [comment]
Yeah as a guy with a Java background I can relate, but I usually have an easier time with iOS as well ;)

Thanks a lot! I'll try to review and merge it tomorrow.

**Comment by EddyVerbruggen** [comment]
@milansar Thanks a lot! I didn't test the new features, but after a little fix on Android the old implementation works nicely. So I'm happy and I'll release this in a second.

**Comment by milansar** [comment]
> @milansar Thanks a lot! I didn't test the new features, but after a little fix on Android the old implementation works nicely. So I'm happy and I'll release this in a second.

Thanks @EddyVerbruggen ,

I figured issue I created. Somehow after doing refactor I missed to test original function on Android hence broken original function. Sorry about that

**Comment by EddyVerbruggen** [comment]
No worries mate, it was an easy fix. Thanks for your contribution!

**Comment by milansar** [comment]
Thanks @EddyVerbruggen 

created another [pull ](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/pull/1486) request, not so much of functionality  change but code improvement in terms of readability and kind of support all types supported by fire store

should integrate when you get time
