### ISSUE TITLE
Error logging in

### ISSUE THREAD

**Issue by jahidshohel** [EddyVerbruggen/nativescript-plugin-firebase#147]
I am on OSX and running my NS app on iOS emulator. 

**Type script version**: 2.0.3
**Native script version**: 2.3.0
**nativescript-plugin-firebase version**: ^3.6.3

Problem: 
---------
When I try to login -

> firebase.login({
         type: firebase.LoginType.ANONYMOUS
    })
            .then((user)=> {
                console.log("created new userrrrrrr", user);
            }, (reason)=> {
                console.log("errrrrrrorrrrr", reason);
            });

After trying anonymous login, I can see on my firebase console that an anonymous account has been created, but on application it throws an error, and the log looks like -

> Oct  2 23:59:55 contourmobile[11077]: CONSOLE LOG file:///app/components/tabs/tab2/tab2.component.js:26:24: errrrrrrorrrrr An error occurred when accessing the keychain. The @c NSLocalizedFailureReasonErrorKey field in the @c NSError.userInfo dictionary will contain

Also, below given error message keep printing on console -

> Oct  2 23:59:54 contourmobile[11077]: CONSOLE LOG file:///app/components/tabs/tab2/tab2.component.js:19:20: trying to loginnnnn
Oct  2 23:59:54 contourmobile[11077]: [] nw_host_stats_add_src recv too small, received 24, expected 28
Oct  2 23:59:54 --- last message repeated 4 times ---
Oct  2 23:59:54 contourmobile[11077]: [] __nwlog_err_simulate_crash simulate crash already simulated "nw_socket_set_common_sockopts setsockopt SO_NOAPNFALLBK failed: [42] Protocol not available"
Oct  2 23:59:54 contourmobile[11077]: [] nw_socket_set_common_sockopts setsockopt SO_NOAPNFALLBK failed: [42] Protocol not available, dumping backtrace:
	        [x86_64] libnetcore-856.1.8
	    0   libsystem_network.dylib             0x000000010750a80e __nw_create_backtrace_string + 123
	    1   libnetwork.dylib                    0x00000001084fb194 nw_socket_add_input_handler + 3002
	    2   libnetwork.dylib                    0x00000001084d8db8 nw_endpoint_flow_attach_protocols + 3768
	    3   libnetwork.dylib                    0x00000001084d7dd5 nw_endpoint_flow_setup_socket + 563
	    4   libnetwork.dylib                    0x00000001084d6b34 -[NWConcrete_nw_endpoint_flow startWithHandler:] + 2612
	    5   libnetwork.dylib                    0x00000001084f1d11 nw_endpoint_handler_path_change + 1261
	    6   libnetwork.dylib                    0x00000001084f1740 nw_endpoint_handler_start + 570
	    7   libnetwork.dylib                    0x0000000108509003 nw_endpoint_resolver_start_next_child + 2240
	    8   libdispatch.dylib                   0x000000
Oct  2 23:59:55 securityd[8279]: found no keychain client entitlements. task=contourmobile[11077]/1#-1 LF=0 procid=org.nativescript.Contour cs_flags=0x02000201

**Comment by EddyVerbruggen** [comment]
Hi, see the readme. Look for keychain sharing.
