### ISSUE TITLE
Android googleSignInResult can be null and crash the app

### ISSUE THREAD

**Issue by jpierront** [EddyVerbruggen/nativescript-plugin-firebase#1473]
Hello,

Crashlytics report a lot of "Cannot read property 'isSuccess' of null" while android google sign in. (Just after `screen_view firebase_screen_class: SignInHubActivity`)

It seems that `const googleSignInResult = com.google.android.gms.auth.api.Auth.GoogleSignInApi.getSignInResultFromIntent(eventData.intent);` can be null and crash on `googleSignInResult.isSuccess();` call.

I still can't reproduce it but it often comes back in Crashlitics on several Android versions (6, 7, 8, 9).

**Comment by EddyVerbruggen** [comment]
Hi, please submit a PR if you know which line causes it.

**Comment by jpierront** [comment]
It should avoid app crash, but it doesn’t explain why it’s happening.

Android API doc explains that it happen when we provide the wrong Intent to the getSignInResultFromIntent method. But I do not understand why this happens ... and only occasionally.

https://developers.google.com/android/reference/com/google/android/gms/auth/api/signin/GoogleSignInApi.html#public-abstract-googlesigninresult-getsigninresultfromintent-intent-data
