### ISSUE TITLE
Implementing missing callback function for Ads

### ISSUE THREAD

**Issue by abozanona** [EddyVerbruggen/nativescript-plugin-firebase#1475]
It'd be great if the plugin implements the `onAdClicked`, `onAdClosed`, `onAdLeftApplication`, `onAdOpened` [callbacks](https://developers.google.com/android/reference/com/google/android/gms/ads/AdListener).

**Comment by EddyVerbruggen** [comment]
Hi, great idea. I've added the events as far as they are applicable for both platforms and depending on the type of ad (banner, interstitial, rewarded video ad).
