### ISSUE TITLE
Pass custom metadata to "uploadFile()" function.

### ISSUE THREAD

**Issue by comemanu** [EddyVerbruggen/nativescript-plugin-firebase#1478]
I can't find a way to pass custom metadata to the uploadFile method.

it should be possible : 
android : 
https://firebase.google.com/docs/storage/android/file-metadata#custom_metadata
ios : 
https://firebase.google.com/docs/storage/ios/file-metadata#custom_metadata

**Comment by EddyVerbruggen** [comment]
Hi! Thanks for the request.

I just implemented it and it will be part of the 10.3.3 release.

**Comment by EddyVerbruggen** [comment]
released to npm
