### ISSUE TITLE
how to use firestore with firebase native api

### ISSUE THREAD

**Issue by Xatta-Trone** [EddyVerbruggen/nativescript-plugin-firebase#1481]
Hi.. I am trying to use firebase firestore after creating a user. 
It seems that the firestore is only for the web api !!! 
How to use it in native api ? 
or if there is a way around please let me know.

**Comment by EddyVerbruggen** [comment]
What native API do you mean? Is there anything you're missing in the README? Please check the `demo-ng` folder for examples.

**Comment by Xatta-Trone** [comment]
Yap..my bad..didn't noticed. 
Btw thank you for this awesome plugin. :D
