### ISSUE TITLE
How to get a generated key doing a push ?

### ISSUE THREAD

**Issue by sflament** [EddyVerbruggen/nativescript-plugin-firebase#15]
Hope, i don't bother you with too simple question.

With the firebase.js library, I can  get the full path to the new object, including the key at the end

For example

``` js
function createNode(myref, title, owner) {
    return myref.push({ title : title, owner : owner});
}

...
mypath = createNode (myurl, "foo", "paul");
mykey = mypath.ref().

```

How can I get the new generated key with the plugin ?

``` js
    function CreateNode(myref, title, owner) {
       result = firebase.push(myref, { title : title, owner : owner});
       return result;
    }
```

result seems to be void (the push is correctly done)

Regards,

**Comment by Nikoms** [comment]
`
firebase.push({...}).then(
      function (result) {
        console.log("generated key: " + result.key);
      }
  );
`

**Comment by ZionInc** [comment]
#492
