### ISSUE TITLE
Can' t display the push notification pop-up

### ISSUE THREAD

**Issue by moreaup** [EddyVerbruggen/nativescript-plugin-firebase#150]
Hi,

I was testing your plugin and put every thing in place to make it work.
Actually it's working, I can display the received notification with an alert like this : 

```
firebase.addOnMessageReceivedCallback(
    function(message) {
        alert(JSON.stringify(message));
    }
);

firebase.init({
  // Optionally pass in properties for database, authentication and cloud messaging,
  // see their respective docs.
}).then(
  (instance) => {
    console.log("firebase.init done");
  },
  (error) => {
    console.log("firebase.init error: " + error);
  }
);
```

But except my alert I can' t see any pop-up showing me that I received this notification.
I'm clearly missing something but I can't figure out.
Do you have an idea ? 

Thanks !

**Comment by charlou28** [comment]
+1

**Comment by hvadotnarola** [comment]
@moreaup You mean you're not getting notification when app is in background OR killed ?

**Comment by moreaup** [comment]
@hvadotnarola  Hi finally did it thanks, I needed to change a lot of things.

Do you know how to send notifications to all user using the application with curl ?

**Comment by hvadotnarola** [comment]
Yes sure, Can you help me with how did you resolve notification problem ?

```
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $url);//$url = 'https://fcm.googleapis.com/fcm/send';
curl_setopt($ch, CURLOPT_POST, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($fields));//$$fields is array of message or Payload

$result = curl_exec($ch);
if ($result === FALSE) {
die('Problem occurred: ' . curl_error($ch));
}

curl_close($ch);`
```

**Comment by hvadotnarola** [comment]
@moreaup can you share what payload you're sending for iOS ?

**Comment by moreaup** [comment]
Here is my package.json in my app folder:
```
{
    "private": false,
    "nativescript": {
        "id": "org.nativescript.myApp"
    },
    "name": "myApp",
    "main": "main.js",
    "version": "2.3.0",
    "author": "Happty",
    "description": "My app",
    "license": "BSD",
    "keywords": [
        "telerik",
        "mobile",
        "angular",
        "nativescript",
        "{N}",
        "tns",
        "appbuilder",
        "template"
    ],
    "android": {
        "v8Flags": "--expose_gc"
    },
    "dependencies": {
        "nativescript-angular": "1.0.0",
        "@angular/core": "2.0.0",
        "@angular/common": "2.0.0",
        "@angular/compiler": "2.0.0",
        "@angular/http": "2.0.0",
        "@angular/platform-browser": "2.0.0",
        "@angular/platform-browser-dynamic": "2.0.0",
        "@angular/platform-server": "2.0.0",
        "@angular/forms": "2.0.0",
        "@angular/router": "3.0.0",
        "reflect-metadata": "^0.1.8"
    },
    "devDependencies": {
        "zone.js": "^0.6.21",
        "nativescript-dev-typescript": "^0.3.2"
    }
}
```

To resolve the notification problem I added my certificate on the firebase platform and I put the right nativescript id to my app. Stupid mistakes.

I can send my notifications to all user using the firebase platforms, but I don't know how to do that with curl. Currently I can send to one user at a time using this : 

`curl -X POST --header "Authorization: key=SERVER_KEY" --Header "Content-Type: application/json" https://fcm.googleapis.com/fcm/send -d "{\"notification\":{\"title\": \"My title\", \"text\": \"My text\", \"sound\": \"default\"}, \"priority\": \"High\", \"to\": \"DEVICE_TOKEN\"}"`

I don't know how to replace the `\"to\": \"DEVICE_TOKEN\"` with  `\"to\": \"ALL_DEVICE\"`

**Comment by hvadotnarola** [comment]
@moreaup is this plugin compatible with core module 2.0.0 ? i am using 2.3.0 but app is crashing in device. do you know how can i debug app or know reason for crash? Tried commenting out code for firebase but problem is still existing.

**Comment by EddyVerbruggen** [comment]
For folks having trouble with notifications on iOS please check the current version in GitHub (not released to npm yet).

My CURL command:

```
curl -X POST --header "Authorization: key=XXXXyATZvM7wUbT3vlQFHeBhHglVGIPj1OQMJ4" --Header "Content-Type: application/json" https://fcm.googleapis.com/fcm/send -d "{\"notification\":{\"title\": \"My title\", \"text\": \"My text\", \"sound\": \"default\"}, \"data\":{\"foo\":\"bar\"}, \"priority\": \"High\", \"to\": \"XXXXGzudbM:APA91bG4UDu62ZOUf_W8rw7scMTn643_P-hO2QF2eMJtBI2pu5eHKsryJ4xchSwWgEX3MYfj3z1BeRm7jftKs1KJRlwnYKkb-v9DvFguNi6Dh_0-LT3W4dTJNMIPYoMUhKiLuIg5x5be\"}"
```
