### ISSUE TITLE
RawValue is the only value returned by Barcode scan

### ISSUE THREAD

**Issue by andreacappadona17** [EddyVerbruggen/nativescript-plugin-firebase#1506]
I needed to use the displayValue because it trims out check characters, and it would be useful to add it to the returned properties.

Check the [docs](https://firebase.google.com/docs/ml-kit/ios/read-barcodes?authuser=0#3.-get-information-from-barcodes) for reference.

Thank you.

**Comment by EddyVerbruggen** [comment]
Nice one. Added in 10.3.1.
