### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by Arystosedes** [EddyVerbruggen/nativescript-plugin-firebase#1509]
Hi, not sure what happened, but since yesterday my app not working locally (webapp working properly). If I try to log in  (using firebase.login or firebaseWebApi.auth().signInWithEmailAndPasswor) there is no response from API (neither response or error). I though it's something with my App, so I created the new one (simple app only to test login) with the same result. 

This can be related with last commits? :/ Any idea? When I debugging I see that there are zero requests to firebase api from my app :/ It is like login function is not fired, but it's not possible. The same behaviour when I try to reset passowrd or createUserWithEmailAndPassword. No requests, no response.

Another test. When I back to the previous (working) version of my app, the result is the same.

**Comment by EddyVerbruggen** [comment]
If it’s related to the plugin then please consider pinning your versions in package.json more aggressively.

**Comment by Arystosedes** [comment]
"tns-android": {
      "version": "6.3.0-2019-11-19-150236-01"
    }

"nativescript-plugin-firebase": "^10.2.0",

**Comment by EddyVerbruggen** [comment]
The demo app in this repo is working just fine, but I may find a minute or 2 to look at your repo if you can share it with exact instructions..

**Comment by Arystosedes** [comment]
After almost the whole day I fixed that problem. It wasn't a problem with the plugin or my code, but with android sdk instance of a mobile device. I added a new device, and now it's working.. ;) Anyway, thx for help!
