### ISSUE TITLE
login() promise for Apple Sign In is not resolved or rejected

### ISSUE THREAD

**Issue by tkrevh** [EddyVerbruggen/nativescript-plugin-firebase#1512]
TNS Android 6.2.0, nativescript-plugin-firebase@10.3.1

Trying Apple Sign in, in its simplest form:
```
     firebase.login({type: firebase.LoginType.APPLE})
          .then(
               result => console.log('result=', JSON.stringify(result)),
               error => console.log('error=', error)
          ).catch(e => console.log('e=', e))
```

It opens up a browser with apple sign in, asks for apple id and password, proceeds to confirmation screen "Do you want to continue using AppName with your Apple ID email@email.com?" 
After tapping on continue there is some processing for about 0.5sec, then the browser closes and promise doesn't resolve or reject.

Any ideas what could be wrong?

In case it is important - Google Auth works normally.

**Comment by tkrevh** [comment]
Could it be, that this [line](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/caea362356a53185f40c4f0717b565d811dd014e/src/firebase.android.ts#L1075) is missing a resolve?
`resolve(toLoginResult(authResult.getUser(), authResult.getAdditionalUserInfo()));`

**Comment by tkrevh** [comment]
Same problem occurs also on iOS. Neither resolve or reject of Promise is called.
Any way to get this fixed please @EddyVerbruggen ?

**Comment by tkrevh** [comment]
Ahhh... Spent 2 days on this iOS issue. Tried everything, to no avail. Sometimes the promise wasn't resolved / delegate method authorizationControllerDidCompleteWithAuthorization wasn't invoked.
Then finally I started suspecting garbage collection. And after some tinkering and googling, I ran across this [issue](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/396).

I've submitted a [PR](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/pull/1516) for this. Can you please include this PR and release a new version? It is currently blocking new app submission to Apple App Store. Thank you @EddyVerbruggen 🥇

**Comment by EddyVerbruggen** [comment]
Absolutely, thank you!

**Comment by tkrevh** [comment]
You're the best, thank you for such quick response and release 🥇 
Now keeping fingers crossed for apple app review...
