### ISSUE TITLE
[Issue] - Not receiving notification on IOS in both foreground and background 

### ISSUE THREAD

**Issue by zhitomir-oreshenski-mm** [EddyVerbruggen/nativescript-plugin-firebase#1513]
Hi @EddyVerbruggen,

I am following up on your recommendation and won't be able to receive push notifications both on fore- and background.

Versions are following:

  "nativescript": {
    "id": "com.testpush.application",
    "templateVersion": "v2",
    "tns-android": {
      "version": "6.2.0"
    },
    "tns-ios": {
      "version": "6.2.0"
    }
  },
  "dependencies": {
    "nativescript-plugin-firebase": "^10.3.1",
    "nativescript-vue": "^2.4.0",
    "tns-core-modules": "^6.0.0"
  },

Partial code snippet here:

const firebase = require("nativescript-plugin-firebase");

firebase
  .init({
    showNotifications: true,
    showNotificationsWhenInForeground: true,
    iOSEmulatorFlush: true,
    autoClearBadge: false,

    onPushTokenReceivedCallback: token => {
      console.log("[Firebase] onPushTokenReceivedCallback:", { token });
    },

    onMessageReceivedCallback: message => {
      console.log("[Firebase] onMessageReceivedCallback:", { message });
    }
  })
  .then(() => {
    console.log("[Firebase].init done");
  })
  .catch(error => {
    console.log("[Firebase].init error", {
      error
    });
  });

Vue.prototype.$firebase = firebase;

Project: Vue with nativescript
Repository: https://github.com/zhitomir-oreshenski-mm/push-notifications

Would you please be so kind to check if I am doing something wrong there?

Best regards,
Zhi

**Comment by EddyVerbruggen** [comment]
First thing I notices is you're missing the entitlements file: https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/MESSAGING.md#copy-the-entitlements-file

After adding that and doing a clean build please use the CURL command in the same readme to send a notification. If that doesn't work please log the command and its response here.

**Comment by zhitomir-oreshenski-mm** [comment]
Hi EddyVerbruggen,

Thank you for your response.

I've managed to fix it after adding .p8 certificate & TeamID into firebase regarding IOS issue.

Have a nice weekend ahead ! :)

Best regards,
Zhi
