### ISSUE TITLE
Device Id in Simulator but not in real Device

### ISSUE THREAD

**Issue by hvadotnarola** [EddyVerbruggen/nativescript-plugin-firebase#152]
Hi,

I have installed plugin and running project with CLI.
Now when running application with `$ tns run ios --emulator` firebase is getting initialized but when creating build with `$ tns build ios --for-device` firebase isn't getting initialized successfully and also no error.

Let me know if i am doing anything wrong

P.S. I am using Firebase for Cloud messaging. Setting certificates and Provision Profiles with xCode 7.2 and running, building with CLI. 
>Device : iPhone 5  9.3.5, Simulator : iPhone 6 9.2

**Comment by macismail2003** [comment]
Did you manage to resolve this? Thank you.
