### ISSUE TITLE
Add revoke auth token

### ISSUE THREAD

**Issue by dosomder** [EddyVerbruggen/nativescript-plugin-firebase#1525]
The firebase api allows to revoke tokens for a specific user. Could you add this? See link: https://firebase.google.com/docs/auth/admin/manage-sessions#revoke_refresh_tokens

**Comment by EddyVerbruggen** [comment]
You linked to the admin SDK. Is there something similar for iOS and Android in the docs?

**Comment by dosomder** [comment]
Ah sorry, doesn't seem to have anything for iOS and Android. So revoking needs to be done from the server.

**Comment by EddyVerbruggen** [comment]
No worries, thanks for checking!
