### ISSUE TITLE
Cannot read property "PASSSWORD" of undefined

### ISSUE THREAD

**Issue by leocrawf** [EddyVerbruggen/nativescript-plugin-firebase#1535]
When I try to run a reauthenticate I am getting an error. Here is my code:

     const firebaseWebApi = require("nativescript-plugin-firebase/app");

     viewModel.reauthenticate = (email,currentPassword,newPassword) => {

        return firebaseWebApi.reauthenticate({
            type: firebaseWebApi.LoginType.PASSWORD, 
            passwordOptions: {
                email: email,
                password: currentPassword
            }
        }).then(
            function (result) {
                return viewModel.updatePassword(newPassword)
            },
            function (error) {
              return error
            }
        );
      }   

everything else works in the firebase plugin. I got the code from the reauthentication section of the docs here: https://github.com/eddyverbruggen/nativescript-plugin-firebase/blob/HEAD/docs/AUTHENTICATION.md

**Comment by leocrawf** [comment]
Thank you, I was able to fix the issue upon observing your response.

**Comment by adekunle11** [comment]
@EddyVerbruggen hello, whenever i add nativescript-plugin-firebase to my app. it crashes when i try to open the app on my phone. samsung s7 edge.

my plugin version is 10.3.3
im using windows 10
