### ISSUE TITLE
[Android] Push notifications does not appears when close app. 

### ISSUE THREAD

**Issue by adahox** [EddyVerbruggen/nativescript-plugin-firebase#1539]
[ANDROID]
"nativescript-angular": "^8.20.0"
"tns-core-modules": "^6.2.0"

I have tested my push notifications and i've see the push notifications does not show when my app is closed. only foreground or minimized. has someway to change this? i used `showNotificationsWhenInForeground: true,` but it does not work too. Seems work only on IOS.

Have someone same problem?

**Comment by dosomder** [comment]
I have the same problem. Looks like the entry point of the app is called (wake up) but the `onMessageReceivedCallback` not.
