### ISSUE TITLE
Conflict with nativescript-fresco

### ISSUE THREAD

**Issue by marcbuils** [EddyVerbruggen/nativescript-plugin-firebase#154]
Hi,

My app use nativescript-fresco plugin  but Fresco is a Facebook's plugin. So "com.facebook" isn't undefined, but it hasn't the attribute "FacebookSdk". 

So, my app show the following error:
Cannot read property 'sdkInitialize' of undefined

Best Regards,
Marc

**Comment by EddyVerbruggen** [comment]
Fix available in 3.6.4, thanks!
