### ISSUE TITLE
iOS showNotificationsWhenInForeground has no effect

### ISSUE THREAD

**Issue by felixkrautschuk** [EddyVerbruggen/nativescript-plugin-firebase#1548]
When setting _showNotificationsWhenInForeground_ to _true_, I still not see any notifications on iOS Simulators and physical devices. I only see the console-logs / alerts as a proof that the cloud message is received at all.

My configuration:
- nativescript-plugin-firebase 10.3.3
- NativeScript 6.3.2
- tested on iOS 12 Simulator, iOS 13.3 Simulator, iPhone 6 iOS 12.4 physical device

To reproduce:
- run the [demo](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/tree/master/demo) of this repository
During my tests I only added `showNotifications: true, showNotificationsWhenInForeground: true` to the firebase-init call.
- tap the init-Button in the native-api tab of the TabView
- tap the "add push handlers" button
- tap the "get push token" Button and put that to the following command
- run `curl -X POST --header "Authorization: key=AAAA9SHtZvM:APA91bGoY0H2nS8GlzzypDXSiUkNY3nrti4st4WOUs_w1A0Rttcx31U90YGv-p3U4Oql-vh-FzZzWUUPEwl47uvwhI4tB5yz4wwzrJA2fVqLEKZpDU42AQppYnU2-dsURqkyc9sKcjay2egWbfyNK2b-G2JQCqrLVA" --Header "Content-Type: application/json" https://fcm.googleapis.com/fcm/send -d "{\"notification\":{\"title\": \"My title\", \"showWhenInForeground\": \"true\", \"content_available\": \"true\", \"text\": \"My text\", \"badge\": \"1\", \"sound\": \"default\"}, \"data\":{\"foo\":\"bar\"}, \"priority\": \"High\", \"to\": \"DEVICE_TOKEN\"}"`
(it is the same as mentioned in the docs, I only added "content_available": true and "showWhenInForeground": true within the notification object)
- you will see the alert and the console-logs, but no notification

Btw, I cannot test if the notifications work in general, because background notifications work only with physical devices (as mentioned in the docs of the plugin), but I am not able to build the demo app for our  physical iPhone 6 due to the build error

> error: Failed to register bundle identifier. The app identifier "org.nativescript.firebasedemo" cannot be registered to your development team. Change your bundle identifier to a unique string to try again. (in target 'demo' from project 'demo')
> error: Provisioning profile "iOS Team Provisioning Profile: *" doesn't support the Associated Domains, Push Notifications, and Sign In with Apple capability. (in target 'demo' from project 'demo')
> error: Provisioning profile "iOS Team Provisioning Profile: *" doesn't include the aps-environment

When building our own app for our iPhone 6, I'm not able to test push messages at all, as running the curl says `"error":"InvalidApnsCredential"`. I only see the alert/console-logs for received messages on the Simulator, but there I also do not see any notifications.

**Comment by felixkrautschuk** [comment]
@EddyVerbruggen do you have any hint on why notifications are not showing on iOS at all?
I just see the console logs that the message is received when the app is in foreground, but NO notification

Here is new created demo app just for firebase cloud messages:
[ns-pushnotifications-ios.zip](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/files/4360961/ns-pushnotifications-ios.zip)

This is the command that I use to send a message:
`curl -X POST --header "Authorization: key=AAAAuTby26k:APA91bE3nd6wgUw1ICJdyQDzcLpzmqDUilJMC85BcXlIRHVVCHo90tVqFmfScU0CO8Qv7STYr1fBhH007v8_qVI30DjcLI0IIWhno-EmUKbkwfTaSllcPp_mVaiNnYKnESyX-DUgFXx5" --Header "Content-Type: application/json" https://fcm.googleapis.com/fcm/send -d "{\"notification\":{\"title\": \"My title\", \"showWhenInForeground\": \"true\", \"content_available\": \"true\", \"text\": \"My text\", \"badge\": \"1\", \"sound\": \"default\"}, \"data\":{\"foo\":\"bar\"}, \"priority\": \"High\", \"to\": \"DEVICE_TOKEN\"}"`


I am grateful for any help

**Comment by manojdcoder** [comment]
@felixkrautschuk  It's hard to test the project, at the least without a valid certificate and provisional profiles. If you are not an enterprise user, you will also need the targeted device id to generate the provisional profile.

**Comment by felixkrautschuk** [comment]
@manojdcoder yes but you should be able to see the notification in iOS Simulator, at least foreground notifications, right?

**Comment by manojdcoder** [comment]
@felixkrautschuk I don't think push notification would work on iOS simulator but just data messages. Data messages are handled by FCM itself but Push has to go through APNS which won't work on Simulator for sure.

**Comment by manojdcoder** [comment]
@felixkrautschuk The new Xcode (11.4) now supports testing push notification on Simulator, but it's not real time. You will still have to use real device for testing your FCM / APN configuration and stuffs. The simulator can be used to to test your app, see how it reacts to a push notification that's received.

**Comment by felixkrautschuk** [comment]
@manojdcoder ok thanks, so I will review our configurations and Provisioning profiles first.

**Comment by felixkrautschuk** [comment]
@manojdcoder thanks for your hints and your help. Indeed, it was just a missing configuration in the ios app within our Firebase project.
Now we see the notifications on our test device in all app states (foreground, background, killed).

Before closing this issue I just want to ask one more thing, as it seems that you have more experience using this plugin:
How can we react to the event after tapping a notification?

My config is:
```
showNotifications: true,
showNotificationsWhenInForeground: true    //iOS only
```

When the message is received, the onMessageReceivedCallback is called with this message-data:
```
{
  "google.c.sender.id": <SENDER_ID>,
  "google.c.a.e": "1",
  "gcm.message_id": "1585732400544333",
  "title": "My title",
  "body": "This is the title",
  "data": {
    "google.c.sender.id": <SENDER_ID>,
    "google.c.a.e": "1",
    "aps": {
      "alert": {
        "title": "My title",
        "body": "This is the title"
      },
      "sound": "default"
    },
    "gcm.message_id": "1585732400544333",
    "title": "My title",
    "body": "This is the title"
  },
  "notificationTapped": false,
  "foreground": true
}
```

When tapping the notification while the app is in foreground, I get the same payload + 
```
"notificationTapped": true,    // --> react to tap event!
"foreground": true
```
and now I can inject my own logic as mentioned in the plugin-docs...

But what about tapping a notification while the app is in background or killed?
When the app is in background, the onMessageReceivedCallback is not called and I just see the notification. When tapping the notification, the callback is not called as well and I just see that the app resumed to foreground.
But how can I access the payload in this case?

**Comment by felixkrautschuk** [comment]
@manojdcoder I just created a new nativescript project, installed firebase and tested push-notifications in simulator (using xcode 11.4) and there everything works as expected. 
The notifications are shown in foreground/background/killed (which is working in our real app as well) and tapping the notification triggers the onMessageReceived callback in all these states... 

I don't know why tapping a notification while app is closed/in background does not trigger the callback in our real app, but it is working in a newly created nativescript app, so it is not a bug in this plugin and the docs are not missing something. It seems to be something in our own app, but no idea what is causing this...
