### ISSUE TITLE
[Feature Request] Add Delete User Capability

### ISSUE THREAD

**Issue by rdlauer** [EddyVerbruggen/nativescript-plugin-firebase#1554]
Per the [Firebase docs](https://firebase.google.com/docs/auth/ios/manage-users#delete_a_user) it would be nice if a user could remove themselves from your system post-authentication.

**Comment by EddyVerbruggen** [comment]
Hey Rob, you've found a feature that is actually in the codebase but has never been documented. I've just added it, and it should work with any plugin version you're using: https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/AUTHENTICATION.md#deleting-a-user
