### ISSUE TITLE
Android. android.context not available before application.start() is called. 

### ISSUE THREAD

**Issue by kritollm** [EddyVerbruggen/nativescript-plugin-firebase#156]
I was calling fireBase.init() before the application.start() in app.js.

It worked in IOS, but on Android (real device and emulator) it didn't work. The log traced the error to firebase.android.js line 185 `com.facebook.FacebookSdk.sdkInitialize(appModule.android.context);`. `appModule.android.context` was undefined/null.

I changed the code to run  fireBase.init() after application.start() and it worked.

Is this a Nativescript bug, nativescript-plugin-firebase bug or just expected behaviour?

**Comment by EddyVerbruggen** [comment]
That's a bug in the plugin - let me try to reproduce that..

**Comment by EddyVerbruggen** [comment]
Can you test whether the current version on GitHub fixes the problem for you?

I'm not entirely comfortable with calling init before app start (you need to require the plugin before app start, not init), but I'd like to make it work also for your scenario nonetheless.

**Comment by kritollm** [comment]
Yes, it worked.

**Comment by EddyVerbruggen** [comment]
Sweet! Available in 3.6.4.
