### ISSUE TITLE
Removing firebase and plugin

### ISSUE THREAD

**Issue by mchallenger88** [EddyVerbruggen/nativescript-plugin-firebase#1562]
I've removed the plugin, removed the platform, removed the google services file, deleted all references to firebase that I can find. Still when I build the project I get:

nativescript-plugin-firebase: ...platforms\android\.pluginfirebaseinfo not found, forcing prepare!
nativescript-plugin-firebase: running release build or change in environment detected, forcing prepare!

And then the error:
Unable to copy google-services.json. You need this file, because the Google Services Plugin cannot function without it..
undefined
Failed to execute hook: ...\hooks\after-prepare\firebase-copy-google-services.js.

I must be missing a remnant of the plugin somewhere but I can't find it. Can you help?

**Comment by EddyVerbruggen** [comment]
`rm -rf hooks platforms node_modules` should suffice

**Comment by mchallenger88** [comment]
When I run that command I receive the following error: A parameter cannot be found that matches parameter name 'rf'
