### ISSUE TITLE
Observable on collection(someCol).doc(someDoc).collection(someSubCol) does not return any data

### ISSUE THREAD

**Issue by Slanfan** [EddyVerbruggen/nativescript-plugin-firebase#1564]
I have problems getting my observable on subcollection to work.
If I add the observable on the first doc level I have no issues returning data but when I reference to a subcollection of a specific document I cannot get the observable to return any document from within the subcollection.

Please help!

```
this.attendees$ = Observable.create(subscriber => {
            const colRef: firestore.CollectionReference = firebase.firestore.collection("events").doc(this.eventDocId).collection("players");
            colRef
                .orderBy("name", "asc")
                .onSnapshot((snapshot: firestore.QuerySnapshot) => {
                    console.log("... fetching attendees, found " + snapshot.docs.length + " attendees");
                    this.zone.run(() => {
                        this.attendees = [];
                        snapshot.forEach(docSnap => {
                            console.log("Data (" + docSnap.id + ")", docSnap.data());
                            const playerData = <EventPlayer>docSnap.data();
                            playerData.docId = docSnap.id;
                            this.attendees.push(playerData);
                        });
                        subscriber.next(this.attendees);
                    });
                });
        });
```

**Comment by manojdcoder** [comment]
Are you saying the `onSnapshot` method is never called Or it's just your subscribers are not notified?

**Comment by Slanfan** [comment]
console message within onSnapshot never reach my console so I guess the onSnapshot method never gets called.

**Comment by Slanfan** [comment]
> Are you saying the `onSnapshot` method is never called Or it's just your subscribers are not notified?

console message within onSnapshot never reach my console so I guess the onSnapshot method never gets called.

**Comment by Slanfan** [comment]
@manojdcoder did you have a suggestion to solve this?
Or maybe @EddyVerbruggen have a solution. 

It might be I do something wrong as I’m a n00b but I have the same code running on two other collections (not subCollections though) in the app and that works.

**Comment by manojdcoder** [comment]
@Slanfan I ran some tests on my end with exact same data model you have showcased, the snapshot method is always called (upon creating / updating / deleting players).

If you still have issues, please share a sample project where the issue can be reproduced.

**Comment by Slanfan** [comment]
Did run it on my iOS device instead of the Android Emulator and all worked fine. Need to test and clean the emulator and reinstall there. Will re-open if more help is needed. Thanks anyways.
