### ISSUE TITLE
Cannot decode refreshToken using JWT

### ISSUE THREAD

**Issue by NordlingArt** [EddyVerbruggen/nativescript-plugin-firebase#157]
When calling `firebase.getCurrentUser()`, it will leave a promise with the user info such as `refreshToken`. I am trying to decode this token using [firebase/php-jwt](https://github.com/firebase/php-jwt), but am unable to do that using the given refresh token.

`Uncaught exception 'UnexpectedValueException' with message 'Wrong number of segments'`

The error comes from the JWT, but it seems like Firebase plugin is handing out an invalid token?

**UPDATE:** After translating [this](https://firebase.google.com/docs/auth/server/verify-id-tokens) to JavaScript, I got a valid token. Which btw is a lot longer than the `refreshToken`:

```js
var currentUser = FIRAuth.auth().currentUser;

currentUser.getTokenForcingRefreshCompletion(true, function(idToken, error) {
  if(error) {
    console.log(error);
  } else {
    console.log(idToken);
  }
});
```

**Comment by IvRRimum** [comment]
Is this on Android? How did you get the token in the first place?

**Comment by NordlingArt** [comment]
@IvRRimum - Sorry, forgot to mention. This is iOS.

**Comment by EddyVerbruggen** [comment]
There was a method called `getAutheToken` that provided this but I somehow managed to remove it by mixing up my remotes. It's back in 3.7.0.
