### ISSUE TITLE
Push notifications not showing

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [EddyVerbruggen/nativescript-plugin-firebase#1576]
Hi, 
I am not able to get push notifications showing in bar using firebase.
I am using configurations from docs and am able to recieve them in console in onMessageReceivedCallback (there is simialr discussion but without solution: https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/1440)

but no notifications are created.
also all follows this blog post (https://medium.com/@renzocastro/nativescript-push-notifications-with-firebase-cloud-messaging-2a4a8643a8cb)

I am using nativescript + android
also I saw that there should be real device is used but not sure how - i am running `tns run android` and then through `preview` app I am running it also on real device (not sure if this means - test on real device)

**Comment by vytautas-pranskunas-** [comment]
I have solved an issue. App really needs to be deployed on device.
Steps to do that:
1) Connect your phone to PC
2) Open SideKick
3) Deploy to device
4) If you do not see deviceenable usb debuging and developer options (for Android)
5) If your pc does not recogniz device update drivers or install manufacturers software - in my case it was Hisuit for Huawey P20

**Comment by NazimMertBilgi** [comment]
Will the emulator not work in any way?
