### ISSUE TITLE
JS: AUTHENTICATION_FAILED

### ISSUE THREAD

**Issue by meparashar** [EddyVerbruggen/nativescript-plugin-firebase#1580]
On trying to get push token (messaging.getCurrentPushToken) or to register push notification/handlers the console prints JS: AUTHENTICATION_FAILED on android platform. On iOS, everything works fine.

**Comment by meparashar** [comment]
I'm trying this on android emulator.

**Comment by manojdcoder** [comment]
Have you installed Google Play services on your emulator?

**Comment by meparashar** [comment]
Yes, they are installed.

**Comment by manojdcoder** [comment]
Have you logged on the emulator with a Google Account, which actually enables Play Services?

**Comment by meparashar** [comment]
Yup, tried logging in with own account as well.

**Comment by manojdcoder** [comment]
Meaning it worked and you are able to access Play Store?

**Comment by meparashar** [comment]
no, i meant i tried with own account as well but still received the same error.

**Comment by manojdcoder** [comment]
Do you have a screenshot? I'm not sure how you could get the same error while logging in with Google for Play Services.

**Comment by meparashar** [comment]
Pls excuse my naive questions, but what do you mean by logging in with google for play services. I logged in to my google account (same one using which I log in to my gmail) and then launched my app via tns debug android etc.

<img width="274" alt="Screen Shot 2020-04-08 at 10 06 08 AM" src="https://user-images.githubusercontent.com/12358309/78745156-fae04d00-7980-11ea-8e28-170619faebc0.png">
<img width="279" alt="Screen Shot 2020-04-08 at 10 07 17 AM" src="https://user-images.githubusercontent.com/12358309/78745165-003d9780-7981-11ea-841d-7c5d4cf4f77a.png">
<img width="599" alt="Screen Shot 2020-04-08 at 10 05 27 AM" src="https://user-images.githubusercontent.com/12358309/78745164-ffa50100-7980-11ea-91a8-2d36938b4e3e.png">

**Comment by meparashar** [comment]
errrrrrrr blocks are inside my catch of messaging.getCurrentPushToken call.

`messaging.getCurrentPushToken()
 .then(deviceToken => {
                    console.log(`Current push token: ${deviceToken}`)
                }).catch((err) => {
                    console.log('errrrrrrr');
                    console.dir(err);
                    console.log(err);
                    console.log('errrrrrrr');
                });`

**Comment by manojdcoder** [comment]
How about on real device, did you test it yet?

**Comment by meparashar** [comment]
nope, just on emulator.. i know it's supposed to work on emulator and unlike ios you can receive notifications on android emulator.

**Comment by meparashar** [comment]
Hi Manoj, I think there's some mistake i made. When i logged in, i did, by going to settings > accounts, which didn't solve it. But then I clicked on play icon on home screen and logged in there which seem to have worked. I'm no longer getting the authentication related error. Thank you for your pointers. Thanks.
