### ISSUE TITLE
firebase functions unknown on 3.6.4 with Typescript 2.0.3

### ISSUE THREAD

**Issue by marcbuils** [EddyVerbruggen/nativescript-plugin-firebase#159]
Hi,

Sorry but I have a new error on the version 3.6.4.
All functions are unknown by typescript (exemple: init, addOnMessageReceivedCallback, getRemoteConfig).

Code:

```javascript
import * as firebase from 'nativescript-plugin-firebase';

// ...
firebase.init({
  iOSEmulatorFlush: true
}).then(
  () => {},
  (error) => {
    console.log('firebase.init error: ' + error);
  }
);
```

Error:

```
app/main.ts(14,10): error TS2339: Property 'init' does not exist on type 'typeof firebase'.
```

I don't know how I should use the `interface Firebase`.

Best Regards,
Marc

**Comment by EddyVerbruggen** [comment]
That's strange.. I tested those changes with a fresh TS and non-TS project because it was such a big change and all seemed fine. Perhaps we're running different TSC versions? I tested with TypeScript 2.x...

Would be great to hear input of some others, and if something needs to be changed I'm all open for ideas as usual. Thanks!

**Comment by mikepaggi** [comment]
Getting same thing after updating...using 2.0.3 of TypeScript as well.

**Comment by christiaan-lombard** [comment]
Same thing here, using "nativescript-plugin-firebase": "^3.6.4", "typescript": "^2.0.3"

**Comment by kritollm** [comment]
Same here. Version 3.6.3 firebase.d.ts exports the login(), logout() as functions, but in 3.6.4  the FireBase object is exported instead.

**Comment by EddyVerbruggen** [comment]
Rolled back those changes, pushed 3.7.0 (see [the changelog](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/CHANGELOG.md#370-2016-october-10) for details).

**Comment by blaur** [comment]
Does your nativescript compile typescript? I have upgraded as said but now my nativescript project no longer creates the js sources as they did for 1.8.3 typescript. 

Do you have an idea?
