### ISSUE TITLE
Intermittent crashing on iOS traced to FBSDKCoreKit

### ISSUE THREAD

**Issue by rdlauer** [EddyVerbruggen/nativescript-plugin-firebase#1598]
Rolled out a test of a new app to about 20 users yesterday. For about 10 minutes, folks couldn't use the app as it kept crashing. This resolved itself after those 10 minutes, magically 🧙‍♂️!

Curious to know if anyone else has seen this issue, as it seems related to `FBSDKCoreKit`. Here is the crash log from Xcode:

![image](https://user-images.githubusercontent.com/1918280/81306319-f1f89f00-9044-11ea-8f09-e2c0f7cf9cd3.png)

**Comment by manojdcoder** [comment]
May be it's related to facebook/facebook-ios-sdk/issues/1374 and fixed already?

**Comment by rdlauer** [comment]
Wow, good catch. I suppose we have to wait for Firebase to start using this SDK? Or is the FB SDK a dependency of this plugin (I'm lazy and not checking myself...).

**Comment by manojdcoder** [comment]
FB SDK is dependency of the plugin, installed by the plugin hooks. Also [it sounds](https://github.com/facebook/facebook-ios-sdk/issues/1374#issuecomment-625354650) like the fix was on server side with Facebook. For what's worth you may try a clean build see if it helps.

**Comment by rdlauer** [comment]
Thanks!
