### ISSUE TITLE
[Reopened][ANDROID-BUG] Getting firebase token?

### ISSUE THREAD

**Issue by IvRRimum** [EddyVerbruggen/nativescript-plugin-firebase#160]
I don't know if i need to create a new issue, becouse last one was closed, but the issue still is present.

All info here: https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/153

**Comment by EddyVerbruggen** [comment]
Somehow my remote got mixed up for the last version, sorry about that. I've now pushed 3.7.0 to npm (so `getAuthToken` is back) which also bumps the iOS and Android SDK's.

**Comment by IvRRimum** [comment]
That's great. Will try that tomorrow.
