### ISSUE TITLE
Typescript: Firebase is not a module on v3.7.0

### ISSUE THREAD

**Issue by marcbuils** [EddyVerbruggen/nativescript-plugin-firebase#161]
Hi,

Now I have the following error:
```
error TS2306: File '.../node_modules/nativescript-plugin-firebase/firebase.d.ts' is not a module
```

The reason is a bad module name in firebase (`nativescript-firebase` in place of `nativescript-plugin-firebase`)

:)

**Comment by EddyVerbruggen** [comment]
😞

**Comment by EddyVerbruggen** [comment]
👍

**Comment by marcbuils** [comment]
Sure, the next version will be the good ;)

**Comment by shawn-pavel** [comment]
@EddyVerbruggen @marcbuils I'm getting the following error at runtime: 
```
app/app.component.ts(9,27): error TS2656: Exported external package typings file '/Users/shawnpavel/Documents/Development/mobile_two/node_modules/nativescript-plugin-firebase/firebase.d.ts' 
is not a module. Please contact the package author to update the package definition.
```

I have plugin version 3.7.1 installed. I'm using the plugin in an Angular project. I get the error on iOS and Android. If I inspect the firebase.d.ts file in the node_modules folder the line in question appears to be updated to the correct value (`nativescript-plugin-firebase`)

Steps I've taken to attempt to resolve the problem:

- Remove and Add platforms back
- Delete node_modules folder and run tns install
- Tried `tns plugin update`

Any ideas?

**Comment by shawn-pavel** [comment]
I updated the typescript version to the newest (2.0.3) and the problem went away!

**Comment by nicowernli** [comment]
I had the same problem, changing the typescript version solved my problem too
