### ISSUE TITLE
Could not find any version that matches com.google.firebase:firebase-components:17.+.

### ISSUE THREAD

**Issue by flatironic** [EddyVerbruggen/nativescript-plugin-firebase#1613]
Howdy,
After adding the plugin our app will not build with the error:

**Build file '...\platforms\android\app\build.gradle' line: 598
A problem occurred configuring project ':app'.
Could not find any version that matches com.google.firebase:firebase-components:17.+.
Versions that do not match: 16.0.0
Required by: project :app > com.google.firebase:firebase-inappmessaging-display:17.2.0 > com.google.firebase:firebase-inappmessaging:17.2.0 > com.google.firebase:firebase-datatransport:17.0.5**

Our app builds fine until the plugin is listed in package.json. We have happily been using this plugin for about a year and this is a new issue that we see on both pc and mac. This issue is on the older version of the plugin we were running (~9.0) as well as version 10.5.2. We updated to the latest android-sdk and deleted .gradle cache files in an attempt to remove any lingering references. 

Any ideas are appreciated. Thanks!

**Comment by flatironic** [comment]
Turns out this was a configuration issue in our app.gradle - setting a minimum version requirement for firebase.

**Comment by henriqueqc** [comment]
Had the same problem. @flatironic Thank you for leaving your follow up. This helped a lot.
