### ISSUE TITLE
After tap a push notification in background app settings not working

### ISSUE THREAD

**Issue by csilvav** [EddyVerbruggen/nativescript-plugin-firebase#1615]
Hi @EddyVerbruggen I got an important issue to solve related to Push Notifications using FCM. The notifications arrive properly, however when the app is in background and any notification arrives the user can tap/touch the notification and after this event all data saved with ApplicationSettings or local storage return null/empty or undefined values.

NativeScript v6.4.x
nativescript-plugin-firebase 10.5.2

Thanks for your help

**Comment by spstratis** [comment]
Hi @csilvav have you found root cause on this? Is it only happening with the newer versions of the plugin?

**Comment by csilvav** [comment]
Hello @spstratis not yet. We're testing with different versions and also changing the structure of use. Really it's strange behavior.
