### ISSUE TITLE
Nativescript-plugin-firebase breaks usage of nativescript-oauth2

### ISSUE THREAD

**Issue by cjohn001** [EddyVerbruggen/nativescript-plugin-firebase#1629]
Hello together, 
when using the firebase plugin together with nativescript-oauth2 the oauth2 plugin breaks. I debugged the issue and described it here: 

https://github.com/alexziskind1/nativescript-oauth2/issues/113#issuecomment-651893514

I believe it is an issue of the firebase plugin as the behavior one sees when debugging the oauth2 plugin looks realy weird (described under the link). Therefore I also added the issue to the plugin here. If someone could come up with a real solution which is better than the workaround I sketched on the other issue, this would be very great!

**Comment by cjohn001** [comment]
Issue was based on oauth2 plugin as it overwrote safariviewcontroller instance, see

https://github.com/alexziskind1/nativescript-oauth2/issues/135

**Comment by anarnoli** [comment]
@cjohn001 May I know the approach you followed to make it together plugins working? 
I’m thinking to use both plugins together since firebase plugin doesn’t returns oauth access token which I can use it further to call Google Apis.
