### ISSUE TITLE
iOS Legacy Build System - still necessary?

### ISSUE THREAD

**Issue by james-criscuolo** [EddyVerbruggen/nativescript-plugin-firebase#1638]
I've been attempting to test the ios-v8 work that appears to be nearing completion, and have run into an issue during build:
```
error: the use of xcframeworks is not supported in the legacy build system.
```

It looks like `nativescript-plugin-firebase` forces the project to build with this here: https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/publish/scripts/installer.js#L601

The commit associated seems to hint that the firebase team was in a bit of a transition about two years ago: https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/1022

Any idea if using the legacy system is still needed? Removing ios-v8 from the situation, just removing that portion of the after-prepare hook seems to work. It is extremely possible this is unrelated to this project, but with ios-v8 altering the hook similarly made my build work, but then my app would not open (nothing in the build output). You can test the ios v8 work by replacing your tns-ios version with `beta-v8` and doing a clean build from there. It does seem like this question can be answered entirely independently from the v8 work though.

**Comment by EddyVerbruggen** [comment]
I'm not sure it's still needed. Maybe give it a go by manually altering that script in your hooks folder.

**Comment by james-criscuolo** [comment]
That's exactly how I did it, I just wasn't sure if there was some sort of compatibility to be worried about. If you'd like, I can make a PR removing it, just wanted to know if there were any concerns I was leaving out.

**Comment by EddyVerbruggen** [comment]
If you have Firestore configured and it builds & works fine then please go ahead!

**Comment by kukurt123** [comment]
=== BUILD TARGET fagckapp OF PROJECT fagckapp WITH CONFIGURATION Debug ===
error: the use of xcframeworks is not supported in the legacy build system.

I am having that error after migrating to {N} 7. Its also caused by firebase-plugin-nativescript. Please help thanks!

**Comment by james-criscuolo** [comment]
Are you using `@nativescript/firebase` and the `rc` version?
