### ISSUE TITLE
Topic Messaging using FCM

### ISSUE THREAD

**Issue by asaph26** [EddyVerbruggen/nativescript-plugin-firebase#164]
Is there topic based message subscription support using the plugin? If so is this documented somewhere?

**Comment by EddyVerbruggen** [comment]
No not yet. Do you have any suggestions about what the API would look like?

**Comment by asaph26** [comment]
I can come back with a suggestion and the links to doc soon.

**Comment by Tyre88** [comment]
Bump

**Comment by asaph26** [comment]
This is addressed as part of https://github.com/EddyVerbruggen/nativescript-plugin-firebase/pull/262

Closing this :)
