### ISSUE TITLE
Terminating app due to uncaught exception 'com.firebase.core'

### ISSUE THREAD

**Issue by SamuelGRwebfab** [EddyVerbruggen/nativescript-plugin-firebase#166]
While building in IOS for the first time I was met wit this error 
`2016-10-11 15:42:34.864 challengeApp[865] <Error> [Firebase/Core][I-COR000012] Could not locate configuration file: 'GoogleService-Info.plist'.
2016-10-11 15:42:34.878 challengeApp[865:565318] *** JavaScript call stack:
(
	0   configure@[native code]
	1   @file:///app/tns_modules/nativescript-plugin-firebase/firebase.js:305:23
	2   ZoneAwarePromise@file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:465:37
	3   init@file:///app/tns_modules/nativescript-plugin-firebase/firebase.js:295:21
	4   anonymous@file:///app/main.js:10:14
	5   evaluate@[native code]
	6   moduleEvaluation@:1:11
	7   @:8:48
	8   promiseReactionJob@:1:11
)
2016-10-11 15:42:34.878 challengeApp[865:565318] *** Terminating app due to uncaught exception 'com.firebase.core', reason: '[FIRApp configure] could not find a valid GoogleServices-Info.plist in your project. Please download one from https://console.firebase.google.com/.'`

I have the GoogleService-Info.plist in the app_resources/IOS yet it still cant seem to find it. I have done every 'fix' I could find online but to no avail. Anyone know how this can be fixed? I have a hard deadline of Friday to get an IOS build out so any help would be greatly appreciated

**Comment by SamuelGRwebfab** [comment]
Incase someone else finds this, I solved this by deleting my platforms, and reinstalling it 12 times. Eventually it worked. Good luck to anyone else with this issue, be patient. It will work eventually (as long as you did it right)

**Comment by mhtsharma948** [comment]
I'm also facing this issue. But the solution provided here doesn't make any sense. Is there any proper solution?

**Comment by alexonozor** [comment]
This is making me sick any solution?
