### ISSUE TITLE
Multiple errors with SO_NOAPNFALLBK failed

### ISSUE THREAD

**Issue by cmermingas** [EddyVerbruggen/nativescript-plugin-firebase#167]
Hi,

I am sorry to open another issue but I can't figure this one out... I didn't find anything with "SO_NOAPNFALLBK" on StackOverflow and I already activated KeyChain Sharing as noted on #147 but it didn't help.

I installed the plugin and added authentication, database, messaging, and analytics. I am testing on an emulator only.

When I run the app it works great but it shows this about 25 times:

```
Oct 11 15:55:59 Carloss-MBP myapp[11588]: [] __nwlog_err_simulate_crash simulate crash already simulated "nw_socket_set_common_sockopts setsockopt SO_NOAPNFALLBK failed: [42] Protocol not available"
Oct 11 15:55:59 Carloss-MBP myapp[11588]: [] nw_socket_set_common_sockopts setsockopt SO_NOAPNFALLBK failed: [42] Protocol not available, dumping backtrace:
	        [x86_64] libnetcore-856.1.8
	    0   libsystem_network.dylib             0x00000001136e580e __nw_create_backtrace_string + 123
	    1   libnetwork.dylib                    0x00000001149d9194 nw_socket_add_input_handler + 3002
	    2   libnetwork.dylib                    0x00000001149b6db8 nw_endpoint_flow_attach_protocols + 3768
	    3   libnetwork.dylib                    0x00000001149b5dd5 nw_endpoint_flow_setup_socket + 563
	    4   libnetwork.dylib                    0x00000001149b4b34 -[NWConcrete_nw_endpoint_flow startWithHandler:] + 2612
	    5   libnetwork.dylib                    0x00000001149cfd11 nw_endpoint_handler_path_change + 1261
	    6   libnetwork.dylib                    0x00000001149cf740 nw_endpoint_handler_start + 570
	    7   libnetwork.dylib                    0x00000001149e7003 nw_endpoint_resolver_start_next_child + 2240
	    8   libdispatch.dylib                   0x000000
```

Some other messages that appear, not sure if they are related to this or the plugin but just in case:

```
Oct 11 15:55:59 Carloss-MBP myapp[11588]: Could not successfully update network info during initialization.

Oct 11 15:55:59 Carloss-MBP myapp[11588]: assertion failed: 15G1004 14A345: libxpc.dylib + 62597 [37A9DF49-35C1-3D93-B854-B35CACF0100F]: 0x7d

Oct 11 15:55:59 Carloss-MBP securityd[8663]: found no keychain client entitlements. task=myapp[11588]/1#-1 LF=0 procid=org.nativescript.myapp cs_flags=0x02000201
```

**Comment by EddyVerbruggen** [comment]
I get similar messages in the Simulator as well (since I installed Xcode 8), but everything works just fine for me on a device.

These messages seem to be related to APNS (the push notification server) which isn't supported on a Simulator anyway so not sure I need to do anything about this.

**Comment by tomazahlin** [comment]
"Not sure I need to do anything about this"

Are you serious? These error messages completely flood the console log, and this is very annoying. At least a simple check is simulator is in use would be great, so no logs are created in this case.

**Comment by EddyVerbruggen** [comment]
Well, you can always channel those sentiments towards sending a PR.
