### ISSUE TITLE
v11 sources

### ISSUE THREAD

**Issue by lucboutier** [EddyVerbruggen/nativescript-plugin-firebase#1676]
Hi,

It sounds strange but I don't find the sources of version 11.0.0. master branch is on 10.5.2 and I don't see any tag or branch that contains v11...

Am I missing something ?

**Comment by lucboutier** [comment]
@EddyVerbruggen Any news on v11 sources ?
@NathanWalker you have answered to some issues and maybe know more ?

**Comment by manijak** [comment]
My guess is that it originates from here: https://github.com/nstudio/nativescript-plugin-firebase
I still get errors & crashes with v11 on ns7. 😕 

Analytics do not work, and there is no guide on how to import it and use it with ns 7.

**Comment by lucboutier** [comment]
@manijak thanks for the link I also finally found that there is a related PR and talk on where to land the sources for v11.

https://github.com/EddyVerbruggen/nativescript-plugin-firebase/pull/1640

Anyway I can close this and follow the PR state!
