### ISSUE TITLE
Typescript change import to var, import not working.

### ISSUE THREAD

**Issue by kritollm** [EddyVerbruggen/nativescript-plugin-firebase#168]
After upgrading to Typescript 2.0.3 I had to change a lot of import * as statements to import name = require. But for this plugin I had to change import to var/let/const for the Facebook login to work.

in app.ts.

```
// Doesn't work
import fire = require("nativescript-plugin-firebase");
// Must run on start
var fire = require("nativescript-plugin-firebase");
```

I think the problem is answered [here](http://www.google.com/url?q=http%3A%2F%2Fstackoverflow.com%2Fa%2F29598404%2F3717718&sa=D&sntz=1&usg=AFQjCNE6-VfkeVAtMmLGr4nIbnvca_84EQ). I don't run any firebase code in the app.ts and that's probably why the import doesn't work. Maybe a notice about this in the doc so others don't face the same problems getting this great plugin to work with Typescript.

**Comment by EddyVerbruggen** [comment]
What do you suggest we need to change in the plugin?

The [doc](https://github.com/EddyVerbruggen/nativescript-plugin-firebase#typescript) already uses the `require` syntax.

**Comment by kritollm** [comment]
It's probably a TypeScript issue, I have to take a look at the js output. I just wanted to ensure users didn't waste hours on debugging because of the change in the new Typescript version.
