### ISSUE TITLE
Need access to Token for Push Notification

### ISSUE THREAD

**Issue by Daxito** [EddyVerbruggen/nativescript-plugin-firebase#169]
Hi,
Since topics are not yet supported I need to send notifications using the Token instead, how can I get the current token? The firebase says something like the code below but the current ```instance``` resolved does not have the "getToken()" function, is there a way to get the current token? or do I have to get  new one every time the App Launches?

@Override
public void onTokenRefresh() {
    // Get updated InstanceID token.
    String refreshedToken = FirebaseInstanceId.getInstance().getToken();
    Log.d(TAG, "Refreshed token: " + refreshedToken);

    // If you want to send messages to this application instance or
    // manage this apps subscriptions on the server side, send the
    // Instance ID token to your app server.
    sendRegistrationToServer(refreshedToken);
}

Thank you!

**Comment by EddyVerbruggen** [comment]
Does the `getAuthToken` function help you?

**Comment by Daxito** [comment]
Did not worked, it returned ```Auth token retrieval error: Log in first```, I just want to use the push notifications and nothing else.
But seems like I can just store the token somewhere, it will be the same unless:
The app deletes Instance ID
The app is restored on a new device
The user uninstalls/reinstall the app
The user clears app data.

So I am ok, thank you!

**Comment by pap5508** [comment]
initFirebase(){
    firebase.init({
        onPushTokenReceivedCallback (token){
          console.log("Push Token: "+ token);
        }
       , 

      onMessageReceivedCallback: function(message) {
         	alert(message.title+"");
           this.router.navigate(["/main-menu"]);
      }
          }).then((data) => {
           
                this.tokentake(data);
            
        },
              function (error) {
                console.log("firebase.init error: " + error);
              }
          );
  }


How can I save and send Push token to Server. ?
