### ISSUE TITLE
Need a way to unregister push notification from Firebase

### ISSUE THREAD

**Issue by Daxito** [EddyVerbruggen/nativescript-plugin-firebase#170]
Hi,
I am trying to figure out how to unregister my device from push notifications after user logs out from my app, is there a way to do this? or is this by design?

**Comment by EddyVerbruggen** [comment]
The Firebase docs don't mention it but it makes sense of course. I can add a function to unregister for remote notifications, then on iOS we could do:

```js
  UIApplication.sharedApplication.unregisterForRemoteNotifications()
```

And on Android I guess [this should be invoked](https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceId.html#deleteInstanceId())

**Comment by Daxito** [comment]
+1
It would be very nice to have! I will keep an eye on it, Thanks!

**Comment by EddyVerbruggen** [comment]
I think we shouldn't do this as [hinted here](http://stackoverflow.com/questions/15577152/is-there-a-way-to-programatically-unregister-a-device-for-push-notification). I can confirm it doesn't work reliably in iOS anyway. So I'm afraid it's up to your own backend to track registration status.

**Comment by EddyVerbruggen** [comment]
Added to 5.1.3 (not released yet), but not sure you should use it - so (at least for now) I won't document it. Only available on iOS as on Android there seems to be no such thing.
