### ISSUE TITLE
Init is not a function iOS

### ISSUE THREAD

**Issue by Mflm** [EddyVerbruggen/nativescript-plugin-firebase#1700]
Hi,

I have a project with pure JS (Vainilla) and updated to Nativescript 7.

I can't run the lastest version of plugin.

In app.js I have:
`import { firebase } from '@nativescript/firebase';
`
And the error is:

**firebase.init is not a function.**

Thanks

**Comment by peppeg85** [comment]
the same here, vanilla javascript, import the new plugin, app installed on the emulator but crashes and have the error firebase.init is not a function

here is my code:
````
var firebase =require("@nativescript/firebase")

setTimeout(()=>{
    firebase.init({
          ...some code
    })
},0);
````

**Comment by peppeg85** [comment]
@EddyVerbruggen are there any news?

**Comment by peppeg85** [comment]
seems to be solved this way

````
var firebase = require("@nativescript/firebase").firebase;
````

please add the info to the documentation!

**Comment by ErikNaslund** [comment]
> ```
> var firebase = require("@nativescript/firebase").firebase;
> ```

This solved it for me. Thanks!

**Comment by EddyVerbruggen** [comment]
Feel free to send a PR to the docs.
