### ISSUE TITLE
IOS nanopb fatal error for ns 6.7.8 and 7

### ISSUE THREAD

**Issue by ilkan** [EddyVerbruggen/nativescript-plugin-firebase#1704]
I've tried delete platfom, node_modules and package-lock.json and also I did delete pod then reinstall. So still same.

My nativescript version is 6.7.8, XCode version 12.0.1.

I've updated nativescript 7, and tried all same things still same.

This is my error:

` While building module 'nanopb' imported from /Users/USER/Documents/GitHub/TNS-App/platforms/ios/Pods/GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/GDTCCTLibrary/Protogen/nanopb/cct.nanopb.h:22:
In file included from <module-includes>:1:
/Users/USER/Documents/GitHub/TNS-App/platforms/ios/Pods/Target Support Files/nanopb/nanopb-umbrella.h:13:9: error: double-quoted include "pb.h" in framework header, expected angle-bracketed instead
      [-Werror,-Wquoted-include-in-framework-header]
#import "pb.h"
        ^~~~~~
        <pb.h>
/Users/USER/Documents/GitHub/TNS-App/platforms/ios/Pods/Target Support Files/nanopb/nanopb-umbrella.h:14:9: error: double-quoted include "pb_common.h" in framework header, expected angle-bracketed instead
      [-Werror,-Wquoted-include-in-framework-header]
#import "pb_common.h"
        ^~~~~~~~~~~~~
        <pb_common.h>
While building module 'nanopb' imported from /Users/USER/Documents/GitHub/TNS-App/platforms/ios/Pods/GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/GDTCCTLibrary/Protogen/nanopb/cct.nanopb.h:22:
In file included from <module-includes>:1:
In file included from /Users/USER/Documents/GitHub/TNS-App/platforms/ios/Pods/Target Support Files/nanopb/nanopb-umbrella.h:14:
/Users/USER/Documents/GitHub/TNS-App/platforms/ios/Pods/nanopb/pb_common.h:8:10: error: double-quoted include "pb.h" in framework header, expected angle-bracketed instead [-Werror,-Wquoted-include-in-framework-header]
#include "pb.h"
         ^~~~~~
         <pb.h>
While building module 'nanopb' imported from /Users/USER/Documents/GitHub/TNS-App/platforms/ios/Pods/GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/GDTCCTLibrary/Protogen/nanopb/cct.nanopb.h:22:
In file included from <module-includes>:1:
/Users/USER/Documents/GitHub/TNS-App/platforms/ios/Pods/Target Support Files/nanopb/nanopb-umbrella.h:15:9: error: double-quoted include "pb_decode.h" in framework header, expected angle-bracketed instead
      [-Werror,-Wquoted-include-in-framework-header]
#import "pb_decode.h"
        ^~~~~~~~~~~~~
        <pb_decode.h>
While building module 'nanopb' imported from /Users/USER/Documents/GitHub/TNS-App/platforms/ios/Pods/GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/GDTCCTLibrary/Protogen/nanopb/cct.nanopb.h:22:
In file included from <module-includes>:1:
In file included from /Users/USER/Documents/GitHub/TNS-App/platforms/ios/Pods/Target Support Files/nanopb/nanopb-umbrella.h:15:
/Users/USER/Documents/GitHub/TNS-App/platforms/ios/Pods/nanopb/pb_decode.h:9:10: error: double-quoted include "pb.h" in framework header, expected angle-bracketed instead [-Werror,-Wquoted-include-in-framework-header]
#include "pb.h"
         ^~~~~~
         <pb.h>
While building module 'nanopb' imported from /Users/USER/Documents/GitHub/TNS-App/platforms/ios/Pods/GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/GDTCCTLibrary/Protogen/nanopb/cct.nanopb.h:22:
In file included from <module-includes>:1:
/Users/USER/Documents/GitHub/TNS-App/platforms/ios/Pods/Target Support Files/nanopb/nanopb-umbrella.h:16:9: error: double-quoted include "pb_encode.h" in framework header, expected angle-bracketed instead
      [-Werror,-Wquoted-include-in-framework-header]
#import "pb_encode.h"
        ^~~~~~~~~~~~~
        <pb_encode.h>
While building module 'nanopb' imported from /Users/USER/Documents/GitHub/TNS-App/platforms/ios/Pods/GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/GDTCCTLibrary/Protogen/nanopb/cct.nanopb.h:22:
In file included from <module-includes>:1:
In file included from /Users/USER/Documents/GitHub/TNS-App/platforms/ios/Pods/Target Support Files/nanopb/nanopb-umbrella.h:16:
/Users/USER/Documents/GitHub/TNS-App/platforms/ios/Pods/nanopb/pb_encode.h:9:10: error: double-quoted include "pb.h" in framework header, expected angle-bracketed instead [-Werror,-Wquoted-include-in-framework-header]
#include "pb.h"
         ^~~~~~
         <pb.h>
While building module 'nanopb' imported from /Users/USER/Documents/GitHub/TNS-App/platforms/ios/Pods/GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/GDTCCTLibrary/Protogen/nanopb/cct.nanopb.h:22:
In file included from <module-includes>:1:
/Users/USER/Documents/GitHub/TNS-App/platforms/ios/Pods/Target Support Files/nanopb/nanopb-umbrella.h:17:9: error: double-quoted include "pb.h" in framework header, expected angle-bracketed instead
      [-Werror,-Wquoted-include-in-framework-header]
#import "pb.h"
        ^~~~~~
        <pb.h>
/Users/USER/Documents/GitHub/TNS-App/platforms/ios/Pods/Target Support Files/nanopb/nanopb-umbrella.h:18:9: error: double-quoted include "pb_decode.h" in framework header, expected angle-bracketed instead
      [-Werror,-Wquoted-include-in-framework-header]
#import "pb_decode.h"
        ^~~~~~~~~~~~~
        <pb_decode.h>
/Users/USER/Documents/GitHub/TNS-App/platforms/ios/Pods/Target Support Files/nanopb/nanopb-umbrella.h:19:9: error: double-quoted include "pb_common.h" in framework header, expected angle-bracketed instead
      [-Werror,-Wquoted-include-in-framework-header]
#import "pb_common.h"
        ^~~~~~~~~~~~~
        <pb_common.h>
/Users/USER/Documents/GitHub/TNS-App/platforms/ios/Pods/Target Support Files/nanopb/nanopb-umbrella.h:20:9: error: double-quoted include "pb.h" in framework header, expected angle-bracketed instead
      [-Werror,-Wquoted-include-in-framework-header]
#import "pb.h"
        ^~~~~~
        <pb.h>
/Users/USER/Documents/GitHub/TNS-App/platforms/ios/Pods/Target Support Files/nanopb/nanopb-umbrella.h:21:9: error: double-quoted include "pb_encode.h" in framework header, expected angle-bracketed instead
      [-Werror,-Wquoted-include-in-framework-header]
#import "pb_encode.h"
        ^~~~~~~~~~~~~
        <pb_encode.h>
/Users/USER/Documents/GitHub/TNS-App/platforms/ios/Pods/Target Support Files/nanopb/nanopb-umbrella.h:22:9: error: double-quoted include "pb_common.h" in framework header, expected angle-bracketed instead
      [-Werror,-Wquoted-include-in-framework-header]
#import "pb_common.h"
        ^~~~~~~~~~~~~
        <pb_common.h>
13 errors generated.
In file included from /Users/USER/Documents/GitHub/TNS-App/platforms/ios/Pods/GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/GDTCCTLibrary/Protogen/nanopb/cct.nanopb.c:20:
/Users/USER/Documents/GitHub/TNS-App/platforms/ios/Pods/GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/GDTCCTLibrary/Protogen/nanopb/cct.nanopb.h:22:10: fatal error: could not build module 'nanopb'
#include <nanopb/pb.h>
 ~~~~~~~~^
14 errors generated.
note: Using new build system
note: Building targets in parallel
note: Using codesigning identity override: 
note: Planning build
note: Constructing build description
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'MDFInternationalization' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'nanopb' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'Toast-Swift' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'GoogleUtilities' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'GoogleDataTransportCCTSupport' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'GoogleDataTransport' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'GTMSessionFetcher' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'FirebaseInstanceID' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'FirebaseInstallations' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'FirebaseCoreDiagnostics' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'FirebaseCore' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'FirebaseAuth' from project 'Pods')
** BUILD FAILED **

Command xcodebuild failed with exit code 65`

**Comment by jeremypele** [comment]
We're actually facing the very same issue.

Ns cli: 7.0.10
XCode version 12.0.1.
Cocoapods: 1.9.1 (tested with 1.9.3 too)

**Comment by ilkan** [comment]
Thank you!

> **Edit**: Works with `gem install cocoapods --pre` , not ideal but unblocks out process for now

Solved for me, but I couldn't install that to Xcode 12.0.1. I've installed Xcode 12.2 Beta.
