### ISSUE TITLE
Google Play Services error on Huawei devices

### ISSUE THREAD

**Issue by IvanAddolorato** [EddyVerbruggen/nativescript-plugin-firebase#1725]
Hello Eddy, thanks for this great plugin.

As the title mentions, I'm having some error regarding the absence of Google Play Services on Huawei devices, which makes sense as these devices in fact don't have GPS.

![Screen Shot 2020-11-10 at 15 36 19](https://user-images.githubusercontent.com/63671421/98716547-7f0d0f80-236a-11eb-8da1-d091d8607a7d.png)

As I understand, most of Firebase services don't requiere Google Play Services ([link](https://firebase.google.com/docs/android/android-play-services#google_play_services_not_required)). So, my question is if there is a way to make this plugin work on those Huawei devices?

Thanks in advance!

Ivan.-

**Comment by EddyVerbruggen** [comment]
That has been announced only recently, so yes I guess some future version of this plugin would no longer require it for things like authentication.

**Comment by IvanAddolorato** [comment]
Ok, thanks for your answer Eddy.

So, to be clear: by now, it is not possible to use this plugin on devices without Google Play Services, right?

**Comment by EddyVerbruggen** [comment]
Correct. It's not possible in the SDK versions currently used by this plugin.
