### ISSUE TITLE
Syntax Error when adding plugin with tns

### ISSUE THREAD

**Issue by blaur** [EddyVerbruggen/nativescript-plugin-firebase#173]
When adding the component on Windows I am receiving following error:

```
> nativescript-plugin-firebase@3.7.1 postinstall C:\Users\Brian\Desktop\Development\student-application\node_modules\nativescript-plugin-firebase
> node scripts/postinstall.js

C:\Users\Brian\Desktop\Development\student-application\node_modules\nativescript-plugin-firebase\scripts\postinstall.js:105
    `pod 'Firebase', '~> 3.7.0'
    ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
nativescript-plugin-firebase@3.7.1 postinstall: `node scripts/postinstall.js`
Exit status 1
```

I am not seeing the same error on older version.

**Comment by EddyVerbruggen** [comment]
So the script chokes on the ` character?

Which version did work on your Windows machine? I don't see a difference with 3.7.0.

**Comment by EddyVerbruggen** [comment]
I think your node version is old and it doesn't support ES6 String templates yet (that's the backtick). I could rewrite it to not use backticks but can you please check and update your node version?

**Comment by blaur** [comment]
Hi Eddy,

Thanks for your reply.

It does not work on 3.7.0 either.

I'll try to update my node version later today and update.

/Brian
