### ISSUE TITLE
When will the plugin be upgraded to use Angular2.1.0? 

### ISSUE THREAD

**Issue by netwiser** [EddyVerbruggen/nativescript-plugin-firebase#177]
I tried to use this plugin with https://github.com/NathanWalker/angular-seed-advanced but can not install the plugin, it prompts "The package @angular/core@2.1.0 does not satisfy its siblings' peerDependencies requirements!'. Since the angular-seed-advanced is using Angular2.1.0, so is there any plan to bump up the plugin to use the Angular2.1.0 as well?

Thank.

**Comment by giordy** [comment]
Uhm, I must say that I'm using Angular 2.1 and this plugin.
Everything works fine for me.

I'm not using angular-seed-advanced though

**Comment by netwiser** [comment]
I can close this issue now. Angular-seed-advanced team had identified this issue and has a workaround. Thing should be better after nativescript 2.4.
