### ISSUE TITLE
Error TS2656: Exported external package typings file '[...]/node_modules/nativescript-plugin-firebase/firebase.d.ts' is not a module.

### ISSUE THREAD

**Issue by giordy** [EddyVerbruggen/nativescript-plugin-firebase#179]
Hello,

I floowed the instructions in the README file but I keep getting this error:

`app/app.component.ts(13,27): error TS2656: Exported external package typings file '/home/gio/GIT/xyz/node_modules/nativescript-plugin-firebase/firebase.d.ts' is not a module. Please contact the package author to update the package definition.`

Could it be that some intervention is needed on `firebase.d.ts`, as the error says?

Thanks

**Comment by ullalaaron** [comment]
I've also encountered the same issue.
As a temporary fix I removed the `typings` line in the `package.json` of the plugin.
Eddy, do you have more insight on this?

**Comment by giordy** [comment]
I just found out that if Typescript is updated to version 2.0.3 the error disappears.

Perhaps it could be a good idea to add a disclaimer in the README? The stub apps coming from NativeScript include version 1.8.10 of TypeScript (at least the ones I used, perhaps now this has changed).

**Comment by EddyVerbruggen** [comment]
@giordy That's ok, are you willing to do a PR?

**Comment by giordy** [comment]
@EddyVerbruggen sure, working on it
