### ISSUE TITLE
Property 'firestore' does not exist on type 'typeof firebase'.

### ISSUE THREAD

**Issue by 16hitjon** [EddyVerbruggen/nativescript-plugin-firebase#1804]
I use NS7 with Angular and my import looks like this : 
        ` _import { firebase } from "@nativescript/firebase";_`
firestore.init(...) works with no errors but when I try to access the firebase.firestore() like here:
          _`const citiesCollection = firebase.firestore().collection("cities");`_
I get the error _"Property 'firestore' does not exist on type 'typeof firebase'."_  
How should I import it instead? 
I tried something like  `import { firestore} from "@nativescript/firebase/firestore"` but that doesn`t do it eighter.
Have I overlooked something in the Docs?

**Comment by 16hitjon** [comment]
Apparently only VSCode gave me an error for this, building the app worked...     ....noobie mistakes...

**Comment by wiliamtaesunglee** [comment]
how did u solved?

**Comment by 16hitjon** [comment]
I had multiple versions of the firestore-plugin installed (one for NS7 and an older one), when building the project you see which version is used.
