### ISSUE TITLE
Question: Does it really take 24 hours for the logged events to reflect?

### ISSUE THREAD

**Issue by paul-castro** [EddyVerbruggen/nativescript-plugin-firebase#1810]
Question: Does it really take 24 hours for the events to reflect on Google Analytics dashboard?

**Comment by EddyVerbruggen** [comment]
In my experience: yes.

**Comment by paul-castro** [comment]
Thanks @EddyVerbruggen, I found out that besides from "analytics" I also need to enable this -> "performance_monitoring" when installing the plugin. Now I see my custom events on "Realtime" board, but yeah, I guess it takes 24 hours for that to reflect in "Events" board.

Thanks again!
