### ISSUE TITLE
App Build successful, but crashes on run throwing an uncaught exception stating "Default FirebaseApp is not initialized in this process"

### ISSUE THREAD

**Issue by ChandanShankar** [EddyVerbruggen/nativescript-plugin-firebase#182]
I try implementing the "Firebase", as instructed in the doc.
By using command **"tns debug android --geny "Google Nexus" --debug-brk"**  it finally shows the message as 
**BUILD SUCCESSFUL
Total time: 2 mins 6.76 secs
Project successfully built.** 

But after the successful build it throws the following error: 

The application crashed because of an uncaught exception. You can look at "stackTrace" or "nativeException" for more detailed information about the exception.
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.v4smobilepublic/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onCreate failed

Error: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process org.nativescript.v4smobilepublic. Make sure to call FirebaseApp.initializeApp(Context) first.
    com.google.firebase.FirebaseApp.getInstance(Unknown Source)
    com.google.firebase.database.FirebaseDatabase.getInstance(Unknown Source)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:865)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:730)
    com.tns.Runtime.callJSMethod(Runtime.java:716)
    com.tns.Runtime.callJSMethod(Runtime.java:697)
    com.tns.Runtime.callJSMethod(Runtime.java:687)
    com.tns.NativeScriptActivity.onCreate(android.app.Activity.java)
    android.app.Activity.performCreate(Activity.java:6237)
    android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
    android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
    android.app.ActivityThread.-wrap11(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5417)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
File: "/data/data/org.nativescript.v4smobilepublic/files/app/tns_modules/nativescript-plugin-firebase/firebase.js, line: 159, column: 36

StackTrace: 
	Frame: function:'_resolve', file:'/data/data/org.nativescript.v4smobilepublic/files/app/tns_modules/nativescript-plugin-firebase/firebase.js', line: 159, column: 37
	Frame: function:'Observable.notify', file:'/data/data/org.nativescript.v4smobilepublic/files/app/tns_modules/data/observable/observable.js', line: 174, column: 23
	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'/data/data/org.nativescript.v4smobilepublic/files/app/tns_modules/ui/frame/frame.js', line: 656, column: 21
	Frame: function:'NativeScriptActivity.onCreate', file:'/data/data/org.nativescript.v4smobilepublic/files/app/tns_modules/ui/frame/activity.js', line: 12, column: 25

	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: com.tns.NativeScriptException: 
Calling js method onCreate failed

Error: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process org.nativescript.v4smobilepublic. Make sure to call FirebaseApp.initializeApp(Context) first.
    com.google.firebase.FirebaseApp.getInstance(Unknown Source)
    com.google.firebase.database.FirebaseDatabase.getInstance(Unknown Source)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:865)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:730)
    com.tns.Runtime.callJSMethod(Runtime.java:716)
    com.tns.Runtime.callJSMethod(Runtime.java:697)
    com.tns.Runtime.callJSMethod(Runtime.java:687)
    com.tns.NativeScriptActivity.onCreate(android.app.Activity.java)
    android.app.Activity.performCreate(Activity.java:6237)
    android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
    android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
    android.app.ActivityThread.-wrap11(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5417)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
File: "/data/data/org.nativescript.v4smobilepublic/files/app/tns_modules/nativescript-plugin-firebase/firebase.js, line: 159, column: 36

StackTrace: 
	Frame: function:'_resolve', file:'/data/data/org.nativescript.v4smobilepublic/files/app/tns_modules/nativescript-plugin-firebase/firebase.js', line: 159, column: 37
	Frame: function:'Observable.notify', file:'/data/data/org.nativescript.v4smobilepublic/files/app/tns_modules/data/observable/observable.js', line: 174, column: 23
	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'/data/data/org.nativescript.v4smobilepublic/files/app/tns_modules/ui/frame/frame.js', line: 656, column: 21
	Frame: function:'NativeScriptActivity.onCreate', file:'/data/data/org.nativescript.v4smobilepublic/files/app/tns_modules/ui/frame/activity.js', line: 12, column: 25

	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:865)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:730)
	at com.tns.Runtime.callJSMethod(Runtime.java:716)
	at com.tns.Runtime.callJSMethod(Runtime.java:697)
	at com.tns.Runtime.callJSMethod(Runtime.java:687)
	at com.tns.NativeScriptActivity.onCreate(android.app.Activity.java)
	at android.app.Activity.performCreate(Activity.java:6237)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
	... 9 more
Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process org.nativescript.v4smobilepublic. Make sure to call FirebaseApp.initializeApp(Context) first.
	at com.google.firebase.FirebaseApp.getInstance(Unknown Source)
	at com.google.firebase.database.FirebaseDatabase.getInstance(Unknown Source)
	... 19 more
```
Please help me solving this.

**Comment by EddyVerbruggen** [comment]
Does your genymotion emulator have Google Play Services?

And have you added google-services.json to the correct spot in your project?

**Comment by ChandanShankar** [comment]
Hi Eddy, Thank for the reply,

- Yes, added google-services.json at platforms/android/google-services.json  
- And I'm trying to install Google Play Service, but is not working every-time throws "Unfortunately google play services has stopped".

**Comment by ChandanShankar** [comment]
Eddy, Thanks for the support.
The issue got resolved by reinstall Google Play Services APK.

**Comment by blaind** [comment]
Had the same problem, fixed by following:
- moved google-services.json to platforms/android instead of app/App_Resources/Android
- added an extra line at the end of platforms/android/build.graddle. This is mentioned in Firebase Android installation instructions

``
apply plugin: "com.google.gms.google-services
``

After adding the line, I can see following lines during build process
``
processF0F1F2F3DebugGoogleServices
Parsing json file: /home/user/testapp/platforms/android/google-services.json
``

Before that adb logcat was displaying the following error:
``
FirebaseInitProvider: FirebaseApp initialization unsuccessful
``

**Comment by blaind** [comment]
Thanks @EddyVerbruggen, I installed the new version and everything works now out of the box. 

One minor note:
``
prompt: Do you want to save the selected configuration. Reinstalling the dependency will reuse the setup from: ../../firebase.nativescript.json. CI will be easier. (y/n):  (y) y
``

as I was running the command from tns app root, this was a bit misleading (should not have ../..).

**Comment by EddyVerbruggen** [comment]
Point taken, will take a look! Thanks for the quick test 👍

**Comment by anuragd7** [comment]
Hi Eddy
Am facing the same issue. Have tried everything mentioned in this thread. The following are some details 

1. the build is successful but on tns run android the app crashes with this error Error: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process org.nativescript.qbank. Make sure to call FirebaseApp.initializeApp(Context) first.

2.  The crash happens with the same message on both GenyMotion and the actual device. Both have play services installed.

3. google-services.json is there in both platforms/android AND app/App_Resources/Android

4. reinstalled Google Play Services APK.

Was not able to get the app to run inspite of all these changes.

**Comment by anuragd7** [comment]
Fixed it. Deleted node modules and the platform and then reinstalled them and then reinstalled the the plugin. Working now!
