### ISSUE TITLE
IOS facebook login crash

### ISSUE THREAD

**Issue by SamuelGRwebfab** [EddyVerbruggen/nativescript-plugin-firebase#187]
This is a repeatable issue. Every time i try to use the login via Facebook function on an IOS device, the app crashes and gives me this error
`1   0xbf51c3 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
2   0xfd9a15 ffi_closure_inner_SYSV
3   0xfdd0b8 ffi_closure_SYSV
4   0x200a88eb <redacted>
5   0x20092a87 <redacted>
6   0x200a8213 <redacted>
7   0x200a7d5f <redacted>
8   0x200a2947 <redacted>
9   0x200737c9 <redacted>
10  0x20813c39 <redacted>
11  0x2080d8db <redacted>
12  0x1afe9c8b <redacted>
13  0x1afe9795 <redacted>
14  0x1afe7a6b <redacted>
15  0x1af37073 CFRunLoopRunSpecific
16  0x1af36e81 CFRunLoopRunInMode
17  0x1c6dfbfd GSEventRunModal
18  0x200deacf <redacted>
19  0x200d9201 UIApplicationMain
20  0xfdd02c ffi_call_SYSV
21  0xfd9759 ffi_call
22  0xbc54b7 NativeScript::FFICall::call(JSC::ExecState*)`

The same code works fine for me on android. I have also confirmed that the firebase connection is working on IOS (used normal login function with email and password). I tried searching on google for some bits of this error and came up with nothing. If anyone have a fix for this I would really appreciate it!

**Comment by EddyVerbruggen** [comment]
That's not a very useful stacktrace I'm afraid. I just confirmed it works fine on an iOS 10 simulator though. Which device is this exactly?

Can I debug your app?

**Comment by austinlarue** [comment]
I'm having the same issue on iOS10 simulator and iOS10 device. This is the error message I receive:

`Oct 20 16:03:09 Austins-MacBook-Pro com.apple.CoreSimulator.SimDevice.FBE00800-99EE-425C-9B75-FACE6ADA04FF.launchd_sim[40033] (UIKitApplication:<BUNDLE_ID>[0x3014][18277]): Service exited with abnormal code: 1`

**Comment by SamuelGRwebfab** [comment]
@EddyVerbruggen i am currently using an iphone 5c. sorry about the error log but thats all it gave me. I have not tried it in an emulator, I personally do not like using them. Is there some other information i could send you that would help?

**Comment by tskweres** [comment]
@EddyVerbruggen I posted a repetitive ticket before I saw this:

#191 

But I'm having the same issue. Do you have a sample repo for the minimal app that works? I can review the differences in implementation to maybe see what's causing it on my end.

**Comment by SamuelGRwebfab** [comment]
@tskweres I've done quite a bit of investigating to no avail. If you find out whats wrong please let me know. Thanks

**Comment by EddyVerbruggen** [comment]
@tskweres [demo here](https://github.com/EddyVerbruggen/nativescript-plugin-firebase-demo)

**Comment by tskweres** [comment]
@EddyVerbruggen @samuelagm still investigating, do you guys ever have this error?

Firebase/Core][I-COR000012] Could not locate configuration file: 'GoogleService-Info.plist'.

I've restarted my emulator, and it doesn't see the .plist even though it's there, not sure what's causing this but it's preventing me from launching the app :/

**Comment by tskweres** [comment]
Had to rebuild my Pods, but yes same error. Then again I'm using Typescript / angular2 so the demo app is a little bit hard to go off of, is there a ng version?

**Comment by EddyVerbruggen** [comment]
Nope, not at the moment.

**Comment by tskweres** [comment]
@samuelagm I copied the implementation from the groceries app and the error is still there. I tried running the app in Xcode to build on a device and I get:

clang: error: linker command failed with exit code 1 (use -v to see invocation)
Framework Not Found: Bolts

This could be what's throwing everything off, trying to track it down

this old Parse error might be related

http://stackoverflow.com/questions/28920666/parse-and-facebook-sdk-bolts-framework-error

**Comment by tskweres** [comment]
@samuelagm @EddyVerbruggen 

Guys solved, for me the issue was that the info.plist did not have my Facebook credentials. We may want to update the installion guide / read me, I didn't see that in the steps ( though admittedly I didn't watch the video, it may be there )

In any event, here's the guide from the Facebook Docs:

https://developers.facebook.com/docs/ios/getting-started

See Step 4 - Configure XCode Project

**Comment by SamuelGRwebfab** [comment]
@tskweres Nice catch! After checking my file i too did not have my credentials saved. Thanks for letting me know. I will be testing this in a few hours

**Comment by EddyVerbruggen** [comment]
Mine have those credentials from the get-go so never encountered this problem (lucky me!). But it would indeed be great to have something in the readme on this.

**Comment by EddyVerbruggen** [comment]
Added it to the [readme](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/AUTHENTICATION.md#ios), thx!
