### ISSUE TITLE
Conflict with nativescript-admob

### ISSUE THREAD

**Issue by calebeaires** [EddyVerbruggen/nativescript-plugin-firebase#19]
This plugin seens to have some issue with nativescript-admob. When using both, build fails.

```
:config phase:  createDefaultIncludeFiles
	+found plugins: nativescript-admob
	+found plugins: nativescript-plugin-firebase

:config phase:  createPluginsConfigFile
	+creating product flavors include.gradle file in configurations folder...

:config phase:  pluginExtend
	+applying configuration from: /Users/calebeaires/Sites/testes/pass/platforms/android/configurations/include.gradle
	+applying configuration from: /Users/calebeaires/Sites/testes/pass/platforms/android/configurations/nativescript-admob/include.gradle
	+applying configuration from: /Users/calebeaires/Sites/testes/pass/platforms/android/configurations/nativescript-plugin-firebase/include.gradle

:config phase:  copyAarDependencies

:config phase:  addAarDependencies
	+adding dependency: /Users/macbook/Sites/testes/pass/platforms/android/libs/aar/widgets-release.aar

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'pass'.
> No flavor is associated with flavor dimension 'nativescriptadmob'.

```

**Comment by EddyVerbruggen** [comment]
Thanks for reporting this!

The problem really was with the AdMob plugin. Please update it to 1.1.2 and you should be all set.

**Comment by dauvollc** [comment]
There seems to be a conflict with the AdMob plugin again.  I am running versions:
`"tns-android": {      "version": "2.4.1"    }
"nativescript-admob": "^1.3.0",
"nativescript-angular": "1.3.0",
"nativescript-plugin-firebase": "^3.9.2",`

I've been running the Firebase plugin just fine, and I just attempted to add the admob plugin and it errors upon runnings `tns run android --watch`

Here is the error information:

> :config phase:  createPluginsConfigFile
>          Creating product flavors include.gradle file in H:\NEW Developing\Firebas
> \android/configurations folder...
> 
> :config phase:  pluginExtend
>         +applying configuration from: H:\NEW Developing\Firebase\Mobile\valuchek\p
> ions\include.gradle
>         +applying configuration from: H:\NEW Developing\Firebase\Mobile\valuchek\p
> ions\nativescript-admob\include.gradle
>         +applying configuration from: H:\NEW Developing\Firebase\Mobile\valuchek\p
> ions\nativescript-plugin-firebase\include.gradle
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Script 'H:\NEW Developing\Firebase\Mobile\valuchek\platforms\android\configuration
> ase\include.gradle' line: 45
> 
> * What went wrong:
> A problem occurred evaluating script.
> > Failed to apply plugin [id 'com.google.gms.google-services']
>    > For input string: "+"
