### ISSUE TITLE
iOS 10 Notification Object Structure

### ISSUE THREAD

**Issue by shawn-pavel** [EddyVerbruggen/nativescript-plugin-firebase#193]
@EddyVerbruggen ,

I'm attempting to add Push Notification to my application. On Android everything went smooth but I have been unable to get iOS working properly. I am able to receive notifications while the app is in the background but I receive nothing at all while the app is in the foreground. The message received callback never gets fired.

In an attempt to figure the issue out I made a clean application using `tns create my-app --ng` and added firebase. Set up a new firebase project. Set up new iOS provisioning. I am able to receive the push notification while the app is in the foreground. However the message does not contain the proper data.

This is what the data object looks like: 

```
{                                                                                                                                                                          
    "google.c.a.e": "1",                                                                                                                                                   
    "gcm.n.e": "1",                                                                                                                                                        
    "google.c.a.c_id": "6050414523571786758",                                                                                                                              
    "google.c.a.udt": "0",                                                                                                                                                 
    "gcm.message_id": "0:1477408211320506%e8a8d6b6e8a8d6b6",                                                                                                               
    "google.c.a.ts": "1477408210",                                                                                                                                         
    "foreground": true                                                                                                                                                     
}    
```

I'm more confused now than I was before I made the test project.

I'm testing on an iPod running iOS 10.0.2. I also have an iPhone running 10.0.2 available for testing.

Any help would be much appreciated.

**Comment by creambyemute** [comment]
I experience similiar problems with iOS 10, but works fine on iOS 8 and 9.

When I receive a notification on iOS 10 while the app is in the background and open the app by tapping the notification it'll crash in applicationDidReceiveRemoteNotificationFetchCompletionHandler calls --> _processPendingNotifications().
When I receive a notification on iOS 10 while the app is in the foreground my `onMessageReceivedCallback` is never called and I've put a `console.dump(userInfoJSON)` in firebase.ios.js inside `if (firebase._receivedNotificationCallback !== null) {`

Which outputs { "gcm.message_id": "0:1477402966649735%e0224ee6e0224ee6" }, which is obviously wrong as well as I send the following message:

curl -X POST --header "Authorization: key=MyAuthKey" --Header "Content-Type: application/json" https://fcm.googleapis.com/fcm/send -d "{\"notification\":{\"title\": \"My title\", \"text\": \"My text\", \"sound\": \"default\"}, \"priority\": \"High\", \"to\": \"MyDevicePushToken\"}"

Cheers,

**Comment by shawn-pavel** [comment]
I discovered why I wasn't getting any in app notifications. Turns out the `status-bar-util` used in the NativeScript Angular tutorial was causing the issue. Probably with the way it used the `applicaiotnDidFinishLaunchingWithOptions` and `appDelegate` Not sure.

However, I am not experiencing the exact same thing as creambyemute. The output just has the `gcm.message_id`.

**Comment by shawn-pavel** [comment]
That last message should have read "I am now experiencing"  I do have the same issue.

**Comment by EddyVerbruggen** [comment]
Looks like Firebase added a few new bits on iOS 10 to their [FCM docs](https://firebase.google.com/docs/cloud-messaging/ios/client#swizzling_disabled_receive_messages_through_the_messaging_apns_interface) which may affect the way the plugin handles messaging on FCM as well.

**Comment by EddyVerbruggen** [comment]
Please give the current master branch in GitHub a spin to see if this helps on iOS 10. The object was indeed incomplete, and receiving the notification popup when the app was in the background didn't seem to work.
