### ISSUE TITLE
firebase user provider data?

### ISSUE THREAD

**Issue by AntonioRossi** [EddyVerbruggen/nativescript-plugin-firebase#196]
I could not find it in the documentation, is it possible to get the info of the provider from which the user authentication was authorized?

Let's say for example something similar to `getProviderData()` of the class `FirebaseUser` in adroid, analogous to `Fireuser.providerData` in the iOS version.

**Comment by EddyVerbruggen** [comment]
Out of curiosity: what kind of data of which provider are you after?

**Comment by AntonioRossi** [comment]
I would like to distinguish if a user is authorized by Google or if otherwise he is authorized by Facebook.

**Comment by EddyVerbruggen** [comment]
You can already determine that I think - it's the logintype you're passing in. If the user is consequently logged on you can store the last logintype with the user.

**Comment by AntonioRossi** [comment]
I think your suggestion works, but also I think it could be preferable to have this information using directly firebase as the source.

Consider for example those cases in which a user has multiple login providers that have been linked to a single firebase user account.
I could have a web app using the javascript sdk that permits to manage this scenario and link multiple providers into a single firebase account, at this point it would be useful gather this information in the mobile apps without the trouble of managing the coherence and keep the syncing of these information.

**Comment by EddyVerbruggen** [comment]
See the [updated readme](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/AUTHENTICATION.md#whats-returned-when-logged-in)
