### ISSUE TITLE
A few questions about the usage of Firebase

### ISSUE THREAD

**Issue by 9thwall** [EddyVerbruggen/nativescript-plugin-firebase#200]
Hi, 
I posted some questions on Stackoverflow hoping that I didn't have to bother you with this but I'm not sure if anybody else has the answers. If you have time, can you please help me with these questions? 

[Stackoverflow](http://stackoverflow.com/questions/40364824/firebase-database-usage-questions)

**Comment by calebeaires** [comment]
Good questions!

**Comment by EddyVerbruggen** [comment]
Perhaps split your questions into multiple questions on SO.
