### ISSUE TITLE
Getting fileUri for selected file showing below error

### ISSUE THREAD

**Issue by JaganJonnala** [EddyVerbruggen/nativescript-plugin-firebase#201]
JS: Error: java.lang.SecurityException: Permission Denial: reading com.android.p
roviders.media.MediaProvider uri content://media/external/images/media from pid=
5319, uid=10104 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPe
rmission()
JS:     android.os.Parcel.readException(Parcel.java:1599)
JS:     android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.jav
a:183)
JS:     android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.jav
a:135)
JS:     android.content.ContentProviderProxy.query(ContentProviderNative.java:42
1)
JS:     android.content.ContentResolver.query(ContentResolver.java:491)
JS:     android.content.ContentResolver.query(ContentResolver.java:434)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:865)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:730)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:716)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:697)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:687)
JS:     com.tns.NativeScriptActivity.onActivityResult(android.app.Activity.java)

JS:     android.app.Activity.dispatchActivityResult(Activity.java:6428)
JS:     android.app.ActivityThread.deliverResults(ActivityThread.java:3695)
JS:     android.app.ActivityThread.handleSendResult(ActivityThread.java:3742)
JS:     android.app.ActivityThread.-wrap16(ActivityThread.java)
JS:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
JS:     android.os.Handler.dispatchMessage(Handler.java:102)
JS:     android.os.Looper.loop(Looper.java:148)
JS:     android.app.ActivityThread.main(ActivityThread.java:5417)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.ja
va:726)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
JS: Seelcted Uri is

**Comment by EddyVerbruggen** [comment]
Look at the message at the top of the stacktrace: you need to add a permission to your app/App_Resources/Android/AndroidManifest.xml if you want to read external storage. Note that on newer Androids you'll also need to request runtime permission when building with target SDK 23. None of this is related to this plugin though.

**Comment by JaganJonnala** [comment]
I have added permission too in my android manifest file But its showing like this Can you please go through with my AndroidManifest.xml and tel me what to do forward...is it ok..?

**Comment by JaganJonnala** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
	package="__PACKAGE__"
	android:versionCode="1"
	android:versionName="1.0">

	<supports-screens
		android:smallScreens="true"
		android:normalScreens="true"
		android:largeScreens="true"
		android:xlargeScreens="true"/>

	<uses-sdk
		android:minSdkVersion="17"
		android:targetSdkVersion="__APILEVEL__"/>

	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
	<uses-permission android:name="android.permission.INTERNET"/>

	<application
		android:name="com.tns.NativeScriptApplication"
		android:allowBackup="true"
		android:icon="@drawable/icon"
		android:label="@string/app_name"
		android:theme="@style/AppTheme">

		<activity
			android:name="com.tns.NativeScriptActivity"
			android:label="@string/title_activity_kimera"
			android:configChanges="keyboardHidden|orientation|screenSize">
			

			

			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
		</activity>
		<activity android:name="com.tns.ErrorReportActivity"/>
	</application>
</manifest>
`

**Comment by EddyVerbruggen** [comment]
LGTM, but like I said: for Android 6+ you need to request runtime permissions as well in case you build against targetsdk 23+.
