### ISSUE TITLE
Google Play services is required for this feature, but not available on this device

### ISSUE THREAD

**Issue by Taremeh** [EddyVerbruggen/nativescript-plugin-firebase#207]
Hi,
I setup everything as it was written in the instructions:

```
Applying changes...
Successfully synced application org.nativescript.apphovenAlpha on device emulator-5554.
JS: firebase.init done
JS: Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
JS: Logged out from firebase
```

But as soon as I try to login (click the button) I get:
```
JS: Google Play services is required for this feature, but not available on this device
```

What's wrong?
I installed both packages 'Google Play Services' and 'Google Repository'. I also defined it in the build.gradle... And I don't get any errors - it just doesn't work.

**Comment by Taremeh** [comment]
Finally, I could solve it:

Make sure, you selected the "Google APIs Intel Atom" as your CPU/ABI in the AVD Manager (`android avd`)

If "Google APIs Intel Atom" doesn't show up as a option, then

- type `android` into the terminal and copy / write down the SDK-Path, shown at the top. For me, it was "/usr/local/Cellar/android-sdk/24.4.1_1".

- Set the ANDROID_HOME var to the SDK-path (no need to specify the version): 
```export ANDROID_HOME=/usr/local/Cellar/android-sdk```

- Run `android avd` and select "Google APIs Intel Atom" as your CPU/ABI.

**Comment by davidbcc** [comment]
@Taremeh, I have the same problem as well. I have setup nativescript-firebase-plugin in my nativescript project. But, when I run the project and hit login method and it throws me the same error as mentioned above. **JS: Google Play services is required for this feature, but not available on this device**

**Comment by Taremeh** [comment]
@davidbcc The "fix" (see above) does not work? If so, please give more information: Are you using a physical device or an emulator (AVD / Genymotion)?

**Comment by davidbcc** [comment]
Hi @Taremeh , Good Day! I have resolved my issue. I was using an emulator (AVD), I updated the Google Play Service on the emulator and re-boot the device. After that, all are working as expected.

Thank you.
