### ISSUE TITLE
Firebase user auth token decoder?

### ISSUE THREAD

**Issue by kevinklinegargar** [EddyVerbruggen/nativescript-plugin-firebase#208]
Hi Guys,
 I'm new in mobile development and the frameworks I used in my apps nativescript, typescript, angular and firebase, anyway I'm wondering how to use the getAuthToken() to re-login the user from offline mode?according to the firebase docs it needs to use the admin.auth().verifyIdToken(idToken) function but I cannot find that function on this plugin. can someone guide me to the right direction how to manage the firebase user auth token for offline auto sync apps with nativescript? 

I used firebase.getAuthToken() then the returned token and I passed in firebase.LoginType.CUSTOM but I got an error " Logging in the user failed. com.google.firebase.auth.FirebaseAuthInvalidCredentialsException: The custom token format is incorrect. Please check the documentation."
any idea?

Thanks

**Comment by keithhie** [comment]
@kevinklinegargar How did you resolve this?
