### ISSUE TITLE
Data is not syncing

### ISSUE THREAD

**Issue by triniwiz** [EddyVerbruggen/nativescript-plugin-firebase#21]
The plugin doesn't show no init error but no other function seems to be working  properly

if i try to login i get 

```
JS: There was an exception while connecting to the authentication server: Host is unresolved: auth.firebase.com
```

after creating a listener it show the log that it was created but i'm not able to retrieve data 

```
firebase.addChildEventListener added
```

using the push function only generates an id

This appears on Android
nativescript-plugin-firebase  version : 2.1.1
CLI: 1.7.0
Cross-platform modules: 1.7.0
Runtime(s): 1.7.0

**Comment by EddyVerbruggen** [comment]
Hi, was this before or after you fixed the login settings in Firebase (re: your Slack messages).

**Comment by triniwiz** [comment]
I tried it on two different fb ref and the same problem

**Comment by EddyVerbruggen** [comment]
Did you also try the [official demo app](https://github.com/EddyVerbruggen/nativescript-plugin-firebase-demo)? You can get it running in 1 minute so please check if that works ok. Otherwise I'll need your app.

**Comment by triniwiz** [comment]
ok i'll test if i run into any problems i'll send you my app

**Comment by triniwiz** [comment]
After checking all of my settings then finally genymotion i found out that i had the network disabled on the emulator from some previous test :( a couple days ago
