### ISSUE TITLE
Send Email Verification

### ISSUE THREAD

**Issue by lorcanfurey** [EddyVerbruggen/nativescript-plugin-firebase#214]
Hi Eddy,

Great plugin by the way!

Will it be difficult to have the Android SDK's FirebaseUser.sendEmailVerification() added though; along with a user property to check if it has been verified through email?
(as well as its iOS counterpart)

**Comment by EddyVerbruggen** [comment]
Hi! Looks like a nice idea, thanks!

Looks quite easy.

For my reference: these are the relevant [iOS](https://firebase.google.com/docs/auth/ios/manage-users#send_a_user_a_verification_email) and [Android](https://firebase.google.com/docs/auth/android/manage-users#send_a_user_a_verification_email) methods.

**Comment by EddyVerbruggen** [comment]
Landed in the (soon to be released) 3.8.0 version. See the [readme](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/AUTHENTICATION.md#sendemailverification).

**Comment by lorcanfurey** [comment]
Thanks! :)
