### ISSUE TITLE
Can't find variable: FIRServerValue

### ISSUE THREAD

**Issue by verasnt** [EddyVerbruggen/nativescript-plugin-firebase#219]
Hi! I'm trying to use the plugin and I came across with this error message:
`CONSOLE LOG file:///app/tns_modules/nativescript-plugin-firebase/firebase.js:481:18: Error in firebase.init: ReferenceError: Can't find variable: FIRServerValue
CONSOLE LOG file:///app/app.js:18:16: firebase.init error: ReferenceError: Can't find variable: FIRServerValue`
GoogleService --> app/App_resources/IOS/GoogleService..
in the package.json --> "nativescript-plugin-firebase": "^3.8.3"

Thanks!!

**Comment by EddyVerbruggen** [comment]
Hi, at what point in your app lifecycle do you invoke `init()`? I'm wondering if the Firebase SDK gets loaded at all, or that it's not loaded at the moment you call `init`..

**Comment by abinici** [comment]
Hi, while trying to authenticate a user in my app running in the iOS simulator I get a similar error message:

```
CONSOLE LOG file:///app/tns_modules/nativescript-plugin-firebase/firebase.js:507:18: Error in firebase.init: ReferenceError: Can't find variable: FIRServerValue
CONSOLE LOG file:///app/tns_modules/nativescript-plugin-firebase/firebase.js:900:18: Error in firebase.login: ReferenceError: Can't find variable: FIRAuth
CONSOLE LOG file:///app/shared/auth.service.ts:26:28: firebase.init error: ReferenceError: Can't find variable: FIRServerValue
```

I invoke the `init()` and `login()` when the user pushes a sign in button:

```
    signIn() {
        let tfEmailAddress = this.page.getViewById<TextField>('tfEmailAddress');
        let tfPassword = this.page.getViewById<TextField>('tfPassword');

        this.auth.init().then(() => {
            this.auth.login(tfEmailAddress.text, tfPassword.text).then(
                (auth) => {
                    Dialogs.alert('Auth successful');
                },
                (error) => {
                    Dialogs.alert('Auth failed: ' + error);
                }
            )
        });
    }
```

And this is how `auth.init()` and `auth.login` looks like:

```
    init() {
        return firebase.init({}).then(
            function (instance) {
                console.log("firebase.init done");
            },
            function (error) {
                console.log("firebase.init error: " + error);
            }
            );
    }

    login(email: string, password: string) {
        return firebase.login({
            type: firebase.LoginType.PASSWORD,
            email: email,
            password: password
        });
    }
```

A week ago this was working just fine.

**Comment by abinici** [comment]
This is weird. Just ran the app in the iOS Simulator, and Firebase started working again. And I haven't changed anything besides my location / network. Any idea why this behaviour suddenly changed?
