### ISSUE TITLE
"Expected "/*", "//" or "{" but "<" found" after adding nativescript-plugin-firebase

### ISSUE THREAD

**Issue by aaweb** [EddyVerbruggen/nativescript-plugin-firebase#22]
Hey there

After adding the nativescript firebase plugin using `tns plugin add nativescript-plugin-firebase`, when I run `tns run ios --emulator` the first time it works fine, but every following time, I get: 
```
Found peer TypeScript 1.8.2 
Expected "/*", "//" or "{" but "<" found.
```

Clearing out the platforms folder does the trick, but it also breaks livesync which is a real shame. Am I missing something obvious here?

**Comment by aaweb** [comment]
Looks like this was a problem with Xcode 7.3, see workaround:
https://github.com/NativeScript/nativescript-cli/issues/1639

**Comment by EddyVerbruggen** [comment]
Ouch. Thanks for the update!
