### ISSUE TITLE
 Could not find any version that matches com.google.firebase:firebase-storag e:9.8.+ Error while tns run android

### ISSUE THREAD

**Issue by LakshmiEvana** [EddyVerbruggen/nativescript-plugin-firebase#220]
After adding firebase and doing tns run android iam facing this issue
![image](https://cloud.githubusercontent.com/assets/17317992/20515559/4bb799b2-b0b8-11e6-86c2-e74f8d13f8f2.png)

**Comment by EddyVerbruggen** [comment]
Check [this](https://github.com/EddyVerbruggen/nativescript-plugin-firebase#android) out and let me know if that works for you.

**Comment by LakshmiEvana** [comment]
Iam following same link,all the steps provided by you are done but no use.

**Comment by EddyVerbruggen** [comment]
So is 9.8.0 in `c:/program files (x86)/android/android-sdk/extras/android/m2repository/com/google/firebase/firebase-core` like on my machine (see screenshot)? If not you'll need to run the SDK manager again..

<img width="540" alt="screen shot 2016-11-22 at 10 34 34" src="https://cloud.githubusercontent.com/assets/1426370/20518392/58fff204-b09f-11e6-8339-4dfe1c59451b.png">

**Comment by xavica** [comment]
+1

Not sure why i don't see google folder in android/m2repository. my folder structure are appeared as below.

**Comment by EddyVerbruggen** [comment]
@xavica While you're at it, can you also provide a screenshot of the Android SDK manager? Especially this bit at the bottom:

<img width="667" alt="screen shot 2016-11-22 at 12 52 33" src="https://cloud.githubusercontent.com/assets/1426370/20522843/95a7185a-b0b2-11e6-80a2-e530d7bb0e9f.png">
