### ISSUE TITLE
Failed to find find module 'platform'

### ISSUE THREAD

**Issue by JaganJonnala** [EddyVerbruggen/nativescript-plugin-firebase#224]
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 

Error calling module function 

Error calling module function 

Error calling module function 

Error: com.tns.NativeScriptException: Failed to find module: "platform", relative to: /app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:220)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:244)
    com.tns.Runtime.run(Runtime.java:238)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
    android.app.ActivityThread.-wrap1(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.j

**Comment by JaganJonnala** [comment]
I have followed the instructions from the repository about the firebase from you but its howing the error as above. for last 30 days i had running my app with development by following that one only your reposiotory but now its not working by adding firebase to the new app

**Comment by EddyVerbruggen** [comment]
`platform` is a core module, not this plugin.. perhaps re-add your Android platform?

**Comment by v-r-sankar** [comment]
I am having this issue as well. I am trying to run the Groceries App (Angular version). Screenshot attached
![image](https://cloud.githubusercontent.com/assets/3470205/21091108/39b137c0-c06a-11e6-9e55-67895f3183ed.png)

**Comment by EddyVerbruggen** [comment]
[Looks like you were able to resolve your issue.](https://github.com/NativeScript/NativeScript/issues/3281) Closing.

**Comment by FuchurKool** [comment]
Hi all!

I get the same exception when I try to run the example. Even when I remove the node_modules and platforms folder... Any ideas?

Also, the "copy to clipboard" button doesn't work :/

Currently using 

node |     6.9.1 
nativescript     │ 2.4.2           │ 2.4.2
tns-core-modules │ 2.4.4           │ 2.4.4
tns-android      │ 2.4.1           │ 2.4.1
tns-ios          │ 2.4.0           │ 2.4.0

**Comment by v-r-sankar** [comment]
Start the emulator externally. That did the trick for me.

**Comment by FuchurKool** [comment]
Unfortunately, this didn't work for me. 

What I tried:
1)  .../android-sdk/tools -> cmd -> emulator -avd  Emulator-Api25-Default
2) .../sample-Groceries -> cmd -> tns run android

Same error :/

**Comment by thakurarun** [comment]
![image](https://cloud.githubusercontent.com/assets/5906747/22559399/f18a648e-e996-11e6-9a57-b63cebedf44b.png)

Grocery app is broken and 

> tns doctor

 say everything is fine.
![image](https://cloud.githubusercontent.com/assets/5906747/22559504/4f610c98-e997-11e6-8b8e-30120145b2df.png)

**Comment by samwil** [comment]
I have the same issue so I did what was suggested, which is to do: tns platform remove android and tns platform add android. But then it gives me this error: Build failed command gradlew.bat failed with exit code 1. So I go to the directory  ..\platforms\android\ and I write this command:  ./gradlew clean. And now when I tns run android it takes me to the original problem of: Error calling module function. I'm going in a circle here!

I need help, any idea what's going on?

**Comment by amittiwari725** [comment]
![screenshot_2018-12-06-15-42-41-550_org nativescript drawer](https://user-images.githubusercontent.com/45282503/49578034-cd3f5a00-f96e-11e8-9720-9c1b23467239.png)
can anyone tell me why I am getting this error??
