### ISSUE TITLE
Cannot find how to link anonymous account to other login type

### ISSUE THREAD

**Issue by kevinklinegargar** [EddyVerbruggen/nativescript-plugin-firebase#226]
Hi Everyone,

There's no function to link an  email and password credential to the firebase anonymous account?

Similar of this -- http://stackoverflow.com/questions/39088876/firebase-convert-anonymous-user-account-to-permanent-account-error

**Comment by kevinklinegargar** [comment]
Anyone can confirm if there's a function integrated with this plugin to link other accounts type to anonymous account?

**Comment by kevinklinegargar** [comment]
@EddyVerbruggen Can you help me?

**Comment by EddyVerbruggen** [comment]
The plugin should automatically link an existing account when logged on with it and authenticating with Google or Facebook.

I didn't do this for email (yet) though.

**Comment by kevinklinegargar** [comment]
Thanks @EddyVerbruggen . I'll give an update here once I tested on email account type

**Comment by RaphaelJenni** [comment]
The login with Google/Facebook works. But the data isn't fetched correctly. For example the name is missing. Beside that if you try to reauthenticate with this "converted" user, there is an error saying "Not currently logged in with Google". You first have to logout and login again.

**Comment by EddyVerbruggen** [comment]
@RaphaelJenni Can you point out in the Firebase iOS/Android documentation how that should work? I'm not sure it's incorrect what you're seeing.

**Comment by RaphaelJenni** [comment]
@EddyVerbruggen I checked the documentation and your code. It seems correct, but there is a problem with the authentication.

If I login with an anonymous user, convert the user to a google user, close the app, reopen it again and reauthenticate, the message "Not currently logged in with Google" message appears. If you try to delete the account this error appears "Deleting a user failed. Credentials too old."

Beside that, if you try to connect your account with a user who already has an account there is an error saying it cannot connect the two accounts but afterwards you are logged in as the other user and the data from the anonymous user is lost.

**Comment by RaphaelJenni** [comment]
@EddyVerbruggen Can you give an status update?

**Comment by EddyVerbruggen** [comment]
No update from me, over.

**Comment by RaphaelJenni** [comment]
Is it planned? Cause I'm gonna need that in the near feature. I can try to fix it by my self, but no guaranty that I solve it...

**Comment by EddyVerbruggen** [comment]
I try to look at every issue across many repo's. It's not possible for me to tell you when this one is up next. Please take a look if you have time, I'd be glad to review.

**Comment by RaphaelJenni** [comment]
Ok, I give it a try. But I'm not sure how much time I can spend...

**Comment by RaphaelJenni** [comment]
@EddyVerbruggen Fixed the first part. Having a look at the seconds part at the moment.

**Comment by RaphaelJenni** [comment]
Found out about the error with "Not currently logged in with Google" after linking the account.
Linking only links the accounts but doesn't sign in with that account. That means if you want to delete the account you either have to login with the other account or stay in your current account.

**Comment by RaphaelJenni** [comment]
@EddyVerbruggen Implemented email account linking #316

**Comment by EddyVerbruggen** [comment]
Thanks a lot @RaphaelJenni, merging!

**Comment by manvendrapratapsingh** [comment]
one issue I am facing is really strange.Log in via Facebook or Google in firebase auth than log out or install and log in with an anonymous user and linking with credential which is present in firebase(google or facebook) than I am not able to link the anonymous user with other social login profile? any solution?
