### ISSUE TITLE
Firebase Push Notification is not stacking in the system tray

### ISSUE THREAD

**Issue by manishmlv50** [EddyVerbruggen/nativescript-plugin-firebase#230]
The app is showing the notification messages received as individual notification. Is there anyway where I can stack the notifications in one.

This is how my notification bar looks like
https://cloud.githubusercontent.com/assets/7044255/20747646/dc4e1b96-b710-11e6-9091-68f30720a576.png
![screenshot_2016-11-30-15-19-25-256_com miui home](https://cloud.githubusercontent.com/assets/7044255/20747646/dc4e1b96-b710-11e6-9091-68f30720a576.png)

I want it to be clubbed together like it happens in gmail and whatsapp.
![notification_drawer](https://cloud.githubusercontent.com/assets/7044255/20747799/7bd1d1c6-b711-11e6-9dcf-bd7617194ea0.png)
https://cloud.githubusercontent.com/assets/7044255/20747799/7bd1d1c6-b711-11e6-9dcf-bd7617194ea0.png

Also my app doesnt receives notification when it is open. Is this a normal behaviour.  

Please help. Thank you

**Comment by SamuelGRwebfab** [comment]
I believe this is normal behavior for both the notifications not stacking and the notifications not appearing when the app is running.

The last project I did would not display them when the app was open
