### ISSUE TITLE
A network error with 3G connection

### ISSUE THREAD

**Issue by uzarsalan** [EddyVerbruggen/nativescript-plugin-firebase#232]
I trying to connect through 3G internet, and it give me an error.
Wi-Fi connection works great
![screenshot_2016-12-06-15-29-26-01](https://cloud.githubusercontent.com/assets/16972594/20918261/1c907fcc-bbd1-11e6-9a81-7ebae2646459.png)

**Comment by EddyVerbruggen** [comment]
I don't see what this plugin can do about that.. it already catches the FB error and invokes `reject` of the `login` promise.
