### ISSUE TITLE
the Notification doesn't work after solving #205

### ISSUE THREAD

**Issue by shinzao** [EddyVerbruggen/nativescript-plugin-firebase#234]
Hi,

After solving my problem (#205) about the crash of my app, my notification doesn't work  anymore (I can't receive a single one).

I add this in my plist : 
`<key>FirebaseAppDelegateProxyEnabled</key>
	<false/>`

This is more information about my settings : 
-node.js version : v5.9.0
-xCode version: v8.1
-OS : OS X El Capitan v10.11.6
-NativeScript CLI version : 2.4.0
-TNS version : 2.4.0
- nativescript-plugin-firebase : 3.8.4

I get this error on my debug when I'm running the app : 
`2016-12-06 11:39:01.782: <FIRInstanceID/WARNING> Failed to fetch APNS token Error Domain=com.firebase.iid Code=1001 "(null)"`

I m not sure if my problem is link to this error. Any idea of what to do ?

Thanks in advance,

**Comment by moreaup** [comment]
Hey guys can we have an update here, we need to deploy the application soon :/

**Comment by EddyVerbruggen** [comment]
Don't add `FirebaseAppDelegateProxyEnabled` to the plist, and update to 3.9.2.
