### ISSUE TITLE
Cloud Messaging: Error on tap notification

### ISSUE THREAD

**Issue by newapx** [EddyVerbruggen/nativescript-plugin-firebase#235]
Tap on the notifiction when the app is background.
Message in console: ` E adTracker: Value GCM-Notification of type java.lang.String cannot be converted to JSONObject`

**Comment by EddyVerbruggen** [comment]
Can you share some more details and reopen if it's still an issue please? I'd like to know how you generate the payload and what it is exactly. Also the device & android details would be welcome.
