### ISSUE TITLE
Notification message not shown when app is in the background

### ISSUE THREAD

**Issue by ViVer-7** [EddyVerbruggen/nativescript-plugin-firebase#237]
Hi, I have a problem using this plugin, could use some help here...

I'm using curl to post a notification message to Firebase, like so:

Headers:
```
Content-Type:application/json
Authorization:key=[MY_AUTH_KEY]
```

JSON:
```json
{
    "to" : "[MY_FIREBASE_KEY]",
    "content_available": true,
    "notification" : {
        "body" : "great match!",
        "title" : "Portugal vs. Denmark",
        "click_action": "helloworld",
        "icon": "notification_default",
        "sound" : "default",
	"priority": "high",
	"badge": 1
    }
}
```
Using the app sample code downloaded from Firebase, this works... So I know that my Firebase key and my authorization key are correct (and also my Apple certificate). When the app is in the background, I receive a sound and a notification in the notification centre on iOS.

Now I'm trying to use my own sample code, with the following result:
When the app is in the foreground, an event is triggered and I receive the data, so that works perfectly!
Now when the app is in the background, I would expect that (as in the sample above), iOS will play a sound, show a badge and display a notification in the notification centre....but it does not! Nothing happens...

Is something wrong with the plugin? Can anybody point me in the right direction?

Source code (main.ts) below:
```nativescript
// this import should be first in order to load some required settings (like globals and reflect-metadata)
import { platformNativeScriptDynamic } from "nativescript-angular/platform";

import { AppModule } from "./app.module";

import firebase = require("nativescript-plugin-firebase");

firebase.init({
  // Optionally pass in properties for database, authentication and cloud messaging,
  // see their respective docs and 'iOSEmulatorFlush' to flush token before init.
  iOSEmulatorFlush: true,
  onPushTokenReceivedCallback: function(token) {
      console.log("Firebase push token: " + token);
  },
  onMessageReceivedCallback: function(message) {
      console.dump(message);
      console.log("Title: " + message.title);
      console.log("Body: " + message.body);
      // if your server passed a custom property called 'foo', then do this:
//      console.log("Value of 'foo': " + message.foo);
    }
}).then(
  (instance) => {
    console.log("firebase.init done");
  },
  (error) => {
    console.log("firebase.init error: " + error);
  }
);

platformNativeScriptDynamic().bootstrapModule(AppModule);
```

**Comment by ViVer-7** [comment]
Been jiggling some more with it, but it seems that calling the firebase.init only succeeds when the app is installed and run for the first time. The onPushTokenReceivedCallback is called and then we can post notifications to it.

But then I close the app (runs in background) and start it up again. The init function triggers the following line in the log: Failed to fetch APNS token Error Domain=com.firebase.iid Code=1001.
Strange thing is, that I am able to send a notification using the 'previous' token...

**Comment by ViVer-7** [comment]
Okay, fail by me... Problem solved by adding 'priority': 'high' to the request...

**Comment by sudhanshu-15** [comment]
I am facing the same issue. The plugin is able to recognize the foreground push messages, but nothing happens when the application is in background. Tried changing the priority to high and still no luck. @ViVer-7 Can you suggest something?

**Comment by ViVer-7** [comment]
No, I'm sorry... setting the priority to high worked fine for me.
Don't know what else to try...

**Comment by simonettoa** [comment]
Hi @ViVer-7, did you solve if for iOS? I am able to the foreground but not the background (in Android it works).

Below the curl command I am using:

curl -X POST --header "Authorization: key=MY_KEY" --Header "Content-Type: application/json" https://fcm.googleapis.com/fcm/send -d "{\"notification\":{\"title\": \"My title\", \"text\": \"My text\", \"sound\": \"default\", \"priority\": \"high\", \"badge\":3}, \"data\":{\"foo\":\"bar\"}, \"to\": \"REAL_IOS_DEVICE_TOKEN\"}"

Any suggestions?

**Comment by EddyVerbruggen** [comment]
@simonettoa Did you also [configure this](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/MESSAGING.md#receiving-remote-notifications-in-the-background)?

**Comment by simonettoa** [comment]
@EddyVerbruggen  yes, below part of the Info.plist

        ...
	`	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIBackgroundModes</key>
	<array>
			<string>remote-notification</string>
	</array>
</dict>
</plist>`

I receive the notification in foreground but nothing in background, then if I open the app I see the notification (I see an alert, is what I've put)

**Comment by sudhanshu-15** [comment]
@simonettoa I am still stuck on this problem. Android works perfectly well but on iOS I can get the message in foreground but when the goes into background nothing happens. No clue how to fix this, I was hoping @EddyVerbruggen could help.

**Comment by EddyVerbruggen** [comment]
@sudhanshu-15 I'm looking at this later today with the demo app.

**Comment by EddyVerbruggen** [comment]
Confirmed it works correctly in [the demo app](https://github.com/EddyVerbruggen/nativescript-plugin-firebase-demo), but:

.. please make sure you've enabled Push notifications in Xcode as mentioned in the readme (I just made it stand out more [here](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/MESSAGING.md#enable-push-support-in-xcode).

Otherwise you'll only see foreground pushes.

This iOS push thing is HARD for all of us, so please be patient while configuring and testing it.

**Comment by simonettoa** [comment]
@EddyVerbruggen thanks, I will try and let you know asap!

**Comment by sudhanshu-15** [comment]
@EddyVerbruggen thanks for looking into this. I am pretty confident that I enabled Push notifications on xcode. Sorry but it is very early morning here so will check in sometime and let you know.

**Comment by EddyVerbruggen** [comment]
@sudhanshu-15 you may have removed and re-added the platforms/ios folder in the meanwhile. That would reset it.

**Comment by sudhanshu-15** [comment]
@EddyVerbruggen I am still not getting anything when the app is in background. I have enable the push notifications on Xcode.

![image](https://cloud.githubusercontent.com/assets/883233/22072172/82b56690-dd6f-11e6-86e6-90ed0f015ab0.png)

This is what I am seeing in my logs:

NativeScript loaded bundle file:///System/Library/Frameworks/UserNotifications.framework
2017-01-18 11:06:44.619 sunapsisiommobile[255] <Debug> [Firebase/Core][I-COR000001] Configuring the default app.
2017-01-18 11:06:44.695: <FIRInstanceID/WARNING> FIRInstanceID AppDelegate proxy enabled, will swizzle app delegate remote notifi
cation handlers. To disable add "FirebaseAppDelegateProxyEnabled" to your Info.plist and set it to NO
2017-01-18 11:06:44.696: <FIRInstanceID/WARNING> Failed to fetch APNS token Error Domain=com.firebase.iid Code=1001 "(null)"
2017-01-18 11:06:44.711: <FIRMessaging/INFO> FIRMessaging library version 1.2.0
2017-01-18 11:06:44.763 sunapsisiommobile[255:] <FIRAnalytics/INFO> Firebase Analytics v.3600000 started
2017-01-18 11:06:44.764 sunapsisiommobile[255:] <FIRAnalytics/INFO> To enable debug logging set the following application argumen
t: -FIRAnalyticsDebugEnabled (see http://goo.gl/Y0Yjwu)
2017-01-18 11:06:44.777: <FIRMessaging/WARNING> FIRMessaging AppDelegate proxy enabled, will swizzle app delegate remote notifica
tion receiver handlers. Add "FirebaseAppDelegateProxyEnabled" to your Info.plist and set it to NO
CONSOLE LOG file:///app/app.js:21:16: firebase.init done
NativeScript loaded bundle file:///var/containers/Bundle/Application/2285CD2B-9874-49C2-A682-8E79221A3065/sunapsisiommobile.app/F
rameworks/TNSWidgets.framework
2017-01-18 11:06:45.543 sunapsisiommobile[255] <Debug> [Firebase/Core][I-COR000018] Already sending logs.
NativeScript loaded bundle file:///System/Library/Frameworks/CoreGraphics.framework
2017-01-18 11:06:46.317 sunapsisiommobile[255] <Debug> [Firebase/Core][I-COR000019] Clearcut post completed.
2017-01-18 11:06:46.492 sunapsisiommobile[255] <Debug> [Firebase/Core][I-COR000019] Clearcut post completed.
2017-01-18 11:06:47.900 sunapsisiommobile[255:] <FIRAnalytics/INFO> Firebase Analytics enabled
CONSOLE LOG file:///app/tns_modules/nativescript-plugin-firebase/firebase.js:244:20: User granted push notifications? true

**Comment by EddyVerbruggen** [comment]
That "Failed to fetch APNS token Error Domain=com.firebase.iid Code=1001" is the problem, as long as you have that you won't see notifications in the background.

It's a pretty popular searchterm on Google.

Did you add you APNS certs to the developer console as well?

**Comment by sudhanshu-15** [comment]
@EddyVerbruggen I have my provisioning profile setup correctly. I also added APNS certs to developer console. I tried looking at possible solutions to "Failed to fetch APNS token Error Domain=com.firebase.iid Code=1001" but couldn't find anything substantial.

**Comment by EddyVerbruggen** [comment]
So...

Will you share your platforms/ios folder with me so I can take a look?

**Comment by sudhanshu-15** [comment]
Can I mail it to you?

**Comment by EddyVerbruggen** [comment]
That's ok, my email is on my github profile. Make sure to just zip your platforms/ios folder, I need the entire Xcode project.

**Comment by sudhanshu-15** [comment]
Done, shared it to you. You might have got a notification. It is on Google Drive.

**Comment by EddyVerbruggen** [comment]
Got it, thx

**Comment by EddyVerbruggen** [comment]
Comparing your and my project I see 1 important difference, can you try adding that and test again? If that doesn't fix it please zip the entire project (so I can run it), because as it turns out there's a dependency on ../../lib/ios as well which is not part of the zip :)

<img width="419" alt="screen shot 2017-01-18 at 20 30 10" src="https://cloud.githubusercontent.com/assets/1426370/22079674/fdb972ee-ddbc-11e6-8dbf-0775b42f85fd.png">

**Comment by sudhanshu-15** [comment]
Still getting the same error. After making changes to the entitlement file it disappears and I get this error again.
![image](https://cloud.githubusercontent.com/assets/883233/22080236/d33e7300-dd8c-11e6-9eea-d50f68892158.png)

Uploading the project file.

**Comment by EddyVerbruggen** [comment]
You'll need to fix that first.

**Comment by sudhanshu-15** [comment]
I keep trying to fix it but every time I run tns run ios it reappears again.

**Comment by EddyVerbruggen** [comment]
Hmm, this file is supposed to take care of adding the "APS environment", perhaps it's not there or there's an error in the script:

<img width="301" alt="screen shot 2017-01-18 at 20 50 18" src="https://cloud.githubusercontent.com/assets/1426370/22080412/d422db02-ddbf-11e6-8fe9-2a6f4c7cc67c.png">

So: is it there? If so, is there an error in the after prepare phase when doing a `tns run ios`?

**Comment by sudhanshu-15** [comment]
This is what I see once I reopen the Project in Xcode after running tns run ios.

![image](https://cloud.githubusercontent.com/assets/883233/22080598/25d5720c-dd8e-11e6-909e-e779f25d4e27.png)

![image](https://cloud.githubusercontent.com/assets/883233/22080610/31e74b56-dd8e-11e6-8a06-c1865ee5ff96.png)

I even tried to manually make changes to the entitlement file and saved it but the changes are discarded after tns run ios.

I can see the after-pepare file

![image](https://cloud.githubusercontent.com/assets/883233/22080737/a4fec4c0-dd8e-11e6-9039-c3ff4046b539.png)

I cannot see an error though.

**Comment by EddyVerbruggen** [comment]
So if you run `tns run ios`, then make the changes in Xcode (so that red exclamation mark is cleared), and then run the app *from Xcode* (pick your device at the top left and press the play button) that should make it all work.

In the meanwhile I'd like to have your entire project and see if I can figure out why that hook isn't working..

**Comment by sudhanshu-15** [comment]
I am trying to run it using Xcode, it is giving me this error:

![image](https://cloud.githubusercontent.com/assets/883233/22080971/a0609dde-dd8f-11e6-8265-a75cc0383f9d.png)

Looking the problem on google.
Have uploaded the project file on drive.

**Comment by EddyVerbruggen** [comment]
Oh damn, I think you'll need to delete that hook for now. It doesn't add the "APS environment" but only the keychainsharing stuff so it wipes your previous config. If you delete that hook script, then add the "APS environment" in Xcode again, then `tns run ios`, that should leave your Xcode config as it was. If you can confirm it's fine afterwards you should be able to receive background notifications.

And I have to figure out a way to make this work better.

**Comment by sudhanshu-15** [comment]
Sigh now getting this error:

![image](https://cloud.githubusercontent.com/assets/883233/22081986/db24e520-dd93-11e6-94bc-ab6563329dcf.png)

Not sure what to do.

**Comment by EddyVerbruggen** [comment]
You created a `.DS_Store` file by accident by accessing that folder with Finder (thanks, macOS!). Go to Terminal and remove it.

You can take this offline to email if you like (gets spammy!) - we'll post the result here.

**Comment by sudhanshu-15** [comment]
Sure

**Comment by jlooper** [comment]
hi, actually I'd be grateful if you'd keep debugging here if you don't mind. I'm having a TRULY HORRIBLE time getting anything working on iOS. I have worked with other push services before (Pushbots, Urban Airship, Parse, etc) and it's never been this hard. Crazy! What my experience is is that I can't get a push notification to work at all, foreground or in the background, on iOS, but I do get an alert that tells me what gets sent through the console. I'll keep tinkering.

**Comment by sudhanshu-15** [comment]
@jlooper here is the update so far, I tried removing the hook script as @EddyVerbruggen suggested but still the app is not able to receive notifications in background. I am still getting the <FIRInstanceID/WARNING> Failed to fetch APNS token Error Domain=com.firebase.iid Code=1
001 "(null)"
warning during initialisation. Not able to overcome this even though I rechecked the provisioning profiles and APNS certs.

**Comment by simonettoa** [comment]
@EddyVerbruggen I'm having the same behavior of @sudhanshu-15 
 In the log file I have the same output:
 
 `Successfully run application org.nativescript.firebaseTest on device with ID 4e4aeec59464a57d30ede11b8c1a14ede6fff1ae.

2017-01-19 12:38:50.640 firebaseTest[315] <Debug> [Firebase/Core][I-COR000001] Configuring the default app.

2017-01-19 12:38:50.657 firebaseTest[315:] <FIRAnalytics/INFO> Firebase Analytics v.3600000 started

2017-01-19 12:38:50.657 firebaseTest[315:] <FIRAnalytics/INFO> To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/Y0Yjwu)

2017-01-19 12:38:50.660 firebaseTest[315] <Info> [Firebase/Crash][I-CRA000004] Successfully enabled

2017-01-19 12:38:50.669: <FIRInstanceID/WARNING> FIRInstanceID AppDelegate proxy enabled, will swizzle app delegate remote notification handlers. To disable add "FirebaseAppDelegateProxyEnabled" to your Info.plist and set it to NO

2017-01-19 12:38:50.670: <FIRInstanceID/WARNING> Failed to fetch APNS token Error Domain=com.firebase.iid Code=1001 "(null)"

2017-01-19 12:38:50.674: <FIRMessaging/INFO> FIRMessaging library version 1.2.0

2017-01-19 12:38:50.707: <FIRMessaging/WARNING> FIRMessaging AppDelegate proxy enabled, will swizzle app delegate remote notification receiver handlers. Add "FirebaseAppDelegateProxyEnabled" to your Info.plist and set it to NO

2017-01-19 12:38:50.737 firebaseTest[315] <Debug> [Firebase/Core][I-COR000018] Already sending 
logs.
CONSOLE LOG file:///app/app.ts:40:18: **************** firebase.init done

2017-01-19 12:38:51.033 firebaseTest[315] <Debug> [Firebase/Core][I-COR000018] Already sending logs.

2017-01-19 12:38:51.127 firebaseTest[315] <Debug> [Firebase/Core][I-COR000019] Clearcut post completed.

2017-01-19 12:38:51.204 firebaseTest[315] <Debug> [Firebase/Core][I-COR000019] Clearcut post completed.

2017-01-19 12:38:51.262 firebaseTest[315] <Debug> [Firebase/Core][I-COR000019] Clearcut post completed.

2017-01-19 12:38:51.346 firebaseTest[315:] <FIRAnalytics/INFO> Firebase Analytics enabled

CONSOLE LOG file:///app/tns_modules/nativescript-plugin-firebase/firebase.js:244:20: User granted push notifications? true

CONSOLE LOG file:///app/main-view-model.ts:49:28: token from google cGNtdJ0uxAM:APA91bHp3sKfrv92B69RzN0e25pVnvt2K2PyGm9gTVsQd7Df3DENhngNRc_uf6VxdVg3ldWS1vdiHavolHLzImwWrRMXpkki1WdwrVj-O30L8bnHsuqDF6aocNphoqORFVtRwRrudA2_
`
 
 I've put the registration token event in a button, so after the load of the app. 
 I get the token, the notification arrives on foreground but NOT in background (and if the app is reduced and I re-open the app the notification is shown).
 
 I've tried to launch the app trough Xcode but I have the same messsage of sudhanshu-15 about --> 'clang: error: linker command failed with exit code 1 (use -v to see invocation)'
 I didn't understand what I am suppose to remove - the hook script!?!?

**Comment by sudhanshu-15** [comment]
@simonettoa You can remove the Hook script from the project folder if your entitlements file is getting changed every time you run `tns run`

**Comment by jlooper** [comment]
This is as far as I am able to get... I can signup for push, get a token, and get a message from Firebase as an alert, but it doesn't come as a true push.

![1](https://cloud.githubusercontent.com/assets/1450004/22118755/fe77ba1c-de46-11e6-8868-fb9e4ce0f283.PNG)
![2](https://cloud.githubusercontent.com/assets/1450004/22118754/fe776c06-de46-11e6-9069-6c4212cb7e4a.PNG)
![3](https://cloud.githubusercontent.com/assets/1450004/22118753/fe764f74-de46-11e6-8022-61afc4ed9a81.PNG)

**Comment by jlooper** [comment]
...and to pile on to poor @EddyVerbruggen my logs are the same: (what's all that about APNS token Error and swizzling?)

2017-01-19 13:09:55.229: <FIRInstanceID/WARNING> FIRInstanceID AppDelegate proxy enabled, will swizzle app delegate remote notification handlers. To disable add "FirebaseAppDelegateProxyEnabled" to your Info.plist and set it to NO
2017-01-19 13:09:55.229: <FIRInstanceID/WARNING> Failed to fetch APNS token Error Domain=com.firebase.iid Code=1001 "(null)"
2017-01-19 13:09:55.248: <FIRMessaging/INFO> FIRMessaging library version 1.2.0
2017-01-19 13:09:55.298: <FIRMessaging/WARNING> FIRMessaging AppDelegate proxy enabled, will swizzle app delegate remote notification receiver handlers. Add "FirebaseAppDelegateProxyEnabled" to your Info.plist and set it to NO

**Comment by sudhanshu-15** [comment]
Guess we all are facing the same issue. As per my conversation with @EddyVerbruggen the root cause of not getting a true push is:

<FIRInstanceID/WARNING> Failed to fetch APNS token Error Domain=com.firebase.iid Code=1001 "(null)"

Google search of this issue did yield any fruitful result. Let's hope we can find a solution soon.

**Comment by EddyVerbruggen** [comment]
@jlooper Can you send me your project so I can zoom in on your issue as well?

**Comment by EddyVerbruggen** [comment]
@jlooper AFAIK it boils down to the file /platforms/ios/yourappname/Resources/yourappname.entitlements - that should look like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>aps-environment</key>
	<string>development</string>
	<key>keychain-access-groups</key>
	<array>
		<string>$(AppIdentifierPrefix)your.package.id</string>
	</array>
</dict>
</plist>
```

The important bit being:

```xml
	<key>aps-environment</key>
	<string>development</string>
```

I can confirm the full project @sudhanshu-15 gave me lacks it and like I said I will investigate ways to  add it. Once I have *new* info I will of course add it here.

**Comment by jlooper** [comment]
Mine looks correct, as per the model above. There may be more info on this thread: https://github.com/firebase/quickstart-ios/issues/111

**Comment by sudhanshu-15** [comment]
@EddyVerbruggen even after removing the entitlement hook script, the entitlements file is being overwritten every time I `tns run ios`. I manually added:

`      <key>aps-environment</key>
	<string>development</string>
`

But it gets overwritten every time.

**Comment by EddyVerbruggen** [comment]
@samuelagm Yeah I rechecked the hook script and it actually looks for an existing script and doesn't touch it if it exists already.

@jlooper Sounds like you should be ok from the plugin side. I'd love to check your firebase console and certificates at this point.

**Comment by sudhanshu-15** [comment]
@EddyVerbruggen thanks a lot for helping out. I am available whenever you are ready to look into this again.

**Comment by simonettoa** [comment]
@EddyVerbruggen btw thanks a lot for help us

**Comment by EddyVerbruggen** [comment]
Please update to 3.9.2 and take note of the update [messaging instructions](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/MESSAGING.md#ios), let me know if issues remain afterwards.

**Comment by sudhanshu-15** [comment]
@EddyVerbruggen it works like a charm!! Thanks a lot!! Now getting push notifications even when the app is in background.

**Comment by EddyVerbruggen** [comment]
That's quick, thanks for letting me know :)

**Comment by simonettoa** [comment]
Hi there, it's still not working for me. What i've done:
- updated the package.json file with the new version, delete the app from the real device, delete node_modules folder and platforms folder.
- tns install | then tns run ios (just to create the ios project, in my scenario is not possible to run the app directly until I install it using Xcode and passing it thorough Xcode --> Window --> Devices)
- opened the Xcode project and turned on the push notifications in Capabilities
- checked the myAppName.entitlements file, it was already in the right folder [app/App_Resources/iOS/] and it had all the lines per instructions
- tried to delete the firebase-install-ios-entitlements.js, but it was not present in the hooks/after-prepare/ folder
- copied the *ipa file using the Xcode --> Window --> Devices
- run tns run ios

then the logs are similar than the old one with the same APNS failed error

`Project successfully built
Successfully deployed on device with identifier '4e4aeec59464a57d30ede11b8c1a14ede6fff1ae'.
Mounting /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/10.1 (14B72)/DeveloperDiskImage.dmg
[Mounting] LookingUpImage
Successfully run application org.nativescript.firebaseTest on device with ID 4e4aeec59464a57d30ede11b8c1a14ede6fff1ae.
2017-01-23 08:35:22.092 firebaseTest[1317] <Debug> [Firebase/Core][I-COR000001] Configuring the default app.
2017-01-23 08:35:22.108 firebaseTest[1317:] <FIRAnalytics/INFO> Firebase Analytics v.3600000 started
2017-01-23 08:35:22.108 firebaseTest[1317:] <FIRAnalytics/INFO> To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/Y0Yjwu)
2017-01-23 08:35:22.109 firebaseTest[1317] <Info> [Firebase/Crash][I-CRA000004] Successfully enabled
2017-01-23 08:35:22.117: <FIRInstanceID/WARNING> Failed to fetch APNS token Error Domain=com.firebase.iid Code=1001 "(null)"
2017-01-23 08:35:22.127: <FIRMessaging/INFO> FIRMessaging library version 1.2.0
2017-01-23 08:35:22.183 firebaseTest[1317] <Debug> [Firebase/Core][I-COR000018] Already sending logs.
CONSOLE LOG file:///app/app.ts:40:18: **************** firebase.init done
2017-01-23 08:35:22.368 firebaseTest[1317] <Debug> [Firebase/Core][I-COR000019] Clearcut post completed.
2017-01-23 08:35:22.984 firebaseTest[1317] <Debug> [Firebase/Core][I-COR000019] Clearcut post completed.
2017-01-23 08:35:23.310 firebaseTest[1317:] <FIRAnalytics/INFO> Firebase Analytics enabled
CONSOLE LOG file:///app/main-view-model.ts:49:28: token from google eqUNe0zQ580:APA91bEYEAm_YZHA_Z_gpU4WrCoqJD-HbLqWiGhBpNHhAiD2MnKS6zD8_AwMky562yKdam3ZU8096sfzbbiKE0eR90GnFkATJ__MzOlq17U4B41w7sJHZpiU6YkXoVMwG8gXbaqsrWZJ`

I came from Xamarin, so to check if it's a certificate issue, I've created a small project and checked the notifications.
I've tested in debug mode with the SandBox development certificate and also in Ad hoc distribution with the Production certificate, both work as expected foreground and background. 

I don't know what else to do, if you want @EddyVerbruggen I can send you my project, maybe there's something I haven't done correctly.
Let me know if you want/can to do and what you need. Thanks in advance.

**Comment by simonettoa** [comment]
Btw I was able to launch the app through Xcode, but still same message error/warning and same result, foreground works, background not. And this is a *.ts simple project made just to test firebase notifications.

**Comment by EddyVerbruggen** [comment]
@simonettoa can you send the entire project?

**Comment by simonettoa** [comment]
@EddyVerbruggen I just shared a folder in dropbox with the entire project, thanks! I used your email address from github.

**Comment by EddyVerbruggen** [comment]
@simonettoa You're doing everything right, except you need to remove `<key>FirebaseAppDelegateProxyEnabled</key><false/>` from app/app_resources/ios/xx.plist

**Comment by simonettoa** [comment]
@EddyVerbruggen it works...that was the error; THANKS A LOT!!!

Still in the log I can see the same 'warning'. Just for the record.

> 2017-01-24 14:17:37.236 firebaseTest[1654:] <FIRAnalytics/INFO> To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/Y0Yjwu)
2017-01-24 14:17:37.236 firebaseTest[1654:] <FIRAnalytics/INFO> Successfully created Firebase Analytics App Delegate Proxy automatically. To disable the proxy, set the flag FirebaseAppDelegateProxyEnabled to NO in the Info.plist
2017-01-24 14:17:37.237 firebaseTest[1654] <Info> [Firebase/Crash][I-CRA000004] Successfully enabled
2017-01-24 14:17:37.245: <FIRInstanceID/WARNING> FIRInstanceID AppDelegate proxy enabled, will swizzle app delegate remote notification handlers. To disable add "FirebaseAppDelegateProxyEnabled" to your Info.plist and set it to NO
2017-01-24 14:17:37.246: <FIRInstanceID/WARNING> Failed to fetch APNS token Error Domain=com.firebase.iid Code=1001 "(null)"
2017-01-24 14:17:37.248: <FIRMessaging/INFO> FIRMessaging library version 1.2.0
2017-01-24 14:17:37.279: <FIRMessaging/WARNING> FIRMessaging AppDelegate proxy enabled, will swizzle app delegate remote notification receiver handlers. Add "FirebaseAppDelegateProxyEnabled" to your Info.plist and set it to NO
2017-01-24 14:17:37.310 firebaseTest[1654] <Debug> [Firebase/Core][I-COR000018] Already sending logs.
CONSOLE LOG file:///app/app.ts:40:18: **************** firebase.init done
...

**Comment by hairen** [comment]
@EddyVerbruggen  Could you provide more details on how did you help @sudhanshu-15 out? I'm encountering the same problem now, foreground push works, but not background push. I'm using nativescript-plugin-firebase v3.11.3. Thanks!
