### ISSUE TITLE
fAuth.signInWithCustomToken is not a function

### ISSUE THREAD

**Issue by elinswilberg** [EddyVerbruggen/nativescript-plugin-firebase#239]
Hi @EddyVerbruggen 

I'm getting this error when I'm trying to log in with a custom token:

```fAuth.signInWithCustomToken is not a function (In fAuth.signInWithCustomToken(arg.token, onCompletion), fAuth.signInWithCustomToken is undefined```

firebase is initialized, and everything else seems to work ok.

I'm using the plugin with Angular2/NS 2.4.2.

**Comment by sivsushruth** [comment]
Even I am facing the same issue, any updates ?

**Comment by elinswilberg** [comment]
No, sorry, @sivsushruth, I haven't really had the time to look deeper into this, but everything else works (login with email/password etc.), so there must be something with the Custom Token login.

**Comment by EddyVerbruggen** [comment]
Looks like a bug on iOS to me. Please retest when 3.9.0 is released (likely tomorrow).

**Comment by elinswilberg** [comment]
@EddyVerbruggen Yey, it works perfectly now. Great work!

**Comment by stephan-fischer** [comment]
@elinswilberg  how can i call it?
`  firebase.auth().signInWithCustomToken("mytoken")`?

Thank you!
