### ISSUE TITLE
Crash reporting slows startup time

### ISSUE THREAD

**Issue by PanayotCankov** [EddyVerbruggen/nativescript-plugin-firebase#240]
Removing:
```
compile "com.google.firebase:firebase-crash:9.8.+"
```
from the include.gradle seems to boost startup time from 3.5sec. to 2.8sec. on some of our devices.
Probably crash reporting should be optional similar to the way push notifications are prompted during installation.

**Comment by EddyVerbruggen** [comment]
Sounds like a good idea, or perhaps it can be lazily loaded. Have you seen similar reports on the web for the Android Firebase SDK?
