### ISSUE TITLE
iOS: Push Notifications not working in Background or when application is reopened

### ISSUE THREAD

**Issue by sudhanshu-15** [EddyVerbruggen/nativescript-plugin-firebase#243]
I am facing this issue where the application is able to receive push notification when in foreground but does nothing when in background. There is no sound, no badge data, no notification in the notification. I followed the issues previously created for this but couldn't find anything substantial. I tried the suggestions made by others to resolve this, like setting the priority high but nothing works. The application works flawlessly on Android.
Moreover the push notifications stop working altogether when the application is reopened.
Can someone help me on this or point me to the right direction?

**Comment by sudhanshu-15** [comment]
Can someone please suggest a fix for this?

**Comment by sasidhar678** [comment]
+1

**Comment by sudhanshu-15** [comment]
#237 same issue

**Comment by EddyVerbruggen** [comment]
Please update to 3.9.2 and take note of the update [messaging instructions](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/MESSAGING.md#ios), let me know if issues remain afterwards.

**Comment by sudhanshu-15** [comment]
@EddyVerbruggen it seems the issue has returned. The background notification stopped working again. I tried following the instructions like the last time but it no longer works. Rechecked my APNS certs, Provisioning Profile and they seem to be in place. Checked XCode and things are as they are supposed to be.

![image](https://cloud.githubusercontent.com/assets/883233/22520041/bd03f7e6-e880-11e6-87f4-9d5d057271c6.png)

![image](https://cloud.githubusercontent.com/assets/883233/22520076/dd5b67cc-e880-11e6-9fa5-109d927ec6ae.png)

![image](https://cloud.githubusercontent.com/assets/883233/22520103/f95d1cfe-e880-11e6-849a-8a296b3970ff.png)

![image](https://cloud.githubusercontent.com/assets/883233/22520164/4211ddcc-e881-11e6-9013-8bc91aa52c0a.png)

Can you please look into this? Thanks a lot.

**Comment by EddyVerbruggen** [comment]
I'll need your project then.

**Comment by sudhanshu-15** [comment]
Sending in few mins.

**Comment by sudhanshu-15** [comment]
Sent. Thanks!

**Comment by EddyVerbruggen** [comment]
@sudhanshu-15 You have plugin version 3.9.0 in your iOS project. This sh** was fixed in 3.9.2.

**Comment by sudhanshu-15** [comment]
Ohh darn! I did update my plugin :/ this is strange. Let me update and get back to you. Thanks a lot for looking.

**Comment by sudhanshu-15** [comment]
I was missing the updated plugin version some how, fixed it and now it is working as expected.
