### ISSUE TITLE
Re-Authenticate a user

### ISSUE THREAD

**Issue by RaphaelJenni** [EddyVerbruggen/nativescript-plugin-firebase#245]
In the official Firebase docuentation, there is a method to re-authenticate a user if his session is too old.
https://firebase.google.com/docs/auth/web/manage-users#re-authenticate_a_user

This method is missing in the plugin, and I haven't found a nice way yet to solve that problem.
This should be implemented as well in the nativescript-firebase-plugin.

**Comment by EddyVerbruggen** [comment]
Good idea. For my reference: [iOS](https://firebase.google.com/docs/auth/ios/manage-users), [Android](https://firebase.google.com/docs/auth/android/manage-users).
