### ISSUE TITLE
Device_Token not getting to send notifications

### ISSUE THREAD

**Issue by LakshmiEvana** [EddyVerbruggen/nativescript-plugin-firebase#247]
Iam not getting any Device_Token using addOnPushTokenReceivedCallback(),onPushTokenReceivedCallback().

**Comment by EddyVerbruggen** [comment]
If you're still not able to get it, then 4.0.0 (will be released today) adds a new method to [get the token on demand](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/31a7f3be12265dd3765d44c8a32185c01745e164/docs/MESSAGING.md#retrieving-the-push-registration-token).
