### ISSUE TITLE
changePassword() not validating old password

### ISSUE THREAD

**Issue by LakshmiEvana** [EddyVerbruggen/nativescript-plugin-firebase#248]
Not validating the old  password while using changePasword().Password successfully updating even old password wrong also.

**Comment by EddyVerbruggen** [comment]
If anything that's an issue with Firebase, not this plugin I guess?

**Comment by LakshmiEvana** [comment]
i have impletmented the changePassword method which is written by you only
is it working fine in your code...?

**Comment by EddyVerbruggen** [comment]
Your code is fine, it's just that changing the password with the Firebase SDK doesn't require the old password. The only requirement is that the uses should have logged in recently (with their old password, of course). See https://firebase.google.com/docs/auth/ios/manage-users#set_a_users_password

**Comment by b02505048** [comment]
Am using NativeScript Vue and every time I called  
```
firebase.changePassword({
    email: this.userEmail,
    oldPassword: this.userOldPassword,
    newPassword: this.userNewPassword
  }).then(() => {
        // called when password change was successful
  }).catch(errorMessage) => {
        console.log(errorMessage);
  });
```
```
JS: '--- changed pwd: com.google.android.gms.tasks.zzu@7796d21'
JS: 'Updating password failed'
```
The `errorMessage` will be thrown no matter the old password is correct or not.
If reauth the user is needed, then in what way should we call the `changePassword` API? Thank you
