### ISSUE TITLE
Gradle build error when nativescript-google-maps-sdk is added

### ISSUE THREAD

**Issue by lukashlobil** [EddyVerbruggen/nativescript-plugin-firebase#250]
Hi,
I have the same issue as some have had before me.
While trying to run the app I get 

> Script .../platforms/android/configurations/nativescript-plugin-firebase/include.gradle' line: 43
 Failed to apply plugin [id 'com.google.gms.google-services']
    For input string: "+"

The video tutorial talks about build.gradle, which I guess is deprecated now. 

I am also using dapriett's google-maps-sdk plugin, which works fine - I haven't specified google services' version there. 

I tried fiddling with the ext property in app.gradle and also tried hardcoding the version in include.gradle of your plugin. 

I have updated my android dependencies using android update sdk and checked - I have the last versions. 

Does someone have some pointers to help me out please?

**Comment by EddyVerbruggen** [comment]
I'd like to help but I need your entire project to figure it out.

**Comment by lukashlobil** [comment]
Hi Eddie,
thanks for quick response - I assumed, you'd need to see the project so I tried to recreate it on a simple project, where it worked instantly. So I tried adding google-maps-sdk plugin and that's when it stopped building. I will do some more investigating and then come back with either the solution or the files for the project. 
Thanks

**Comment by lukashlobil** [comment]
Hi Eddie,
I forked your demo repo (runs fine), typed

> tns plugin add nativescript-google-maps-sdk

and immediately I am getting the error.

So it seems it is interaction of the two plugins. I checked [this issue](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/86), but nothing there helps me.

Now I am able to run your plugin or his plugin, but not together. You can see the code on the forked repo, although I just installed the other plugin.

I have noticed, right after merging dex messages I am getting these:

> Skip com.google.android.gms.internal.zzt
        Error: java.lang.NullPointerException
Skip com.google.android.gms.internal.zzw
        Error: java.lang.NullPointerException
Skip com.google.android.gms.internal.zzy
        Error: java.lang.NullPointerException
Skip com.google.android.gms.internal.zzz
        Error: java.lang.NullPointerException
( it happens everytime, but everything worked, so I paid no attention to it). I apologize in advance if it's only my machine...

**Comment by EddyVerbruggen** [comment]
Hi, thanks for those details! I will do the same and let you know what the results are on my machine.

**Comment by EddyVerbruggen** [comment]
Luckily, same issue on my machine so I'll try and figure this out soon.

**Comment by EddyVerbruggen** [comment]
Can you try something to make these two work together? We may need to tell the project which version of play services we want to use.

Open `app/App_Resources/Android/app.gradle` and add:

```gradle
android {  
  ....
  project.ext {
    googlePlayServicesVersion = "9.8.+"
  }
}
```

**Comment by lukashlobil** [comment]
Thanks Eddy, that fixed it right away!

**Comment by EddyVerbruggen** [comment]
Awesome, added that info to the readme as I don't think a plugin should try to automate that.

**Comment by phatakrajan** [comment]
I am facing exactly same issue but the resolution of adding 

android {  
  // other stuff here
  project.ext {
    googlePlayServicesVersion = "9.8.+"
  }
}
is not helping. I get following issue after that

Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 9.8.+.

I tried with different versions is 11.0, 9.8 etc. How to identify rootcause and fix this issue?

**Comment by edyrkaj** [comment]
hi @EddyVerbruggen, using
`
"tns-android": {
  "version": "5.0.0"
}
`    

`tns build android` failed
Command ./gradlew failed with exit code 1
