### ISSUE TITLE
User's profile update

### ISSUE THREAD

**Issue by rcluan** [EddyVerbruggen/nativescript-plugin-firebase#251]
Hello, is there any support for updating a user's profile? I've found this on firebase documentation regarding the profile update on android applications.

```
FirebaseUser user = FirebaseAuth.getInstance().getCurrentUser();

UserProfileChangeRequest profileUpdates = new UserProfileChangeRequest.Builder()
        .setDisplayName("Jane Q. User")
        .setPhotoUri(Uri.parse("https://example.com/jane-q-user/profile.jpg"))
        .build();

user.updateProfile(profileUpdates)
        .addOnCompleteListener(new OnCompleteListener<Void>() {
            @Override
            public void onComplete(@NonNull Task<Void> task) {
                if (task.isSuccessful()) {
                    Log.d(TAG, "User profile updated.");
                }
            }
        });
```

But it seems the User interface on this plugin does not have a updateProfile(). Is it correct or the update can be achieved using another method?

Cheers.

**Comment by EddyVerbruggen** [comment]
[Here ya go](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/AUTHENTICATION.md#updating-a-profile)

**Comment by rcluan** [comment]
Thanks @EddyVerbruggen 

I followed the tutorial but this message was given: 

> Property 'updateProfile' does not exist on type 'typeof "/home/rcluan/Luan/Projects/DiMoto/node_modules/nativescript-plugin-firebase/index"'

Taking a closer look to the plugin's index.d.ts I couldn't find the updateProfile method. Perhaps it's not available for the Typescript version or I'm using an older version. What do you think?

**Comment by EddyVerbruggen** [comment]
If you're not on 3.9.0 then you should update to get [this](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/index.d.ts#L541)

**Comment by rcluan** [comment]
Yeah, I reinstalled the plugin and the method appeared on the index.d.ts. The ts compiler is not recognising it though, but I'll figure it out. Thanks again

**Comment by EddyVerbruggen** [comment]
Perhaps you'll need to do one full `tns run ios / android` for it to kick in.

Anyway: good luck!
