### ISSUE TITLE
onPushTokenReceivedCallback never called

### ISSUE THREAD

**Issue by burkard** [EddyVerbruggen/nativescript-plugin-firebase#253]
Hi,

The plugin works right, I can initialize it with the code below, and even login anonymously.

    firebase.init({
                    onPushTokenReceivedCallback: function(token) {
                        console.log("Firebase plugin received a push token: " + token);
                    },
                    
                    onMessageReceivedCallback: function(message) {
                        console.log("MESSAGE: "+JSON.stringify(message));
                    }
                }).then(
                    (instance) => {
                        console.log("firebase.init done =>> "+instance);
                        
                        firebase.login({
                            type: firebase.LoginType.ANONYMOUS
                        }).then(
                            function (result) {
                                console.log(JSON.stringify(result));
                                firebase.getAuthToken({forceRefresh: false}).then((data)=>{
// this function IS CALLED!
                                    console.log("data: "+JSON.stringify(data));
                                });
                                
                            },
                            function (errorMessage) {
                                console.log(errorMessage);
                            }
                        );    
                    },
                    (error) => {
                        console.log("firebase.init error: " + error);
                    }
                );

The problem is **the function onPushTokenReceivedCallback is NEVER called**.

What am I doing wrong?

**Comment by sasidhar678** [comment]
+1

**Comment by burkard** [comment]
@sasidhar678 no, I'm testing on two real devices (LG Leon 4g and Moto G2), both with Google Play Services, Gmail account, etc.

Have you experienced it too?

**Comment by sasidhar678** [comment]
Yes ! But now it's working fine with both emulator and real devices.

**Comment by burkard** [comment]
Could you please tell me how did you solved the issue?

**Comment by sasidhar678** [comment]
In my case, previously I tested on a Non-Google API's emulator. 

Did you add the two services in `AndroidManifest.xml` file ?

**Comment by burkard** [comment]
Yes, the services tags were added.

I'll try to test on the emulator using a different system image. Meanwhile, I'll be using the nativescript-push-notification plugin.

**Comment by sagesan** [comment]
I just had the same problem, you should try checking out the 
> node_modules\nativescript-plugin-firebase\platforms\android\include.gradle
for 
>     // Uncomment if you want FCM (Firebase Cloud Messaging)
>    compile "com.google.firebase:firebase-messaging:10.0.+"
If the compile... line is commented, that's the reason you don't ever receive tokens - messaging is not compiled in, and hence the callback is registered, but app never registers in Firebase for messages.

Un-comment, remove platform, build anew and let me know if that helped.

**Comment by manishmlv50** [comment]
I am facing the same issue. I receive the notification and the addOnMessageReceivedCallback() is called. But when the app is terminated. No notification is received by the device. Also, onPushTokenReceivedCallback() is never called when firebase is initiated. I have checked that the two services are added in AndroidManifest.xml and even firebase messaging is uncommented in the include.gradle

What could be the issue?

**Comment by Nikoms** [comment]
I had the same issue.
I removed hooks/platform/node_module et used tns-android "version": "3.1.0-next-2017-06-12-1864" and it worked

**Comment by samuelzv** [comment]
I followed the steps


tns platform remove android
tns platform add android
did the trick  :)

**Comment by nakorndev** [comment]
Pass 1 year still not fix this issue? I still have this problem.

**Comment by EddyVerbruggen** [comment]
@nakorndev Oh, sorry, forgot to close.
