### ISSUE TITLE
How to Regenerate the Firebase Cloud Messaging Token

### ISSUE THREAD

**Issue by sasidhar678** [EddyVerbruggen/nativescript-plugin-firebase#255]
How to get the Firebase Cloud Messaging token that already generated or how to generate a new one ?

Thanks in advance

**Comment by maddy2get** [comment]
I am looking to get the device_token as well for later use. Can I store it in local storage after receiving the token for the first time?

**Comment by sagesan** [comment]
You basically have to, apart from setting onPushTokenReceivedCallback callback, you can not reliably get the token already received as far as I know.

**Comment by ryanzaatari** [comment]
Same issue here, @EddyVerbruggen is there a way to get the token already generated? 
Would the "instance" object received from init() promise (if called again) has a method to get the token?

**Comment by EddyVerbruggen** [comment]
There is an API to get the current messaging token: https://firebase.google.com/docs/cloud-messaging/ios/client

I'll add it to the plugin, just in time for the 4.0.0 release (today/tomorrow).
