### ISSUE TITLE
iOS Notification not received in background mode

### ISSUE THREAD

**Issue by fsandreau** [EddyVerbruggen/nativescript-plugin-firebase#258]
I use this awesome plugin and I just added the Firebase notification feature,  It work only if the application state is activated (foreground). When the application is suspended or closed, I don’t receive any notification sent from firebase notification UI. Once the application is launched, all notifications are pushed.
Any ideas ?

**Comment by thomasmoon** [comment]
I am experiencing this too with the latest version of the plugin, though it has worked for me before.

These settings have to be added to the Info.plist, but other than that, not sure why this would be?

`
<key>UIBackgroundModes</key>
	<array>
	    <string>remote-notification</string>
	</array>`

**Comment by fsandreau** [comment]
Happy to see that I'm not the only one. 
Note that the same code works great with Android.

**Comment by sudhanshu-15** [comment]
#237 is the same issue.

**Comment by EddyVerbruggen** [comment]
I just tested with the demo app again and confirmed I was able to reproduce this issue (would only receive a notification in the foreground), but after [doing this](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/MESSAGING.md#enable-push-support-in-xcode) the pushes started appearing in the background as well.

Watch the devicelog closely right after the "This app wants to send you notifications" consent popup is accepted. That's when helpful hints may be emitted by Firebase as to why notifications may not work. Like in this case I got "Failed to fetch APNS token Error Domain=NSCocoaErrorDomain Code=3000 "no valid 'aps-environment' entitlement string found for application" UserInfo={NSLocalizedDescription=no valid 'aps-environment' entitlement string found for application}" and realized I had to toggle that switch in Xcode.

**Comment by EddyVerbruggen** [comment]
Please update to 3.9.2 and take note of the update [messaging instructions](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/MESSAGING.md#ios), let me know if issues remain afterwards.

**Comment by thomasmoon** [comment]
Hey Eddy, thanks for the update!

The background notifications work perfectly with plugin version 3.9.2, my Xcode settings were apparently correct.

The new instructions about the entitlements file are useful and the file seems to be copied to the write place when reinstalling the ios platform, however for some reason Xcode doesn't recognize the push notification settings from that file.  I had to open Xcode and toggle the switch for those, any idea why?  The background notifications on the other hand are recognized automatically from the Info.plist file.

**Comment by manishmlv50** [comment]
Hey Eddy, 
Thank for a wonderful plugin. I am facing the same issue in android. I get the notification and the addOnMessageReceivedCallback() method is called when the app is active, but when the app is in the background, no notifications are received. I am facing this issue in android. Please help.

**Comment by EddyVerbruggen** [comment]
@thomasmoon I'm afraid this no longer automatically works - so you need to correct that in Xcode indeed. I'm pondering a hook that will fix the entitlements though.

@manishmlv50 Most often folks have issues with iOS not Android. Is there any code I can look at?

**Comment by manishmlv50** [comment]
The code for the onMessageReceivedCallback is as follow : 
firebase.init({
    persist: true,
    onPushTokenReceivedCallback: function(token) {
    //   console.log("Firebase push token: " + token);
    },
    onMessageReceivedCallback: function(message) {
        alert(JSON.stringify(message));
      console.log("Title: " + message.title);
      console.log("Body: " + message.body);
      // if your server passed a custom property called 'foo', then do this:
      console.log("Value of 'foo': " + message.data.foo);
    },
    onAuthStateChanged: (data) => {
        console.log(data.loggedIn ? "Logged in to firebase" : "Logged out from firebase");
    }
}).then(
    (instance) => {
          console.log("firebase.init done");
        //   var token = com.google.firebase.iid.FirebaseInstanceId.getInstance().getToken();
        //   console.log( token.to );
        firebase.addOnPushTokenReceivedCallback((token)=> {
            console.log("Firebase push token: " + token);
        });
    },
    (error) => {
        // console.log("firebase.init error: " + error);
    }
);


The code for sending the notification is as follow : 


    http.request({
      url: "https://fcm.googleapis.com/fcm/send",
      method: "POST",
      headers: { 
        "Content-Type": "application/json" ,
        "Authorization" : "key=XXXXXXXXXXX"
      },
      content: JSON.stringify({ 
        "to": "/topics/news", 
        "collapse_key" : news,
        "data": { 
            "test": "test'
        }, 
        "notification": notification
      })
    }).then(function (response) {
      // push notification response
      console.log("Push Notification Response");
      console.dump(response);
    }, function (e) {
        console.log("Error occurred " + e);
    });


I am getting the notification when the app is open. But when the app is closed, I figured out the way to show notification. But the onMessageReceivedCallback method is not called when the app is opened from the notification

**Comment by EddyVerbruggen** [comment]
What was the problem with not receiving the notification while the app was in the background? May be helpful to others to know.

**Comment by manishmlv50** [comment]
The issue is not with the plugin but android avc:  denied  { unlink } for  pid=19488. So if I disconnect the device from debug mode. I get the notifications. But when I tap on that notification, the callback for messages is not called.

**Comment by manishmlv50** [comment]
Application launched on: Wed Mar 01 2017 12:30:18 GMT+0530 (IST)
JS: Error in firebase.addOnMessageReceivedCallback: Error: java.lang.NoSuchMethodError: no static method "Ljava/lang/Long;.toString()Ljava/lang/String;"
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1047)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1028)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1018)
JS:     com.tns.FragmentClass.onCreateView(android.app.Fragment.java)
JS:     android.app.Fragment.performCreateView(Fragment.java:2053)
JS:     android.app.FragmentManagerImpl.moveToState(FragmentManager.java:894)
JS:     android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
JS:     android.app.BackStackRecord.run(BackStackRecord.java:833)
JS:     android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
JS:     android.app.Activity.performResume(Activity.java:6090)
JS:     android.app.ActivityThread.performResumeActivity(ActivityThread.java:3131)
JS:     android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3173)
JS:     android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2535)
JS:     android.app.ActivityThread.access$900(ActivityThread.java:163)
JS:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1358)
JS:     android.os.Handler.dispatchMessage(Handler.java:102)
JS:     android.os.Looper.loop(Looper.java:135)
JS:     android.app.ActivityThread.main(ActivityThread.java:5536)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     java.lang.reflect.Method.invoke(Method.java:372)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1397)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1192)
JS: granted





EXCEPTION: Uncaught (in promise): Error: java.lang.NoSuchMethodError: no static method "Ljava/lang/Long;.toString()Ljava/lang/String;"
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1047)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1028)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1018)
JS:     com.tns.FragmentClass.onCreateView(android.app.Fragment.java)
JS:     android.app.Fragment.performCreateView(Fragment.java:2053)
JS:     android.app.FragmentManagerImpl.moveToState(FragmentManager.java:894)
JS:     android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
JS:     android.app.BackStackRecord.run(BackStackRecord.java:833)
JS:     android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
JS:     android.app.Activity.performResume(Activity.java:6090)
JS:     android.app.ActivityThread.performResumeActivity(ActivityThread.java:3131)
JS:     android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3173)
JS:     android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2535)
JS:     android.app.ActivityThread.access$900(ActivityThread.java:163)
JS:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1358)
JS:     android.os.Handler.dispatchMessage(Handler.java:102)
JS:     android.os.Looper.loop(Looper.java:135)
JS:     android.app.ActivityThread.main(ActivityThread.java:5536)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     java.lang.reflect.Method.invoke(Method.java:372)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1397)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1192)
JS: ORIGINAL STACKTRACE:
JS: Error: Uncaught (in promise): Error: java.lang.NoSuchMethodError: no static method "Ljava/lang/Long;.toString()Ljava/lang/String;"
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1047)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1028)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1018)
JS:     com.tns.FragmentClass.onCreateView(android.app.Fragment.java)
JS:     android.app.Fragment.performCreateView(Fragment.java:2053)
JS:     android.app.FragmentManagerImpl.moveToState(FragmentManager.java:894)
JS:     android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
JS:     android.app.BackStackRecord.run(BackStackRecord.java:833)
JS:     android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
JS:     android.app.Activity.performResume(Activity.java:6090)
JS:     android.app.ActivityThread.performResumeActivity(ActivityThread.java:3131)
JS:     android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3173)
JS:     android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2535)
JS:     android.app.ActivityThread.access$900(ActivityThread.java:163)
JS:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1358)
JS:     android.os.Handler.dispatchMessage(Handler.java:102)
JS:     android.os.Looper.loop(Looper.java:135)
JS:     android.app.ActivityThread.main(ActivityThread.java:5536)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     java.lang.reflect.Method.invoke(Method.java:372)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1397)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1192)
JS:     at resolvePromise (file:///data/data/com.one.develop/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:416:31)
JS:     at file:///data/data/com.one.develop/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:393:13
JS:     at file:///data/data/com.one.develop/files/app/tns_modules/nativescript-plugin-firebase/firebase.js:278:7
JS:     at new ZoneAwarePromise (file:///data/data/com.one.develop/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:465:29)
JS:     at Object.firebase.addOnMessageReceivedCallback (file:///data/data/com.one.develop/files/app/tns_modules/nativescript-plugin-firebase/firebase.js:252:10)
JS:     at new AppComponent (file:///data/data/com.one.develop/files/app/app.component.js:53:18)
JS:     at new Wrapper_AppComponent (/AppModule/AppComponent/wrapper.ngfactory.js:6:18)
JS:     at _View_AppComponent_Host0.createInternal (/AppModule/AppComponent/host.ngfactory.js:15:28)
JS:     at _View_AppComponent_Host0.AppView.create (file:///data/data/com.one.develop/files/app/tns_modules/nativescript-angular/node_modules/@angular/core/bundles/core.umd.js:9170:25)
JS:     at ComponentFactory.create (file:///data/data/com.one.develop/files/app/tns_modules/nativescript-angular/node_modules/@angular/core/bundles/core.umd.js:5809:40)
JS: Unhandled Promise rejection: java.lang.NoSuchMethodError: no static method "Ljava/lang/Long;.toString()Ljava/lang/String;"
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1047)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1028)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1018)
JS:     com.tns.FragmentClass.onCreateView(android.app.Fragment.java)
JS:     android.app.Fragment.performCreateView(Fragment.java:2053)
JS:     android.app.FragmentManagerImpl.moveToState(FragmentManager.java:894)
JS:     android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
JS:     android.app.BackStackRecord.run(BackStackRecord.java:833)
JS:     android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
JS:     android.app.Activity.performResume(Activity.java:6090)
JS:     android.app.ActivityThread.performResumeActivity(ActivityThread.java:3131)
JS:     android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3173)
JS:     android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2535)
JS:     android.app.ActivityThread.access$900(ActivityThread.java:163)
JS:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1358)
JS:     android.os.Handler.dispatchMessage(Handler.java:102)
JS:     android.os.Looper.loop(Looper.java:135)
JS:     android.app.ActivityThread.main(ActivityThread.java:5536)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     java.lang.reflect.Method.invoke(Method.java:372)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1397)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1192) ; Zone: angular ; Task: Promise.then ; Value: Error: java.lang.NoSuchMethodError: no static method "Ljava/lang/Long;.toString()Ljava/lang/String;"
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1047)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1028)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1018)
JS:     com.tns.FragmentClass.onCreateView(android.app.Fragment.java)
JS:     android.app.Fragment.performCreateView(Fragment.java:2053)
JS:     android.app.FragmentManagerImpl.moveToState(FragmentManager.java:894)
JS:     android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
JS:     android.app.BackStackRecord.run(BackStackRecord.java:833)
JS:     android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
JS:     android.app.Activity.performResume(Activity.java:6090)
JS:     android.app.ActivityThread.performResumeActivity(ActivityThread.java:3131)
JS:     android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3173)
JS:     android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2535)
JS:     android.app.ActivityThread.access$900(ActivityThread.java:163)
JS:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1358)
JS:     android.os.Handler.dispatchMessage(Handler.java:102)
JS:     android.os.Looper.loop(Looper.java:135)
JS:     android.app.ActivityThread.main(ActivityThread.java:5536)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     java.lang.reflect.Method.invoke(Method.java:372)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1397)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1192) Error: java.lang.NoSuchMethodError: no static method "Ljava/lang/Long;.toString()Ljava/lang/String;"
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1047)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1028)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1018)
JS:     com.tns.FragmentClass.onCreateView(android.app.Fragment.java)
JS:     android.app.Fra
JS: gment.performCreateView(Fragment.java:2053)
JS:     android.app.FragmentManagerImpl.moveToState(FragmentManager.java:894)
JS:     android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
JS:     android.app.BackStackRecord.run(BackStackRecord.java:833)
JS:     android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
JS:     android.app.Activity.performResume(Activity.java:6090)
JS:     android.app.ActivityThread.performResumeActivity(ActivityThread.java:3131)
JS:     android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3173)
JS:     android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2535)
JS:     android.app.ActivityThread.access$900(ActivityThread.java:163)
JS:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1358)
JS:     android.os.Handler.dispatchMessage(Handler.java:102)
JS:     android.os.Looper.loop(Looper.java:135)
JS:     android.app.ActivityThread.main(ActivityThread.java:5536)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     java.lang.reflect.Method.invoke(Method.java:372)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1397)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1192)
JS:     at Object.<anonymous> (file:///data/data/com.one.develop/files/app/tns_modules/console/console.js:316:33)
JS:     at JSON.stringify (<anonymous>)
JS:     at Console.createDump (file:///data/data/com.one.develop/files/app/tns_modules/console/console.js:307:26)
JS:     at Console.dump (file:///data/data/com.one.develop/files/app/tns_modules/console/console.js:342:25)
JS:     at file:///data/data/com.one.develop/files/app/app.component.js:54:21
JS:     at file:///data/data/com.one.develop/files/app/tns_modules/nativescript-plugin-firebase/firebase.js:271:9
JS:     at new ZoneAwarePromise (file:///data/data/com.one.develop/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:465:29)
JS:     at Object.firebase.addOnMessageReceivedCallback (file:///data/data/com.one.develop/files/app/tns_modules/nativescript-plugin-firebase/firebase.js:252:10)
JS:     at new AppComponent (file:///data/data/com.one.develop/files/app/app.component.js:53:18)
JS:     at new Wrapper_AppComponent (/AppModule/AppComponent/wrapper.ngfactory.js:6:18)
JS: Error: Uncaught (in promise): Error: java.lang.NoSuchMethodError: no static method "Ljava/lang/Long;.toString()Ljava/lang/String;"
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1047)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1028)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1018)
JS:     com.tns.FragmentClass.onCreateView(android.app.Fragment.java)
JS:     android.app.Fragment.performCreateView(Fragment.java:2053)
JS:     android.app.FragmentManagerImpl.moveToState(FragmentManager.java:894)
JS:     android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
JS:     android.app.BackStackRecord.run(BackStackRecord.java:833)
JS:     android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
JS:     android.app.Activity.performResume(Activity.java:6090)
JS:     android.app.ActivityThread.performResumeActivity(ActivityThread.java:3131)
JS:     android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3173)
JS:     android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2535)
JS:     android.app.ActivityThread.access$900(ActivityThread.java:163)
JS:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1358)
JS:     android.os.Handler.dispatchMessage(Handler.java:102)
JS:     android.os.Looper.loop(Looper.java:135)
JS:     android.app.ActivityThread.main(ActivityThread.java:5536)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     java.lang.reflect.Method.invoke(Method.java:372)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1397)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1192)



I hope this helps in identifying the problem

**Comment by EddyVerbruggen** [comment]
@manishmlv50 Can you show me what's on this line? `file:///data/data/com.one.develop/files/app/app.component.js:53:18`
