### ISSUE TITLE
number bug?

### ISSUE THREAD

**Issue by elinswilberg** [EddyVerbruggen/nativescript-plugin-firebase#261]
Hi

When I store a number it's not returned in the first result (only when I change the value):

<img width="886" alt="screen shot 2017-01-14 at 15 59 37" src="https://cloud.githubusercontent.com/assets/1379035/21955821/bdee2c4c-da72-11e6-9631-77de95f53b79.png">"level" is missing from the result.

If I change the type to string, it's returned as expected:
<img width="889" alt="screen shot 2017-01-14 at 16 00 33" src="https://cloud.githubusercontent.com/assets/1379035/21955822/c5c2d83c-da72-11e6-935f-295d13d16147.png">
"level" is returned as expected.

**Comment by EddyVerbruggen** [comment]
Can you tell me which platform this is?

**Comment by elinswilberg** [comment]
Oh, sorry. I'm testing on iOS.

**Comment by EddyVerbruggen** [comment]
I've been trying to reproduce this a few times, but dunno how. Is there any code you can share?
