### ISSUE TITLE
Podfile.lock No such file or directory

### ISSUE THREAD

**Issue by MalinGunasekara** [EddyVerbruggen/nativescript-plugin-firebase#263]
Hi.
I have complete all of the steps which was given and push notification it was working for the Android.

In iOS app when I was trying to put the app in to itunesconnect (Archive) it's popping up errors. But the App it runs on the simulator itself for "tns run ios" in terminal.  

![screen shot 2017-01-16 at 2 58 15 pm](https://cloud.githubusercontent.com/assets/22995308/21977472/4cfc0f50-dbfc-11e6-92ad-df15d18f099a.png)

It says update pods, But when I ran the pod install this message pops up 
![screen shot 2017-01-16 at 2 58 27 pm](https://cloud.githubusercontent.com/assets/22995308/21977540/926d27e0-dbfc-11e6-8b1c-93a33e6d4c5a.png)

After the pod Install error stays the same.
Anyone have a solution (xcode v8.1, tns-ios@2.4.0).. 

App itself can build and run through xCode.
Thank you...

**Comment by Daxito** [comment]
I have seen people (like me)  executing "tns prepare ios --release" before archiving.

**Comment by MalinGunasekara** [comment]
@Daxito  Thank you..

**Comment by selinsakarya** [comment]
in which directory should we run this command?
