### ISSUE TITLE
iOS: Push Notifications not working in Background in Production 

### ISSUE THREAD

**Issue by yi5915** [EddyVerbruggen/nativescript-plugin-firebase#264]
In IOS I can receive Background  Notifications Message in development   , but in production Background  Notifications can't work and when  I close app  after open app , Notifications Message  can't receive .  
Please Help  thanks !

**Comment by garciaguillermoa** [comment]
I am facing the same problem. Any help would be really appreciated. Thanks.

**Comment by EddyVerbruggen** [comment]
Please update to 3.9.2 and take note of the update [messaging instructions](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/MESSAGING.md#ios), let me know if issues remain afterwards.

**Comment by yi5915** [comment]
Hi  
I have update to 3.9.2  In production Background Notifications can't work . Thanks !

**Comment by KingAndroid** [comment]
Hello Every one.
I also get same issue on this case.
Here is my package config

> "dependencies": {
>     "moment": "2.18.1",
>     "nativescript-geolocation": "^3.0.0",
>     "nativescript-loading-indicator": "^2.3.2",
>     "nativescript-plugin-firebase": "^3.11.4",
>     "nativescript-screen-orientation": "^2.0.0",
>     "tns-core-modules": "^3.0.1"
> }
How can i resolve this issue?
Thanks
