### ISSUE TITLE
[Firebase Storage] Upload file with custom meta data?

### ISSUE THREAD

**Issue by NordlingArt** [EddyVerbruggen/nativescript-plugin-firebase#265]
One should be able to customize the metadata when uploading a file to Firebase Storage.

**iOS:** https://firebase.google.com/docs/storage/ios/file-metadata
**Android:** https://firebase.google.com/docs/storage/android/file-metadata

Currently when uploading images, the default `contentType` is "application/octet-stream", which should be changed to, say, "image/jpeg" or "image/png".

**Comment by EddyVerbruggen** [comment]
Recent versions of this plugin should be able to infer the mimetype. Which do you use?

**Comment by NordlingArt** [comment]
@EddyVerbruggen - Is it? It's not documented. Hence why I did not know. The version I currently use is 3.8.2

**Comment by EddyVerbruggen** [comment]
I searched the issues for you, it's fixed in 3.9.0 by #236 

And it's not documented as I consider it not working a bug, not a feature :)
