### ISSUE TITLE
TypeError: Cannot read property 'ServerValue' of undefined

### ISSUE THREAD

**Issue by hypery2k** [EddyVerbruggen/nativescript-plugin-firebase#268]
I'm trying to use it in an angular 2 app:
```
import {init} from 'nativescript-plugin-firebase';

...
        init({
          onPushTokenReceivedCallback: (token) => {
          ...
          },
          onMessageReceivedCallback: (notificationData) => {
           ...
        }).then(
          (instance) => this.logger.debug("firebase.init done"),
          (error) => {
            this.logger.error('Error during push configuration', error);
            observer.error();
          }
        );
```

But always getting this error:

```
JS: Error in firebase.init: TypeError: Cannot read property 'ServerValue' of undefined
JS: "Error during push configuration",{}
```

Seems to be this [one](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/firebase.android.js#L158): 

Any ideas?

**Comment by EddyVerbruggen** [comment]
Using livesync, or an older version of the plugin?

**Comment by hypery2k** [comment]
currently using watch-mode of webpack.

Could it be an issue that I'm trying to use it in angular 2 service?

**Comment by EddyVerbruggen** [comment]
I don't think so, but can you try a plain `tns run android` as well to rule things out?

**Comment by hypery2k** [comment]
that's the error. Thanks for your support
