### ISSUE TITLE
Click on push notification when active

### ISSUE THREAD

**Issue by hypery2k** [EddyVerbruggen/nativescript-plugin-firebase#269]
I've discovered a small issue with the messaging part. I sent a message to my app:

1. App is open --> getting push message
2. App is active, but in background --> not getting push message
3. App is killed --> getting push message during open

Any idea how to resolve this?

**Comment by EddyVerbruggen** [comment]
iOS, right?

Are you using the latest version? I've done a major update to fix background notifications on iOS recently.

You'll need to follow the steps in the doc very carefully to make those work.

**Comment by hypery2k** [comment]
no, running on Android

**Comment by hypery2k** [comment]
sorry, was my fault on using the data/notification property wrong on the server side. It's working

**Comment by nilsmehlhorn** [comment]
@hypery2k Would you mind elaborating on what you did wrong on the server side? 

I am stuck with the same behaviour, where the `onMessageReceivedCallback` is called when the push notification is received while the app is open or after it is clicked from the system tray while the app is killed. When the application is in background, the push notification shows up in the tray, yet the callback is not invoked on-click.

The push notification itself is sent as a data message via HTTP:
```
{
    "notification": {"title": "My title", "text": "My text", "badge": "1", "sound": "default"},
    "data": {"foo":"bar"},
    "priority": "High",
    "to": "/topics/foo"
}
```

@EddyVerbruggen I can open a separate issue on this matter, if that's more convenient for you

**Comment by ZionInc** [comment]
Any idea how to use onNewIntent, with this plugin ? @nilsmehlhorn

**Comment by nilsmehlhorn** [comment]
I've setup a gist to show you how it's working for me:
https://gist.github.com/nilsmehlhorn/1a3ee7447d0c7b60104288bc16c80c13

**Comment by ZionInc** [comment]
Thank for the gits. In my case, Intent does gets called as expected, but with an empty `'Extras'`
```
JS: SaveInstanceState-------
JS: Stop-------
JS: NewIntent,{}<=============
JS: Start-------
```
I don't get it. Expected behavior is clearly [mentioned ](https://goo.gl/39bRNJ) in firebase docs .
I will try with fresh project one last time and log an issue if problem persists

**Comment by ZionInc** [comment]
Finally got it working!  @nilsmehlhorn  Your gist is perfect except \:
We need to do `get("paramName")` on intent to obtain the `paramName`
![intent](https://user-images.githubusercontent.com/31528799/30816453-9e879b48-a233-11e7-8352-eb7e407d8e5c.png)

Refer:  [How to use Firebase Cloud Messaging in a NativeScript Angular Mobile App](https://developer.telerik.com/products/nativescript/use-firebase-cloud-messaging-nativescript-app/)

**Comment by ZionInc** [comment]
@nilsmehlhorn . A side-note. 
I saw custom notif icon config in your [AndroidManifest.xml.](https://gist.github.com/nilsmehlhorn/1a3ee7447d0c7b60104288bc16c80c13#file-androidmanifest-xml-L28-L29) 
Were you able to make it work ?

**Comment by nilsmehlhorn** [comment]
**_Extras_**
Actually I excluded the retrieval of extras to make the gist more generic. In my app I'm mapping the extra-bundle to a JavaScript map like this
```
OnIntent
    ...
    .map(i => i.getExtras())
    .map(extras => {
        let data = {};
        const iterator = extras.keySet().iterator();
        while (iterator.hasNext()) {
            let key = iterator.next();
            data[key] = extras.get(key);
        }
        return data;
    })
```
**_Icon_**
Yes, it is working for me. Make sure to provide the resource appropriately (dont forget to do a full rebuild) and specify the icon when dispatching the notficiation with firebase.

**Comment by Sharique-Hasan** [comment]
@nilsmehlhorn When I included your gist tns run android did not build the project successfully and threw an error of java.
