### ISSUE TITLE
An internal error has occurred, print and inspect the error details for more information

### ISSUE THREAD

**Issue by musso** [EddyVerbruggen/nativescript-plugin-firebase#280]
Hi ~

I have created an app from `tns create fblogin --ng` to test the facebook auth.
Followed the setup, successfully create user through email and password in firebase. 

But when using facebook login, there is an error message `An internal error has occurred, print and inspect the error details for more information` returned.

I have already done the following 
1. setup facebook ios with correct Bundle ID, Single Sign On and Valid OAuth redirect URIs
2. copied the fb id and app secret values to info.plist
3. Allow fb auth when install the plugin with correct podfile 
4. tns platform clean ios

```
firebase.login({
            type: firebase.LoginType.FACEBOOK,
        }).then(
            function (result) {
                console.log(result);
            }, function (error) {
                console.log(error);
            }
        );
```

Is there any way to log a detailed error other than just a string of "An internal error has occurred, print and inspect the error details for more information"

Using tns-ios 2.5

Please help. Many thanks !

**Comment by EddyVerbruggen** [comment]
You could go into firebase.ios.js and `console.dump()` the error that's returned to the method you highlighted.

**Comment by musso** [comment]
successfully log the error in firebase.ios.js L:763

**Comment by musso** [comment]
for those having same error code, please go to https://github.com/firebase/FirebaseUI-iOS/issues/83

**Comment by EddyVerbruggen** [comment]
@musso you're saying that you had this enabled and disabling made it all work?

<img width="378" alt="0edda83a-491e-11e6-9389-ce77b44056f4" src="https://cloud.githubusercontent.com/assets/1426370/23103677/416743c0-f6bf-11e6-8273-f1379fe535c2.png">

**Comment by musso** [comment]
@EddyVerbruggen yup... need to disable it
