### ISSUE TITLE
nativescript-plugin-firebase and nativescript admob conflict

### ISSUE THREAD

**Issue by deifos** [EddyVerbruggen/nativescript-plugin-firebase#284]
After installing nativescript-admob I'm getting 

Build Failed with an exception.

...platforms/android/configurations/nativescript-plugin-firebase/include.gradle' line: 45

`> Failed to apply plugin [id 'com.google.gms.google-services']
   > For input string: "+"`

Everything was working fine before then.

Thanks for any help.

**Comment by EddyVerbruggen** [comment]
I could try and sync those dependencies forever, or just add AdMob support to this plugin directly as it's part of the Firebase suite nowadays.

Work in progress (expect to land this on Friday):

<img width="319" alt="screen shot 2017-02-15 at 23 03 08" src="https://cloud.githubusercontent.com/assets/1426370/22997535/125b45b6-f3d3-11e6-9805-0603332d59f8.png">

**Comment by deifos** [comment]
Sounds great!

Thank you for your quick reply!

**Comment by EddyVerbruggen** [comment]
Available in 3.10.0
