### ISSUE TITLE
Plugins not uncommented in include.gradle

### ISSUE THREAD

**Issue by lukeramsden** [EddyVerbruggen/nativescript-plugin-firebase#285]
Even though I have Crash Reporting and Storage set to `true` in the config, and I run `npm run setup` in the plugin root, Crash Reporting and Storage are still commented out in `/platforms/android/configurations/nativescript-plugin-firebase/include.gradle`

Is it possible to get the hook to do it? Otherwise I have to keep doing it manually all the time.

**Comment by EddyVerbruggen** [comment]
Can you please update {N} to 2.5.1 and __then__ this plugin to 3.10.0 and try again?
