### ISSUE TITLE
ReferenceError: firebase is not defined

### ISSUE THREAD

**Issue by blaur** [EddyVerbruggen/nativescript-plugin-firebase#289]
After upgrading to NativeScript 2.5 I am not able to bundle with webpack. It works perfectly fine when running it with "tns run android" but when running with bundle I am not able to instantiate firebase.

I get my front screen but then nothing is loaded after trying to run firebase. I am simply importing it as defined here (import firebase = require("nativescript-plugin-firebase")).

I get the following error:
```
JS: ReferenceError: firebase is not defined
JS:     at LoginPageComponent.module.exports.LoginPageComponent.ngOnInit (file:///data/data/org.nativescript.drivelogger
.student/files/app/bundle.js:22985:9)
JS:     at Wrapper_LoginPageComponent.module.exports.Wrapper_LoginPageComponent.ngDoCheck (file:///data/data/org.natives
cript.drivelogger.student/files/app/bundle.js:54812:30)
JS:     at View_LoginPageComponent_Host0.module.exports.View_LoginPageComponent_Host0.detectChangesInternal (file:///dat
a/data/org.nativescript.drivelogger.student/files/app/bundle.js:54854:38)
JS:     at View_LoginPageComponent_Host0.module.exports.AppView.detectChanges (file:///data/data/org.nativescript.drivel
ogger.student/files/app/vendor.js:11439:14)
JS:     at ViewContainer.module.exports.ViewContainer.detectChangesInNestedViews (file:///data/data/org.nativescript.dri
velogger.student/files/app/vendor.js:15719:37)
JS:     at View_AppComponent0.module.exports.View_AppComponent0.detectChangesInternal (file:///data/data/org.nativescrip
t.drivelogger.student/files/app/bundle.js:53527:20)
JS:     at View_AppComponent0.module.exports.AppView.detectChanges (file:///data/data/org.nativescript.drivelogger.stude
nt/files/app/vendor.js:11439:14)
JS:     at View_AppComponent0.module.exports.AppView.internalDetectChanges (file:///data/data/org.nativescript.drivelogg
er.student/files/app/vendor.js:11424:18)
JS:     at View_AppComponent_Host0.module.exports.View_AppComponent_Host0.detectChangesInternal (file:///data/data/org.n
ativescript.drivelogger.student/files/app/bundle.js:53493:25)
JS:     at View_AppComponent_Host0.module.exports.AppView.detectChanges (file:///data/data/org.nativescript.drivelogger.
student/files/app/vendor.js:11439:14)
JS: ReferenceError: firebase is not defined

```

The command I am using to bundle is this: webpack --config=webpack.android.js --progress

And it works fine when I remove firebase from my login component.

Any ideas of how to get around this?

**Comment by blaur** [comment]
I am experiencing exactly the same on iOS. 

Seems a problem with the newest addition of AoT bundle.

**Comment by smarza** [comment]
@blaur How did you fixed the "firebase is not defined" issue?

I am experiencing the same using {N} 2.5.2 with webpack.

Thanks

**Comment by doubleaa93** [comment]
I having the same issue. Works fine with "tns run android" but when bundled with webpack "npm run start-android-bundle" application crashed at launch with firebase is not defined in ...bundle.js

**Comment by SamuelGRwebfab** [comment]
any update on this issue?

**Comment by ls-spavel** [comment]
Where do you all initialize firebase? Is it in `main.ts`? Try the `app.component.ts` file.

I moved all my initialization code to `app.component.ts` and all was well for me. I ran into a similar issue with the nativescript-google-maps-sdk.

**Comment by SamuelGRwebfab** [comment]
the above fix did get me past this error. more came up but its past that one! Thanks

**Comment by lukashlobil** [comment]
I too have the same issue, although the solution did not work for me. I had the firebase init call (firebase is wrapped in a service) in my first real component. Tried moving it to main.aot.ts, app.component.ts, fails the same way wherever it is. Any help is appreciated.

**Comment by davorpeic** [comment]
I fixed my webpack init in `main.aot.ts` issue with solution mentioned [here](https://discourse.nativescript.org/t/firebase-webpack/1161/4)

Importing the plugin this way: 
`import * as firebase from "nativescript-plugin-firebase"`
instead of the way it's mentioned on github
`import firebase = require("nativescript-plugin-firebase");`

hope it helps
