### ISSUE TITLE
multi-location update

### ISSUE THREAD

**Issue by veenatic** [EddyVerbruggen/nativescript-plugin-firebase#29]
support for multi-location update should be available. this is an important feature for this plugin. would this be possible?

**Comment by EddyVerbruggen** [comment]
Can you send a pull request in case you need it soon? Also, do you have a link to the exact feature you need in the native SDK's?

**Comment by veenatic** [comment]
I just realized with the update function we can achieve it. for example if we need to update like below (in android) since updateChildren supports multi-path updates:
```
Firebase usersRef = ref.child("users/");
Map<String, Object> nickname = new HashMap<String, Object>();
nickname.put("alanisawesome/nickname", "Alan The Machine");
nickname.put("gracehop/nickname", "Amazing Grace");
usersRef.updateChildren(nickname);
```

We can say:
```
firebase.update('/users', {
"alanisawesome/nickname" : "Alan The Machine",
"gracehop/nickname" : "Amazing Grace"
});
```

I haven't tried this. But looks like it can work. Do you think?

**Comment by EddyVerbruggen** [comment]
See #313, I guess.
