### ISSUE TITLE
Don't load AdMob symbols if AdMob was not enabled in the config

### ISSUE THREAD

**Issue by EddyVerbruggen** [EddyVerbruggen/nativescript-plugin-firebase#290]
This leads to build errors on iOS because `build.xcconfig` expects `platforms/ios/Pods/Google-Mobile-Ads-SDK` to exist.

**Comment by asaph26** [comment]
@EddyVerbruggen When will this fix be released?

**Comment by EddyVerbruggen** [comment]
Tonight
