### ISSUE TITLE
 Error in firebase.admob.showBanner: ...'initialize' of undefined

### ISSUE THREAD

**Issue by deifos** [EddyVerbruggen/nativescript-plugin-firebase#291]
I'm following the example you have here https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/ADMOB.md but I'm getting:

`JS: Error in firebase.admob.showBanner: TypeError: Cannot read property 'initialize' of undefined
`
I thought it was that I was calling the function to display the banner on ngOninit() and that it was not having enough time to load completely but it also happens if I call the firebase.admob.showBanner() using Tap().

Thank you for any guidance you can give me.

**Comment by EddyVerbruggen** [comment]
Hi, which platform is this on?

**Comment by deifos** [comment]
Android

**Comment by deifos** [comment]
I just cloned the Firebase demo app and admob works fine there. so it must be something I'm missing.

**Comment by EddyVerbruggen** [comment]
Make sure admob is enabled in your configuration. You can reconfigure the plugin by going to the `node_modules/nativescript-plugin-firebase` folder and run `npm run config`. Make sure to select AdMob. Then `tns platform remove android && tns platform add android && tns run android` should work just fine.

**Comment by deifos** [comment]
Yes, that was exactly the problem.
Thank you so much.
