### ISSUE TITLE
iOS crashes when AdMob is not enabled

### ISSUE THREAD

**Issue by vswee** [EddyVerbruggen/nativescript-plugin-firebase#294]
JavaScript stack trace:
1   @file:///app/tns_modules/nativescript-plugin-firebase/firebase.js:1777:69
2   promiseReactionJob@[native code]
3   require@[native code]
4   loadModule@file:///app/tns_modules/tns-core-modules/globals/globals.js:29:38
5   resolvePageFromEntry@file:///app/tns_modules/tns-core-modules/ui/frame/frame-common.js:79:50
6   navigate@file:///app/tns_modules/tns-core-modules/ui/frame/frame-common.js:165:40
7   navigate@file:///app/tns_modules/tns-core-modules/ui/frame/frame.js:44:43
8   onLoaded@file:///app/tns_modules/tns-core-modules/ui/frame/frame.js:38:26
9   viewDidLoad@file:///app/tns_modules/tns-core-modules/ui/frame/frame.js:404:27
10  makeKeyAndVisible@[native code]
11  didFinishLaunchingWithOptions@file:///app/tns_modules/tns-core-modules/application/application.js:144:39
12  @[native code]
13  onReceive@file:///app/tns_modules/tns-core-modules/application/application.js:59:32
14  UIApplicationMain@[native code]
15  start@file:///app/tns_modules/tns-core-modules/application/application.js:251:26
16  anonymous@file:///app/app.js:80:18
17  evaluate@[native code]
18  moduleEvaluation@[native code]
19  @[native code]
20  promiseReactionJob@[native code]
JavaScript error:
file:///app/tns_modules/nativescript-plugin-firebase/firebase.js:1777:69: JS ERROR ReferenceError: Can't find variable: GADInterstitialDelegate

Not sure where to start looking for solutions here...

**Comment by EddyVerbruggen** [comment]
Hi, I'm currently working on a solution. It will land today.

**Comment by vswee** [comment]
Well, uh... I updated to 3.10.1 manually from git.

**Comment by EddyVerbruggen** [comment]
Ah, ok, that's work in progress. I'll prolly push the final 3.10.1 to npm today.

**Comment by vswee** [comment]
Much appreciated

**Comment by rbasniak** [comment]
I tried build for iOS for the first time this week and this is still happening. I had to answer yes for AdMob, otherwise it does not build for iOS. 

The error message is not exactly the same, but the solution is to choose AdMob on setup.
