### ISSUE TITLE
How can i show notifications based on certain condition?

### ISSUE THREAD

**Issue by LakshmiEvana** [EddyVerbruggen/nativescript-plugin-firebase#296]
I want to display the notification based on some condition.
Is there any way to do this?help me!

**Comment by xavica** [comment]
Is it possible to stop showing notifications based on received message even in topics.

**Comment by LakshmiEvana** [comment]
Noo.I want to stop the notification from displaying by checking condition from the reciever end.
If the condition satisfied then only will display.
Is it possible?

**Comment by EddyVerbruggen** [comment]
I guess you'll need to build that logic into your backend; don't send a message if it doesn't apply. No way that I know to do that clientside.
