### ISSUE TITLE
Implement changePassword

### ISSUE THREAD

**Issue by guillaume-roy** [EddyVerbruggen/nativescript-plugin-firebase#30]
Due to the fact that `resetPassword` creates a temporary password, the user must change its password manually from the client using [`changepassword`](https://www.firebase.com/docs/web/api/firebase/changepassword.html).

This plugin provides `resetPassword` but not `changepassword`.

How can i change the user's password using your plugin ?

**Comment by EddyVerbruggen** [comment]
Are you up for a PR? Otherwise you'll need to wait a bit for someone (likely me) to add it.

**Comment by guillaume-roy** [comment]
Please see #31

**Comment by EddyVerbruggen** [comment]
Supercool! Version 2.1.7 is published.
