### ISSUE TITLE
iOS [Real device] returns token: null

### ISSUE THREAD

**Issue by vswee** [EddyVerbruggen/nativescript-plugin-firebase#300]
IOS app appears to simply return null as token after subsequent launches via tns run.

My tokens are stored in mysql

The token and app bond is not reflected in the FCM which registers a success for any notifications pushed to the device token but no message is received.

The app also logs unable to register /topics/etc.. with token (null) if an attempt is made to subscribe to a topic.

**Comment by EddyVerbruggen** [comment]
Perhaps try 4.0.0 which adds the ability to manually retrieve the current push registration token.
