### ISSUE TITLE
Remote Config

### ISSUE THREAD

**Issue by mn-martin** [EddyVerbruggen/nativescript-plugin-firebase#305]
Could you please provide more info on when to call getRemoteConfig and how to actually use it?

Would i put it into my app.ts file and call app.start() in the promise resolve callback?

**Comment by mn-martin** [comment]
Oh and what about the firebase init? Do I need to put everything inside it's promise resolve callback as well?

**Comment by EddyVerbruggen** [comment]
What have you tried, and what is the actual problem?

**Comment by jlooper** [comment]
I have an example of using RemoteConfig here: http://www.github.com/jlooper/quicknoms-app - the top yellow bar shows a message that you can change remotely. Beware, Google likes to throttle your calls if you use it too much. It's an interesting feature.

**Comment by mn-martin** [comment]
@EddyVerbruggen  That's what I currently have. It's kinda working, but already a lot of custom code here. I thought the plugin would do all that stuff for me maybe. But I'm missing some samples or API. (If you have a look at the [intro video](https://firebase.google.com/docs/remote-config/) you know what I mean. This Remote Config thing is promising to fix a lot of problems out of the box) Using just firebase.getRemoteConfig() for example didn't work because it needs one initial successful fetch. (Didn't fall back to the default) 

@jlooper Thank you for that example. I'll have a look at it.

```typescript
import { RemoteConfigProperty } from "nativescript-plugin-firebase";

class Config {

    public static properties: RemoteConfigProperty[] = [
        {
            "key": "livestream_url",
            "default": "https://www.youtube.com/channel/.../live"
        }
    ];

    private static fetchedProperties: { [propertyName: string]: any } = {};

    public static get(key: string): any {
        if (Config.fetchedProperties.hasOwnProperty(key)) return Config.fetchedProperties[key];

        let property: RemoteConfigProperty =  Config.properties.find(
            (property: RemoteConfigProperty): boolean => property.key === key
        );

        return property ? property.default : "";
    }

    public static update(properties: { [propertyName: string]: any }) {
        console.log("Updating config ...");
        Config.fetchedProperties = properties;
    }

}

firebase.init({}).then(
    (instance) => {
        firebase.getRemoteConfig({
            developerMode: true,
            cacheExpirationSeconds: 60,
            properties: Config.properties
        }).then((result: any) => {
            Config.update(result.properties);
        });
    },
    (error) => {
        console.log("firebase.init error: " + error);
    }
);

console.log(Config.get("livestream_url"));
```

**Comment by jlooper** [comment]
Just a word of warning @mn-martin ...Apple is starting to reject apps that have a 'hot push' capability. If you use RemoteConfig in production can you let me know how your app deployment goes? I'd like to monitor this. thanks!

**Comment by mn-martin** [comment]
@jlooper As far as I understand Apple would just reject an app if it's behavior can be changed after the App-Review process. I've seen a lot of questions regarding that subject in connection with rollout.io. Did you hear of anyone using firebase having their apps rejected? Don't you think I'm safe if it's just about some config changes that don't affect my apps functionality. (Some URL's to the backend etc. or URL's to web resources like an impressum for example)

Thank you for the warning thought. Really appreciate that.

**Comment by jlooper** [comment]
My apps that use this plugin (PracticeBuddy and also PocketRave) have been successfully deployed to the iOS store, no problems :) - I don't however use RemoteConfig with it. Are you planning to use RemoteConfig in production? What worries me is the blanket rejection of apps using rollout.io. I wonder if there would be a blanket rejection fo apps using RemoteConfig. But I don't have data to back up my fear! :)

**Comment by mn-martin** [comment]
Yes I'm planning to do so. I'll keep you updated.

**Comment by mn-martin** [comment]
@jlooper My app has passed the review process. I added following description to the submission including a screenshot of all the config keys + values.

* We use the Firebase Remote Config only as a key-value storage for config entries, that might need a change over time.
* This is all about content. We do not change any functionality / behavior of the app using remote config.
