### ISSUE TITLE
Crash reporting is it mandatroy add 'com.google.firebase:firebase-crash:10.2.0' to build.gradle?

### ISSUE THREAD

**Issue by upender-devulapally** [EddyVerbruggen/nativescript-plugin-firebase#310]
Hi thank you for great plugin.
Enabled the 'Crash Reporting' while installing the plugin.
My question is it mandatory to add below to 'build.gradle' file? or plugin will take care of that while building the app? I don't have any knowledge on 'android' development 
`compile 'com.google.firebase:firebase-crash:10.2.0'`
Can you please help me I am about to submit my app to play store....

**Comment by EddyVerbruggen** [comment]
That should happen automatically by the script. You can check the gradle file in node_modules/nativescript-plugin-firebase/platforms/android and see if that line was uncommented.

**Comment by upender-devulapally** [comment]
yes its uncommented in include.gradle file
``` 
    // Uncomment if you want to use 'Remote Config'
    // compile "com.google.firebase:firebase-config:10.2.+"

    // Uncomment if you want to use 'Crash Reporting'
     compile "com.google.firebase:firebase-crash:10.2.+"
```

Thank you very much for quick reply and for great plugin..

**Comment by upender-devulapally** [comment]
@EddyVerbruggen 
I was initialized the firebase plugin in mait.ts
```
import firebase = require("nativescript-plugin-firebase");
firebase.init({
    // Optionally pass in properties for database, authentication and cloud messaging,
    // see their respective docs.
}).then(
    (instance) => {
        console.log("firebase.init done");
    },
    (error) => {
        console.log("firebase.init error: " + error);
    }
);

```
Firebase init calling successfully.
Can you please help me how to report crash manually using this plugin in NativeScript, like in android below

`FirebaseCrash.report(new Exception("My first Android non-fatal error"));`

**Comment by upender-devulapally** [comment]
Just gone through the demo app,  
and realised that calling below working. Thank you for great plugin..
` firebase.sendCrashLog({})`
