### ISSUE TITLE
iOS Push Notification OnReceivedCallback Implementation.

### ISSUE THREAD

**Issue by pap5508** [EddyVerbruggen/nativescript-plugin-firebase#311]
@EddyVerbruggen : Firstly Thank you for the Plugin.. 
My question is that.. I have implemented plugin but I do not have much idea to handle push notification and navigation to respected screen...
I have developed project using Angular2... 

Do we have any sample project to handle push notification onReceivedCallback method..??

Thank you...

**Comment by EddyVerbruggen** [comment]
IDK, perhaps someone has. Applied 'question' and 'help wanted' labels accordingly..

**Comment by jlooper** [comment]
well, I am implementing it with http://www.github.com/jlooper/yowwlr - but I find these notifications to be flaky. Working on it.

**Comment by EddyVerbruggen** [comment]
I'd be interested to learn whether or not there's a difference between the latest version and the one before that.

**Comment by pap5508** [comment]
@jlooper  @EddyVerbruggen : Thanks a lot for your help Its working successfully....
Will close this issue tomorrow and also with the Sample Navigation code..

Once again thanks..! :)

**Comment by pap5508** [comment]
```
 var that = this;
      // Initialize the firebase
      firebase.init({
    // Optionally pass in properties for database, authentication and cloud messaging,
    // see their respective docs.
     
onPushTokenReceivedCallback: function(deviceID) {
     console.log("Device ID : ",deviceID);
    },
onMessageReceivedCallback: function(message) {
    console.log(JSON.stringify(message));
// if application foreground false
if(message.foreground == false){
          // Redirect it to the Respective Screen...
      }
}
```

2. you can also handle onMessageReceivedCallback with Defining global variable in Main.ts file and app.routing.ts file you can give specific router path and navigate.

**Comment by tusharvikky** [comment]
@pap5508 Hey, Could you help me find a way how you implemented to a particular route on "onMessageReceivedCallback" function? I tried appSettings it works fine in Android but iOS just doesn;t work.
