### ISSUE TITLE
Firebase cloud messaging login issue

### ISSUE THREAD

**Issue by jayakrishnanjr** [EddyVerbruggen/nativescript-plugin-firebase#318]
Hi,
I am using firebase onPushTokenReceivedCallback function to generate the token for push notification which has to be saved to the db for sending notification to registered users.The issue which i am facing is that sometimes THEN function with result gets invoked  the token does not get created.This issues happens twice out of 10 atempts.pasting my code below.

firebase.init({
   onPushTokenReceivedCallback: function (token) {
   cache.setItem("gcm_token", token);
   setGCM()
 }
}).then(
  function (result) {
  console.log("token"+gcmToken) //code hits in this parts but token is not getting generated.
},
function (error) {
  console.log("firebase.init error: " + error);	
}
)

**Comment by EddyVerbruggen** [comment]
Which platform(s)?
