### ISSUE TITLE
Unable to query by child that equals to null

### ISSUE THREAD

**Issue by NordlingArt** [EddyVerbruggen/nativescript-plugin-firebase#319]
Reading [this on StackOverflow](http://stackoverflow.com/questions/39195191/firebase-query-to-exclude-data-based-on-a-condition/39195551#39195551), it should be possible to query by a child property that has the value of `null`. However, this plugin doesn't seem to allow me to enter the value `null` into the query's `range` object.

What I'm trying to do in this query below is to fetch articles that don't have any category specified:

```js
firebase.query(snapshot => {
  console.dump(snapshot);
}, "/articles", {
  singleEvent: true,
  orderBy: { type: firebase.QueryOrderByType.CHILD, value: "category" },
  range: { type: firebase.QueryRangeType.EQUAL_TO, value: null }
}).then(() => {
  console.log("Snapshot received.");
});
```

Database looks like this:

```json
{
  "articles": {
    "article1": {
      "title": "Article #1",
      "category": "news"
    },
    "article2": {
      "title": "Article #2",
      "category": "other"
    },
    "article3": {
      "title": "Article #3"
    },
    "article4": {
      "title": "Article #4"
    }
  }
}
```

Expected result is to get article 3 and 4. But a snapshot is never received and the callback is never fired. Not even the `then` promise fires. According to the link posted above, you should be able to do this.

Is there anything that blocks `firebase.QueryRangeType.EQUAL_TO` to have a value of `null`? If I change from `null` to `"news"`, I get article 1 (as expected), so there aren't any database rules missing. When using the Firebase REST API, I can fetch an expected result.

**Comment by Dashue** [comment]
I second this! Quite a standard use-case

**Comment by EddyVerbruggen** [comment]
Yep, me too.

Was this encountered on iOS or Android (or both)?

**Comment by EddyVerbruggen** [comment]
In 4.0.7 you'll be able to query `null` values.

**Comment by NordlingArt** [comment]
@EddyVerbruggen - Great news! Thank you!

**Comment by Dashue** [comment]
Just testing this out and it looks like it might be something google has sorted?

As these two queries return the same results

`{
    orderBy: { type: QueryOrderByType.CHILD, value: 'lastBookRefresh' },
   range: { type: QueryRangeType.EQUAL_TO, value: null },
   limit: { type: QueryLimitType.FIRST, value: 5 },
   singleEvent: true
}`

` {
    orderBy: { type: QueryOrderByType.CHILD, value: 'lastBookRefresh' },
    limit: { type: QueryLimitType.FIRST, value: 5 },
    singleEvent: true
 }`

That is the same 5 records without lastBookRefresh set
