### ISSUE TITLE
How does the query function actually work?

### ISSUE THREAD

**Issue by NordlingArt** [EddyVerbruggen/nativescript-plugin-firebase#32]
Hi,

In my Firebase database, I have this:

```
{
  "deals": {
    "_1234567890": {...}
  }
}
```

If I run this code, I receive nothing from the `onQueryEvent`:
```

var onQueryEvent = function(result) {
  console.dump(result);

  if(!result.error) {
    console.log("Event type: " + result.type);
    console.log("Key: " + result.key);
    console.log("Value: ");
    console.dump(result.value);
  }
};

firebase.query(onQueryEvent, "/deals", {
  singleEvent: true,
  orderBy: {
    type: firebase.QueryOrderByType.KEY
  }
});
```

result seems to be `null` or `undefined` as well, so it doesn't hand me any error. Nothing is being logged in other words. What am I doing wrong?

**Comment by EddyVerbruggen** [comment]
So that `/deals` node is in the root of your Firebase? Code looks good. Is this on iOS, Android, or both? And if only on one platform: does it behave differently on the other?

**Comment by NordlingArt** [comment]
Hi @EddyVerbruggen,

I just realized I had to put the read state to `true` for the `/deals` node. It works now! 😁

**Comment by NordlingArt** [comment]
Another question, is there a way to sort by key value, but filter out the keys that does NOT have a certain value within the key object?

Like this:

```
{
  "_1234567890": {
    "owner": "foo"
  },
  "_0987654321": {
    "owner": "bar"
  }
}
```

The query I use in the starting comment will fetch both keys. I only want to fetch the ones that match the user's name (i.e. `foo`).
