### ISSUE TITLE
iOS Badge count 

### ISSUE THREAD

**Issue by pap5508** [EddyVerbruggen/nativescript-plugin-firebase#322]
How can I retrieve the number of notification and show it on App icon..??

Does this plugin supports badge count number..?

Please help me out to solve

**Comment by EddyVerbruggen** [comment]
AFAIK badges need to be managed manually. The plugin doesn't offer support for that currently.

**Comment by jlooper** [comment]
I'd really like to see that added if possible, +1 👌

**Comment by EddyVerbruggen** [comment]
the [FCM docs](https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support) suggest setting a `badge` property should work. Anyone brave enough to try that?

**Comment by jlooper** [comment]
I tried it from the web console...no effect. Wonder if there are configurations I'm missing

**Comment by EddyVerbruggen** [comment]
Using CURL I was able to do it:

```
curl -X POST --header "Authorization: key=AAAA9SHtZvM:APA91bGoY0H2nS8GlzzypDXSiUkNY3nrti4st4WOUs_w1A0Rttcx31U90YGv-p3U4Oql-vh-FzZzWUUPEwl47uvwhI4tB5yz4wwzrJA2fVqLEKZpDU42AQppYnU2-dsURqkyc9sKcjay2egWbfyNK2b-G2JQCqrLVA" --Header "Content-Type: application/json" https://fcm.googleapis.com/fcm/send -d "{\"notification\":{\"title\": \"My title\", \"badge\": \"3\", \"text\": \"My text\", \"sound\": \"default\"}, \"data\":{\"foo\":\"bar\"}, \"priority\": \"High\", \"to\": \"cmgdCrTUDvA:APA91bF6fV113ojlRGvplBht7YUulbqJ9g9uucm74tXfQ6BlCgg-IJZkB5QHp9AbAlQBne3wzaEwf7gmCb4OLlc95Su5ShAnP8Zvcp1hE2BWU__Bbj0jUJmG8YSuKe8Nqa3PUv7Wa7tK\"}"
```
(Note the 'badge' string here)

I'm also working on fixing automatic iOS entitlements so opening the project in Xcode is no longer needed to enable push notifications.
