### ISSUE TITLE
Build Error after adding Nativescript Firebase Plugin

### ISSUE THREAD

**Issue by efgonz** [EddyVerbruggen/nativescript-plugin-firebase#326]
Can someone help me please. Just after I add the plugin I get this error and if I remove it I can run the app normaly.

> node_modules/@types/node/index.d.ts(60,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'global' must be of type 'any', but here has type 'Global'.
> 
> node_modules/@types/node/index.d.ts(84,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'NativeScriptRequire', but here has type 'NodeRequire'.
> node_modules/@types/node/index.d.ts(96,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'module' must be of type 'NativeScriptModule', but here has type 'NodeModule'.
> 
> node_modules/@types/node/index.d.ts(4091,5): error TS2309: An export assignment cannot be used in a module with other exported elements.
> 
> node_modules/tns-core-modules/es-collections.d.ts(30,14): error TS2300: Duplicate identifier 'MapConstructor'.
> 
> node_modules/tns-core-modules/es-collections.d.ts(31,14): error TS2300: Duplicate identifier 'SetConstructor'.
> node_modules/tns-core-modules/es6.d.ts(9,5): error TS2687: All declarations of 'iterator' must have identical modifiers.
> 
> TypeScript compiler failed with exit code 1

**Comment by EddyVerbruggen** [comment]
Anyone an idea what this TS error is?

In the meanwhile just use a version lower than 3.11.0.

**Comment by joedope** [comment]
See #332

**Comment by EddyVerbruggen** [comment]
👍

**Comment by efgonz** [comment]
@joedope Thanks but that didn't solve the problem, I opted to use a lower version of the plugin.

**Comment by EddyVerbruggen** [comment]
@efgonz Have you tried removing the `node_modules` folder and do a `npm i`? It's an upstream dependency that needs updating..
