### ISSUE TITLE
Error after install plugin

### ISSUE THREAD

**Issue by yanuwid** [EddyVerbruggen/nativescript-plugin-firebase#327]
Unable to run. Error after install plugin

> tns run ios
> Executing before-prepare hook from /Users/devel/Documents/riset/pro-react/mlabs/ng2/jadwal/MobileApp/hooks/before-prepare/nativescript-dev-android-snapshot.js
> Executing before-prepare hook from /Users/devel/Documents/riset/pro-react/mlabs/ng2/jadwal/MobileApp/hooks/before-prepare/nativescript-dev-typescript.js
> Found peer TypeScript 2.1.6
> node_modules/@types/node/index.d.ts(38,11): error TS2300: Duplicate identifier 'MapConstructor'.
> 
> node_modules/@types/node/index.d.ts(40,11): error TS2300: Duplicate identifier 'SetConstructor'.
> 
> node_modules/@types/node/index.d.ts(50,14): error TS2687: All declarations of 'iterator' must have identical modifiers.
> node_modules/@types/node/index.d.ts(60,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'global' must be of type 'any', but here has type 'Global'.
> node_modules/@types/node/index.d.ts(84,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'NativeScriptRequire', but here has type 'NodeRequire'.
> node_modules/@types/node/index.d.ts(96,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'module' must be of type 'NativeScriptModule', but here has type 'NodeModule'.
> 
> node_modules/@types/node/index.d.ts(4091,5): error TS2309: An export assignment cannot be used in a module with other exported elements.
> 
> node_modules/tns-core-modules/es-collections.d.ts(30,14): error TS2300: Duplicate identifier 'MapConstructor'.
> 
> node_modules/tns-core-modules/es-collections.d.ts(31,14): error TS2300: Duplicate identifier 'SetConstructor'.
> node_modules/tns-core-modules/es6.d.ts(9,5): error TS2687: All declarations of 'iterator' must have identical modifiers.
> 
> TypeScript compiler failed with exit code 1
> Sending exception report (press Ctrl+C to stop).....

**Comment by joedope** [comment]
See #332

**Comment by EddyVerbruggen** [comment]
Thanks! Indeed see #332

**Comment by yanuwid** [comment]
New error after fresh install.

`tns create MobileApp --ng`

`tns plugin add nativescript-plugin-firebase`

`tns run ios`

> warning: Falling back to contents of entitlements file "MobileApp.entitlements" because it was modified during the build process. Modifying the entitlements file during the build is unsupported.error: The file “MobileApp.entitlements” couldn’t be opened because there is no such file.
> ** BUILD FAILED **
> The following build commands failed:
> 	ProcessProductPackaging "" /Users/devel/Library/Developer/Xcode/DerivedData/MobileApp-dwzxtuegmxwpgxbakylugrqsywrd/Build/Intermediates/MobileApp.build/Debug-iphonesimulator/MobileApp.build/MobileApp.app.xcent
> (1 failure)
> Command xcodebuild failed with exit code 65
