### ISSUE TITLE
Error when trying to run android

### ISSUE THREAD

**Issue by ezequielzacca** [EddyVerbruggen/nativescript-plugin-firebase#330]
after i installed the nativescript-splashscreen and tried to run android, started to give me this error, and i cant fix it even after i removed the plugin

Executing before-prepare hook from C:\node\projects\nativescript\ofertasv2\Ofertas\hooks\before-prepare\nativescript-dev-android-snapshot.js
Executing before-prepare hook from C:\node\projects\nativescript\ofertasv2\Ofertas\hooks\before-prepare\nativescript-dev-typescript.js
Found peer TypeScript 2.1.6
Preparing project...

:config phase:  createDefaultIncludeFiles

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\node\projects\nativescript\ofertasv2\Ofertas\platforms\android\build.gradle' line: 497

* What went wrong:
A problem occurred evaluating root project 'Ofertas'.
> ..\..\node_modules

package.json

{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.Ofertas",
    "tns-android": {
      "version": "3.0.0-next-2017-03-23-1712"
    }
  },
  "dependencies": {
    "@angular/common": "2.4.3",
    "@angular/compiler": "2.4.3",
    "@angular/core": "2.4.3",
    "@angular/forms": "2.4.3",
    "@angular/http": "2.4.3",
    "@angular/platform-browser": "2.4.3",
    "@angular/platform-browser-dynamic": "2.4.3",
    "@angular/router": "3.4.3",
    "@ngrx/core": "^1.2.0",
    "@ngrx/effects": "^2.0.1",
    "@ngrx/store": "^2.2.1",
    "nativescript-angular": "^1.4.1",
    "nativescript-bitmap-factory": "^1.7.0",
    "nativescript-cardview": "^1.3.2",
    "nativescript-checkbox": "^1.2.6",
    "nativescript-directions": "^1.0.5",
    "nativescript-floatingactionbutton": "^2.2.7",
    "nativescript-geolocation": "0.0.19",
    "nativescript-google-maps-sdk": "^1.4.3",
    "nativescript-localstorage": "^1.1.0",
    "nativescript-permissions": "^1.2.3",
    "nativescript-screenshot": "0.0.2",
    "nativescript-social-share": "^1.3.2",
    "nativescript-telerik-ui": "^1.6.1",
    "nativescript-theme-core": "~1.0.2",
    "nativescript-web-image-cache": "^3.4.0",
    "ngrx-store-localstorage": "^0.1.5",
    "ngrx-undo": "^1.0.6",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.0.1",
    "tns-core-modules": "2.5.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~2.4.3",
    "@ngtools/webpack": "1.2.10",
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "copy-webpack-plugin": "~3.0.1",
    "extract-text-webpack-plugin": "~2.0.0-beta.4",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "~0.3.5",
    "nativescript-dev-webpack": "^0.3.6",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~1.6.0",
    "typescript": "~2.1.0",
    "webpack": "2.2.0",
    "webpack-sources": "~0.1.3",
    "zone.js": "~0.7.2"
  },
  "scripts": {
    "ns-bundle": "ns-bundle",
    "start-android-bundle": "npm run ns-bundle --android --start-app",
    "start-ios-bundle": "npm run ns-bundle --ios --start-app",
    "build-android-bundle": "npm run ns-bundle --android --build-app",
    "build-ios-bundle": "npm run ns-bundle --ios --build-app"
  }
}

AndroidManifes.xml

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
	package="__PACKAGE__"
	android:versionCode="1"
	android:versionName="1.0">

	<supports-screens
		android:smallScreens="true"
		android:normalScreens="true"
		android:largeScreens="true"
		android:xlargeScreens="true"/>

	<uses-sdk
		android:minSdkVersion="17"
		android:targetSdkVersion="__APILEVEL__"/>

	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
	<uses-permission android:name="android.permission.INTERNET"/>

	<application
			android:name="com.tns.NativeScriptApplication"
			android:allowBackup="true"
			android:icon="@drawable/logo_shop"
			android:label="@string/app_name"
			android:theme="@style/AppTheme">

		<activity
				android:name="com.tns.NativeScriptActivity"
				android:label="@string/title_activity_kimera"
				android:configChanges="keyboardHidden|orientation|screenSize"
				android:theme="@style/LaunchScreenTheme">

			<meta-data android:name="SET_THEME_ON_LAUNCH" android:resource="@style/AppTheme" />

			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
		</activity>
		<activity android:name="com.tns.ErrorReportActivity"/>
	</application>
</manifest>

**Comment by EddyVerbruggen** [comment]
You stacktrace snippet doesn't really help. Can you post the full thing somewhere?

**Comment by ezequielzacca** [comment]
you can close this, i managed to fix it and had nothing to do with firebase plugin
