### ISSUE TITLE
CI builds may file if no entitlements file exists

### ISSUE THREAD

**Issue by EddyVerbruggen** [EddyVerbruggen/nativescript-plugin-firebase#331]
[This line](https://github.com/telerik/mobile-cli-lib/blob/f9990aa9779b2c4a5601071381f69a13b1f8e114/services/hooks-service.ts#L124) doesn't play nice with the empty reject [here](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/25a5d520377bd86351043b18abf7b98cfc84069c/scripts/entitlements-after-prepare.js#L14) - so let's not do an empty reject.

**Comment by spike1292** [comment]
good find, will also implement this in our nativescript-custom-entitlements plugin

**Comment by RaphaelJenni** [comment]
Since this "fix" our CI build fails because our provisioning profile isn't configured for this entitlements.
@EddyVerbruggen Do you know how to fix that?

**Comment by EddyVerbruggen** [comment]
@RaphaelJenni Can you elaborate? I'm not entirely sure what you mean. Code may help.

**Comment by RaphaelJenni** [comment]
Always get this error. But only if I build for release.
```
18-Apr-2017 10:00:01	Check dependencies
18-Apr-2017 10:00:01	The file "/PATH/nativescript/platforms/ios/PROJECT_NAME/PROJECT_NAME.entitlements" could not be opened. Verify the value of the CODE_SIGN_ENTITLEMENTS build setting for target "nativescript" and build configuraiton "Release" is correct and that the file exists on disk.
18-Apr-2017 10:00:01	Code signing is required for product type 'Application' in SDK 'iOS 10.2'
18-Apr-2017 10:00:01	Code signing is required for product type 'Application' in SDK 'iOS 10.2'
18-Apr-2017 10:00:01	
18-Apr-2017 10:00:01	** BUILD FAILED **
18-Apr-2017 10:00:01	
18-Apr-2017 10:00:01	
18-Apr-2017 10:00:01	The following build commands failed:
18-Apr-2017 10:00:01	        Check dependencies
18-Apr-2017 10:00:01	(1 failure)
18-Apr-2017 10:00:01	Command xcodebuild failed with exit code 65
18-Apr-2017 10:00:01	# build ios
```
