### ISSUE TITLE
Types conflicts with tns-core-modules

### ISSUE THREAD

**Issue by SBD580** [EddyVerbruggen/nativescript-plugin-firebase#332]
Hi,

Recent changes added "fs-promise" as dependency which add @types/node (added by @types/fs-extra) as a dependency and causing types conflict with tns-core-modules:

```
node_modules/@types/node/index.d.ts(38,11): error TS2300: Duplicate identifier 'MapConstructor'.
node_modules/@types/node/index.d.ts(40,11): error TS2300: Duplicate identifier 'SetConstructor'.
node_modules/tns-core-modules/es-collections.d.ts(30,14): error TS2300: Duplicate identifier 'MapConstructor'.
node_modules/tns-core-modules/es-collections.d.ts(31,14): error TS2300: Duplicate identifier 'SetConstructor'.
```

**Comment by SBD580** [comment]
seems like fs-promise fault as not adding the Types dependencies to devDependencies. I opened a PR.
As a workaround just `npm uninstall @types/fs-extra @types/mz @types/node` after installing/updating the plugin.

**Comment by EddyVerbruggen** [comment]
You're the best @SBD580! An update (2.0.1) to fs-promise has already been published and since this plugin just takes the latest 2.x version this problem should not occur anymore for folks installing this plugin.

**Comment by SBD580** [comment]
I'm glad I could help :) 
Thank you for this entire plugin!
