### ISSUE TITLE
Query on searching their names?

### ISSUE THREAD

**Issue by tsebvaan** [EddyVerbruggen/nativescript-plugin-firebase#334]
Hi, I'm still new to firebase and I'm having trouble in doing a search for the user's name. For SQL, it's SELECT * FROM users WHERE name LIKE 'hello%'. How can I do wildcards in Firebase?

I tried,
firebase.query(
                    (snapshot)=>{
                        console.dump(snapshot);
                    },
                    "/users/student/",
                    {
                        singleEvent: true,
                        orderBy: {
                            type: firebase.QueryOrderByType.CHILD,
                            value: 'name'
                        },
                        range: {
                            type: firebase.QueryRangeType.START_AT,
                            value: this.search
                        }
                    }
                ).then((result)=>{
                    console.log("RESULT");
                    console.log(JSON.stringify(result));
                }).catch((error)=>{
                    console.log("ERROR");
                    console.log(JSON.stringify(error));
                });

but it doesn't give me the desired output. I should only get the hello world user.

![1](https://cloud.githubusercontent.com/assets/23137338/24319336/f7a16572-1153-11e7-950f-a4b09c56b4ac.jpg)
![2](https://cloud.githubusercontent.com/assets/23137338/24319340/0162a918-1154-11e7-96f0-87a8c7e4e492.jpg)

**Comment by kryzys69** [comment]
Try:

```
range: {
    type: firebase.QueryRangeType.EQUAL_TO, // <- change START_AT
    value: this.search
}
```

or add to your query:

```
limit: {
    type: firebase.QueryLimitType.FIRST, // <- get only first result... your "hello world" user
    value: 1
}
```

**Comment by tsebvaan** [comment]
ranges: [
                        {
                            type: firebase.QueryRangeType.START_AT,
                            value: this.search.toLowerCase()
                        },
                        {
                            type: firebase.QueryRangeType.END_AT,
                            value: this.search.toLowerCase()+"\uf8ff"
                        }
                        ],

solved but, whenever i search for "world" or any letter that doesnt start with "h"  doesnt show the "hello world" user. Anyone could help me out???

**Comment by NordlingArt** [comment]
Firebase querying is extremely limited and making a "LIKE" query like SQL is not possible. The query range will only fetch items that matches in alphabetical order. So if you don't start with "h" in your search query, the item won't be found. Maybe you should stick with SQL database?

**Comment by tsebvaan** [comment]
Oh i see. Thanks. Maybe i'll just sync my firebase database to sqlite to perform a LIKE query in my app. 

Everytime the user clicks search, firebase query all users and insert those users into the sqlite and perform a LIKE query.

**Comment by tsebvaan** [comment]
Closed thread. Now using nativescript-sqlite to perfomr 'LIKE' queries

**Comment by ChirantanPatel** [comment]
hi @NordlingArt 
   SQL query : select * from usertbl where username == "abc" && password == "abc"
     this type of query how to write for firebase query. 
thanks in advance
