### ISSUE TITLE
The profileImageURL property doesn't update when it's changed on Facebook.

### ISSUE THREAD

**Issue by flpn** [EddyVerbruggen/nativescript-plugin-firebase#341]
I logged for the first time with the Facebook in my app and everything went well. So I change my profile image on Facebook. After a  while, I realize that my profile image on my app was still the same (the first one). The property profileImageURL doesn't update. How can I update this property every time I change it on the Facebook?

**Comment by EddyVerbruggen** [comment]
I think caching that is beyond this plugin.
