### ISSUE TITLE
Error: Make sure you've uploaded your SHA1 fingerprint(s) to the Firebase console

### ISSUE THREAD

**Issue by vivex** [EddyVerbruggen/nativescript-plugin-firebase#344]
Getting this error on google auth, even after i am mentioning the keystore and i have uploaded this key in firebase console

Using following command to run emulator 
```
tns run android --key-store-path /home/vivek/.keystore --key-store-password android  --key-store-alias my-expenses --key-store-alias-password android  --clean

```
Getting this error:

```
JS: Make sure you've uploaded your SHA1 fingerprint(s) to the Firebase console
JS: Has the SHA1 fingerprint been uploaded? Sign-in status: Status{statusCode=unknown status code: 12501, resolution=null}
```

**Comment by memphisvl** [comment]
Same issue. Used to work before for Google login and now this error

**Comment by EddyVerbruggen** [comment]
Make sure you've also uploaded the debug keystore SHA1 fingerprint to the console. Also (for others reading this) if you move to a new developer machine that debug keystore is likely different, so add that one as well. See https://developers.google.com/android/guides/client-auth

I just ran into the same and adding the fingerprints helped me out as usual.

**Comment by ParVisual** [comment]
Hi. 
I just generated my Android fingerprint .keystore file (I placed it into my desktop). Then I updated my Firebase settings (Project Overview > Android App > Settings > SHA certificate fingerprints). 

When I run the emulator and try to login appears the message: "Make sure you've uploaded your SHA1 fingerprint(s) to the Firebase console".

Some idea about what I'm doing wrong?

Thanks.

**Comment by ITServicesAM** [comment]
@ParVisual You have to provide your debug key. You can get from the build apk via the solution on this site
[https://stackoverflow.com/questions/11331469/how-do-i-find-out-which-keystore-was-used-to-sign-an-app](https://stackoverflow.com/questions/11331469/how-do-i-find-out-which-keystore-was-used-to-sign-an-app)
