### ISSUE TITLE
Support for Nativescript 3.0?

### ISSUE THREAD

**Issue by spmamidi** [EddyVerbruggen/nativescript-plugin-firebase#353]
Support for Nativescript 3.0?

**Comment by jlooper** [comment]
I have this plugin working on 3.0 RC fwiw

**Comment by VeRsu5** [comment]
@jlooper How did you manage to migrate the seed to nativescript 3.0. When I tried, it gives me an error saying Duplicate Identifier.

**Comment by jlooper** [comment]
For me, the plugin just worked, see the latest commit for http://www.github.com/jlooper/quicknoms-app

**Comment by vswee** [comment]
Can anyone verify that background notifications work on iOS?
I haven't made any changes to my certs yet I seem to have lost by background PNSs since upgrading to {N} 3.0

**Comment by EddyVerbruggen** [comment]
Just tested _again_ and all is fine when the project is setup correctly.

Please update to plugin version 4.0.0 just in case some Firebase SDK issue was causing the problem as they overhauled the notifications a bit. Will be releasing that today.
