### ISSUE TITLE
Ability to upload image-asset (or image-source)

### ISSUE THREAD

**Issue by lukeramsden** [EddyVerbruggen/nativescript-plugin-firebase#354]
Reference to #91

It does seem like it would be useful, because currently (AFAIK) every time you upload an image taken with `nativescript-camera`, you're storing the image locally permanently. This would clog up the user's phone with unnecessary files.

My solution to this would be a `imageAsset` (or similarly named) property that takes an image-asset or image-source (maybe both?), and if it exists, saves the image to a file, uploads it, then deletes the file. Yes, the developer could do this manually, and I currently am, but this seems like it could be a nicer solution to it.

**Comment by lukeramsden** [comment]
In an ideal world, the NativeScript core modules would have an `image-asset` or `image-source` to a `file-system` File (without actually touching the filesystem), but I can't find one.

**Comment by lukeramsden** [comment]
This would also tie in nicely with a feature to upload multiple images, with an array of strings, image-assets or image-source (with a mix of the three aswell).

I don't know much about the internals of the plugin, but I'd be happy to have a go at a PR if you don't have the time for any of this.

**Comment by EddyVerbruggen** [comment]
Hey Luke,

If you already have this in place then I'd love to see it added to the plugin as well.

A PR would be awesome. Just keep it as small as possible because I'm going to rewrite the plugin in TypeScript soon.

**Comment by narayananl23** [comment]
This will be a great feature +1. you can take picture in camera and upload to google storage.

**Comment by narayananl23** [comment]
@EddyVerbruggen 

how can I create a storage ref and upload a base64 string. if we can achieve that , we can upload image assist which can give you base64 .


[https://firebase.google.com/docs/storage/web/upload-files](url)

> Shows Upload from a String
> If a Blob, File, or Uint8Array isn't available, you can use the putString() method to upload a raw, base64, base64url, or data_url encoded string to Cloud Storage.
> 

```

                // Create a root reference
                var storageRef = firebase.storage().ref();
                // Create a reference to 'images/mountains.jpg'
                var ExpImagesRef = storageRef.child('images/');

                var message = "" ;
                 cameraModule.takePicture(options).then(imageAsset => {
                      imageSource.fromAsset(imageAsset).then(res => {
                         message = res.toBase64String(enums.ImageFormat.png));
                       })
                 }).catch(function (err) {
                 console.log("Error -> " + err.message);
                 });

                ExpImagesRef.putString(message, 'base64').then(function (snapshot) {
                    console.log('Uploaded a base64 string!');
                });
```

the above code does not work.. but just trying..

**Comment by EddyVerbruggen** [comment]
@narayananl23 Are you able to use/set the reference and upload a base64 encoded string? I'm asking because your code is cluttered by the camera logic so I'm not sure what the problem is you're trying to solve.

In any case, `takePicture` and `imageSource.fromAsset` are async, so you'll have to move this to the resolved promise of `imageSource.fromAsset`:

```js
  ExpImagesRef.putString(message, 'base64').then(function (snapshot) {
    console.log('Uploaded a base64 string!');
  });
```

**Comment by narayananl23** [comment]
@EddyVerbruggen  Did not work.. in the below code camera module is out with hard coded base64 string.

```
    // Base64 formatted string
    var message = '5b6p5Y+344GX44G+44GX44Gf77yB44GK44KB44Gn44Go44GG77yB';
    // Create a root reference
    var storageRef = firebase.storage().ref();
    // Create a reference to 'images/mountains.jpg'
    var ExpImagesRef = storageRef.child('images/mountains.jpg');
    ExpImagesRef.putString(message, 'base64').then(function (snapshot) {
        console.log('Uploaded a base64 string!');
    }); 
```

error I see in the log

`Setting Exp failed, error: TypeError: firebase.storage is not a function. (In 'firebase.storage()', 'firebase.storage' is an instance of FIRStorageReference)`

also tried like 
`var storageRef = firebase.storage.ref();`

`Setting Exp failed, error: TypeError: firebase.storage.ref is not a function. (In 'firebase.storage.ref()', 'firebase.storage.ref' is undefined)`

**Comment by EddyVerbruggen** [comment]
@narayananl23  I'm not entirely sure if you're trying to use Firestore or Firebase Storage (different things). Your code doesn't reflect either API I've documented so I'm confused.

With Firebase Storage you can upload binaries, so here's a sample using Firestore that I've just tested:

```typescript
  public issue354(): void {
    // Base64 formatted string
    const message = '5b6p5Y+344GX44G+44GX44Gf77yB44GK44KB44Gn44Go44GG77yB';
    // Create a root reference
    const storageRef = firebase.firestore().collection('images');
    // Create a reference to 'images/mountains.jpg'
    const ExpImagesRef = storageRef.doc('mountains.jpg');
    ExpImagesRef.set({'base64': message, 'mimetype': 'img/jpg'}).then(() => {
      console.log('Uploaded a base64 string!');
    })
  }
```

That results in this entry, which you can read and process any way you like:

<img width="1138" alt="screen shot 2018-02-21 at 16 00 24" src="https://user-images.githubusercontent.com/1426370/36487098-61576ac0-1720-11e8-9bd4-c09e1c37e99a.png">

**Comment by narayananl23** [comment]
Thanks for taking your time and sharing it.

@EddyVerbruggen  I want to upload to firebase storage due to the cost.As you know, It is cheeper to use firebase storage instead of firestore. 

 I was referring to 
[https://firebase.google.com/docs/storage/web/upload-files](https://firebase.google.com/docs/storage/web/upload-files)

Initially I was also trying to avoid storing the file in the device, uploading it and then deleting it (option A).

Since camera can give image-assist and I can get base64 from image-assist, I can store that in firebase storage as base64. (OPTION B)

I do not know if Option A or B is better. Now I am going with Option A.
