### ISSUE TITLE
On iOS "permission denied" adding listener

### ISSUE THREAD

**Issue by ullalaaron** [EddyVerbruggen/nativescript-plugin-firebase#355]
Hello!
For some reason I cannot setup listeners on iOS (works perfectly on android).
Here is the code I use to setup the listener : 
```
        return firebase.addChildEventListener(
            (data)=>{
               //dostuff
        },
        path).
        catch((error)=>{
             //dump error
        });
```

The error I get is the following 
 
`<Warning> [Firebase/Database][I-RDB03812] Listener at /..../..... failed: permission_denied
`
What could be causing this?
As a note, I never remove listeners. Should I be doing that? If so, when?

**Comment by EddyVerbruggen** [comment]
I'd say firebase auth rules are in the way probably. Make sure the (logged in) user has access to that `path`. Please try the [demo app](https://github.com/EddyVerbruggen/nativescript-plugin-firebase-demo) to see a working case.
