### ISSUE TITLE
Can't re-authenticate with Google/Facebook on app hard-restart

### ISSUE THREAD

**Issue by RaphaelJenni** [EddyVerbruggen/nativescript-plugin-firebase#357]
How to reproduce:

1. Login to your account
2. Close the app and remove it from the task view
3. Reopen the app
4. Call `reauthenticate()`

**IS:**
Error: _Not logged in with google_ or  _Not logged in with facebook_

**SHOULD:**
Re-authenticate

On restart the variables 
```
// firebase.android.js - Line 10,11,12
firebase._rememberedContext = null;
firebase._googleSignInIdToken = null;
firebase._facebookAccessToken = null;
```
are reset to null. They should be stored in the appSettings.

**Comment by rossbg** [comment]
+1

**Comment by SamuelGRwebfab** [comment]
are we sure this issue is resolved? I just updated to the newest version and I am still getting this error

**Comment by SamuelGRwebfab** [comment]
It would seem that `firebase._facebookAccessToken` is not saving, I dont have time to today, but I will try to look further into it tomorrow.

**Comment by SamuelGRwebfab** [comment]
I found a temporary solution. I save the token to appsettings, then on reauth I pass this token to the reauth function which i edited slightly to accept the token. It works but it obv doesnt fix the issue at hand.

**Comment by EddyVerbruggen** [comment]
You mean it doesn't fix the issue because the plugin needs to be update with your suggestion?

**Comment by SamuelGRwebfab** [comment]
I was unable to find why the token isnt saving, I havent had to time to fully investigate it

**Comment by RaphaelJenni** [comment]
This issue is not fixed. Please reopen it.

**Comment by RaphaelJenni** [comment]
@EddyVerbruggen @witi83 How should this fix solve this problem. With your change, one of the main functionality of the anonymous account got killed. Why would I have an anonymous user if I can't convert him to an authenticated user.

This commit needs to be reverted. I have a fix for the issue with the reauth problem, described above. Please reopen that issue.

**Comment by EddyVerbruggen** [comment]
@RaphaelJenni You are right, this way you can't link anonymous accounts. What fix for the reauth problem are you talking about - is there a PR I missed?

**Comment by RaphaelJenni** [comment]
@EddyVerbruggen There isn't a PR. I solved it by manually copy and store the authTokens from the firebase object in the app. Then before reauthenticate, I set this tokens again to the firebase object.

**Comment by EddyVerbruggen** [comment]
Sounds like a great enhancement actually.

Do you use a plugin for secure storage? If not: keychain on iOS, and what exactly on Android?

**Comment by RaphaelJenni** [comment]
Yes I do, I'm using your plugin 😆

**Comment by RaphaelJenni** [comment]
What do you suggest @EddyVerbruggen ?

**Comment by EddyVerbruggen** [comment]
I think it would be great to have reauthenticate "just work". For now I think it would suffice to add your approach to the readme. Can you perhaps share the code you have to grab and restore the tokens? It would be perfect to have it [here](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/1167bb491cc43275296cc0ba40b23ab322d2ad7c/docs/AUTHENTICATION.md#reauthenticate).

**Comment by RaphaelJenni** [comment]
This is my code in a condensed way. You can extract the code you want for the README.

```
const fbase = require('nativescript-plugin-firebase');

//********************************

private static setAuthenticationToken(googleSignInToken: string, facebookSignInToken: string){
        const authTokens: AuthTokens = {
            googleSignInIdToken: googleSignInToken,
            facebookSignInToken: facebookSignInToken
        };
        
	this.secureStorage.set({
                key: UserService.SECURE_STORAGE_AUTH_TOKEN_KEY,
                value: JSON.stringify(authTokens)
            })
        );
}

private static getAuthenticationToken() {
        return JSON.parse(this.secureStorage.get({
                key: UserService.SECURE_STORAGE_AUTH_TOKEN_KEY
          }));
}

private static clearAuthenticationToken$() {
    this.secureStorage.remove({key: UserService.SECURE_STORAGE_AUTH_TOKEN_KEY});
}
	
//********************************
	
this.firebase.login({type: loginType})
   .then(() => UserService.setAuthenticationToken(fbase._googleSignInIdToken, fbase._facebookAccessToken))
			
			
//********************************
	
	
const reAuthenticationOptions = getAuthenticationToken();
	
fbase._googleSignInIdToken = authTokens.googleSignInIdToken;
fbase._facebookSignInToken = authTokens.facebookSignInToken;
	
this.firebase.reauthenticate(/*REAUTHENTICATION OPTIONS*/)
```

**Comment by EddyVerbruggen** [comment]
Thanks!

**Comment by RaphaelJenni** [comment]
No problem. And please revert this commit as soon as possible. It's project critical.

**Comment by witi83** [comment]
Hey guys.

I'm not quite sure, if I understand this problem correctly. How could my change (#445) break `reauthenticate` in the first place? Correct me if I'm wrong, but the documentation states that reauthentication should only be used, if the user _was_ already signed in. But in your case @RaphaelJenni the user is not, he is anonymous.

>  Why would I have an anonymous user if I can't convert him to an authenticated user.
Maybe we're doing something conceptually different than you, but this works in our case without any problems.

That being said, we don't use `reauthenticate` to "convert" a user to an authenticated one. We just call `login` providing the proper `LoginOptions`.

**Comment by RaphaelJenni** [comment]
@witi83 
> the documentation states that reauthentication should only be used, if the user was already signed in. But in your case @RaphaelJenni the user is not, he is anonymous.

No, the user is signed in, as an anonymous user. This user isn't just local, you can see him in the firebase console.

> That being said, we don't use reauthenticate to "convert" a user to an authenticated one. We just call login providing the proper LoginOptions.

If you do that, the user gets a new uid and you would have to copy the data over to the new user. Definitely not the correct way.

It's described in the docs: https://firebase.google.com/docs/auth/web/anonymous-auth#convert-an-anonymous-account-to-a-permanent-account

**Comment by witi83** [comment]
> No, the user is signed in, as an anonymous user. This user isn't just local, you can see him in the firebase console.

What happens in your case if you just call `login` instead of `reauthenticate`? Do you really see two accounts after it? AFAIK @EddyVerbruggen avoided this in the implementation of `login` where he takes care of the whole linking stuff.

So no, we don't copy any data from one user to another.

**Comment by RaphaelJenni** [comment]
Yes, you see two users. And yes he did, but with your change it doesn't link the account anymore, it just does a login. (it checks if the user is already assigned to the same provider, except for anonymous user (your change))

**Comment by witi83** [comment]
After reviewing the code base (specifically `login`) and the firebase documentation, it seems to me that you are correct: Anonymous users have to be linked as well!

However, I'm still curious about two things: First, why this change fixes the ominous `FirebaseAuthUserCollisionException`, which occured to a couple of people. Obviously, the real reason lies somewhere else.
And second, why didn't we observe the creation of two users as well. This is something I have to investigate.

In the meantime @EddyVerbruggen , feel free to revert it.

Thanks for @RaphaelJenni reporting!
