### ISSUE TITLE
Accessing child elements in firebase

### ISSUE THREAD

**Issue by mutox19** [EddyVerbruggen/nativescript-plugin-firebase#358]
Hi, I have been trying to access the child elements or the user id 
this is my query:

```js
  firebase.query(
      function(){},
      "/lottotickets",
      {
        singleEvent: true,
        orderBy: {
          type: firebase.QueryOrderByType.CHILD,
          value: "email"
        },
        range: {
          type: firebase.QueryRangeType.EQUAL_TO,
          value: currentUserEmail
        },
        limit: {
          type: firebase.QueryLimitType.FIRST,
          value: 1
        }
      }
    )
```

I am trying to access the ID(bolded below) of the users by searching for email when i do a dump on the result it shows 

```js
 {
     "type": "ValueChanged",
     "key": "lottotickets",
     "value": {
       <strong>  "-KiXZXk_vrH3x6nVzfUU"</strong>: {
             "address": "600 Westlake rd ",
             "email": "dan17@hot.com",
             "ticketnumber": "89,67,45,34,8",
             "ticketname": "Lotto Max"
         }
     }
 }
````

what i would like to access is the key(bolded) or be able to access all child data to display to users.
I have tried result.value. (with many options such as .key, .ID. id, .uid, .uuid) all returns undefined. Is there a way to access the key in the value or access the child elements in the the value, key?

Thank you

**Comment by EddyVerbruggen** [comment]
This is more of a JSON question than a Firebase question imo.

There's a few answers here: http://stackoverflow.com/questions/8711580/how-to-get-the-key-value-in-json-object

**Comment by mutox19** [comment]
thank you eddy
