### ISSUE TITLE
export fetchProvidersForEmail

### ISSUE THREAD

**Issue by rrizun** [EddyVerbruggen/nativescript-plugin-firebase#360]
would be great to export fetchProvidersForEmail

https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseAuth.html#fetchProvidersForEmail(java.lang.String)

https://firebase.google.com/docs/reference/ios/firebaseauth/api/reference/Classes/FIRAuth#-fetchprovidersforemailcompletion

**Comment by EddyVerbruggen** [comment]
Nice, and thanks for the SDK links.

**Comment by EddyVerbruggen** [comment]
Added to 4.0.0.
