### ISSUE TITLE
[Question] Integration with ElasticSearch

### ISSUE THREAD

**Issue by davorpeic** [EddyVerbruggen/nativescript-plugin-firebase#363]
Hi Eddy,

do you think this is something could be implemented with query method do be hable to do more advanced search/filter https://medium.com/@NodeArt/improving-firebase-database-searching-abilities-with-elasticsearch-f999245e3925

thanks
davor

**Comment by RaphaelJenni** [comment]
You can try http://elasticlunr.com/. This gives you a way to locally search/filter the data.

**Comment by davorpeic** [comment]
Thanks @RaphaelJenni but downloading large amount of data locally to be able to filter isn't very performant compared on doing that on the server.

I will close this issue as new Firestore (already implemented https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/FIRESTORE.md) is what will do the job :)
