### ISSUE TITLE
How to access the query results?

### ISSUE THREAD

**Issue by d3mac123** [EddyVerbruggen/nativescript-plugin-firebase#364]
When I ask for a console.dump(result.value), I get the following:
{
     "-KjJ_KADr9XDrC5K0Hz2": {
         "name": "Alex Souza",
         "uid": "mADTA83iTlJ2",
         "nick": "",
         "mainColor": "#CEFF00",
         "secColor": "59B9D6",
     }
 }

How to access, for example, the content of "name"?

I've tried to convert the JSON to an array but it is crashing:
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onDataChange failed

SyntaxError: Unexpected token o in JSON at position 1
File: "<unknown>, line: 1, column: 1

Thanks!
Alex

**Comment by tsebvaan** [comment]
use loop
```
for(let uid in result.value){
      console.log(uid);
      console.dump(result.value[uid]);
      console.log(result.value[uid]["name"]);
}
```
