### ISSUE TITLE
IOS firebase to JSON not converting numbers with NSDecimalNumber subclass

### ISSUE THREAD

**Issue by jorgelcf** [EddyVerbruggen/nativescript-plugin-firebase#365]
Hi,

I was not receiving the keys which values were numbers in firebase due to the fact that the class received from the getClass method call is NSDecimalNumber.

I resolved the issue by adding 'NSDecimalNumber' as an option to the switch of the funtion 'firebase.toJsObject' (line 354).

**Comment by EddyVerbruggen** [comment]
Cool. Are you up for a little PR perhaps?

**Comment by EddyVerbruggen** [comment]
Added this to 4.0.0.

**Comment by EddyVerbruggen** [comment]
Also added a fallback and warning for any other possibly missing types.
