### ISSUE TITLE
[iOS] onMessageReceivedCallback not called when app is in background

### ISSUE THREAD

**Issue by simba4everyoung** [EddyVerbruggen/nativescript-plugin-firebase#368]
I'm having an issue with onMessageReceivedCallback not called when app is in background or is reopened from background on iOS (tested on real device). 
In the callback function, I save the notification details so users can check back in the app. It works great when app is in foreground. 
I can receive the notifications when app is in background. 
If the app is reopened by clicking the notification, I can see the notification in the plugin output from console (attached below). 

`[320:22412] didReceiveNotification`

But the details won't be saved.
I'm sure I already did what [here](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/MESSAGING.md#enable-push-support-in-xcode) says. 'Background App Refresh' is switched open on my device.

Some version info...
iOS: 10.3.1
Xcode: 8.3.2
```
"dependencies": {
    "nativescript-drop-down": "^1.5.3",
    "nativescript-geolocation": "0.0.19",
    "nativescript-orientation": "^1.6.1",
    "nativescript-platform-css": "^1.4.0",
    "nativescript-plugin-firebase": "^3.11.4",
    "nativescript-sidedrawer": "^1.0.5",
    "nativescript-sqlite": "^1.1.3",
    "nativescript-telerik-ui": "^1.6.2",
    "nativescript-theme-core": "~1.0.2",
    "nativescript-zxing": "^1.5.2",
    "tns-core-modules": "2.5.2",
    "ts-promise": "^0.3.4"
  },
  "devDependencies": {
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "lazy": "1.0.11",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "~0.3.5",
    "typescript": "~2.1.0"
  }
```

Am I missing something? Or has anyone had same issue and found ways to work around of this?

**Comment by SFXMBatroukh** [comment]
I'm Having the same issue @EddyVerbruggen

**Comment by SFXMBatroukh** [comment]
Also, it works on and saves on the iOS simulator but not on the physical device, any idea what is happening?

**Comment by simba4everyoung** [comment]
[UPDATE]
I have read every thread that related to this topic. I've checked all the mentioned setup tips.

Still, I can get the push notification and badge, but when I open the app through the notification, the callback function doesn't fire so I can't save the message in app. 
I also noticed, when I add 
```
<key>FirebaseAppDelegateProxyEnabled</key>
<false/>
```
I won't receive the notification pop and badge doesn't appear. However, the callback function is able to fire after I open the app from background, so the message can be saved.

**Comment by simba4everyoung** [comment]
Using correct silent notification message format resolved this issue.
```
{
	"to": "/topics/ios",
	"content-available": 1,
	"sound": "default",
	"data":{
		"title":"Notification Title",
		"body":"text"
	},
	"priority": "High"
}
```

**Comment by BMwanza** [comment]
@simba4everyoung Hey, what version of Firebase are you using? I am still struggling with this
