### ISSUE TITLE
Support Firebase Performance Monitoring

### ISSUE THREAD

**Issue by RaphaelJenni** [EddyVerbruggen/nativescript-plugin-firebase#370]
Support the new Firebase Feature called "Performance Monitoring".
https://firebase.google.com/docs/perf-mon/

**Comment by ivanwitzke** [comment]
Any info about this? Am I able to use it with the plugin?

**Comment by bearoutthere** [comment]
Bump.   Any updates on performance monitoring support?

**Comment by RaphaelJenni** [comment]
Performance Monitoring is working now. Tried it locally directly inside the node_modules folder. Should be an easy thing to implement it.
But currently, I don't think, that I find the time to create a PR.

**Comment by FatimahSanni** [comment]
Hi, is this feature supported now?

**Comment by EddyVerbruggen** [comment]
Although it's easy to add this feature, I never got around adding it. Aiming to have it in the next minor version though (probably as soon as next week).

**Comment by EddyVerbruggen** [comment]
Available in 7.3.0 (about to publish): https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/PERFORMANCE_MONITORING.md

Note that I've seen the performance metrics pop up on the Firebase console for iOS just fine (after a ~12h delay, per their documentation), but I have not yet seen it for Android (although the SDK is called correctly, and getting values from the trace works just fine)... I guess I'll need to wait a bit longer. Curious to learn your experiences with this!
