### ISSUE TITLE
Google and Facebook conflict in IOS, can't use at the same time, want help :) 

### ISSUE THREAD

**Issue by wisonye** [EddyVerbruggen/nativescript-plugin-firebase#390]
Hi guys, I just try `Google Sign-In` and `FaceBook Login` in same IOS app like this:
<img width="339" alt="screen shot 2017-06-15 at 17 49 11" src="https://user-images.githubusercontent.com/3477321/27167175-959bb9b4-51f3-11e7-8856-5b480da27b90.png">

But finally I found that I only can choose one of them, and the reason I found is located at the **`Info.plist`** file:

```
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<!-- For FaceBook Login -->
			<key>CFBundleURLSchemes</key>
			<array>
				<string>fbxxxxxx</string>
			</array>

			<!-- For Google Login -->
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>REVERSED_CLIENT_ID</string>
			<key>CFBundleURLSchemes</key>
			<array>			
				<string>com.googleusercontent.apps.yyyyyy</string>
			</array>
		</dict>
	</array>
```

As you can see there are two _**`CFBundleURLSchemes`**_ with different values there, so I think the plugin somehow doesn't know pick the right one, I only can do that manually to choose:

* If use Facebook login, comment the Google related _**`CFBundleURLSchemes`**_ 

* If use Google sign-in, comment the Facebook related _**`CFBundleURLSchemes`**_ 

Then it will works fine, otherwise, the app will crash :(

So is that possible that the plugin does it more smarter, when call `firebase.login()`, check the `type`, 

- if is `firebase.LoginType.GOOGLE` then read the Google related _**`CFBundleURLSchemes`**_ 

- if is `firebase.LoginType.FACEBOOK` then read the Facebook related _**`CFBundleURLSchemes`**_

**Comment by ShawnPavel** [comment]
Hey @wisonye. We actually use both google and facebook in our app. Below is how our plist is set up. The big difference I noticed is that we keep them in separate dictionaries.

```
<key>CFBundleURLTypes</key>
<array>
    <dict>
       <key>CFBundleTypeRole</key>
       <string>Editor</string>
        <key>CFBundleURLName</key>
        <string>REVERSED_CLIENT_ID</string>
        <key>CFBundleURLSchemes</key>
        <array>
            <string>{google goes here}</string>
        </array>
    </dict>
    <dict>
        <key>CFBundleURLSchemes</key>
        <array>
            <string>{facebook goes here}</string>
        </array>
    </dict>
</array>
```

**Comment by EddyVerbruggen** [comment]
Thanks for trying to help others out, @ShawnPavel!

**Comment by wisonye** [comment]
@ShawnPavel Yup, tested, it works perfectly, thanks man :)
