### ISSUE TITLE
please fix the version conflict either by updating ..........

### ISSUE THREAD

**Issue by nelsonwilliam11** [EddyVerbruggen/nativescript-plugin-firebase#393]
am trying to use firebase-messaging and my version is 10.0.1 but the google services needs 10.2.+ i don't know how to updatde it to the latest version can anyone help?
how can i update the firebase-messaging ???

**Comment by EddyVerbruggen** [comment]
Install Android Studio and launch the SDK manager. Then update the repositories as mentioned in the readme. That's perhaps easiest.

**Comment by nelsonwilliam11** [comment]
But I already update all of them and it still throws the same error

**Comment by EddyVerbruggen** [comment]
Was Google any help? It's quite a generic problem so there should be something on the web that helps you. I can't access your computer so it's a bit hard for me to offer assistance.

**Comment by rytyr** [comment]
I got the same issue. already update everything.

**Comment by nelsonwilliam11** [comment]
Problem solved thanks

**Comment by ParVisual** [comment]
@nelsonwilliam11 how do you solve it?

**Comment by nelsonwilliam11** [comment]
Simply by updating your firebase plugin to the required version
