### ISSUE TITLE
email login error

### ISSUE THREAD

**Issue by gbonline** [EddyVerbruggen/nativescript-plugin-firebase#397]
With my iOS app and also in your demo just cloned, I get the following error
`CONSOLE LOG file:///app/tns_modules/nativescript-plugin-firebase/firebase.js:1193:18: Error in firebase.login: ReferenceError: Can't find variable: FIREmailAuthProvider`

**Comment by EddyVerbruggen** [comment]
Please don't crosspost.

**Comment by gbonline** [comment]
I'm sorry, 
but I need a solution, I'm stuck with my app

**Comment by EddyVerbruggen** [comment]
See my comment in the crosspost.
