### ISSUE TITLE
v4.0.2 fails Webpack/Angular AoT

### ISSUE THREAD

**Issue by DickSmith** [EddyVerbruggen/nativescript-plugin-firebase#399]
```
ERROR in ../~/nativescript-plugin-firebase/firebase.ios.js
Module parse failed: /Users/dick/src/pnp-client-mobile/node_modules/nativescript-plugin-firebase/firebase.ios.js 'return' outside of function (21:2)
You may need an appropriate loader to handle this file type.
| } catch (e) {
|   console.log(">>>> Firebase is not configured correctly; please remove your 'platforms/ios' folder, then run 'tns run ios'");
|   return;
| }
|
 @ ./vendor.ts 25:0-39
```

Removing the return resolves this.

**Comment by EddyVerbruggen** [comment]
Hi Dick,

Did pre-4.0 versions also fail with webpack? Just wondering if this is something I broke recently..

Thanks,
Eddy

**Comment by EddyVerbruggen** [comment]
Oh nevermind.. that's indeed brand new code.

**Comment by hypery2k** [comment]
having this issue, too. Any suggestions or progress on this bug?

**Comment by EddyVerbruggen** [comment]
Not yet, any suggestions on your part perhaps?

**Comment by hypery2k** [comment]
Expected behaviour. Top level returns are not ES6 module compliant. So that's why it's failing.

Will add a PR for this issue as soon as i verified my AoT build with iOS

**Comment by hypery2k** [comment]
So mor me it's working with my changes for iOS and AoT build.

@EddyVerbruggen: Would be great if you release an patched version of the plugin

**Comment by EddyVerbruggen** [comment]
Awesome, will be part of 4.0.3 which I'll publish later today.
