### ISSUE TITLE
TypeError: Cannot read property 'firebase' of undefined

### ISSUE THREAD

**Issue by mi6crazyheart** [EddyVerbruggen/nativescript-plugin-firebase#40]
I'm using this plugin in my new Nativescript project & getting following error -

`JS: Clicked on Login button
JS: Error in firebase.init: TypeError: Cannot read property 'firebase' of undefined
JS: firebase.init error: TypeError: Cannot read property 'firebase' of undefined`

Here is the link of my Stackoverflow post  : http://stackoverflow.com/questions/37565864/typeerror-cannot-read-property-firebase-of-undefined-in-nativescript-app

As, totally new to both NativeScript & TypeScript I can't able to understand how to solve it.

**Comment by 441N143G** [comment]
import firebase = require("nativescript-plugin-firebase");

**Comment by mi6crazyheart** [comment]
When I'm doing changes in "reference.d.ts" file, following error I'm getting

![firebase-error-modified](https://cloud.githubusercontent.com/assets/4346688/15742204/1dc94682-28db-11e6-8110-6adb0b8a4364.png)

**Comment by 441N143G** [comment]
No) u must add this line in reference.d.ts in root dir of project)

**Comment by mi6crazyheart** [comment]
@441N143G : Sorry, I added the wrong screenshot. Now, I've updated my Screenshot. You can see.

**Comment by mi6crazyheart** [comment]
I think, I need to add "extension" in the path. But, which 'ts' file I need to point. There are 2 'ts' files.
- firebase-common.d.ts
- firebase.d.ts

By, adding extension to the file path error is getting resolved. But, I don't understand to which TS file I need to point.

**Comment by 441N143G** [comment]
Can u make screen with project structure?

**Comment by mi6crazyheart** [comment]
Here is the folder structure of my application 

![firebase-structure-cropped](https://cloud.githubusercontent.com/assets/4346688/15742607/a97df0b8-28dd-11e6-9bae-e42f29059f8b.png)

**Comment by 441N143G** [comment]
Maybe this help: This is how looks files in my test app (native, angular2, firebase, created with: tns create tespApp --ng) (works as expected):
reference.dt.ts(in root folder): 
`/// <reference path="./node_modules/tns-core-modules/tns-core-modules.d.ts" /> Needed for autocompletion and compilation.
/// <reference path="./node_modules/nativescript-plugin-firebase/firebase" />`
app.component.ts:
`import {Component} from "@angular/core";
import firebase = require("nativescript-plugin-firebase");
@Component({
...
export class AppComponent {
    public counter: number = 16;
    constructor() {
        firebase.init(<any>{
            persist: true // Allow disk persistence. Default false.
        }).then(
            function(instance) {
                console.log("firebase.init done");
            },
            function(error) {
                console.log("firebase.init error: " + error);
            }
            );
...
`

**Comment by mi6crazyheart** [comment]
Can you tell which file path I should give in "reference path" link ? It should point to `firebase-common.d.ts` or `firebase.d.ts` ?

**Comment by 441N143G** [comment]
in my project - firebase.d.ts

**Comment by mi6crazyheart** [comment]
If I point reference path link to "firebase.d.ts" then IntelliSense is not giving any error. But, at the compiling time, I'm getting the same error. 

JS: Clicked on Login button
JS: Error in firebase.init: TypeError: Cannot read property 'firebase' of undefined
JS: firebase.init error: TypeError: Cannot read property 'firebase' of undefined

**Comment by mi6crazyheart** [comment]
Is following code is fine ?

    import {Component} from "@angular/core";
    import {User} from "./shared/user/user";
    import {UserService} from "./shared/user/user.service";
    import {HTTP_PROVIDERS} from "@angular/http";
    import firebase = require("nativescript-plugin-firebase");

    @Component({
      selector: "my-app",
      providers: [UserService, HTTP_PROVIDERS],
      templateUrl: "pages/login/login.html",
      styleUrls: ["pages/login/login-common.css", "pages/login/login.css"]
    })

    export class AppComponent {
        user: User;
        isLoggingIn = true;

        constructor(private _userService: UserService) {
            this.user = new User();
        }

        submit() {
            if (this.isLoggingIn) {
                this.login();
            } else {
                this.signUp();
            }
        }

        login() {
            // TODO: Define
            console.log('Clicked on Login button');

            firebase.init(<any>{
                persist: true // Allow disk persistence. Default false.
            }).then(
                function (instance) {
                    console.log("firebase.init done");
                },
                function (error) {
                    console.log("firebase.init error: " + error);
                }
            );
        }

        signUp() {
            this._userService.register(this.user);
        }

        toggleDisplay() {
            this.isLoggingIn = !this.isLoggingIn;
        }
    }

**Comment by 441N143G** [comment]
can u put firebase.init(<any>... in constructor() - just 4 test?

**Comment by mi6crazyheart** [comment]
I did that also when I saw in your code. But, that's also giving me the same error.

**Comment by 441N143G** [comment]
error when app just starting or after tap event?

**Comment by mi6crazyheart** [comment]
I'm using `tns livesync android --watch` . So, just after saving the file when compiler start compiling once again.. I'm getting that error.

**Comment by 441N143G** [comment]
Do u do this: google-services.json which you'll add to your NativeScript project at platforms/android/google-services.json ?

**Comment by mi6crazyheart** [comment]
YES. I've setup that also.

**Comment by 441N143G** [comment]
its seems your code wont execute "undefined.firebase". u have many way to get undefined) i was thought there something like this: some code try execute "this.firebase...." but context of "this" is lost. Maybe author of plugin will help u better.

**Comment by mi6crazyheart** [comment]
@441N143G : Just for curiosity here is my package.json file. Is it fine or there is some problem.

    {
      "description": "NativeScript Application",
      "license": "SEE LICENSE IN <your-license-filename>",
      "readme": "NativeScript Application",
      "repository": "<fill-your-repository-here>",
      "nativescript": {
        "id": "org.nativescript.bhramaan",
        "tns-android": {
          "version": "2.0.0"
        }
      },
      "dependencies": {
        "@angular/common": "2.0.0-rc.1",
        "@angular/compiler": "2.0.0-rc.1",
        "@angular/core": "2.0.0-rc.1",
        "@angular/http": "2.0.0-rc.1",
        "@angular/platform-browser": "2.0.0-rc.1",
        "@angular/platform-browser-dynamic": "2.0.0-rc.1",
        "@angular/platform-server": "2.0.0-rc.1",
        "@angular/router-deprecated": "2.0.0-rc.1",
        "nativescript-angular": "0.1.1",
        "nativescript-plugin-firebase": "^3.0.1",
        "tns-core-modules": "^2.0.0"
      },
      "devDependencies": {
        "babel-traverse": "6.9.0",
        "babel-types": "6.9.0",
        "babylon": "6.8.0",
        "filewalker": "0.1.2",
        "lazy": "1.0.11",
        "nativescript-dev-typescript": "^0.3.2",
        "typescript": "^1.8.10"
      },
      "android": {
        "defaultConfig": {
            "applicationId" : "org.nativescript.bhramaan"
        }
      }
    }

**Comment by 441N143G** [comment]
Maybe try create clear project with: tns ctreate myMegaProj --ng ?) if u'll have same trouble when added plugin - u can use any native "sugar" without plugins - just read docs: https://docs.nativescript.org/core-concepts/accessing-native-apis-with-javascript

**Comment by mi6crazyheart** [comment]
@441N143G - As I told you yesterday that, I'm using `tns livesync android --watch` at the time of development. But today, I discovered a build issue when I'm once tried the command `tns run android`. For that I've open an issue at here - https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/41

But, plugin author is telling it's not seems plugin related issue. But, now I feel all these issue are coming because of that build issue. If I can able to resolve that one then, may be this issue also get resolve.

But, I've no idea what's the problem & where is the issue is. Currently thinking, to open an issue in 'NativeScript' repository it self.

**Comment by mi6crazyheart** [comment]
As issue - https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/41 resolved which also resolved this ongoing issue I'm going to close the thread. @441N143G Again, thank you a lot.

**Comment by 441N143G** [comment]
u are welcome)

**Comment by Melf11** [comment]
i had the same problem and finally just reinstalled plugin
`npm plugin remove nativescript-plugin-firebase`
`npm plugin add nativescript-plugin-firebase`
