### ISSUE TITLE
Livesync not working on android

### ISSUE THREAD

**Issue by vcooley** [EddyVerbruggen/nativescript-plugin-firebase#401]
We've had a problem with live sync on Android after installing the plugin. After running `tns run android` and making a change, the console prints out a message that the modified files have been transferred, but there is no indication on the app. The app does not refresh or reflect the changes made.

**Comment by ivanwitzke** [comment]
same problem here...

**Comment by ivanwitzke** [comment]
Found out that my package name was different in some places/files. (I think after trying the [nativescript-sidekick](https://www.nativescript.org/nativescript-sidekick) and changing it from there - not sure what happened) but in my case looks like its working now...
I just don't know why the compiler or even Android didn't show any error...

**Comment by vcooley** [comment]
I found an instance where my package name was different as well (in app.gradle). It appears that livescync is working after making that change.
