### ISSUE TITLE
Question: Use Remote Config to set API Url in app - Good or Bad idea?

### ISSUE THREAD

**Issue by zoeitsolutions** [EddyVerbruggen/nativescript-plugin-firebase#403]
Hi Gents.

I have been reading a lot of articles in regards to security and other parties reverse engineering your app and then hammering your APIs etc.

For my current app I am using Firebase for Auth and then have my own API URL hardcoded into the app.

I am considering using Remote Config to retrieve my API URL and then setting it in the app.

I was wondering if someone has done this before? And if this approach is a good or bad idea?

Thanks. Robert

**Comment by EddyVerbruggen** [comment]
You should really take this to SO as there are lots of folks happy to answer your question when using the firebase tag (as opposed to only my opinion).
