### ISSUE TITLE
Build failed on NativeScript 2.0.1

### ISSUE THREAD

**Issue by mi6crazyheart** [EddyVerbruggen/nativescript-plugin-firebase#41]
HI,
After adding this plugin I'm getting following error when I'm trying to build my app by using `tns run android` command.

Error -

![firebase-error-cropped](https://cloud.githubusercontent.com/assets/4346688/15775797/985ab0e0-29a1-11e6-971d-5c65c91054b5.png)

**Comment by EddyVerbruggen** [comment]
Doesn't look like a plugin-specific error to me. Can you try removing and adding the Android platform?

`tns platform remove android && tns platform add android`

If that doesn't help please test on a new project.

**Comment by mi6crazyheart** [comment]
@EddyVerbruggen : Thanks for your quick reply. But, after running `tns platform remove android && tns platform add android` command now I'm getting following error. 

![firebase-error-cropped](https://cloud.githubusercontent.com/assets/4346688/15777329/f721098a-29ab-11e6-8cb0-37bfd77c6019.png)

I'm new to nativeScript. So, don't know a lot. But, before adding this plugin my app was working properly. Just only after adding this one. I've started getting this error.

**Comment by EddyVerbruggen** [comment]
Never seen this one. Perhaps others reading this have an idea?

**Comment by mi6crazyheart** [comment]
I've no idea what's happening. I have a working copy which I took as a backup before adding this plugin. Which works fine. But, after adding this plugin only.. something is happening & whole build process is failed. Already 2 times I've done this thing & I'm getting same behaviour each time.

**Comment by 441N143G** [comment]
It seems multiDex error. U can add multiDex(multiDexEnabled true) supprot in your app.gradle. something like this:
android {
  defaultConfig {
    applicationId "com.mysite.myproj"
    generatedDensities = []
    multiDexEnabled true
  }

**Comment by 441N143G** [comment]
*and rebuild project

**Comment by mi6crazyheart** [comment]
@441N143G : Thanks a lot for patience & helping hand. Finally, your above suggestion `multiDexEnabled true` did the job. Now, previous firebase error `Cannot read property 'firebase' of undefined` also resolved.

By the way, what's is this `multiDex` thing? Why was it shown to me? Is anything wrong in my development? 

Man, you just made my day. From last 2 days, I was struggling with this & as I'm using NativeScript with AngularJS2 which is still in testing phase today I thought to give up this R&D on NativeScript as long as AngualrJS2 will not production ready. 

But, now I can move ahead. By the way, I'm from India. Bug me whenever you'll be at here. I'll buy you a beer.

**Comment by 441N143G** [comment]
you are welcome :-) about multiDex: https://developer.android.com/studio/build/multidex.html

**Comment by mi6crazyheart** [comment]
Have you also added that `multiDexEnabled true` in your test app & Shall this thing should be mentioned in Plugin doc ?

**Comment by EddyVerbruggen** [comment]
NativeScript issue related to this phenomenon: https://github.com/NativeScript/android-runtime/issues/344

**Comment by 441N143G** [comment]
In test app -  yes. This is not plugin fail, but if author will put few lines about this issue in readMe  - will be great)

**Comment by mi6crazyheart** [comment]
All right. Thanks a lot for your support people. I'm closing this issue now.

**Comment by EddyVerbruggen** [comment]
Added a note to the readme, thx! 👍

**Comment by LakshmiEvana** [comment]
HI,
After adding this plugin I'm getting following error when I'm trying to build my app by using tns run android command.

Error -
Command E:\Native Script\firebasetest3\platforms\android\gradlew.bat failed with
 exit code 1
Help me please!

**Comment by dameety** [comment]
Facing this issue too, right now, but this solution does not work for me. removing and adding platform android, enabling multidex.

**Comment by lumayara** [comment]
I am facing the same issue. I already added the 

> /// <reference path="./node_modules/nativescript-plugin-firebase/firebase.d.ts" />

 on references.d.ts, already added 

> multiDexEnabled = true

 on app.graddle and still get 

> JS: Error in firebase.init: TypeError: Cannot read property 'getInstance' of undefined
