### ISSUE TITLE
[iOS] Cloud Messaging - No Background Notifications

### ISSUE THREAD

**Issue by tonyhogben** [EddyVerbruggen/nativescript-plugin-firebase#415]
nativescript-plugin-firebase: 4.0.2
tns-core-modules: 3.0.0
tns-ios: 3.0.1
tns-android: 3.0.1

Okay, so after a good day or two fighting this I am at a loss.

I have followed the installation and setup instructions to the letter (apart from the recent change at Apple that left the Google instructions slightly out of sync - regarding the APN Key) and have a fully working Android implementation, plus I receive messages in foreground of iOS (though they stop after the App is killed and restarted - I have tried moving the initialization code out of app.ts and into my first main page as per suggestions from other git issues).

**My questions:**

1. Am I correct in my understanding that the _onMessageReceivedCallback_ function should be called when the app is in the background?
2. Am I correct in thinking that native background notifications (i.e. appearing in the notification center) are invoked by the plugin and that nothing needs to be done within the _onMessageReceivedCallback_ function?
3. What am I doing wrong!? ;)

**Firebase:**

I have created the iOS App and added the Apple APNs Authentication Key under the Project Settings > Cloud Messaging (this step appears to be missing from the setup documentation).

**Info.plist:**

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        ...
	<key>UIBackgroundModes</key>
	<array>
		<string>remote-notification</string>
	</array>
</dict>
</plist>
```

**.entitlements file:**

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>aps-environment</key>
	<string>development</string>
</dict>
</plist>
```

**app.ts / main page initialization:**

```
firebase.init({
    onPushTokenReceivedCallback: token => {
        console.log("Firebase push token: " + token);
    },
    onMessageReceivedCallback: (message: firebase.Message) => {
        console.log("--- message received: " + message.title + " - " + message.body);
        setTimeout(function () {
            alert({
                title: (message.title !== undefined ? message.title : ""),
                message: (message.body !== undefined ? message.body : ""),
                okButtonText: "Okay"
            });
        }, 3000);
}}).then(
    (instance) => {
        console.log("firebase.init done");
},
    (error) => {
        console.log("firebase.init error: " + error);
});
```

**Comment by vswee** [comment]
My advise strictly refers to the last working version. 

1. _onMessageReceivedCallback_ should be run after firebase.init with a declared function to handle messages in the app UI. - You may choose to save to SQLite or simply display an alert or console log etc.

2. Setting an _onMessageReceivedCallback_ , invokes an appDelegate which handles the seamless Notification Centre integration whilst the app is in the background or killed etc.

The documentation as far as I am aware instructs on the use of Development/Production certs which are generated via Apple Developer site and exported as .p12s using keychain then uploaded to FCM console. (In the past, _after much frustration and confusion_, completing this step correctly would make everything work as one would expect)

Perhaps your problem is a bit like mine: #402 ?

**Comment by tonyhogben** [comment]
@vswee, thanks for the clarification. When you say last working version, which version are you referring to? ;)

Apple appear to have changed the APNs Key stuff very recently and you now get one .p8 certificate for both dev and prod use. FCM accepts either this new .p8 key or a .p12 cert. I wondered if this was having any bearing and did some digging, but feel confident it should work.

We are perhaps suffering the same issue here?

I am not using {N} - I don't know if that has any relevance.

**Comment by vswee** [comment]
@tonyhogben v3.12.0 worked for me without flaw (for FCM that is).

Admittedly I've not tried testing now with v3.12.0.

I did try the APNs Key potion in FB Console but it made no difference that I could see.

**Comment by tonyhogben** [comment]
@vswee Thanks for the suggestion.

I tried v3.12.0 but I couldn't even get it to deliver a message whilst the app was running!

Today I have run the app both locally (on a device) and via TestFlight with v3.12.0 and v4.0.3 with both an APNs Key and an older style APNs certificate. Nothing creates a background notification and only v4.0.3 (with both the key or the cert) creates a foreground alert when the app is running.

I am quite literally pulling my hair out!

**Comment by vswee** [comment]
There's work being done on it according to the open Pull Requests.

This article on implementing the plugin from May this year notes that it currently doesn't work http://developer.telerik.com/products/nativescript/use-firebase-cloud-messaging-nativescript-app/

**Comment by dominikspeh** [comment]
Any updates here? I've got the same problem :/

**Comment by vswee** [comment]
I'd recommend what I did -revert to version 3.12.0.
Cloud Messaging works as expected in development (i.e. I haven't tested with test flight or publishing) and you'll be able to get on with other aspects of your app.

**Comment by tonyhogben** [comment]
I am using version 4.05 without any issues.

**Comment by greedz** [comment]
I'm not receiving background pushes on iOS with `^4.1.1`. Reverting to `^3.12.0` fixes this.

**Comment by shiamalon** [comment]
What worked for me:
firebase.init on main.ts
firebase.addOnPushTokenReceivedCallback and firebase.addOnMessageReceivedCallback on the second screen, after the login

Notifications working everywhere except **background notifications for IOs that I got only working on a real device.** 

Wasted to much time with the bold section.
