### ISSUE TITLE
[iOS] [Android] Cloud Messaging - subscribeToTopic not working

### ISSUE THREAD

**Issue by tonyhogben** [EddyVerbruggen/nativescript-plugin-firebase#416]
After initializing the plugin on the app.ts or first page, I then call the following code on another page...

```
import { subscribeToTopic } from "nativescript-plugin-firebase";

function obButtonTap() {
    subscribeToTopic("TopicName")
}
```

This does not create a new topic inside FCM. Am I missing something here?

**Comment by rafaelcmrj** [comment]
Did you figure this out? Try adding a:

`subscribeToTopic("TopicName").then(success => {
console.log(success);
}, error => {
console.log(error);
});`

**Comment by tonyhogben** [comment]
I did thank you. I used very similar code. My apologies for leaving this issue open.

**Comment by rafaelcmrj** [comment]
@tonyhogben could paste your code as an example?

**Comment by tonyhogben** [comment]
Sure...

```
subscribeToTopic(topicID)
  .then(function(response) {
    console.log("Successfully subscribed to topic: " + response);
  })
  .catch(function(error) {
    console.log("Error subscribing to topic: " + error);
  });
```

**Comment by rafaelcmrj** [comment]
It's not working for me... how are you importing the method? not `import firebase = require("nativescript-plugin-firebase");` ?

**Comment by tonyhogben** [comment]
Hi Rafael,

Sorry, let me try and be of more help. My problems mainly stemmed from the app initialisation and in my app.ts I ended up with this code before my app.start...

```
import * as firebase from "nativescript-plugin-firebase";

app.on("launch", () => {
  if (app.ios) {
    initFirebase();
  }
});

if (app.android) {
  initFirebase();
}

function initFirebase() {
  // Initialize firebase (Notifications)
  firebase.init({
      onPushTokenReceivedCallback: token => {
        console.log("Firebase push token: " + token);
      },
      onMessageReceivedCallback: message => {
        //console.dir(message);
        let title: string = "Important Update";
        if (message.title) {
          title = message.title;
        }
        alert({
          title: title,
          message: message.body,
          okButtonText: "Okay"
        }).then(function () {
          //console.log("Dialog closed!");
        });
      }
  }).then(
      (instance) => {
        console.log("firebase.init done");
      },
      (error) => {
        console.log("firebase.init error: " + error);
      }
  );
}
```

This solved the other issues I was having regarding iOS not displaying background notifications.

I then used the following code in another page to manage subscriptions...

`import { subscribeToTopic, unsubscribeFromTopic } from "nativescript-plugin-firebase";`

```
subscribeToTopic("topicID")
  .then(function(response) {
    console.log("Successfully subscribed to topic:", response);
  })
  .catch(function(error) {
    console.log("Error subscribing to topic:", error);
  });
```

```
unsubscribeFromTopic("topicID")
  .then(function(response) {
    console.log("Successfully unsubscribed from topic:", response);
  })
   .catch(function(error) {
    console.log("Error unsubscribing from topic:", error);
  });
```

For me, this works.

P.S. I am using v4.05 of the plugin.

**Comment by rafaelcmrj** [comment]
Yeah, my code is almost the same.. I can get the token, but subscribe isn't working.. I can't send messages through Firabase console... and the subscribeToTopic returns undefined in the success method (weird).

**Comment by tonyhogben** [comment]
If I remember correctly (don't quote me on this!), I had trouble sending messages to topics via the Firebase console, so I used [PostMan](https://www.getpostman.com/) and constructed the calls to the API.

I was building it all into a web app to support the mobile app, so this was something I needed to do anyway.

**Comment by rafaelcmrj** [comment]
I'm also POST request but the notification doesn't show up in the app. I'm gonna test Android, but iOS doesn't work!! Did you do anything else other than import the APNs Key?

**Comment by tonyhogben** [comment]
I am posting to [https://fcm.googleapis.com/fcm/send](https://fcm.googleapis.com/fcm/send)

In my headers I have 2 keys..

```
Authorization: "key=<your FCM API key>"
Content-Type: "application/json"
```

The body is set to raw and looks like this (for a single topic)...

```
{
  "to": "/topics/<TopicName>",
  "title": "your title",
  "body": "your message",
  "content-available": 1,
  "prority": "high",
  "notification": {
    "title": "your title",
    "body": "your-message"
}
```

For multiple topics, it is a little different...

```
{
  "condition": "'<TopicName>' in topics || '<TopicName>' in topics",
  "title": "your title",
  "body": "your message",
  "content-available": 1,
  "prority": "high",
  "notification": {
    "title": "your title",
    "body": "your-message"
}
```

With the _**condition**_, it is important to note, according to [https://firebase.google.com/docs/cloud-messaging/http-server-ref](https://firebase.google.com/docs/cloud-messaging/http-server-ref)... 

> Supported operators: &&, ||. Maximum two operators per topic message supported.

I.e. you can only have 3 queries in here (which IMHO is a dumb limitation).

**Comment by rafaelcmrj** [comment]
Hi, @tonyhogben thanks for your help. In my code, the subscribeToTopic isn't working.. it always returns undefined in the success method... I've created a new issue in the repository but I didn't have an answer yet
