### ISSUE TITLE
Logout breaking on Android when nativescript-fresco plugin is added to app

### ISSUE THREAD

**Issue by shripalsoni04** [EddyVerbruggen/nativescript-plugin-firebase#418]
In my application I have installed both `nativescript-fresco` and `nativescript-plugin-firebase`.

When I tried to call `firebase.logout()` it failed with error: "Cannot call LoginManager of undefined". I tried to find the root cause. The issue is coming at below lines in `logout` function.

`firebase.android.js`
```
 if (typeof(com.facebook) !== "undefined") {
  com.facebook.login.LoginManager.getInstance().logOut();
}
```

As, due to `nativescript-fresco`, `com.facebook` will not be undefined and so it will try to call `com.facebook.login.LoginManager.getInstance().logOut()`. But it will not be able to find `com.facebook.login` and will break.

**Possible Solution:**

We may change the condition to
`if (typeof(com.facebook.login) !== "undefined")`

Let me know if you want any other information.

Thanks for this very useful plugin 👍 .

**Comment by EddyVerbruggen** [comment]
Thank you for your bug report and analysis. I've added a better check for this case and will release it with versiosn 4.0.4.
