### ISSUE TITLE
Solved : No background notifications, if APP was removed from task manager // version 4.0.3 & 3.12.0

### ISSUE THREAD

**Issue by Lacos247** [EddyVerbruggen/nativescript-plugin-firebase#422]
Hi all,

i have an issue with background push notification. 
The Initialization is done within the AfterViewInit for the first view. 

Pushes are delivered to the function "messageReceivedCallback", if the app is in the foreground and if the app is in background (available in the task manager). If I remove the app from the task manager, no push notifications are delivered. 

Has anyone experienced the same issue on Android or has some suggestions to solve this issues? 

Tested Plugin-Versions: 4.0.3 , 3.12.0

BR,
Lacos

**Comment by derFaizio** [comment]
Isn't it an expected behavior? If you kill the app via task manager, it is no longer running in background mode and cannot process the callbacks.

**Comment by Lacos247** [comment]
Hi, 

thanks for your feedback. At least there should be some notification in the system tray. 
That is a common feature and normal for serval apps that I use. 

BR,
Lacos

**Comment by Lacos247** [comment]
Is no one experiencing the same problems?

**Comment by Lacos247** [comment]
@EddyVerbruggen 
do you habe some hints regarding this issue? Our app depends on background push-notifications (if the app was killed from task-manager, too). 

BR,
Lacos

**Comment by Lacos247** [comment]
Problem was solved. The key was to send the "notfication"-block (additional to the data payload) within the JSON, too. If the App was killed from task manager, the message will be shown in the system tray. The app will not be woken up till the user clicks this message. If the user clicks the message, you can do your stuff with your data payload (show a dialog, for example).

BR,
Lacos

**Comment by tdhman** [comment]
@Lacos247 : Hello, I have encountered the same problem. Could you give the detail of the notification payload that can resolve this issue ?
Thanks a lot.

**Comment by SergioZhydecky** [comment]
I have just also encountered that problem. NativeScript6, Angular8,  nativescript firebase plugin [](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/NON_FIREBASE_MESSAGING.md)

**Comment by rohanrunloyal** [comment]
I have just also encountered that problem. NativeScript6, Angular9, nativescript firebase plugin
Works fine when the app is in background or foreground BUT
not getting notifications when app is killed..please help 
@tdhman @Lacos247 @EddyVerbruggen 

below is the body im using for triggering push notification

```
{
"to" : "<token>",
    "notification":{
      "title":"Portugal vs. Denmark",
      "body":"great match!"
    },    
    "data":{
      "title":"Portugal vs. Denmark",
      "body":"great match!"
    }
}
```

**Comment by tdhman** [comment]
@rohanrunloyal Hello,
I ended up using the iOS APN "alert" push type notification for this issue. You can look up to configure an alert notification with `apns-push-type` header.
