### ISSUE TITLE
Analytics not working on Android

### ISSUE THREAD

**Issue by johnnyzen** [EddyVerbruggen/nativescript-plugin-firebase#429]
The plugin init ok and when I send a event, it seems to send ok.

But nothing is appearing on console, even waiting 24 hours.

Any ideas?

**Comment by johnnyzen** [comment]
This can be closed as events came through (after about 40 hours) So prepare to wait!

**Comment by carrbrpoa** [comment]
@johnnyzen even with Analytics/DebugView?
