### ISSUE TITLE
Document uploading?

### ISSUE THREAD

**Issue by jlooper** [EddyVerbruggen/nativescript-plugin-firebase#43]
would it be possible to extend this plugin to support uploading larger documents, like music files? Asking for a friend 👯

**Comment by EddyVerbruggen** [comment]
Hi Jen, can you ask your friend if (s)he refers to the [Storage API](https://firebase.google.com/docs/storage/)?

**Comment by jlooper** [comment]
Yep, that's the one!! I guess we have to use Google Storage. :) thanks!

**Comment by EddyVerbruggen** [comment]
Yes, Firebase is supposed to use that underneath but you can interact with that through this plugin once I've added the required methods to store/retrieve files. But first I'm working on extending the Auth capabilities since that would also benefit storage access.

**Comment by EddyVerbruggen** [comment]
Look what the iOS demo app just uploaded through the Firebase plugin!

Will land in the repo later this week, also for Android, including a download function.

<img width="960" alt="screen shot 2016-07-05 at 21 34 16" src="https://cloud.githubusercontent.com/assets/1426370/16597282/595a9e26-42f8-11e6-9981-541f060ea454.png">

**Comment by jlooper** [comment]
👏🏻👏🏻👏🏻👏🏻👏🏻❤️❤️❤️🔥🔥🔥🎉🎉🎉

**Comment by EddyVerbruggen** [comment]
Aaaaaand it's live - grab 3.4.0 while it's hot. [Storage doc here](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/STORAGE.md).

I'm also maintaining a [changelog](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/CHANGELOG.md) now.

Btw, blow away your platform folders since the Firebase SDK's have been bumped again so we include the latest features and fixes.

**Comment by jlooper** [comment]
Yay!!! One thing I also find helpful is to do a simulator refresh on iOS to ensure everything is installed, maybe add this to the readme?

**Comment by jlooper** [comment]
@EddyVerbruggen I'm encountering a persistent error when updating my current app to this version - even without tinkering with the Podfile. I remove every folder except /app and do a fresh plugin install, but having issues with this new SDK, any ideas?

[!] Unable to satisfy the following requirements:

- `Firebase/Auth (~> 3.3)` required by `Podfile`

**Comment by jlooper** [comment]
@EddyVerbruggen closed and referencing the problem I had here https://github.com/EddyVerbruggen/nativescript-plugin-firebase-demo/issues/1

**Comment by jlooper** [comment]
The storage upload is working extremely well! Is there a way to get a list of all the files in a particular storage bucket? :) thanks!

**Comment by EddyVerbruggen** [comment]
@jlooper That would be a really great feature but the SDK doesn't seem to support it. [See fi the iOS docs](https://firebase.google.com/docs/storage/ios/start).

A good alternative may be the accepted answer [here](http://stackoverflow.com/questions/37335102/how-to-get-an-array-with-all-pictures).
