### ISSUE TITLE
Can we set screenName?

### ISSUE THREAD

**Issue by johnnyzen** [EddyVerbruggen/nativescript-plugin-firebase#430]
On Android analytics, the screen is showing as NativescriptActivity...

Is there a way to set the screen name as in https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.html#setCurrentScreen(android.app.Activity, java.lang.String, java.lang.String)

Best

**Comment by EddyVerbruggen** [comment]
Great idea. Available in 4.0.4.

**Comment by johnnyzen** [comment]
Awesome mate. Thanks a million 👍
