### ISSUE TITLE
Can't deploy to AppStore anymore

### ISSUE THREAD

**Issue by jeremypele** [EddyVerbruggen/nativescript-plugin-firebase#435]
Hello,

just upgraded to the new version this morning (entitlements fix) and now I got an error message anytime I want to publish to the AppStore

```
1 package(s) were not uploaded because they had problems:
/var/folders/h5/xh1f3yy150zd7lwsxwl5g8gr0000gn/T/itms-117617-99021-gkbwj.ko8fv9rudi/mybundle.itmsp - Error Messages:
  ERROR ITMS-90045: "Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, key 'com.apple.keystore.device' in 'Payload/mobileapp.app/mobileapp' is not supported."
  ERROR ITMS-90045: "Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, key 'com.apple.keystore.access-keychain-keys' in 'Payload/mobileapp.app/mobileapp' is not supported."
```

**Comment by EddyVerbruggen** [comment]
Hmm, did you Google a bit to find a solution?

Perhaps @RobertGardner has an idea as those are the keys he used to fix #420. I'm wondering if he tried submitting an app to the appstore.

**Comment by jeremypele** [comment]
Yep, sorry @EddyVerbruggen I should have closed it.

The entitlements need to be signed with the right certificates, and it's done through Xcode (if anyone comes to this issue too)

**Comment by EddyVerbruggen** [comment]
No worries! Thanks for your comment 👍
