### ISSUE TITLE
The phone verification prompt doesnt go away even after login, if the app has detected the incoming sms.

### ISSUE THREAD

**Issue by sarkar4540** [EddyVerbruggen/nativescript-plugin-firebase#436]
I am using phone verification for user. If the app detects the verification sms, the user with the phone number gets logged in but, the verification prompt doesnt go away.

**Comment by EddyVerbruggen** [comment]
I'm not sure what you mean. Can't the user dismiss the popup? A little video may help.

**Comment by sarkar4540** [comment]
Sorry for the delay in response. That issue was created by an alert which occurs just when the app detects that the user has logged in. After putting the alert in a different component and thus letting it happen after the logging in loading popup has been closed, now the issue has resolved.

Regards.
