### ISSUE TITLE
createUser fails

### ISSUE THREAD

**Issue by cescoferraro** [EddyVerbruggen/nativescript-plugin-firebase#44]
I am initializing the firebase instance  like this. I get "Firebase is ready!". So I suppose, it is all good.

```

  ngOnInit() {
    console.log("sdfdsf");

    firebase.init({
      url: 'https://COOLDBURL.firebaseio.com/',
      persist: true
    }).then(
      (result)=> {
        dialogs.alert({
          title: "Firebase is ready",
          okButtonText: "Merci!"
        });
      },
      (error) => {
        console.log("firebase.init error: " + error);
      }
    );


  }
```

this works

```
  firebase(){
    firebase.setValue(
      '/companies',
      {'foo':'bar'}
    );

    // to store an array of JSON objects
    firebase.setValue(
      '/companies',
      [
        {name: 'Telerik', country: 'Bulgaria'},
        {name: 'Google', country: 'USA'}
      ]
    );
  }
```

this does not work
```
  firebase(){
    firebase.createUser({
      email: 'eddyverbruggen@gmail.com',
      password: 'firebase'
    }).then(
      function (result) {
        dialogs.alert({
          title: "User created",
          message: "userid: " + result.key,
          okButtonText: "Nice!"
        })
      },
      function (errorMessage) {
        dialogs.alert({
          title: "No user created",
          message: errorMessage,
          okButtonText: "OK, got it"
        })
      }
    )
  }
```

**Comment by EddyVerbruggen** [comment]
Did you enable email/password authentication in your Firebase console?

**Comment by cescoferraro** [comment]
![fire](https://cloud.githubusercontent.com/assets/6259987/15872294/04f3bd84-2ccf-11e6-971c-cc4565db2962.png)
![firebase](https://cloud.githubusercontent.com/assets/6259987/15872295/04fa8f38-2ccf-11e6-8bbb-b27bdfeb8f8d.png)

**Comment by cescoferraro** [comment]
@EddyVerbruggen its my first time using this new firebase console. But it seems activated

**Comment by EddyVerbruggen** [comment]
It does indeed - what's the `errorMessage` in the popup you see after `createUser` fails?

**Comment by cescoferraro** [comment]
![firebase](https://cloud.githubusercontent.com/assets/6259987/15915556/9d3b123a-2dc0-11e6-9fb8-1cd10091c775.png)

**Comment by shripalsoni04** [comment]
I was also getting the same error. In my case the issue was I was entering password as  "test", and due to that firebase was returning FirebaseAuthWeakPasswordException (firebase excepts at-least 6 character password.)

Similarly firebase will also throw an exception, if email is malformed or user with the email is already exists.

You can check the proper error by doing below changes in `firebase.android.js` file.

Inside `createUser` method, instead of returning message **Creating a user failed**, we can send message like **Creating a user failed + task.getException().getReason()** as shown below.

```javascript
var onCompleteListener = new com.google.android.gms.tasks.OnCompleteListener({
          onComplete: function (task) {
            if (!task.isSuccessful() && task.getException()) {
              reject("Creating a user failed " + task.getException().getReason());
            } else {
              // the AuthStateListener.onAuthStateChanged callback will resolve the promise
            }
          }
});
```
It will be great if we can accommodate this change in the plugin. So it will be very useful to other users also.

**Comment by EddyVerbruggen** [comment]
Thanks, added something similar in my current dev version, will land in the next release.

**Comment by cescoferraro** [comment]
Why closing this? Firebase has 8 letters. Why would that happen for me? @EddyVerbruggen

**Comment by EddyVerbruggen** [comment]
Better to ask the creator of the SDK - if they think 'Firebase' is not a strong password for a Firebase user then that's on them, right? This issue was about exposing the error to the plugin dev which will be done in the next release.

**Comment by cescoferraro** [comment]
@EddyVerbruggen yeah! makes sense. thanks

**Comment by NathanWalker** [comment]
@cescoferraro did you ever get past this by changing password to something stronger?
I'm encountering same thing with a password that is def more than 6 characters and should be consider *strong*... What ended up working for you. I still see this error when trying to use `createUser`:
```
Error Domain=FIRAuthErrorDomain Code=17999 "An internal error has occurred, print and inspect the error details for more information." UserInfo={error_name=ERROR_INTERNAL_ERROR, NSUnderlyingError=0x7e62b130 {Error Domain=FIRAuthInternalErrorDomain Code=2 "(null)"}, NSLocalizedDescription=An internal error has occurred, print and inspect the error details for more information.}
```

**Comment by NathanWalker** [comment]
Nvm, it all sudden started working, so strange. Ok all good here 👍
