### ISSUE TITLE
Add Facebook authentication

### ISSUE THREAD

**Issue by EddyVerbruggen** [EddyVerbruggen/nativescript-plugin-firebase#45]
Currently working on the iOS implementation. It's not trivial but I will pull through!

**Comment by EddyVerbruggen** [comment]
Getting somewhere! Linked the Facebook account of a previous email-login user:

<img width="587" alt="screen shot 2016-06-07 at 23 39 32" src="https://cloud.githubusercontent.com/assets/1426370/15875619/2a7b9380-2d09-11e6-9c82-88c9e0e64d7b.png">

**Comment by EddyVerbruggen** [comment]
iOS is working fine with the latest release (check the readme for details). Android has build issues mostlt - YMMV. Keeping this issue open to revisit that with a future Firebase SDK release.

**Comment by yogeshwar607** [comment]
getting following error : firebase.js:535:18: Error in firebase.login: ReferenceError: Can't find variable: FIRAuth
<img width="1056" alt="screen shot 2016-06-29 at 2 54 14 am" src="https://cloud.githubusercontent.com/assets/10059011/16432916/29196b1e-3da5-11e6-8e76-ed26ea82e716.png">


Note: tns --version
2.0.1

**Comment by t-moe** [comment]
It seems I got Facebook login working on Android. I'll open a MR today or tomorrow.

**Comment by EddyVerbruggen** [comment]
@t-moe Cool! Are you building on what's already in the repo?
