### ISSUE TITLE
Reconfigure doesn't work

### ISSUE THREAD

**Issue by YonatanKra** [EddyVerbruggen/nativescript-plugin-firebase#453]
In the docs you mention: 
```
You can reconfigure the plugin by going to the `node_modules/nativescript-plugin-firebase` and running `npm run config`.
```
When I first installed the plugin, I chose to use facebook login.
It gives an error that I need a facebook app id.  
Now I want to disable facebook login, so I went the config file and set facebook login to `false`.
I ran `npm run setup` in the `node-modules/nativescript-plugin-firebase` dir.
Re-ran `tns run android`.
Still got the facebook app id error.
Is this a bug? Or am I missing something?

**Comment by EddyVerbruggen** [comment]
Reconfiguring is simply updating a json file that's being used when the plugin is installed.

You'll need to do `tns platform remove android && tns platform add android` so the Facebook library is removed from the Android build.

**Comment by YonatanKra** [comment]
Thanks!
Might want to add this to the docs to clarify.
