### ISSUE TITLE
Turn off push notifications and check if user has push notifications enabled

### ISSUE THREAD

**Issue by mikelinden1** [EddyVerbruggen/nativescript-plugin-firebase#456]
Is there a way turn off push notifications once a user has turned them on? Also, is it possible to check wether or not a user has enabled push notifications?

**Comment by EddyVerbruggen** [comment]
I don't think we have a deregistration function for push notifications yet. Sounds very useful! And the other one as well.

**Comment by mikelinden1** [comment]
@EddyVerbruggen How about if a user declines when the "This app wants to send notifications" dialog? Can that be detected?

**Comment by EddyVerbruggen** [comment]
Yes, but it's not exposed by the plugin. You can do it in your app though - Google it and add that to your app.. or wait until this plugin exposes a function. Before you ask: I have no idea when.

**Comment by mikelinden1** [comment]
Update for those interested: I was able to check if a user has opted into notifications but it was relatively useless since I can't see a way to re-run the enrollment process for push notifications if the user turned off notifications via the settings app or declined the auth dialog.

**Comment by EddyVerbruggen** [comment]
Exactly, that's not allowed by Apple. In case that method returns `false` you should prompt the user to open the Settings app and enable the permissions there.

**Comment by mikelinden1** [comment]
Oh ok. That makes sense. Thanks for the reply.

**Comment by TinusJ** [comment]
Anything on 'check if user has push notifications enabled' ?

**Comment by konradkluzniak** [comment]
Hi @mikelinden1 
You said: "I was able to check if a user has opted into notifications"
How did you do this ?
Thanks.

**Comment by Mixelated** [comment]
Same here. I am really interested in knowing how you did this

**Comment by Mixelated** [comment]
found the answer here: https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/1429#event-2712411869
