### ISSUE TITLE
Whats the recomended way to use firebase counter in nativescript?

### ISSUE THREAD

**Issue by ishandutta2007** [EddyVerbruggen/nativescript-plugin-firebase#458]
In JS web app I had used https://www.npmjs.com/package/firebase-counter
Is there any equivalent API being build here or plan to migrate the above node package as a separate plugin here?

**Comment by EddyVerbruggen** [comment]
Not planned. If you want it you could look at [the source code of that package](https://github.com/zrrrzzt/firebase-counter/blob/master/index.js) and try to adapt it for your app.
