### ISSUE TITLE
Messaging plugin on iOS passes a toString() version of NSConcreteNotification to onPushTokenReceivedCallback

### ISSUE THREAD

**Issue by briandilley** [EddyVerbruggen/nativescript-plugin-firebase#460]
I get the following string passed to `onPushTokenReceivedCallback` on ios:

`NSConcreteNotification 0x174442790 {name = com.firebase.iid.notif.refresh-token; object = XXXX-token-here-XXXX}`

I'm using a regex to pull the token out, but i'd like to use something more secure/reliable than that.

**Comment by dbenninger** [comment]
I have noticed that the first time it is a NSConcreteNotification object, the second time it is a string. 

Before the second time, this is logged: 
CONSOLE LOG file:///app/tns_modules/nativescript-plugin-firebase/firebase.js:2175:16: >> fcmToken refreshed: c....

**Comment by bozhidarc** [comment]
I have the same problem. The interesting think is that this was working a couple of months ago.
My phone is with iOS 11.00 .

**Comment by bozhidarc** [comment]
After some debugging i found out that `onPushTokenReceivedCallback()` is called twice.
The first time it is called from `firebase._onTokenRefreshNotification()` which is a callback of `'com.firebase.iid.notif.refresh-token'` event and it passes a `NSNotification` instance, and the second time it is called from `FIRMessagingDelegateImpl.messagingDidRefreshRegistrationToken()` and there it passes the token as string.

I'm no sure why this is happening, I'm not so familiar with the iOS infrastructure.
As a temporary work around which is more reliable then regex is to check of it's an object or string and handle both cases.
