### ISSUE TITLE
When I call firebase.createUser nothing happens!

### ISSUE THREAD

**Issue by mutazmq** [EddyVerbruggen/nativescript-plugin-firebase#463]
I'm calling the below code but nothing is happening, no result or error message is returned. It seems the promise is not being fulfilled. There is also no user created in Firebase. And I have enabled "Email/Password" in the "Sign-in method" tab.

```
    firebase.createUser({
            email: 'eddyverbruggen@gmail.com',
            password: 'firebase'
          }).then(
              function (result) {
                console.log("Created");
                dialogs.alert({
                  title: "User created",
                  message: "userid: " + result.key,
                  okButtonText: "Nice!"
                })
              },
              function (errorMessage) {
                console.log("Error");
                dialogs.alert({
                  title: "No user created",
                  message: errorMessage,
                  okButtonText: "OK, got it"
                })
              
```

And this is my package.json

```
    {
      "description": "NativeScript Application",
      "license": "SEE LICENSE IN <your-license-filename>",
      "readme": "NativeScript Application",
      "repository": "<fill-your-repository-here>",
      "nativescript": {
        "id": "org.nativescript.helloWorld",
        "tns-android": {
          "version": "3.1.1"
        },
        "tns-ios": {
          "version": "3.1.0"
        }
      },
      "dependencies": {
        "@angular/animations": "~4.1.0",
        "@angular/common": "~4.1.0",
        "@angular/compiler": "~4.1.0",
        "@angular/core": "~4.1.0",
        "@angular/forms": "~4.1.0",
        "@angular/http": "~4.1.0",
        "@angular/platform-browser": "~4.1.0",
        "@angular/router": "~4.1.0",
        "font-awesome": "^4.7.0",
        "nativescript-angular": "~3.1.0",
        "nativescript-camera": "^3.0.1",
        "nativescript-couchbase": "^1.0.18",
        "nativescript-ngx-fonticon": "^2.2.3",
        "nativescript-plugin-firebase": "^4.0.5",
        "nativescript-telerik-ui": "^3.0.4",
        "nativescript-theme-core": "~1.0.2",
        "reflect-metadata": "~0.1.8",
        "rxjs": "^5.4.2",
        "tns-core-modules": "^3.1.1",
        "zone.js": "~0.8.2"
      },
      "devDependencies": {
        "babel-traverse": "6.25.0",
        "babel-types": "6.25.0",
        "babylon": "6.17.4",
        "lazy": "1.0.11",
        "nativescript-dev-typescript": "~0.5.0",
        "typescript": "~2.2.1"
      }
    }

```

**Comment by mutazmq** [comment]
This is Android. No, just on the emulator API 26

**Comment by EddyVerbruggen** [comment]
Are you able to check it on a real device?

**Comment by mutazmq** [comment]
I don't have an Android device. And I'm having issues running the app on my iPhone :(
I also tried on ios simulator and the same problem.

Is this a common problem on simulators? What is going on? No way I can get it working on the simulator?

**Comment by EddyVerbruggen** [comment]
Sure you can, but it could be a problem with that specific emulator (missing play services for instance) and I wanted to rule that out.

If you're having trouble on iOS as well you may have a bug in your code - please [test the demo app first](https://github.com/EddyVerbruggen/nativescript-plugin-firebase-demo).

**Comment by mutazmq** [comment]
Ok thanks. I will test it right now. But where the bug in my code will come from? I just copied and pasted your code as is inside a (tap) listener for a button. It is totally isolated from my code.

**Comment by EddyVerbruggen** [comment]
I have no idea.

**Comment by mutazmq** [comment]
The demo app build failed as below:

```
* Where:
Build file '/Users/mutaz/Dev_Projects/nativescript-plugin-firebase-demo/Firebase/platforms/android/build-tools/android-static-binding-generator/build.gradle' line: 251

* What went wrong:
Execution failed for task ':asbg:generateBindings'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
```

**Comment by mutazmq** [comment]
Can you please help me troubleshoot the issue in my app? It seems the below line in `firebase.android.js` is not calling the `onCompleteListener`

`firebaseAuth.createUserWithEmailAndPassword(arg.email, arg.password).addOnCompleteListener(onCompleteListener);`

Note: There is no build errors and Firebase is being initialized successfully in `main.ts`

Thank you

**Comment by mutazmq** [comment]
I downloaded [Giftler](https://github.com/jlooper/giftler) app for Jen Looper and the same thing is happening there.. no response :(

**Comment by jlooper** [comment]
I haven't seen this - you did enable email auth in the backend, right? Admittedly giftler probably needs updating... maybe run Eddy's demo code to see if things work as expected?

**Comment by mutazmq** [comment]
Hello Jen, I got an issue when I ran Eddy's demo app (reported above). 
I could run your app finally after installing `nativescript-telerik-ui": "^3.0.4"` and it worked fine. But I got the same issue.
Yes email auth is enabled in Firebase backend.

**Comment by mutazmq** [comment]
@jlooper @EddyVerbruggen Thanks for the support. It works fine on a real device. I tried everything online to get the simulator to work with no success. You might want to add it as a note for other developers that if they don't get any response from `firebase.createUser` to try on a real device. Thanks.

**Comment by EddyVerbruggen** [comment]
Fair enough - doc updated, thx!

**Comment by ThomCM** [comment]
Hi @EddyVerbruggen I'm having the same issue:

`createUserWithEmailAndPassword()` function is working.
`createUser()` function is not working: no response at all.
Repo: [](https://github.com/ThomCM/khrapp)

Testing on a Samsung Galaxy S8.

```
auth.createUserWithEmailAndPassword('test001@gmail.com', 'pass123456')
        .then(function(user) {
          // user signed in
          self.form_response = 'user successfully created.';
          console.log(user);
          self.createUserDocument(user);
        }).catch(function(error) {
          // Handle Errors here.
          self.form_response = error;
          console.log(error);
          var errorCode = error.code;
          console.log(errorCode);
        });

auth.createUser({
        email: 'test001@gmail.com', password: 'pass123456'
      })
      .then(function(user) {
        // user signed in
        console.log('success');
        self.form_response = 'user successfully created.';
        console.log(user);
        self.createUserDocument(user);
      }).catch(function(error) {
        // Handle Errors here.
        self.form_response = error;
        console.log(error);
        var errorCode = error.code;
        console.log(errorCode);
      });
```

**Comment by ThomCM** [comment]
@EddyVerbruggen 

OK so what I've been doing is using the auth directory instead of the root.

```
var firebase = require('nativescript-plugin-firebase');
var firebaseApp =  require('nativescript-plugin-firebase/app');
var firebaseAppAuth = firebaseApp.auth();
```

I got into the habbit of doing this whilst working with Firestore. Not sure why but it has been working for me. As I mentioned, `firebaseAppAuth.createUserWithEmailAndPassword()` is working, `firebaseAppAuth.createUser()` is not.

So, firebase.createUser() is working for me now but I'm essentially having the same issue as it doesn't seem to accept any additional parameters beyond email & password.

Finally, I think that the [documentation for updateProfile()](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/AUTHENTICATION.md#updating-a-profile) is missing the user UID which should be the first argument before the data object as when trying exactly as described it does nothing. When trying the following... 

```
firebase.updateProfile(user_uid,{
      displayName: 'Eddy Verbruggen',
      photoURL: 'http://provider.com/profiles/eddyverbruggen.png'
    }).then(
        function () {
          // called when update profile was successful
        },
        function (errorMessage) {
          console.log(errorMessage);
        }
    );
```

.... it returns _Updating a profile requires a displayName and / or a photoURL argument_

**Comment by ThomCM** [comment]
In firebase.android.js:

```
if (!arg.displayName && !arg.photoURL) {
                reject("Updating a profile requires a displayName and / or a photoURL argument");
            }
```

should be:

```
if (!arg.displayName || !arg.photoURL) {
                reject("Updating a profile requires a displayName or a photoURL argument");
            }

```

Although in dreamland neither are required imho.

I did clone the plugin, create a new branch and try to push but it says access is denied. I've not contributed to a public repo previously.

**Comment by EddyVerbruggen** [comment]
@ThomCM you can create a so-called Pull Request (PR). First fork the repo and clone it locally then optionally change to a different branch and make, commit, push the changes. Once that’s done go to the Github repo and press the ‘pull request’ button. Thanks!

**Comment by AceTheFace** [comment]
Seems to work now. I was able to register a new user using 'createUserWithEmailAndPassword()' within the emulator.
