### ISSUE TITLE
Authentication works only in watch mode

### ISSUE THREAD

**Issue by b4rtt** [EddyVerbruggen/nativescript-plugin-firebase#470]
Hey, @eddyverbruggen
I have little problem with authentication by google. It´s workin´ only in watch mode (on real device). When I try to publish app or run it on emulator, login fails with exception. But when I run it on real iPhone 6s (tns run ios) it´s working properly. 

My repository is here. 
https://github.com/b4rtt/PiratiGo

Do you know where should be the problem?

Thank you so much for your time

**Comment by EddyVerbruggen** [comment]
What's watch mode?

And can you share what the problem and exception actually is?

**Comment by b4rtt** [comment]
@eddyverbruggen 
Sorry I call watch mode "tns run ios" with real iPhone connected to Mac.

I can't read exception because it happens only in published APK and in iOS simulator.
