### ISSUE TITLE
Build failed with IOS

### ISSUE THREAD

**Issue by p-3** [EddyVerbruggen/nativescript-plugin-firebase#472]
I am getting following error as soon I add firebase plugin to my project on iOS. (Works with Android)

d: warning: directory not found for option '-F/Users/p-3/Library/Developer/Xcode/DerivedData/dialog-dqtrjcchmcudkggjvbwudxgblacx/Build/Products/Debug-iphonesimulator/GTMOAuth2'
ld: warning: directory not found for option '-F/Users/p-3/Library/Developer/Xcode/DerivedData/dialog-dqtrjcchmcudkggjvbwudxgblacx/Build/Products/Debug-iphonesimulator/GTMSessionFetcher'
ld: warning: directory not found for option '-F/Users/p-3/Library/Developer/Xcode/DerivedData/dialog-dqtrjcchmcudkggjvbwudxgblacx/Build/Products/Debug-iphonesimulator/GoogleAPIClientForREST'
ld: warning: directory not found for option '-F/Users/p-3/Library/Developer/Xcode/DerivedData/dialog-dqtrjcchmcudkggjvbwudxgblacx/Build/Products/Debug-iphonesimulator/GoogleToolboxForMac'
ld: warning: directory not found for option '-F/Users/p-3/Library/Developer/Xcode/DerivedData/dialog-dqtrjcchmcudkggjvbwudxgblacx/Build/Products/Debug-iphonesimulator/Protobuf'
ld: warning: directory not found for option '-F/Users/p-3/Library/Developer/Xcode/DerivedData/dialog-dqtrjcchmcudkggjvbwudxgblacx/Build/Products/Debug-iphonesimulator/SAMKeychain'
ld: warning: directory not found for option '-F/Users/p-3/Library/Developer/Xcode/DerivedData/dialog-dqtrjcchmcudkggjvbwudxgblacx/Build/Products/Debug-iphonesimulator/nanopb'
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_GINDeviceInfoBase", referenced from:
      _OBJC_CLASS_$_GINInviteDeviceInfo in FirebaseInvites(GINInviteDeviceInfo_bc6638c725309e299695a2031b85f7ad.o)
  "_OBJC_METACLASS_$_GINDeviceInfoBase", referenced from:
      _OBJC_METACLASS_$_GINInviteDeviceInfo in FirebaseInvites(GINInviteDeviceInfo_bc6638c725309e299695a2031b85f7ad.o)
  "_OBJC_METACLASS_$_GPPSpamSignal", referenced from:
      _OBJC_METACLASS_$_GINInviteSpamSignal in FirebaseInvites(GINInviteSpamSignal_3f71bceb62b83773b12801c72b354f98.o)
  "_OBJC_CLASS_$_GPPSpamSignal", referenced from:
      _OBJC_CLASS_$_GINInviteSpamSignal in FirebaseInvites(GINInviteSpamSignal_3f71bceb62b83773b12801c72b354f98.o)
  "_OBJC_CLASS_$_GINDurableDeepLinkService", referenced from:
      objc-class-ref in FirebaseInvites(GINInvite_a4cd829f88815c40445a7f8e1c1c97de.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

Any ideas why I am getting this?

**Comment by EddyVerbruggen** [comment]
I have not idea..

**Comment by BMwanza** [comment]
Were you ever able to solve this? I am getting a similar error
