### ISSUE TITLE
Invites on Android: AppInviteApi has been deprecated

### ISSUE THREAD

**Issue by sserdyuk** [EddyVerbruggen/nativescript-plugin-firebase#478]
AppInviteApi has been deprecated. Please consider upgrading to current API.
https://developers.google.com/android/reference/com/google/android/gms/appinvite/AppInviteApi

**Comment by EddyVerbruggen** [comment]
Yeah you've probably seen [this as well](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/6b9c4283eeaa9121c412e7ee292452adb5bf94fd/firebase.android.js#L2108) - I've pushed an update that fixes the TODO mentioned.

If I push a new version to npm, can you perhaps test it?

**Comment by sserdyuk** [comment]
@EddyVerbruggen Yes, I can test it, but my test scenario is not app-to-app sharing but rather web-to-app conversion, where the website generates a FB dynamic link, and the app gets context upon installation. It doesn't work with the current version of plugin, but it does with the getDynamicLink() API that @dbeulen  implemented in his fork https://github.com/dbeulen/nativescript-plugin-firebase, so, I should be able to test your implementation as well.

**Comment by EddyVerbruggen** [comment]
Do me a favor and mention that in the PR. Finding time to review and test PRs is often the only reason those don't get merged ;)

**Comment by sserdyuk** [comment]
@EddyVerbruggen Hey, it wasn't me :)

**Comment by EddyVerbruggen** [comment]
LOL - no I meant if you test someones PR give it a thumbs up when it works. Just a little tip, I value your contribution to this topic very much already!
