### ISSUE TITLE
Is anybody using the invites part? I can't get the deeplink or invitation id.

### ISSUE THREAD

**Issue by sserdyuk** [EddyVerbruggen/nativescript-plugin-firebase#479]
I have been trying to get it to work a few days by now, and still nothing. Please share your working setup here.

Per instructions, the following code is used and while the promise gets resolved, no data is actually passed in as seen below.

I have tried it with registering intent filter in the manifest (per current Android docs) and without, the result is the same. I am using an emulator for testing. The process I follow is: (1) uninstall the app, (2) launch the dynamic link generated in FB console, (3) run 'tns run android' to install and start the app. 

```
    firebase.invites.getInvitation().then(
        function (result) { // GetInvitationResult
          console.log("deeplink: " + result.deeplink + ", invitationId: " + result.invitationId);
        },
        function (error) {
          console.log("getInvitation error: " + error);
        }
    );
```
```
JS: getInvitation:onResult: true
JS: deeplink: undefined, invitationId: 
```
```
$ tns info
All NativeScript components versions information
┌──────────────────┬─────────────────┬────────────────┬─────────────┐
│ Component        │ Current version │ Latest version │ Information │
│ nativescript     │ 3.1.3           │ 3.1.3          │ Up to date  │
│ tns-core-modules │ 3.1.1           │ 3.1.1          │ Up to date  │
│ tns-android      │ 3.1.1           │ 3.1.1          │ Up to date  │
│ tns-ios          │ 3.1.0           │ 3.1.0          │ Up to date  │
└──────────────────┴─────────────────┴────────────────┴─────────────┘
```

**Comment by EddyVerbruggen** [comment]
I don't think getting the invite works well - I've focused on sending invites. Getting the invite is only relevant for directing the user to some deeplink in your app, right?

**Comment by sserdyuk** [comment]
@EddyVerbruggen The goal is to use FB dynamic link to convert web user to an app with continuous experience where context is passed to the app and survives the trip to the app store if the app needs to be installed.

**Comment by EddyVerbruggen** [comment]
What kind of context? Just looking for real-life examples here so I can wrap my head around it..

**Comment by sserdyuk** [comment]
@EddyVerbruggen It's one of the use cases shown https://firebase.google.com/products/dynamic-links/
Customer, possibly already registered, is taken to the app store to install the app, and the app opens with user's information already known, right on the spot where the user left the website, hence the "context" is passed to the app from the website through the dynamic link.

According to https://firebase.google.com/docs/invites/, the invites system uses dynamic links internally.

![image](https://user-images.githubusercontent.com/395998/30218017-db5344c0-9485-11e7-84d4-b08a2cb54d42.png)
