### ISSUE TITLE
Can't call equalTo() and startAt() combined

### ISSUE THREAD

**Issue by chiquitto** [EddyVerbruggen/nativescript-plugin-firebase#481]
Error in firebase.query: Error: java.lang.IllegalArgumentException: Can't call equalTo() and startAt() combined.

But the query is:

```
firebase.query(
  (result) => { },
  "/estabelecimentos",
  {
    singleEvent: true,
    orderBy: {
      type: firebase.QueryOrderByType.KEY
    },
    ranges: [
      {
        type: firebase.QueryRangeType.EQUAL_TO,
        value: 0,
      },
      {
          type: firebase.QueryRangeType.EQUAL_TO,
          value: 1,
      }
    ]
  }
)
```

Am I doing something wrong?

**Comment by EddyVerbruggen** [comment]
That message is from Firebase's Android SDK itself, not this plugin - if you Google it you'll find a lot of similar messages on SO.

My guess is you need to change those 2 `EQUAL_TO`'s to `START_AT` and `END_AT` respectively.
