### ISSUE TITLE
Multiple environments

### ISSUE THREAD

**Issue by Dashue** [EddyVerbruggen/nativescript-plugin-firebase#490]
I'd like to have two different databases when running in dev vs prod.
How would I conditionally load dev or prod google-services.json the simplest?

I feel this is an area where little is documented and I appreciate all help!
Thanks!

**Comment by dminine** [comment]
Is there a solution?

**Comment by EddyVerbruggen** [comment]
It highly depends on your build setup how you would swap out one file for the other. There are so many ways depending on that answer. I would probably create a script that's triggered by a script in package.json. But it could be gulp, or probably even a NativeScript hook.

**Comment by Dashue** [comment]
For anyone coming back, I found a way to do it and it's basically by setting up two different apps
Have three different json google-services files.
google-services.dev.json
google-services.json (the one being used when building)
google-services.prod.json

Package names
com.readersguide.dev
com.readersguide.android

When I do a release I change the following
- Change package name in app.gradle to com.readersguide.android
- Change google-services.json to prod version, by copying the content from google-services.prod.json
- Change id in package.json to com.readersguide.android
- Possibly delete platforms folder before build

I only do android builds, so there's probably additional steps required for ios.
