### ISSUE TITLE
Facebook SDK

### ISSUE THREAD

**Issue by nikis** [EddyVerbruggen/nativescript-plugin-firebase#494]
I`am using Facebook login with "nativescript-plugin-firebase": "^4.0.5". When i install my app on **real ios device** i got error: "Facebook SDK is not installed - see Podfile". Its very strange because on ios simulator everything works fine.

```
    firebase.login({
        type: firebase.LoginType.FACEBOOK,
        facebookOptions: {
            scope: ['email']
        }
    }).then(result=>{
        //Success
    }, err=>{
        //Error - "Facebook SDK is not installed - see Podfile"
    });
````

This is my pod file
```
 pod 'SCLAlertView-Objective-C' 
 pod 'MBProgressHUD'
 
 pod 'Firebase', '~> 4.1.1'
 pod 'Firebase/Database'
 pod 'Firebase/Auth'
 
 # Uncomment if you want to enable Remote Config
 #pod 'Firebase/RemoteConfig'
 
 # Uncomment if you want to enable Crash Reporting
 #pod 'Firebase/Crash'
 
 # Uncomment if you want to enable FCM (Firebase Cloud Messaging)
 pod 'Firebase/Messaging'
 
 # Uncomment if you want to enable Firebase Storage
 #pod 'Firebase/Storage'
 
 # Uncomment if you want to enable AdMob
 #pod 'Firebase/AdMob'
 
 # Uncomment if you want to enable Invites and/or Dynamic Links
 #pod 'Firebase/Invites'
 
 # Uncomment if you want to enable Facebook Authentication
 pod 'FBSDKCoreKit', '~> 4.14.0'
 pod 'FBSDKLoginKit', '~> 4.14.0'
 
 # Uncomment if you want to enable Google Authentication
 #pod 'GoogleSignIn'
 # End Podfile 

end
```

**Comment by ravidoki** [comment]
@nikis  Have you resolved this issue. I am struck with this error.
Thanks.

**Comment by nikis** [comment]
Yes, last week we fix it. 
- Update to latest Xcode
- Remove all manually downloaded and imported SDKs
- Follow install procedure and install everything with pods

**Comment by ravidoki** [comment]
Thanks. My case is different as I am working on windows machine.

**Comment by ravidoki** [comment]
@nikis, Resolved  my issue. I have done reinstalled all node modules.

Thanks for your help.

**Comment by ryanlangton** [comment]
what does "install everything with pods" mean? I've installed everything w/ `tns plugin add` and am having this error

**Comment by EddyVerbruggen** [comment]
@ryanlangton Do you have a repo I can look at? Ping me there and I'll close this issue because it's usually fixed by blowing away the platforms folder, updating cocoapods (`pod repo update`) and building again.

**Comment by EddyVerbruggen** [comment]
For others: the problem Ryan was having was not related to this plugin.
