### ISSUE TITLE
iOS background notification never show and foreground notification stop working after killing the app

### ISSUE THREAD

**Issue by henrychavez** [EddyVerbruggen/nativescript-plugin-firebase#499]
I have the latest version "nativescript-plugin-firebase": "^4.1.1".

and I never get the background notifications and the foregrounds are failing when I kill the app and reopen.

I call the init method before the application starts and the foregrounds notifications works only that first time.

Any idea of what version of the plugin I should use that works background notification and foreground?

**Comment by uzarsalan** [comment]
i have the same issue. But sometimes, i can't understand why, background notification works until second launch. I've changed code hundreds times and can't find why it happens. Tried 3.11.0, 4.0.5, 4.1.1.

**Comment by b4rtt** [comment]
Same issue here.

**Comment by TheOnlyMatt** [comment]
I am still having this same issue with the version 5.1.6

**Comment by ebiscardi** [comment]
Is this issue resolved? I have a similar issue.
Notifications work fine after installing the application, but after killing, notifications stop working.
To make tests, I send notification calling firebase API through Postman, using FCM token received calling firebase.getCurrentPushToken() method.
After notifications stop working, the response sent by firebase API is "notRegistered", even if the token is exactly the one received as current token.
