### ISSUE TITLE
Sorting / Order in a list from Firebase

### ISSUE THREAD

**Issue by jlooper** [EddyVerbruggen/nativescript-plugin-firebase#50]
TJ and I worked over our Groceries list for a while today, adding items to the array. We added an inverse time stamp to each element, hoping we could sort it so that when you add to a list, the item goes to the top. However, we don't see any logic to the way items are added, it's very strange. Sometimes they go to the top, sometimes elsewhere. We tried the various orderBy calls in the docs. Kind of strange!

https://github.com/NativeScript/sample-Groceries/blob/angular-firebase/app/shared/grocery/grocery-list.service.ts#L49-52 is our current query. We also tried 'Child' and 'Priority' but can't find a logic.

thanks!

**Comment by EddyVerbruggen** [comment]
Wait, are you saying you fixed #46 then?

**Comment by jlooper** [comment]
No, we turned out attention to making the app work great on iOS :) - let me comment the other issue

**Comment by EddyVerbruggen** [comment]
Once I figure out #46 for your app I'll take a look at this one. But it's a toughie.

**Comment by jlooper** [comment]
Just to note, the ordering is super nutty atm
![groceries](https://cloud.githubusercontent.com/assets/1450004/15975463/94f2f960-2f1b-11e6-874e-3b3ac5b26533.gif)

**Comment by EddyVerbruggen** [comment]
If I add a `console.log` statement in the query function you linked to above then I won't see it in my log so I don't think the query is executed.

Instead, in the `constructor` of the same class there's a `firebase.addValueEventListener` which _I think_ is the one actually retrieving the data here.

**Comment by jlooper** [comment]
the query is hit by the event listener when the data changes. So if you add an item, you should see that query run. It's also hit when the page first loads to retrieve the list, or any time the database data is altered. I would think that it would be more efficient for the plugin to handle the sorting on the database side, right? If it is too hard, though, we can work on client side sorting. 👍 thanks!

**Comment by EddyVerbruggen** [comment]
Hey Jen, did you try adding that log statement? Seriously, I don't think the query runs at all so sorting is never applied.

**Comment by jlooper** [comment]
ooh, I think you're right. We have changed the code to make the sync work. Debugging now. Thanks for the heads up!

**Comment by jlooper** [comment]
It has to be sorted using a pipe if you want to done client side

**Comment by codef0rmer** [comment]
@jlooper I've also faced the same problem. Sorting in firebase.query especially with `firebase.QueryLimitType.LAST` is a bit invalid. I'd to use a custom sort filter over the list again!

**Comment by prantikv** [comment]
I am unable to sort data using `singleEvent: false` is that it expected behavior? The sorting works when I use `singleEvent: true`

**Comment by JillevdW** [comment]
Issue #405 seems to be relevant here. I feel piping on the client side is a hacky work-around seeing as it'll be a major hit to performance on bigger queries.
