### ISSUE TITLE
'createUser' method returning previous user's User UID when creating a new user

### ISSUE THREAD

**Issue by mi6crazyheart** [EddyVerbruggen/nativescript-plugin-firebase#51]
@EddyVerbruggen, First of all, thanks for this nice plugin. Currently, I'm using this in one my android app & I'm having some strange behavior. 

Whenever I'm using `createUser` method for creating a new user account in response I'm getting KEY(User UID) of the just immediate user which I'd created before this. Here is my testing flow -

1. Firebase console has no user.
2. Created  USER  A. In response got user KEY of USER A. Checked with firebase console for KEY miss match. KEY is fine. No miss match found.
3. Created USER B. In response got KEY. When matching with firebase console it's showing that KEY is belonged to USER A.  
4.Created USER C. In response got KEY of USER B. Then it's going on like this.

I'd a small chat with #jacosta in NativeSscript slack channel about this. He suggested me to use `logout` method(which I'm currently not using) to log out old user & then user `createUser` method to create new user account. Although, I've not tested this one yet now but I think it's kind issue.

**Comment by Jpaagt** [comment]
The use of the logout method is not enough, I think the createUser method should not resolve with the authStateChange event, and users of the plugin should use the plugins addAuthStateListener to correctly get the current user information as stated [here](https://firebase.google.com/docs/auth/android/manage-users#get_the_currently_signed-in_user).

**Comment by mi6crazyheart** [comment]
@Jpaagt All right. I'll check this.
