### ISSUE TITLE
Facebook sign in stopped work on iOS device

### ISSUE THREAD

**Issue by d3mac123** [EddyVerbruggen/nativescript-plugin-firebase#514]
My app has more than 5 months and FB login always worked fine until I added more code today, not related to Firebase. Now, I keep getting the following message on the console:
`CONSOLE LOG file:///app/tns_modules/nativescript-plugin-firebase/firebase-common.js:177:16: Please update your code: the 'scope' property is deprecated and now expected at 'facebookOptions.scope'`

On the device, all the screens show up but I get a message
`An internal error has occurred, print and inspect the error details for more information.`

I am running FB plugin 4.1.1 with {N} 3.2.1. Any ideas?

**Comment by EddyVerbruggen** [comment]
Hi, did you try moving the `scope` to `facebookOptions.scope`?

**Comment by d3mac123** [comment]
I did not touch anything 😂 how do I so that?

**Comment by Dashue** [comment]
This is the new syntax: 
firebase.login({
      type: firebase.LoginType.FACEBOOK,
      facebookOptions: {
        scope: ['public_profile', 'email'] // optional: defaults to ['public_profile', 'email']
      }
    })

**Comment by d3mac123** [comment]
Thanks @Dashue! It worked. My code was a "bit" old :)

**Comment by Dashue** [comment]
My pleasure, enjoy :)
