### ISSUE TITLE
Error in tns build android: 'spawn gradle.bat ENOENT'

### ISSUE THREAD

**Issue by ali-hooshmand** [EddyVerbruggen/nativescript-plugin-firebase#53]
I'm able to run NativeScript simple example. However, I am getting 'spawn gradle.bat ENOENT' when I'm trying to build a project with firebase plugin where multidex is enabled. Here is my build log:

http://pastebin.com/mf6ZHVA0

This happened after I added nativescript-plugin-firebase to the project. All I did was:
"tns plugin add nativescript-plugin-firebase"
and then I added "GoogleService-Info.plist" file to platforms/android.
Then I added following lines to platforms/android/build.gradle:
in dependencies, added: "com.google.gms:google-services:3.0.0" and at the end of file "apply plugin: "com.google.gms.google-services""
Finally enabled Multidex by adding "multiDexEnabled true" in app.gradle.

Thanks!
P.S.: I asked the same question in nativescript-cli and thought it might be related to firebase plugin. That's why I'm posting it again in firebase plugin issues.

**Comment by EddyVerbruggen** [comment]
Can you provide a link to the cli issue?

**Comment by EddyVerbruggen** [comment]
FYI Manually editing the Gradle files is no longer needed in version 3.8.0.
