### ISSUE TITLE
[BUG] Reference Error with version 4.2.0

### ISSUE THREAD

**Issue by Spenstar** [EddyVerbruggen/nativescript-plugin-firebase#531]
Updated to the new TypeScript version of the plugin (nice work on your part for doing that!) and now get the following error when loading up my app:
```console
JS ERROR ReferenceError: Can't find variable: FIRInviteDelegate
```
I'm guessing this error goes along with the invites feature of the plugin. I currently don't use invites in my app, so I don't believe it's an error with my code.

When I commented out the line of code with `FIRInviteDelegate` in the plugin, I then got the following error:
```console
JS ERROR ReferenceError: Can't find variable: GADInterstitialDelegate
```
I'm guessing if I were to comment that out, the next error would be:
```console
JS ERROR ReferenceError: Can't find variable: GIDSignInDelegate
```
Hopefully this is enough information for you to track this down.

**Comment by EddyVerbruggen** [comment]
Thank you! I guess I have those files referenced [like this in the demo app](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/demo/references.d.ts), but I fully agree you should not need to do that in your own app - please copy that `references.d.ts` file as a quick workaround and I'll fix this in  4.2.1 as soon as possible.

**Comment by Spenstar** [comment]
Awesome, thanks!

**Comment by Spenstar** [comment]
Just a heads up, those reference files do not exist in both my platform directory or your plugin directory. They do however, exist in a previous version of your plugin: [here, for example](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/tree/e19caa9afa331164221b2d9adea42dabfa15222e/platforms/ios/typings)

**Comment by EddyVerbruggen** [comment]
Ah, yes, but those are still [in the repo](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/tree/master/src/platforms/ios/typings). But you can't use them when installed from npm so that's not helping you really ;)

Just to be sure: it's `firebase(.ios).js` complaining when doing `tns run ios`, right? Is there a line number involved?

**Comment by Spenstar** [comment]
Gotcha 😁 And unfortunately, there was no real context provided when the error was given. It just gave `JS ERROR ReferenceError: Can't find variable: FIRInviteDelegate` and hung on the splash screen.

Also, I manually put those files into my project and got the following typing errors. Not sure if this will be common for everyone:
```console
typings/objc!FBSDKCoreKit.d.ts(201,64): error TS2304: Cannot find name 'BFAppLinkResolving'.

typings/objc!FBSDKCoreKit.d.ts(221,42): error TS2304: Cannot find name 'BFTask'.

typings/objc!FBSDKCoreKit.d.ts(223,52): error TS2304: Cannot find name 'BFTask'.

typings/objc!FirebaseDatabase.d.ts(134,15): error TS2415: Class 'FIRDatabaseReference' incorrectly extends base class 'FIRDatabaseQuery'.
  Types of property 'description' are incompatible.
    Type '() => string' is not assignable to type 'string'.

typings/objc!FirebaseDatabase.d.ts(134,15): error TS2417: Class static side 'typeof FIRDatabaseReference' incorrectly extends base class static side 'typeof FIRDatabaseQuery'.
  Types of property 'alloc' are incompatible.
    Type '() => FIRDatabaseReference' is not assignable to type '() => FIRDatabaseQuery'.
      Type 'FIRDatabaseReference' is not assignable to type 'FIRDatabaseQuery'.
        Types of property 'description' are incompatible.
          Type '() => string' is not assignable to type 'string'.

typings/objc!FirebaseDatabase.d.ts(164,2): error TS2425: Class 'FIRDatabaseQuery' defines instance member property 'description', but extended class 'FIRDatabaseReference' defines it as instance member function.

typings/objc!GoogleSignIn.d.ts(24,23): error TS2304: Cannot find name 'GTMFetcherAuthorizationProtocol'.
```

**Comment by EddyVerbruggen** [comment]
Yeah you shouldn't need those typings files in the first place.

The rootcause is [I used to check for stuff like `GADInterstitialDelegate`](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/e19caa9afa331164221b2d9adea42dabfa15222e/firebase.ios.js#L2255) before using them. Since the demo app includes all features (and thus libraries like Invites, from Cocoapods) there's no problem in my case.

I'll re-add those checks the TS-way and publish a new version.
