### ISSUE TITLE
Nativescript Firebase app working on Android but not on iOS. Getting some warning in console while running 

### ISSUE THREAD

**Issue by SamBaqai94** [EddyVerbruggen/nativescript-plugin-firebase#533]
hello there,
My app is working perfectly fine on android but for some reason its not working on iOS. I am getting this warning in console while running on iOS.
![screen shot 2017-10-25 at 1 21 08 pm](https://user-images.githubusercontent.com/14830320/32013088-f51dfbe4-b987-11e7-835f-9459aa03b94a.png)

**Comment by EddyVerbruggen** [comment]
Those console messages are not problematic. What’s the actual problem?

**Comment by SamBaqai94** [comment]
yeah I just fixed the issue. I was having same issue as #385 and after disabling invites it worked for me

**Comment by dimitarmar** [comment]
Hi , I have disabled disabled invities , but still  my application is crashing on start if I leave the firebase.init . If I comment all is good .
