### ISSUE TITLE
routing not working on native script angular

### ISSUE THREAD

**Issue by souly1** [EddyVerbruggen/nativescript-plugin-firebase#534]
Hi, 
first let me thank you @EddyVerbruggen for the great plugin - this and all the rest (nativescript & cordova!)

I had an issue I thought the solution worth mentioning here as someone else might encounter it and have difficulties.

The symptom I've got is when calling routerExtenstions navigate (or router.navigate) nothing happens.
After making sure we're in the 'zone' (this._ngZone.run(() => {....) one could see from the logs that the navigation happens but the view doesn't update.
After attempting several solutions what eventually solved it for me was calling 'firebase.addOnMessageReceivedCallback' right after the 'firebase.init' instead of configuring the message received callback inside the 'firebase.init'. 
Probably still connected to the angular zones, but something that I was not able to solve.

Hope this helps!

Thanks

**Comment by EddyVerbruggen** [comment]
Thanks for the thanks, @souly1! 😄 

The demo app also uses the separate `addOnMessageReceivedCallback` function, and I think most people use that approach as it won't trigger the push notification registration permission prompt during `init`. Not sure why that would block navigation though, but I'm sure someone will find your experience useful, so very grateful you shared it!

**Comment by EddyVerbruggen** [comment]
Look mom, I just created a new label for this repo! "Tip" 🤣

**Comment by chernov-stas** [comment]
Very useful tip, @souly1! 👏 
Wish I found it before. I've spent so much time trying to make navigation work. Maybe it even worth mentioning somewhere in the docs

**Comment by EddyVerbruggen** [comment]
@chernov-stas Happy you found it useful! If you think others will benefit as well, please consider doing a PR to the docs.

**Comment by RoyiNamir** [comment]
@souly1 Thank you for this info !I've been dealing with this for 4 hours.

**Comment by phatakrajan** [comment]
I have created a firebase service and planning to use router object inside the same. Do i still need to use "addOnMessageReceivedCallback" or i can write the callback function within init itself?

**Comment by agnoam** [comment]
Hey, I'm dealing with receiving share intent in android NativeScript angular app. And I search a way to navigate in my pages. The app log that the page moved but actually nothing was changed on the UI. There is any way to fix it **without firebase** ?
