### ISSUE TITLE
Support for Push Notifications

### ISSUE THREAD

**Issue by jlooper** [EddyVerbruggen/nativescript-plugin-firebase#54]
I know push is a big fat pain but I feel like, by leveraging Firebase, we can avoid at least two or three extra plugin installations by supporting the build-in power of Firebase 3.0. Just want to put on your radar screen support for the new Firebase Cloud Messaging which is essentially rebranded GCM. Maybe we could reuse some GCM integration borrowed from the current NativeScript Push plugin. 

Thanks Eddy!

**Comment by EddyVerbruggen** [comment]
Wow, FCM is a step up from GCM configuration-wise. Certainly considering this!

**Comment by jlooper** [comment]
I know, and the whole cross platform story is super compelling...

**Comment by EddyVerbruggen** [comment]
Getting somewhere!

Note that iOS certificate hell is still as bad as ever.

![img_7343](https://cloud.githubusercontent.com/assets/1426370/16266259/306d9c12-3884-11e6-8a1a-c3d9466462f4.PNG)

![img_7342](https://cloud.githubusercontent.com/assets/1426370/16266261/3071b9c8-3884-11e6-936a-0baea01392ff.PNG)

![img_7341](https://cloud.githubusercontent.com/assets/1426370/16266260/30703814-3884-11e6-8e3f-6039283bc063.PNG)

**Comment by EddyVerbruggen** [comment]
Update: iOS 10 had some push / badge issues that delayed my work a bit. I'm just assuming those are pre-beta issues that will be ironed out, so testing this baby with iOS 9 for now and it starts to look super good!

**Comment by bfv** [comment]
My hands are itching to get to work with this! Any idea when there will be something "releasable"?

**Comment by EddyVerbruggen** [comment]
Ha, @bfv, you can expect iOS support to land today. I'm doing the final tests and have to document it. You can prepare yourself by going through certificate hell (add the push entitlement to your appid at the iOS developer center, add the push certificates to it, upload those certs to the firebase console, generate and download new provisioning profiles - basically [this](https://firebase.google.com/docs/cloud-messaging/ios/certs)).

Android support will follow shortly after, but once you've got iOS running that will be a breeze to add.

**Comment by EddyVerbruggen** [comment]
@bfv go ahead and grab it from github.. not on npm yet. Working on Android support currently.

**Comment by jlooper** [comment]
So amped for this!

**Comment by EddyVerbruggen** [comment]
Android support just landed! 🚀 

Tagging and releasing 3.3.0 right now, see [the new docs](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/MESSAGING.md) on how to use it.

**Comment by EddyVerbruggen** [comment]
Btw, I recommend removing and adding the Android platform since I figured out which bits of the play services libs were really needed on Android (thanks Google for not documenting that) - should help ppl not running into multiDex issues in the future. Don't forget to re-add the two gradle afterwards bits as mentioned in the readme.

**Comment by jlooper** [comment]
Fantastic, Eddy! 👏🏻👏🏻👏🏻👏🏻👏🏻

**Comment by bfv** [comment]
It works! Thanks!

**Comment by pap5508** [comment]
I am looking for Nativescript Firebase Push Notification demo sample.. Anyone please help ??

**Comment by pap5508** [comment]
firebase.init({
       iOSEmulatorFlush: true,
        onPushTokenReceivedCallback (token){
          console.log("Push Token: "+ token);
        }
       , 

      onMessageReceivedCallback: function(message) {
         	alert(message.title+"");
           this.router.navigate(["/main-menu"]);
      }
        }).then(
            (instance) => {
                console.log("firebase.init done");
            },
            (error) => {
                console.log("firebase.init error: " + error);
            });


How can I send push token to Own backend Server.. __

**Comment by asaph26** [comment]
@pap5508 You can send the token to the backend by utilising the onPushTokenReceivedCallback callback inside the init method.

```
onPushTokenReceivedCallback (token){ 
    //send the token to the backend. You might also want to add some additional information such as the user details in case you want to target notifications to the a specific user
}
```

**Comment by jlooper** [comment]
I'm working on a blogpost about this, please stay tuned and watch for it in the NativeScript blog!

**Comment by pap5508** [comment]
@jlooper : Have u completed your blog..???

**Comment by jlooper** [comment]
@pap5508 working on it for next week, thanks

**Comment by pap5508** [comment]
I am working on firebase push notifications bt I am not able to launch
dialog for asking permission...

Though response from server that Firebase init done.
.



Hope you can guide me that why confirm dialog is not showing..???


Rewards,
Parth

**Comment by URvesh109** [comment]
Firebase Cloud Messaging (FCM) get always prompt though no message is send with nativescript webpack plugin, but work gud without nativescript webpack plugin
