### ISSUE TITLE
iOS Build Fail

### ISSUE THREAD

**Issue by zoeitsolutions** [EddyVerbruggen/nativescript-plugin-firebase#540]
Hi,

I am getting the following error:

=== BUILD TARGET ISMessages OF PROJECT Pods WITH CONFIGURATION Debug ===
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
** BUILD FAILED **

Command xcodebuild failed with exit code 65

I see that ISMessages is getting pulled from:

Pre-downloading: `ISMessages` from `https://github.com/EddyVerbruggen/ISMessages.git`, commit `d54b0901bd390164e45adee4e7158122440d10eb`

This is a NG project using the latest version of TNS and the plugin.

Android build works fine for the project.

How to fix this?

**Comment by EddyVerbruggen** [comment]
Hi `ISMessages` is used in the nativescript-feedback plugin, not this one... do you think there's some interference between the two?

**Comment by zoeitsolutions** [comment]
Ok. Let me remove that plugin and do a build to see. FYI I am using the latest version of that plugin as well.

**Comment by zoeitsolutions** [comment]
@EddyVerbruggen I did a fresh build and it still fails:

Preparing project...
Successfully prepared plugin nativescript-angular for ios.
Successfully prepared plugin nativescript-camera for ios.
Successfully prepared plugin nativescript-email for ios.
Successfully prepared plugin nativescript-geolocation for ios.
Successfully prepared plugin nativescript-ngx-fonticon for ios.
Successfully prepared plugin nativescript-plugin-firebase for ios.
Successfully prepared plugin nativescript-socket.io for ios.
Successfully prepared plugin nativescript-telerik-ui-pro for ios.
Successfully prepared plugin nativescript-theme-core for ios.
Successfully prepared plugin tns-core-modules for ios.
Successfully prepared plugin nativescript-intl for ios.
Successfully prepared plugin nativescript-dom for ios.
Successfully prepared plugin tns-core-modules-widgets for ios.
Installing pods...
Analyzing dependencies
Downloading dependencies
Installing Firebase (4.4.0)
Installing FirebaseAnalytics (4.0.4)
Installing FirebaseAuth (4.3.0)
Installing FirebaseCore (4.0.9)
Installing FirebaseDatabase (4.1.1)
Installing FirebaseInstanceID (2.0.5)
Installing FirebaseMessaging (2.0.5)
Installing GTMOAuth2 (1.1.5)
Installing GTMSessionFetcher (1.1.12)
Installing GoogleSignIn (4.1.1)
Installing GoogleToolboxForMac (2.1.3)
Installing Protobuf (3.4.0)
Installing Socket.IO-Client-Swift (11.1.3)
Installing StarscreamSocketIO (8.0.7)
Installing leveldb-library (1.20)
Installing nanopb (0.3.8)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `xxx.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There are 6 dependencies from the Podfile and 16 total pods installed.
[WARNING]: [!] Automatically assigning platform ios with version 8.0 on target mobiskills because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
Project successfully prepared (ios)
Executing after-prepare hook from /Library/WebServer/Documents/demos/nativescript/xxx/hooks/after-prepare/firebase-build-gradle.js
Configure firebase
Executing after-prepare hook from /Library/WebServer/Documents/demos/nativescript/xxx/hooks/after-prepare/firebase-copy-google-services.js
Copy /Library/WebServer/Documents/demos/nativescript/xxx/app/App_Resources/Android/google-services.json to /Library/WebServer/Documents/demos/nativescript/xxx/platforms/android/google-services.json.
Executing after-prepare hook from /Library/WebServer/Documents/demos/nativescript/xxx/hooks/after-prepare/nativescript-dev-sass.js
All SASS source files removed from app package
Executing after-prepare hook from /Library/WebServer/Documents/demos/nativescript/xxx/hooks/after-prepare/nativescript-plugin-firebase.js
Building project...
Xcode build...
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
** BUILD FAILED **

Command xcodebuild failed with exit code 65

I checked to make sure I am using the latest version of each plugin.

So I am really not sure which one is failing.

**Comment by EddyVerbruggen** [comment]
Can you please share a repo that I can clone and replicate this issue?

**Comment by zoeitsolutions** [comment]
Will do

**Comment by zoeitsolutions** [comment]
@EddyVerbruggen I created a test repo and found that SocketIO plugin is breaking the build process.

Adding of the below plugins breaks the build:

https://github.com/naderio/nativescript-socket.io
https://github.com/triniwiz/nativescript-socketio

I am closing this issue here, and will pick it up with the other repos authors.

**Comment by EddyVerbruggen** [comment]
Ouch, OK, thanks for the update and good luck! 👍
