### ISSUE TITLE
Firebase crashlytics

### ISSUE THREAD

**Issue by tsili852** [EddyVerbruggen/nativescript-plugin-firebase#543]
Does the plugin works with the new Firebase crashlytics?
The Crash Reporting that is already implemented works only with the initial firebase Crash reporting?

**Comment by NathanWalker** [comment]
iOS support:
https://github.com/EddyVerbruggen/nativescript-plugin-firebase/pull/549

**Comment by r0zar** [comment]
I'm also curious of this.

**Comment by EddyVerbruggen** [comment]
Please update to 5.3.0 to be able to use Crashlytics. See the docs for details: https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/CRASHREPORTING.md
