### ISSUE TITLE
Compatibility with the Firebase Web API

### ISSUE THREAD

**Issue by EddyVerbruggen** [EddyVerbruggen/nativescript-plugin-firebase#548]
As y'all may know, this plugin is built on top of the native iOS and Android SDK's which are very different from the web API. For instance, the web API uses a method like `on` to attach an event listener to a db path, whereas the native (iOS) API uses `observeEventType:WithBlock:WithCancelBlock`.

Adding Web API compatibility will have the following benefits:
* Easily switch back and forth between web and native Firebase usage (for instance, to upgrade from webview-based usage scenario's).
* Allow for easier code sharing between web and native in 1 project.
* It will be easier to add AngularFire compatibility (#260) later, because that works on top of the Web API.

## Tasks:
These are the WebAPI function names I'd like to wire to their native equivalents (checked = completed):

### `firebase`
- [x] `.initializeApp`

### `firebase.auth()`
- [x] `.signInAnonymously`
- [x] `.signInWithEmailAndPassword`
- [x] `.createUserWithEmailAndPassword`
- [x] `.signOut`
- [x] `.fetchProvidersForEmail`

### `firebase.database().ref(path: string)`
- [x] `.set`
- [x] `.remove`
- [x] `.on`
- [x] `.off`
- [x] `.once`
- [x] `.orderByChild`
- [x] `.orderByKey`
- [x] `.orderByPriority`
- [x] `.orderByValue`

### `firebase.firestore()`
see #507 

## Other web API functions
Let's cut the 5.0.0 release and add other functions (based on demand by the community) later.

**Comment by RaphaelJenni** [comment]
@EddyVerbruggen for the authentication, how do I authenticate with a provider?

Can I run the web API and the "old" version in parallel? How? One uses `ns-pl-fb/app` and one doesn't require the `/app`. Do I need to have two different imports and how does it work with the initialization?

**Comment by EddyVerbruggen** [comment]
Hi @RaphaelJenni!

You can use them in parallel. Internally they call the same (native SDK) code. So you can mix & match them.

As an example look at the usages of [these imports](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/933f7d6de1020ffaaf3f387f1c80940ad6a60071/demo/app/main-view-model.ts#L8-L9) in the demo app.

**Comment by RaphaelJenni** [comment]
Ah perfect. Thanks.
