### ISSUE TITLE
iOS is closing app

### ISSUE THREAD

**Issue by Ceany** [EddyVerbruggen/nativescript-plugin-firebase#551]
I started on a basic Nativescript app with Firebase. 
I tried to add everything, but everytime when i try to call firebase.init({}) the app is closing on iOS. There is no error. On Android it is working.

main.ts
```
import { platformNativeScriptDynamic } from "nativescript-angular/platform";

import { AppModule } from "./app.module";

const firebase = require("nativescript-plugin-firebase");
firebase.init({});


platformNativeScriptDynamic().bootstrapModule(AppModule);
```

**Comment by EddyVerbruggen** [comment]
I think you need to wait with that init call until the app has started.

**Comment by Ceany** [comment]
I tried to place it in main.ts, in app.module.ts, and in app.component.ts. But everywhere the app is closing

**Comment by EddyVerbruggen** [comment]
Yeah that's all too early I think. You can leave that require in main.ts, but try moving init to somewhere else. Just for experiment sake move it to the `ngOnInit` of your first "page component".

**Comment by Ceany** [comment]
unfortunately it does not help. I have a login component. The UI is loading if I don't call ```firebase.init({})```. But when i add that code to the ```ngOnInit``` function of the login component the app closes again.

**Comment by EddyVerbruggen** [comment]
Version 5.0.3 may help with this as it fixes an issue where no feedback is given in the console, and the app just quits. The rootcause is explained in #564 but it may not be applicable. Just give it a try anyway please.
