### ISSUE TITLE
[Feature request] Extending it to cordova

### ISSUE THREAD

**Issue by bil-ash** [EddyVerbruggen/nativescript-plugin-firebase#552]
The plugin is awesome. But there is no firebase plugin for cordova with same(or at least comparable) set of features. Could you please extend it to cordova?
If not, do you know about any cordova plugin(for android) which allows access to nativescript plugins?

**Comment by EddyVerbruggen** [comment]
Hi, the scope of this plugin is NativeScript. Cordova plugins have a very different structure and the current code in this repo can’t be used in a Cordova plugin.

There is no way I know of to use a NativeScript plugin in a Cordova project, so you’ll really need to look for a Cordova plugin or use the web api.
