### ISSUE TITLE
Problems version 5.0

### ISSUE THREAD

**Issue by torvicv** [EddyVerbruggen/nativescript-plugin-firebase#554]
Excuse me my english, I am spanish.
I have had problems with new version 5.0.

Console show me these errors:

System.err: Calling js method onCreate failed
System.err:
System.err: TypeError: Cannot read property 'ServerValue' of undefined

I could solved after install previous version, 4.2.1.
If it can help anybody.

**Comment by EddyVerbruggen** [comment]
Can you please provide more info?

- Which platform (iOS / Android)
- What's the code triggering this error?
- A sample project recreating this issue perhaps..

**Comment by EddyVerbruggen** [comment]
IDK what `onCreate` is.. it's probably something in your app. Check the demo apps in this repo please, and reopen if you have more info.
