### ISSUE TITLE
getValue() not working

### ISSUE THREAD

**Issue by irthos** [EddyVerbruggen/nativescript-plugin-firebase#556]
Hello, thanks for the awesome plugin. I'm getting a firebase.getValue() is not a function error. Setting values and auth works fine. Using the latest nativescript and plugin versions. Any ideas why?

**Comment by EddyVerbruggen** [comment]
getValue was added in 5.0.0. Are you sure it’s all up to date?

If so, please share more info, like the platform and code.

**Comment by irthos** [comment]
ahh i'm on 4.2.1 sorry, assumed it was latest! my bad. i'll check that it works with 5 and come back to close!

**Comment by irthos** [comment]
Groovy, all good. my bad. thanks for the quick attention!
