### ISSUE TITLE
Holy Hot Push! "Firebase Remote Config" support please!

### ISSUE THREAD

**Issue by jlooper** [EddyVerbruggen/nativescript-plugin-firebase#56]
One more! We constantly are asked for support for hot push (e.g. deploying changes to the app stores without resubmitting), and it looks like Firebase Remote Config supports this. I would love to see this available for Firebase-configured apps! 

Thanks!

**Comment by EddyVerbruggen** [comment]
What I'm reading [here](https://firebase.google.com/docs/remote-config/) it's a way to remotely configure your app by flipping (boolean) switches or activating parts of your app after you shipped a version.

So you can't add content remotely but you can manipulate app behavior remotely (but you need to pre-cook those behaviors in your app beforehand).

I guess you can achieve the same results by looking at specific values in the database and manipulate those through the Firebase console, but this has a much cleaner API for that purpose.

I'm on it!

**Comment by jlooper** [comment]
Fabulous!!

**Comment by EddyVerbruggen** [comment]
Added in plugin version 3.2.0, see https://github.com/EddyVerbruggen/nativescript-plugin-firebase#getremoteconfig

Note that the Firebase SDK version is also bumped - update your local Android SDK as suggested in the readme.

**Comment by jlooper** [comment]
ugh, sadly I am getting this error. I believe the RemoteConfig is successfully being included in the new pod build, but the functionality isn't happening...:

```
Error: Uncaught (in promise): TypeError: firebase.getRemoteConfigDefaults is not a function. (In 'firebase.getRemoteConfigDefaults(art.properties)', 'firebase.getRemoteConfigDefaults' is undefined)
```

**Comment by EddyVerbruggen** [comment]
Crap, that may be an error on my part. Hang on.

**Comment by EddyVerbruggen** [comment]
Yep [this line](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/commit/7b77414359e0e1e27a203fd95f9f54d3a46dae28) needs to go. Was a last minute refactor which I tested on Android... Just pushed to master but you can manually drop it from the local firebase.js file.
