### ISSUE TITLE
Firebase Auth + WebPack crashing iOS application (when createUser is triggered)

### ISSUE THREAD

**Issue by NickIliev** [EddyVerbruggen/nativescript-plugin-firebase#564]
Bundling the app with WebPack is causing the application to crash on iOS when `createUser` method is used. The same scenario seems to work as expected when using `tns run ios`. 

Steps to reproduce:
- use [this application ](https://github.com/NickIliev/nativescript-ng-firebase-auth)(you will still need to adjust the package ID and the firebase console)
-  execute `npm run start-ios-bundle`
The crash happens only on iOS when [this line is called](https://github.com/NickIliev/nativescript-ng-firebase-auth/blob/master/app/item/items.component.ts#L21)

- or create an Angular application, init firebase and then call createUser
```
firebase.createUser({
    email: 'test001@gmail.com',
    password: '123456'
}).then((result) => {
    console.log(result);
}).catch(e => {
    console.log(e);
})
```

Result: the application is instantly killed on iOS.

**Comment by EddyVerbruggen** [comment]
The app crashes because `FIRApp.configure()` hasn't been executed, and that can only be the case when the mandatory `init` function wasn't invoked first.

I'll move that `FIRApp.configure()` outside `init` to prevent this in the future.

**Comment by EddyVerbruggen** [comment]
Looks like this kills background push notifications. Foreground is OK, but I can reproduce breaking/fixing background notifications on iOS by moving `FIRApp.configure()` back and forth between `.init` and at a global level. The latter breaks the notifications.

I'll do what Firebase actually recommends: run `FIRApp.configure()` in `application:didFinishLaunching:withOptions`.

**Comment by shabib3** [comment]
Hi I experience a case that the app is stuck on the logo page, and after debug it I saw that it stuck on `FIRApp.configure()`after I call `firebase.init` function...Only on IOS.

any idea what can cause that?
