### ISSUE TITLE
Cannot read property firebase of undefined error in Windows 7 Genymotion

### ISSUE THREAD

**Issue by vzhen** [EddyVerbruggen/nativescript-plugin-firebase#57]
Here is my setup.

**Enviroment**

Windows 7 64bits
Genymotion android 4.4

**Genymotion Google play service setup**

1. Drag Genymotion-ARM-Translation_v1.1 to install
2. adb reboot
3. Drag gapps-kk-20140606-signed to install
4. adb reboot
5. login google account
6. update all google apps including google play services

**Create new Nativescript app**

1. tns create my-app
2. tns livesync android  --watch to check if {N} working.

**Install nativescript-plugin-firebase@3.0.1**

- Download google-services.json from firebase console and move it to platform/android
- tns plugin add nativescript-plugin-firebase
- add applicationId “org.nativescript.myapp” and “multiDexEnabled true” in app/App_Resources/Android/app.gradle
```
defaultConfig { 
  generatedDensities = [] 
  applicationId “org.nativescript.myapp”
  multiDexEnabled true
}
```
- add classpath “com.google.gms:google-services:3.0.0” in platforms/android/build.gradle
```
dependencies {
 classpath “com.android.tools.build:gradle:1.5.0”
 classpath “com.google.gms:google-services:3.0.0”
 }
```
- In same file, platforms/android/build.gradle add apply plugin: “com.google.gms.google-services” at very bottom.
- add these 2 lines in app/references.d.ts
```
/// <reference path=”../node_modules/nativescript-plugin-firebase/firebase.d.ts” />
/// <reference path=”../node_modules/nativescript-plugin-firebase/firebase-common.d.ts” />
```
- add firebase.init in app.js
```
var application = require(“application”);
var firebase = require(“nativescript-plugin-firebase”);
firebase.init({
   persist: true // Allow disk persistence. Default false.
}).then(function (instance) {
   console.log(“firebase.init done”);
},function (error) {
 console.log(“firebase.init error: “ + error);
});
application.start({ moduleName: “main-page” });
```

- tns livesync android  --watch

Ok, app is running but got firebase init error: cannot read property firebase of undefined in cmd.

**Comment by EddyVerbruggen** [comment]
I'm not sure the plugin behaves nicely if you run init before the app itself is completely bootstrapped -- can you move firebase stuff to after `application.start`?

**Comment by vzhen** [comment]
Tried and same error, i even tested init in another module. By the way, where to check logs file?  so i can provide you more info

**Comment by vzhen** [comment]
@EddyVerbruggen i tested it again on version 3.2.0  there is an new error.

![capture](https://cloud.githubusercontent.com/assets/1941395/16211523/9f95e3b2-3774-11e6-8951-c9bcce7977cf.png)

**Comment by EddyVerbruggen** [comment]
Did you follow all the steps in the readme, including the 'known issues' section? This is not an easy thing to do so please have patience.

**Comment by vzhen** [comment]
My bad,  i got id typo.
Ok,  Cannot read property firebase of undefined error fixed. Thanks for that.

but there is a new weird issue, refer to image below. At first, firebase init done but after 2-3 seconds it returns FirebaseApp with name [DEFAULT] doesn't exists. The weird thing is, i'm able to push() to firebase. LOL

Let me know if you want to open this as new issue
![capture](https://cloud.githubusercontent.com/assets/1941395/16213335/2985aeb6-3781-11e6-9db6-cbe3995076ec.png)

**Comment by EddyVerbruggen** [comment]
No please check the known issues in the readme for that error.
