### ISSUE TITLE
Firestore typescript not compiling

### ISSUE THREAD

**Issue by Kunoacc** [EddyVerbruggen/nativescript-plugin-firebase#571]
When i try to compile my android app with NS + Typescript i get this error:

`app/home/home-page.ts(19,19): error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof firestore' has no compatible call signatures.`

from this line

`const years = firebase.firestore().collection("Years");`

**Comment by mast3rd3mon** [comment]
Any progress on this? just encountered it today

**Comment by EddyVerbruggen** [comment]
Check out this import:

https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/d7499af7831157e17b1b02e32472ef1d72e740e1/demo-ng/app/item/items.component.ts#L6

And this usage:

https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/d7499af7831157e17b1b02e32472ef1d72e740e1/demo-ng/app/item/items.component.ts#L36

**Comment by mast3rd3mon** [comment]
Well it doesnt error in the ide anymore, thanks Eddy!
