### ISSUE TITLE
firebase.createUser does not work on Android

### ISSUE THREAD

**Issue by R4h4** [EddyVerbruggen/nativescript-plugin-firebase#575]
Hi,

latest since the update to 5.0.4 (and in my memory also on 5.0.3) firebase.createUser does not seem to work on Android. "Not work" means, that after calling the function I do not get a result (or an error) back.

How to recreate:

- use [this application](https://github.com/NickIliev/nativescript-ng-firebase-auth) (you will still need to adjust the package ID, the firebase console and change the plugin version to 5.0.4 inside the package.json)
- run `tns run android`
- or create an Angular application, init firebase and then call createUser

` firebase.createUser({
    email: 'test001@gmail.com',
    password: '123456'
}).then((result) => {
    console.log(result);
}).catch(e => {
    console.log(e);
}) `

In both cases, the app does not receive a result.

**Comment by EddyVerbruggen** [comment]
I'm sorry but I can't reproduce this - it works fine for me on Android (Samsung S8).

I tried with `{ email: 'eddy2@xservices.nl', password: 'firebase' }`.
