### ISSUE TITLE
no way to register for push on IOS

### ISSUE THREAD

**Issue by Pant76** [EddyVerbruggen/nativescript-plugin-firebase#576]
[xcodeLog.txt](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/files/1563322/xcodeLog.txt)
Hi,
i followed readme instructions + this:
https://firebase.google.com/docs/cloud-messaging/ios/certs

my code is:
`firebase.init({
    persist: false,
    iOSEmulatorFlush: true,
    onPushTokenReceivedCallback: function(token) {
        console.log("Firebase push token: " + token);
      },
    //storageBucket: config.firebaseBucket,
    onMessageReceivedCallback: function(message) {
        console.log("Title: " + message.title);
        console.log("Body: " + message.body); 
        // if your server passed a custom property called 'foo', then do this:
        console.log("Value of 'foo': " + message.data.foo);
        alert();
      }
    }).then(() => console.log("firebase.init done"),
    (error) => console.log(`firebase.init error: ${error}`));`

I obtain "firebase.init.done" but **No way to get onPushTokenReceivedCallback fired**.
No errors on console.

I tried debugging with xcode enabling firebase analythics logging verbose and i obtain the log attached!

**Comment by Pant76** [comment]
...I uninstalled and reinstalled plugin....now it's ok but no way to obtain background notification! (i'll follow on other issue)

**Comment by TheOnlyMatt** [comment]
Did you find a way to solve this ?
