### ISSUE TITLE
sendEmailVerification - "Run init() first!" issue

### ISSUE THREAD

**Issue by damikael** [EddyVerbruggen/nativescript-plugin-firebase#581]
Thanks for this awesome plugin!
I'm using latest version of Nativescript and nativescript-plugin-firebase with Angular (Typescript).
After latest upgrades the function sendEmailVerification for Android does not works anymore (I don't tried for iOS)
It always return error "Run init() first!" also after firebase init and login.
I had to comment out the follow code inside firebase.android.js into node_modules to get it work right:

```
firebase_common_1.firebase.sendEmailVerification = function () {
   return new Promise(function (resolve, reject) {
      try {
         /*
         if (firebase_common_1.firebase.instance === null) {
            reject("Run init() first!");
            return;
         }
         */
         ...
```

Can you check it please?
Thanks

**Comment by EddyVerbruggen** [comment]
Ah, interesting point. Are you using Firestore or the (older) Real-time database, or none of the above (check your `firebase.nativescript.json` file).

**Comment by damikael** [comment]
None:
```
{
    "using_ios": true,
    "using_android": true,
    "firestore": false,
    "realtimedb": false,
    "remote_config": false,
    "messaging": true,
    "crash_reporting": true,
    "storage": false,
    "facebook_auth": false,
    "google_auth": false,
    "admob": false,
    "invites": false
}
```

**Comment by EddyVerbruggen** [comment]
I figured. Let's support this case, thanks!

**Comment by damikael** [comment]
Thanks to you!

**Comment by EddyVerbruggen** [comment]
Please give 5.0.5 a try.

**Comment by mzainulhassan** [comment]
what is the solution of this error "JS: Run init() first!"

**Comment by mzainulhassan** [comment]
pls tell me solution of this problem
