### ISSUE TITLE
Facebook login keep spinning on Android

### ISSUE THREAD

**Issue by d3mac123** [EddyVerbruggen/nativescript-plugin-firebase#583]
App was working fine until I update to {N} 3.4 and Firebase plugin 5.0.5 in both Android Simulator and RHD1 devices. However, now it works on the Simulator but keep spinning (and not even show Facebook app for validation) on the device. Console shows:
```
ActivityManager: Start proc 31243:com.asouza.ppgFinder/u0a281 for activity com.asouza.ppgFinder/com.tns.NativeScriptActivity
ActivityManager: START u0 {act=NATIVE_WITH_FALLBACK cmp=com.asouza.ppgFinder/com.facebook.FacebookActivity (has extras)} from uid 10281 from pid 31243 on display 0
```

Then, it crashes:
```
ActivityManager: Killing 31243:com.asouza.ppgFinder/u0a281 (adj 0): stop com.asouza.ppgFinder
ActivityManager: Spurious death for ProcessRecord{13c89c5 0:com.asouza.ppgFinder/u0a281}, curProc for 31243: null
```
Any ideas how to address this issue?

**Comment by EddyVerbruggen** [comment]
There’s not much relevant info in those logs. Can you narrow it down to either the plugin or nativescript version you updated? And what’s RHD1?

**Comment by d3mac123** [comment]
Eddy, thanks for chime in. After a few device (RHD1) reboots, every thing went back to normal. Weird. Thanks again!
