### ISSUE TITLE
What are the best patterns for login persistence and checking.

### ISSUE THREAD

**Issue by bearoutthere** [EddyVerbruggen/nativescript-plugin-firebase#584]
I'm new to NativeScript and Firebase so apologies if this is a stupid question.  I'm wondering what is the best pattern to keep logged in state between pages and sessions.  I'd like the NS app to stay logged in until the user explicitly loggs out.  This means that if a user closes and reopens the app he will remain logged in.  Do i need to do anything with the token or does the persist: true option in firebase.init take care of that automatically.  
Is there a need to check for a current valid user token on every page in the app or does firebase plugin take care of that?  What's the best pattern for that?

The example includes all of the firebase functionality on a single page so it's not clear how to use it for a multi-page application.

Thanks in advance.

**Comment by bearoutthere** [comment]
Found the answer after some more digging:

https://groups.google.com/forum/#!searchin/firebase-talk/keep$20user$20logged$20in|sort:date/firebase-talk/DFSIzikV98w/8035m15CwS4J

https://firebase.google.com/docs/auth/web/auth-state-persistence

https://groups.google.com/forum/#!searchin/firebase-talk/keep$20user$20logged$20in|sort:date/firebase-talk/deOdomCEaa4/WAyecXOkEQAJ

**Comment by BMwanza** [comment]
I'm still very confused on how to do this using the Native Script firebase plug in. I want the same thing: All I want is that once a user logs in they remained logged in and authenticated until the explicilty log out
