### ISSUE TITLE
Push token is not always a string

### ISSUE THREAD

**Issue by erkanarslan** [EddyVerbruggen/nativescript-plugin-firebase#587]
`onPushTokenReceivedCallback` provides the token as a string and a native iOS object (I guess). I log the provided token to console. When app starts callback is called twice with these parameters in this order:

````
cEaxp1x58Ns:APA91bFOrbKjPnAdU4E100YQhILtIFieLZOzSOYhelQklEHr103-X_c4p31lCamARGBy9ndSC3tiuElA_hBx4ynWqS2TtAwFJiN0ppLdu9NkZuQomym9nch0uVicSiwzXDmw8TmQd810

NSConcreteNotification 0x1c0a49990 {name = com.firebase.iid.notif.refresh-token; object = cEaxp1x58Ns:APA91bFOrbKjPnAdU4E100YQhILtIFieLZOzSOYhelQklEHr103-X_c4p31lCamARGBy9ndSC3tiuElA_hBx4ynWqS2TtAwFJiN0ppLdu9NkZuQomym9nch0uVicSiwzXDmw8TmQd810}
````

Second one is treated like an object in the typescript code. Because of that I have to check type of the token when I get it.

If I call `firebase.init` 3 seconds after app starts, the callback is called only once with the second parameter: `NSConcreteNotification ...`.

**Comment by EddyVerbruggen** [comment]
Thanks for reporting that! Fixed in 5.1.0.
