### ISSUE TITLE
Firestore: doc.exists returns true for non-existing documents

### ISSUE THREAD

**Issue by RyanNuijen** [EddyVerbruggen/nativescript-plugin-firebase#589]
`let myRef = fb.firestore().collection('existingcollection').doc('reallydoesnotexist');
 myRef.get().then(doc => {
      console.log(doc.exists); //returns true??? 
})`

`doc.data();` shows "This document doesn't exist...." in the console.

**Comment by EddyVerbruggen** [comment]
iOS/Android/both?

**Comment by RyanNuijen** [comment]
I'm not able to test this on iOS at the moment so can only confirm it happens on Android. Tested both the emulator and a real device. Plugin version 5.0.5 + NS 3.3.0.

**Comment by EddyVerbruggen** [comment]
Seems like it happens on iOS as well.

**Comment by EddyVerbruggen** [comment]
Thanks for the report - fixed in 5.1.1.
