### ISSUE TITLE
Cannot save Date and Array objects to Firestore

### ISSUE THREAD

**Issue by resnickj** [EddyVerbruggen/nativescript-plugin-firebase#592]
When saving data to Cloud Firestore, native JS Date objects should be saved in the database with the date/time data type, and JS Array objects should be saved in the database with the array data type, as suggested by the example shown here (scroll to "Data types" heading):
https://firebase.google.com/docs/firestore/manage-data/add-data

Instead, both of these end up being saved as "object" data type. I have traced the issue to two methods: `firebase.toHashMap` and `firebase.toValue` (in firebase.android.ts), where both Date and Array objects will match the first case in the switch statement and are therefore treated as objects.

I was able to work around the issue for now by monkey-patching these methods - pasted below for  reference.

    const fb = require("nativescript-plugin-firebase");
    fb.toValue = val => {
        let returnVal = null;
        if (val !== null) {
            // Patch: handle Date and Array objects
            if(val instanceof Date) {
                return new java.util.Date(val.getTime());
            }
            if(Array.isArray(val)) {
                return fb.toJavaArray(val);
            }

            switch (typeof val) {
                case 'object':
                    returnVal = fb.toHashMap(val);
                    break;
                case 'boolean':
                    returnVal = java.lang.Boolean.valueOf(String(val));
                    break;
                case 'number':
                    if (Number(val) === val && val % 1 === 0)
                        returnVal = java.lang.Long.valueOf(String(val));
                    else
                        returnVal = java.lang.Double.valueOf(String(val));
                    break;
                case 'string':
                    returnVal = String(val);
                    break;
            }
        }
        return returnVal;
    };
    fb.toHashMap = obj => {
        const node = new java.util.HashMap();
        for (const property in obj) {
            if (obj.hasOwnProperty(property)) {
                if (obj[property] === null) {
                    node.put(property, null);
                } else {
                    // Patch: handle Date and Array objects
                    if(obj[property] instanceof Date) {
                        node.put(property, new java.util.Date(obj[property].getTime()));
                    } else if (Array.isArray(obj[property])){
                        node.put(property, fb.toJavaArray(obj[property]));
                    } else {
                        switch (typeof obj[property]) {
                            case 'object':
                                node.put(property, fb.toHashMap(obj[property], node));
                                break;
                            case 'boolean':
                                node.put(property, java.lang.Boolean.valueOf(String(obj[property])));
                                break;
                            case 'number':
                                if (Number(obj[property]) === obj[property] && obj[property] % 1 === 0)
                                    node.put(property, java.lang.Long.valueOf(String(obj[property])));
                                else
                                    node.put(property, java.lang.Double.valueOf(String(obj[property])));
                                break;
                            case 'string':
                                node.put(property, String(obj[property]));
                                break;
                        }
                    }
                }
            }
        }
        return node;
    };

    fb.toJavaArray= val => {
        var javaArray = new java.util.ArrayList();
        for(var i = 0; i < val.length; i++) {
            javaArray.add(fb.toValue(val[i]));
        }
        return javaArray;
    };

**Comment by EddyVerbruggen** [comment]
Once you're happy with testing these changes, would you mind doing a PR?

**Comment by jr76** [comment]
I'm happy to do a PR - will try to get to it this week sometime. I don't have a means to really test it beyond my particular use case, but I think the changes are simple enough.

**Comment by abhayastudios** [comment]
Had a similar issue where an empty JS array was being stored as an empty object in Firestore with 5.1.1 but this seems to have been solved in 5.1.6. Seems like the above patch was added to the code, so I think this issue can be closed.

**Comment by EddyVerbruggen** [comment]
@abhayastudios Yes, this was fixed by #598 in 5.1.6. I forgot to close this issue.
