### ISSUE TITLE
JS: Error: Uncaught (in promise): Run init() first!

### ISSUE THREAD

**Issue by mzainulhassan** [EddyVerbruggen/nativescript-plugin-firebase#593]
i got this error while doing firebase.push()

**Comment by EddyVerbruggen** [comment]
Did you run `firebase.init()` first?

**Comment by mzainulhassan** [comment]
yes

**Comment by mzainulhassan** [comment]
const firebase = require("nativescript-plugin-firebase");
firebase.init({
    persist: false
}).then(
  instance => {
    console.log("firebase.init done");
  },
  error => {
    console.log(`firebase.init error: ${error}`);
  }
);
firebase.push();

**Comment by EddyVerbruggen** [comment]
I hope you realize your bug report is not too helpful this way. Can you share a repo reproducing the issue? Then also state the steps I need to take to reproduce the issue, and on which platform.

**Comment by ITServicesAM** [comment]
In my opinion he calls firebase.push() befor the init function returns.
Try to move your call to firebase.push in the then block of the promise returned by the call to firebase.init().
If your are using angular maybe you have to wrap that call in a NgZone.run call

**Comment by mzainulhassan** [comment]
can u provide the code?

**Comment by ITServicesAM** [comment]
```javascript
const firebase = require("nativescript-plugin-firebase");

firebase.init({
    persist: false
}).then(instance => {
    console.log("firebase.init done");
    firebase.push();
}, error => {
    console.log(firebase.init error: ${error});
});
```

**Comment by mzainulhassan** [comment]
still same error

JS: firebase.init done
JS: Unhandled Promise rejection: Run init() first! ; Zone: <root> ; Task: Promise.then ; Value: Run init() first!
JS: Error: Uncaught (in promise): Run init() first!

**Comment by giorgiopiatti** [comment]
I think that this is related to #612, which version of nativescript and angular are you using?

**Comment by EddyVerbruggen** [comment]
See #613.
