### ISSUE TITLE
Creating Observables from Firestore Documents/Collections

### ISSUE THREAD

**Issue by andrewexton373** [EddyVerbruggen/nativescript-plugin-firebase#595]
I'm trying to determine the best route for creating observables from the recently added firestore features. It seems as if it would be possible, but maybe firestore isn't intended to be used with observables?

```
public getCurrentUserAssignments(): Observable<any> {
        return new Observable((observer) => {
            const query = this.assignmentsColRef
                .where("uid", "==", BackendService.currentUID);

            let _currentUserAssignments = query.get().then(querySnapshot => {
                this.ngZone.run(() => {
                    observer.next(querySnapshot.docSnapshots);
                });
            });
        });
    }
```

This is my current implementation.. it retrieves the user associated assignments once, but doesn't update after adding an addition user assignment to the collection. Is this possible with firestore?

**Comment by andrewexton373** [comment]
The WebApi shows it possible to call .onSnapshot(callback) on a collection (https://firebase.google.com/docs/firestore/query-data/listen), as far as I can tell this isn't possible yet with this plugin?

**Comment by EddyVerbruggen** [comment]
I'm hoping to be able to make this plugin compatible with https://github.com/angular/angularfire2 which uses observables.

I've added `onSnapshot` to a document, but not to a collection. Shouldn't be too hard though.

**Comment by EddyVerbruggen** [comment]
With 5.1.2 you can use the new [`collection.onSnapshot`](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/FIRESTORE.md#collectiononsnapshot) feature. There's a link to an Observables example in the readme as well.

Please give me some feedback on what you think of it as I don't use Observables much myself, but I'd love to broaden its support in this plugin.

**Comment by andrewexton373** [comment]
You do awesome work Eddy!!! Really appreciate your efforts!
