### ISSUE TITLE
Can not to run Android, Could not find com.google.firebase:firebase-messaging:11.4.2.

### ISSUE THREAD

**Issue by yenjcc** [EddyVerbruggen/nativescript-plugin-firebase#596]
I'm facing this after installing pushnotifications plugin.  I followed the steps for fix the "Failed to apply plugin .. For input string: "+"". And then this others appear, i already update google Respository and Google play services. 
 
Any advise? 

> Could not resolve all dependencies for configuration ':_F0F1F2F3F4F5F6F7F8DebugApkCopy'.
   > Could not find com.google.android.gms:play-services-maps:11.8.0.
     Searched in the following locations:
         file:/C:/Android/android-sdk/extras/google/m2repository/com/google/android/gms/play-services-maps/11.8.0/play-services-maps-11.8.0.pom
         file:/C:/Android/android-sdk/extras/google/m2repository/com/google/android/gms/play-services-maps/11.8.0/play-services-maps-11.8.0.jar
         file:/C:/Users/yen/security-app/platforms/android/sdk-manager/com/google/android/gms/play-services-maps/11.8.0/play-services-maps-11.8.0.jar
         file:/C:/Android/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-maps/11.8.0/play-services-maps-11.8.0.pom
         file:/C:/Android/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-maps/11.8.0/play-services-maps-11.8.0.jar
         file:/C:/Users/yen/security-app/platforms/android/sdk-manager/com/google/android/gms/play-services-maps/11.8.0/play-services-maps-11.8.0.jar
     Required by:
         project :
   > Could not find com.google.firebase:firebase-messaging:11.4.2.
     Searched in the following locations:
         file:/C:/Android/android-sdk/extras/google/m2repository/com/google/firebase/firebase-messaging/11.4.2/firebase-messaging-11.4.2.pom
         file:/C:/Android/android-sdk/extras/google/m2repository/com/google/firebase/firebase-messaging/11.4.2/firebase-messaging-11.4.2.jar
         file:/C:/Users/yen/security-app/platforms/android/sdk-manager/com/google/firebase/firebase-messaging/11.4.2/firebase-messaging-11.4.2.jar
         file:/C:/Android/android-sdk/extras/android/m2repository/com/google/firebase/firebase-messaging/11.4.2/firebase-messaging-11.4.2.pom
         file:/C:/Android/android-sdk/extras/android/m2repository/com/google/firebase/firebase-messaging/11.4.2/firebase-messaging-11.4.2.jar
         file:/C:/Users/yen/security-app/platforms/android/sdk-manager/com/google/firebase/firebase-messaging/11.4.2/firebase-messaging-11.4.2.jar
     Required by:
         project :
   > Could not find com.google.firebase:firebase-core:11.8.0.
     Searched in the following locations:
         file:/C:/Android/android-sdk/extras/google/m2repository/com/google/firebase/firebase-core/11.8.0/firebase-core-11.8.0.pom
         file:/C:/Android/android-sdk/extras/google/m2repository/com/google/firebase/firebase-core/11.8.0/firebase-core-11.8.0.jar
         file:/C:/Users/yen/security-app/platforms/android/sdk-manager/com/google/firebase/firebase-core/11.8.0/firebase-core-11.8.0.jar
         file:/C:/Android/android-sdk/extras/android/m2repository/com/google/firebase/firebase-core/11.8.0/firebase-core-11.8.0.pom
         file:/C:/Android/android-sdk/extras/android/m2repository/com/google/firebase/firebase-core/11.8.0/firebase-core-11.8.0.jar
         file:/C:/Users/yen/security-app/platforms/android/sdk-manager/com/google/firebase/firebase-core/11.8.0/firebase-core-11.8.0.jar
     Required by:
         project :

**Comment by EddyVerbruggen** [comment]
Did you also try `rm -rf platforms/android`?

**Comment by yenjcc** [comment]
Yes, i tried that, before i run tns platform remove android, but keeps showing this error.

**Comment by yenjcc** [comment]
I found the solution, just replace the 	

classpath "com.google.gms:google-services:3.1.1" TO: 	classpath "com.google.gms:google-services:3.0.0"
in the platform/android/build.gradle.

Additionally, in the same file, in 


> repositories { 
>   jcenter()
>     // used for local *.AAR files
>     flatDir {
>     	dirs 'libs/aar'
> 	}
> 
> //I put this: 
> 
>  	**mavenLocal()
>          maven {
>              url 'https://maven.google.com'
>          }
>          maven {
>              // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
>              url "$rootDir/../node_modules/react-native/android"
>         }**
> }
`

**Comment by EvangelosG** [comment]
that is not a solution.
