### ISSUE TITLE
Firebase plugin Fail on IOS 9.2 ( XCode 7.2 )

### ISSUE THREAD

**Issue by enchev** [EddyVerbruggen/nativescript-plugin-firebase#6]
_From @wisonye on January 14, 2016 8:58_

Before I upgrade to IOS 9.2( XCode 7.2 ), everything is fine, but my Iphone upgrade to IOS9.2, then I also update to new XCode, after I upgraded, seems some plugins not work, for example "firebase", right now cannot run, the error looks like this:

```javascript
=== BUILD TARGET NativeScriptProject OF PROJECT NativeScriptProject WITH CONFIGURATION Debug ===

Check dependencies
CodeSign error: entitlements are required for product type 'Application' in SDK 'Simulator - iOS 9.2'. Your Xcode installation may be damaged.

** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
Command xcodebuild failed with exit code 65
# run ios

```

If I remove the plugin it can open fine( but of course my app will crash when running the firebase part ):

```javascript
tns plugin remove nativescript-plugin-firebase
```

I've already modified the Pod file to use latest version of firebase( 2.5.0 ), still not work, any help on this :(

_Copied from original issue: NativeScript/NativeScript#1372_

**Comment by jlooper** [comment]
@enchev Another user is encountering this, should we encourage everyone to stay with Xcode 7.1 for the time being?

**Comment by enchev** [comment]
Hey @jlooper,

We are still not sure what is causing this error. It works perfectly on some of the machines (like mine) and we receive reports for problems on other. Once we have more info we will announce it! In the meantime maybe it will be wise to hold any upgrades.

**Comment by jlooper** [comment]
To update this thread, I am using Xcode 7.3 with the newest Firebase plugin without issue.

**Comment by EddyVerbruggen** [comment]
I think this is obsolete with the Firebase 3.x SDK.

**Comment by rsquared86** [comment]
I'm using Xcode 7.3.1 with the latest firebase and am getting the same error as OP

** BUILD FAILED **


The following build commands failed:
	CompileC ../-ejorqvlibhcwgydczfrnxtludogd/Build/Intermediates/Pods.build/Debug-iphonesimulator/FBSDKCoreKit.build/Objects-normal/i386/FBSDKApplicationDelegate.o FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/FBSDKApplicationDelegate.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Command xcodebuild failed with exit code 65

**Comment by francorobles** [comment]
Im experiencing the same error of @rsquared86
