### ISSUE TITLE
[iOS] Unable to login using Facebook authentication

### ISSUE THREAD

**Issue by NordlingArt** [EddyVerbruggen/nativescript-plugin-firebase#60]
Using the latest plugin version. The login procedure will redirect me to the Facebook login page in Safari. After I sign in and accept, it redirects me to a blank page. I can only tap on "Done" in the upper left corner and a popup will say "login cancelled".

I have added the necessary lines in info.plist as Facebook stated when creating the app. Firebase config has also Facebook auth enabled with the correct API key and such.

**Comment by EddyVerbruggen** [comment]
Can you try adding [this bit to `app.js`](https://github.com/EddyVerbruggen/nativescript-plugin-firebase-demo/blob/master/Firebase/app/app.js#L5-L34)?

**Comment by NordlingArt** [comment]
@EddyVergurgen - That did work. However, the e-mail never gets recorded:

```
{
  "uid": "84gfhYMCQ5iVasdCH22A9LE0fndfg14",
  "profileImageURL": {},
  "email": null,
  "emailVerified": false,
  ...
}
```
![image](https://cloud.githubusercontent.com/assets/2098838/16227773/05ae8a08-37b3-11e6-85c9-679fd29c1c26.png)

**Comment by EddyVerbruggen** [comment]
I'm not sure that's expected anyway.. what does the Firebase documentation say?

**Comment by NordlingArt** [comment]
@EddyVerbruggen - According to [this post of yours](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/45#issuecomment-224423282), you got the email attached? I googled a little and [found this](http://stackoverflow.com/questions/24275410/get-email-with-facebook-firebase-simple-login). It says that this (from the Firebase web API) needs to be included in the auth process:

```
auth.login('facebook', {
  rememberMe: true,
  scope: 'email,user_likes'
});
```

Specifically referring to the scope property there. Could that be it?

**Comment by EddyVerbruggen** [comment]
[Email is already in the request](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/2a2c11b7ea14df354c34789b0808bd2b99745e08/firebase.ios.js#L333) and that screenshot has an email address because it was added by the 'login by email' type which was merged with the Facebook login (see the envelope above the Facebook logo).

So perhaps Firebase doesn't store the email in the console, but do you also not see the emailaddress in the login callback of the Facebook login? (not sure it should, I don't have access to my test app currently)

**Comment by NordlingArt** [comment]
@EddyVerbruggen 

Interesting... Well, as stated in a previous post, this is the callback from Facebook login:

```
{
  "uid": "84gfhYMCQ5iVasdCH22A9LE0fndfg14",
  "profileImageURL": {},
  "email": null,
  "emailVerified": false,
  "name": [hidden],
  "refreshToken": [long token]
}
```

Email is null, the rest seem to work (uid, profileImageURL, emailVerified, name, refreshToken).

The Facebook login does ask for the public profile and e-mail address (screenshot in Swedish):

![image](https://cloud.githubusercontent.com/assets/2098838/16235164/2713a4fa-37d4-11e6-87c4-51cfae095be9.png)

But the callback returns `email: null`

**Comment by NordlingArt** [comment]
I found the issue and [it seems to be a problem in Firebase itself](http://stackoverflow.com/questions/37522582/empty-email-field-of-firebase-auth-user-using-facebook-login-integration-fireba). I had to check "One account per email address" in the Firebase Sign-in Method page. That way the email property will get the e-mail address.

Though I still think it seems weird that you managed to combined the accounts together 🤔

**Comment by EddyVerbruggen** [comment]
I had that option checked from the get go. This particular user was already registered via email and later logged on via Facebook with the same email address. Then [this line of code](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/firebase.ios.js#L320) kicked in and linked the two.

**Comment by NordlingArt** [comment]
@EddyVerbruggen Ah, I see! However, I got the alert/error "email already in use" (or something like that) if I already had an account with the same email address (pretty sure that's what the option is for - to prevent double accounts).

This solved my issue though, so thank you for your help!

**Comment by EddyVerbruggen** [comment]
If you feel this needs to be documented in the readme, or is useful for others to know, please send a PR for the readme.

Happy coding!
