### ISSUE TITLE
Error using admob

### ISSUE THREAD

**Issue by thunder413** [EddyVerbruggen/nativescript-plugin-firebase#601]
I'm using "nativescript-angular": "~5.0.0" and building with webpack
I get this error when i use interstitial
```
JS: firebase.init done
JS: Error in firebase.admob.showInterstitial: Error: java.lang.NullPointerException: Context cannot be null
JS:     com.google.android.gms.common.internal.zzbq.checkNotNull(Unknown Source)JS:     com.google.android.gms.ads.InterstitialAd.<init>(Unknown Source)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:957)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:941)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:933)
JS:     com.tns.NativeScriptActivity.onStart(NativeScriptActivity.java:38)
JS:     android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1256)
JS:     android.app.Activity.performStart(Activity.java:6972)
JS:     android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2937)
JS:     android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
JS:     android.app.ActivityThread.-wrap14(ActivityThread.java)
JS:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
JS:     android.os.Handler.dispatchMessage(Handler.java:102)
JS:     android.os.Looper.loop(Looper.java:154)
JS:     android.app.ActivityThread.main(ActivityThread.java:6776)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
```
And this one when i use the banner```

JS: firebase.init done
JS: Error in firebase.admob.showBanner: Error: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
JS:     android.view.ViewConfiguration.get(ViewConfiguration.java:392)
JS:     android.view.View.<init>(View.java:4330)
JS:     android.view.View.<init>(View.java:4473)
JS:     android.view.ViewGroup.<init>(ViewGroup.java:579)
JS:     android.view.ViewGroup.<init>(ViewGroup.java:575)
JS:     android.view.ViewGroup.<init>(ViewGroup.java:571)
JS:     android.view.ViewGroup.<init>(ViewGroup.java:567)
JS:     com.google.android.gms.ads.BaseAdView.<init>(Unknown Source)
JS:     com.google.android.gms.ads.AdView.<init>(Unknown Source)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:957)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:941)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:933)
JS:     com.tns.NativeScriptActivity.onStart(NativeScriptActivity.java:38)
JS:     android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1256)
JS:     android.app.Activity.performStart(Activity.java:6972)
JS:     android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2937)
JS:     android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
JS:     android.app.ActivityThread.-wrap14(ActivityThread.java)
JS:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
JS:     android.os.Handler.dispatchMessage(Handler.java:102)
JS:     android.os.Looper.loop(Looper.java:154)
JS:     android.app.ActivityThread.main(ActivityThread.java:6776)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
JS: Angular is running in the development mode. Call enableProdMode() to enable
the production mode.
JS: Error: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
JS:     android.view.ViewConfiguration.get(ViewConfiguration.java:392)
JS:     android.view.View.<init>(View.java:4330)
JS:     android.view.View.<init>(View.java:4473)
JS:     android.view.ViewGroup.<init>(ViewGroup.java:579)
JS:     android.view.ViewGroup.<init>(ViewGroup.java:575)
JS:     android.view.ViewGroup.<init>(ViewGroup.java:571)
JS:     android.view.ViewGroup.<init>(ViewGroup.java:567)
JS:     com.google.android.gms.ads.BaseAdView.<init>(Unknown Source)
JS:     com.google.android.gms.ads.AdView.<init>(Unknown Source)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:957)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:941)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:933)
JS:     com.tns.NativeScriptActivity.onStart(NativeScriptActivity.java:38)
JS:     android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1256)
JS:     android.app.Activity.performStart(Activity.java:6972)
JS:     android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2937)
JS:     android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
JS:     android.app.ActivityThread.-wrap14(ActivityThread.java)
JS:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
JS:     android.os.Handler.dispatchMessage(Handler.java:102)
JS:     android.os.Looper.loop(Looper.java:154)
JS:     android.app.ActivityThread.main(ActivityThread.java:6776)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
```

**Comment by thunder413** [comment]
Any help here ?

**Comment by EddyVerbruggen** [comment]
Seems like a timing issue. I'll make it more robust in 5.1.3.

**Comment by thunder413** [comment]
Yes indeed i had to put it into a timeout Handler
Thanks for this plugin
