### ISSUE TITLE
firestore order by with where class does not work

### ISSUE THREAD

**Issue by narayananl23** [EddyVerbruggen/nativescript-plugin-firebase#602]
orderby is not working ? All latest versions

does not work   
`let query = citiesCollection.where("state", "==", "CA").orderBy("population", "desc").limit(2);`
does not work   
`let query = citiesCollection.where("state", "==", "CA").orderBy("population").limit(1);`
does not work   
`let query = citiesCollection.where("state", "==", "CA").orderBy("state").limit(1);`

Works 
`let query = citiesCollection.where("state", "==", "CA").limit(2);`
Works
`let query = citiesCollection.limit(2);`

Thanks,
Narayan

**Comment by narayananl23** [comment]
I was playing more with it.. it is not order by .. it is "order by" with "where" class

works
```
let query = citiesCollection.orderBy("population", "desc").limit(2); 
let query = citiesCollection.orderBy("population").limit(1);
let query = citiesCollection.where("state", "==", "CA").limit(2);
```
does not work
`let query = citiesCollection.where("state", "==", "CA").orderBy("population").limit(1);`

When order by used with where class it does not work.

Thanks
Narayan

**Comment by EddyVerbruggen** [comment]
You last example is actually exactly what the demo-ng app does:https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/a1cb801f2a7050ee0152b8e0a623260657c3483c/demo-ng/app/item/items.component.ts#L246-L249

I just tried it on both iOS and Android and it works as expected. These cities are returned in both cases, which aligns with my data model:

```text
{"capital":false,"country":"USA","state":"CA","name":"Los Angeles","population":3900000}
{"population":860000,"country":"USA","capital":false,"geo":{"latitude":4.444,"longitude":5.555},"name":"San Franciscoooo","state":"CA"}
```

Please run the demo-ng app and see for yourself, then provide me with a failing case I can reproduce and I'll take another look.

**Comment by narayananl23** [comment]
Thanks @EddyVerbruggen. Sharing my finding, so it can help others.

Copying the code from the demo ng helped. Since I am using non angular, I did not look at the sample at first and non angular do not have firestore sample. 

I was using [https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/FIRESTORE.md](url) "Ordering and limiting results of collection.where() " from the firestore doc page.

When I used the angular, I found that I do not have index. When I posted the issue, I did not have error handling so I got lost.

`CONSOLE LOG firestoreWhereOrderLimit failed, errorThe query requires an index. You can create it here: https://console.firebase.google.com/project/xxxxxx/database/firestore/indexes?create_index=xxxxxxxx`

**Comment by EddyVerbruggen** [comment]
Those index links are pretty cool indeed!

**Comment by Ravi2908** [comment]
The problem is you need to create an index for your where and orderBy condition 
in the indexes column in your cloud firestore. 

By creating indexes you will be able to fetch the record using where and orderBy

**Comment by halfbaked** [comment]
Thanks @Ravi2908 - this fixed the problem for me. If this step is in the documentation I missed it.

**Comment by EddyVerbruggen** [comment]
AFAIK you'll see a pretty descriptive error message if you catch it.
