### ISSUE TITLE
not able to authenticate using IOS:  Unhandled Promise rejection

### ISSUE THREAD

**Issue by sarojrout** [EddyVerbruggen/nativescript-plugin-firebase#605]
I am building a mobile app using native script. am getting the below error during startup of my project
CONSOLE LOG file:///app/main.js:31:16: firebase.init done
CONSOLE LOG file:///app/tns_modules/@angular/core/./bundles/core.umd.js:2957:20: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
CONSOLE ERROR file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:569:26: Unhandled Promise rejection: Error Domain=com.google.fcm Code=501 "(null)" ; Zone: <root> ; Task: null ; Value: Error Domain=com.google.fcm Code=501 "(null)" undefined
CONSOLE ERROR file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:571:22: Error: Uncaught (in promise): Error Domain=com.google.fcm Code=501 "(null)"
Normal message received by listener connection. Ignoring.
Could not successfully update network info during initialization.
[Firebase/InstanceID][I-IID003009] Failed to fetch default token Error Domain=com.firebase.iid Code=6 "(null)" UserInfo={NSUnderlyingError=0x608000a57970 {Error Domain=com.google.iid Code=-34018 "(null)"}}
[Firebase/InstanceID][I-IID009001] Error removing keypair status: -34018
[Firebase/InstanceID][I-IID010007] Unable to remove RSA keypair
[Firebase/InstanceID][I-IID007004] Unable to save checkin info, resetting checkin preferences in memory.
[Firebase/InstanceID][I-IID010003] Unable to generate keypair.
[Firebase/InstanceID][I-IID010009] Keypair could not be loaded from Keychain. Error: Error Domain=com.firebase.iid Code=-34018 "(null)"
[Firebase/Analytics][I-ACS020001] Failed to get InstanceID: Error Domain=com.firebase.iid Code=-34018 "(null)"
8:05:57 AM - Compilation complete. Watching for file changes.

[Firebase/InstanceID][I-IID007004] Unable to save checkin info, resetting checkin preferences in memory.
[Firebase/InstanceID][I-IID007004] Unable to save checkin info, resetting checkin preferences in memory.
[Firebase/InstanceID][I-IID003009] Failed to fetch default token Error Domain=com.firebase.iid Code=6 "(null)" UserInfo={NSUnderlyingError=0x600000e57e20 {Error Domain=com.google.iid Code=-34018 "(null)"}}
[Firebase/InstanceID][I-IID007004] Unable to save checkin info, resetting checkin preferences in memory.
[Firebase/InstanceID][I-IID007004] Unable to save checkin info, resetting checkin preferences in memory.
[Firebase/InstanceID][I-IID007004] Unable to save checkin info, resetting checkin preferences in memory.
[Firebase/InstanceID][I-IID003009] Failed to fetch default token Error Domain=com.firebase.iid Code=6 "(null)" UserInfo={NSUnderlyingError=0x608000c595c0 {Error Domain=com.google.iid Code=-34018 "(null)"}}
[Firebase/InstanceID][I-IID007004] Unable to save checkin info, resetting checkin preferences in memory.
[Firebase/InstanceID][I-IID007004] Unable to save checkin info, resetting checkin preferences in memory.
[Firebase/InstanceID][I-IID003009] Failed to fetch default token Error Domain=com.firebase.iid Code=6 "(null)" UserInfo={NSUnderlyingError=0x608000c55840 {Error Domain=com.google.iid Code=-34018 "(null)"}}
CONSOLE WARN file:///app/tns_modules/@angular/core/./bundles/core.umd.js:2965:21: Template parse warnings:
setViewControllers:animated: called on <UINavigationControllerImpl 0x7f9ef831e400> while an existing transition or presentation is occurring; the navigation stack will not be updated.
[Common] _BSMachError: port d007; (os/kern) invalid capability (0x14) "Unable to insert COPY_SEND"
[Common] _BSMachError: port d007; (os/kern) invalid name (0xf) "Unable to deallocate send right"
[Firebase/InstanceID][I-IID009001] Error removing keypair status: -34018
[Firebase/InstanceID][I-IID010007] Unable to remove RSA keypair
[Firebase/InstanceID][I-IID010003] Unable to generate keypair.
[Firebase/InstanceID][I-IID010009] Keypair could not be loaded from Keychain. Error: Error Domain=com.firebase.iid Code=-34018 "(null)"
[Firebase/Analytics][I-ACS020001] Failed to get InstanceID: Error Domain=com.firebase.iid Code=-34018 "(null)"
[Firebase/InstanceID][I-IID009001] Error removing keypair status: -34018
[Firebase/InstanceID][I-IID010007] Unable to remove RSA keypair
[Firebase/InstanceID][I-IID010003] Unable to generate keypair.
[Firebase/InstanceID][I-IID010009] Keypair could not be loaded from Keychain. Error: Error Domain=com.firebase.iid Code=-34018 "(null)"
[Firebase/Analytics][I-ACS020001] Failed to get InstanceID: Error Domain=com.firebase.iid Code=-34018 "(null)"
[Firebase/InstanceID][I-IID007004] Unable to save checkin info, resetting checkin preferences in memory.
[Firebase/InstanceID][I-IID009001] Error removing keypair status: -34018
[Firebase/InstanceID][I-IID010007] Unable to remove RSA keypair
[Firebase/InstanceID][I-IID010003] Unable to generate keypair.
[Firebase/InstanceID][I-IID010009] Keypair could not be loaded from Keychain. Error: Error Domain=com.firebase.iid Code=-34018 "(null)"
[Firebase/Analytics][I-ACS020001] Failed to get InstanceID: Error Domain=com.firebase.iid Code=-34018 "(null)"
[Firebase/InstanceID][I-IID009001] Error removing keypair status: -34018
[Firebase/InstanceID][I-IID010007] Unable to remove RSA keypair
[Firebase/InstanceID][I-IID010003] Unable to generate keypair.
[Firebase/InstanceID][I-IID010009] Keypair could not be loaded from Keychain. Error: Error Domain=com.firebase.iid Code=-34018 "(null)"
[Firebase/Analytics][I-ACS020001] Failed to get InstanceID: Error Domain=com.firebase.iid Code=-34018 "(null)"
[Firebase/InstanceID][I-IID007004] Unable to save checkin info, resetting checkin preferences in memory.
[Firebase/InstanceID][I-IID007004] Unable to save checkin info, resetting checkin preferences in memory.
[Firebase/InstanceID][I-IID003009] Failed to fetch default token Error Domain=com.firebase.iid Code=6 "(null)" UserInfo={NSUnderlyingError=0x608000e48b20 {Error Domain=com.google.iid Code=-34018 "(null)"}}
[Firebase/InstanceID][I-IID003007] Failed to retrieve the default GCM token after 5 retries
[Firebase/InstanceID][I-IID007004] Unable to save checkin info, resetting checkin preferences in memory.
[Firebase/InstanceID][I-IID007004] Unable to save checkin info, resetting checkin preferences in memory.
[Firebase/InstanceID][I-IID007004] Unable to save checkin info, resetting checkin preferences in memory.
[Firebase/InstanceID][I-IID007004] Unable to save checkin info, resetting checkin preferences in memory.
[Firebase/InstanceID][I-IID007004] Unable to save checkin info, resetting checkin preferences in memory.

**Comment by sarojrout** [comment]
i am able to resolve this by adding the app.entitlements file inside /App_Resources/IOS/

**Comment by sattasundar** [comment]
@sarojrout  can you mentioned what you have add?
