### ISSUE TITLE
A problem occurred configuring project ':app'.

### ISSUE THREAD

**Issue by torvicv** [EddyVerbruggen/nativescript-plugin-firebase#606]
Since I installed webpack, I follow the instructions for to update nativescript, I begin with a problem with nativescript-plugin-firebase and I go on with others problems, finally I got this error, 

A problem occurred configuring project ':app'.
> No match found

my package.json is this:

```
    "tns-android": {
      "version": "3.4.1"
    }
  },
  "dependencies": {
    "@angular/animations": "~5.0.0",
    "@angular/common": "~5.0.0",
    "@angular/compiler": "~5.0.0",
    "@angular/core": "~5.0.0",
    "@angular/forms": "~5.0.0",
    "@angular/http": "~5.0.0",
    "@angular/platform-browser": "~5.0.0",
    "@angular/platform-browser-dynamic": "~5.0.0",
    "@angular/router": "~5.0.0",
    "email-validator": "^1.1.1",
    "firebase-functions": "^0.7.5",
    "nativescript-angular": "^5.0.0",
    "nativescript-plugin-firebase": "^5.1.2",
    "nativescript-theme-core": "~1.0.2",
    "nativescript-xml2js": "^0.5.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "^5.5.0",
    "tns-core-modules": "^3.4.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~5.0.0",
    "@ngtools/webpack": "~1.8.2",
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "copy-webpack-plugin": "~4.0.1",
    "css-loader": "~0.28.7",
    "extract-text-webpack-plugin": "~3.0.0",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.6.0",
    "nativescript-dev-webpack": "^0.9.0",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.1.0",
    "typescript": "~2.4.2",
    "webpack": "~3.8.1",
    "webpack-bundle-analyzer": "^2.8.2",
    "webpack-sources": "~1.0.1"
  }
}
```
my build.gradle is this:

`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {

    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
        classpath 'com.google.gms:google-services:3.1.2'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}`

my project is with android.

Any body can help me?

**Comment by EddyVerbruggen** [comment]
I can't help you, sorry. "No match found" is not much to go by.. and the webpack Travis config in this repo build just fine.

**Comment by xaksis** [comment]
@torvicv I started having this issue due to a mismatch in gradle build and tool versions. I had to follow instructions to update nativescript and regenerate the android app to fix it. Make sure that the generated app has compatible versions of `com.android.tools.build:gradle` in dist/platforms/android/build.gradle  and `distributionUrl` in dist/platforms/android/gradle/gradle-wrapper.properties

**Comment by torvicv** [comment]
After I updated my application, I fixed it. The problem was same which xaksis. Thanks xaksis.

**Comment by campbellscript** [comment]
@torvicv I believe i am having a similar problem, did you just run npm update? what exactly did you update?

**Comment by torvicv** [comment]
you follow this link:

[https://docs.nativescript.org/releases/upgrade-instructions](url)

**Comment by torvicv** [comment]
you follow this link:

[https://docs.nativescript.org/releases/upgrade-instructions](url)

**Comment by pauly815** [comment]
Ran into this issue but not during an upgrade (I'm still using TNS 3.4.2).  Had to update my firebase after-prepare hook to use google service 3.1.1.  The "No match found" error was saying that during the build it couldn't find google services 3.1.2.  I'm not sure why this was the case cause I see the 3.1.2 jar in my local gradle repo and I have Google Repo support in Android Studio.
