### ISSUE TITLE
Firestore calls keep throwing exceptions in onFailureListener

### ISSUE THREAD

**Issue by bearoutthere** [EddyVerbruggen/nativescript-plugin-firebase#608]
I'm trying to get Firestore connected to the NativeScript/TypeScript app with plugin version 5.1.1

I followed the example.  The calling function in a xxxx-view-model.ts 

```
public loadNationalities(): void {
        const countryNamesDocument = firebase.firestore.collection("Countries").doc("testCountry");
        console.log("got doc - " + countryNamesDocument.id);
        countryNamesDocument.delete().then(() => {
           console.log("testCountry deleted");
       });
    }
```

When i step through debug the initial call gets the document just fine and outputs its id to the console.  But then i get exception in firebase.android.js  at line 2094: 

```
var onFailureListener = new com.google.android.gms.tasks.OnFailureListener({
                onFailure: function (exception) { return reject(exception.getMessage()); }
            });
```

Same happens when i try to update the document which exist and has a test field that i'm trying to update.
Do i need to setup some extra listeners?  I didn't see anything of the sort in the examples.
Any help would be greatly appreciated.

**Comment by EddyVerbruggen** [comment]
Is `onFailureListener` called when you delete the document? What's the error in the rejected promise? And is the document deleted or not?

Your usage seems fine to me btw.

**Comment by bearoutthere** [comment]
Both when i update and delete and neither complete the operation.  So the document is neither updated nor deleted.  The debugger is not showing the actual error message.  Just the object properties.

**Comment by bearoutthere** [comment]
i also tried to get the document's data but nothing came back either.

**Comment by bearoutthere** [comment]
oh,  the message is "PERMISSION_DENIED: Missing or insufficient permissions."

**Comment by EddyVerbruggen** [comment]
Ah, you'll need to fix that in the Firebase console.

**Comment by bearoutthere** [comment]
indeed.  should have looked at that first.  many apologies.

**Comment by EddyVerbruggen** [comment]
No worries at all, thanks for reporting back.
