### ISSUE TITLE
Offline capabilities for Firebase database

### ISSUE THREAD

**Issue by jlooper** [EddyVerbruggen/nativescript-plugin-firebase#61]
According to the Firebase docs, you can set up Offline capabilities for your database like thus: https://firebase.google.com/docs/database/web/offline-capabilities 
https://firebase.google.com/docs/database/android/offline-capabilities

We already have the ability to set the Persistence (setPersistenceEnabled) I believe; we just would need to use the keepSynched flag and handle data sync on the client side. A nice enhancement!

thanks!
Jen

**Comment by EddyVerbruggen** [comment]
That sounds sweet. `setPersistenceEnabled` is a global property though and this one is for a specific branch (which can be the root of course, lol). So it's a bit more work but compared to Facebook auth and push notifications it's a walk in the park 🌲 🌳

**Comment by EddyVerbruggen** [comment]
Version 3.4.1 of this plugin added [`keepInSync`](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/DATABASE.md#keepinsync).

It's a bit hard to demo this feature but I'm sure you'll find a good usecase for it.

**Comment by jlooper** [comment]
Looks super useful! Look @tjvantoll, offline sync!

**Comment by ChirantanPatel** [comment]
hi @EddyVerbruggen  how can Sync data offline and online both?   

  firebase.init({
            //persist: false   //working on online database
            persist: true   //working on offline database
        }).then((instance) => {
            console.log("FireBase init Done!")
        }, (error) => {
            console.log("FireBase Error" + error);
        });

 when I set persist  = true;  then offline data working good but when I connect to internet then not sync online database. only getting offline data. so how to resolve this.
