### ISSUE TITLE
Nativescript 3.4 and angular 5 - support

### ISSUE THREAD

**Issue by giorgiopiatti** [EddyVerbruggen/nativescript-plugin-firebase#612]
For the past days, I've was thinking that this can be achieved adding timeOut when initializing Firebase as mention in issue #588, but it was wrong.
I've open this new issue to address this problematic, in which I will explain me better. 

Using the plugin as always with `firebase.init`, return nothing, no error, no promise callback. Simply the plugin isn't initialized.

Putting the  initialization function into a timeout:
`setTimeout(()=>{ firebase.init(()=>{...}) },1000)`

Something seems to work, authentication is working fine (login, auth callback, ...). 
Also retrieving data from the real-time DB works, 
but when I try to update a value something goes wrong:
`JS: Unhandled Promise rejection: Reload failed com.google.firebase.FirebaseNetworkException: A network error (such as timeout, interrupted connection or unreachable host) has occurred. ; Zone: <root> ; Task:  ; Value: Reload failed com.google.firebase.FirebaseNetworkException: A network error (such as timeout, interrupted connection or unreachable host) has occurred.`

These problems are related to the following versions:
`angular: ^5.0.0;
nativescript: 3.4;
nativescript-angular: ^5.0.0  ;
tns-core-modules: 3.4;
tns-android: 3.4`

I think that it can be related to some conflict and/or changes in nativescript-angular.

Note: I've cannot test it on iOs

**Comment by EddyVerbruggen** [comment]
Thank you. See #613.
