### ISSUE TITLE
Firestore - how to configure Firestore end-points at run-time

### ISSUE THREAD

**Issue by marcellodalessio** [EddyVerbruggen/nativescript-plugin-firebase#614]
I have developed an Android APP based on Firestore for DB storing data.

Now I need that the user is able to configure on the APP at run-time the end-point of Firestore DB - these parameters are typically stored in google-services.json (firebase_url, project_id, storage_bucket)

How can these values be changed at run time? 
Is there a specific Android API to do this?

Thanks in advance for any suggestion/support on this matter :)

**Comment by EddyVerbruggen** [comment]
You may want to look at the Firebase docs first.

**Comment by marcellodalessio** [comment]
I took a look without success - I'll try to post a question. Thanks

**Comment by EddyVerbruggen** [comment]
OK, please reopen if there's any positive news 👍
