### ISSUE TITLE
Facebook login Error

### ISSUE THREAD

**Issue by rafusfx** [EddyVerbruggen/nativescript-plugin-firebase#616]
Hi all.
I'm trying to do a facebook login with this plugin. But I'm getting this error: 

**Error in firebase.login: TypeError: Cannot read property 'getInstance' of undefined**

I've the latest version of everything about nativescript included this plugin.

This is the code I'm using, nothing fancy:

               `firebase.login({
			type: firebase.LoginType.FACEBOOK,
			facebookOptions: {
			 scope: ['public_profile', 'email']
			}
		  }).then(
			  function (result) {
				JSON.stringify(result);
			  },
			  function (errorMessage) {
				console.log("fuck: "+ errorMessage);
			  }
		  );`

I just can't find where the proplem is..
Thaks in advance for your help.

**Comment by EddyVerbruggen** [comment]
Hi, the embedded [demo app](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/tree/master/demo) has a working Facebook login. Please consult that.
