### ISSUE TITLE
DynamicLinks stop working if app contains delegate overrides

### ISSUE THREAD

**Issue by manijak** [EddyVerbruggen/nativescript-plugin-firebase#620]
I'm testing the DynamicLinks for iOS. I managed to get it working (with callbacks and the whole package), but only if I remove the ios app-delegate overrides in app.ts. 

For instance, in my app.ts I had this (includes init for google-analytics and more):
```ts
class AppDelegate extends UIResponder implements UIApplicationDelegate {
        public static ObjCProtocols = [UIApplicationDelegate];
        applicationDidFinishLaunchingWithOptions(application: UIApplication, launchOptions: any): boolean {     
            ...
            return true;
        }
    }
    application.ios.delegate = AppDelegate;
```

Having this the callbacks from Firebase plugin are ignored. Removing the above code, causes the callbacks to work again. 

Any tips on how I can both working normally?

Edit: Notifications work with or without the above code. 

Edit 2: The `firebase.ini()` must be declared in the app.ts for the callback to be hit...

**Comment by manijak** [comment]
Ok I seem to got it working. Had to remove the way I overrode the AppDelegate functions, and replace it with this, think this is more proper:
```ts
application.on(application.launchEvent, function (args) {
          ...
    });
```

Still have to init Firebase in the main app.ts file (that is ok). The rest of callback binding happens on the main view (`main-view.ts`). 

This change made it possible for me to:
- Receive DynamicLinks via callback if the app is both in background or suspended mode!
- Receive Notification data-payload via callback when the app is in both foreground and background mode!

Only missing feature is fetching notification data when the app is in suspended mode.

**Comment by manijak** [comment]
DynamicLinks for Android do not work. The `launchIntent` is always null.

**Comment by benlooi** [comment]
Hi Manijak,
Can you share your main.ts? Or advise me how to solve this? I seem to be having a similar issue as my Braintree plugin requires me to write some AppDelegate code in my main.ts and it is preventing FIrebase facebook login from returning to the app .
My main.ts code:
`import { platformNativeScriptDynamic } from "nativescript-angular/platform";

import { AppModule } from "./app/app.module";
import * as app from "application";
//import firebase=require("nativescript-plugin-firebase");
require("nativescript-plugin-firebase");
declare var UIResponder, UIApplicationDelegate, BTAppSwitch;

if (app.ios) {
 
    class MyDelegate extends UIResponder {

        public static ObjCProtocols = [UIApplicationDelegate];

        applicationDidFinishLaunchingWithOptions(application, launchOptions): boolean {

            try {
                BTAppSwitch.setReturnURLScheme("co.pompipi.app2018.payments"); // should be same as CFBundleURLSchemes value.
                return true;
            } catch (error) {
                console.log(error);
            }
            return false;
        }

        applicationOpenURLSourceApplicationAnnotation(application, url, sourceApplication, annotation) {

            try {
                if (url.scheme == "co.pompipi.app2018.payments") {
                    BTAppSwitch.handleOpenURLSourceApplication(url, sourceApplication);
                    return true;
                }
            } catch (error) {
                console.log(error);
            }
            return false;
        }
    }
    
    app.ios.delegate = MyDelegate;
}
platformNativeScriptDynamic().bootstrapModule(AppModule);`
