### ISSUE TITLE
Get push key avoiding .then()

### ISSUE THREAD

**Issue by alesmit** [EddyVerbruggen/nativescript-plugin-firebase#624]
Is it possible to have the `key` of a reference before pushing it?

Just actually what [angularfire2](https://github.com/angular/angularfire2/blob/master/src/database/database.ts#L31) does with `createPushId()`.

**Comment by andrewexton373** [comment]
I believe you'd have to generate the id first, then rely on:

```
let pushId = generatedId();
CollectionRef.set(pushId).then(()=>{});
```

I'm not sure how you would deal with conflicts due to duplicate id generation, other than performing a check to see if a Document exists for your generated id beforehand.

**Comment by alesmit** [comment]
I thought I could use the firebase UID just because I don't want to check for an existing one before.
angularfire2 provides a firebase UID synchronously, so avoiding the use `.then()` in order to get it.
In some scenarios this is very helpful as code will look more readable.

**Comment by EddyVerbruggen** [comment]
Hi, I did some research today and found that Angularfire2 depends on the Firebase JS API to generate an ID clientside. I've recreated this in the NativeScript plugin, so with version 5.1.7 you do thing like [this example](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/c5831199628bcebe7766c8888f2350be63537d6d/demo/app/main-view-model.ts#L247).
