### ISSUE TITLE
Firebase storage methods not reacting

### ISSUE THREAD

**Issue by fmu93** [EddyVerbruggen/nativescript-plugin-firebase#628]
I have tried copying all demos and templates to my project, it's just not reacting... only I see up to the last console.log() before the firebase.uploadFile(), and nothing ever happens at the firebase end. 
Same thing happens with downloading file or url. Init and authentication work, storageBucket included within firebase.init(). I'm using typescript without Angular.

I am getting a bit desperate since there aren't even errors. What am I doing wrong?

> 
	
       import firebase = require("nativescript-plugin-firebase");
       
       export class BackendService {
        // auth stuff...
       
        static uploadFile(remoteFullPath: string, localPath: string): Promise<any> {
		const appPath = fs.knownFolders.currentApp();
		const localFullPath = fs.path.join(appPath.path, localPath);
		if (!fs.File.exists(localFullPath)) {
			console.log("File does not exist");
			return null
		}
		console.log("localFullPath: " + localFullPath);
		
		return firebase.uploadFile({
			remoteFullPath,
			localFullPath,
			onProgress: status => {
				console.log("Uploaded fraction: " + status.fractionCompleted);
				console.log("Percentage complete: " + status.percentageCompleted);
			}	
		}).then((uploadedFile) => {
				console.log("File uploaded: " + JSON.stringify(uploadedFile));
				return uploadedFile
		},
		(error) => {
			console.log("File upload error: " + error);
		});
	    }
        }

That method is to be called when pressing a button:

> 

    export function imgUpload() {
        const localPath = "/res/pengbrew.png";
        BackendService.uploadFile("test.png", localPath);
    }

My project dependencies are (only running it on Android):

> 

    "dependencies": {
    "email-validator": "1.1.1",
    "nativescript-imagepicker": "4.0.1",
    "nativescript-localstorage": "1.1.5",
    "nativescript-plugin-firebase": "5.1.7",
    "nativescript-pro-ui": "3.4.0",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-toast": "1.4.6",
    "tns-core-modules": "~3.4.0"
     },

**Comment by EddyVerbruggen** [comment]
Did you try the demo (it has upload and download as well)?

**Comment by fmu93** [comment]
Hi Eddy, 
Thanks for the reply and the awesome job of creating this plugin. 

I just tested the demo, it works as expected. I can see in the console " Uploaded fraction: 1 (100%) "
Maybe my problem is on the firebase side? The storage service is enabled (uncommented) in the gradle and settings.

**Comment by fmu93** [comment]
It was just an issue with the storage bucket! Silly me!
