### ISSUE TITLE
 Can't find variable: FIRApp

### ISSUE THREAD

**Issue by yogeshwar607** [EddyVerbruggen/nativescript-plugin-firebase#63]
getting following error : firebase.js:287:18: Error in firebase.init: ReferenceError: Can't find variable: FIRApp
<img width="1056" alt="screen shot 2016-06-29 at 2 54 14 am" src="https://cloud.githubusercontent.com/assets/10059011/16433378/8fb75f64-3da7-11e6-8181-ca82dc6d93c7.png">

Also getting error : ReferenceError: Can't find variable: FIRAuth
Note: tns --version
2.0.1

**Comment by EddyVerbruggen** [comment]
Did you download `GoogleService-Info.plist` and add it to `app/App_Resources/iOS/`? See https://firebase.google.com/support/guides/firebase-ios

**Comment by yogeshwar607** [comment]
Yes , i have included GooglrService-Info.plist file

**Comment by EddyVerbruggen** [comment]
Please share your project with me so I can debug it.

**Comment by yogeshwar607** [comment]
I can't access my machine now but will share it after 3 hours

**Comment by EddyVerbruggen** [comment]
No hurry, thanks!

**Comment by yogeshwar607** [comment]
Solved issue by removing platform ios and adding it again .
Thanx for ur effort and time.

**Comment by EddyVerbruggen** [comment]
@chillyprig can you please retry with the latest (3.5.0) version of this plugin?

**Comment by yoojene** [comment]
Hi @EddyVerbruggen I know this has been closed but I'm still getting the same error setting up on my demo app with the latest plugin

`Sep  1 12:53:03 ip-172-16-1-25 nsexerciseDaily[46170]: CONSOLE LOG file:///app/tns_modules/nativescript-plugin-firebase/firebase.js:372:18: Error in firebase.init: ReferenceError: Can't find variable: FIRApp`

Followed the setup instructions and downloaded the GoogleService-Info.plist file to App_Resources/iOS

versions:
 nativescript-plugin-firebase │ ^3.5.4 

$ tns --version
2.2.1

**Comment by EddyVerbruggen** [comment]
@yoojene How are you starting the app, and on which device / simulator?

**Comment by EddyVerbruggen** [comment]
@yoojene Oh, and does this "hack" work for you as well? #76

**Comment by yoojene** [comment]
Using the iOS emulator ( tns run ios --emulator --watch) whcih is loading up a 9.3 instance.  I just found that hack but no didn't work, I'm not trying anything wrt auth or storage - seems to fail straight away firebase.init

I don't have to declare FIRApp somewhere as a constant do I?  Similar to the URL in the web app version?

**Comment by EddyVerbruggen** [comment]
Do you have [this](https://github.com/EddyVerbruggen/nativescript-plugin-firebase#start-up-wiring)?

**Comment by yoojene** [comment]
Yep - this is my app.ts

The page loads but with the error above 

`import application = require("application");
import firebase = require("nativescript-plugin-firebase");

firebase.init({

  // Optionally pass in properties for database, authentication and cloud messaging,
  // see their respective docs.

}).then(
  (instance) => {
    console.log("firebase.init done");
  },
  (error) => {
    console.log("firebase.init error: " + error);
  }
);

application.start({ moduleName: "views/login/login" });
`

**Comment by EddyVerbruggen** [comment]
Looks legit. Can you try `tns emulate ios` (without the watch, or livesync features) and see if that helps? If not remove and readd your iOS platform as well.

**Comment by yoojene** [comment]
Hmm OK that worked fine, then when I've retried the previous command, it worked too!   thanks for the help man.

**Comment by phil-fuber** [comment]
@EddyVerbruggen hi Eddy sadly i have also encountered this issue and it is preventing me from continuing my Firebase integration. I am using tns version 2.2. I have thoroughly checked the code and tried all the fixes and other suggestions here and in the other related issue.
