### ISSUE TITLE
I ran into a problem with FCM Report 501

### ISSUE THREAD

**Issue by ZhengXueNing** [EddyVerbruggen/nativescript-plugin-firebase#640]
When I started the FCM, I did not encounter any problems. APNS also works.
Below is the FCM Log：

4.9.0 - [Firebase/Crash][I-CRA000004] Successfully initialized

4.9.0 - [Firebase/Messaging][I-FCM001000] FIRMessaging Remote Notifi
cations proxy enabled, will swizzle remote notification receiver handlers. If you'd prefer to manually integrate Firebase Messaging, add "FirebaseAppDelegateProxyEnabled" to your Info.plist, and set it to NO. Follow the instructions at:
https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in_firebase_messaging
to ensure proper integration.

4.9.0 - [Firebase/Analytics][I-ACS023007] Firebase Analytics v.40009000 started

4.9.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)

But when I send a message:
![image](https://user-images.githubusercontent.com/13215544/36961999-b3bd93c2-2088-11e8-8769-956c6ad8d7ba.png)

![image](https://user-images.githubusercontent.com/13215544/36962049-e3d60710-2088-11e8-93e8-f4b70343eb11.png)

![982eba70-c2bf-4a01-9e29-c4a667682747](https://user-images.githubusercontent.com/13215544/36962538-f7787c38-208a-11e8-99ac-0dd6af82e62c.png)

Can you help me?

**Comment by EddyVerbruggen** [comment]
I'm not sure what the issue is and why I'm looking at ObjC code?

**Comment by ZhengXueNing** [comment]
Yes, our project is written in Objective-C
Mainly when I sendmassage, most of the time is reported 501, and sometimes able to send the correct.

**Comment by EddyVerbruggen** [comment]
If your project is written in ObjC, then what's the relevance to NativeScript (this repo)?

**Comment by ZhengXueNing** [comment]
Oh, I'm sorry, I asked the wrong place

**Comment by EddyVerbruggen** [comment]
No worries 😉
Good luck!

**Comment by ZhengXueNing** [comment]
Feel Google is full of hate for our iOS developers

**Comment by EddyVerbruggen** [comment]
Here's something to cheer you up: ❤️💪
