### ISSUE TITLE
Will this plugin plan to split into several sub plugins by functional base?

### ISSUE THREAD

**Issue by kelvinliuhk** [EddyVerbruggen/nativescript-plugin-firebase#645]
Your plugin is great. This is not a bug report. 
I have a question, will this plugin plan to split into several plugins by functional base? 
Just like nativescript-pro-ui split to nativescript-ui-listview, nativescript-ui-calendar , etc.

Because I using AOT compile, want to make the vendor.js lib as small as possible.  

Thank you for attention.

**Comment by EddyVerbruggen** [comment]
This will remain a monorepo, but much like how I'm making sure no native libraries are included for modules you don't want/need, I'm thinking of ways to do that with the JS/TS files as well.
