### ISSUE TITLE
NO Background Notifications on iOS - notifications are submitted on App-Start

### ISSUE THREAD

**Issue by Lacos247** [EddyVerbruggen/nativescript-plugin-firebase#651]
Hi @EddyVerbruggen ,

having big trouble with this plugin regarding push notifications. It is really really frustrating so far and i really hate NativeScript right now. It is not possible with this plugin to receive (data) notifications when the app is in background? Any help would be appreciated. 

- remote notifications are activated in xcode
- Plugin Version 5.1.8
- (Data)Notifications are incoming if the app is in foreground

- If the app is in background, the notifications seem to be processed by iOS but are received in the app only if the app is started (foreground), this is logged in XCode Debug Console:

2018-03-23 13:25:34.156341+0100 MyApp[14310:11690264] Warning: Application delegate received call to -application:didReceiveRemoteNotification:fetchCompletionHandler: but the completion handler was never called.

What is wrong. Please help.

BR Lacos

**Comment by EddyVerbruggen** [comment]
I'm not entirely sure this is the best way to report an issue on my OSS repo. And without sharing your project it's impossible to say anything useful.

**Comment by joseandrespr** [comment]
Have you looked at this
## What if iOS doesn't receive notifications in the background?
Make sure you [`require` the plugin in `app.ts`]
*before* `application.start()`, and do `init()` *after* the app has started (not in `app.ts` - not even in a timeout; move it out of `app.ts` entirely!).

> Make sure to use `require`, *not* `import` in `app.ts` because TSC will remove the import in case you're not using it.

**Comment by Lacos247** [comment]
Hi, 

I have done that. I think it is a general problem with this plugin oder implementation. 
I have checked out your demo app @EddyVerbruggen an this app behaves the same.
The push-notifications (data only) are processed by the app on startup - not in background mode.

What is wrong? I have written a demo in Objective C (based on the Demo Code from Firebase) and that is running as desired - with background notifications.

The intention was to save time with Nativescript while developing for both platforms. But it seems quite to be the contrary :/

Here a push notification send by curl, for example:

`{  
   "to":"<token>",
    "priority": "high",
    "content_available": true,
    "data":{  
      "title":"mytitle",
      "body":"mybody",
      "url":"myurl"
   }
}
`

Any help would be very appreciated.

BR,
Lacos

**Comment by EddyVerbruggen** [comment]
Please stop complaining and start being constructive. Again, share your project if you want any remotely helpful reply by me on this subject.

**Comment by Lacos247** [comment]
Hi @EddyVerbruggen , sorry for complaining but it is very frustrating so far. 
I can't post the sources since it is a commercial app. I can try to strip down that and email you, for example. 

The same problem occured if I tried your demo app. Are you sure that background notifications on ios are supported by the implementation in general?

BR,
Lacos

**Comment by EddyVerbruggen** [comment]
@Lacos247 I understand it's frustrating but it's of no use repeatedly telling me. Please just focus that energy towards finding a solution.

Of course it works for me, and I've helped *many* others getting it to work and it's always either a problem with their project setup or the way they are sending notifications.

If the demo app doesn't work then make sure you're using the curl command I added to the readme.

**Comment by Lacos247** [comment]
@EddyVerbruggen 
Yes you are right with the energy - sorry.
I have build your demo app and connected to my ios dev account. 
The curl commands work, if the app is in foreground. If the app is in background only the commands work which include the messages-block, but this way it is not supposed to work. The data-message only commands do not work but they are passed instantly if the app is started again.

In my opinion the app should be able to process/edit the message and show it (with your local notifications plugin), for example on their own. Is that plugin supporting that? 

BTW: On Android everything ist fine and works ad desired.

BR,
Lacos

**Comment by Lacos247** [comment]
Hi @EddyVerbruggen ,

I have send you an email with the small project attached. I hope you can help me and find my mistake.

BR,
Lacos

**Comment by Lacos247** [comment]
Hi Jen,

many thanks for the information. I will try that. 

BR,
Lacos

**Comment by Lacos247** [comment]
Hi all,

the demo app from Eddy seems to work (at least with the 5.2.0 plugin Version). I got it running and got background notifications on iOS.
What not works for me right now is a NativeScript-Angular-App with the push notification plugin. 
If the app is in foreground, everything works fine. If the app is in background, the callback is not triggered.

In my opinion I have followed your best practices:
- require in main.ts
- Firebase-Init in app.component.ts (ng-on-init method) 

My test messages (works with Eddys Demo above):
curl -X POST --header "Authorization: key=<AUTH-KEY>" --Header "Content-Type: application/json" https://fcm.googleapis.com/fcm/send -d "{\"data\":{\"foo\":\"bar\"}, \"priority\": \"High\", \"content_available\":true, \"to\": \"<DEVICE-TOKEN>\"}"
 

@EddyVerbruggen 
I have send you a demo. It would be great if you could look at it and give some tips. What ist wrong?

BR,
Lacos

**Comment by tangjh** [comment]
Any updates on success?  I'm also facing no background notification for ns angular project.

**Comment by bniehuser** [comment]
Also having this problem; NS/Angular/Typescript using nativescript-plugin-firebase.  as shown in the demo app, i am adding the appropriate "require()" in both main.ts and main.aot.ts, as well as using the ngOnInit() for my app.component.ts to run the firebase.init().   Android receives messages both foreground and background, with background appropriately generating system notices.  iOS 11 on iPhone X receives the messages both foreground and background, but does not generate system notifications in background -- neither on-screen notification or entries in the notification center.

has anyone found a solution/gotcha for this?

**Comment by EddyVerbruggen** [comment]
@bniehuser It's not very clear to me what you're missing exactly. Mind doing a PR?

**Comment by bniehuser** [comment]
sorry eddy, had nothing to do with your wonderful code... was missing the cert chain (.p8 file) in the firebase config, which strangely still allows the app to receive messages directly but does not allow the actual iOS notifications.  figured this could be added to an faq or something for noobs like me who missed this step so they don't complain to you for their own oversight ;)

**Comment by csaggo** [comment]
@bniehuser Hi, can i ask you a question. i have the same background - issue (system-notification not displayed) on iphone x. But ONLY iPhone X other iPhones work fine.
Was that the same for you and regenerating the cert-files like described helped. Or did it not work on any iPhone?
