### ISSUE TITLE
LimitToLast is not a function

### ISSUE THREAD

**Issue by joseandrespr** [EddyVerbruggen/nativescript-plugin-firebase#652]
When using Real Time Database and I add limitToLast to my child_added event I get an undefined error:

ERROR TypeError: _this._messageRef.child(channelId).orderByChild('message').limitToLast is not a function

this._messageRef.child(channelId).orderByChild('message').limitToLast(5).on('child_added', function(snapshot) {
                self.ngZone.run(() => {
                  let results = self.handleChatSnapshot(snapshot.val());
                   observer.next(results);
                });
            });

Is this feature not supported?

**Comment by EddyVerbruggen** [comment]
Where in the docs did you find it is? A PR is of course more than welcome.

**Comment by joseandrespr** [comment]
I did not see it in the docs and was just giving it a try.  I have never worked on a Nativescript plugin before but would love to help to add to this great plugin.  Let me do my homework to see how to go about doing that.  Is there a prefered way to contact you if I have any questions and is it ok to contact you?

**Comment by joseandrespr** [comment]
Nevermind, I see that there is a conversation section in the pull request, I will go through there, I will close this issue thanks.
