### ISSUE TITLE
firebase and background service (only android)

### ISSUE THREAD

**Issue by marcossaore** [EddyVerbruggen/nativescript-plugin-firebase#654]
Hi Everyone!!!
I want to send the location in background mode using firebase, is this possible?

**Comment by EddyVerbruggen** [comment]
The location? What do you mean exactly?

**Comment by marcossaore** [comment]
My app is very similar to uber, what I want to do is to send the location to the whole server caused the nativescript-geolocation plugin to change the location, however when I close the application this process terminates even using background service.
Before I was implementing this functionality with server node with socket.io, then every time I closed the application I started the background service by establishing a two-way connection.
I'm new to firebase and do something similar to what was done before by the app.

**Comment by EddyVerbruggen** [comment]
Sending data to Firebase is what you can use this plugin for, but making a background geolocation service is of course out of scope of this plugin. So you'll need to look for a plugin that supports background geolocation I guess.
