### ISSUE TITLE
Firebase Google auth all user info

### ISSUE THREAD

**Issue by PraktikerNeosoft** [EddyVerbruggen/nativescript-plugin-firebase#656]
Can Anybody help me how can I get User nicname gender and more info from user when I login with this plugin?

```
I only get:
"uid": "",
"name": ,
"email": ,
"emailVerified": 
"providers": [
 {
"id": "firebase"
 },
{
"id": "google.com"
}
],
"anonymous": 
"isAnonymous": 
"phoneNumber":
"profileImageURL":
```

**Comment by EddyVerbruggen** [comment]
Hi, this is what's returned from Google sign in, when using the demo:

![simulator screen shot - iphone x - 2018-04-02 at 20 10 34](https://user-images.githubusercontent.com/1426370/38208605-eb0a2482-36b1-11e8-9019-cdb0257ecabe.png)

AFAIK Firebase doesn't support returning properties like gender, so you'll need to call the approriate Google API's yourself. You can prove me wrong by pointing at the Firebase SDK showing how to do it.
