### ISSUE TITLE
Notification Icon not showing on Oreo devices (Android)

### ISSUE THREAD

**Issue by NickIliev** [EddyVerbruggen/nativescript-plugin-firebase#660]
Using[ this basic application](https://github.com/NickIliev/NS-Issues-2018/tree/master/others/t_1152076) the notification icon does not appear on Samsung S8 device.
It appears as expected on Nexus 5xx and Nexus 5, HTC and Lenovo devices.

I've used Firebase console and Postman to send notifications, 
The notifications are received - just the icon is not shown.

**Comment by NickIliev** [comment]
Possibly related to [the update of Google Play Services to 12.0.0+ ](https://firebase.google.com/support/release-notes/android#20180320)(and the reason why this happens only on devices with Oreo as the update of GPS is forced on such devices)

> FIXED Fixed a regression that caused custom notification icons to be rejected on Android 8.0.

**Comment by NickIliev** [comment]
Update: after updating the dependency of Google Play Services in [push-plugin](https://github.com/NativeScript/push-plugin/tree/master/src) the issue was resolved

**Comment by EddyVerbruggen** [comment]
Hey @NickIliev thanks for the heads up, I'll bump this plugin to 12.0.1 as soon as possible 👍
