### ISSUE TITLE
[iOS] FIRDocumentReference.onSnapshot always exists

### ISSUE THREAD

**Issue by vcooley** [EddyVerbruggen/nativescript-plugin-firebase#661]
There is an error in the `FIRDocumentReference.onSnapshot` callback which sets `DocumentSnapshot.exists` to `true` even if the document does not exist. After investigation, it looks like the `DocumentSnapshot.data` method is trying to coerce a null value improperly when invoked.

**Comment by EddyVerbruggen** [comment]
Thanks for the PR!
