### ISSUE TITLE
Batch and Transaction Operation in FireStore

### ISSUE THREAD

**Issue by rajatraj733** [EddyVerbruggen/nativescript-plugin-firebase#667]
Firestore supports Batch and Transaction Operation api. The same can be found here [https://firebase.google.com/docs/firestore/manage-data/transactions](https://firebase.google.com/docs/firestore/manage-data/transactions). But the current plugin does not support this api. Please look into this.

**Comment by EddyVerbruggen** [comment]
Yep, that's not supported yet. Are you up for a PR?

**Comment by rajatraj733** [comment]
I'm a rookie. I'll need understanding of nativescript. Nevertheless, I'm up for it. Could you just guide me how to contribute?

**Comment by EddyVerbruggen** [comment]
That would be great!

You can press the 'Fork' button at the top right, and clone the repo locally. The (preferably) switch to a new branch). Once done you push everything to your fork's GitHub repo and press the 'Pull Request' button to request merging it to this (upstream) repo.

The first rule of any PR is: keep it focused; make sure you're only doing 1 thing and not fi also refactor everything (that could be a separate Pull Request).

As for the actual content of the PR, you probably want to look at [this doc](https://firebase.google.com/docs/firestore/manage-data/transactions) (for iOS in this case).

To run the plugin and demo app locally you can `cd src` and `npm run demo.ios`.

**Comment by rajatraj733** [comment]
Thanks for your input. Forking the repo. Will post here, if I get stuck.

**Comment by nuvoPoint** [comment]
Any news on batch and transactions implementation?

**Comment by nuvoPoint** [comment]
Hey @EddyVerbruggen, welcome back from vacation!

We are about to start converting our existing cordova app to nativescript, but need to have transaction and batch support in your plugin.

Can you give us a timeframe?

**Comment by rajatraj733** [comment]
Apology guys!

I could not contribute.

**Comment by larssn** [comment]
@EddyVerbruggen Alrighty :-)

We're planning on expanding our horizons into Nativescript beginning next year, by converting our pretty big Cordova app to Nativescript. We're mostly annoyed with webview quirks, and the inefficient indexeddb layer in said webviews.

**Comment by EddyVerbruggen** [comment]
I've just finished support for Firebase "batched writes", see the docs here: https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/FIRESTORE.md#batch

The API is 100% compatible with the Web API you can find [here, in the Firebase docs](https://firebase.google.com/docs/firestore/manage-data/transactions) (scroll down to "Batched Writes" and select the "Web" tab).

I've also been working on `runTransaction` (see "Updating data with transactions" in the aforementioned Firebase doc). On iOS this works perfectly fine, but on Android I ran into a nasty threading issue I wasn't able to solve (yet).

Luckily most of the transaction features are covered by batch. But I will take another look before closing this issue.

Available with 6.5.0, which will be released later this month.

**Comment by EddyVerbruggen** [comment]
I tried standing on my head and every other trick to get "Transacional Updates" working on Android, but I give up. You can use it on iOS (see the docs), but for a x-plat solution use "Batched Writes" as mentioned above.

**Comment by larssn** [comment]
What problems are you seeing? Asking in case I decide to dive into it :-)

**Comment by EddyVerbruggen** [comment]
See the commented runTransaction code in src/firebase.android.ts. 

It wants to not run on the main thread.

**Comment by larssn** [comment]
Have you tried using workers? From the sound of it, they don't run on the UI thread. Could be wrong, the docs are unclear about that.

**Comment by EddyVerbruggen** [comment]
@larssn  Absolutely, but workers only allow sending plain JS objects back and forth, and this implementation requires sending native objects. I even implemented entirely in native Java, but still, that native code needs to call back to JS while it's running, forcing it to go back to the main thread.

**Comment by KkevinLi** [comment]
Going to take a stab at this. I wrote some java code and wanted to put that into the src directory, but when I put it in `src/platforms/android/java/com/tns/test.java` it fails to build with `Could not get unknown property 'supportVersion' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.` 

If I wanted to have native Java code, where should I put it so I can access it from firebase.android.ts?

I am also curious as to what you have already tried so that I do not redo the same thing.
