### ISSUE TITLE
Nativescript Vue Install Fails

### ISSUE THREAD

**Issue by PythonDevOp** [EddyVerbruggen/nativescript-plugin-firebase#672]
Hello,

I am using GenyMotion 2.10 for emulation, with the latest version of NodeJS, nativescript and the nativescript vue cli template found [here](https://nativescript-vue.org/en/docs/getting-started/quick-start/)

I installed nativescript firebase using `npm install nativescript-plugin-firebase` (based on [this](https://nativescript-vue.org/en/docs/getting-started/nativescript-plugins/)), and ran an `npm run clean` after that. I copied the `firebase.nativescript.json` file to the `template` directory, and copied the `google-services.json` file and `GoogleService-Info.plist` to the appropriate folders in `template/app/resources`.

Everything seems to build properly when running `npm run watch:android`. However, once the app is installed on my virtual emulator, I get an error found in the [pastebin](https://pastebin.com/cZQ5LSH3) which is similar to issue [649](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/649), but I saw that the `hooks` folder was populated with before and after hooks.

My repo is here: https://github.com/PythonDevOp/vuens

Any help is greatly appreciated!

**Comment by EddyVerbruggen** [comment]
See my last comment in #701.
