### ISSUE TITLE
firebase Child/Value EventListeners

### ISSUE THREAD

**Issue by usmanakram1996** [EddyVerbruggen/nativescript-plugin-firebase#674]
Please help in solving it.
I need to update the values in my nativescript component view without any pull-to-refresh method when a child value is changed in firebase database console using valueListener but I am unable to figure out how to accomplish this task.

**Comment by EddyVerbruggen** [comment]
Please see the demo apps in this repo.

**Comment by usmanakram1996** [comment]
Thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
