### ISSUE TITLE
Crash logs are not appearing for android in google firebase console

### ISSUE THREAD

**Issue by slsumathi** [EddyVerbruggen/nativescript-plugin-firebase#676]
I am using nativescript-plugin-firebase. I did all the configuration needed and created an app in google firebase console. I am able to see the number of users of my app.

I don't see any crash logs appearing on console. Can some one help me out if I am missing anything ?

**Comment by EddyVerbruggen** [comment]
Please update to 5.3.0, which now supports Crashlytics. See the docs for details.
