### ISSUE TITLE
Vue: App Crashes On Import 

### ISSUE THREAD

**Issue by banunn** [EddyVerbruggen/nativescript-plugin-firebase#681]
```
import Vue from 'nativescript-vue';
import router from './router';
import store from './store';

const firebase = require("nativescript-plugin-firebase");

import './styles.scss';

// Uncommment the following to see NativeScript-Vue output logs
Vue.config.silent = false;

new Vue({
  router,
  store,
}).$start();
```
I cannot get any further than simply importing the plugin within the main.js of the Vue-webpack-cli.  Once the plugin is imported, the app crashes with no logged error.    ( the app is otherwise completely vanilla and blank with no other plugins )  

Is there something that I am missing?

**Comment by banunn** [comment]
Works with new version of CLI

**Comment by nodetech-architecture** [comment]
Its crashing for me too
