### ISSUE TITLE
Firebase Crashlytics migration path?

### ISSUE THREAD

**Issue by lambourn** [EddyVerbruggen/nativescript-plugin-firebase#683]
Are there any plans to add a migration path for using Firebase Crashlytics instead of Firebase Crash Reporting? 

To quote the Firebase team:

> Today, we're graduating Firebase Crashlytics out of beta. As the default crash reporter for Firebase going forward, Crashlytics is the next evolution of the crash reporting capabilities of our platform. It empowers you to achieve everything you want to with Firebase Crash Reporting, plus much more.

and with regards to deprecation of the old SDK/API

> Firebase Crash Reporting will continue to be functional until September 8th, 2018 - at which point it will be retired fully.

References:
https://firebase.googleblog.com/2018/03/firebase-crashlytics-graduates-from-beta.html
https://firebase.google.com/docs/crashlytics/upgrade-from-crash-reporting

**Comment by EddyVerbruggen** [comment]
Working on it, see #549.

**Comment by lambourn** [comment]
great - missed that PR, thanks!
