### ISSUE TITLE
[iOS] New Version in NPM has podfile error during build

### ISSUE THREAD

**Issue by vtjon** [EddyVerbruggen/nativescript-plugin-firebase#684]
My project is in an automated build environment and I noticed that it started to fail today. It appears that this plugin was updated to version 5.3.0 and the way XCode merges the podfile is incorrect. I only have Admob and Messaging enabled in my app. If I look at my podfile, I have the following:

```
 pod 'Firebase', '~> 4.11.0' 
pod 'Firebase/Auth'

# Uncomment if you want to enable Realtime DB
#pod 'Firebase/Database'

# Uncomment if you want to enable Cloud Firestore
#pod 'Firebase/Firestore'

# Uncomment if you want to enable Remote Config
#pod 'Firebase/RemoteConfig'

# Uncomment if you want to enable Crash Reporting
#pod 'Firebase/Crash'

# Uncomment if you want to enable Crashlytics
#pod 'Fabric'
#pod 'Crashlytics'
# Crashlytics works best without bitcode
#def post_install4 (installer)
#    installer.pods_project.targets.each do |target|
#        target.build_configurations.each do |config|
#            config.build_settings['ENABLE_BITCODE'] = "NO"
#        end
#    end
#end

# Uncomment if you want to enable FCM (Firebase Cloud Messaging)
pod 'Firebase/Messaging'

# Uncomment if you want to enable Firebase Storage
#pod 'Firebase/Storage'

# Uncomment if you want to enable AdMob
pod 'Firebase/AdMob'

# Uncomment if you want to enable Invites and/or Dynamic Links
#pod 'Firebase/Invites'

```
However, in the post_install steps, I have:
```
post_install do |installer|
  post_install1 installer
  post_install2 installer
  post_install3 installer
  post_install4 installer
end
```
post_install4 should not be there in this case and was causing a build error. I have not had a chance to look into exactly why.

**Comment by EddyVerbruggen** [comment]
Let me know if you find out more. This doesn’t ring a bell for me.

**Comment by vtjon** [comment]
Here are the steps to duplicate
`tns create pod-test --ng`
`cd pod-text`
`tns plugin install nativescript-plugin-firebase` - Just select messaging and admob
`tns plugin install @nstudio/nativescript-camera-plus` - I think you just need another plugin that has a post install step
`tns prepare ios`

The prepare will fail. If you look at the resulting PodFile, it will have attempted to merge the commented out post install steps for Crashlytics. I'm guessing this is some type of Cocoapod bug. I tried a mult-line ruby comment for the post install steps and it still did the same thing. 

I am using:

- Nativescript CLI 3.4.3
- XCode 9.3
- Cocoapods 1.4.0

**Comment by EddyVerbruggen** [comment]
"the post install definition remains commented while the invocation is not" exactly 👌🏻

Thanks for reporting this guys!

Seems like a bug in the NativeScript's Podfile merger that I'll need to work around by not including the commented section at all.
