### ISSUE TITLE
App constantly crashing

### ISSUE THREAD

**Issue by shivgolani** [EddyVerbruggen/nativescript-plugin-firebase#687]
System.err: java.lang.RuntimeException: Unable to instantiate service org.nativescript.plugins.firebase.MyFirebaseMessagingService: java.lang.ClassNotFoundException: Didn't find class "org.nativescript.plugins.firebase.MyFirebaseMessagingService" on path: DexPathList[[zip file "/data/app/com.ngasce.jforce-1/base.apk"],nativeLibraryDirectories=[/data/app/com.ngasce.jforce-1/lib/arm, /data/app/com.ngasce.jforce-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
System.err:     at android.app.ActivityThread.handleCreateService(ActivityThread.java:3282)
System.err:     at android.app.ActivityThread.-wrap5(ActivityThread.java)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1618)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
System.err:     at android.os.Looper.loop(Looper.java:154)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6316)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.nativescript.plugins.firebase.MyFirebaseMessagingService" on path: DexPathList[[zip file "/data/app/com.ngasce.jforce-1/base.apk"],nativeLibraryDirectories=[/data/app/com.ngasce.jforce-1/lib/arm, /data/app/com.ngasce.jforce-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
System.err:     at android.app.ActivityThread.handleCreateService(ActivityThread.java:3279)
System.err:     ... 8 more
System.err:     Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/messaging/FirebaseMessagingService;
System.err:             at java.lang.VMClassLoader.findLoadedClass(Native Method)
System.err:             at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
System.err:             at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
System.err:             ... 10 more
System.err:     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.messaging.FirebaseMessagingService" on path: DexPathList[[zip file "/data/app/com.ngasce.jforce-1/base.apk"],nativeLibraryDirectories=[/data/app/com.ngasce.jforce-1/lib/arm, /data/app/com.ngasce.jforce-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
System.err:             at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
System.err:             at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
System.err:             at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
System.err:             ... 13 more
ActivityManager: Process com.ngasce.jforce (pid 20501) has died
ActivityManager: cleanUpApplicationRecord -- 20501

**Comment by EddyVerbruggen** [comment]
Can you share the project? Otherwise you can't expect me to make sense of this.
