### ISSUE TITLE
Error: URL scheme needed for Google Sign-In

### ISSUE THREAD

**Issue by aalshaikh** [EddyVerbruggen/nativescript-plugin-firebase#693]
Hello,

i am getting this error, i am just trying to enable push notifications

Error: URL scheme needed for Google Sign-In not included in your app's Info.plist. Please refer to the Google Sign-In SDK documentation for more information.

**Comment by EddyVerbruggen** [comment]
Yeah see the readme @ https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/AUTHENTICATION.md#google-sign-in

**Comment by surdu** [comment]
Even if you only want to use Invites and Dynamic Links ?

**Comment by surdu** [comment]
Even if you opted only to use Invites and Dynamic Links
