### ISSUE TITLE
iOS Crashlytics Stack Trace

### ISSUE THREAD

**Issue by MattNer0** [EddyVerbruggen/nativescript-plugin-firebase#694]
Hello,

As I was implemeting Crashlytics for iOS into my app I noticed that the stack trace page doesn't show the javascript error but only the native error stack like: 

`NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool) + 1752
NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*) + 112
...`

I went back to the Crashlytics PR and saw @DickSmith wrote that he improved logging. I'm not sure what he's referring to but should I be able to see the javascript stack?

Do I have to do something different to see more js information inside the firebase report?

Thank you.

**Comment by DickSmith** [comment]
@MattNer0 

Yes, so the regular stack trace will just display the native stuff, which in the case of JS crashes looks largely identical, so the changes I made will output any `std err` into the logs tab.

Most of the time the most important part will be at the bottom like:
`stderr: file:///app/vendor.js:1:712723: JS ERROR TypeError: null is not an object (evaluating 'a.viewControllers')`

**Comment by MattNer0** [comment]
I can't see anything in the **LOGS** tab right now, just a "screen_view" entry.

Do I need to activate any particular firebase service other than Crashlytics and Analytics?

**Comment by lambourn** [comment]
@MattNer0 as far as I can tell, the logs will only be written on non-DEBUG builds

https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/f923b84cff6b365514dadeddf16d57f9ead2e4b9/src/scripts/postinstall.js#L3138-L3150
