### ISSUE TITLE
firebase.instance not set when I run firebase.init() 

### ISSUE THREAD

**Issue by dbilovd** [EddyVerbruggen/nativescript-plugin-firebase#696]
I've been having some issues when I try using .getValue(), .push(), .setValue(), etc.

I did a little digging and found the following block of code inside `node_modules/nativescript-plugin-firebase/firebase.android.js (LN 263 - 277)`
```

if (typeof (com.google.firebase.database) !== "undefined") {
                firebase_common_1.firebase.ServerValue = {
                    TIMESTAMP: firebase_common_1.firebase.toJsObject(com.google.firebase.database.ServerValue.TIMESTAMP)
                };
                var fDatabase = com.google.firebase.database.FirebaseDatabase;
                if (arg.persist) {
                    try {
                        fDatabase.getInstance().setPersistenceEnabled(true);
                    }
                    catch (ignore) {
                    }
                }
                console.log(fDatabase);
                firebase_common_1.firebase.instance = fDatabase.getInstance().getReference();
            }

```
The section of the code to set the instance id doesn't run because `com.google.firebase.database` is always undefined.

Also when I attempt to run firebase.init() again, I get an "already initialised" message.

Has someone encountered something similar before?

**Comment by EddyVerbruggen** [comment]
I think on Slack we figured out that Realtime DB wasn't enabled in your app, hence `com.google.firebase.database` was undefined.
