### ISSUE TITLE
TypeScript Definition Not Included

### ISSUE THREAD

**Issue by burkeholland** [EddyVerbruggen/nativescript-plugin-firebase#7]
Can we get a TypeScript definition?

**Comment by EddyVerbruggen** [comment]
Do you have an example of what you're after?

**Comment by lelong37** [comment]
+10 @burkeholland 's request, @EddyVerbruggen here's an example of chat.d.ts (TypeScript definition) https://github.com/DefinitelyTyped/tsd/blob/master/typings/chai/chai.d.ts 

this would be super handy for all teams developing NativeScript w/ TypeScript using Firebase w/ your npm plugin, thanks btw, for your plugin as is...!

**Comment by burkeholland** [comment]
Yikes! Sorry. This got lost in the deluge of GitHub notifications.

I just want a .d.ts file. The `nativescript-geolocation.d.ts` is a good example of this...

https://github.com/NativeScript/nativescript-geolocation/tree/master/source

**Comment by EddyVerbruggen** [comment]
Cheers guys. @burkeholland I know what you mean ;)

**Comment by EddyVerbruggen** [comment]
Done. Part of release 2.0.0.

Please feel free to shoot at those `.d.ts` files as I intend to add similar files to other {N} plugins and rather not repeat errors.
