### ISSUE TITLE
Add `getCurrentUser` Method

### ISSUE THREAD

**Issue by t-moe** [EddyVerbruggen/nativescript-plugin-firebase#70]
https://developers.google.com/android/reference/com/google/firebase/auth/FirebaseAuth#getCurrentUser()

The official firebase API has a method to fetch the currently signed in user, which is really useful. Without that method one has to save the user object somewhere after login/stateChange.

**Comment by EddyVerbruggen** [comment]
Hi, it may not be documented but it's actually in there :)

`firebase. getCurrentUser()` etc

**Comment by t-moe** [comment]
Yes it's implemented but not in the typescript references...
I'm a bit new to Typescript:
How can I access properties which are not defined in the references? (=prevent the compiler error)

**Comment by EddyVerbruggen** [comment]
Ah OK, makes sense. I've just added it to the TS definition and pushed it to this repo. Will be on npm with the next release.
