### ISSUE TITLE
Can not use library with natvescript 4.0 angular project.

### ISSUE THREAD

**Issue by richard457** [EddyVerbruggen/nativescript-plugin-firebase#700]
With Error `problem occurred configuring project ':app'` No Match found and in package.json I have "nativescript-plugin-firebase": "^5.3.1"
Please help me if I am missing something in configuring this libray to work with nativescript angular. thank you.

**Comment by EddyVerbruggen** [comment]
You’ll need to provide a lot more info for me to make sense of this. 

Also, I have an Angular / N4 app in the store with this plugin so I’m sure it should work with this combo.
