### ISSUE TITLE
Unable to copy google-services.json.

### ISSUE THREAD

**Issue by gambheera** [EddyVerbruggen/nativescript-plugin-firebase#701]
I'm new to Nativescript and trying to configure Firebase in my app. 

I'm using nativescript 3.3.1 version

These are the steps I followed
1. Added fire base plugin to the project (`tns plugin add nativescript-plugin-firebase`)
2. Created Firebase project (with correct project Id) on web and got the google-services.json file
3. Copied downloaded json file to app/App_Resources/Android folder.
4. Added following code to app.component.ts file 
`import firebase = require('nativescript-plugin-firebase');
firebase.init()
    .then(() => console.log('Firebase initialized!!!'))
    .catch(error => console.log(`Failed to initialize Firebase ${error}`));`

5. executed command `tns run android`

But it is giving following output:
![typescript_error](https://user-images.githubusercontent.com/6507302/39969960-6baa5f3e-5701-11e8-8213-de01491f2dc0.PNG)

Am I mistaken anything?

**Comment by gambheera** [comment]
Yes I answered.

This is my code base:
[(https://github.com/gambheera/my-log-app-1)]

**Comment by gambheera** [comment]
I created a fresh project and tried. But same issue is comming...

**Comment by gambheera** [comment]
I updated the nativescript vertion to 4.0.1
Now it is working... 👍

**Comment by Burgov** [comment]
Doesn't work for me either. it looks like it's trying to copy the file from App_Resources into the platforms folder, but the file (google-services.json) doesn't exist. Tried reinstalling the plugin, removing platforms, all to no avail. Any ideas?

**Comment by Burgov** [comment]
here's my firebase.nativescript.json, if it helps:

```
{
    "using_ios": true,
    "using_android": true,
    "firestore": false,
    "realtimedb": false,
    "remote_config": false,
    "messaging": false,
    "crashlytics": false,
    "crash_reporting": false,
    "storage": false,
    "facebook_auth": false,
    "google_auth": false,
    "admob": false,
    "invites": false,
    "ml_kit": true,
    "ml_kit_text_recognition": true,
    "ml_kit_barcode_scanning": true,
    "ml_kit_face_detection": false,
    "ml_kit_image_labeling": false,
    "ml_kit_custom_model": false
}
```

**Comment by EddyVerbruggen** [comment]
@Burgov What's the reason you didn't add the google-services.json file to your project?

**Comment by Burgov** [comment]
@EddyVerbruggen that would be because I'm too impatient to read documentation... Thanks for your quick response.

https://github.com/EddyVerbruggen/nativescript-plugin-firebase/pull/716

**Comment by EddyVerbruggen** [comment]
And TY for the RP ;)

**Comment by elimin8r** [comment]
I am having the same issue despite the fact the app/App_Resources/Android/google-services.json file exists and I have upgraded to NS 4.0.1.

**Comment by endytc** [comment]
I have same issue, I'm used NS 4.0.2

**Comment by s-triar** [comment]
i got same issue too. i play around NS 4+ with angular typescript. 

my issue is got like that. and sometimes my google-service.json is disappeared in my android platform folder when i run tns run android

**Comment by paweldziura** [comment]
Does it work only with NS4? For now I have to use 3.x, I have google-services.json in app/App_Resources/Android but I'm still getting:

```
Executing after-prepare hook from /Users/pawel.dziura/Projects/DHL_POC/hooks/after-prepare/firebase-copy-google-services.js
Unable to copy google-services.json.
Failed to execute hook: /Users/pawel.dziura/Projects/DHL_POC/hooks/after-prepare/firebase-copy-google-services.js.
```

I did chmod 777 to platforms/android and app/App_Resources/Android/google-services.json

still error occurs

**Comment by s-triar** [comment]
`i got same issue too. i play around NS 4+ with angular typescript.

my issue is got like that. and sometimes my google-service.json is disappeared in my android platform folder when i run tns run android`

Accidentally i copy -paste in wrong folder so i got error like that

**Comment by EddyVerbruggen** [comment]
@s-triar Which folder do you add that file to? It should be [here](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/tree/master/demo-ng/app/App_Resources/Android).

**Comment by paweldziura** [comment]
The problem is in hooks.after-prepare/firebase-copy-google-services.js line 10.

`var destinationGoogleJson = path.join($projectData.platformsDir, "android", "app", "google-services.json");`

platforms/android doesn't have app folder and that is why the hook is failing. 

Correct me if I'm wrong but the google-services.json should be in platforms/android, not in platforms/android/app folder.

Changing 

`var destinationGoogleJson = path.join($projectData.platformsDir, "android", "app", "google-services.json");`

to

`var destinationGoogleJson = path.join($projectData.platformsDir, "android", "google-services.json");`

fixes the problem

**Comment by EddyVerbruggen** [comment]
Whether or not the `app` folder exists perhaps depends on the NativeScript version(?). I'm on 4.x usually and see this:

<img width="258" alt="screenshot 2018-07-11 at 16 36 53" src="https://user-images.githubusercontent.com/1426370/42579479-b3755d5a-8528-11e8-9d33-29e097800102.png">

Can you check your N version and folder structure?

Perhaps we should try both folders in the hook?

**Comment by paweldziura** [comment]
NativeScript 3.3.1, Android platform version 3.3.1
![screen shot 2018-07-11 at 16 48 34](https://user-images.githubusercontent.com/3899080/42580220-574790d2-852a-11e8-8e0a-0a46f418559a.png)

It seems to depend on the version then.

**Comment by EddyVerbruggen** [comment]
@paweldziura Thanks! Let me reopen and try to make this compatible with N 3.

**Comment by EddyVerbruggen** [comment]
Plugin version 6.4.1 (not released yet, but will do later this week) will look for the `platforms/android/app` folder, and if your project doesn't have it (NativeScript < 4, allegedly) it will attempt to copy the file to `platforms/android` instead.

**Comment by SalehMahmood** [comment]
@EddyVerbruggen I'm having this issue in version 6.8.1 "Unable to copy google-services.json"
So I looked up in the hook file `firebase-copy-google-services.js`. 

Why you're checking for the destination file. `fs.existsSync(path.dirname(destinationGoogleJson))` and the `fs.existsSync(path.dirname(destinationGoogleJsonAlt))`?. 

I mean if you're using this hook to copy the file to the destination, why checking the existence if for sure it doesn't exist. it's always gonna be false until user itself copies it, right?. What's the point of the hook? I hope you're getting my point

Anyway after removing that check working fine for me. I can share my environment if you need me to.

**Comment by EddyVerbruggen** [comment]
@SalehMahmood That code is checking the *file* to copy exists, and the *folder* to copy to exists as well. See the docs of [path.dirname](https://www.w3schools.com/nodejs/met_path_dirname.asp).

Those lines have been in the code since 2016 so I don't think they are the problem in your case, but dunno what is - perhaps this explanation helps somehow.

**Comment by inONEL** [comment]
@EddyVerbruggen If your using Non-Firebase Push Messaging, so without the use of firebase do I still need a google-services.json? I am able to build for IOS but not Android getting the "Unable to copy google-services.json." warning.
Thank a lot

**Comment by inONEL** [comment]
For those struggling with "Non-Firebase Push Messaging" and getting the "Unable to copy google-services.json." warning. You still need to setup a FireBase Cloud Messaging account.

**Comment by Zec2703** [comment]
I haved a this problem when I put **'tns run android'** in my terminal : 
```
Unable to apply changes on device: _device_name_. Error is: Failed to build plugin nativescript-plugin-firebase : 
Error: Command gradlew.bat failed with exit code 1.
```
and when I just put **'tns run'**, it's worked !
`Successfully synced application org.nativescript._project_name_ on device _device_name_.`
