### ISSUE TITLE
Add custom (TensorFlow Lite) models support to the ML Kit feature

### ISSUE THREAD

**Issue by EddyVerbruggen** [EddyVerbruggen/nativescript-plugin-firebase#702]
Checklist for https://firebase.google.com/docs/ml-kit/use-custom-models:

- [x] Use a custom TensorFlow Lite model, on the device
- [ ] ~~Use a custom TensorFlow Lite model, stored in Firebase (so users always have the latest model)~~ (having trouble, let's postpone this one)

**Comment by EddyVerbruggen** [comment]
On iOS I'm experiencing a crash when resizing an image (see the comments in the code). Going to postpone this.

**Comment by neil-119** [comment]
Awesome! This is going to be great!

**Comment by geoffbullen** [comment]
Looking forward to this being available!

**Comment by OscarAgreda** [comment]
Adding Tensor Flow Lite to Eddy's work will be terrific, a game changer for sure.

**Comment by gimox** [comment]
And news?

**Comment by efgonz** [comment]
This is great but seems that we have to wait a bit, so, is there any other way to load a custom tensorflow model in a nativescript app with angular?

**Comment by EddyVerbruggen** [comment]
Hi folks, I'm actively working on this task and I'm seeing a few results that give me good hope for the near future ;)

What would be really helpful to me is receiving a few custom tflite models, along with a sample image and expected labels (and scores). Would really appreciate if anyone can provide me with those, otherwise I'll continue development with the single model I have.

**Comment by jlooper** [comment]
On it!

**Comment by jlooper** [comment]
Eddy, there are some here https://www.tensorflow.org/lite/models

**Comment by geoffbullen** [comment]
I’m excited!

**Comment by EddyVerbruggen** [comment]
I'm wrapping things up for a first release with support for loading and interpreting bundled quantized models on both iOS and Android. Interpretation can be performed from a still image, as well as a live camera feed.

Please check the [updated ML Kit docs](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/ML_KIT.md#custom-model-inference). I'll release 7.7.0 soon, so y'all can give it a shot! 💪
