### ISSUE TITLE
Nativescript-vue Can't find variable: FIRApp

### ISSUE THREAD

**Issue by alexpalchikovskiy** [EddyVerbruggen/nativescript-plugin-firebase#712]
Help me, please.

I installed plugin, copied GoogleService-Info.plist but always get this error.

My /src/main.js:

```
import Vue from 'nativescript-vue';

import router from './router';
import store from './store';

import './styles.scss';

Vue.config.silent = false;

const firebase = require('nativescript-plugin-firebase');

firebase.init({
    onMessageReceivedCallback: function(message) {
      console.log("Title: " + message.title);
      console.log("Body: " + message.body);
      // if your server passed a custom property called 'foo', then do this:
      console.log("Value of 'foo': " + message.data.foo);
    },
    onPushTokenReceivedCallback: function(token) {
        console.log("Firebase push token: " + token);
      }
});
firebase.getCurrentPushToken().then((token) => {
    // may be null if not known yet
    console.log("Current push token: " + token);
});

new Vue({
    router,
    store
}).$start();

```

**Comment by alexpalchikovskiy** [comment]
@EddyVerbruggen I see that after installing /dist/platforms/ios/Podfile was not rewritable and not contain Firebas. 

I added to Podfile manually:
```
pod 'Firebase', '~> 4.11.0' 
pod 'Firebase/Messaging'
```

Run
```
pod install
```

but problem staying... I get error "JS ERROR ReferenceError: Can't find variable: **FIRApp**"

If I use setTimeout for calling firebase.init() I get "Error in firebase.init: ReferenceError: Can\'t find variable: **FIROptions**"

**Comment by elalienx** [comment]
Yeah same error here If I use setTimeout for calling firebase.init() I get "Error in firebase.init: ReferenceError: Can't find variable: FIROptions"

**Comment by fabfischer** [comment]
I got the same error. But I could resolve it with the following commands:

-------------
#### update/install cocoapods 
`sudo gem install cocoapods`
#### update repo list
`pod repo update`
#### clear dist folder and force nativescript to build/install all plugins again
`npm run clear`
#### start watcher again
`npm run watch:ios`

-------------

I hope you can solve your issues with it too

**Comment by jlooper** [comment]
@elalienx did this workaround work for you? and @alexpalchikovskiy, did you get it working?

**Comment by Macuzzin** [comment]
I had the same issue but being new to NativeScript (and Vue.js for that matter), I didn't realise that I needed to run "npm install" in the template folder too. Here's the article that pointed me in the right direction: https://medium.com/@groksrc/how-to-set-up-nativescript-vue-js-and-firebase-465354d4296b Thanks Drew Cain!

**Comment by EddyVerbruggen** [comment]
Thanks all!

I've also been tinkering with the 2.0 template and I don't see any of the issues that were reported in the past (especially around hooks this plugin requires, as the project structure is now similar to any other NativeScript project). [Here's the app](https://github.com/EddyVerbruggen/footplr) I'm building using Firestore, Cloud Functions, and the NativeScript-Vue 2.0 template.
