### ISSUE TITLE
Build fails for android platform: version conflict with google-services plugin

### ISSUE THREAD

**Issue by Jpaagt** [EddyVerbruggen/nativescript-plugin-firebase#72]
tns version 2.1.1
"tns-core-modules": "^2.1.0"
"tns-android": {
      "version": "2.1.1"
}
"nativescript-plugin-firebase": "^3.4.0"

I updated to the latest version of NativeScript and the latest version of the Firebase plugin and now my build breaks with the following appearing in the build output:

Found com.google.android.gms:play-services-base:9.2.0, but version 9.0.0 is needed for the google-services plugin.

* What went wrong:
Execution failed for task ':processF0F1F2F3DebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 9.0.0.

**Comment by Jpaagt** [comment]
I found the issue. I had applied the google-services plugin in the app level gradle.

**Comment by preethijayanthi** [comment]
How to use this plugin in app level gradle ?
