### ISSUE TITLE
Camera is stretched when using width and height

### ISSUE THREAD

**Issue by Burgov** [EddyVerbruggen/nativescript-plugin-firebase#720]
I have a barcode scanner with width 400 and height 200, and the camera view is stretch to make everything really flat, looks like it's scaling the full screen camera down to the dimensions without keeping aspect ratio.

**Comment by EddyVerbruggen** [comment]
Yeah, I noticed this as well (only on Android actually).

**Comment by ndcunningham** [comment]
+1

**Comment by shaqaruden** [comment]
I have this issue on iOS as well. Can you fix this? Or is this a Firebase MLKit issue?

**Comment by EddyVerbruggen** [comment]
Can you share the UI code?

**Comment by shaqaruden** [comment]
The code in the example

**Comment by shaqaruden** [comment]
Changing the width and height to 100% does not distort the image

**Comment by EddyVerbruggen** [comment]
So that means it's ok now?

**Comment by shaqaruden** [comment]
Yea, but it would be nice to be able to have a camera view that's not the full size

**Comment by zalesak** [comment]
I hope this is fix: 
In file mlkit-cameraview.android.js, line 243 replace with this:
var diff = Math.abs((size.width / size.height) - (pict.width / pict.height));

it compute preview/picture pair with the closest aspect ratio.

**Comment by DanielDent** [comment]
To the extent that this is an Android-specific issue, I think the following line is responsible:

https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/794467a9d72b66247c1343eee3a7665c6b00306c/src/mlkit/mlkit-cameraview.android.ts#L130

The selectSizePair function seems to be looking for the previewSize which most closely matches the aspect ratio of the display area -- however, it assumes that the display area is always 1400x1200. Identifying the camera preview's current height & width, and updating it based on screen orientation or other layout changes does not currently appear implemented.

**Comment by EddyVerbruggen** [comment]
Yeah that TODO is waiting to be solved indeed. Happy to merge a PR if someone would like to take a stab at it :)

**Comment by MurilloBrand** [comment]
I solved this!
I will create a PR soon

**Comment by EddyVerbruggen** [comment]
@MurilloBrand That would be great!
