### ISSUE TITLE
Storage - uploadFile is missing url on success.

### ISSUE THREAD

**Issue by spmamidi** [EddyVerbruggen/nativescript-plugin-firebase#727]
Upgraded to 6.0.2

uploadFile result is missing url for both android and ios.

Here is the code commented in firebase.ios.js.
 ```
resolve({
                        name: metadata.name,
                        // url: metadata.downloadURL() ? metadata.downloadURL().absoluteString : null,
                        contentType: metadata.contentType,
                        created: metadata.timeCreated,
                        updated: metadata.updated,
                        bucket: metadata.bucket,
                        size: metadata.size
                    });
```
Is there any technical limitation to get download url?

**Comment by EddyVerbruggen** [comment]
They’ve removed it from the sdk. Getting the url is now async, so it would take mire time to complete. But if you need the url, you can retrieve it in the promise of the upload function by calling the getdownloadurl (or similar) function (see the readme for the exact name).
