### ISSUE TITLE
firebase.js:310:18: Error in firebase.init: ReferenceError: Can't find variable: FIRDatabase

### ISSUE THREAD

**Issue by NathanWalker** [EddyVerbruggen/nativescript-plugin-firebase#73]
> Jul 14 00:14:30 Mac ShoutOutPlay[84214]: <FIRAnalytics/INFO> Firebase Analytics v.3201000 started
> Jul 14 00:14:30 Mac ShoutOutPlay[84214]: <FIRAnalytics/INFO> To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/Y0Yjwu)
> Jul 14 00:14:30 Mac ShoutOutPlay[84214]: CONSOLE LOG file:///app/tns_modules/nativescript-plugin-firebase/firebase.js:310:18: Error in firebase.init: ReferenceError: Can't find variable: FIRDatabase

Just added plugin tonight and seeing that error?
Using `"nativescript-plugin-firebase": "^3.4.1",`  

Running in iPhone 6 Simulator with:

```
import firebase = require("nativescript-plugin-firebase");

firebase.init({
      persist: false,
      iOSEmulatorFlush: true
    }).then((instance) => {
      console.log("firebase.init done");
    }, (error) => {
      console.log("firebase.init error: " + error);
    });
```
```
firebase.init error: ReferenceError: Can't find variable: FIRDatabase
```

/cc @jlooper

**Comment by EddyVerbruggen** [comment]
Hey Nathan, can you open the `Podfile` in the plugin's folder and manually add `pod 'Firebase/Database'` and rebuild to see if that makes a difference? I just changed a few bits to this file in 3.4.1 so that may have caused it.

**Comment by NathanWalker** [comment]
Hi @EddyVerbruggen that worked like a charm. Thank you, are you going to post a `.2` update with that fix?  I noticed it's on master now.

**Comment by EddyVerbruggen** [comment]
Yeah I was finalizing crash reporting and now it's published. Cheers!

**Comment by NathanWalker** [comment]
Hooray! thx @EddyVerbruggen !

**Comment by Nikoms** [comment]
Thx @EddyVerbruggen!  You never stop :)

**Comment by abulshariff** [comment]
Hi! @EddyVerbruggen I am having the same issue. I am a beginner at Nativescript
