### ISSUE TITLE
ml kit barcode 

### ISSUE THREAD

**Issue by lucasp18** [EddyVerbruggen/nativescript-plugin-firebase#737]
Hello I would like to thank for developing the firebase plugin and ml barcode.
My English is not so good so I'm writing this text with the help of google translate.
I'm doing some testing with your ml barcode plugin and found some improvements, I'll list it down to what I found:

1- Whenever I open the screen to read the barcode, the camera permission screen appears. I tried some approaches, but none avoided the permission display. Could you improve this or help me improve?

2- The onBarcodeScanResult method is always called twice, would it be possible to do the other plugin, when I read the first code does not read but no code?

3- Could you explain how the plugin reading barcode is configured?
Currently the plugin looks like this:

<MLKitBarcodeScanner
      width = "250"
      height = "250"
      formats = "EAN_13"
      processEveryNthFrame = "5"
      (scanResult) = "onBarcodeScanResult ($ event)">
  </ MLKitBarcodeScanner>

Thank you for the contact

**Comment by lucasp18** [comment]
open PR for resolution item 1

**Comment by EddyVerbruggen** [comment]
Hi,

I don't see the issue with 1. really. The first time (after the app is installed) the permission popup will appear when you access the camera, but the second time it will no longer request the permission. Can you share a video where you see this permission popup every time?

Note that requesting permission is not supposed to show the permission prompt in case permission has already been granted.
