### ISSUE TITLE
Android - Unnecessary permissions added to AndroidManifest.xml

### ISSUE THREAD

**Issue by mintyweazel** [EddyVerbruggen/nativescript-plugin-firebase#740]
Hi, 
I am facing the issue on Android permissions with your plugin. 

Following your installation guide, I configured my firebase settings as follows.

```
{
  "using_ios": false,
  "using_android": true,
  "firestore": false,
  "realtimedb": false,
  "remote_config": true,
  "messaging": false,
  "crashlytics": true,
  "crash_reporting": false,
  "storage": false,
  "facebook_auth": false,
  "google_auth": false,
  "admob": false,
  "invites": false,
  "ml_kit": false
}
```

As you can see, the enabled firebase services are only remote_config and crashlytics, both of which does not require permissions on camera or flashlight.
However, after the apk build completed, unnecessary permissions were added to `AndroidManifest.xml` (located under `platforms/android` directory).

```
    <!-- for ML Kit -->
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.FLASHLIGHT" />
    
    <uses-feature
        android:name="android.hardware.camera"
        android:required="false" />
    
    <!-- for Messaging -->
    <application>
        <service android:name="org.nativescript.plugins.firebase.MyFirebaseMessagingService" >
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
        <service android:name="org.nativescript.plugins.firebase.MyFirebaseInstanceIDService" >
            <intent-filter>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
            </intent-filter>
        </service>
    </application>
``` 

With some research, I find that this issue is due to `firebase-release.aar`( in this repository, this file is located in `nativescript-plugin-firebase/blob/master/src/platforms/android/`.)
In fact, the deletion of this aar file fixed the problem. In other words, unnecessary permissions were removed from my `AndroidManifest.xml`.  

I do not want to use such an ugly hack every time I install your great plugin.
Any better solution for this?

Thank you in advance.

**Comment by EddyVerbruggen** [comment]
Good point. I'll probably end up removing those from the .aar and add them to the docs for ML Kit.
