### ISSUE TITLE
Error logging in using Facebook test user

### ISSUE THREAD

**Issue by arielnmz** [EddyVerbruggen/nativescript-plugin-firebase#746]
Whenever I try to login using a Facebook test user created using the test users console:

`https://developers.facebook.com/apps/xxx/roles/test-users/`

I get the following message:

> `com.google.firebase.FirebaseException: An internal error has occurred. [ Unsuccessful debug_token response from Facebook:{&quot;error&quot;:{&quot;message&quot;:&quot;(#100) You must provide an app access token or a user access token that is an owner or developer of the app&quot;,&quot;type&quot;:&quot;OAuthException&quot;,&quot;code&quot;:100,&quot;fbtrace_id&quot;:&quot;AvcthT7RNW5&quot;}} ]`

This is the important bit:

> `You must provide an app access token or a user access token that is an owner or developer of the app`

But there's no mention about not being able to use the login flow using a test user from Facebook, and indeed I am able to obtain an access token and even use the Graph API Explorer with that token. The app I am trying to authenticate with is also a test version of the original app.

Am I missing something?

**Comment by EddyVerbruggen** [comment]
Dunno. The only things I've done is follow [these steps](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/AUTHENTICATION.md#facebook-login) and tested those in the embedded demo app...

**Comment by liuchuancong** [comment]
i get an error  A valid Facebook app id must be set in the AndroidManifest.xml or set by calling FacebookSdk.setApplicationId before initializing the sdk.
i want to konw how to set it? where

**Comment by EddyVerbruggen** [comment]
@liuchuancong Dude, you asked that in #747, and I answered it.
