### ISSUE TITLE
Unable to query with equalTo param as true.

### ISSUE THREAD

**Issue by uttahb** [EddyVerbruggen/nativescript-plugin-firebase#748]
I am using firebase.query method to get a list of data having a child value equal to true. This is the code I wrote.

      firebase.query(result => {}, rootKey, {
        orderBy: {
          type: firebase.QueryOrderByType.CHILD,
          value: orderByChildKey
        },
        range: {
          type: firebase.QueryRangeType.EQUAL_TO,
          value: true
        },
        singleEvent: true
      })
Here even though there is result in db, its fetching null. If I change the true value in db to some string val, its fetching correctly.  

{
"nativescript-plugin-firebase": "5.3.1",
"firebase": "4.5.0",
}
Is this becoz of any known issue or am I doing something wrong here.
Thanks

**Comment by EddyVerbruggen** [comment]
Is the behavior the same on both iOS and Android?

**Comment by uttahb** [comment]
I just tried this out on android, haven't checked on ios yet.

**Comment by EddyVerbruggen** [comment]
Thanks, I'll wait for that.
