### ISSUE TITLE
TypeError: Cannot set property '_launchNotification' of undefined

### ISSUE THREAD

**Issue by arielnmz** [EddyVerbruggen/nativescript-plugin-firebase#749]
I am using a fresh [Vue template](https://nativescript-vue.org/en/docs/getting-started/quick-start/) and followed the [instructions for Vue](https://github.com/EddyVerbruggen/nativescript-plugin-firebase#using-vue), but just importing the plugin in `main.js` makes the app crash with the following stack trace:

~~~
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 
System.err: 
System.err: Error calling module function 
System.err: 
System.err: Error calling module function 
System.err: 
System.err: Error calling module function 
System.err: 
System.err: TypeError: Cannot set property '_launchNotification' of undefined
System.err: File: "file:///data/data/com.nopalcreativa.palmira/files/app/tns_modules/nativescript-plugin-firebase/firebase.js, line: 11, column: 47
System.err: 
System.err: StackTrace: 
System.err:     Frame: function:'', file:'file:///data/data/com.nopalcreativa.palmira/files/app/tns_modules/nativescript-plugin-firebase/firebase.js', line: 11, column: 48
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     Frame: function:'', file:'file:///data/data/com.nopalcreativa.palmira/files/app/tns_modules/nativescript-plugin-firebase/firebase-common.js', line: 5, column: 18
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     Frame: function:'', file:'file:///data/data/com.nopalcreativa.palmira/files/app/app.js', line: 1, column: 207276
System.err:     Frame: function:'t', file:'file:///data/data/com.nopalcreativa.palmira/files/app/app.js', line: 1, column: 161
System.err:     Frame: function:'', file:'file:///data/data/com.nopalcreativa.palmira/files/app/app.js', line: 1, column: 152527
System.err:     Frame: function:'t', file:'file:///data/data/com.nopalcreativa.palmira/files/app/app.js', line: 1, column: 161
System.err:     Frame: function:'', file:'file:///data/data/com.nopalcreativa.palmira/files/app/app.js', line: 1, column: 146957
System.err:     Frame: function:'t', file:'file:///data/data/com.nopalcreativa.palmira/files/app/app.js', line: 1, column: 161
System.err:     Frame: function:'', file:'file:///data/data/com.nopalcreativa.palmira/files/app/app.js', line: 1, column: 511
System.err:     Frame: function:'', file:'file:///data/data/com.nopalcreativa.palmira/files/app/app.js', line: 1, column: 521
System.err:     Frame: function:'require', file:'', line: 1, column: 266
~~~
Both 
`const firebase = require('nativescript-plugin-firebase')`
and
`import * as firebase from 'nativescript-plugin-firebase'`
yield the same result.

Also, both `firebase.nativescript.json` and `google-services.json` are placed in their correct locations (inside `template` and `template/app/App_Resources/Android` respectively)

**Comment by EddyVerbruggen** [comment]
That's this line (but transpiled to js):

https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/4b6bae96bb4c34105ff59a5ec6673ee8b293a6a2/src/firebase.android.ts#L12

That would mean `firebase-common.js` can't be found..

**Comment by arielnmz** [comment]
I found something:

`firebase` is importing `"./firebase-common"` which in turn is importing `firebase` again to use a constant defined in `firebase.d.ts` named `FIRESTORE_SERVER_TS`, this causes a problem to webpack and may return `exports` prematurely, before `exports.firebase` is defined (which makes sense because it is defined after importing `firebase` again) and thus breaking everything.

This is explained here (I quote): https://stackoverflow.com/a/35240717/2625090

> A imports another module C, which, in turn, imports B. A gets imported first in main.js, so B ends up being the last link in the "circle", and Webpack ... just short-circuits it by returning A's module.exports, which is still undefined.

In this case it is only between two modules. Moreover, this does not seem to happen with TypeScript or Javascript alone, only when using Webpack to bundle the app.

One workaround is to just hardcode the value of `FIRESTORE_SERVER_TS` in the one (and only) place where the `firebase` module is needed in `firebase-common`, like this:

~~~
// var firebase_1 = require("./firebase");
...
var FieldValue = /** @class */ (function () {
    function FieldValue() {
        this.serverTimestamp = function () { return "SERVER_TIMESTAMP"; };
    }
    return FieldValue;
}());
~~~

**Comment by EddyVerbruggen** [comment]
Awesome! Hardcoding that is fine. Willing yo do a little PR?

**Comment by EddyVerbruggen** [comment]
Nevermind, I'll take care of it now. Although weirdly I don't have this issue (with the Angular-based demo-ng app).

**Comment by EddyVerbruggen** [comment]
Please update to 6.1.1 and let me know if that helps.

**Comment by arielnmz** [comment]
It works! Thanks!
