### ISSUE TITLE
Error while trying to use Admob

### ISSUE THREAD

**Issue by anaszgh** [EddyVerbruggen/nativescript-plugin-firebase#753]
I'm using TNS@4.0.1
Plugin Version: 6.1.1
Template: Angular

After i added and configured the plugin i noticed the following logs in the console
```
 ERROR TypeError: Cannot read property 'android' of null
chromium: [INFO:library_loader_hooks.cc(136)] Chromium logging enabled: level = 0, default verbosity = 0
```
And whenever i try to create banner, i get the following error
```
JS: admob createBanner error: 0
```
And the ads are not showing

**Comment by redabelca** [comment]
use setTimeout(()=>createBanner(),  2e3)

**Comment by anaszgh** [comment]
@redabelca I have tried this, the error code changed to 3

As per their documentation this error code means
```
The ad request was successful, but no ad was returned due to lack of ad inventory.

Constant Value: 3
```
But don't know what is this and how to solve it :( however this is irrelevant to the plugin it self.
So i'm going to close this issue.

Thanks.
