### ISSUE TITLE
Cannot read property 'android' of null in onPageLoaded 

### ISSUE THREAD

**Issue by rakeshgirase** [EddyVerbruggen/nativescript-plugin-firebase#755]
Hi

I am getting following exception when I am trying to launch the smart banner from firebase adMob from onPageLoaded function. 
----------------------------
Exception:
TypeError: Cannot read property 'android' of null
File: "file:///data/data/com.travel.agent/files/app/tns_modules/nativescript-plugin-firebase/firebase.js, line: 586, column: 43

StackTrace: 
	Frame: function:'', file:'file:///data/data/com.travel.agent/files/app/tns_modules/nativescript-plugin-firebase/firebase.js', line: 586, column: 44
	Frame: function:'invoke', file:'file:///data/data/com.travel.agent/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 19, column: 48
	Frame: function:'run', file:'file:///data/data/com.travel.agent/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 23, column: 13
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
	at com.tns.Runtime.callJSMethod(Runtime.java:970)
	at com.tns.Runtime.callJSMethod(Runtime.java:954)
	at com.tns.Runtime.callJSMethod(Runtime.java:946)
	at com.tns.gen.java.lang.Runnable.run(Runnable.java:15)
	at android.os.Handler.handleCallback(Handler.java:836)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6339)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)
----------------------------
I can launch smart banner successfully after the page is loaded but not from the onPageLoaded method. I checked and I am sure that I am initialising the firebase before calling a function which creates smart banner. Can some please see if I am missing any configurations on my side or if its an issue with the firebase nativescript plugin.

Thanks,
Rakesh

**Comment by EddyVerbruggen** [comment]
Which version of the plugin is this? It can't be the last one because those linenumbers don't match up.

The reason I ask is because I recently fixed something similar for NativeScript 4 compatibility.

If you don't want to upgrade, wrap a `setTimeout` around the call to show the banner.

**Comment by rakeshgirase** [comment]
I upgraded to ^6.0.0 but now I get TypeError:"com.google.android.gms.ads.InterstitialAd is not a constructor" and "TypeError: com.google.android.gms.ads.AdView is not a constructor". I searched but couldnt get any solution online. Can you please advise?

**Comment by rakeshgirase** [comment]
Nativescript-admob plugin also has the same problem. I get following exception when I call createBanner from onPageLoaded method:
TypeError: Cannot read property 'android' of null
File: "file:///data/data/com.exuberant.quiz.sas/files/app/tns_modules/nativescript-admob/admob.js, line: 142, column: 37

StackTrace: 
	Frame: function:'', file:'file:///data/data/com.exuberant.quiz.sas/files/app/tns_modules/nativescript-admob/admob.js', line: 142, column: 38
	Frame: function:'invoke', file:'file:///data/data/com.exuberant.quiz.sas/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 19, column: 48
	Frame: function:'run', file:'file:///data/data/com.exuberant.quiz.sas/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 23, column: 13


	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)

**Comment by EddyVerbruggen** [comment]
Without a repo to look at I can only guess. I think the best way forward is running the demo apps of those plugins..
