### ISSUE TITLE
GeoPoint data type.

### ISSUE THREAD

**Issue by tthil** [EddyVerbruggen/nativescript-plugin-firebase#756]
How do I use the GeoPoint datatype with the Firebase plugin. In the cloud functions I have access to the GeoPoint using firebase-admin but I can't see anything like this in the plugin.
I like to do something like this.
   ```
 firestore.collection("GeoData").add(
            { geolocation: new admin.firestore.GeoPoint(13.123456, 100.123456) }).then(() => {
                alert("New GEO");
            });
    }
```

**Comment by EddyVerbruggen** [comment]
Reading Geopoints is already possible, but writing is indeed not supported atm.

**Comment by EddyVerbruggen** [comment]
Added in 6.3.0, see [this example in the Firestore doc](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/766e606d71f6ccb2550a9b9fd7e07be06c23f596/docs/FIRESTORE.md#collectiondocupdate).
