### ISSUE TITLE
how can I delete a folder?

### ISSUE THREAD

**Issue by parliament718** [EddyVerbruggen/nativescript-plugin-firebase#757]
The API provides deleteFile but not deleteFolder, and the former does not work when passing a partial path to the file.

What is the equivolent of

`firebase.storage().ref().child('images').delete()`

Is there a way to get the storage object?

**Comment by EddyVerbruggen** [comment]
Have you seen this? https://firebase.google.com/docs/firestore/manage-data/delete-data#collections

**Comment by parliament718** [comment]
I have but I'm refering to deleting a file in storage, not in firestore.

I'm referring to this https://firebase.google.com/docs/storage/web/delete-files

And doing something like this 
```
var storage = firebase.storage();
var storageRef = storage.ref();
storageRef.child('images').delete();
```

However, nativescript-plugin-firebase does not expose the storage object reference via ```firebase.storage()```

**Comment by EddyVerbruggen** [comment]
Hi,

I've now [implemented the Web API](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/d68b16a0933cbac1fbb77499fea1f2ed3c2a91b2/docs/STORAGE.md#typescript-3) so you can actually do `firebase.storage().ref().child('my/path').delete()` in the next version of this plugin.

However, as Googling this fact seems to prove: you can't delete a folder from Firebase Storage, you can only delete individual files. So perhaps it's best to store a reference to those files and remove them one by one.

Please reopen one Firebase has implemented this feature in their SDK's.

**Comment by imbilal1** [comment]
Deleting a folder is not possible in firebase.
firebase have a lot of limitations, it is one of them.
