### ISSUE TITLE
Firebase query not returning datasnapshot

### ISSUE THREAD

**Issue by uttahb** [EddyVerbruggen/nativescript-plugin-firebase#758]
Hi,
I've met with above issue, that I am not receiving snapshot in both promise.then() and the completion handler. I am using singleEvent.

firebase.query((res) => {console.log(res.val()}, rootPath, query)

when I dump res, I am getting the result data, but res.val getting undefined. Is there any way I can get the data snapshot? am I doing something wrong here? 
I think its connected to [https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/188](url)

**Comment by EddyVerbruggen** [comment]
Is that the actual code you're using? If so then look at the docs https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/DATABASE.md#query, but if it's not please share the actual code.
