### ISSUE TITLE
Error in firebase.init: ReferenceError: Can't find variable: FIRApp

### ISSUE THREAD

**Issue by sean-perkins** [EddyVerbruggen/nativescript-plugin-firebase#76]
I feel like it's an issue with how I have configured the plugin, but after spending 2-3 hours on debugging; I am reaching out for help.

Dependency Version:
`"nativescript-plugin-firebase": "^3.4.3",`

Error Code:
```
Jul 17 13:41:40 [92254]: CONSOLE LOG file:///app/tns_modules/nativescript-plugin-firebase/firebase.js:310:18: Error in firebase.init: ReferenceError: Can't find variable: FIRApp
Jul 17 13:41:40 [92254]: CONSOLE LOG file:///app/main.js:17:16: firebase.init error: ReferenceError: Can't find variable: FIRApp
```

It is throwing errors on initialization.

main.ts

```
import firebase = require("nativescript-plugin-firebase");

firebase.init({
    // Optionally pass in properties for database, authentication and cloud messaging,
    // see their respective docs.
    storageBucket: 'gs://icebreaker-c8e62.appspot.com',
    persist: true,
    iOSEmulatorFlush: true
}).then(
    (instance) => {
        console.log("firebase.init done");
    },
    (error) => {
        console.log("firebase.init error: " + error);
    }
    );
```

The `GoogleService-Info.plist` file is located in `App_Resources/iOS/`

I have also attempted to drop and re-add the iOS platform:
-  `tns platform remove ios`
-  `tns platform add ios`

Which will produce the following log on emulation:
```
Successfully prepared plugin nativescript-angular for ios.
Successfully prepared plugin nativescript-intl for ios.
The iOS Deployment Target is now 8.0 in order to support Cocoa Touch Frameworks in CocoaPods.
Successfully prepared plugin nativescript-plugin-firebase for ios.
Successfully prepared plugin tns-core-modules for ios.
The iOS Deployment Target is now 8.0 in order to support Cocoa Touch Frameworks.
Successfully prepared plugin tns-core-modules-widgets for ios.
Installing pods...
Analyzing dependencies
Downloading dependencies
Installing Firebase (3.3.0)
Installing FirebaseAnalytics (3.2.1)
Installing FirebaseAuth (3.0.3)
Installing FirebaseCrash (1.0.6)
Installing FirebaseDatabase (3.0.2)
Installing FirebaseInstanceID (1.0.7)
Installing GoogleInterchangeUtilities (1.2.1)
Installing GoogleNetworkingUtilities (1.2.1)
Installing GoogleParsingUtilities (1.1.1)
Installing GoogleSymbolUtilities (1.1.1)
Installing GoogleUtilities (1.3.1)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `icebreaker.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There are 4 dependencies from the Podfile and 11 total pods installed.
```

`tns --version` is 2.1.1

The `GoogleService-Info.plist` is successfully copied to `platforms/ios/{project_name}/Resources/`.

I was able to get the sample app working correctly and cannot find out where the differences are between my implementation and the sample.

**Comment by sean-perkins** [comment]
Unsure why, but updating the configuration sets for xcode project resolved the issue. After switching both the debug and release to the pod.debug and pod.release targets; then switching back to the default builds, resolved the issue.

**Comment by diestrin** [comment]
@sean-perkins can you elaborate more on what you didi? I have been having this error all day and I'm about to get crazy. Tried everything but yours solution, because I don't understand what you did.

**Comment by sean-perkins** [comment]
@diestrin Please refer to this page: https://developer.apple.com/library/mac/recipes/xcode_help-project_editor/Articles/BasingBuildConfigurationsonConfigurationFiles.html

You will see drop downs in your xcode project, that allow you to change the build targets. When I was experiencing this issue, I changed the build target, built the project and then changed the build target back.
