### ISSUE TITLE
Question: analytics.setScreenName

### ISSUE THREAD

**Issue by jmfsilva** [EddyVerbruggen/nativescript-plugin-firebase#762]
Hello,

In the analytics documentation on the analytics.setScreenName you state that:
"By default Firebase will log the classname, but since all your NativeScript screens run inside the same UIViewController (iOS) / Activity (Android), the screenlogs won't be of much use. That's where this function comes in. Simply call setScreenName on every page your app routes to."

I'm doing an app using Nativescript Angular, so, to provide the screen name, on the components, i'm considering to call setScreenName in the constructor. But, i don't think this is a correct approach...

When i go from component A to B and then i press back button (ios) neither the constructor nor the OnInit, as expected, is called on back action. So, the last setScreenName that was called is the B component.

If i go from component A to B and back to A (back button), the screen name that will be registered in the events is the B name or the A name?

The underlying question is: is the setScreenName global to the app or it has the current component context in consideration?

If it is global, what is the correct strategy to get the proper screen name set?

**Comment by jmfsilva** [comment]
To solve this issue on angular nativescript i'v added to each route on its data object an id.
Then i subscribed to router events on app component: 
this.router.router.events
        .pipe(filter((event) => event instanceof ActivationEnd))
        .subscribe((event: ActivationEnd) => {
            this.analyticsService.setScreenName(event.snapshot.data.id);
        });

A filter to check if the id field exists can also be added if you'v routes that you dont want to be set.

**Comment by surdu** [comment]
I would also be interested where exactly to call `setScreenName` on a vanilla JS NativeScript page

**Comment by abhayastudios** [comment]
Hi @jmfsilva!

I am doing something similar where I set the screen name in the `AppComponent` based on the route name that I pass in the data like this:

```
private setFireBaseAnalytics() {
    this.routeSub = this.router.events
      .filter(event => event instanceof NavigationEnd)
      .map(() => this.route)
      .map(route => {
        while (route.firstChild) route = route.firstChild;
        return route;
      })
      .filter(route => route.outlet === 'primary')
      .mergeMap(route => route.data)
      .subscribe((data) => {
        // console.log(`Setting Analytics: ${data.name}`);
        if (data.hasOwnProperty('name')) {
          analytics.setScreenName({ screenName: data.name }).then(() => {
            console.log(`Analytics screen name set: ${data.name}`);
          });
        }
      })
    ;
  }
```

My question, however, is whether you got this to work properly? I see that the callback is fired properly, but I don't see the screen name show up in Firebase analytics? 

Thanks!

**Comment by jmfsilva** [comment]
On the Firebase Console if i select screen_view event, under user engagement if i pick Screen name i can see the components name from Angular.

**Comment by abhayastudios** [comment]
Thanks @jmfsilva!

The thing is that I go to the same place and under class name I see the generic classes, but under screen name it shows up empty. Do you see them immediately or do you need to wait for a while to accumulate?

**Comment by jmfsilva** [comment]
Firebase Analytics may take a 3h to 6h to update with new data. On the top right side of the screen there is a calendar to filter the data that is displayed by date. The default filter excludes the current day because the data is not displayed in really time, this is done to avoid incomplete data for current day to be displayed. You can select the current day on the filter, but you will not see real time logs anyway.

**Comment by abhayastudios** [comment]
Ok that might explain. Thanks again @jmfsilva!

**Comment by abhayastudios** [comment]
For anyone reading this later: in my case I had to explicitly set the `analyticsCollectionEnabled` property in `firebase.init()` to `true`. Apparently in my setup it defaulted to false somehow and once I had this in place it started to work.

**Comment by EddyVerbruggen** [comment]
Hi, which exact plugin version do you use? I think that default has been wrong in some versions, but in the latest few it should be ‘true’.

**Comment by abhayastudios** [comment]
Hey @EddyVerbruggen I am using `6.8.1`. Oh now I see you have been busy in the last two weeks... Well I guess the leaving the property there won't hurt... 

Thanks!

**Comment by EddyVerbruggen** [comment]
Hey man! Nope, won't hurt. I think indeed 6.8.1 was one of those few versions where the default was wrong.
