### ISSUE TITLE
Provide additionalUserInfos and metadata

### ISSUE THREAD

**Issue by RaphaelJenni** [EddyVerbruggen/nativescript-plugin-firebase#763]
Since a few months a new method on the `AuthResult` exists: `getAdditionalUserInfo()`.
It provides some details about the user and amongst other things the information if it is a new user.

https://firebase.google.com/docs/reference/android/com/google/firebase/auth/AuthResult.html#getAdditionalUserInfo()

This would be very helpful in the login flow to have the knowledge if the user just registered or not without having to go to the database and check for document existence.

I tested it out and check what there must be done:
Android:
- `toLoginResult` must take a second parameter to parse those additionalUserInfos
- all methods using the `toLoginResult` method need to be changed
 - `onCompleteListener`
 - `getCurrentUser`
 - `login`
 - `authStateChanged`

In addition to that it also would be nice to have access to the metadata of the user:
https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseUser.html#getMetadata()

@EddyVerbruggen What do you think? Should I create a PR for that? And how fast would it be in a live version?

**Comment by EddyVerbruggen** [comment]
A PR would be awesome, and it could be live pretty quickly, but it would also need to be added to the iOS version before I push it to npm.

**Comment by RaphaelJenni** [comment]
@EddyVerbruggen 
* Why do you use `signInWithCredentialCompletion` instead of `signInAndRetrieveDataWithCredentialCompletion`?
https://firebase.google.com/docs/reference/ios/firebaseauth/api/reference/Classes/FIRAuth#/c:objc(cs)FIRAuth(im)signInWithCredential:completion:

* And is there a reason, wyh you don't use the typescript types inside the firebase.*.ts files.

**Comment by RaphaelJenni** [comment]
- Ok, I had to migrate to `signInAndRetrieveDataWithCredentialCompletion` as the additional info are located on it
- I now added types to the user object but left the rest untouched

I'm currently testing it.

**Comment by RaphaelJenni** [comment]
@EddyVerbruggen I can't start the demo. Always get the `...google-services' not found.`

Already checked https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/278 but none of thos worked. Do I need to do some special stuff before running?

I did `deployment.setup` and `demo.android.linked`

**Comment by EddyVerbruggen** [comment]
Have you tried [this one](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/c3427fc8a20988f6fc4e0b7f6ff6925a820036f8/src/package.json#L45)?

**Comment by RaphaelJenni** [comment]
This one works, thanks. Was used to use the one with npm link, but that works as well :)

It already works on android. iOS I test now.

**Comment by RaphaelJenni** [comment]
@EddyVerbruggen Created a PR

**Comment by DSimonovski** [comment]
This still has problems, I have opened a new issue.
