### ISSUE TITLE
VueJS | TypeError: Cannot read property 'firebase' of undefined

### ISSUE THREAD

**Issue by shaqaruden** [EddyVerbruggen/nativescript-plugin-firebase#766]
I am using the nativescript-vue template. I have ran yarn add nativescript-plugin-firebase, followed by npm install and created the config file.

Here is my main,js file
```javascript
import Vue from 'nativescript-vue';
import router from './router';
import './styles.scss';
import firebase from 'nativescript-plugin-firebase';
// Uncommment the following to see NativeScript-Vue output logs
//Vue.config.silent = false;

new Vue({
  router,
}).$start();

```

when I build
```
yarn watch:android
```

I get a error
```
TypeError: Cannot read property 'firebase' of undefined
```

I have attempted

```javascript
var firebase = require("nativescript-plugin-firebase");
```

**Comment by shaqaruden** [comment]
I had uploaded the project to a personal git repo and cloned it at home (started working on it at work) and now it builds fine.

**Comment by bm2ilabs** [comment]
i am facing the same issue for a week no luck at all , could you please tell me the steps you did @shaqaruden

**Comment by shaqaruden** [comment]
I commented what I did. I’m not sure what about what I did fixed the issue. But quickly upload to a git repo and download into a new folder and run ‘npm install’

**Comment by jafsparrow** [comment]
Now I am getting this error. tried the solution given in github repo on app.gradle file.. nothing works.. Nativescript  is not stable yet??
