### ISSUE TITLE
Google access token?

### ISSUE THREAD

**Issue by johnRosalin** [EddyVerbruggen/nativescript-plugin-firebase#767]
Is there a way to get the google access token after logging in, just like in facebook where the token is included in the providers object?

**Comment by indradha** [comment]
submitted PR #880, and it's already merged :).
So it's should be solved solved

**Comment by EddyVerbruggen** [comment]
Yes, this can now be closed. Thanks for reporting, @johnRosalin, and many thanks for the PR, @indradha!
