### ISSUE TITLE
Compile error with Firestore Pod after upgrading to 6.0.1+

### ISSUE THREAD

**Issue by abhayastudios** [EddyVerbruggen/nativescript-plugin-firebase#768]
Hi @EddyVerbruggen!

I just updated my project to use version `6.3.0` of this plugin and now I get a compile error on iOS on this path `Pods/FirebaseFirestore/document.h`:
```
'Firestore/core/src/firebase/firestore/model/field_path.h' file not found
```

I get the same error even for `6.0.1`, but downgrading back to `5.3.1` fixes the issue.

Hoping there is an easy fix to this.

Thanks!

**Comment by EddyVerbruggen** [comment]
Hi @abhayastudios!

Have you tried removing the platforms/ios folder to make sure the native Firebase SDK is updated?

After doing so and building for iOS, the file should be here:

<img width="476" alt="screenshot 2018-06-27 at 21 22 49" src="https://user-images.githubusercontent.com/1426370/41994916-48014cec-7a50-11e8-91dc-0f711164d903.png">

**Comment by abhayastudios** [comment]
Hey man!

Yes I had removed the entire `platforms` directory before I tried...

I tried again now after upgrading to NS 4.1 and still get the same error, even though I confirmed that the file `platforms/ios/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/model/field_path.h` does exist!

Somehow I think there is an interaction effect with the SVGkit plugin that I am using. No idea though why the SVGkit would be using Firestore (and also why it starts to conflict when I upgrade this plugin, as said with `5.3.1` it worked fine in combination with SVGkit...).

```
In file included from /Users/joni/projects/june/nativescript/platforms/ios/Pods/SVGKit/Source/DOM classes/Unported or Partial DOM/SVGDescriptionElement.m:8:
In file included from /Users/joni/projects/june/nativescript/platforms/ios/Pods/SVGKit/Source/DOM classes/Unported or Partial DOM/SVGDescriptionElement.h:8:
In file included from /Users/joni/projects/june/nativescript/platforms/ios/Pods/SVGKit/Source/DOM classes/Unported or Partial DOM/SVGElement.h:10:
In file included from /Users/joni/projects/june/nativescript/platforms/ios/Pods/SVGKit/Source/DOM classes/Core DOM/Element.h:52:
/Users/joni/projects/june/nativescript/platforms/ios/Pods/SVGKit/Source/DOM classes/Core DOM/Node.h:114:64: warning: not a Doxygen trailing comment
      [-Wdocumentation]
@property(nonatomic,strong,readonly) NamedNodeMap* attributes; /*< NB: according to DOM Spec, this is null if the Node is NOT subclassed as a...
                                                               ^~~
                                                               /**<
1 warning generated.
In file included from /Users/joni/projects/june/nativescript/platforms/ios/Pods/SVGKit/Source/DOM classes/SVG-DOM/SVGDocument.m:9:
In file included from /Users/joni/projects/june/nativescript/platforms/ios/Pods/SVGKit/Source/DOM classes/Core DOM/Document+Mutable.h:1:
In file included from /Users/joni/projects/june/nativescript/platforms/ios/Pods/SVGKit/Source/DOM classes/Core DOM/Document.h:58:
/Users/joni/projects/june/nativescript/platforms/ios/Pods/SVGKit/Source/DOM classes/Core DOM/Node.h:114:64: warning: not a Doxygen trailing comment
      [-Wdocumentation]
@property(nonatomic,strong,readonly) NamedNodeMap* attributes; /*< NB: according to DOM Spec, this is null if the Node is NOT subclassed as a...
                                                               ^~~
                                                               /**<
In file included from /Users/joni/projects/june/nativescript/platforms/ios/Pods/SVGKit/Source/DOM classes/SVG-DOM/SVGDocument.m:11:
In file included from /Users/joni/projects/june/nativescript/platforms/ios/Pods/SVGKit/Source/DOM classes/SVG-DOM/SVGDocument.h:18:
/Users/joni/projects/june/nativescript/platforms/ios/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/model/document.h:20:10: fatal error:
      'Firestore/core/src/firebase/firestore/model/field_path.h' file not found
#include "Firestore/core/src/firebase/firestore/model/field_path.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 1 error generated.
```

Thanks :)

**Comment by abhayastudios** [comment]
I have created a little [test project](https://github.com/abhayastudios/svg_test) that demonstrates the issue.  It was a little test project for `nativescript-svg` which was working fine until I just added the `nativescript-plugin-firebase` even without actually using/initializing it, which then started giving the above error.

Wondering if there is anybody else who runs into it or if it is an environmental issue for me...

**Comment by abhayastudios** [comment]
The nativescript-svg plugin is hopelessly outdated and was causing issues on older Android devices as weel. I decided to migrate away from svg and use use bitmaps instead. Doing so also solved this weird interaction effect.

**Comment by b-m-9** [comment]
???
