### ISSUE TITLE
Xcode can't parse plist file

### ISSUE THREAD

**Issue by stevegardnersa** [EddyVerbruggen/nativescript-plugin-firebase#771]
Xcode 9.4
Nativescript: 4.1.0
tns-core-modules: 4.0.1
tns-android: 4.0.1
tns-ios: 4.0.1

nativescript-plugin-firebase: 6.0.2

I get a build error 

> Code Signing Error: Bundle identifier is missing. XXXXX doesn't have a bundle identifier for the Debug build configuration. Add a value for PRODUCT_BUNDLE_IDENTIFIER in the build settings editor.

I opened the project in Xcode and it indicates that it can't parse the plist file. To fix the problem... 

in _/node_modules/nativescript-plugin-firebase/platforms/ios/Info.plist_ I had to change...
```
<key>NSCameraUsageDescription</key>
<string/>
```

to

    <key>NSCameraUsageDescription</key>
    <string> </string>

For anyone wanting to fix this temporarily just add the following to your projects plist file

```
<key>NSCameraUsageDescription</key>
<string> </string>
```

**Comment by EddyVerbruggen** [comment]
Hmm, that's not good. I'll change it to what you have.

Btw, if you're actually using the camera in your app (ML Kit comes to mind), specify an actual reason to prevent Apple from rejecting your app during review.

**Comment by EddyVerbruggen** [comment]
Code updated, and [doc as well](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/78676d805cbb103f97aec06191c7698053cacaac/docs/ML_KIT.md#required-ios-permission).

**Comment by stevegardnersa** [comment]
Thanks Eddy! I'm not using the camera so all fine but good to keep in mind.

**Comment by wendt88** [comment]
But if you have [`nativescript-camera`](https://market.nativescript.org/plugins/nativescript-camera) or [`nativescript-barcodescanner`](https://market.nativescript.org/plugins/nativescript-barcodescanner) plugins installed, in the final `.plist` file `NSCameraUsageDescription` is empty and can't be uploaded to the Appstore (Xcode 11.3.1).

> **Missing Purpose String in Info.plist** - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSCameraUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data.

**Comment by EddyVerbruggen** [comment]
@wendt88 AFAIK you can always override those plist values in your project-level plist file (the one in app_resources/ios).

**Comment by wendt88** [comment]
sure... it isn't blocking, but you loose a lot of time to build, upload and find the error

**Comment by EddyVerbruggen** [comment]
OK - let me know (by comment or PR) if anything can be made better to prevent that.
