### ISSUE TITLE
iOS: onAuthStateChanged sometimes returns {} as user

### ISSUE THREAD

**Issue by RaphaelJenni** [EddyVerbruggen/nativescript-plugin-firebase#781]
iOS and Android do not work the same with the authStateListener.

Sometimes on iOS after login in with an account, the `authState.user` returns `{}` instead of the user.

Not sure where this error comes from.

**Comment by EddyVerbruggen** [comment]
Seems like there are cases (also on Android, when dynamic links are used) where the native object is returned to the JS layer. So where `console.log(user)` gives you `{}`, that's actually a native Firebase SDK User object which can't be serialized by the console logger.

I'll check all cases for both platforms and make sure a proper JS object is returned.

**Comment by EddyVerbruggen** [comment]
@RaphaelJenni Thanks for reporting this one. It's actually a very old issue, I'm a bit surprised this wasn't logged before.

The fix will be part of 6.3.1.
