### ISSUE TITLE
Unable to copy google-services.json.

### ISSUE THREAD

**Issue by peppeg85** [EddyVerbruggen/nativescript-plugin-firebase#782]
hello, this is another post on the "Unable to copy google-services.json"
i followed the documentation, copyed the google json file inside android and installed firebase like the documentation says.....but i have the following error: 

Executing after-prepare hook from D:\repository\xxx\hooks\after-prepare\firebase-copy-google-services.js
Unable to copy google-services.json.
Unable to apply changes on device: xxx. Error is: Failed to execute hook: D:\repository\xxx\hooks\after-prepare\firebase-copy-google-services.js..

i've updated nativescrcipt, i have 

	"tns-android": {
			"version": "3.4.3"
		}
and 
"tns-core-modules": "^4.1.0"

here is also the firebase configuration json: 

{
    "using_ios": true,
    "using_android": true,
    "firestore": false,
    "realtimedb": false,
    "remote_config": false,
    "messaging": true,
    "crashlytics": false,
    "crash_reporting": false,
    "storage": false,
    "facebook_auth": false,
    "google_auth": false,
    "admob": false,
    "invites": false,
    "ml_kit": false
}

could someone tell me where i am wrong?

thank you

**Comment by peppeg85** [comment]
hello, it was my fault,obviously, i copied the file in the right folder appRespources, but now i have the following error:

Unable to apply changes on device:xxxxx. Error is: Processing node_modules failed. Error: ENOENT: no such file or directory, lstat 'D:\repository\xxxx\node_modules\nativescript-plugin-firebase\node_modules\xcode\package.json'.

**Comment by EddyVerbruggen** [comment]
See my last comment in #701.
