### ISSUE TITLE
Combination with Vue.js: gradlew.bat failed with exit code 1

### ISSUE THREAD

**Issue by birthevdb** [EddyVerbruggen/nativescript-plugin-firebase#792]
In my app I combined Nativescript and Vue.js. When adding the Firebase plugin, I get the following exception:
```
Unable to apply changes on device: XXX Error is: Command gradlew.bat failed with exit code 1.
```

To make a simple Nativescript-Vue project, follow the instructions in [https://nativescript-vue.org/en/docs/getting-started/quick-start/](url) 

I followed the instructions from the video in this Github project, except for the adaptions in build.gradle, since this file is automatically generated when built.  

This is my package.json:
```
{
  "name": "test",
  "version": "1.0.0",
  "description": "A native application built with NativeScript-Vue",
  "author": "bird",
  "license": "MIT",
  "scripts": {
    "build": "webpack --env.tnsAction build",
    "build:android": "npm run build -- --env.android",
    "build:ios": "npm run build -- --env.ios",
    "debug": "webpack --watch --env.tnsAction debug",
    "debug:android": "npm run debug -- --env.android",
    "debug:ios": "npm run debug -- --env.ios",
    "watch": "webpack --watch --env.tnsAction run",
    "watch:android": "npm run watch -- --env.android",
    "watch:ios": "npm run watch -- --env.ios",
    "clean": "rimraf dist"
  },
  "dependencies": {
    "debug": "^3.1.0",
    "nativescript-camera": "^4.0.2",
    "nativescript-imagepicker": "^6.0.2",
    "nativescript-permissions": "^1.2.3",
    "nativescript-plugin-firebase": "^6.4.0",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-vue": "^1.3.1",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.4",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "copy-webpack-plugin": "^4.5.1",
    "css-loader": "^0.28.11",
    "extract-text-webpack-plugin": "^3.0.2",
    "fs-extra": "^5.0.0",
    "nativescript-vue-externals": "^0.2.0",
    "nativescript-vue-loader": "^0.1.5",
    "nativescript-vue-target": "^0.1.0",
    "nativescript-vue-template-compiler": "^1.3.1",
    "node-sass": "^4.7.2",
    "ns-vue-loader": "^0.1.2",
    "optimize-css-assets-webpack-plugin": "^3.2.0",
    "rimraf": "^2.6.2",
    "sass-loader": "^6.0.7",
    "vue-template-compiler": "^2.5.16",
    "webpack": "^3.11.0",
    "webpack-synchronizable-shell-plugin": "0.0.7",
    "winston-color": "^1.0.0",
    "tns-core-modules": "~3.4.1"
  }
}
```

**Comment by birthevdb** [comment]
Apparently the facebook_auth and google_auth in the firebase.nativescript.json file are the problem. Setting these to false solves the issue for me.

**Comment by polizinha** [comment]
I have same issue, but only with `"using_android": true`. 

`registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Unable to apply changes on device: 192.168.109.101:5555. Error is: Command gradlew.bat failed with exit code 1.`

**Comment by EddyVerbruggen** [comment]
@MrWizardGN Perhaps that patch in #858 also applies to your case. It helped that that person shared a repo with me.

**Comment by MrWizardGN** [comment]
Building project...
Gradle build...
spawn: gradlew.bat "assembleDebug" "-PcompileSdk=android-25" "-PtargetSdk=25" "-PbuildToolsVersion=27.0.3" "-PsupportVersion=25.3.1" "-PgenerateTypings=false"

> Configure project :app
         + setting applicationId
         + applying user-defined configuration from M:\VueProjects\matchmetest\template\app\App_Resources\Android\app.gradle
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
         + adding nativescript runtime package dependency: nativescript-optimized-with-inspector
         + adding aar plugin dependency: M:\VueProjects\matchmetest\template\node_modules\nativescript-plugin-firebase\platforms\android\firebase-release.aar
         + adding aar plugin dependency: M:\VueProjects\matchmetest\template\node_modules\tns-core-modules-widgets\platforms\android\widgets-release.aar
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

> Task :app:processDebugGoogleServices
Parsing json file: M:\VueProjects\matchmetest\template\platforms\android\app\google-services.json

C:\Users\Workspace\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.0.2.aar\87b89cc725715d8d0d4fa8a376bffc42\res\values-v26\values-v26.xml:9:5-12:13: AAPT: error: resource android:attr/colorError not found.

C:\Users\Workspace\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.0.2.aar\87b89cc725715d8d0d4fa8a376bffc42\res\values-v26\values-v26.xml:13:5-16:13: AAPT: error: resource android:attr/colorError not found.

C:\Users\Workspace\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.0.2.aar\87b89cc725715d8d0d4fa8a376bffc42\res\values-v26\values-v26.xml:17:5-93: AAPT: error: style attribute 'android:attr/keyboardNavigationCluster' not found.

C:\Users\Workspace\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.0.2.aar\87b89cc725715d8d0d4fa8a376bffc42\res\values\values.xml:252:5-69: AAPT: error: resource android:attr/fontStyle not found.

C:\Users\Workspace\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.0.2.aar\87b89cc725715d8d0d4fa8a376bffc42\res\values\values.xml:252:5-69: AAPT: error: resource android:attr/font not found.

C:\Users\Workspace\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.0.2.aar\87b89cc725715d8d0d4fa8a376bffc42\res\values\values.xml:252:5-69: AAPT: error: resource android:attr/fontWeight not found.

error: failed linking references.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Failed to process resources, see aapt output above for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
16 actionable tasks: 3 executed, 13 up-to-date
Unable to apply changes on device: emulator-5554. Error is: Command gradlew.bat failed with exit code 1.

@EddyVerbruggen here some additional logs. I really just got a fresh machine set up, then followed your instructions(using vue js and nativescript, so i just ran the quickstart here: https://nativescript-vue.org/en/docs/getting-started/quick-start/   and followed by your instructions)

**Comment by EddyVerbruggen** [comment]
@MrWizardGN That log doesn't ring a bell. If you want my help, share a repo.

**Comment by telcy** [comment]
I am having the same issue. Here is a repo: https://bitbucket.org/Telcy/vue-ns-firebase-test/src/master/

`tns plugin add nativescript-plugin-firebase` is not working in the root directory, so I have used `npm install --save nativescript-plugin-firebase`. Not sure what the correct procedure here is and would be really happy to get some more information here :) If I run `tns plugin add ...` in the template folder it creates 4 hook files. While running `npm install --save ...` in the root folder creates only 2 hook files. 

Nevertheless I end up with the same error:
`Unable to apply changes on device: xxx. Error is: Command gradlew.bat failed with exit code 1.`

**Comment by telcy** [comment]
Enabling multiDex helped. https://github.com/nativescript-vue/nativescript-vue/issues/313#issuecomment-415929657

**Comment by EddyVerbruggen** [comment]
Thanks for helping each other!

I've also been tinkering with the 2.0 template this weekend and those hook issues are no longer present because of the simpler project structure. It's as simple as the other frameworks now actually. [Here's the app](https://github.com/EddyVerbruggen/footplr) I'm building using Firestore, Cloud Functions, and the NativeScript-Vue 2.0 template.
