### ISSUE TITLE
Error while generating main dex list

### ISSUE THREAD

**Issue by neil-119** [EddyVerbruggen/nativescript-plugin-firebase#793]
There's some kind of incompatibility with nativescript-plugin-firebase and nativescript-lottie that I'm trying to figure out. I can't seem to include the two together (in a clean new nativescript project).

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithMultidexlistForRelease'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list.
```

Here's what my package.json looks like:
```
{
	"description": "NativeScript Application",
	"license": "SEE LICENSE IN <your-license-filename>",
	"readme": "NativeScript Application",
	"repository": "<fill-your-repository-here>",
	"nativescript": {
		"id": "org.nativescript.test",
		"tns-android": {
			"version": "4.1.3"
		}
	},
	"dependencies": {
		"@angular/animations": "~6.0.0",
		"@angular/common": "~6.0.0",
		"@angular/compiler": "~6.0.0",
		"@angular/core": "~6.0.0",
		"@angular/forms": "~6.0.0",
		"@angular/http": "~6.0.0",
		"@angular/platform-browser": "~6.0.0",
		"@angular/platform-browser-dynamic": "~6.0.0",
		"@angular/router": "~6.0.0",
		"nativescript-angular": "~6.0.0",
		"nativescript-lottie": "^2.1.0",
		"nativescript-plugin-firebase": "^6.4.0",
		"nativescript-theme-core": "~1.0.4",
		"reflect-metadata": "~0.1.8",
		"rxjs": "~6.1.0",
		"tns-core-modules": "~4.1.0",
		"zone.js": "^0.8.26"
	},
	"devDependencies": {
		"babel-traverse": "6.4.5",
		"babel-types": "6.4.5",
		"babylon": "6.4.5",
		"lazy": "1.0.11",
		"nativescript-dev-typescript": "~0.7.0",
		"typescript": "~2.7.2"
	}
}
```

And my app.gradle file:

```
dependencies {
  implementation 'com.android.support:multidex:1.0.3'
}

android {
  compileSdkVersion 27
  defaultConfig {  
    generatedDensities = []
    applicationId = "org.nativescript.test"
    multiDexEnabled true
  }  
  aaptOptions {  
    additionalParameters "--no-version-vectors"  
  }
  project.ext {
    googlePlayServicesVersion = "15.0.0"
  }
  dexOptions {
    javaMaxHeapSize "4g"
  }
}
```

I've been fiddling with the multidex issue for a while now. Any ideas? I should note that if I include one or the other in the package.json (not both), the build succeeds, and this only happens on **release** builds -- debug works fine.

**Comment by neil-119** [comment]
This took literally 9 hours out of my life (and 2 years off my lifespan) but I finally got it working. Hope this helps someone.

```
dependencies {
  implementation 'com.android.support:multidex:1.0.3'
  implementation 'com.android.support:design:27.1.0'
}

android {
  compileSdkVersion 27
  defaultConfig {
    minSdkVersion 17
    targetSdkVersion 27
    vectorDrawables.useSupportLibrary = true
    generatedDensities = []
    applicationId = "com.your_app.your_id"
    multiDexEnabled true
  }  
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_7
    targetCompatibility JavaVersion.VERSION_1_7
  }
  aaptOptions {  
    additionalParameters "--no-version-vectors"  
  }
  project.ext {
    googlePlayServicesVersion = "15.0.0"
  }
  dexOptions {
    javaMaxHeapSize "4g"
  }
}
```

**Comment by bdrobinson** [comment]
@neil-119 thanks very much for this! I had a similar issue upgrading to `react-native` 0.57 and adding in your `implementation 'com.android.support:design:27.1.0'` line seemed to fix it for me too. Do you know why that line was needed?

**Comment by abartolo** [comment]
Thank you @neil-119  and @bdrobinson. Adding the following code to my dependency works.

```
dependencies {
  ...
  implementation 'com.android.support:multidex:1.0.3'
  implementation 'com.android.support:design:27.1.0'
}
```

**Comment by mbajaria** [comment]
I am getting same error on buidling app
Execution failed for task ':app:transformClassesWithMultidexlistForProdRelease'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list.

Environment
react-native-cli: 2.0.1
react-native: 0.56.0

My **build.gradle** is 

buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.3'
        classpath 'com.google.gms:google-services:4.1.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven { url "https://jitpack.io" }
    }

}

task clean(type: Delete) {
    delete rootProject.buildDir
}

ext {
    minSdkVersion = 16
    compileSdkVersion = 27
    targetSdkVersion = 27
    buildToolsVersion = "27.0.3"
    supportLibVersion = "27.1.0"
    googlePlayServicesVersion = "15.0.1"
    gradle3EXPERIMENTAL = "yes"

}

subprojects{
    if(name.equals('react-native-google-analytics-bridge')){
        project.ext.'googlePlayServicesVersion'='12.0.1'
    }
}

My **app/build.gradle** is 

android {
    dexOptions {
        javaMaxHeapSize "4g"
    }
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion

    defaultConfig {

        applicationId "com.smarttimer"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 17
        versionName "3.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        multiDexEnabled=true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    aaptOptions {  
        additionalParameters "--no-version-vectors"  
    } 
    flavorDimensions "version"
    productFlavors {
        uat {
            resValue "string", "app_name", "Uat Timer"
            resValue "string", "content_provider", "com.smarttimer.uat.provider"
            resValue "string", "content_authority", "com.smarttimer.uat.provider"
        }
        prod {
            resValue "string", "app_name", "Smart Timer"
            resValue "string", "content_provider", "com.smarttimer.provider"
            resValue "string", "content_authority", "com.smarttimer.provider"
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    signingConfigs {
        release {
            storeFile file(MY_AWESOME_PROJECT_RELEASE_STORE_FILE)
            storePassword MY_AWESOME_PROJECT_RELEASE_STORE_PASSWORD
            keyAlias MY_AWESOME_PROJECT_RELEASE_KEY_ALIAS
            keyPassword MY_AWESOME_PROJECT_RELEASE_KEY_PASSWORD
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
    android.applicationVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "com.utopiatech.smart-timer.apk"
        }
    }
    project.ext {
        googlePlayServicesVersion = "15.0.0"
    }
}

dependencies {
    implementation project(':react-native-config')
    implementation project(':react-native-mauron85-background-geolocation')
    implementation project(':react-native-linear-gradient')
    implementation project(':react-native-google-analytics-bridge')
    implementation project(':react-native-firebase')
    implementation project(':react-native-device-info')
    implementation project(':react-native-camera')
    implementation project(':react-native-android-location-services-dialog-box')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:0.56.0"  // From node_modules
    implementation "com.google.android.gms:play-services-base:15.0.1"
    implementation "com.google.firebase:firebase-core:16.0.3"
    implementation "com.google.android.gms:play-services-analytics:15.0.2"
    implementation "com.google.firebase:firebase-messaging:17.3.0"
    implementation "com.android.support:multidex:1.0.3"
    implementation "com.android.support:design:27.1.0"
}


package.json is as below

{
  "name": "SmartTimer",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "rnpm": {
    "assets": [
      "./assets/fonts/Lato",
      "./assets/fonts/NotoSans",
      "./assets/fonts/NunitoSans"
    ]
  },
  "dependencies": {
    "axios": "^0.18.0",
    "find-cache-dir": "^2.0.0",
    "firebase": "^5.4.2",
    "firebase-messaging": "^1.0.6",
    "lodash": "^4.17.5",
    "moment": "^2.21.0",
    "moment-timezone": "^0.5.14",
    "native-base": "^2.3.10",
    "react": "^16.4.2",
    "react-moment": "^0.7.0",
    "react-native": "^0.56.0",
    "react-native-android-location-services-dialog-box": "^2.4.4",
    "react-native-camera": "^1.1.1",
    "react-native-config": "^0.11.5",
    "react-native-device-info": "^0.21.5",
    "react-native-firebase": "^4.3.8",
    "react-native-fontawesome": "^5.7.0",
    "react-native-google-analytics-bridge": "^5.6.3",
    "react-native-keyboard-aware-scroll-view": "^0.6.0",
    "react-native-linear-gradient": "^2.4.0",
    "react-native-loader": "^1.2.1",
    "react-native-mauron85-background-geolocation": "^0.5.0-alpha.40",
    "react-native-modal": "^6.2.0",
    "react-native-modal-dropdown": "^0.6.2",
    "react-native-phone-input": "^0.2.1",
    "react-native-pull-to-refresh": "^2.1.3",
    "react-native-router-flux": "^4.0.0-beta.28",
    "react-native-simple-popover": "^2.1.0",
    "react-native-vector-icons": "^5.0.0",
    "socket.io-client": "^2.0.4"
  },
  "devDependencies": {
    "babel-jest": "^23.0.0-alpha.0",
    "babel-preset-react-native": "^5.0.2",
    "jest": "^22.4.2",
    "metro": "^0.45.0",
    "metro-core": "^0.45.0",
    "react-test-renderer": "^16.3.0-alpha.2"
  },
  "jest": {
    "preset": "react-native",
    "transformIgnorePatterns": [
      "/node_modules/(?!native-base)/"
    ]
  }
}
