### ISSUE TITLE
OnAuthStateChanged android crash

### ISSUE THREAD

**Issue by kanclalg** [EddyVerbruggen/nativescript-plugin-firebase#795]
Hi, sometimes the app crashes when you call firebase.init method. Looks like it's crashing only on android. It started after nativescript-plugin-firebase version 6.3.0.

Error:
> Calling js method onAuthStateChanged failed TypeError: Cannot read property 'getCreationTimestamp' of null

Looks like it's this line and the return value of the getMetadata() is null:

> file: firebase.android.ts

> line: creationTimestamp: new Date(user.getMetadata().getCreationTimestamp() as number),

**Comment by EddyVerbruggen** [comment]
Thanks for reporting this one. It all sounds very plausible. I've added a `null` / `undefined` check.
