### ISSUE TITLE
Pass Query to Firebase ref

### ISSUE THREAD

**Issue by lelong37** [EddyVerbruggen/nativescript-plugin-firebase#8]
Thanks @EddyVerbruggen for your work, how do we pass a Query to Firebase?

**Comment by EddyVerbruggen** [comment]
At the moment the plugin has no convenient xplatform way to do that, but let me add it. Probably this weekend.

**Comment by EddyVerbruggen** [comment]
Hey @lelong37, I've added query support to version 2.0.0, please check out the [readme](https://github.com/EddyVerbruggen/nativescript-plugin-firebase#query).

Hope you like it!

**Comment by lelong37** [comment]
Thanks...!
