### ISSUE TITLE
Embedded Barcode Scanner not showing in Android < 6

### ISSUE THREAD

**Issue by seanstanden** [EddyVerbruggen/nativescript-plugin-firebase#802]
Hi folks,

I have successfully embedded the barcode scanner with the latest versions of Android without issue, but when I load the same view in devices running KitKat, the scanner doesn't show up.

Any idea why that might be the case? I don't get any errors in my console and haven't been able to find anything online so far.

Thanks in advance

**Comment by seanstanden** [comment]
Doesn't work with Lollipop (5.0) either. Works with Android 6.0+ though.

**Comment by hcgustavo** [comment]
Hey @seanstanden , have you found a solution for this issue? I'm facing the same problem. All works fine on the emulator (Android 8.1), but on my device which runs 5.0.1 the barcode scanner doesn't show up.

**Comment by EddyVerbruggen** [comment]
Hmm, I'm not surprised 4.4 has issues, but 5.x is unexpected. So the demo-ng app in this repo has the same issues? And `adb logcat` doesn't report anything either?

**Comment by hcgustavo** [comment]
@EddyVerbruggen Actually I'm using the vue-cli template. As for the adb logcat, there are a lot of things, but the camera called my attention as it is used by the scanner:

```08-14 11:44:07.114 926-1052/? E/CameraController: openCamera S
08-14 11:44:07.124 926-1052/? E/CameraController: sendMessageAndWait, lock.lock before
    sendMessageAndWait, lock.lock after
08-14 11:44:07.124 926-1183/? E/CameraController: handleMessage(1) before lock{ when=0 what=1 arg1=4 target=com.samsung.android.smartface.CameraController$EventHandler }
08-14 11:44:07.124 926-1052/? E/CameraController: Wait for 1
    waitHere, condition var. will be used. related lock release and re-acquired after await done.
08-14 11:44:07.124 926-1183/? E/CameraController: handleMessage, lock.lock after
    handleMessage(1) after lock{ when=-4ms what=1 arg1=4 target=com.samsung.android.smartface.CameraController$EventHandler }
08-14 11:44:07.134 926-1183/? E/CameraController: isCameraAllowed: true
    open() as 100
08-14 11:44:07.134 926-1183/? E/SecCamera-JNI-Java: SecCamera.open()
08-14 11:44:07.154 926-1183/? I/EDMNativeHelperService: isCameraEnabled
08-14 11:44:07.164 274-274/? D/SurfaceFlinger: FPS : 0.33
08-14 11:44:07.164 274-274/? W/SurfaceFlinger: Fail to Open /sys/devices/platform/gpusysfs/fps
08-14 11:44:07.164 302-6185/? E/CameraService: getStatus: Invalid camera ID 11
    orgID: 3 checkingID: 0 seems GOOD
    orgID: 3 checkingID: 1 seems GOOD
    orgID: 3 checkingID: 2 seems GOOD
    orgID: 3 checkingID: 3 seems GOOD
    orgID: 3 checkingID: 4 seems GOOD
08-14 11:44:07.164 302-6185/? E/QualcommCamera: Qint android::get_camera_info(int, camera_info*): E```

**Comment by EddyVerbruggen** [comment]
Looks like that message `Invalid camera ID 11` originates from the very bottom of [this class](http://newandroidbook.com/code/android-5.1.1_r24/frameworks/av/services/camera/libcameraservice/CameraService.cpp).

I'll look at some official samples by Google again when I find time.

**Comment by hcgustavo** [comment]
Ok, thanks.

**Comment by hcgustavo** [comment]
@EddyVerbruggen if it helps, digging into the plugin code (mlkit-cameraview.android.js: line 50), I see that the callback function `permissionCb_1` is never invoked when I use my device (Android 5.0.1). In fact, the permission dialog is never called at all, while in the emulator the dialog shows up nicely. Maybe something about `android.support.v4.app.ActivityCompat.requestPermissions` doesn't work for older versions?

**Comment by seanstanden** [comment]
@hcgustavo I haven't found a solution yet, for the time being I'm detecting the android version and using the previous (if inefficient) scanning method for older devices. Thanks for your efforts on this one folks.

**Comment by EddyVerbruggen** [comment]
Thanks for posting your findings here! I made a mistake: for Android < 6 there is no need to request runtime permissions (the user has already allowed those during app installation), and as the callback of `requestPermissions` is never called, the camera view never initializes.

So I'll just bypass the persmission check for older versions like I've done for many other plugins in the past.

**Comment by hcgustavo** [comment]
Glad I was of help. Thanks for looking into this!

**Comment by seanstanden** [comment]
Thanks @EddyVerbruggen! Love your work!
