### ISSUE TITLE
iOS app crashes after tapping an FCM notification if app is closed

### ISSUE THREAD

**Issue by erkanarslan** [EddyVerbruggen/nativescript-plugin-firebase#804]
If you close the application and get an FCM notification after that, tapping on the notification starts the app but app immediately crashes after launch screen.

This doesn't happen in Android. onMessageReceived callback is not called but app starts normally.

My lib versions:
tns-ios : 4.1.1
tns-android : 4.1.3
nativescript-plugin-firebase : 6.4.0
tns-core-modules : 4.1.0

**Comment by EddyVerbruggen** [comment]
2 questions: what’s the exact payload of the notification? And can you try the curl command in the plugin doc to see if that crashes the app as well? If it does, try with the demo app (non-ng) because I don’t think it happens there.

**Comment by erkanarslan** [comment]
I found out that problem is not related to the plugin.

I noticed that I initialize Firebase too early that when I get a notification, onMessageReceived callback is called before I fetch data from server. Because of that code in the onMessageReceived callback breaks as some of the data it requests is missing.

I initialize firebase after I fetch data from server and it works now.

**Comment by subashkv** [comment]
@erkanarslan Can you share the code that how you handle iOS crash issue when tap on the notification (app is closed)
