### ISSUE TITLE
Unable to update document using serverTimeStamp

### ISSUE THREAD

**Issue by bearoutthere** [EddyVerbruggen/nativescript-plugin-firebase#805]
Hey Eddy,
Had to create a new issue since the original was already closed.
I'm trying to use the latest FieldValue updates to add server timestamp to the document like so:

```
const transactionsCollection = firebase.firestore.collection("Transactions");
        transactionsCollection.add({
            accountPushKey: this.accountPushKey,
            credits: purchasedCredits,
            transactionId: transaction,
            voucherName: voucher
        })
        .then((documentRef) => {
            console.log("created transaction " + documentRef.id);
            documentRef.update({
                test: "test",
                transactionTimeStamp:  firebase.firestore.FieldValue.serverTimestamp()
            })
            .then(() => {
                // blah blah blah
                console.log("added timestamp");
            });
        });
```
'test' gets updated but not 'transactionTimeStamp'.
There are no errors in the debugger and when i look up objects i see the following.  My app is Nativescript with Typescript.  Not sure where to look next.  Could you take a quick look and point me in the right direction.  Thanks in advance.  

**firebase.firestore**

```
Object
__proto__:Object
_getDocumentReference:function (javaObj, collectionPath, documentPath) { … }
_getQuery:function (collectionPath, query) { … }
add:function (collectionPath, document) { … }
collection:function (collectionPath) { … }
delete:function (collectionPath, documentPath) { … }
doc:function (collectionPath, documentPath) { … }
FieldValue:function FieldValue() { … }
GeoPoint:function (latitude, longitude) { … }
get:function (collectionPath) { … }
getCollection:function (collectionPath) { … }
getDocument:function (collectionPath, documentPath) { … }
limit:function (collectionPath, limit, query) { … }
onCollectionSnapshot:function (colRef, callback) { … }
onDocumentSnapshot:function (docRef, callback) { … }
orderBy:function (collectionPath, fieldPath, direction, query) { … }
set:function (collectionPath, documentPath, document, options) { … }
update:function (collectionPath, documentPath, document) { … }
where:function (collectionPath, fieldPath, opStr, value, query) { … }
```

**firebase.firestore.FieldValue**
```
function FieldValue() { … }
```

**firebase.firestore.FieldValue()**  results in this Typescript error
```
[ts] Value of type 'typeof FieldValue' is not callable. Did you mean to include 'new'?
class firebase.firestore.FieldValue
```

**firebase.firestore.FieldValue.serverTimestamp**
```
undefined
```

**firebase.firestore.FieldValue.serverTimestamp()**
```
TypeError: firebase.firestore.FieldValue.serverTimestamp is not a function\n    at eval (eval at evaluate (:117:21), <anonymous>:1:31)\n    at file:///data/data/com.xxxxxx/files/app/shared/models/account-model.js:643:13
__proto__:Error
message:"firebase.firestore.FieldValue.serverTimestamp is not a function"
stack:"TypeError: firebase.firestore.FieldValue.serverTimestamp is not a function\n    at eval (eval at evaluate (:117:21), <anonymous>:1:31)\n    at file:///data/data/com.xxxxxx/files/app/shared/models/account-model.js:643:13"
firebase.firestore
```

**Comment by EddyVerbruggen** [comment]
Hard to tell without a repo, so please check these:

Is your import like this?
https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/91dec18d313be073171322760721d0d3d0a7762b/demo-ng/app/tabs/firestore/firestore.component.ts#L6

And the call like this?
https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/91dec18d313be073171322760721d0d3d0a7762b/demo-ng/app/tabs/firestore/firestore.component.ts#L125

And which platform(s) do you encounter the issue on?

**Comment by bearoutthere** [comment]
I use native option:  import firebase = require("nativescript-plugin-firebase");

Do i have to import Web API in order to use FieldValue?

**Comment by bearoutthere** [comment]
Bump.

**Comment by EddyVerbruggen** [comment]
I’m on vacation. Just do whatever the demo app does.

**Comment by bearoutthere** [comment]
Didn't realize that.  Sorry to bother you.  Could you take a look when you get back please?  Would really like to avoid refactoring to use web api syntax.

**Comment by EddyVerbruggen** [comment]
Vacation update: with 6.4.1 you can now use the non-webapi as well. [Here are both examples (mind the imports)](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/474182c0fdd4f7b145d06cbd22bb5c28a0b80f2d/demo-ng/app/tabs/firestore/firestore.component.ts#L125-L126).

**Comment by bearoutthere** [comment]
Thank you very much.

**Comment by spencercap** [comment]
@EddyVerbruggen thanks so much for adding this feature! 💯

any chance `arrayUnion` and `arrayRemove` can be added too? they're documented at the bottom of [this page of the firestore docs](https://firebase.google.com/docs/firestore/manage-data/add-data).

**Comment by EddyVerbruggen** [comment]
@spencercap You're welcome! Would you mind opening a new issue for this feature request? It seem like something I could add pretty easily.

**Comment by spencercap** [comment]
@EddyVerbruggen sure thing, see issue #922
