### ISSUE TITLE
Support for Firebase 'Callable' functions 

### ISSUE THREAD

**Issue by breningham** [EddyVerbruggen/nativescript-plugin-firebase#806]
Seems that there's this new firebase functions feature, call-able functions. 
Read: https://firebase.google.com/docs/functions/callable

Seems like it would be pretty simple to implement.

**Comment by EddyVerbruggen** [comment]
Can you be more specific about what you need and how you’d use it? Directly links to the sdk docs are also much appreciated. Thx.

**Comment by breningham** [comment]
Ok So Callable functions are new with Firebase, allows you to call Firebase Functions from directly within your code with all Firebase Authentication and FCM tokens included automatically (when available). 

The Link above is the Current SDK Link, has instructions for Android and IOS.

**Comment by EddyVerbruggen** [comment]
Sounds good, thanks. I'm on vacation so don't currently have the time to implement it, but looking at the page you linked to it's rather easy to add to this plugin.

**Comment by EddyVerbruggen** [comment]
FYI I've altered the script in package.json to generate the typings for Android. Also pushed the Cloud Functions typings to the repo, and added logic to the installation script to add the Functions libraries if the user wants them.
