### ISSUE TITLE
I can not install version 6.4.1 through NPM.

### ISSUE THREAD

**Issue by marcelomiranda90** [EddyVerbruggen/nativescript-plugin-firebase#808]
Hello Eddy,

I am having the problem of onAuthStateChanged on android and I saw that you have already corrected, however I can not use version 6.4.1, am I doing something wrong?

Your work is excellent, thank you very much.

**Comment by EddyVerbruggen** [comment]
Thanks!

6.4.1 is not on npm yet because I have to finish some work still. And then vacation happened. I'll try to publish it in the next few days though.
