### ISSUE TITLE
Support for Cloud Messaging Topics 

### ISSUE THREAD

**Issue by mattpcaswell** [EddyVerbruggen/nativescript-plugin-firebase#81]
It would be awesome to be able to use [topics](https://firebase.google.com/docs/cloud-messaging/topic-messaging). This is an amazing plugin and you're the best

**Comment by EddyVerbruggen** [comment]
Thanks! Sounds like a nice enhancement.

Deeplinks to the examples for my own reference (or anyone that likes to jump on this feature request):

[iOS](https://firebase.google.com/docs/cloud-messaging/ios/topic-messaging)
[Android](https://firebase.google.com/docs/cloud-messaging/android/topic-messaging)

**Comment by hvadotnarola** [comment]
Is there method to handle `notification` type and `data` type notification ?

**Comment by Daxito** [comment]
+1

**Comment by EddyVerbruggen** [comment]
Done in #262.
