### ISSUE TITLE
App not working on Android version below v7

### ISSUE THREAD

**Issue by abhayastudios** [EddyVerbruggen/nativescript-plugin-firebase#812]
I am running into an issue where the app that I built using this plugin does not work on Android 5 or 6, but works fine on Android 7+. I think it is related to #810, however I am not sure I completely understand the implications, so I was hoping someone could help me out here.

Please find the `app.gradle` that I use below, which contains two adaptions from the default that I had to make to be able to use this plugin: `multiDexEnabled`, `googlePlayServicesVersion` & `supportVersion`.

Am I correct to assume that setting the support version means that anything below level 26 is not supposed to work? If so, then how come the app works fine on Android 7 which is level 24 & 25 from what I can understand?

Is there a way to make it work with levels lower than that? I have already received some feedback from users that my app "hangs" on boot (where I initialise this plugin), all of which are on Android 5 or 6. Therefore, it seems these older Android versions are still in use quite a lot. I know they are quite old already, but obviously it is out of my control. How do others cope with this? I would be very happy if I would be able to add support for only Android 6 even.

```
android {
  defaultConfig {
    generatedDensities = []
    applicationId = "com.abhayastudios.myapp"
    multiDexEnabled true // required for Firestore dependencies
  }
  aaptOptions {
    additionalParameters "--no-version-vectors"
  }

  // required to make the firebase and geolocation plugins play nice together
  // see: https://github.com/NativeScript/nativescript-geolocation/issues/81
  project.ext {
    googlePlayServicesVersion = "12.0.1"
    supportVersion = "26.0.0"
  }
}
```

**Comment by tomcatmwi** [comment]
I am using it on a Samsung J1 with Android 6.0.1. I just found the solution for #810, it may be the same for you. My app uses API 27.

**Comment by abhayastudios** [comment]
Turns out that my specific problem is related to another plugin... @tomcatmwi thanks anyway for the help as I learned some things on the way!
