### ISSUE TITLE
Admob RangeError: Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by marcelomiranda90** [EddyVerbruggen/nativescript-plugin-firebase#813]
I'm calling the banner display after the firebase init.
The problem apparently only happens in IOS, I'm using a 5s physical device with iOS 11.4.

```
firebase.init({
      storageBucket: 'gs://controle-bovespa.appspot.com',
      onAuthStateChanged: (data) => { // optional but useful to immediately re-logon the user when he re-visits your app
        if (data.loggedIn) {
          this.auth_data = data.user;
        }
      }
    }).then(
      instance => {
        console.log("firebase.init done");
        setTimeout(() => {
          this.showAdMobBanner();
        }, 5000);
      },
      error => {
        console.log(`firebase.init error: ${error}`);
      }
    );
```

```
 showAdMobBanner() {
    firebase.admob.showBanner({
      testing: true,
      size: firebase.admob.AD_SIZE.SMART_BANNER, // see firebase.admob.AD_SIZE for all options
      margins: { // optional nr of device independent pixels from the top or bottom (don't set both)
        bottom: 0
      },
      androidBannerId: "ca-app-pub-...",
      iosBannerId: "ca-app-pub-...",
      iosTestDeviceIds: ["5543fab05f1d3f8d82f..."]

    }).then(
      () => {
        console.log("AdMob banner showing");
      },
      (errorMessage) => {
        console.log(errorMessage);
      }
    );
  }
```

When the app starts, it sometimes freezes and only responds again after this error message.
I think it might be something with a webpack too.

CONSOLE LOG file:///app/vendor.js:45874:24: Error in firebase.admob.showBanner: RangeError: Maximum call stack size exceeded.
CONSOLE ERROR file:///app/vendor.js:42774:30: Unhandled Promise rejection: Maximum call stack size exceeded. ; Zone: <root> ; Task: Promise.then ; Value: RangeError: Maximum call stack size exceeded. merge@file:///app/vendor.js:45061:44
merge@file:///app/vendor.js:45062:51
merge@file:///app/vendor.js:45062:51
merge@file:///app/vendor.js:45062:51
merge@file:///app/vendor.js:45062:51
merge@file:///app/vendor.js:45062:51
merge@file:///app/vendor.js:45062:51
merge@file:///app/vendor.js:45062:51
merge@file:///app/vendor.js:45062:51
merge@file:///app/vendor.js:45062:51
merge@file:///app/vendor.js:45062:51
merge@file:///app/vendor.js:45062:51
merge@file:///app/vendor.js:45062:51
merge@file:///app/vendor.js:45062:51
merge@file:///app/vendor.js:45062:51
merge@file:///app/vendor.js:45062:51
merge@file:///app/vendor.js:45062:51
merge@file:///app/vendor.js:45062:51
merge@file:///app/vendor.js:45062:51
merge@file:///app/vendor.js:45062:51
merge@file:///app/vendor.js:45062:51
merge@file:///app/vendor.js:45062:51

**Comment by EddyVerbruggen** [comment]
Hmm extremely hard to tell with those webpacked bundles. Looks some kind of recurrence issue but without knowing which line(s) cause(s) the issue it's hard to tell. Perhaps there's something at `app/vendor.js:45062:51` which points in the right direction?

**Comment by marcelomiranda90** [comment]
line 45.062
`                result = result || GIDSignIn.sharedInstance().handleURLSourceApplicationAnnotation(url, sourceApplication, annotation);`


```
    // there's no notification event to hook into for this one, so using the appDelegate
    if (typeof (FBSDKApplicationDelegate) !== "undefined" || typeof (GIDSignIn) !== "undefined" || typeof (FIRInvites) !== "undefined" || typeof (FIRDynamicLink) !== "undefined") {
        appDelegate.prototype.applicationOpenURLSourceApplicationAnnotation = function (application, url, sourceApplication, annotation) {
            var result = false;
            if (typeof (FBSDKApplicationDelegate) !== "undefined") {
                result = FBSDKApplicationDelegate.sharedInstance().applicationOpenURLSourceApplicationAnnotation(application, url, sourceApplication, annotation);
            }
            if (typeof (GIDSignIn) !== "undefined") {
                result = result || GIDSignIn.sharedInstance().handleURLSourceApplicationAnnotation(url, sourceApplication, annotation);
            }
            if (typeof (FIRInvites) !== "undefined") {
                var receivedInvite = FIRInvites.handleURLSourceApplicationAnnotation(url, sourceApplication, annotation);
                if (receivedInvite) {
                    console.log("Deep link from " + sourceApplication + ", Invite ID: " + receivedInvite.inviteId + ", App URL: " + receivedInvite.deepLink);
                    firebase_common_1.firebase._cachedInvitation = {
                        deepLink: receivedInvite.deepLink,
                        matchType: receivedInvite.matchType,
                        invitationId: receivedInvite.inviteId
                    };
                    result = true;
                }
            }
            if (typeof (FIRDynamicLink) !== "undefined") {
                var dynamicLink = FIRDynamicLinks.dynamicLinks().dynamicLinkFromCustomSchemeURL(url);
                if (dynamicLink) {
                    console.log(">>> dynamicLink.url.absoluteString: " + dynamicLink.url.absoluteString);
                    firebase_common_1.firebase._cachedDynamicLink = {
                        url: dynamicLink.url.absoluteString,
                        matchConfidence: dynamicLink.matchConfidence,
                        minimumAppVersion: dynamicLink.minimumAppVersion
                    };
                    result = true;
                }
            }
            return result;
        };
    }
```

**Comment by marcelomiranda90** [comment]
Eddy, I did some more tests and it seems to be something with angular, the problem occurs more easily when we use the rotation of the device.

In android everything is ok, on iOS 11.4 iPhone 5s I'm having trouble.

I downloaded the nativescript demo and modified the code tab.component.ts to:

```
import { Component, OnInit } from "@angular/core";
import { isAndroid } from "platform";
import { SelectedIndexChangedEventData, TabView } from "tns-core-modules/ui/tab-view";

const firebase = require("nativescript-plugin-firebase");

@Component({
  selector: "TabsComponent",
  moduleId: module.id,
  templateUrl: "./tabs.component.html"
})
export class TabsComponent implements OnInit {
  private _title: string;

  constructor() {
    // Use the component constructor to inject providers.
  }

  ngOnInit(): void {
    // Init your component properties here.
    this.showAdMobBanner();
  }

  get title(): string {
    return this._title;
  }

  set title(value: string) {
    if (this._title !== value) {
      this._title = value;
    }
  }

  getIconSource(icon: string): string {
    return isAndroid ? "" : "res://tabIcons/" + icon;
  }

  onSelectedIndexChanged(args: SelectedIndexChangedEventData) {
    const tabView = <TabView>args.object;
    const selectedTabViewItem = tabView.items[args.newIndex];

    this.title = selectedTabViewItem.title;
  }

  showAdMobBanner() {
    setTimeout(() => {
      console.log("AdMob banner init");
      firebase.admob.showBanner({
        testing: true,
        size: firebase.admob.AD_SIZE.SMART_BANNER, // see firebase.admob.AD_SIZE for all options
        margins: { // optional nr of device independent pixels from the top or bottom (don't set both)
          bottom: 0
        },
        iosBannerId: "ca-app-pub-3940256099942544/2934735716", //id test admob
        androidBannerId: "ca-app-pub-3940256099942544/6300978111", //id test admob
        iosTestDeviceIds: [ //Android automatically adds the connected device as test device with testing:true, iOS does not
          "uuid device test",
        ],
      }).then(
        () => {
          console.log("AdMob banner showing");
        },
        (errorMessage) => {
          console.log(errorMessage);
        }
      );

    }, 2000);
  }

}

```

Modify firebase.nativescript.json to enable admob, reinstall the plugin, run tns prepare ios --bundle --env.aot and start the project with xcode.
![whatsapp image 2018-07-28 at 20 27 24](https://user-images.githubusercontent.com/30594073/43361460-6da04fc6-92a5-11e8-8797-00ed4bbd319f.jpeg)
![whatsapp image 2018-07-28 at 20 27 24 1](https://user-images.githubusercontent.com/30594073/43361463-7226ff36-92a5-11e8-9ad5-f4dc416bef09.jpeg)
![captura de tela 2018-07-28 as 20 24 27](https://user-images.githubusercontent.com/30594073/43361466-797eefbe-92a5-11e8-898c-b15454f69224.png)

I will continue doing test to find more details, using the admob project demo that is not angular everything worked fine.

**Comment by marcelomiranda90** [comment]
Hello Eddy, do you have any suggestions for me to try to solve this problem? Thank you.

**Comment by MustafaCa** [comment]
Hi Eddy, 

I am having the same issue on a project based on NativeScript Vue. The app freezes for ~30sec to a min until the message "Error in firebase.admob.showBanner: RangeError: Maximum call stacksize exceeded." appears. 

I observe the issue mostly on HW devices (iPhone 7 and iPhone 8). However, I just confirmed that it also happens on the iOS simulator - iPhone 7 Plus.

Really appreciate any suggestion to resolve this. Thank you!

**Comment by EddyVerbruggen** [comment]
Even with the nativescript-admob code applied I get that error - I've removed this logic for now.
