### ISSUE TITLE
How to know if user is logged in and get its data.

### ISSUE THREAD

**Issue by IvRRimum** [EddyVerbruggen/nativescript-plugin-firebase#82]
Recently started using your plugin.

i init a listener, like in your tutorial. But how do i make a if statement check, if a person is logged in. and how do i get the users data ? documentation should be updated.

**Comment by IvRRimum** [comment]
firebase.getCurrentUser()

**Comment by jlooper** [comment]
hi, you can check out the Groceries app on the angular-firebase branch to see how your use case is implemented. Eddy's documentation may not be the right place to explain how to build out specific use cases. http://www.github.com/nativescript/sample-Groceries

**Comment by IvRRimum** [comment]
Hello, i think i will stick with my way for now. But when i inspect the example of receaveing list of data( multiple entries ), i dont really get it ?

How can you push the data into a protocol( the Groceries class ), if you receave keys and values 1 by 1( from nativescript-plugin-firebase ) ?

**Comment by IvRRimum** [comment]
this is what i am getting from the call:

`[{"id":"date"},{"id":"deleted"},{"id":"description"},{"id":"category_id"},{"id":"id"},{"id":"user_id"},{"id":"path"}]`

**Comment by IvRRimum** [comment]
Ooooooooohhhh, i think i got it. Firebase works different than i thinked. THANKS!

**Comment by IvRRimum** [comment]
My structure was as following:

Base:
  photos:
    id: 1,
    name: "hello there",
    ...

But should have been:

Base:
  photos:
    0:
      id: 1,
      name: "hello there",
      ...
    1:
      ...

**Comment by jlooper** [comment]
Glad you got it sorted! :)

**Comment by vivex** [comment]
@jlooper  angular-firebase branch is no more there http://www.github.com/nativescript/sample-Groceries
