### ISSUE TITLE
Ability to use array-contains in .where query

### ISSUE THREAD

**Issue by psrcek** [EddyVerbruggen/nativescript-plugin-firebase#830]
firestore.collection(whatever).where('foo', 'array-contains', 'bar').whatever();

It is now in the API:
https://github.com/googleapis/nodejs-firestore/pull/270
https://firebase.google.com/support/release-notes/js

I would make a PR, but I can't seem to find it in the source.

**Comment by EddyVerbruggen** [comment]
This feature is for the JS SDK, so we need to wait for their native SDKs to support it as well.

- iOS support was added in 5.5.0 [changelog](https://firebase.google.com/support/release-notes/ios), aug 2, 2018.
- Android support is not released yet - I see no mention in the [changelog](https://firebase.google.com/support/release-notes/android).

**Comment by EddyVerbruggen** [comment]
iOS is now done. There is no word on array_contains support in the Android SDK though.

**Comment by EddyVerbruggen** [comment]
Ha, there it is! [check the August 13 update](https://firebase.google.com/support/release-notes/android). Will add this soon.

**Comment by EddyVerbruggen** [comment]
Done. Docs here: https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/FIRESTORE.md#collectionwhere
