### ISSUE TITLE
JS ERROR TypeError: null is not an object

### ISSUE THREAD

**Issue by psrcek** [EddyVerbruggen/nativescript-plugin-firebase#835]
**EDIT:** only occurs on iOS
**EDIT 2:** only occurs when there is array data in the document that is being read

When I open the page an error occurs:
```
JavaScript error:
file:///app/tns_modules/nativescript-plugin-firebase/firebase.js:2143:37: JS ERROR TypeError: null is not an object (evaluating 'snapshot.documents')
```
what i used:
```typescript
import { firestore } from 'nativescript-plugin-firebase';

export class WhateverPage implements OnInit{
    // ... removed unrelated code
    
    notesCollection = firestore.collection(`/dt/${this.storage.user.serverId}/dailyInflow`);

    canReadNotesDoc = firestore.collection(`/dt`).doc(`${this.storage.user.serverId}`);
 
    unsubNotes: () => void;

    subNotes() {
        this.unsubNotes = this.notesCollection.onSnapshot(snap => {
            this.notes = snap.docSnapshots.map(doc => doc.data());
            this.changeDetectorRef.detectChanges();
        });
    }
    
    ngOnInit() {
        this.canReadNotesDoc.onSnapshot(canReadDoc => {
            if (canReadDoc.data().dif_read_temp.indexOf(this.storage.user.userName) != -1) {
                this.canReadNotes = true;
                this.subNotes();
            } else {
                this.canReadNotes = false;
                try {
                    this.subNotes();
                } catch (e) {
                    // do nothing if not already subscribed.
                }

                if (this.displayMode == 'NOTES') {
                    this.displayMode = 'ALL'
                    this.changeDetectorRef.detectChanges();
                }
            }
        });
    }

    // ... Removed unrelated code
}
```

**Comment by ppulwey** [comment]
+1

**Comment by EddyVerbruggen** [comment]
Which line is the issue, and can you share a screenshot of the problematic data in the Firebase console?

**Comment by psrcek** [comment]
> Which line is the issue?
```
JavaScript error:
file:///app/tns_modules/nativescript-plugin-firebase/firebase.js:2143:37: JS ERROR TypeError: null is not an object (evaluating 'snapshot.documents')
```
That would be line 2143.

> can you share a screenshot of the problematic data in the Firebase console?

I've changed the data now to get around this, so no, but I've recreated it (looked something like this):
![image](https://user-images.githubusercontent.com/13370323/44027385-a29f42ba-9ef6-11e8-8bf0-87e88e153ff2.png)
If i removed the rd array, it would work.

**Comment by EddyVerbruggen** [comment]
Thanks for the details. I suspect it's an issue in the Firebase SDK actually because array support was added more recently and the SDK referred to in this plugin is a bit older.

I just tested this with the upcoming 6.5.0 release which updates to the latest SDK:

<img width="969" alt="screenshot 2018-08-13 at 13 39 03" src="https://user-images.githubusercontent.com/1426370/44029706-84bc5622-9efe-11e8-89bb-4c92df7f43e8.png">

**Comment by ppulwey** [comment]
@EddyVerbruggen Is there a workaround to receive array data?

**Comment by EddyVerbruggen** [comment]
Wait a little for the new release. Trying to get more changes in..
