### ISSUE TITLE
firebase.firestore().collection no longer working

### ISSUE THREAD

**Issue by birthevdb** [EddyVerbruggen/nativescript-plugin-firebase#841]
I'm using firebase in combination with Nativescript and Vue. I have the following code:

```
function loadAllImages() {
    console.log('loading images...');
    const imageRef = firebase.firestore.collection('images');
    return imageRef.get().then(function (querySnapshot) {
        if (!querySnapshot.exists) {
            console.log("no query snapshot!")
        }
        const images = [];
        querySnapshot.forEach(function (doc) {
            console.log(JSON.stringify(doc.data()));
            const data = doc.data();
            images.push(data.base64image);
        });
        return images;
    });
```

My firebase console looks as follows: 

![image](https://user-images.githubusercontent.com/17502534/43905849-37182572-9bf2-11e8-8842-348b9ea12eb1.png)

About a week ago this code worked fine, today it doesn't since the querySnapshot is empty (returning "no query snapshot!"). Did the plugin change this week or am I doing something wrong?

**Comment by EddyVerbruggen** [comment]
If a change in the plugin broke your app then you'll want to open `package.json` and pin the plugin (all deps) to a certain version. If you actually have it pinned to a specific version then it can't be a plugin issue. In any case: what's the version string you're using?

**Comment by birthevdb** [comment]
I'm currently using version 5.2.0

**Comment by EddyVerbruggen** [comment]
Can you screenshot your package.json for me? The bit where `nativescript-plugin-firebase` is included.

**Comment by birthevdb** [comment]
![image](https://user-images.githubusercontent.com/17502534/43906708-3bd0e6a6-9bf4-11e8-99e0-0d44c2475a89.png)

**Comment by EddyVerbruggen** [comment]
Yeah that's what I figured. With "^5.2.0" in package.json you might as well have 5.3.1 in your node_modules. If you want to be sure you have 5.2.0 you'll have to remove that caret.

Especially if you share this project with others and other computers you're in trouble when pinning to the major version like that.

That being said, if there is a problem with Firestore it may have been solved in a more recent version. Just update to the latest one and check the demo apps please.
