### ISSUE TITLE
angular firebase init issue on Android - "Run init() first!"

### ISSUE THREAD

**Issue by janossuta** [EddyVerbruggen/nativescript-plugin-firebase#845]
Hi,

Could you please help me with this issue?
I tried initialize the plugin in the main.ts but I got the "Run init() first" error message. 
I have read the #613 but I couldn't manage to make it work.

I got the init done message 
JS: firebase.init done
but after this
JS: Error: Run init() first!

```javascript
const firebase = require("nativescript-plugin-firebase");

setTimeout(()=>{  firebase.init({
    // Optionally pass in properties for database, authentication and cloud messaging,
    // see their respective docs.
    persist:false,
  }).then(
    instance => {
      console.log("firebase.init done");
    },
    error => {
      console.log(`firebase.init error: ${error}`);
    }
  );  },1000);
```
and I try to use like this:

```javascript
    getData(){ 
        firebase.getValue('/books')
        .then(result => console.log(JSON.stringify(result)))
        .catch(error => console.log("Error: " + error));
    }
```

**Comment by EddyVerbruggen** [comment]
Looks like getData runs before init.

**Comment by janossuta** [comment]
I call getData() from a button

like this: 
`<Button class="btn btn-primary" text="getData" (tap)="getData()" ></Button>`

**Comment by EddyVerbruggen** [comment]
Please share a repo reproducing this, because something's not quite right here.

**Comment by janossuta** [comment]
Is this enough?
https://github.com/janossuta/nativescriptDemoApp

**Comment by EddyVerbruggen** [comment]
I don't endorse running `init` in a timeout at main.ts. Can you try removing the timeout or moving `init` to the first actual component that loads?

**Comment by janossuta** [comment]
I moved the init into the about component but still the same

```javascript
import { Component, OnInit } from "@angular/core";
import * as camera from "nativescript-camera";
import { Image } from "ui/image";

const firebase = require("nativescript-plugin-firebase");

@Component({
    selector: "About",
    moduleId: module.id,
    templateUrl: "./about.component.html"
})
export class AboutComponent implements OnInit {

public source:string = null;

    constructor() {
        // Use the component constructor to inject providers.     
    }

    ngOnInit(): void {
        // Init your component properties here.    
        
        firebase.init({
            // Optionally pass in properties for database, authentication and cloud messaging,
            // see their respective docs.
            persist:false,
          }).then(
            instance => {
              console.log("firebase.init done");
            },
            error => {
              console.log(`firebase.init error: ${error}`);
            }
          );
   
    }   

    takeApicture(){
        camera.requestPermissions().then(()=>{
            camera.takePicture().
            then((imageAsset) => {
                console.log("Result is an image asset instance");
                let image = new Image();
                image.src = imageAsset;
                this.source = image.src;
            }).catch((err) => {
                console.log("Error -> " + err.message);
            });
        },()=>{
            console.log("Permission rejected!");
        });     
    }

    getData(){ 
        firebase.getValue('/books')
        .then(result => console.log(JSON.stringify(result)))
        .catch(error => console.log("Error: " + error));
    }
}

```

**Comment by janossuta** [comment]
Yes I did see them and 
this is inside my `firebase.nativescript.json`:

{
    "using_ios": false,
    "using_android": true,
    "firestore": false,
    "realtimedb": true,
    "remote_config": false,
    "messaging": true,
    "crashlytics": false,
    "crash_reporting": false,
    "storage": true,
    "facebook_auth": false,
    "google_auth": false,
    "admob": true,
    "invites": false,
    "ml_kit": false
}

I installed with this command 
`tns plugin add nativescript-plugin-firebase`

**Comment by EddyVerbruggen** [comment]
That's all perfectly fine. Can you remove the platforms/android folder and run `tns run android` again?

**Comment by janossuta** [comment]
I did that a couple of times but still the same :( 

I used sidekick and propt as well but always the same result.

Is there a repo with working demo in angular nativescript?

**Comment by EddyVerbruggen** [comment]
The demo-ng folder. Using it all the time. Clone the repo, go to the `src` folder and run `npm i` and `npm run demo-ng.android`.

**Comment by janossuta** [comment]
I couldn't manage to run you demo-ng app I got a lot of errors, but I copied your implementation to my code but nothing changed.

I'm using the latest version of nativescript and your plugin.

this is my package.json

```javascript
{
  "nativescript": {
    "id": "org.nativescript.DemoApp",
    "tns-android": {
      "version": "4.2.0"
    },
    "tns-ios": {
      "version": "4.2.0"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "@angular/animations": "~6.1.0",
    "@angular/common": "~6.1.0",
    "@angular/compiler": "~6.1.0",
    "@angular/core": "~6.1.0",
    "@angular/forms": "~6.1.0",
    "@angular/http": "~6.1.0",
    "@angular/platform-browser": "~6.1.0",
    "@angular/platform-browser-dynamic": "~6.1.0",
    "@angular/router": "~6.1.0",
    "nativescript-angular": "~6.1.0",
    "nativescript-camera": "4.0.2",
    "nativescript-plugin-firebase": "^6.4.1",
    "nativescript-theme-core": "~1.0.4",
    "reflect-metadata": "~0.1.10",
    "rxjs": "~6.2.0",
    "tns-core-modules": "~4.2.0",
    "zone.js": "~0.8.18"
  },
  "devDependencies": {
    "nativescript-dev-typescript": "~0.7.0",
    "nativescript-dev-webpack": "~0.15.0",
    "typescript": "~2.7.2",
    "@angular/compiler-cli": "~6.1.0",
    "@ngtools/webpack": "~6.1.0"
  },
  "readme": "NativeScript Application"
}
```

**Comment by EddyVerbruggen** [comment]
Share the entire repo if you need help.

**Comment by janossuta** [comment]
this is the repo:
`https://github.com/janossuta/demoNativeScript`

**Comment by EddyVerbruggen** [comment]
Your app works perfectly fine for me. Init runs according to the log, and when running "getdata" on the About page a bunch of data is dumped to the console (`JS: {"type":"ValueChanged","key":"borders","value":{"b_184":{"load":0,"stop":24,"name":"Mokranje - Bregovo (0-24)","start":0,"pair":"b_189"},"b_185":{"load":0,"stop":24,"name":"Oltomantsi - Ribarci (0-24)", ...`

#### My steps:

```bash
git clone https://github.com/janossuta/demoNativeScript
cd demoNativeScript
npm i
tns run android [--bundle]
```

**Comment by janossuta** [comment]
still not working here
I can only run with 
`tns run android` 

it doesn't recognize this command: `tns run android [--bundle]`

**Comment by EddyVerbruggen** [comment]
With `tns run android [--bundle]` I meant either `tns run android` or `tns run android --bundle`. That's a common syntax for describing a param is optional.

I don't know what to do for you anymore. With your repo and those steps it works for me as demonstrated.

**Comment by janossuta** [comment]
Have you tried on a phone or emulator?

**Comment by janossuta** [comment]
I tried on an S7, running Andorid 8.

I'm going to try on an other phone, maybe that is the problem.

Thank you for your help!

**Comment by janossuta** [comment]
The problem is with my developer environment, I set up a new environment on another machine and it working like charm. 

I don't know what is the problem with my current environment but at this point I don't really care.

Thanks everything!

**Comment by jofftiquez** [comment]
In my case, this is happening whenever I close the app and re-open it again.

**Comment by ceht** [comment]
Facing the same problem I  fixed it by deleting platform, then I ran the firebase command config again, I deleted the node modules, run npm install and finally I installed platform again, after that the plugin worked fine.
