### ISSUE TITLE
[Android] Flashlight doesn't work with Barcode scanner

### ISSUE THREAD

**Issue by paweldziura** [EddyVerbruggen/nativescript-plugin-firebase#852]
Unable to to open flashlight from android top menu when Barcode scanner is open.
When opening flashlight programmatically f.e. with flashlight plugin, the barcode scanner stops scanning (the camera view is frozen).

On Android 6+ I used your fork - https://github.com/EddyVerbruggen/nativescript-flashlight.git
Works fine on iOS.

**Comment by EddyVerbruggen** [comment]
I've just added this feature. You can now set a `useTorch` property on the UI element and bind that to a component property that you can toggle with fi. an on-screen `Switch` or `Button`. See the [demo-ng app](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/b92431e6daf51c503dde98bf095a5b7d8936ab7e/demo-ng/app/tabs/mlkit/barcodescanning/barcodescanning.component.html#L12) for an example.
