### ISSUE TITLE
Using a Dynamic value for a document / collection makes the application crash

### ISSUE THREAD

**Issue by GindoraMichael** [EddyVerbruggen/nativescript-plugin-firebase#854]
First of all, thank you for this plugin!

I'm trying to access a dynamic doc. but It crashed when -> without any errors..

`const helloRef: firestore.DocumentReference = firebaseWebApi.firestore().collection("users").doc(userID).collection("availability").doc("hello");`

OR

`const helloRef: firestore.DocumentReference = firestore.collection("users").doc(userID).collection("availability").doc("hello");`

Any clues, anyone?

**Comment by EddyVerbruggen** [comment]
Hi,

That looks like what I have in the demo-ng folder. Can you compare it? Perhaps your firrestore import is different?

**Comment by EddyVerbruggen** [comment]
Oh, and can you tell me what the crash actually is and on which platform(s)?

**Comment by GindoraMichael** [comment]
I’m using the same imports. 
When the function is being called (on iOS) the UINavigationBarItem gets stuck in the pressed state and after about 30 sec the app just crashes. Can’t seem to find any errors

**Comment by EddyVerbruggen** [comment]
I’d be happy to try and replicate. Can you share a repo or a screenshot of the relevant Firestore DB structure in the console?

**Comment by GindoraMichael** [comment]
The structure is very simple:
Root:
```
Users
-->UserID (Dynamic value)
---->UserData
----->Availability (not there yet) (should become a subcollection) 
------->(new doc with some data)
```

That's all that is currently in the DB.

the `userID` is retrieved from the `getCurrentUser()` function:
```
            var userID = "";
            firebase.getCurrentUser()
            .then(user => userID = user.uid)
            .catch(error => console.log("Trouble in paradise: " + error));
```

I've tried the following `imports`:

```
const firebaseC = require("nativescript-plugin-firebase");
import { firestore } from "nativescript-plugin-firebase";
import firebase = require("nativescript-plugin-firebase");
import firebaseWebApi = require("nativescript-plugin-firebase/app");
```


Hope this helps recreate it..? If you need more info, don't hesitate to ask :D


<br><br>

Met vriendelijke groet, Kind regards,

Michael

Send from my iPhone

**Comment by GindoraMichael** [comment]
Any luck replicating it?

**Comment by EddyVerbruggen** [comment]
This is not on top of my priority-pile yet.

**Comment by EddyVerbruggen** [comment]
I can't reproduce it so please take a look at what I've done. This is my DB structure:

<img width="803" alt="screenshot 2018-08-23 at 10 56 53" src="https://user-images.githubusercontent.com/1426370/44515614-474f1a00-a6c3-11e8-95f5-6a37afdbbd11.png">

And I've just pushed this code sample to demo-ng which should be similar to what you have:

https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/9d7377c8a2c87304c6151145575baf74f0c7f43f/demo-ng/app/tabs/firestore/firestore.component.ts#L29-L47

The console output is as expected:

```bash
CONSOLE LOG file:///app/tns_modules/@angular/core/bundles/core.umd.js:3882:43: {
"foo": "bar"
}
```

Can you take a look and see what's different with your implementation?

**Comment by GindoraMichael** [comment]
Thank your sir, 

I do know why but I got it working by storing the user id in the application settings..
