### ISSUE TITLE
iOS: TypeError: null is not an object (evaluating 'snapshot.documentID')

### ISSUE THREAD

**Issue by jnorkus** [EddyVerbruggen/nativescript-plugin-firebase#855]
After logging out iOS app crashes with the error in title. Seems related to the issue where it is not possible to unsubscribe properly.

**Comment by EddyVerbruggen** [comment]
I've added a guard to the only place that error could originate from. Thanks for reporting it!

**Comment by jnorkus** [comment]
I had basically done the same thing in the PR that references this issue. But I guess you can close it now also.

**Comment by EddyVerbruggen** [comment]
I feel bad for not seeing it. Sorry man!
