### ISSUE TITLE
Unable to build the project in android

### ISSUE THREAD

**Issue by BlackCurtains** [EddyVerbruggen/nativescript-plugin-firebase#86]
```
FAILURE: Build failed with an exception.  * Where: Build file 'C:\Users\User\Desktop\MyApp\ap-app-fb\platforms\android\build.gradle' line: 699  * What went wrong: A problem occurred evaluating root project 'wpapp'. 
> Failed to apply plugin [id 'com.google.gms.google-services']    
> For input string: "+"  * Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.  BUILD FAILED  Total time: 20.566 secs Command C:\Users\User\Desktop\MyApp\ap-app-fb\platforms\android\gradlew.bat failed with exit code 1
'FAILURE:' is not recognized as an internal or external command,
operable program or batch file.
```

- I have google-services.json in "platforms\android\  " path.
-  I have installed latest "Google Play Service", "Google Repository" &  "Android Support Repository" in Android SDK.
- I have tried using : 
```
     compile 'com.google.android.gms:play-services:9.0.0'
```
and 

```
     compile 'com.google.android.gms:play-services:9.2.0'
```

then, I get issues like:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processF0F1F2F3F4F5F6F7DebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 9.2.0.
```

**Comment by EddyVerbruggen** [comment]
Are you including any other plugins requiring google play services perhaps?

**Comment by BlackCurtains** [comment]
ya, it was nativescript-google-maps-sdk.
But, I also need this plugin to show maps in my app. 
Isn't there any way to solve this problem and use both plugin withour error?

**Comment by EddyVerbruggen** [comment]
What I'm reading all over the interwebs is that one should (unfortunately) avoid using `+` in the `compile .. play-services` command.

Armed with that bit of information I just verified this works with both plugins installed:

#### First remove/add the platform folder:
- tns platform remove android
- tns platform add android
- Re-add the google-services.json and alter the build.gradle script (see this plugin's readme)

#### Alter the Maps plugin to include the [same version](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/platforms/android/include.gradle#L23) as the Firebase plugin:
- Open node_modules/nativescript-google-maps-sdk/platforms/android/
- Replace that `+` by `9.2.0`

That should build nicely. If so I will alter the readme and refer to this issue.

**Comment by ParVisual** [comment]
Hi, I have the same issue. 
I tried to solve it replacing inside **node_modules/nativescript-google-maps-sdk/platforms/android/include.gradle**

```
dependencies {
	def googlePlayServicesVersion = project.hasProperty('googlePlayServicesVersion') ? project.googlePlayServicesVersion : '11.2.+'
	compile "com.google.android.gms:play-services-maps:$googlePlayServicesVersion"
}
```
and in the file **app/App_Resources/Android/app.gradle** :
```
  defaultConfig {  
    generatedDensities = []
    applicationId = "ar.com.myapp.fullapp"  
  }  
  aaptOptions {  
    additionalParameters "--no-version-vectors"  
  }  

  project.ext {
    googlePlayServicesVersion = "11.2.+"
  
}} 
```
When I execute "tns run android" works fine, but when I try "tns build android" the error still, and the build is not possible.

Some idea about it?
Thanks.

**Comment by burkard** [comment]
For me, what solved the problem was to comment the last line on Firebase's include.gradle (full path is:

**Comment by burkard** [comment]
What solved for me was look which version the nativescript-plugin-firebase and set the same for the file app/App_Resources/Android/app.gradle 
1) [Click here](https://github.com/EddyVerbruggen/nativescript-plugin-firebase#google-play-services-version) and then follow the "this version" link; there you'll see something like this: 
      `def firebaseVersion = "11.4.2"`
 2)Now, open app/App_Resources/Android/app.gradle and put this inside defaultConfig:
       `project.ext {
		googlePlayServicesVersion = "11.4.2"
	}`

Hope that helps!

**Comment by smd-codeslayers** [comment]
@burkard This solves the build error. But it crashes when running google place picker in my app.
