### ISSUE TITLE
IOS - notification permission asked immediately on firebase init

### ISSUE THREAD

**Issue by anuragd7** [EddyVerbruggen/nativescript-plugin-firebase#860]
Hi
In my nativescript angular app I find that the notification permission is asked for immediately on firebase init in IOS. (not so in android). 
This even though i am not setting up the notification handlers  at the time I am initialising firebase. 

Please use [this repository](https://github.com/anuragd7/notifications) to see this issue with the `nativescript-plugin-firebase version 6.5.0`

**Comment by anuragd7** [comment]
Would be great if someone could take a look at [the repo](https://github.com/anuragd7/notifications) and tell me if I need to do something differently. Thanks

**Comment by EddyVerbruggen** [comment]
With plugin version 7.0 this was fixed.
