### ISSUE TITLE
Access AdvertisingIdClient.info

### ISSUE THREAD

**Issue by LSmint** [EddyVerbruggen/nativescript-plugin-firebase#861]
Can this plugin access to get advertising tracking ID (IDFA and GAID)?

**Comment by EddyVerbruggen** [comment]
Not that I know, can you share the native SDK docs that would enable it?

**Comment by LSmint** [comment]
i studied on few link but cant figure out how to call it in NS, you can refer to this:

Android 
https://developers.google.com/android/reference/com/google/android/gms/ads/identifier/AdvertisingIdClient

IOS
https://developer.apple.com/documentation/adsupport/asidentifiermanager

**Comment by LSmint** [comment]
found way to include, close this case

**Comment by EddyVerbruggen** [comment]
Can you perhaps share it with us?

**Comment by LSmint** [comment]
I hope this help
For iOS, get the advertising identifier using the advertisingIdentifier property:
```
declare class ASIdentifierManager extends Object {
  static alloc(): ASIdentifierManager;
  static new(): ASIdentifierManager;
  static sharedManager(): ASIdentifierManager;
  readonly advertisingIdentifier: string;
  readonly advertisingTrackingEnabled: boolean;
}
```

For android, call the method getAdvertisingIdInfo(), which returns the user's current Advertising ID and tracking preference. The getAdvertisingIdInfo() method is a blocking call, thus i refer to nativescript-worker-loader and run it on background thread:

```
declare const com: any;
const ctx = utils.ad.getApplicationContext();
let adsInfo = com.google.android.gms.ads.identifier.AdvertisingIdClient.getAdvertisingIdInfo(ctx)
let tracking = adsInfo.isLimitAdTrackingEnabled();
let GAID = adsInfo.getId();
```

**Comment by mrzanirato** [comment]
@LSmint can you provide a more detail example.
I receive this error:
JS: ERROR TypeError: Cannot read property 'google' of undefined
