### ISSUE TITLE
Unable to Download Files (Images from Firebase to Real ios Device)

### ISSUE THREAD

**Issue by BMwanza** [EddyVerbruggen/nativescript-plugin-firebase#863]
Hi,

I have this functionality in my {N} app where I need to download images from my Firebase Storage and load them into the UI of the app.

I am simply calling the download function provided with this plug in, and saving the downloaded file to a local path using the File System module. This operation works perfectly fine on the iOS simulator, as well as on real Android devices I have tested on, however when Downloading the files and trying to save locally on a real ios Device I get this error: 
CONSOLE LOG file:///app/tns_modules/nativescript-plugin-firebase/storage/storage.js:78:28: >>> download complete, error: Error Domain=FIRStorageErrorDomain Code=-13000 "An unknown error occurred, please check the server response." UserInfo={NSUnderlyingError=0x10e73db20 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}, bucket=myapp-firebasebucket.appspot.com, object=JobRequests/jobID-0d37cf99-71d8-9222-7236-b9b5fa514c94/SnowAngelPictures/gtKMOcR450SqZV5wfHkgnjRancZ2-image-7-20-2018-SAImage1.jpg, NSDestinationFilePath=/var/mobile/Containers/Data/Application/33EC71C5-0341-4B4A-BAAE-E38CA067A5D7/DocumentsSAImage1.jpg, NSLocalizedDescription=An unknown error occurred, please check the server response., NSUserStringVariant=(
Move
), NSSourceFilePathErrorKey=/private/var/mobile/Containers/Data/Application/33EC71C5-0341-4B4A-BAAE-E38CA067A5D7/tmp/CFNetworkDownload_VnmuDK.tmp, NSFilePath=/private/var/mobile/Containers/Data/Application/33EC71C5-0341-4B4A-BAAE-E38CA067A5D7/tmp/CFNetworkDownload_VnmuDK.tm
CONSOLE LOG file:///app/DatabaseRoutes/JobRequestRoute.js:106:28: An unknown error occurred, please check the server response.

I noticed that within the error it says "operation not permitted" so I don't know if I missed a step to allow files to be downloaded to the iOS device but I've been trying to solve this all day. 

Thanks in advance

**Comment by EddyVerbruggen** [comment]
An iOS device is more restrictive to where you can save files. 

You didn’t provide the actual code, but I’m assuming you’re saving it to the app bundle - which is not allowed. 

Try:

const documents = fs.knownFolders.documents();
    const logoPath = documents.path + "/telerik-logo-downloaded.png";

**Comment by BMwanza** [comment]
![image](https://user-images.githubusercontent.com/26012815/44401808-76278d80-a515-11e8-9a50-5de5cd04a3c1.png)
Sorry I didn't provide the code ahead of time, I feel like I am doing what you said above. I'm using the code that was provided the in README guide. The only thing I feel like I am doing differently is saving the images as .jpeg file and not a .png

I'll explain my code a bit further though
All I am doing is downloading multiple files each from a different remote path from my Firebase Storage Bucket, and saving them to a path using the  File System module, just using the index of the array of images to differ each local path

**Comment by BMwanza** [comment]
Oh caught my mistake! I forgot to include a "/" in the local path of where I'm saving it! Didn't realize it at the time! Thanks so much, also I'm not an expert on this but is it better storage wise to save pictures a png instead of jpg?

**Comment by EddyVerbruggen** [comment]
Depends on what the picture is. For photo’s (from a camera) use jpg, otherwise png.
