### ISSUE TITLE
Push Notification Question

### ISSUE THREAD

**Issue by BMwanza** [EddyVerbruggen/nativescript-plugin-firebase#865]
Hi,

So I have just completed the Cloud Messaging Guide and enabled push Notifications in my app. I am able to receive the messages in the foreground and background. (I have tested it with the CURL commands). 

However, when a message is sent and recieved on an ios Device both simulator and real device the Notification does not pop up on the top status bar, nor does a badge appear on my app.
I believe I followed the guide to the letter, and didn't miss a step, but I'm not too sure where to start off to go about trying to fix this problem

**Comment by abhayastudios** [comment]
What does your message object look like? If you are sending only data then the app will receive it but not show a notification. If it contains an alert/notification property then it will show a notification (and if you want a badge on iOS you will need to provide a number). Have a look at the [Firebase docs](https://firebase.google.com/docs/cloud-messaging/admin/send-messages) for more info on what the object should look like.

This is the object that I am sending which works quite good for my purposes using the `send()` method.

```
const message = {
    token: addresseePushToken,
    /*
       Apple Push Notification Service
       https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns
    */
    apns: {
      headers: {
        'apns-priority': 10,                // defaults to 10 (send immediately), can be set to 5 (consider device power)
        'apns-collapse-id': dataObj.chatId  // group multiple notifications into a single notification (must not exceed 64 bytes)
      },
      payload: {
        aps: {
          alert: {
            title: title,
            body: dataObj.doc.message,
          },
          badge: unseenCount+1,
        }
      }
    },
    /*
       Android specifics
       https://firebase.google.com/docs/cloud-messaging/admin/send-messages#android_specific_fields
    */
    android: {
      priority: 'high',               // either 'normal' or 'high' - high send immediately & waking sleeping device
      notification: {                 // notification object creates status bar notification if app in background
        tag: dataObj.chatId,          // key for grouping notifications (Android only)
        title: title,
        body: dataObj.doc.message,
        color: '#ffffff',             // notification's icon color
        icon: thumbUrl,               // if not specified FCM displays the launcher icon as defined in app manifest
      }
    },
    // data object is available to the app both when received in foreground and background
    data: {
      type: 'chat',
      senderId: dataObj.senderId,
      title: title,
      body: dataObj.doc.message,
    },
  }
```

**Comment by BMwanza** [comment]
Hmmm, I was just testing it on the FCM console, I haven't implemented any firebase cloud functions as of yet, but I've tried sending a message using these settings in the FCM console, and it results to nothing being shown 
![image](https://user-images.githubusercontent.com/26012815/44420374-53ac6900-a543-11e8-8963-e5388250cb9f.png)

**Comment by BMwanza** [comment]
I noticed that using the CURL commands does actually Trigger my onMessageReceivedCallback Function I think that is the problem

**Comment by EddyVerbruggen** [comment]
Dunno of it helps, but this postman payload also works pretty well (it's much like the curl command in the docs):

<img width="485" alt="screenshot 2018-08-31 at 13 12 50" src="https://user-images.githubusercontent.com/1426370/44909432-9fb79480-ad1f-11e8-9774-c05127d4f479.png">

Note that the iOS simulator can't receive push notifications.

**Comment by tebieto** [comment]
Explanations are actually not clear for newbies to understand, If I know how to make things work, I would make everything clear for newbies. I am building for android, I receive the notifications, but I can only console.log them or alert them, teach us how  to make the  notification appear in notification appear in android notification bar even when app is closed
