### ISSUE TITLE
Google Play services is required for this feature, but not available on this device

### ISSUE THREAD

**Issue by Enlitened** [EddyVerbruggen/nativescript-plugin-firebase#88]
I am trying to auth but this is the error returned by the login function. I am using Intel Atom (x86) as the CPU for the emulator, if I try any of the Google ones (i.e. Google APIs Intel Atom x86) it gives the 'FirebaseApp with name [DEFAULT] doesn't exist' error. I have installed Google Play Services and Google repository through Android SDK Manager (and added the relevant items in app.gradle and build.gradle). I read that I need to add something like this to the build.gradle to get the Google Play services functioning: compile 'com.google.android.gms:play-services:9.2.1'

**Comment by EddyVerbruggen** [comment]
Google play services is not installed by default on most emulators. You can Google a bit on how to install it for Genymotion if you want..

Regarding the other error.. did you [do this](https://github.com/EddyVerbruggen/nativescript-plugin-firebase#firebaseapp-with-name-default-doesnt-exist)?

**Comment by EddyVerbruggen** [comment]
Please also see if 3.5.0 fixes the issue for you, especially in case you called `init` before the app starts.
