### ISSUE TITLE
googlePlayServicesVersion problem [with temporary solution, should i do PR?]

### ISSUE THREAD

**Issue by indradha** [EddyVerbruggen/nativescript-plugin-firebase#882]
Found this bug, maybe just me or some other with the googlePlayServicesVersion problem, so am sharing my solution/fix here that takes me hours to solve:

As stated on the documentation, we have to set googlePlayServicesVersion to 15.0.0, but somehow I got this error

```
Failed to capture snapshot of input files for task ':app:preDebugBuild' property 'compileManifests' during up-to-date check.
The library com.google.android.gms:play-services-auth-base is being requested by various other libraries at [[15.0.0,15.0.0]], but resolves to 15.1.0. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.

```

without setting the googlePlayServicesVersion, my error will fall on 15.0.1:

`The library com.google.android.gms:play-services-auth-base is being requested by various other libraries at [[15.0.1,15.0.1]], but resolves to 15.1.0. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.`

The temporary fix/solution in my code will be updating include.gradle (is it set by scripts/installer.js?) on these lines below 

```
compile "com.google.android.gms:play-services-base:$googlePlayServicesVersion" -> compile "com.google.android.gms:play-services-base:15.0.1"

compile "com.google.android.gms:play-services-auth:$googlePlayServicesVersion" -> compile "com.google.android.gms:play-services-auth:16.0.0"

``` 

(I got the latest version from here: https://developers.google.com/android/guides/setup)

**Comment by sebastiandg7** [comment]
Same happening here

**Comment by andermev** [comment]
The same for me, I looked up this issue in several pages, until finally I achieved resolve it.

I am going to share you my **app.gradle**

```
dependencies {
  compile "com.google.android.gms:play-services-auth:16.0.0"
  compile fileTree(dir: 'libs', include: ['*.jar'])
}

android {  
  defaultConfig {  
    generatedDensities = []
    multiDexEnabled true
    applicationId = "org.nativescript.appmigotabsapp"
  }  
  aaptOptions {  
    additionalParameters "--no-version-vectors"  
  }

  project.ext {
    googlePlayServicesVersion = "15.0.0"
  }

  buildTypes {
      release {
          minifyEnabled false
          proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
      }
  } 

  dexOptions {
    jumboMode true
    javaMaxHeapSize "4g"
  }
} 

def settingsGradlePath

if(project.hasProperty("appResourcesPath")){
    settingsGradlePath = "$project.appResourcesPath/Android/settings.gradle";
} else {
    settingsGradlePath = "$rootDir/../../app/App_Resources/Android/settings.gradle";
}

def settingsGradleFile = new File(settingsGradlePath);

if(settingsGradleFile.exists())
{
    apply from: settingsGradleFile;
}

apply plugin: 'com.google.gms.google-services'
```

Perhaps, there is something to fix in my file but it's working.

I hope that it can be helped for you.

**Comment by andermev** [comment]
Awesome, I am glad for you :) 👍

**Comment by DickSmith** [comment]
https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/src/scripts/postinstall.js
That is the file that generates these, I believe.

However, to get around it for now you can also do this in your app.gradle:

dependencies {
    configurations.all {
        exclude group: 'commons-logging', module: 'commons-logging'
        resolutionStrategy.eachDependency { DependencyResolveDetails details ->
            def requested = details.requested
            if (requested.group == 'com.google.android.gms' || requested.group == 'com.google.firebase') {
                details.useVersion '+'
            } else if (requested.group == 'com.android.support' && requested.name != 'multidex') {
                // com.android.support major version should match buildToolsVersion
                details.useVersion '27.+'
            }
        }
    }
    implementation "com.google.android.gms:play-services-tagmanager:15.0.0"
}

project.ext {
  // TODO PR this so that '15.+' can be used
    googlePlayServicesVersion = "15.0.0"
    supportVersion = "27.+"
}
As you can see there, I've also been meaning to PR this, but it needs to be able to handle the + in any of the 3 positions, as well.

But that snippet above will override all gms/firebase stuff to latest (+) as unfortunately there isn't really unified version for those right now and they're sort of all over the place.

In general the best way to override version conflicts in Gradle, as I also use it to force the android.support versions.

**Comment by EddyVerbruggen** [comment]
Hi, ran into this issue today while preparing 6.8.1. I changed `scripts/installer.js` to roughly what @indradha posted and that solved it for me. Going to include it in the release, but I'd be happy to merge a better fix (if one exists) in a future release.
