### ISSUE TITLE
[Messaging] Format '/topics/all' is deprecated

### ISSUE THREAD

**Issue by davorpeic** [EddyVerbruggen/nativescript-plugin-firebase#883]
We got deprecated message when subscribing to topic in latest version
```
5.5.0 - [Firebase/Messaging][I-FCM002024] Format '/topics/all' is deprecated. Only 'all' should be used in subscribeToTopic
```

**Comment by EddyVerbruggen** [comment]
Thanks for reporting that! I'll take a look.

**Comment by EddyVerbruggen** [comment]
Done. Also, with 6.7.0 subscribe/unsubscribe no longer immediately resolve the promise, but rather resolve when/if the native SDK completes its actions, or reject in case of trouble. That was not possible in the past.
