### ISSUE TITLE
How to get live camera feed with nativescript-vue?

### ISSUE THREAD

**Issue by shilik** [EddyVerbruggen/nativescript-plugin-firebase#887]
I have worked the all day trying to figure out the above question but in vain.
error message likes 'ML Kit error: TypeError: Cannot read property \'android\' of undefined'
is what I got.

I know the critical part is get the " imageSource" well set.

	firebase.mlkit.textrecognition
		.recognizeTextOnDevice({
		   image: imageSource //get stuck here!!
		})

Here is what I have 
 <MLKitTextRecognition ref="mlk" class="my-class" width="260" height="340" processEveryNthFrame="5" :torchOn="torchOn" horizontalAlignment="center" @scanResult="onTextRecognitionResult">
</MLKitTextRecognition>

Is there anyone know what needs to be added to the code in order to get the live camera feed?

**Comment by EddyVerbruggen** [comment]
Share a repo and steps to reproduce and I may take a look.

**Comment by shilik** [comment]
Here are the codes:

<template>
  <Page class="page">
    <ActionBar class="action-bar" title="Home" />

    <StackLayout>
      <Button class="btn btn-primary" @tap="fromCameraroll">Camera</Button>
      <Label :text="result_text" />
      <MLKitTextRecognition ref="mlk" class="my-class" width="260" height="340" processEveryNthFrame="5" :torchOn="torchOn" horizontalAlignment="center" @scanResult="onTextRecognitionResult">
      </MLKitTextRecognition>
    </StackLayout>

  </Page>
</template>

<script>
const firebase = require("nativescript-plugin-firebase");
//import * as Camera from "nativescript-camera";
import {
	fromFile,
	ImageSource,
	fromAsset
} from "tns-core-modules/image-source";
import { isIOS } from "tns-core-modules/ui/page/page";
import { ImagePicker } from "nativescript-imagepicker";
export default {
	data() {
		return {
			surprise: false,
			torchOn: true,
			pickedImage: null,
			result_text: ""
		};
	},
	created() {},
	mounted() {
		firebase
			.init({
				//persist: false
			})
			.then(
				instance => {
					console.log("firebase.init done!");
				},
				error => {
					console.log("firebase.init error " + error);
				}
			);
	},
	methods: {
		onCameraOpen() {
			/*	if (!isIOS) {
				Camera.requestPermissions();
				Camera.takePicture({
					width: 260,
					height: 380,
					keepAspectRatio: true,
					saveToGallery: true,
					cameraFacing: "rear"
				}).then(imageAsset => {
					new ImageSource().fromAsset(imageAsset).then(imageSource => {
						// give the user some time to to see the picture
						setTimeout(() => this.onTextRecognitionResult(imageSource), 3000);
					});
				});
			}*/
		},
		fromCameraroll() {
			var imagepicker = require("nativescript-imagepicker");
			var context = imagepicker.create({ mode: "single" }); // use "multiple" for multiple selection
			context
				.authorize()
				.then(() => context.present())
				.then(selection => {
					if (selection.length == 0) return;

					const selected = selection[0];
					selected.options.height = 800;
					selected.options.width = 800;
					selected.options.keepAspectRatio = true;
					selected.getImageAsync((image, error) => {
						if (error) {
							console.log(`Error getting image source from picker: ${error}`);
							return;
						}
						if (!image) {
							alert({
								title: "Invalid image",
								message: `Perhaps this is an image from cloud storage?`,
								okButtonText: "Hmm.."
							});
							return;
						}
						const imageSource = new ImageSource();
						imageSource.setNativeSource(image);

						setTimeout(() => {
							this.onTextRecognitionResult(imageSource);
						}, 500);
					});
				});
		},
		onTextRecognitionResult(imageSource) {
			firebase.mlkit.textrecognition
				.recognizeTextOnDevice({
					image: imageSource //get stuck here!!??
				})
				.then(result => {
					setTimeout(() => {
						console.log(result.text ? result.text : "");
					}, 4000);
					this.result_text = result.text;
					console.log(
						"recognizeTextOnDevice result: " + JSON.stringify(result)
					);
					alert({
						title: `Result`,
						message: result.text ? result.text : "",
						okButtonText: "OK"
					});
				})
				.catch(errorMessage => {
					console.log("ML Kit error: " + errorMessage);
				});
		}
	}
};
</script>

**Comment by EddyVerbruggen** [comment]
Share a repo an steps to reproduce please.

**Comment by shilik** [comment]
Sorry, here is the repo.
https://github.com/shilik/ns-firebase

**Comment by shilik** [comment]
npm run watch:android

**Comment by shilik** [comment]
Instead of live camera feed, I used still image from camera to sort out the source of error of  android of undefined. The part of camera took the picture as expected, and produced an image likes "android.graphics.Bitmap@a8a855c", while used it as a parameter for onTextRecognitionResult(), no errors and no results are found in terminal.
 the repo.
https://github.com/shilik/ns-firebase

steps to reproduce results:
npm install
npm run watch:android

**Comment by ctacosta** [comment]
I can confirm I am having the exact same issue.

I found I was able to get the processed text using MLKitTextRecognition custom element in live view via the scanResult event

then accessed the  processed text using the passed in event object 

eventObject.value.text;

using the recognizeTextOnDevice function seems to give that android error.

**Comment by EddyVerbruggen** [comment]
I just update the doc and demo-vue app to show how to embed ML Kit on Android. Hope that helps.

**Comment by shilik** [comment]
Thank you Eddy, you save my day.
