### ISSUE TITLE
firestore.where does not work correctly with document references

### ISSUE THREAD

**Issue by cainjonm** [EddyVerbruggen/nativescript-plugin-firebase#888]
Hi,

I'm trying to filter a collection of documents ("objects") to only include documents with a field referencing a particular document ("category"), but it appears the `.where` on a collection never matches anything if the thing being matched is a reference.

Repro: 
1. create the following firestore collections
`categories:`
```
{
    'YdmPTzSnsYt4ysWZUhBO': {
        'name': 'Foo'
    },
    'vcmuSulK0VWrpF4CqE3i': {
        'name': 'Bar'
    }
}
```
`objects`:
```
{
    '4352daeohtuon125125thaoeu': {
        'category': '/categories/YdmPTzSnsYt4ysWZUhBO', // a reference type in firestore
        name: 'meh'
    },
    '4352daeohtuon125125thaoeu': {
        'category': '/categories/vcmuSulK0VWrpF4CqE3i', // a reference type in firestore
        name: 'argh'
    },
}
```

then using this plugin:

```
let objectsCollection = firebase.firestore.collection('objects');
let categoriesCollection = firebase.firestore.collection('categories');
let categoryRef = categoriesCollection.doc('YdmPTzSnsYt4ysWZUhBO') // name: Foo

objectsCollection
.where('category', '==', categoryRef)
.get()
.then((snapshot) => {
     // expect length of 1, but get 0
    console.log(querySnapshot.docSnapshots.length);
});
```
This should output the object document with that category id, but instead it outputs no matches.

However, if i use the firestore-admin npm module, i correctly get the 'meh' document returned.

Am I doing anything obviously wrong? (sorry for the fake code, just attempting to simplify what it is in my actual project)

**Comment by EddyVerbruggen** [comment]
I can confirm this issue on both iOS and Android. Thanks for reporting it!

You also currently can't compare with a GeoPoint, but that's not as important as the reference you mentioned.

Will fix this and release 6.7.0 shortly after.
