### ISSUE TITLE
showWhenInForeground

### ISSUE THREAD

**Issue by BMwanza** [EddyVerbruggen/nativescript-plugin-firebase#889]
Hey there,
So to get the new showWhenInForeground feature to work, is this how the payload should look?
I tried getting the notification to show in the foreground on a real iPhone 6 device but didn't get it to show. I suspect that I am missing something?

![image](https://user-images.githubusercontent.com/26012815/45000997-ef4fc780-af8e-11e8-9df0-a32153539f95.png)

Thanks in advance!

**Comment by EddyVerbruggen** [comment]
I don’t know how to do that with apns as I’m using fcm in the examples on this page: https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/MESSAGING.md

Go ahead and try one of those curl commands, or use postman to send your payload to firebase
