### ISSUE TITLE
Projects created at console.firebase.google.com must use the new Firebase Authentication SDKs available from firebase.google.com/docs/auth/

### ISSUE THREAD

**Issue by esakal** [EddyVerbruggen/nativescript-plugin-firebase#89]
Hello,
I will really appreciate your help since I'm struggling with this for several hours now.

When running the groceries sample after adding the plugin I manage to initialize the firebase but once trying to login I'm getting the following error : 
```
Projects created at console.firebase.google.com must use the new Firebase Authentication SDKs available from firebase.google.com/docs/auth/
```

I followed the [plugin NativeScript Firebase plugin instructions](https://github.com/EddyVerbruggen/nativescript-plugin-firebase#android):
- copied ```google-services.json```
- update applicationId in ```app.gradle```
- updated depedency and applied plugin in ```build.gradle```

And I'm still getting the same error in the console.

I thought maybe trying [nativescript-plugin-firebase-demo](https://github.com/EddyVerbruggen/nativescript-plugin-firebase-demo) but I reviewed its' content and it has many elements that doesn't resemble the sample-groceries (with the addition of the firebase).

Help help please :)
Eran.

**Comment by EddyVerbruggen** [comment]
Looks like you're using [an older SDK](http://stackoverflow.com/questions/38010536/how-to-solve-the-error-projects-created-at-console-firebase-google-com-must-use). Can you try removing and readding the Android platform folder in case you previously used an older Firebase version..
