### ISSUE TITLE
Crash after Splashscreen iOS

### ISSUE THREAD

**Issue by pboulch** [EddyVerbruggen/nativescript-plugin-firebase#891]
Hi, 
I try to use this plugin. With Android, no problem. But with iOS, the app crash after splashscreen. I tried to create a new nativescript project, and just add this plugin. With the line `var firebase = require("nativescript-plugin-firebase");` , the app crashing just after splashscreen without any message. 

Any ideas ? 

Thanks

**Comment by EddyVerbruggen** [comment]
Not without a repo to look at.

**Comment by pboulch** [comment]
[https://github.com/pboulch/test-tns-firebase](https://github.com/pboulch/test-tns-firebase)

**Comment by EddyVerbruggen** [comment]
Thanks. There's a configuration error. I got this when trying to run the app on iOS from Xcode:

**Error: URL scheme needed for Google Sign-In not included in your app's Info.plist. Please refer to the Google Sign-In SDK documentation for more information.'**

I assume that's clear enough. If not, check [the Info.plist of the demo](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/demo/app_resources/iOS/Info.plist), and/or [RTFM](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/bcf645a695364b80ddea45b0d54854a94284fa14/docs/AUTHENTICATION.md#ios-1).
