### ISSUE TITLE
JS: ERROR Error: Uncaught (in promise): Run init() first! 

### ISSUE THREAD

**Issue by job111** [EddyVerbruggen/nativescript-plugin-firebase#892]
been facing this error for couple days i tried everything but nothing seems to be working.
here is a sample project

[myapp.zip](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/files/2349983/myapp.zip)

**Comment by job111** [comment]
anything new about this topic?

**Comment by jenyaivanova521** [comment]
same issue for me

**Comment by jenyaivanova521** [comment]
I found the issue
on firebase.nativescript.json file, set "realtimedb": true,

    {
        ...
        "realtimedb": true,
        ...
    }

**Comment by ibnYusrat** [comment]
> I found the issue
> on firebase.nativescript.json file, set "realtimedb": true,
> 
> ```
> {
>     ...
>     "realtimedb": true,
>     ...
> }
> ```

What if someone is not using realtime db?

**Comment by EddyVerbruggen** [comment]
@ibnYusrat Set it to `false`, and if that leads to an error then please share a repo with me so I can take a look.
