### ISSUE TITLE
user.additionalUserInfo are (almost) never returned as stated in the docs

### ISSUE THREAD

**Issue by vratojr** [EddyVerbruggen/nativescript-plugin-firebase#903]
Hello @EddyVerbruggen,
In the [docs](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/AUTHENTICATION.md#whats-returned-when-logged-in) there's written:

    All login functions below, as well as getCurrentUser return a 'User' object with these properties:

The fact is that it's not doing it :)
For example, I checked the code and I see that _getCurrentUser_ is calling _toLoginResult_ without the additional parameter required to fill the extra data.

This is also true for other situations (like for example when listening for state change). So it's suspect :)
Is there a problem (that I don't see) in always returning the additional info (and maybe the docs are outdated and we should remove that statement) or simply we can modify the code to always return the additionaldata?

I cannot test it sorry as I still unable to build this plugin and testing it locally... :/

**Comment by EddyVerbruggen** [comment]
Do these instructions work for you? https://github.com/EddyVerbruggen/nativescript-plugin-firebase#demo-app

**Comment by vratojr** [comment]
Hello Eddy!
You mean running the demo and testing the behaviour of getCurrentUser?
I confirm that for the native api (sorry I should have mentioned it before)
getCurrentUser doesn't return the additionalUserInfo.

**Comment by vratojr** [comment]
Hello Eddy!
You mean running the demo and testing the behaviour of getCurrentUser?
I confirm that, for the **native api** (sorry I should have mentioned it before), getCurrentUser doesn't return the additionalUserInfo.
