### ISSUE TITLE
Separation of Environments

### ISSUE THREAD

**Issue by rgomezu** [EddyVerbruggen/nativescript-plugin-firebase#905]
Greetings,

Recently I saw a new section named "Separation of Environments" on the main plugin documentation, I tried adding it to my project but wasn't able to make it work.

Reviewing the plugin's history this functionality was removed from the code.

Is there another way to have separate environments on my project?

Thanks in advance.

**Comment by abhayastudios** [comment]
Yeah as I wrote in #895 [this commit](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/commit/4e1c502b7e8963691beb2f099688823507780181#diff-dc840b87fef4416b36741b07a01fdea3) undid my changes (probably by mistake). I will submit a new PR to redo them.

**Comment by EddyVerbruggen** [comment]
I apologize if this got somehow removed. That was indeed not the intention.

**Comment by BMwanza** [comment]
Not sure if I'm going about this the wrong way but I am having trouble setting this up.

I created a new Firebase Project and configured it on the Firebase Console to use my apps bundle ID. Then saved the plist in the appropriate iOS folder but getting the following error:
Hey Everyone I’m having trouble seperating my Dev and Prod environments on with the firebase plug in
/Users/BMwanza/NativeScript Apps/noSnow/app/App_Resources/iOS/GoogleService-Info.plist does not exist. Please follow the installation instructions from the documentation
Unable to apply changes on device: 390519a03a0b5d0e35fe2266eb37db31160b4ddc. Error is: Failed to execute hook: /Users/BMwanza/NativeScript Apps/noSnow/hooks/after-prepare/firebase-copy-google-services.js..

**Comment by abhayastudios** [comment]
@BMwanza have a look at [this](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/968#issuecomment-432011225). Does this solve the issue?

**Comment by abhayastudios** [comment]
@BMwanza honestly, I haven't tried it with functions. However, if you use this plugin's [support](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/FUNCTIONS.md) for functions, I would expect it to use the correct ones depending on the google services config that is used in the build... but yeah you would need to deploy the functions to both the dev and prod project (which might be different versions). Let me know if you get it to work.
