### ISSUE TITLE
cannot initialize w NEW vue-cli-template iOS

### ISSUE THREAD

**Issue by spencercap** [EddyVerbruggen/nativescript-plugin-firebase#906]
hey eddy - this rad plugin works great on android but not ios unfortunately (with NEW vue-cli-template that is). the `next` branch of the  vue-cli-template was [recently merged](https://github.com/nativescript-vue/vue-cli-template/commit/ae4062224163aaf21152357e4fca1c460ee49ce1) with the master and it appears to structure things a little differently. i've tried a bunch of configurations regarding requiring the plugin before vue starts and initializing it afterwards as the readme indicates, but no luck... would a simple [example](https://github.com/EddyVerbruggen/ns-vue-firebase-test) as you did before w the old vue-cli be possible?

**Comment by spencercap** [comment]
to see the behavior or tinker around, you can [clone this repo](https://github.com/spencercap/ns-vue-cli-template-firebase), which is simply the new vue-cli-template after running `tns plugin add nativescript-plugin-firebase` and placing the .json and .plist files appropriately. 

running `tns debug android --bundle` shows `firebase.init done` in the console
but running `tns debug ios --bundle` does not show `firebase.init done` in the console

**Comment by EddyVerbruggen** [comment]
Thanks for the sample! I hope to find some time to play with it soon.

**Comment by Reached** [comment]
@spencercap I managed to get it running today using the new Vue template. So the difference from your linked repo is that I am running the `firebase.init()` inside of my `created()` method on the main Vue instance, also remember to `rm -rf` your platforms folder.

Hope it helps!

**Comment by EddyVerbruggen** [comment]
Thanks all!

I've also been tinkering with the 2.0 template this weekend and, MAN, it's so much easier to use with this plugin. It's as simple as the other frameworks now actually. [Here's the app](https://github.com/EddyVerbruggen/footplr) I'm building using Firestore, Cloud Functions, and the NativeScript-Vue 2.0 template.

**Comment by Reached** [comment]
I imagine that the new 2.0 template will make everything easier, also for awesome plugin developers as yourself @EddyVerbruggen - thanks for all your hard work and contributions to the community 🙏 !!

**Comment by spencercap** [comment]
agreed 🙏🏼thank you very very much for all the significant contributions @EddyVerbruggen 
i'll be tinkering with this very soon.
