### ISSUE TITLE
Is Google login supported

### ISSUE THREAD

**Issue by calebeaires** [EddyVerbruggen/nativescript-plugin-firebase#92]
There is an Google Login on your demo app, but it is not working. 

Enable Google auth in your firebase instance: **done**!
Code used:

```

    firebase.login({
        // note that you need to enable Google auth in your firebase instance
        type: firebase.LoginType.GOOGLE
    }).then(function (result) {
        dialogs.alert({
            title: "Login OK",
            message: JSON.stringify(result),
            okButtonText: "Nice!"
        });
    }, function (errorMessage) {
        dialogs.alert({
            title: "Login error",
            message: errorMessage,
            okButtonText: "OK, pity"
        });
    });

```

![screenshot_2016-07-31-11-41-47](https://cloud.githubusercontent.com/assets/794195/17277225/0240261c-5714-11e6-84de-d5568d06c5ab.png)

**Comment by jlooper** [comment]
Looks like Google login is not yet supported in the plugin https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/AUTHENTICATION.md

**Comment by calebeaires** [comment]
Yes, I thought it might be. Consider adding it as soon as possible. It is a very important plugin.

**Comment by EddyVerbruggen** [comment]
Look what I added to this plugin during my holiday :)

[Google Sign In with NativeScript + Firebase docs](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/doc
s/AUTHENTICATION.md#google-sign-in)

**Comment by jlooper** [comment]
Nice!!!

**Comment by ullalaaron** [comment]
Whoooow!! @EddyVerbruggen  you're amazing!!
