### ISSUE TITLE
Manipulating Array fields in Firestore documents via FieldValue 

### ISSUE THREAD

**Issue by spencercap** [EddyVerbruggen/nativescript-plugin-firebase#922]
hi! would it be possible to support `arrayUnion` and `arrayRemove` for arrays in a firebase firestore document? please see the [official docs for updating firestore documents](https://firebase.google.com/docs/firestore/manage-data/add-data) for reference.

this is similar to issue #805 regarding accessing serverTimeStamp via FieldValue with `firebase.firestore().FieldValue().serverTimestamp()` or `firestore.FieldValue.serverTimestamp()`. 

i suppose an implementation like `firebase.firestore().FieldValue().arrayUnion("array_item")` would be best. 

many thanks @EddyVerbruggen !

**Comment by EddyVerbruggen** [comment]
Done, [chcek the updated docs](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/a3a2cd06b28124f871c70cdec94704ce6ab70cc8/docs/FIRESTORE.md#adding-to-arrayunion-and-removing-from-arrayremove-arrays). Version 7.1.0 will be release later this week.

**Comment by spencercap** [comment]
awesome, will look out for it! 

thanks @EddyVerbruggen
