### ISSUE TITLE
[iOS] > Invalid 'podifle' file: syntax error, unexpected keyword_end, expecting end-of-input.

### ISSUE THREAD

**Issue by mpochron** [EddyVerbruggen/nativescript-plugin-firebase#925]
version 7.0.1

![image](https://user-images.githubusercontent.com/7736131/46075669-7dccf880-c18b-11e8-8494-0496216b7e5c.png)

![image](https://user-images.githubusercontent.com/7736131/46075704-91785f00-c18b-11e8-9db6-717af7de8a54.png)

**Comment by mpochron** [comment]
It's related to https://github.com/NativeScript/nativescript-cli/pull/3900

**Comment by EddyVerbruggen** [comment]
OK, see that PR for a workaround if you need it now, otherwise wait a day or 2 for a new CLI version to be pushed. Follow-up in that issue.
