### ISSUE TITLE
POD file not update after installing the plugin.

### ISSUE THREAD

**Issue by halaharr** [EddyVerbruggen/nativescript-plugin-firebase#937]
Hi,
    I am not sure why the pod file is not update after installing the plugin.
These are the 2 items in the pod file.
pod 'GoogleMaps'
pod 'GoogleMaps'

Please let me know if I amassing any steps.
(1) Installed "tns plugin add nativescript-plugin-firebase"
(2) Added GoogleService-Info.plist and google-services.json to the the project resources.
(3) ran pod repo update
(4) Copied entitlements file to the iOS folder
(5) tns build iOS  

It failed with the following message

error: Multiple commands produce '/Users/xxx/Projects/NativeScriptProjects/FieldCompass/platforms/ios/build/emulator/FieldCompass.app':
1) Target 'FieldCompass' has create directory command with output '/Users/xxx/Projects/NativeScriptProjects/FieldCompass/platforms/ios/build/emulator/FieldCompass.app'
2) That command depends on command in Target 'FieldCompass': script phase “[CP] Copy Pods Resources”
warning: ignoring duplicated output file: '/Users/xxx/Projects/NativeScriptProjects/FieldCompass/platforms/ios/build/emulator/FieldCompass.app' (in target 'FieldCompass')
note: Using new build systemnote: Planning buildnote: Constructing build description

any suggestions please.

Thanks

**Comment by halaharr** [comment]
Here is my firebase.mativescript.json file contents
{
    "messaging": true,
    "external_push_client_only": true,
    "using_ios": true,
    "using_android": true
}

**Comment by EddyVerbruggen** [comment]
That’s not a valid combination of config options. Better remove that json file and the platforms folder, then run ‘npm i’.

**Comment by halaharr** [comment]
Hi,
    Thanks for responding. I removed the firebase.nativescript.json file and removed iOS platform and ran "tns build iOS" and still getting the same message. I am using the plugin just for push notification. Did I need to run anything else to generate firebase.nativesacript.json file?

Thanks for all your help

**Comment by halaharr** [comment]
I also ran "nom I"

Thanks

**Comment by EddyVerbruggen** [comment]
Share a repo and I’ll take a look.
