### ISSUE TITLE
Auth: log out after app rebuild

### ISSUE THREAD

**Issue by jnorkus** [EddyVerbruggen/nativescript-plugin-firebase#938]
Whenever app is rebuilt, Firebase auth asks to log in again. This is annoying for users when they update their app via Google Play or App Store.

I am not sure if this is something that comes with the Firebase native SDKs or happens with NS/plugin.

Any insight on this?

**Comment by EddyVerbruggen** [comment]
Isn't it because the CLI actually removes and adds the app? That's not what appstores do.

**Comment by jnorkus** [comment]
Initially I thought this is only seen while developing, i.e. when working with the CLI. But now we're observing the same issue with the app stores.

**Comment by EddyVerbruggen** [comment]
I guess it depends on how you handle login, and where Firebase caches those credentials. I don't have much knowledge about that so you'd better Google a bit.
