### ISSUE TITLE
cloud function never resolving

### ISSUE THREAD

**Issue by cmckni3** [EddyVerbruggen/nativescript-plugin-firebase#939]
`handleCompletion` is never called by `callable.callWithObjectCompletion` and `callable.callWithCompletion`.

Followed [installation instructions](https://github.com/EddyVerbruggen/nativescript-plugin-firebase#installation) and [cloud functions instructions](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/FUNCTIONS.md#enabling-cloud-functions). Installed the [demo cloud function](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/ff95c77c7b09acf66654f53c52e8ae0c8d7b1c78/demo/firebasefunctions/functions/src/index.ts#L15-L19). Using the [default examples](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/FUNCTIONS.md#httpscallable) never resolve the promise.

Any ideas? Permissions error maybe?

**Comment by EddyVerbruggen** [comment]
Do you have something like this? https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/ff95c77c7b09acf66654f53c52e8ae0c8d7b1c78/demo/firebasefunctions/functions/src/index.ts#L15-L19

**Comment by cmckni3** [comment]
@EddyVerbruggen yep except `exports.helloName = ...` due to lack of import/export support. Calling from Firebase cli works.

**Comment by cmckni3** [comment]
Do you think the Firebase sdk needs to be updated from 5.6.0 to 5.9.0?

**Comment by EddyVerbruggen** [comment]
No idea. I copied my function from their docs.

**Comment by cmckni3** [comment]
@EddyVerbruggen where is the `Podfile` and `include.gradle` located for this plugin? I found this [documentation](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/REMOTECONFIG.md#enabling-remote-config) but those files do not exist.

**Comment by EddyVerbruggen** [comment]
In the same location as any other plugin: `node_modules/<plugin>/platforms/[ios/Podfile | android/include.gradle]`.

But those should actually not be edited manually; if you need to change them, remove `firebase.nativescript.json` (app root) and run `npm i`. If anything was changed in that json file, remove the `/platforms` folder.

**Comment by cmckni3** [comment]
oh ok. I see you are using a script to generate them. I have seen [other](https://github.com/nstudio/nativescript-checkbox/blob/master/platforms/ios/Podfile) [approaches](https://docs.nativescript.org/plugins/cocoapods#wrap-the-library-as-nativescript-plugin)

**Comment by EddyVerbruggen** [comment]
Yes, I have [a ton of those as well](onsole.firebase.google.com), but this plugin should *only* include Pods/.aars the developer wants. Otherwise your project be huge while you only want fi firestore.
