### ISSUE TITLE
Error during init of firebase in Android

### ISSUE THREAD

**Issue by halaharr** [EddyVerbruggen/nativescript-plugin-firebase#942]
Hi,
     I am getting the following error when I run on android during the init of firebase.
 TypeError: Cannot read property 'getInstance' of undefined.

Here is the code I am using:
firebase.init({
            onMessageReceivedCallback: message => {
                console.log("Push message received");
                setTimeout(() => {
                    alert({
                        title: "Push message!",
                        message: (message.title !== undefined ? message.body : ""),
                        okButtonText: "Sw33t"
                    });
                }, 500);
            }

        })
            .then((data) => {
                console.log('Fiebase.init done!!!');
            })
            .catch((err) => {
                console.log('---->Erroor in firebase init---->', err);
            });

Thanks for your help

**Comment by EddyVerbruggen** [comment]
Duplicates #933
