### ISSUE TITLE
.startAfter() is not working

### ISSUE THREAD

**Issue by tingfong214** [EddyVerbruggen/nativescript-plugin-firebase#945]
```
firebase.firestore().collection('collection')
     .orderBy(order,'desc')
     .startAfter(number)
     .limit(5)
     .get()
     .then(querySnapshot => {
         querySnapshot.forEach(doc => {
                    //doc processing
          })
})
```

The order is by some scoring order. (number)
Without .startAfter(), the database can be easily retrieved.
However, as .startAfter() is added, it fails and nothing happens. 
Did I do something wrong? Thank you

**Comment by EddyVerbruggen** [comment]
According to the documentation and demo app `startAfter` should be used with a 'document reference'.

**Comment by tingfong214** [comment]
Thank You so much
