### ISSUE TITLE
Nested GeoPoint gets saved as object in Firestore on iOS

### ISSUE THREAD

**Issue by abhayastudios** [EddyVerbruggen/nativescript-plugin-firebase#947]
GeoPoint gets saved as object in Firestore on iOS with plugin `7.1.2` (and `6.8.1` for that matter). On Android it works fine.

**Comment by EddyVerbruggen** [comment]
Hi, can you share the call you use?

**Comment by abhayastudios** [comment]
@EddyVerbruggen let me know if you were able to reproduce or whether you need me to create a little app to demonstrate the issue

**Comment by EddyVerbruggen** [comment]
That's strange.. I just tested this in the demo-ng app (iOS sim, latest plugin version):

```typescript
import { firestore } from "nativescript-plugin-firebase";
const firebase = require("nativescript-plugin-firebase/app");

  lastKnownLocation: firebase.firestore().GeoPoint(4.34, 5.67),
  lastKnownLocation2: firestore.GeoPoint(4.34, 5.67)
```

Result:

<img width="553" alt="screenshot 2018-10-08 at 17 28 06" src="https://user-images.githubusercontent.com/1426370/46618353-8cb69200-cb1f-11e8-8f31-a7da27c7dc8c.png">

I will try `.set` as well.

**Comment by EddyVerbruggen** [comment]
Hmm, `.set` works equally well for me with similar code.

**Comment by abhayastudios** [comment]
Thanks for checking @EddyVerbruggen. I will try to replicate in a minimal project.

**Comment by abhayastudios** [comment]
Hi @EddyVerbruggen,

So it seems that the issue occurs only when using GeoPoint nested in an object, such as below.

```
let profile:any = {
      first: 'First',
      last: 'Last',
      location: {
        geoPoint: firestore.GeoPoint(52.345342, 4.900721400000066),
        latitude: 52.345342,
        longitude: 4.900721400000066
      }
    }

    let geoRef:firestore.CollectionReference = firestore.collection("geopoints");

    geoRef.doc('issue947').set(profile)
    .then(() => { console.log("Saved GeoLocation data to Firestore!"); })
    .catch((error) => console.log(`Error saving GeoLocation data to Firestore: ${error}`));
  }
```

Is this expected behavior? As said, on Android this still produces a GeoPoint type in Firestore.

Thanks!

**Comment by EddyVerbruggen** [comment]
That could indeed be a limitation, but let's see if it's fixable. Thanks for investigating this!

**Comment by EddyVerbruggen** [comment]
Fixed in 7.1.4. Note that on iOS the same issue/fix applies for storing nested server timestamps, document references, and array union/remove.

**Comment by EddyVerbruggen** [comment]
Hmm 🤔.. I don't have that kind of usage, but wouldn't mind merging that!

**Comment by abhayastudios** [comment]
OK submitted a PR. Sorry, next time I will inform you when I decide to try myself :)

**Comment by EddyVerbruggen** [comment]
Haha no worries. I’ll pop out a new version late(r) today.
