### ISSUE TITLE
Error in firebase.init: ReferenceError: Can't find variable: FIROptions

### ISSUE THREAD

**Issue by donny08** [EddyVerbruggen/nativescript-plugin-firebase#948]
I added **"nativescript-plugin-firebase"**: "^7.1.2" plugin. I getting error running on ios simulator, but works fine in Android

```
const firebase = require("nativescript-plugin-firebase");

firebase.init({
    }).then((instance) => {
      console.log("firebase.init done");
    }, (error) => {
      console.log("firebase.init error: " + error);
    });
```

`firebase.init error: ReferenceError: Can't find variable: FIROptions`

Can anyone help me out.

**Comment by davecoffin** [comment]
run `pod repo update`. 
If youre using only the messaging feature, you dont need to call `init` as far as I understand it, @EddyVerbruggen correct me if I'm wrong.

**Comment by EddyVerbruggen** [comment]
Correct!

**Comment by donny08** [comment]
@davecoffin I am still facing same issue

**Comment by davecoffin** [comment]
are you using "lite" mode for push notifications only? Whats your firebase.nativescript.json file look like?

**Comment by donny08** [comment]
@davecoffin 
firebase.nativescript.json
{
    "external_push_client_only": true,
    "using_ios": true,
    "using_android": true
}

**Comment by davecoffin** [comment]
you are using lite mode, so you do not need to call firebase.init. lite mode doesnt install any cocoapods, thats why youre getting that message. follow these instructions and *only* these instructions: https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/NON_FIREBASE_MESSAGING.md

**Comment by donny08** [comment]
@davecoffin I followed the instructions, but i am not getting token. Below is code
```
messaging.registerForPushNotifications({
            onPushTokenReceivedCallback: (token: string): void => {  // This is function is not trigger 
                console.log("Firebase plugin received a push token: " + token);
            },

            onMessageReceivedCallback: (message: Message) => {
                console.log("Push message received: " + message.title);
            },
            showNotifications: true,
            showNotificationsWhenInForeground: true
        }).then(() => console.log("Registered for push"));
messaging.getCurrentPushToken()
            .then(token => console.log("Current push token:", token));// I'm getting undefined here
```

**Comment by donny08** [comment]
While running app on android. I'm getting **ERROR Error: Uncaught (in promise): Uncomment firebase-messaging in the plugin's include.gradle first**

**Comment by davecoffin** [comment]
Yea, thats the problem I was having, see this issue: https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/950 @EddyVerbruggen maybe reopen that?

To solve that, dont use lite mode. heres my json:

```
{
    "external_push_client_only": false,
    "using_ios": true,
    "using_android": true,
    "firestore": false,
    "realtimedb": false,
    "authentication": true,
    "remote_config": false,
    "messaging": true,
    "crashlytics": true,
    "crash_reporting": false,
    "storage": false,
    "functions": false,
    "facebook_auth": false,
    "google_auth": false,
    "admob": false,
    "invites": false,
    "dynamic_links": false,
    "ml_kit": false
}
```

**Comment by EddyVerbruggen** [comment]
Thanks for the help @davecoffin!

@donny08 It looks like you're adding that code to app.ts/main.ts, right? That's when you can run into the "Uncomment firebase-messaging in the plugin's include.gradle first" issue. It's because the app needs to be bootstrapped for it to get a sender ID from FCM.

Anyway, I just pushed a change for #928 which allows you to run messaging-related code before the app is bootstrapped. Available in 7.1.6.

**Comment by donny08** [comment]
@EddyVerbruggen After updating fiberbase plugin to 7.1.6. I'm facing some issues both on android and ios. 

In Android on running tns run android i m getting **Unable to apply changes on device: emulator-5554. Error is: Socket Error: Error: read ECONNRESET.**

In IOS on running tns run android i m getting **Unable to apply changes on device: B60D3C35-CC78-41BD-8671-9910C15ABFAB. Error is: Command xcodebuild failed with exit code 65.**

**Comment by donny08** [comment]
@EddyVerbruggen yes

**Comment by EddyVerbruggen** [comment]
Hmm, reboot or something - those errors have nothing to do with this plugin.

**Comment by donny08** [comment]
@EddyVerbruggen  I'm not receiving notification on IOS when it is in background. I followed  this (https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/NON_FIREBASE_MESSAGING.md).

**Comment by EddyVerbruggen** [comment]
Share a repo please.

**Comment by donny08** [comment]
@EddyVerbruggen  @davecoffin  Here `https://github.com/donny08/push-fiberbase`

**Comment by donny08** [comment]
@EddyVerbruggen I didn't commit platform folder. If needed please intimate. Thank you

**Comment by EddyVerbruggen** [comment]
You don’t have the ‘require’ of the plugin in 
https://github.com/donny08/push-fiberbase/blob/master/app/main.ts

**Comment by donny08** [comment]
@EddyVerbruggen Tried adding require in main.ts, but still i'm not getting notifications in IOS when background.

**Comment by EddyVerbruggen** [comment]
Yes, it's all in the readme (but not in your repo): https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/NON_FIREBASE_MESSAGING.md#ios

**Comment by donny08** [comment]
@EddyVerbruggen After adding entitlement file in app resource for ios, its working. But getting weird error: **Unhandled Promise rejection: Error Domain=com.google.fcm Code=2001 "FIRMessaging is already connected" UserInfo={NSLocalizedFailureReason=FIRMessaging is already connected} ; Zone: <root> ; Task: null ; Value: Error Domain=com.google.fcm Code=2001 "FIRMessaging is already connected" UserInfo={NSLocalizedFailureReason=FIRMessaging is already connected} undefined**

**Comment by EddyVerbruggen** [comment]
I don't think that matters.

**Comment by donny08** [comment]
@EddyVerbruggen Ok Thanks

**Comment by donny08** [comment]
@EddyVerbruggen In Android, if i close the  app and send notification via postman. I unable to receive notification on device. So I am using **nativescript-local-notifications** plugin. Is this right approach?

**Comment by EddyVerbruggen** [comment]
No. Remove that plugin.

**Comment by ashokch8** [comment]
Hi @EddyVerbruggen can you please help me Tried all of the above options and keep my code in app.component.ts
Error in firebase.init: ReferenceError: Can't find variable: FIROptions #948
> var firebase = require("nativescript-plugin-firebase");
 firebase.init({
            onMessageReceivedCallback: (message: any) => {
              console.log(`Title: ${message.title}`);
              console.log(`Body: ${message.body}`);
              // if your server passed a custom property called 'foo', then do this:
              console.log(`Value of 'foo': ${message.data.foo}`);
            }
          }).then(
            () => {
              console.log("firebase.init done");
            },
            (error) => {
              console.log("firebase.init error: " + error);
            }
          );

          firebase.addOnPushTokenReceivedCallback(
            function(token) {
              console.log("this is token"+ token);
            }
          );

          firebase.getCurrentPushToken().then((token: string) => {
            // may be null if not known yet
            console.log(`Current push token: ${token}`);
          });


{
  "external_push_client_only": false,
  "using_ios": true,
  "using_android": true,
  "firestore": false,
  "realtimedb": false,
  "authentication": true,
  "remote_config": false,
  "messaging": true,
  "crashlytics": false,
  "crash_reporting": false,
  "storage": false,
  "functions": false,
  "facebook_auth": false,
  "google_auth": false,
  "admob": false,
  "invites": false,
  "dynamic_links": false,
  "ml_kit": false
}

added entitlements
testing in device, following message doc
and verfify app is struct in firebase continuously showing loader
