### ISSUE TITLE
Cloud Messaging: Not getting a token back on iOS

### ISSUE THREAD

**Issue by davecoffin** [EddyVerbruggen/nativescript-plugin-firebase#950]
This worked for me initially but has stopped working. 
When building on a device I get this:
```
[org.nessit.nystpba] Requested authorization [ didGrant: 0 hasError: 0 hasCompletionHandler: 1 ]
[org.nessit.nystpba] Requesting token for remote notifications
[org.nessit.nystpba] Requested token for remote notifications [ didSucceed: 1 hasError: 0 hasCompletionHandler: 1 ]
[org.nessit.nystpba] Requested authorization [ didGrant: 1 hasError: 0 hasCompletionHandler: 1 ]
[org.nessit.nystpba] Requesting token for remote notifications
[org.nessit.nystpba] Requested token for remote notifications [ didSucceed: 1 hasError: 0 hasCompletionHandler: 1 ]
[org.nessit.nystpba] Did receive remote notification token
[org.nessit.nystpba] Sending received device token to delegate UIApplication
[org.nessit.nystpba] Did receive remote notification token
[org.nessit.nystpba] Sending received device token to delegate UIApplication
```

then when I call `areNotificationsEnabled` I get this:
```
[org.nessit.nystpba] Getting notification settings (sync)
[org.nessit.nystpba] Got notification settings [ hasResult: 1 ]
[org.nessit.nystpba] Getting notification categories (sync)
[org.nessit.nystpba] Got 0 notification categories
```
and it returns `true`

then when I call `getCurrentPushToken` the token is `undefined`.

Any ideas why this would be happening?

**Comment by davecoffin** [comment]
FYI, switching out of "lite" mode, returns me a token, but now I get the following error that crashes my app when I receive a notification: 

`Terminating app due to uncaught exception 'NativeScript encountered a fatal error: ReferenceError: Can't find variable: FIRAuth`

Thats this line in messages.js: 
```
appDelegate.prototype.applicationDidReceiveRemoteNotificationFetchCompletionHandler = function (app, notification, completionHandler) {
        // Pass notification to auth and check if they can handle it (in case phone auth is being used), see https://firebase.google.com/docs/auth/ios/phone-auth
       ******* if (firebase_common_1.firebase._configured && FIRAuth.auth().canHandleNotification(notification)) {******
            completionHandler(1 /* NoData */);
            return;
        }
        completionHandler(0 /* NewData */);
        handleRemoteNotification(app, notification);
    };
```

**Comment by davecoffin** [comment]
Looks like the project *needs* to have Firebase Authentication turned on to use messaging. I enabled Authentication and now everything works fine.

**Comment by EddyVerbruggen** [comment]
Hey @davecoffin, sorry, seems like I missed that one. I've now guarded it, so with 7.1.3 enabling authentication is no longer needed (as intended).

**Comment by davecoffin** [comment]
What about the original issue? I am not able to use lite mode.

**Comment by EddyVerbruggen** [comment]
Give demo-push a spin with plugin version 7.1.3. It works great for me on iOS 12 (device). If that works and your app doesn't then I'd be happy to take a look.
