### ISSUE TITLE
Failed to verify bitcode in TNSMLKitCamera.framework/TNSMLKitCamera

### ISSUE THREAD

**Issue by FatimahSanni** [EddyVerbruggen/nativescript-plugin-firebase#954]
Hi,

I am experiencing this issue that causes `tns run ios` to fail when building on a real device. Using the emulator works fine but whenever I try to run or build on a real device, the changes cannnot be applied and the error is `error: exportArchive: Failed to verify bitcode in TNSMLKitCamera.framework/TNSMLKitCamera:
error: Bundle only contains bitcode-marker /var/folders/5d/_v1mn0f16w7dt6k7dbvby_c00000gn/T/XcodeDistPipeline.neH/Root/Payload/mobile.app/Frameworks/TNSMLKitCamera.framework/TNSMLKitCamera (armv7)`

Any help/guidance is appreciated. Thanks

**Comment by Cheas** [comment]
I'm experiencing a similar problem.

**Comment by EddyVerbruggen** [comment]
Thanks for the details guys! Especially @jpakulski's note about Enterprise distribution put me on the right path to reproduce this issue. Will look into it.
