### ISSUE TITLE
Adding a FRONT or REAR property when using Ml Kit, in order to select the camera-facing direction. 

### ISSUE THREAD

**Issue by hugomejia** [EddyVerbruggen/nativescript-plugin-firebase#955]
It seems currently not possible to choose the default camera direction "Rear" or "Front" when using ML Kit. This feature would be particularly useful when using the face detection features for selfies, chat or video conferences.

Thanks @EddyVerbruggen .

**Comment by EddyVerbruggen** [comment]
Thanks for opening this issue. I agree this is a nice addition and I've added a little scaffolding for it already. Will try to make time to add it to the next version.

**Comment by EddyVerbruggen** [comment]
Update the demo and docs for the new `preferFrontCamera` property (default `false`). Available in 7.1.6 later today.
