### ISSUE TITLE
Error when compiling with AOT

### ISSUE THREAD

**Issue by joshcomley** [EddyVerbruggen/nativescript-plugin-firebase#963]
(Fix below, suggested for documentation unless it's only me that gets the problem)

I was getting this error only when compiling with AOT:

    Undefined symbols for architecture armv7:
      "_CACurrentMediaTime", referenced from:
          -[FBMLx_CCTClearcutTimerHistogram start] in FirebaseMLCommon(CCTClearcutCounters_0f7757c22b26f43080a5b745a1049c6c.o)
          -[FBMLx_CCTClearcutTimerHistogram stopAndLogTimeWithDimension:] in FirebaseMLCommon(CCTClearcutCounters_0f7757c22b26f43080a5b745a1049c6c.o)
          l088 in GoogleMobileVision
          l091 in GoogleMobileVision
    ld: symbol(s) not found for architecture armv7
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build systemnote: Planning buildnote: Constructing build description

I looked up `_CACurrentMediaTime` and it ultimately let me to something hinting that `QuartzCore` is needed. So I added the following line to my `build.xxconfig` and it fixed it:

    OTHER_LDFLAGS = $(inherited) -framework "QuartzCore"

Now I can compile with AOT (also needed the line `IPHONEOS_DEPLOYMENT_TARGET = 10.0;`, but I believe this is documented).

This is a bug report with, at least for me, a solution so hopefully it can be added to the documentation.

Many thanks for this plugin!

**Comment by EddyVerbruggen** [comment]
Thanks for sharing! It may be fixed with plugin version 7.4.0, but I've never seen this particular error. I'll keep this in mind though in case it does pop up.

**Comment by paweldziura** [comment]
I experience this error with v7.4.6 and previous ones too when sending the app to Testflight. It works with tns run ios but doesn't work with tns publish ios.
