### ISSUE TITLE
Constantly rebuilding when running with .dev and .prod separation

### ISSUE THREAD

**Issue by edusperoni** [EddyVerbruggen/nativescript-plugin-firebase#968]
Nativescript detects the copy from GoogleService-Info.plist.dev to GoogleService-Info.plist as a file change, even if both files are the same. As such, running `tns run ios` results in endless xcode builds and app installs. Maybe there should be a check to see if the files are the same?

How to reproduce:
Use `GoogleService-Info.plist.dev` and ` GoogleService-Info.plist.prod`
Run `tns run ios`
Check the console for constant rebuilding

**Comment by EddyVerbruggen** [comment]
Any ideas how to fix this? I'm not personally using this setup..

**Comment by edusperoni** [comment]
I have done something similar where I read both files and compare, I can make a quick PR.

Should I edit both of these:
https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/635d07a0c978b11ec264caf88fbc8552d06a7982/publish/scripts/installer.js
https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/635d07a0c978b11ec264caf88fbc8552d06a7982/src/scripts/postinstall.js

?

**Comment by EddyVerbruggen** [comment]
Hey @edusperoni that would be great! You only need to edit the first one, because `postinstall.js` is generated from that one.

**Comment by EddyVerbruggen** [comment]
I think it's best to ask @abhayastudios for his opinion because he added this to the project and I don't want to break his workflow.

**Comment by edusperoni** [comment]
PR is done, if @abhayastudios approves it, it's ready to be merged.

**Comment by abhayastudios** [comment]
Hi @edusperoni, sorry for the delay, I am a bit busy at the moment. 

As far as I know your PR should not be needed. The idea is that the plist is copied only if a project prepare is required, which is checked in our `before-checkForChanges` hook which also creates the `platforms/ios/.pluginfirebaseinfo` status file. If this file exists and the environment didn't change and we are not running a release build, then we are not forcing a prepare and thus are not updating the plist files.

Can you confirm the `.pluginfirebaseinfo` is properly created? Can you send the relevant console output (especially the output from the `before-checkForChanges` hook), to try and see what is going on?

Thanks!

**Comment by edusperoni** [comment]
Actually it runs despite not needing to prepare, see the last "else":

```
        if (fs.existsSync(npfInfoPath)) {
            var npfInfo = undefined;
            try { npfInfo = JSON.parse(fs.readFileSync(npfInfoPath, 'utf8')); }
            catch (e) { $logger.info('nativescript-plugin-firebase: error reading '+npfInfoPath); }

            if (npfInfo && npfInfo.hasOwnProperty('buildType') && npfInfo.buildType===buildType) {
                $logger.info('nativescript-plugin-firebase: building for same environment, not forcing prepare.');
                forcePrepare=false;
            }
        } else { $logger.info('nativescript-plugin-firebase: '+npfInfoPath+' not found, forcing prepare!'); }

        if (forcePrepare && fs.existsSync(nsPrepareInfoPath)) {
            $logger.info('nativescript-plugin-firebase: running release build or change in environment detected, forcing prepare!');

            if (fs.existsSync(npfInfoPath)) { fs.unlinkSync(npfInfoPath); }
            fs.unlinkSync(nsPrepareInfoPath);

            if (copyPlist(copyPlistOpts)) { resolve(); } else { reject(); }
        } else { if (copyPlist(copyPlistOpts)) { resolve(); } else { reject(); } }
```

**Comment by edusperoni** [comment]
Actual output:

```
Successfully transferred all files.
Refreshing application...
Successfully synced application my.app.handle on device DEVICEID.
Executing before-checkForChanges hook from /Users/mobiledev/Desktop/ns-project/hooks/before-checkForChanges/firebase-copy-google-services.js
nativescript-plugin-firebase: building for same environment, not forcing prepare.
nativescript-plugin-firebase: copy /Users/mobiledev/Desktop/ns-project/app/App_Resources/iOS/GoogleService-Info.plist.dev to /Users/mobiledev/Desktop/ns-project/app/App_Resources/iOS/GoogleService-Info.plist.
Executing before-shouldPrepare hook from /Users/mobiledev/Desktop/ns-project/hooks/before-shouldPrepare/nativescript-dev-webpack.js
```

**Comment by abhayastudios** [comment]
@edusperoni you are right, somehow the version of the `before-checkForChanges` hook that I used locally is different from what ended up in the project.

PR #974 contains a fix (no need to do a comparison between the files, as you pointed out above, it should just not be copied if the environment does not change)

**Comment by edusperoni** [comment]
Seems good to me :)

**Comment by EddyVerbruggen** [comment]
Excellent teamwork guys, thanks a lot!

**Comment by edusperoni** [comment]
Uhm, apparently this isn't fixed as I thought. Even when forcing a prepare, it's not copying because `.nsprepareinfo` is not present in the first dev run (as this runs before the prepare happens).

```
 if (forcePrepare && fs.existsSync(nsPrepareInfoPath)) {
            $logger.info('nativescript-plugin-firebase: running release build or change in environment detected, forcing prepare!');
```

if I just use `if (forcePrepare)`, it works correctly when using `tns platform clean ios && tns run ios`. @abhayastudios can you check if this fix also works for you?

**Comment by abhayastudios** [comment]
@edusperoni sorry for the delay. This seems to work. Can you submit this PR? Thanks!
