### ISSUE TITLE
Failed to run on IOS

### ISSUE THREAD

**Issue by anaszgh** [EddyVerbruggen/nativescript-plugin-firebase#972]
I'm trying to run a simple project on IOS that uses the firebase plugin for AdMob

The project works correctly on Android, but whenever i try to run ```tns run ios --provision Dev```

the build fails and returns this message

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_ASIdentifierManager", referenced from:
      objc-class-ref in GoogleMobileAds(flat-x86_64)
  "_OBJC_CLASS_$_WKWebView", referenced from:
      objc-class-ref in FirebaseDynamicLinks(FIRDLJavaScriptExecutor_0038e9b0f22e18bf943e5e3e449a1f2f.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by anaszgh** [comment]
Please note that i have added the ```GoogleServices-Info.plist ``` and the entitlements files to 

```App_Resources/IOS```

**Comment by EddyVerbruggen** [comment]
Can you try removing the platforms folder?

**Comment by anaszgh** [comment]
I already did before posting this issue, but it didn't resolve it.

**Comment by EddyVerbruggen** [comment]
Can you share that repo?

**Comment by anaszgh** [comment]
Sure, It is on Gitlab, can you please provide me with email address and i'll add it to the repo.

**Comment by EddyVerbruggen** [comment]
eddyverbruggen  at gmail

**Comment by anaszgh** [comment]
@EddyVerbruggen Invitation sent by email

**Comment by EddyVerbruggen** [comment]
@anaszgh I cloned the repo and updated the version of `nativescript-plugin-firebase` to the latest release and ran `npm i`. `tns build ios` succeeds...

**Comment by anaszgh** [comment]
I have tried to remove node_modules, hooks and platforms folders 

then updated the ```nativescript-plugin-firebase``` to version 7.1.6

then ran ```npm i tns build ios```

and it resulted in build failed and the following logs & errors

```
ld: warning: directory not found for option '-F/Users/anasaref/Library/Developer/Xcode/DerivedData/StopTheWatch-gzbqgdbcbaiuzwbvorzxrrombsjk/Build/Products/Debug-iphonesimulator/FirebaseDynamicLinks'
ld: warning: directory not found for option '-F/Users/anasaref/Library/Developer/Xcode/DerivedData/StopTheWatch-gzbqgdbcbaiuzwbvorzxrrombsjk/Build/Products/Debug-iphonesimulator/GoogleUtilities'
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_ASIdentifierManager", referenced from:
      objc-class-ref in GoogleMobileAds(flat-x86_64)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ld: warning: directory not found for option '-F/Users/anasaref/Library/Developer/Xcode/DerivedData/StopTheWatch-gzbqgdbcbaiuzwbvorzxrrombsjk/Build/Products/Debug-iphonesimulator/FirebaseDynamicLinks'
ld: warning: directory not found for option '-F/Users/anasaref/Library/Developer/Xcode/DerivedData/StopTheWatch-gzbqgdbcbaiuzwbvorzxrrombsjk/Build/Products/Debug-iphonesimulator/GoogleUtilities'
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_ASIdentifierManager", referenced from:
note: Using new build systemnote: Planning buildnote: Constructing build description
** BUILD FAILED **

Command xcodebuild failed with exit code 65

```

**Comment by EddyVerbruggen** [comment]
Have you tried that in the `mobile` folder?

**Comment by anaszgh** [comment]
Sorry for this misunderstanding, mobile folder is outdated the problem is with Stop The Watch folder

**Comment by EddyVerbruggen** [comment]
I tried one as well but it failed because (it seems like) there’s a space in the foldername..

**Comment by anaszgh** [comment]
I'll remove the space and try again.

**Comment by anaszgh** [comment]
Still receiving the same error, exit code 65 even after removing spaces in the folder name

**Comment by anaszgh** [comment]
The strange thing is that event mobile folder threw the same error on `ios build`

**Comment by EddyVerbruggen** [comment]
What `tns --version` are you on? I'm on 4.2.4.

If that doesn't help, try adding https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/715862dae29c65fbc83aa65024eabddc606ec104/demo/firebase.nativescript.json#L18 and remove the platforms folder.

**Comment by packytagliaferro** [comment]
I also was unable to get it to run on iOS. I got  exit code 65 over and over. I tried all suggested methods here. 

```
"dependencies": {
    "@vue/devtools": "5.0.0-beta.3",
    "nativescript-loading-indicator": "^2.4.0",
    "nativescript-localstorage": "^2.0.0",
    "nativescript-socket.io": "^0.9.0",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-toast": "^1.4.6",
    "nativescript-videoplayer": "^4.2.0",
    "nativescript-vue": "^2.0.0",
    "nativescript-vue-devtools": "^1.0.0",
    "nativescript-zxing": "^1.5.7",
    "tns-core-modules": "^4.2.1",
    "vuex": "^3.0.1"
  },
```
