### ISSUE TITLE
Delete individual field feature

### ISSUE THREAD

**Issue by keerl** [EddyVerbruggen/nativescript-plugin-firebase#975]
Would it be possible to implement a feature to delete an individual field?

[https://firebase.google.com/docs/firestore/manage-data/delete-data](https://firebase.google.com/docs/firestore/manage-data/delete-data)

```
var cityRef = db.collection('cities').doc('BJ');

// Remove the 'capital' field from the document
var removeCapital = cityRef.update({
    capital: firebase.firestore.FieldValue.delete()
});
```

**Comment by EddyVerbruggen** [comment]
Yep, looks like a nice feature to have!

**Comment by EddyVerbruggen** [comment]
Done, check the doc: https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/FIRESTORE.md#delete-specific-fields-in-a-document
