### ISSUE TITLE
Adding facebook app id resolves to an error

### ISSUE THREAD

**Issue by zslusnys** [EddyVerbruggen/nativescript-plugin-firebase#977]
mobile-app/platforms/android/app/build/intermediates/
manifests/full/debug/AndroidManifest.xml:56: AAPT: error: resource string/facebook_app_id
(aka org.mobileapp.application:string/facebook_app_id) not found.

I got this after following the suggestion to add facebook_app_id into its own xml file of: facebooklogin.xml positioned under App_Resources/Android/values/

When I pasted that string insode App_Resources/Android/res/values/strings.xml then everything worked as expected. 

My question is, am I doing something wrong that this unexpected behaviour happened? 

Thank you for the time.

**Comment by zslusnys** [comment]
I've checked out the paths again and while in documentation it says add the meta to:
`app\App_Resources\Android\AndroidManifest.xml`

and add the file of facebooklogin.xml to: 
`app\App_Resources\Android\values\facebooklogin.xml`

in my case everything is in `app/App_Resources/Android/src/main/res/` directory

**Comment by EddyVerbruggen** [comment]
Share a repo - hard to give any meaningful feedback without being able to look at the project.

**Comment by mbouclas** [comment]
@zslusnys is correct. The `facebooklogin.xml` file needs to be placed under `App_Resources\Android\src\main\res\values` and not `App_Resources\Android\values\facebooklogin.xml`. At least in my case this is what worked in the end

**Comment by EddyVerbruggen** [comment]
I've updated the documentation.
