### ISSUE TITLE
Excessive logs on iOS

### ISSUE THREAD

**Issue by FranciZ** [EddyVerbruggen/nativescript-plugin-firebase#978]
On iOS there's excessive logging after installing the firebase plugin and it's very distracting. This was described in the below issue on nativescript-cli repo.

https://github.com/NativeScript/nativescript-cli/issues/3544

Log example:
```
TIC TLS Event [8:0x1c4378b40]: 1, Pending(0)
TIC TLS Event [8:0x1c4378b40]: 2, Pending(0)
TIC TLS Event [8:0x1c4378b40]: 11, Pending(0)
TIC TLS Event [8:0x1c4378b40]: 12, Pending(0)
TIC TLS Event [8:0x1c4378b40]: 14, Pending(0)
TIC TLS Trust Result [8:0x1c4378b40]: 0
TIC TLS Event [8:0x1c4378b40]: 20, Pending(0)
TIC TCP Conn Connected [8:0x1c4378b40]: Err(16)
TIC TCP Conn Event [8:0x1c4378b40]: 1
TIC TCP Conn Event [8:0x1c4378b40]: 8
TIC TLS Handshake Complete [8:0x1c4378b40]
Task <BAF32BAC-8310-4670-BACB-43893D5E20FF>.<2> now using Connection 8
Task <BAF32BAC-8310-4670-BACB-43893D5E20FF>.<2> sent request, body N
Task <BAF32BAC-8310-4670-BACB-43893D5E20FF>.<2> received response, status 200 content K
Task <BAF32BAC-8310-4670-BACB-43893D5E20FF>.<2> response ended

```

**Comment by EddyVerbruggen** [comment]
Can you narrow it down to a certain part of Firebase perhaps? I mean, if you don't install any additional components like Google Auth, Realtime DB, etc, do you still see those messages?

**Comment by cerireyhan** [comment]
I only use Firebase-Cloud-Messaging and have been seeing those logs for a long time. Only happens in real iOS device though.

**Comment by EddyVerbruggen** [comment]
Thanks! It would be nice to know if using anything *but* Messaging would show the same amount logging.

**Comment by FranciZ** [comment]
Unfortunately it does. Setup a sample project with just the `storage` and still get the excessive logs.

`firebase.nativescript.json`

```json
{
    "external_push_client_only": false,
    "using_ios": true,
    "using_android": false,
    "firestore": false,
    "realtimedb": false,
    "authentication": false,
    "remote_config": false,
    "messaging": false,
    "crashlytics": false,
    "crash_reporting": false,
    "storage": true,
    "functions": false,
    "facebook_auth": false,
    "google_auth": false,
    "admob": false,
    "invites": false,
    "dynamic_links": false,
    "ml_kit": false
}
```

An example of the logs:
```
TIC TLS Event [3:0x1c0569180]: 1, Pending(0)
TIC TLS Event [3:0x1c0569180]: 2, Pending(0)
TIC TLS Event [3:0x1c0569180]: 11, Pending(0)
TIC TLS Event [3:0x1c0569180]: 12, Pending(0)
TIC TLS Event [3:0x1c0569180]: 14, Pending(0)
System Trust Evaluation yielded status(0)
TIC TLS Trust Result [3:0x1c0569180]: 0
TIC TLS Event [3:0x1c0569180]: 20, Pending(0)
TIC TCP Conn Connected [3:0x1c0569180]: Err(16)
TIC TCP Conn Event [3:0x1c0569180]: 1
TIC TCP Conn Event [3:0x1c0569180]: 8
TIC TLS Handshake Complete [3:0x1c0569180]
Task <AF686A38-97D5-4BE1-84F6-FEF90569E194>.<1> now using Connection 3
Task <AF686A38-97D5-4BE1-84F6-FEF90569E194>.<1> sent request, body S
Task <AF686A38-97D5-4BE1-84F6-FEF90569E194>.<1> received response, status 204 content U
Task <AF686A38-97D5-4BE1-84F6-FEF90569E194>.<1> response ended
TIC TCP Conn Cancel [3:0x1c0569180]
[3 <private> stream, pid: 2578, url: https://app-measurement.com/a, tls] cancelled
[3.1 2FB8B69B-568C-4E9A-BEC4-DFE8A0B3294D <private>.57545<-><private>]
Connected Path: satisfied (Path is satisfied), interface: en0, ipv4, dns
Duration: 0.154s, DNS @0.002s took 0.004s, TCP @0.011s took 0.022s, TLS took 0.080s
bytes in/out: 3588/1248, packets in/out: 9/10, rtt: 0.020s, retransmitted packets: 0, out-of-order packets: 0
TIC TCP Conn Destroyed [3:0x1c0569180]
TIC Read Status [3:0x0]: 1:57
TIC Read Status [3:0x0]: 1:57
```

**Comment by EddyVerbruggen** [comment]
That's good to know, thanks. So it must be because of FirebaseCore or Analytics. If you want we can rule Analytics out by disabling it (best to do it in the plist I guess): https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/ANALYTICS.md#analyticssetanalyticscollectionenabled

Anyway, I don't think the plugin can do anything to stop it.. so similar reports (about the native iOS Firebase SDK) should be on StackOverflow et al..

**Comment by cerireyhan** [comment]
Must be coming from FirebaseCore, I still see the logs after disabling Analytics in plist.

**Comment by EddyVerbruggen** [comment]
I don't see how the plugin can change any of that. Perhaps contact Firebase support?

**Comment by jnorkus** [comment]
Has anyone found any way to fix this? Or a reference to Firebase SDK issue? It makes it so much more difficult to debug on an iOS device!

**Comment by GrEg00z** [comment]
here [](https://github.com/NativeScript/nativescript-cli/issues/3727)

**Comment by virtualbjorn** [comment]
@GrEg00z its not a proper solution as the console.dir is not working when piping
