### ISSUE TITLE
`Firebase (~> 3.3.0)` required by `Podfile`

### ISSUE THREAD

**Issue by jahidshohel** [EddyVerbruggen/nativescript-plugin-firebase#98]
I am tns version 2.1.1. Was trying to build using `tns build ios` and got this error -

$ tns build ios
Executing before-prepare hook from /Users/jahid/Development/temp/native_script/ns-learning/hooks/before-prepare/nativescript-dev-typescript.js
Found peer TypeScript 1.8.10
The depedency located at /Users/jahid/Development/temp/native_script/ns-learning/node_modules/@angular/platform-server/node_modules/parse5 with version  1.3.2 will be replaced with dependency located at /Users/jahid/Development/temp/native_script/ns-learning/node_modules/nativescript-angular/node_modules/parse5 with version 1.4.2
Successfully prepared plugin nativescript-angular for ios.
Successfully prepared plugin nativescript-intl for ios.
Successfully prepared plugin nativescript-plugin-firebase for ios.
Successfully prepared plugin tns-core-modules for ios.
The iOS Deployment Target is now 8.0 in order to support Cocoa Touch Frameworks.
Successfully prepared plugin tns-core-modules-widgets for ios.
Installing pods...
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `Firebase (~> 3.3.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `Firebase (~> 3.3.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
Processing node_modules failed. Error: Command sandbox-pod failed with exit code 1
Sending exception report (press Ctrl+C to stop).....

**Comment by shripalsoni04** [comment]
I also got the exact same issue and I solved it by executing `pod repo update` command as it is said in error.

This command may take some time to complete. So please be patient.

Hope this will help.

**Comment by jahidshohel** [comment]
@shripalsoni04 : Thanks for your reply. You executed that command being inside the project?

**Comment by shripalsoni04** [comment]
I executed from inside project but ideally it should not matter, because that command is updating all spec-repos at ~/.cocoapods/repos. Reference: https://guides.cocoapods.org/terminal/commands.html#pod_repo_update

**Comment by jahidshohel** [comment]
Will try that. Thanks 👍

**Comment by jlooper** [comment]
I made some notes on this issue when I hit it: http://www.ladeezfirstmedia.com/2016/07/11/when-cocoapods-attack/ if that might be of use to you

**Comment by jahidshohel** [comment]
It works. Thanks a lot 👍

**Comment by blaur** [comment]
Hi guys,

Did any of you see the following? I do not seem to be able to get around it.

```
[!] /usr/bin/git fetch --unshallow

error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly


/Users/user/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/lib/cocoapods/executable.rb:69:in `execute_command'
/Users/user/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/lib/cocoapods/executable.rb:27:in `block in executable'
/Users/user/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/lib/cocoapods/sources_manager.rb:123:in `block in update_git_repo'
/Users/user/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:161:in `info'
/Users/user/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/lib/cocoapods/sources_manager.rb:122:in `update_git_repo'
/Users/user/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-core-1.0.1/lib/cocoapods-core/source.rb:339:in `block in update'
/Users/user/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-core-1.0.1/lib/cocoapods-core/source.rb:337:in `chdir'
/Users/user/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-core-1.0.1/lib/cocoapods-core/source.rb:337:in `update'
/Users/user/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-core-1.0.1/lib/cocoapods-core/master_source.rb:15:in `update'
/Users/user/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/lib/cocoapods/sources_manager.rb:88:in `block (2 levels) in update'
/Users/user/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Users/user/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/lib/cocoapods/sources_manager.rb:87:in `block in update'
/Users/user/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/lib/cocoapods/sources_manager.rb:86:in `each'
/Users/user/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/lib/cocoapods/sources_manager.rb:86:in `update'
/Users/user/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/lib/cocoapods/command/repo/update.rb:23:in `run'
/Users/user/.rvm/gems/ruby-2.3.0@global/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/user/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Users/user/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/Users/user/.rvm/rubies/ruby-2.3.0/bin/pod:23:in `load'
/Users/user/.rvm/rubies/ruby-2.3.0/bin/pod:23:in `<main>'
/Users/user/.rvm/gems/ruby-2.3.0@global/bin/ruby_executable_hooks:15:in `eval'
/Users/user/.rvm/gems/ruby-2.3.0@global/bin/ruby_executable_hooks:15:in `<main>'
```
