### ISSUE TITLE
ML Kit Barcode Recognition for ISBN Format 

### ISSUE THREAD

**Issue by rg777** [EddyVerbruggen/nativescript-plugin-firebase#980]
I am trying to recognize the bar code for books with ISBN Format (13 Digit). 
Is this not yet supported for this plugin?

I tried to make some changes in the source code by referencing this url:
[Firebase Barcode Format](https://developers.google.com/android/reference/com/google/firebase/ml/vision/barcode/FirebaseVisionBarcode.html#TYPE_ISBN)

Changes made:
A. barcodescanning-common.js
```
(function (BarcodeFormat) {
    // UNKNOWN = -1,
    // ALL = 0,
    BarcodeFormat[BarcodeFormat["CODE_128"] = 1] = "CODE_128";
    BarcodeFormat[BarcodeFormat["CODE_39"] = 2] = "CODE_39";
    BarcodeFormat[BarcodeFormat["ISBN"] = 3] = "ISBN";  // Added the format for ISBN
    BarcodeFormat[BarcodeFormat["CODE_93"] = 4] = "CODE_93";
    BarcodeFormat[BarcodeFormat["CODABAR"] = 8] = "CODABAR";
    BarcodeFormat[BarcodeFormat["DATA_MATRIX"] = 16] = "DATA_MATRIX";
    BarcodeFormat[BarcodeFormat["EAN_13"] = 32] = "EAN_13";
    BarcodeFormat[BarcodeFormat["EAN_8"] = 64] = "EAN_8";
    BarcodeFormat[BarcodeFormat["ITF"] = 128] = "ITF";
    BarcodeFormat[BarcodeFormat["QR_CODE"] = 256] = "QR_CODE";
    BarcodeFormat[BarcodeFormat["UPC_A"] = 512] = "UPC_A";
    BarcodeFormat[BarcodeFormat["UPC_E"] = 1024] = "UPC_E";
    BarcodeFormat[BarcodeFormat["PDF417"] = 2048] = "PDF417";
    BarcodeFormat[BarcodeFormat["AZTEC"] = 4096] = "AZTEC";
})(BarcodeFormat = exports.BarcodeFormat || (exports.BarcodeFormat = {}));
```

B. barcodescanning-common.d.ts
```

export declare enum BarcodeFormat {
    CODE_128 = 1,
    CODE_39 = 2,
    ISBN = 3, // Added the format for ISBN
    CODE_93 = 4,
    CODABAR = 8,
    DATA_MATRIX = 16,
    EAN_13 = 32,
    EAN_8 = 64,
    ITF = 128,
    QR_CODE = 256,
    UPC_A = 512,
    UPC_E = 1024,
    PDF417 = 2048,
    AZTEC = 4096,
}

```
However I was unsuccessful as the results return an empty array [].

Has anyone tried it yet?

Sample image for testing
[Wiki ISBN Image](https://upload.wikimedia.org/wikipedia/commons/2/28/EAN-13-ISBN-13.svg)

**Comment by EddyVerbruggen** [comment]
Hi! If you look at that documentation link again carefully you'll see that `ISBN` is not a type of barcode, but a type of barcode **value**.

I think `ISBN` is an EAN_13, so please set that and scan away!

**Comment by rg777** [comment]
Thanks a lot!!! 
It is working as intended.
Sorry should have looked through the documentation carefully.
