### ISSUE TITLE
Push Notifications with Vue

### ISSUE THREAD

**Issue by kevinjbayer** [EddyVerbruggen/nativescript-plugin-firebase#982]
I have the notifications being received properly from Firebase when the app is open, but nothing when the app is in the background. In my main.js I have

```
firebase.init()
  .then(instance => console.log("firebase.init done"))
  .catch(error => console.log(`firebase.init error: ${error}`));
```

before `new Vue...`

The section [What is iOS doesn't receive notifications in the bg](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/MESSAGING.md#what-if-ios-doesnt-showreceive-notifications-in-the-background) says to require it and take it out of app.ts. How does this correlate to main.js? I'm also still including it like `import * as firebase from "nativescript-plugin-firebase"`.

The notification is being created in a top-level component (to avoid the permission until after logged in) like so:

```
firebase.addOnMessageReceivedCallback(
      function(message) {
        alert({
            title: message.title,
            message: message.body,
            okButtonText: "OK"
          })
          .then(() => {
            console.log("Alert dialog closed.");
          });
      }
    );
```

I'm also not sure if this is the best to show a background notification , but I'm not finding a lot of information on this part right now.

**Comment by EddyVerbruggen** [comment]
Share a repo please and reopen. This kind of issues is impossible to help with unless there’s a project to inspect.

**Comment by EddyVerbruggen** [comment]
UPDATE: the repo was shared and I'm looking into it.

**Comment by kevinjbayer** [comment]
Thanks again, Eddy. Just wanted to confirm here that it's working properly on iOS now. Woo!

**Comment by EddyVerbruggen** [comment]
Excellent!
