### ISSUE TITLE
Application crashes when using arrayUnion from firestore

### ISSUE THREAD

**Issue by zslusnys** [EddyVerbruggen/nativescript-plugin-firebase#985]
Hello Eddy,

I've been trying out the arrayUnion function and it works as in the example of your documentation, however I import firestore in other way - like this:
`import { firestore } from 'nativescript-firebase-plugin'`

and use it like this as it was written in the official documentation of firestore.
ref: [here](https://firebase.google.com/docs/firestore/manage-data/add-data?authuser=0)

`const eventDocRef = await firestore.collection('events').doc(this.eventId)`
`await eventDocRef.update({`
`    participants: firestore.FieldValue.arrayUnion(this.user.id)`
`});`

however if I call the arrayUnion method with a number as a property of that method, the app crashes completely giving me this:

> 10-22 08:46:19.145  8906  8906 F ith.applicatio: java_vm_ext.cc:542]     from java.lang.Object com.tns.Runtime.callJSMethodNative(int, int, java.lang.String, int, boolean, java.lang.Object[])
10-22 08:46:19.145  8906  8906 F ith.applicatio: java_vm_ext.cc:542]   at com.tns.Runtime.callJSMethodNative(Native method)
10-22 08:46:19.145  8906  8906 F ith.applicatio: java_vm_ext.cc:542]   at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
10-22 08:46:19.145  8906  8906 F ith.applicatio: java_vm_ext.cc:542]   at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
10-22 08:46:19.145  8906  8906 F ith.applicatio: java_vm_ext.cc:542]   at com.tns.Runtime.callJSMethod(Runtime.java:983)
10-22 08:46:19.145  8906  8906 F ith.applicatio: java_vm_ext.cc:542]   at com.tns.Runtime.callJSMethod(Runtime.java:967)
10-22 08:46:19.145  8906  8906 F ith.applicatio: java_vm_ext.cc:542]   at com.tns.Runtime.callJSMethod(Runtime.java:959)
10-22 08:46:19.234  8906  8906 F ith.applicatio: runtime.cc:558]   at com.tns.Runtime.callJSMethodNative(Native method)
10-22 08:46:19.234  8906  8906 F ith.applicatio: runtime.cc:558]   at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
10-22 08:46:19.234  8906  8906 F ith.applicatio: runtime.cc:558]   at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
10-22 08:46:19.234  8906  8906 F ith.applicatio: runtime.cc:558]   at com.tns.Runtime.callJSMethod(Runtime.java:983)
10-22 08:46:19.234  8906  8906 F ith.applicatio: runtime.cc:558]   at com.tns.Runtime.callJSMethod(Runtime.java:967)
10-22 08:46:19.234  8906  8906 F ith.applicatio: runtime.cc:558]   at com.tns.Runtime.callJSMethod(Runtime.java:959)
10-22 08:46:19.249  8906  8906 F ith.applicatio: runtime.cc:558]   at com.tns.Runtime.callJSMethodNative(Native method)
10-22 08:46:19.249  8906  8906 F ith.applicatio: runtime.cc:558]   at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
10-22 08:46:19.249  8906  8906 F ith.applicatio: runtime.cc:558]   at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
10-22 08:46:19.249  8906  8906 F ith.applicatio: runtime.cc:558]   at com.tns.Runtime.callJSMethod(Runtime.java:983)
10-22 08:46:19.249  8906  8906 F ith.applicatio: runtime.cc:558]   at com.tns.Runtime.callJSMethod(Runtime.java:967)
10-22 08:46:19.249  8906  8906 F ith.applicatio: runtime.cc:558]   at com.tns.Runtime.callJSMethod(Runtime.java:959)
10-22 08:46:19.249  8906  8906 F ith.applicatio: runtime.cc:566]     from java.lang.Object com.tns.Runtime.callJSMethodNative(int, int, java.lang.String, int, boolean, java.lang.Object[])
10-22 08:46:19.250  8906  8906 F ith.applicatio: runtime.cc:566]   at com.tns.Runtime.callJSMethodNative(Native method)
10-22 08:46:19.250  8906  8906 F ith.applicatio: runtime.cc:566]   at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
10-22 08:46:19.250  8906  8906 F ith.applicatio: runtime.cc:566]   at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
10-22 08:46:19.250  8906  8906 F ith.applicatio: runtime.cc:566]   at com.tns.Runtime.callJSMethod(Runtime.java:983)
10-22 08:46:19.250  8906  8906 F ith.applicatio: runtime.cc:566]   at com.tns.Runtime.callJSMethod(Runtime.java:967)
10-22 08:46:19.250  8906  8906 F ith.applicatio: runtime.cc:566]   at com.tns.Runtime.callJSMethod(Runtime.java:959)

if I pass a list with my wished value, then it works correctly. I'm raising this to talk about the expected results. Should we pass the values as a list or just pass it as properties as in the official documentation? I could make a PR, but I rather talk to you about this first.

**Comment by EddyVerbruggen** [comment]
Hi,

I've just updated the demo to try that.. and this works just fine for me (see the `colors` property):

https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/2ffc70e295c51fa3225db7a0d9dbe151be5611fa/demo-ng/app/tabs/firestore/firestore.component.ts#L233-L243

Where the imports are:

```typescript
import { firestore } from "nativescript-plugin-firebase";
const firebase = require("nativescript-plugin-firebase/app");
```

If this exact same code crashes for you, then look out for plugin version 7.3.0 which contains a version bump of the underlying Firestore Android SDK.

**Comment by zslusnys** [comment]
> Hi,
> 
> I've just updated the demo to try that.. and this works just fine for me (see the `colors` property):
> 
> [nativescript-plugin-firebase/demo-ng/app/tabs/firestore/firestore.component.ts](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/2ffc70e295c51fa3225db7a0d9dbe151be5611fa/demo-ng/app/tabs/firestore/firestore.component.ts#L233-L243)
> 
> Lines 233 to 243 in [2ffc70e](/EddyVerbruggen/nativescript-plugin-firebase/commit/2ffc70e295c51fa3225db7a0d9dbe151be5611fa)
> 
>  firestore.collection("dogs").doc("fave") 
>      .update({ 
>        last: "Updated From 'arrayUnion'", 
>        fieldToDelete: firestore.FieldValue.delete(), 
>        updateTs: firebase.firestore().FieldValue().serverTimestamp(), 
>        // just fyi - both these work: 
>        colors: firestore.FieldValue.arrayUnion(["red", "blue"]) 
>        // colors: firebase.firestore().FieldValue().arrayUnion(["red", "blue"]) 
>      }) 
>      .then(() => console.log("Woofie updated from 'arrayUnion'")) 
>      .catch(err => console.log("Updating Woofie from 'arrayUnion' failed, error: " + JSON.stringify(err))); 
> Where the imports are:
> 
> ```ts
> import { firestore } from "nativescript-plugin-firebase";
> const firebase = require("nativescript-plugin-firebase/app");
> ```
> 
> If this exact same code crashes for you, then look out for plugin version 7.3.0 which contains a version bump of the underlying Firestore Android SDK.

What you did was FieldValue and FieldValue() but what i was intending to point out that if you pass properties (not a list of properties) to arrayUnion method like `firestore.FieldValue.arrayUnion("red", "blue")` then it will crash. In the official documentation it is allowed to pass properties in rather than the list itself.

**Comment by EddyVerbruggen** [comment]
ahhhhhhhhh, that wasn't very clear to me from your issue report. Well, should be easy to fix.

**Comment by zslusnys** [comment]
In addition to that, I've found that when i use ServerTimestamp as you do i get the following error:

>'Error in firebase.firestore.set: Error: java.lang.RuntimeException: No properties to serialize found on class com.google.firebase.firestore.FieldValue$zzd
JS:     com.google.firebase.firestore.g.zzg$zza.<init>(com.google.firebase:firebase-firestore@@17.0.5:643)
JS:     com.google.firebase.firestore.g.zzg.zza(com.google.firebase:firebase-firestore@@17.0.5:331)
JS:     com.google.firebase.firestore.g.zzg.zzb(com.google.firebase:firebase-firestore@@17.0.5:152)
JS:     com.google.firebase.firestore.g.zzg.zzb(com.google.firebase:firebase-firestore@@17.0.5:122)
JS:     com.google.firebase.firestore.g.zzg.zza(com.google.firebase:firebase-firestore@@17.0.5:1085)
JS:     com.google.firebase.firestore.UserDataConverter.convertPOJO(com.google.firebase:firebase-firestore@@17.0.5:437)
JS:     com.google.firebase.firestore.DocumentReference.set(com.google.firebase:firebase-firestore@@17.0.5:165)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
JS:     com.tns.Runtime.callJSMethodImpl...
JS: [Error: java.lang.RuntimeException: No properties to serialize found on class com.google.firebase.firestore.FieldValue$zzd
JS:     com.google.firebase.firestore.g.zzg$zza.<init>(com.google.firebase:firebase-firestore@@17.0.5:643)
JS:     com.google.firebase.firestore.g.zzg.zza(com.google.firebase:firebase-firestore@@17.0.5:331)
JS:     com.google.firebase.firestore.g.zzg.zzb(com.google.firebase:firebase-firestore@@17.0.5:152)
JS:     com.google.firebase.firestore.g.zzg.zzb(com.google.firebase:firebase-firestore@@17.0.5:122)
JS:     com.google.firebase.firestore.g.zzg.zza(com.google.firebase:firebase-firestore@@17.0.5:1085)
JS:     com.google.firebase.firestore.UserDataConverter.convertPOJO(com.google.firebase:firebase-firestore@@17.0.5:437)
JS:     com.google.firebase.firestore.DocumentReference.set(com.google.firebase:firebase-firestore@@17.0.5:165)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
JS:     com.tns.Ru...

**Comment by EddyVerbruggen** [comment]
I can't reproduce that timestamp issue with the latest plugin version, but I did now add support for passing a list of values to `arrayUnion` and `arrayRemove`, just as the web api does. I still support passing an array but it's no longer documented.
