### ISSUE TITLE
Wrong FCM token returned

### ISSUE THREAD

**Issue by JillevdW** [EddyVerbruggen/nativescript-plugin-firebase#986]
The token received in the `addOnPushTokenReceivedCallback` is in the wrong format, and when I try to use it with FCM to send a notification, I get an error message stating: `InvalidRegistration`. After some debugging, I've noticed that the format of the token I receive changed from what I received before.

This happens on iOS, on an iPhone X (physical device) running iOS 12.0.

When I run the exact same app on an iPhone Xs simulator running iOS 12.0, however, the aforementioned function returns the token in the right format again.

Both cases I'm using version 7.1.3 of this plugin.

I'm not sure if this is something that has happened before to anyone, or if it's a known issue; so far I haven't been able to find anything on this. Thanks in advance.

**Comment by EddyVerbruggen** [comment]
Yeah, as a matter of fact I'm looking into this issue today. Btw, on your physical device you should have also received the correct (FCM) token in addition to the incorrect (APNs) token.

**Comment by EddyVerbruggen** [comment]
Can you also confirm you get both tokens in the callback of `addOnPushTokenReceivedCallback`?

**Comment by JillevdW** [comment]
After some extra tests, I am indeed seeing the callback called twice. Once for the FCM ID, and once for the APNs.

**Comment by EddyVerbruggen** [comment]
Cool, then I know what's going on. I recently added support for using this plugin without FCM, so I added some code to get an APNs token as well - but that should obviously not run in case FCM *is* used.

**Comment by slejnej** [comment]
Hi. This issue is still happening. Tried all the "fixes" in issues, but no matter what I do, I get back token like 7468697320697320736f6d6520746f6b656e204920676574206f6e20694f53 instead dAoKxPGjU0U:APA91bFmidcN6esIwtmI6ox4hpVedzFpXIDFZa2kK6y-1...
