### ISSUE TITLE
GoogleService-Info.plist missing error

### ISSUE THREAD

**Issue by waynerobinson** [EddyVerbruggen/nativescript-plugin-firebase#991]
I'm getting a GoogleService-Info.plist missing error on build for iOS however, I'm using this plugin in messaging-only mode ( https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/NON_FIREBASE_MESSAGING.md ) and my understanding is that this mode shouldn't require a config like this.

**Comment by EddyVerbruggen** [comment]
Ah, interesting. Is it more like "... does not exist. Please follow the installation instructions from the documentation"? That originates from a hook script that expects it to exist.

Do you have a Firebase project (for Android)? If so, just download the file (or create a dummy), or wait for me to release a new version without that check.

**Comment by waynerobinson** [comment]
It seems to be an error from the hook:

```
nativescript-plugin-firebase: ~/general-app/App_Resources/iOS/GoogleService-Info.plist does not exist. Please follow the installation instructions from the documentation
Failed to execute hook:  ~/general-app/hooks/before-checkForChanges/firebase-copy-google-services.js.
```

I tried putting in an empty file as substitute, but then that caused XCode compilation errors.

I ended up putting a real config in from Firebase, but I'd prefer it not to have to be there if we're not using it. Although you're right, we will need the config for the Android project.

**Comment by EddyVerbruggen** [comment]
@GlenCroft This issue was for iOS. For Android, you'll need that file otherwise Google Services won't work. Let me update the documentation.
