### ISSUE TITLE
Crashlytics: must Initialize Fabric before using singleton()

### ISSUE THREAD

**Issue by giorgiopiatti** [EddyVerbruggen/nativescript-plugin-firebase#999]
I've enabling the Firebase Crashlytics extension according to the [documentation](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/CRASHREPORTING.md)
but something is not working correcting.  

According to this [https://stackoverflow.com/questions/50782068/why-is-fabric-not-initialized-java-lang-illegalstateexception-must-initialize](https://stackoverflow.com/questions/50782068/why-is-fabric-not-initialized-java-lang-illegalstateexception-must-initialize), we must initialize something but I think that this plugin doesn't handle this. Or is done in the background?

Error stack:
```
System.err: Error: java.lang.IllegalStateException: Must Initialize Fabric before using singleton()

System.err:     io.fabric.sdk.android.Fabric.singleton(Fabric.java:301)

System.err:     io.fabric.sdk.android.Fabric.getKit(Fabric.java:551)
System.err:     com.crashlytics.android.Crashlytics.getInstance(Crashlytics.java:190)
System.err:     com.crashlytics.android.Crashlytics.checkInitialized(Crashlytics.java:373)
System.err:     com.crashlytics.android.Crashlytics.log(Crashlytics.java:232)
```

**Comment by EddyVerbruggen** [comment]
Please share a repo - I've never seen that, and the SO issue you linked to mentions this is not needed when using Firebase.

**Comment by GrEg00z** [comment]
I have the same problem, with Android (didn't try with iOS), while using :
- Nativescript 4.2.4
- tns-core-modules : 4.2.1
- tns android : 4.2.0
- nativescript-plugin-firebase : 7.2.0

Here is my implementation of the method :
```
firebase.init({persist: true, storageBucket: sb}).then((instance) => {

	console.log('firebase.init done');

	if (isAndroid)
		crashlytics.sendCrashLog(new java.lang.Exception("test Exception GG"));

});
```

Did you find a solution for this ?
